/* ==== accounts_core ==== */
"use strict";
/* ============================ ACCOUNTS: paid and social connectors, actuals store, model feedback (module 15) ============================ */
/* Where this runs decides what connects. In the browser app (Chrome or Firefox extension) the page has host permissions and an identity
   API, so OAuth flows and API calls run here with the business's own developer credentials. Opened as a file, pasted tokens work where
   the API allows browser calls (Meta does; most Google APIs do). Inside the Claude viewer only file imports work. Every credential and
   every row of actuals stays in this browser's storage and can be cleared from the module. */
const ACCT = (() => {
  const RT = (typeof globalThis.browser !== 'undefined' && globalThis.browser.runtime && globalThis.browser.runtime.id) ? globalThis.browser : (typeof globalThis.chrome !== 'undefined' && globalThis.chrome.runtime && globalThis.chrome.runtime.id) ? globalThis.chrome : null;
  const ENV = RT ? (typeof globalThis.browser !== 'undefined' && globalThis.browser.runtime && globalThis.browser.runtime.id && navigator.userAgent.includes('Firefox') ? 'firefox' : 'chrome') : inViewer() ? 'viewer' : 'file';
  const KEY = 'tda.accounts.v1';
  /* ---------- storage: extension local storage when present, localStorage otherwise ---------- */
  const kv = {
    async get(k, d) { if (RT && RT.storage) { try { const r = await RT.storage.local.get(k); return r && r[k] !== undefined ? r[k] : d; } catch (e) { return d; } } return store.get(k, d); },
    async set(k, v) { if (RT && RT.storage) { try { await RT.storage.local.set({ [k]: v }); return; } catch (e) { } } store.set(k, v); },
  };
  let S = { cfg: {}, tokens: {}, actuals: {}, settings: { useObserved: false, applied: null, range: 30 }, imports: [] };
  let ready = false; const readyP = kv.get(KEY, null).then(v => { if (v && typeof v === 'object') S = Object.assign(S, v); ready = true; BUS.emit('acct'); });
  const save = () => kv.set(KEY, S).then(() => BUS.emit('acct'));
  /* ---------- providers ---------- */
  const PROVIDERS = {
    google: { name: 'Google', long: 'Google Ads, Local Services Ads, YouTube Analytics, Business Profile', kind: 'oauth', authUrl: 'https://accounts.google.com/o/oauth2/v2/auth', tokenUrl: 'https://oauth2.googleapis.com/token', scopes: ['https://www.googleapis.com/auth/adwords', 'https://www.googleapis.com/auth/yt-analytics.readonly', 'https://www.googleapis.com/auth/youtube.readonly', 'https://www.googleapis.com/auth/business.manage'], pkce: true, secret: true, extra: { access_type: 'offline', prompt: 'consent' },
      fields: [['clientId', 'OAuth client ID (Web application)'], ['clientSecret', 'OAuth client secret'], ['developerToken', 'Google Ads developer token'], ['customerId', 'Google Ads customer ID (digits, no dashes)'], ['loginCustomerId', 'Manager account ID (optional)'], ['gbpLocation', 'Business Profile location ID (optional)']],
      covers: 'Search, Performance Max and Demand Gen campaigns by day and hour, spend and conversions by ZIP (geographic view), phone calls, Local Services leads by job type and charge status, YouTube channel views and subscribers, Business Profile calls and direction requests.',
      setup: ['console.cloud.google.com: create a project, enable the Google Ads API, YouTube Analytics API and Business Profile Performance API.', 'OAuth consent screen: internal or testing, add the account emails as test users.', 'Credentials: OAuth client ID, type Web application; add the redirect URL shown below.', 'ads.google.com manager account: API Center, apply for a developer token (Basic access covers this use; a test token works only on test accounts).', 'Business Profile API access is a separate request form from Google.'] },
    meta: { name: 'Meta', long: 'Marketing API (Facebook and Instagram ads), Page and Instagram insights, Ad Library', kind: 'implicit', authUrl: 'https://www.facebook.com/v21.0/dialog/oauth', scopes: ['ads_read', 'read_insights', 'pages_read_engagement', 'pages_show_list', 'instagram_basic', 'instagram_manage_insights', 'business_management'], pkce: false, secret: false,
      fields: [['appId', 'Meta app ID'], ['adAccountId', 'Ad account ID (act_ followed by digits)'], ['pageId', 'Facebook Page ID'], ['igUserId', 'Instagram business account ID (optional)']],
      covers: 'Campaign spend, impressions, clicks, leads, messages and calls by day and by hour of the advertiser time zone; region and DMA breakdowns (Meta does not break out ZIP); Page reach and engagement; Instagram reach and followers; the Ad Library API for competitor financing ads (module 13).',
      setup: ['developers.facebook.com: create a Business type app; add Marketing API and Facebook Login for Business.', 'Facebook Login settings: add the redirect URL shown below to Valid OAuth Redirect URIs.', 'App review: ads_read and the insights permissions need Advanced Access for accounts outside the app\'s own business; in development mode the app\'s admins, developers and testers can connect now.', 'System user tokens from Business Manager also work: paste one below.'] },
    microsoft: { name: 'Microsoft Advertising', long: 'Bing and Microsoft Audience Network campaigns', kind: 'oauth', authUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize', tokenUrl: 'https://login.microsoftonline.com/common/oauth2/v2.0/token', scopes: ['https://ads.microsoft.com/msads.manage', 'offline_access'], pkce: true, secret: false,
      fields: [['clientId', 'Application (client) ID'], ['developerToken', 'Microsoft Advertising developer token'], ['customerId', 'Customer ID'], ['accountId', 'Account ID']],
      covers: 'Campaign performance by day and hour (spend, impressions, clicks, conversions) through the Reporting REST API; the report arrives as a zipped CSV that the page unpacks.',
      setup: ['portal.azure.com: register an application; platform Single page application (or Mobile and desktop if the token call is refused); add the redirect URL shown below.', 'ads.microsoft.com: Tools, Developer settings, request a developer token (approved for the account\'s user).', 'Customer ID and Account ID are in the Microsoft Advertising URL (cid and aid).'] },
    linkedin: { name: 'LinkedIn', long: 'Campaign Manager ads, Page followers', kind: 'oauth', authUrl: 'https://www.linkedin.com/oauth/v2/authorization', tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken', scopes: ['r_ads', 'r_ads_reporting', 'r_organization_social', 'rw_organization_admin'], pkce: false, secret: true,
      fields: [['clientId', 'Client ID'], ['clientSecret', 'Client secret'], ['adAccountId', 'Sponsored account ID (digits)'], ['organizationId', 'Organization (Page) ID']],
      covers: 'Campaign impressions, clicks, spend and leads by day; Page follower counts. Recruiting and commercial lines only.',
      setup: ['linkedin.com/developers: create an app tied to the company Page; request the Advertising API product (partner review) and Community Management API.', 'Auth tab: add the redirect URL shown below.'] },
  };
  const PORDER = ['google', 'meta', 'microsoft', 'linkedin'];
  const redirectUrl = () => { try { return RT && RT.identity && RT.identity.getRedirectURL ? RT.identity.getRedirectURL() : ''; } catch (e) { return ''; } };
  /* ---------- OAuth ---------- */
  const b64url = buf => btoa(String.fromCharCode(...new Uint8Array(buf))).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
  async function pkce() { const v = b64url(crypto.getRandomValues(new Uint8Array(32))); const c = b64url(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(v))); return { verifier: v, challenge: c }; }
  function cfg(p) { return S.cfg[p] || {}; }
  function tok(p) { return S.tokens[p] || null; }
  const expired = t => !t || !t.access || (t.exp && Date.now() > t.exp - 60e3);
  async function connect(p) {
    const P = PROVIDERS[p], C = cfg(p); if (!RT || !RT.identity) throw new Error('OAuth needs the browser app (Chrome or Firefox extension). Opened as a file, paste a token instead.');
    if (!C.clientId && !C.appId) throw new Error('Enter the client or app ID first.');
    const redirect = redirectUrl(); const state = b64url(crypto.getRandomValues(new Uint8Array(12))); let pk = null;
    const q = new URLSearchParams({ client_id: C.clientId || C.appId, redirect_uri: redirect, state, scope: P.scopes.join(p === 'meta' ? ',' : ' ') });
    if (P.kind === 'implicit') q.set('response_type', 'token'); else { q.set('response_type', 'code'); if (P.pkce) { pk = await pkce(); q.set('code_challenge', pk.challenge); q.set('code_challenge_method', 'S256'); } Object.entries(P.extra || {}).forEach(([k, v]) => q.set(k, v)); }
    const resp = await RT.identity.launchWebAuthFlow({ url: `${P.authUrl}?${q}`, interactive: true });
    const u = new URL(resp); const frag = new URLSearchParams(u.hash.replace(/^#/, '')); const qs = u.searchParams;
    if ((frag.get('state') || qs.get('state')) !== state) throw new Error('State mismatch; try again.');
    if (P.kind === 'implicit') { const access = frag.get('access_token'); if (!access) throw new Error(frag.get('error_description') || qs.get('error_description') || 'No token returned'); S.tokens[p] = { access, exp: Date.now() + (+frag.get('expires_in') || 3600) * 1000, got: Date.now() }; await save(); return S.tokens[p]; }
    const code = qs.get('code'); if (!code) throw new Error(qs.get('error_description') || qs.get('error') || 'No code returned');
    const body = new URLSearchParams({ grant_type: 'authorization_code', code, redirect_uri: redirect, client_id: C.clientId }); if (pk) body.set('code_verifier', pk.verifier); if (P.secret && C.clientSecret) body.set('client_secret', C.clientSecret);
    const r = await fetch(P.tokenUrl, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const j = await r.json(); if (!r.ok || j.error) throw new Error(j.error_description || j.error || 'Token exchange failed');
    S.tokens[p] = { access: j.access_token, refresh: j.refresh_token || (tok(p) || {}).refresh, exp: Date.now() + (+j.expires_in || 3600) * 1000, got: Date.now() }; await save(); return S.tokens[p];
  }
  async function refreshToken(p) { const P = PROVIDERS[p], C = cfg(p), t = tok(p); if (!t || !t.refresh || !P.tokenUrl) return null; const body = new URLSearchParams({ grant_type: 'refresh_token', refresh_token: t.refresh, client_id: C.clientId }); if (P.secret && C.clientSecret) body.set('client_secret', C.clientSecret); const r = await fetch(P.tokenUrl, { method: 'POST', headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body }); const j = await r.json(); if (!r.ok || j.error) throw new Error(j.error_description || 'Token refresh failed'); S.tokens[p] = Object.assign(t, { access: j.access_token, exp: Date.now() + (+j.expires_in || 3600) * 1000, refresh: j.refresh_token || t.refresh }); await save(); return S.tokens[p]; }
  async function access(p) { let t = tok(p); if (expired(t) && t && t.refresh) t = await refreshToken(p); if (expired(t)) throw new Error(`${PROVIDERS[p].name}: not connected or the token expired. Connect again or paste a token.`); return t.access; }
  async function pasteToken(p, access, hours) { S.tokens[p] = { access: String(access || '').trim(), exp: Date.now() + (hours || 1) * 36e5, got: Date.now(), pasted: true }; await save(); }
  async function disconnect(p) { delete S.tokens[p]; await save(); }
  async function setCfg(p, patch) { S.cfg[p] = Object.assign(cfg(p), patch); await save(); }
  /* ---------- API helpers ---------- */
  async function J(url, opt) { const r = await fetch(url, opt); const txt = await r.text(); let j = null; try { j = JSON.parse(txt); } catch (e) { } if (!r.ok) { const msg = j && (j.error && (j.error.message || j.error.error_description) || j.error_description || (Array.isArray(j) && j[0] && j[0].error && j[0].error.message)) || txt.slice(0, 200); throw new Error(`${r.status}: ${msg}`); } return j; }
  const dstr = d => d.toISOString().slice(0, 10); const daysAgo = n => { const d = new Date(); d.setDate(d.getDate() - n); return d; };
  const range = n => ({ since: dstr(daysAgo(n)), until: dstr(new Date()) });
  /* ---------- line mapping ---------- */
  function lineOf(name) { const s = String(name || ''); const m = s.match(/DFW_([A-Z]+)_/); if (m) { const id = m[1].toLowerCase(); if (SLM.LI[id]) return id; if (id === 'b2b') return 'landlord'; if (id === 'blend') return 'replace'; } const t = s.toLowerCase(); const pairs = [[/hail|storm/, 'hail'], [/r-?22|freon/, 'r22'], [/builder|first repl/, 'firstwave'], [/heat ?pump/, 'heatpump'], [/furnace/, 'furnace'], [/heat(ing)?(?! ?pump)|no heat|heater/, 'heat'], [/duct(work| seal| repair)/, 'duct'], [/ductless|mini ?split/, 'ductless'], [/air quality|iaq|purif|filtration/, 'iaq'], [/maint|tune|membership|vip/, 'maint'], [/commercial|rooftop|rtu/, 'commercial'], [/rental|landlord|property manag/, 'landlord'], [/replace|install|new (ac|system)|changeout/, 'replace'], [/repair|emergency|not cooling|ac service/, 'repair'], [/lsa|local services/, 'repair']]; const hit = pairs.find(([re]) => re.test(t)); return hit ? hit[1] : ''; }
  const row = o => Object.assign({ src: '', kind: 'ads', date: '', hour: null, campaign: '', adset: '', geo: null, imp: 0, clicks: 0, spend: 0, leads: 0, calls: 0, conv: 0, msgs: 0, line: '' }, o, { line: o.line || lineOf(o.campaign) });
  /* ---------- Google ---------- */
  async function gaql(query) { const C = cfg('google'); const a = await access('google'); const h = { Authorization: 'Bearer ' + a, 'developer-token': C.developerToken || '', 'Content-Type': 'application/json' }; if (C.loginCustomerId) h['login-customer-id'] = String(C.loginCustomerId).replace(/-/g, ''); const cid = String(C.customerId || '').replace(/-/g, ''); const out = []; let pageToken = null; do { const j = await J(`https://googleads.googleapis.com/v21/customers/${cid}/googleAds:search`, { method: 'POST', headers: h, body: JSON.stringify(Object.assign({ query, pageSize: 10000 }, pageToken ? { pageToken } : {})) }); (j.results || []).forEach(r => out.push(r)); pageToken = j.nextPageToken || null; } while (pageToken && out.length < 50000); return out; }
  async function pullGoogle(n) {
    const R = range(n); const rows = [];
    const camp = await gaql(`SELECT campaign.name, campaign.advertising_channel_type, segments.date, segments.hour, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions, metrics.phone_calls, metrics.all_conversions FROM campaign WHERE segments.date BETWEEN '${R.since}' AND '${R.until}' AND metrics.impressions > 0`);
    camp.forEach(r => rows.push(row({ src: r.campaign.advertisingChannelType === 'LOCAL_SERVICES' ? 'lsa' : 'google', date: r.segments.date, hour: r.segments.hour == null ? null : +r.segments.hour, campaign: r.campaign.name, imp: +r.metrics.impressions || 0, clicks: +r.metrics.clicks || 0, spend: (+r.metrics.costMicros || 0) / 1e6, leads: +r.metrics.conversions || 0, calls: +r.metrics.phoneCalls || 0, conv: +r.metrics.allConversions || 0 })));
    try { const geo = await gaql(`SELECT campaign.name, segments.geo_target_postal_code, segments.date, metrics.impressions, metrics.clicks, metrics.cost_micros, metrics.conversions FROM geographic_view WHERE segments.date BETWEEN '${R.since}' AND '${R.until}' AND metrics.impressions > 0`); const byGid = {}; Z.forEach(z => { if (z.gid) byGid[String(z.gid)] = z.zip; }); geo.forEach(r => { const gid = String(r.segments.geoTargetPostalCode || '').split('/').pop(); rows.push(row({ src: 'google', kind: 'geo', date: r.segments.date, campaign: r.campaign.name, geo: { gid, zip: byGid[gid] || '' }, imp: +r.metrics.impressions || 0, clicks: +r.metrics.clicks || 0, spend: (+r.metrics.costMicros || 0) / 1e6, leads: +r.metrics.conversions || 0 })); }); } catch (e) { rows.push(row({ src: 'google', kind: 'note', campaign: 'geographic_view unavailable: ' + e.message })); }
    try { const leads = await gaql(`SELECT local_services_lead.lead_type, local_services_lead.category_id, local_services_lead.service_id, local_services_lead.lead_status, local_services_lead.creation_date_time, local_services_lead.lead_charged, local_services_lead.locale FROM local_services_lead WHERE local_services_lead.creation_date_time >= '${R.since} 00:00:00'`); leads.forEach(r => { const L = r.localServicesLead; rows.push(row({ src: 'lsa', kind: 'lead', date: String(L.creationDateTime || '').slice(0, 10), hour: +String(L.creationDateTime || '').slice(11, 13), campaign: 'LSA ' + (L.categoryId || ''), adset: L.serviceId || '', leads: 1, calls: L.leadType === 'PHONE_CALL' ? 1 : 0, msgs: L.leadType === 'MESSAGE' ? 1 : 0, conv: L.leadCharged ? 1 : 0, note: L.leadStatus, line: lineOf(L.serviceId || L.categoryId || '') || 'repair' })); }); } catch (e) { rows.push(row({ src: 'lsa', kind: 'note', campaign: 'local_services_lead unavailable: ' + e.message })); }
    S.actuals.google = { fetched: new Date().toISOString(), range: R, rows: rows.filter(r => r.kind !== 'note'), notes: rows.filter(r => r.kind === 'note').map(r => r.campaign) };
    try { const C = cfg('google'); const a = await access('google'); const yt = await J(`https://youtubeanalytics.googleapis.com/v2/reports?ids=channel%3D%3DMINE&startDate=${R.since}&endDate=${R.until}&metrics=views,estimatedMinutesWatched,subscribersGained,likes&dimensions=day&sort=day`, { headers: { Authorization: 'Bearer ' + a } }); const rows2 = (yt.rows || []).map(r => row({ src: 'youtube', kind: 'social', date: r[0], imp: r[1], conv: r[3], msgs: r[4], clicks: 0, campaign: 'YouTube channel' })); S.actuals.youtube = { fetched: new Date().toISOString(), range: R, rows: rows2 }; if (C.gbpLocation) { const st = daysAgo(n), en = new Date(); const q = ['CALL_CLICKS', 'WEBSITE_CLICKS', 'BUSINESS_DIRECTION_REQUESTS', 'BUSINESS_IMPRESSIONS_MOBILE_MAPS', 'BUSINESS_IMPRESSIONS_MOBILE_SEARCH'].map(m => 'dailyMetrics=' + m).join('&'); const g = await J(`https://businessprofileperformance.googleapis.com/v1/locations/${encodeURIComponent(C.gbpLocation)}:fetchMultiDailyMetricsTimeSeries?${q}&dailyRange.start_date.year=${st.getFullYear()}&dailyRange.start_date.month=${st.getMonth() + 1}&dailyRange.start_date.day=${st.getDate()}&dailyRange.end_date.year=${en.getFullYear()}&dailyRange.end_date.month=${en.getMonth() + 1}&dailyRange.end_date.day=${en.getDate()}`, { headers: { Authorization: 'Bearer ' + a } }); const rows3 = []; (g.multiDailyMetricTimeSeries || []).forEach(s => (s.dailyMetricTimeSeries || []).forEach(m => (m.timeSeries && m.timeSeries.datedValues || []).forEach(dv => { const d = dv.date; rows3.push(row({ src: 'gbp', kind: 'social', date: `${d.year}-${String(d.month).padStart(2, '0')}-${String(d.day).padStart(2, '0')}`, campaign: m.dailyMetric, calls: m.dailyMetric === 'CALL_CLICKS' ? +dv.value || 0 : 0, clicks: m.dailyMetric === 'WEBSITE_CLICKS' ? +dv.value || 0 : 0, conv: m.dailyMetric === 'BUSINESS_DIRECTION_REQUESTS' ? +dv.value || 0 : 0, imp: /IMPRESSIONS/.test(m.dailyMetric) ? +dv.value || 0 : 0 })); }))); S.actuals.gbp = { fetched: new Date().toISOString(), range: R, rows: rows3 }; } } catch (e) { S.actuals.google.notes.push('YouTube or Business Profile: ' + e.message); }
    await save(); return S.actuals.google;
  }
  /* ---------- Meta ---------- */
  const metaActs = (acts, types) => sum((acts || []).filter(a => types.includes(a.action_type)).map(a => +a.value || 0));
  async function pullMeta(n) {
    const C = cfg('meta'); const a = await access('meta'); const R = range(n); const act = String(C.adAccountId || '').startsWith('act_') ? C.adAccountId : 'act_' + C.adAccountId; const rows = []; const notes = [];
    const tr = encodeURIComponent(JSON.stringify({ since: R.since, until: R.until })); const F = 'campaign_name,adset_name,spend,impressions,clicks,reach,actions';
    const page = async (u) => { const out = []; let next = u; let g = 0; while (next && g < 20) { const j = await J(next); (j.data || []).forEach(x => out.push(x)); next = j.paging && j.paging.next; g++; } return out; };
    const LEAD = ['lead', 'onsite_conversion.lead_grouped', 'offsite_conversion.fb_pixel_lead', 'onsite_web_lead'], CALL = ['click_to_call_call_confirm', 'onsite_conversion.click_to_call'], MSG = ['onsite_conversion.messaging_conversation_started_7d', 'onsite_conversion.messaging_first_reply'];
    const daily = await page(`https://graph.facebook.com/v21.0/${act}/insights?level=adset&fields=${F}&time_range=${tr}&time_increment=1&limit=500&access_token=${encodeURIComponent(a)}`);
    daily.forEach(x => rows.push(row({ src: 'meta', date: x.date_start, campaign: x.campaign_name, adset: x.adset_name, imp: +x.impressions || 0, clicks: +x.clicks || 0, spend: +x.spend || 0, leads: metaActs(x.actions, LEAD), calls: metaActs(x.actions, CALL), msgs: metaActs(x.actions, MSG), conv: metaActs(x.actions, LEAD) + metaActs(x.actions, CALL) })));
    try { const hourly = await page(`https://graph.facebook.com/v21.0/${act}/insights?level=campaign&fields=campaign_name,spend,impressions,clicks,actions&breakdowns=hourly_stats_aggregated_by_advertiser_time_zone&time_range=${tr}&limit=500&access_token=${encodeURIComponent(a)}`); hourly.forEach(x => rows.push(row({ src: 'meta', kind: 'hour', date: R.until, hour: +String(x.hourly_stats_aggregated_by_advertiser_time_zone || '0').slice(0, 2), campaign: x.campaign_name, imp: +x.impressions || 0, clicks: +x.clicks || 0, spend: +x.spend || 0, leads: metaActs(x.actions, LEAD), calls: metaActs(x.actions, CALL), msgs: metaActs(x.actions, MSG) }))); } catch (e) { notes.push('hourly breakdown: ' + e.message); }
    try { const reg = await page(`https://graph.facebook.com/v21.0/${act}/insights?level=campaign&fields=campaign_name,spend,impressions,clicks,actions&breakdowns=region&time_range=${tr}&limit=500&access_token=${encodeURIComponent(a)}`); reg.forEach(x => rows.push(row({ src: 'meta', kind: 'geo', date: R.until, campaign: x.campaign_name, geo: { region: x.region }, imp: +x.impressions || 0, clicks: +x.clicks || 0, spend: +x.spend || 0, leads: metaActs(x.actions, LEAD) }))); } catch (e) { notes.push('region breakdown: ' + e.message); }
    S.actuals.meta = { fetched: new Date().toISOString(), range: R, rows, notes };
    try { if (C.pageId) { const pg = await J(`https://graph.facebook.com/v21.0/${C.pageId}/insights?metric=page_impressions_unique,page_post_engagements,page_fans&period=day&since=${R.since}&until=${R.until}&access_token=${encodeURIComponent(a)}`); const rows2 = []; (pg.data || []).forEach(m => (m.values || []).forEach(v => rows2.push(row({ src: 'facebook', kind: 'social', date: String(v.end_time).slice(0, 10), campaign: m.name, imp: m.name === 'page_impressions_unique' ? +v.value || 0 : 0, conv: m.name === 'page_post_engagements' ? +v.value || 0 : 0, msgs: m.name === 'page_fans' ? +v.value || 0 : 0 })))); S.actuals.facebook = { fetched: new Date().toISOString(), range: R, rows: rows2 }; } if (C.igUserId) { const ig = await J(`https://graph.facebook.com/v21.0/${C.igUserId}/insights?metric=reach,follower_count&period=day&since=${R.since}&until=${R.until}&access_token=${encodeURIComponent(a)}`); const rows3 = []; (ig.data || []).forEach(m => (m.values || []).forEach(v => rows3.push(row({ src: 'instagram', kind: 'social', date: String(v.end_time).slice(0, 10), campaign: m.name, imp: m.name === 'reach' ? +v.value || 0 : 0, msgs: m.name === 'follower_count' ? +v.value || 0 : 0 })))); S.actuals.instagram = { fetched: new Date().toISOString(), range: R, rows: rows3 }; } } catch (e) { notes.push('Page or Instagram insights: ' + e.message); }
    await save(); return S.actuals.meta;
  }
  /* ---------- Microsoft Advertising (Reporting REST) ---------- */
  async function inflateZipCsv(buf) { const dv = new DataView(buf); let off = 0; const u8 = new Uint8Array(buf); while (off + 30 <= u8.length && dv.getUint32(off, true) === 0x04034b50) { const method = dv.getUint16(off + 8, true), csz = dv.getUint32(off + 18, true), nlen = dv.getUint16(off + 26, true), xlen = dv.getUint16(off + 28, true); const start = off + 30 + nlen + xlen; const data = u8.slice(start, start + csz); if (method === 0) return new TextDecoder().decode(data); if (method === 8 && typeof DecompressionStream !== 'undefined') { const ds = new DecompressionStream('deflate-raw'); const out = await new Response(new Blob([data]).stream().pipeThrough(ds)).text(); return out; } off = start + csz; } throw new Error('Report ZIP could not be read in this browser'); }
  async function pullMicrosoft(n) {
    const C = cfg('microsoft'); const a = await access('microsoft'); const R = range(n); const h = { Authorization: 'Bearer ' + a, DeveloperToken: C.developerToken || '', CustomerId: String(C.customerId || ''), CustomerAccountId: String(C.accountId || ''), 'Content-Type': 'application/json' };
    const d = s => { const [y, m, dd] = s.split('-').map(Number); return { Day: dd, Month: m, Year: y }; };
    const req = { ReportRequest: { Type: 'CampaignPerformanceReportRequest', Format: 'Csv', ReportName: 'atlas', ReturnOnlyCompleteData: false, Aggregation: 'Hourly', Columns: ['TimePeriod', 'CampaignName', 'Impressions', 'Clicks', 'Spend', 'Conversions'], Scope: { AccountIds: [+C.accountId] }, Time: { CustomDateRangeStart: d(R.since), CustomDateRangeEnd: d(R.until) } } };
    const sub = await J('https://reporting.api.bingads.microsoft.com/Reporting/v13/GenerateReport/Submit', { method: 'POST', headers: h, body: JSON.stringify(req) }); const id = sub.ReportRequestId; let url = null;
    for (let i = 0; i < 20 && !url; i++) { await new Promise(r => setTimeout(r, 3000)); const p = await J('https://reporting.api.bingads.microsoft.com/Reporting/v13/GenerateReport/Poll', { method: 'POST', headers: h, body: JSON.stringify({ ReportRequestId: id }) }); const st = p.ReportRequestStatus || {}; if (st.Status === 'Success') url = st.ReportDownloadUrl; if (st.Status === 'Error') throw new Error('Report failed'); }
    if (!url) throw new Error('Report not ready after one minute'); const buf = await (await fetch(url)).arrayBuffer(); const csv = await inflateZipCsv(buf);
    const lines = csv.split(/\r?\n/).filter(l => l && !l.startsWith('"Report') && !l.startsWith('Report')); const hdrI = lines.findIndex(l => /TimePeriod/.test(l)); const H = lines[hdrI].split(',').map(x => x.replace(/"/g, '')); const ix = k => H.indexOf(k); const rows = [];
    lines.slice(hdrI + 1).forEach(l => { const c = l.match(/("([^"]|"")*"|[^,]*)(,|$)/g).map(x => x.replace(/,$/, '').replace(/^"|"$/g, '').replace(/""/g, '"')); if (c.length < H.length || !c[ix('TimePeriod')]) return; const tp = c[ix('TimePeriod')]; rows.push(row({ src: 'microsoft', date: tp.slice(0, 10), hour: /\d{1,2}$/.test(tp) && tp.length > 10 ? +tp.split(/[ |]/).pop() : null, campaign: c[ix('CampaignName')], imp: +c[ix('Impressions')] || 0, clicks: +c[ix('Clicks')] || 0, spend: +c[ix('Spend')] || 0, leads: +c[ix('Conversions')] || 0 })); });
    S.actuals.microsoft = { fetched: new Date().toISOString(), range: R, rows, notes: [] }; await save(); return S.actuals.microsoft;
  }
  /* ---------- LinkedIn ---------- */
  async function pullLinkedIn(n) {
    const C = cfg('linkedin'); const a = await access('linkedin'); const R = range(n); const h = { Authorization: 'Bearer ' + a, 'LinkedIn-Version': '202509', 'X-Restli-Protocol-Version': '2.0.0' };
    const p = s => { const [y, m, d] = s.split('-').map(Number); return `(year:${y},month:${m},day:${d})`; };
    const j = await J(`https://api.linkedin.com/rest/adAnalytics?q=analytics&pivot=CAMPAIGN&timeGranularity=DAILY&dateRange=(start:${p(R.since)},end:${p(R.until)})&accounts=List(urn%3Ali%3AsponsoredAccount%3A${C.adAccountId})&fields=impressions,clicks,costInLocalCurrency,oneClickLeads,externalWebsiteConversions,dateRange,pivotValues`, { headers: h });
    const rows = (j.elements || []).map(e => { const d = e.dateRange && e.dateRange.start; return row({ src: 'linkedin', date: d ? `${d.year}-${String(d.month).padStart(2, '0')}-${String(d.day).padStart(2, '0')}` : R.until, campaign: (e.pivotValues || [])[0] || 'LinkedIn', imp: +e.impressions || 0, clicks: +e.clicks || 0, spend: +e.costInLocalCurrency || 0, leads: (+e.oneClickLeads || 0) + (+e.externalWebsiteConversions || 0), line: 'landlord' }); });
    S.actuals.linkedin = { fetched: new Date().toISOString(), range: R, rows, notes: [] };
    try { if (C.organizationId) { const f = await J(`https://api.linkedin.com/rest/organizationalEntityFollowerStatistics?q=organizationalEntity&organizationalEntity=urn%3Ali%3Aorganization%3A${C.organizationId}`, { headers: h }); const tot = sum((f.elements || []).flatMap(e => (e.followerCountsByAssociationType || []).map(x => (x.followerCounts || {}).organicFollowerCount || 0))); S.actuals.linkedinpage = { fetched: new Date().toISOString(), range: R, rows: [row({ src: 'linkedinpage', kind: 'social', date: R.until, campaign: 'followers', msgs: tot })] }; } } catch (e) { S.actuals.linkedin.notes.push('Page followers: ' + e.message); }
    await save(); return S.actuals.linkedin;
  }
  async function pull(p, n) { n = n || S.settings.range || 30; if (p === 'google') return pullGoogle(n); if (p === 'meta') return pullMeta(n); if (p === 'microsoft') return pullMicrosoft(n); if (p === 'linkedin') return pullLinkedIn(n); throw new Error('Unknown provider'); }
  async function test(p) { const a = await access(p); if (p === 'google') { const j = await J('https://googleads.googleapis.com/v21/customers:listAccessibleCustomers', { headers: { Authorization: 'Bearer ' + a, 'developer-token': cfg('google').developerToken || '' } }); return `Accessible customers: ${(j.resourceNames || []).map(x => x.split('/').pop()).join(', ') || 'none'}`; } if (p === 'meta') { const j = await J(`https://graph.facebook.com/v21.0/me?fields=id,name&access_token=${encodeURIComponent(a)}`); const ac = await J(`https://graph.facebook.com/v21.0/me/adaccounts?fields=account_id,name,account_status&limit=50&access_token=${encodeURIComponent(a)}`).catch(() => ({ data: [] })); return `Connected as ${j.name}; ad accounts: ${(ac.data || []).map(x => `${x.name} (act_${x.account_id})`).join(', ') || 'none visible'}`; } if (p === 'microsoft') { const C = cfg('microsoft'); const j = await J('https://clientcenter.api.bingads.microsoft.com/CustomerManagement/v13/User/Query', { method: 'POST', headers: { Authorization: 'Bearer ' + a, DeveloperToken: C.developerToken || '', 'Content-Type': 'application/json' }, body: JSON.stringify({ UserId: null }) }); return `Connected as ${(j.User || {}).UserName || 'user'}`; } if (p === 'linkedin') { const j = await J(`https://api.linkedin.com/rest/adAccounts?q=search`, { headers: { Authorization: 'Bearer ' + a, 'LinkedIn-Version': '202509', 'X-Restli-Protocol-Version': '2.0.0' } }); return `Ad accounts: ${(j.elements || []).map(e => e.name + ' (' + e.id + ')').join(', ') || 'none'}`; } return 'ok'; }
  /* ---------- file imports ---------- */
  function parseCSV(text) { const rows = []; let r = [], c = '', q = false; const s = String(text || '').replace(/^﻿/, '').replace(/\r/g, ''); for (let i = 0; i < s.length; i++) { const ch = s[i]; if (q) { if (ch === '"') { if (s[i + 1] === '"') { c += '"'; i++; } else q = false; } else c += ch; } else if (ch === '"') q = true; else if (ch === ',') { r.push(c); c = ''; } else if (ch === '\n') { r.push(c); rows.push(r); r = []; c = ''; } else c += ch; } if (c.length || r.length) { r.push(c); rows.push(r); } return rows; }
  const num = v => { const n = parseFloat(String(v == null ? '' : v).replace(/[$,%\s]/g, '').replace(/^--$/, '')); return isN(n) ? n : 0; };
  const dnorm = v => { const s = String(v || '').trim(); let m; if ((m = s.match(/^(\d{4})-(\d{2})-(\d{2})/))) return `${m[1]}-${m[2]}-${m[3]}`; if ((m = s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})/))) return `${m[3]}-${m[1].padStart(2, '0')}-${m[2].padStart(2, '0')}`; const t = Date.parse(s); return isN(t) ? new Date(t).toISOString().slice(0, 10) : ''; };
  const IMPORTERS = [
    { id: 'google-ui', name: 'Google Ads report (UI export)', src: 'google', detect: H => H.includes('campaign') && (H.includes('cost') || H.includes('cost (usd)')) && (H.includes('day') || H.includes('week') || H.includes('month')), map: { date: ['day', 'week', 'month'], hour: ['hour of day', 'hour'], campaign: ['campaign'], adset: ['ad group'], zip: ['postal code', 'user location', 'matched location'], imp: ['impr.', 'impressions'], clicks: ['clicks'], spend: ['cost', 'cost (usd)'], leads: ['conversions', 'conv.'], calls: ['phone calls', 'calls'] } },
    { id: 'meta-ui', name: 'Meta Ads Manager export', src: 'meta', detect: H => H.some(h => h.startsWith('campaign name')) && H.some(h => h.startsWith('amount spent')), map: { date: ['day', 'reporting starts'], hour: ['time of day (ad account time zone)', 'time of day (viewer time zone)'], campaign: ['campaign name'], adset: ['ad set name'], imp: ['impressions'], clicks: ['link clicks', 'clicks (all)'], spend: ['amount spent (usd)', 'amount spent'], leads: ['leads', 'results', 'on-facebook leads', 'website leads'], calls: ['calls', 'call confirmation clicks'], msgs: ['messaging conversations started'] } },
    { id: 'microsoft-ui', name: 'Microsoft Advertising report', src: 'microsoft', detect: H => H.includes('campaignname') || (H.includes('campaign name') && H.includes('spend')), map: { date: ['timeperiod', 'time period', 'gregorian date'], hour: ['hourofday', 'hour of day'], campaign: ['campaignname', 'campaign name'], imp: ['impressions'], clicks: ['clicks'], spend: ['spend'], leads: ['conversions'] } },
    { id: 'lsa', name: 'Local Services Ads leads export', src: 'lsa', detect: H => H.some(h => h.includes('lead')) && (H.includes('job type') || H.includes('lead type')), map: { date: ['created', 'lead creation time', 'date', 'time'], campaign: ['job type', 'category'], leads: [], calls: [], note: ['lead status', 'status'], charged: ['charged', 'lead charged'] }, lead: true },
    { id: 'calls', name: 'Call tracking export (CallRail, CTM)', src: 'calls', detect: H => (H.includes('start time') || H.includes('call start')) && (H.includes('source') || H.includes('tracking number')), map: { date: ['start time', 'call start', 'date'], campaign: ['campaign', 'source', 'tracking number name'], calls: [] }, lead: true, call: true },
    { id: 'generic', name: 'Generic daily spend and leads (Nextdoor, Yelp, TikTok, mailers)', src: 'other', detect: H => H.includes('date') && (H.includes('spend') || H.includes('cost')), map: { date: ['date', 'day'], hour: ['hour'], campaign: ['campaign', 'name', 'source', 'platform'], zip: ['zip', 'postal code'], imp: ['impressions', 'impr'], clicks: ['clicks'], spend: ['spend', 'cost'], leads: ['leads', 'conversions', 'results'], calls: ['calls'] } },
  ];
  function importCSV(text, forceId, srcLabel) {
    const rows = parseCSV(text).filter(r => r.length > 1); if (!rows.length) return { rows: [], note: 'No rows' };
    let hi = rows.findIndex(r => r.filter(Boolean).length >= 3 && r.some(c => /campaign|date|day|spend|cost|lead/i.test(c))); if (hi < 0) hi = 0; const H = rows[hi].map(h => String(h).trim().toLowerCase()); const imp = IMPORTERS.find(i => i.id === forceId) || IMPORTERS.find(i => i.detect(H)); if (!imp) return { rows: [], note: 'Columns not recognized; use a template or pick the format' };
    const col = k => { const cands = imp.map[k] || []; for (const c of cands) { const i = H.indexOf(c); if (i >= 0) return i; } for (const c of cands) { const i = H.findIndex(h => h.startsWith(c)); if (i >= 0) return i; } return -1; };
    const ix = {}; Object.keys(imp.map).forEach(k => ix[k] = col(k)); const g = (r, k) => ix[k] >= 0 ? r[ix[k]] : '';
    const out = []; rows.slice(hi + 1).forEach(r => { if (r.filter(Boolean).length < 2 || /^total/i.test(String(r[0]))) return; const date = dnorm(g(r, 'date')); if (!date) return; const hourRaw = g(r, 'hour'); const hour = hourRaw === '' ? null : (isN(parseInt(hourRaw)) ? parseInt(hourRaw) : null); const zip = String(g(r, 'zip') || '').match(/\b(7[5-6]\d{3})\b/); const o = row({ src: srcLabel || imp.src, kind: imp.lead ? 'lead' : (zip ? 'geo' : 'ads'), date, hour, campaign: g(r, 'campaign') || imp.name, adset: g(r, 'adset') || '', geo: zip ? { zip: zip[1] } : null, imp: num(g(r, 'imp')), clicks: num(g(r, 'clicks')), spend: num(g(r, 'spend')), leads: imp.lead ? 1 : num(g(r, 'leads')), calls: imp.call ? 1 : num(g(r, 'calls')), msgs: num(g(r, 'msgs')), conv: imp.lead ? (/yes|true|charged/i.test(String(g(r, 'charged'))) ? 1 : 0) : 0, note: g(r, 'note') || '' }); if (imp.id === 'lsa') o.line = lineOf(o.campaign) || 'repair'; out.push(o); });
    const key = 'import:' + imp.src; const prev = S.actuals[key] || { rows: [] }; S.actuals[key] = { fetched: new Date().toISOString(), range: { since: out.reduce((m, r) => !m || r.date < m ? r.date : m, ''), until: out.reduce((m, r) => !m || r.date > m ? r.date : m, '') }, rows: prev.rows.concat(out).slice(-40000), notes: [], importer: imp.id }; S.imports.push({ at: new Date().toISOString(), importer: imp.id, n: out.length }); save();
    return { rows: out, note: `${out.length} rows as ${imp.name}`, importer: imp };
  }
  function templateCSV() { return toCSV(['date', 'hour', 'campaign', 'zip', 'impressions', 'clicks', 'spend', 'leads', 'calls'], [['2026-09-20', '17', 'DFW_REPAIR_NEXTDOOR_EN', '75150', 1200, 18, 42.5, 2, 1]], 'Generic import template: one row per day (or hour) per campaign; zip optional. Campaign names that contain the desk token (DFW_REPAIR_, DFW_REPLACE_, ...) map to service lines automatically.'); }
  /* ---------- analytics over actuals ---------- */
  function rowsAll(kind) { return Object.entries(S.actuals).flatMap(([k, a]) => (a.rows || []).map(r => Object.assign({ _src: k }, r))).filter(r => !kind || (Array.isArray(kind) ? kind.includes(r.kind) : r.kind === kind)); }
  const paidRows = () => rowsAll(['ads']).filter(r => r.src !== 'youtube' && r.src !== 'gbp');
  function byLine(days) { const since = dstr(daysAgo(days || S.settings.range || 30)); const out = {}; paidRows().filter(r => r.date >= since && r.hour == null).forEach(r => { const k = r.line || 'unmapped'; const o = out[k] = out[k] || { line: k, spend: 0, imp: 0, clicks: 0, leads: 0, calls: 0, byPlat: {} }; o.spend += r.spend; o.imp += r.imp; o.clicks += r.clicks; o.leads += r.leads; o.calls += r.calls; const p = o.byPlat[r.src] = o.byPlat[r.src] || { spend: 0, clicks: 0, leads: 0, calls: 0, imp: 0 }; p.spend += r.spend; p.clicks += r.clicks; p.leads += r.leads; p.calls += r.calls; p.imp += r.imp; }); rowsAll('lead').filter(r => r.date >= since).forEach(r => { const k = r.line || 'repair'; const o = out[k] = out[k] || { line: k, spend: 0, imp: 0, clicks: 0, leads: 0, calls: 0, byPlat: {} }; o.leads += r.src === 'lsa' ? 1 : 0; o.calls += r.calls; const p = o.byPlat[r.src] = o.byPlat[r.src] || { spend: 0, clicks: 0, leads: 0, calls: 0, imp: 0 }; p.leads += 1; p.calls += r.calls; }); Object.values(out).forEach(o => { const L = o.leads + (o.src === 'lsa' ? 0 : 0); o.cpl = (o.leads + o.calls) ? o.spend / (o.leads + o.calls) : null; o.cpc = o.clicks ? o.spend / o.clicks : null; o.ctr = o.imp ? 100 * o.clicks / o.imp : null; o.cvr = o.clicks ? 100 * (o.leads + o.calls) / o.clicks : null; }); return Object.values(out).sort((a, b) => b.spend - a.spend); }
  function byHour(days) { const since = dstr(daysAgo(days || S.settings.range || 30)); const H = Array.from({ length: 24 }, (_, h) => ({ h, spend: 0, clicks: 0, leads: 0, calls: 0, n: 0 })); rowsAll(['ads', 'hour', 'lead']).filter(r => r.hour != null && r.date >= since).forEach(r => { const o = H[clamp(Math.floor(r.hour), 0, 23)]; o.spend += r.spend; o.clicks += r.clicks; o.leads += r.leads; o.calls += r.calls; o.n++; }); const tot = sum(H.map(x => x.spend)) || 1, totL = sum(H.map(x => x.leads + x.calls)) || 1; H.forEach(x => { x.spendSh = 100 * x.spend / tot; x.leadSh = 100 * (x.leads + x.calls) / totL; x.cpl = (x.leads + x.calls) ? x.spend / (x.leads + x.calls) : null; }); return H; }
  function observedGrid() { const H = byHour(90); if (!H.some(x => x.n)) return null; const blocks = [[0, 6], [6, 9], [9, 12], [12, 17], [17, 21], [21, 24]]; const mean = sum(H.map(x => x.leadSh)) / 24; const g = blocks.map(([a, b]) => { const sh = sum(H.slice(a, b).map(x => x.leadSh)) / (b - a); return clamp(Math.round(((sh / (mean || 1)) - 1) * 100 / 5) * 5, -50, 60); }); return [0, 1, 2, 3, 4, 5, 6].map(() => g.slice()); }
  function byZip(days) { const since = dstr(daysAgo(days || S.settings.range || 90)); const out = {}; rowsAll('geo').filter(r => r.geo && r.geo.zip && r.date >= since).forEach(r => { const o = out[r.geo.zip] = out[r.geo.zip] || { zip: r.geo.zip, spend: 0, clicks: 0, leads: 0, imp: 0 }; o.spend += r.spend; o.clicks += r.clicks; o.leads += r.leads; o.imp += r.imp; }); Object.values(out).forEach(o => { o.cpl = o.leads ? o.spend / o.leads : null; o.z = ZI[o.zip] || null; }); return Object.values(out).sort((a, b) => b.spend - a.spend); }
  function pacing(planBudget) { const now = new Date(); const m0 = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-01`; const dim = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const day = now.getDate(); const rows = paidRows().filter(r => r.date >= m0 && r.hour == null); const spend = sum(rows.map(r => r.spend)); const bySrc = {}; rows.forEach(r => bySrc[r.src] = (bySrc[r.src] || 0) + r.spend); const days = [...new Set(rows.map(r => r.date))].length; return { spend, bySrc, days, day, dim, rate: days ? spend / days : 0, projected: days ? spend / days * dim : 0, plan: planBudget || null, onPace: planBudget ? spend / (planBudget * day / dim) : null }; }
  function social(days) { const since = dstr(daysAgo(days || 90)); const out = {}; rowsAll('social').filter(r => r.date >= since).forEach(r => { (out[r.src] = out[r.src] || []).push(r); }); return out; }
  /* ---------- feed the models ---------- */
  function applyToModels() { const bl = byLine(90); const paid = paidRows().filter(r => r.src === 'google' || r.src === 'microsoft'); const cpc = sum(paid.map(r => r.spend)) / Math.max(1, sum(paid.map(r => r.clicks))); const prev = { cpc: SLM.A.cpc, lines: JSON.parse(JSON.stringify(SLM.A.lines)) }; const patch = { lines: {} }; if (isN(cpc) && cpc > 0.2) patch.cpc = +cpc.toFixed(2); bl.forEach(o => { if (!SLM.LI[o.line]) return; const L = {}; const g = o.byPlat.google; if (g && g.clicks >= 50 && (g.leads + g.calls) >= 3) L.cvr = +(100 * (g.leads + g.calls) / g.clicks).toFixed(1); const m = o.byPlat.meta; if (m && (m.leads + m.calls) >= 3) L.metaCpl = Math.round(m.spend / (m.leads + m.calls)); const l = o.byPlat.lsa; if (l && l.leads >= 3 && l.spend > 0) L.lsaCpl = Math.round(l.spend / l.leads); if (Object.keys(L).length) patch.lines[o.line] = L; }); S.settings.applied = { at: new Date().toISOString(), prev, patch }; SLM.set(patch); save(); return patch; }
  function revertModels() { const a = S.settings.applied; if (!a) return; SLM.set({ cpc: a.prev.cpc, lines: a.prev.lines }); S.settings.applied = null; save(); }
  async function clearAll(what) { if (what === 'tokens' || !what) S.tokens = {}; if (what === 'actuals' || !what) { S.actuals = {}; S.imports = []; } if (what === 'cfg') S.cfg = {}; await save(); }
  function status(p) { const t = tok(p), C = cfg(p); const P = PROVIDERS[p]; const configured = P.fields.slice(0, 1).every(([k]) => C[k]); if (!configured && !t) return { state: 'unconfigured', label: 'Not configured' }; if (!t) return { state: 'configured', label: 'Configured, not connected' }; if (expired(t) && !t.refresh) return { state: 'expired', label: 'Token expired' }; return { state: 'connected', label: (t.pasted ? 'Token pasted' : 'Connected') + (t.exp ? ' · expires ' + new Date(t.exp).toLocaleString() : '') }; }
  async function requestHosts() { if (!RT || !RT.permissions) return false; const origins = ['https://api.weather.gov/*', 'https://www.spc.noaa.gov/*', 'https://graph.facebook.com/*', 'https://www.facebook.com/*', 'https://googleads.googleapis.com/*', 'https://oauth2.googleapis.com/*', 'https://youtubeanalytics.googleapis.com/*', 'https://businessprofileperformance.googleapis.com/*', 'https://api.linkedin.com/*', 'https://www.linkedin.com/*', 'https://login.microsoftonline.com/*', 'https://*.api.bingads.microsoft.com/*', 'https://*.integrityairconditioning.com/*']; try { return await RT.permissions.request({ origins }); } catch (e) { return false; } }
  async function hostsGranted() { if (!RT || !RT.permissions) return null; try { return await RT.permissions.contains({ origins: ['https://api.weather.gov/*', 'https://graph.facebook.com/*'] }); } catch (e) { return null; } }
  return { ENV, RT, PROVIDERS, PORDER, IMPORTERS, get S() { return S; }, ready: () => readyP, isReady: () => ready, cfg, tok, status, setCfg, connect, pasteToken, disconnect, test, pull, importCSV, templateCSV, redirectUrl, rowsAll, byLine, byHour, observedGrid, byZip, pacing, social, applyToModels, revertModels, clearAll, lineOf, settings: () => S.settings, setSettings: p => { Object.assign(S.settings, p); return save(); }, requestHosts, hostsGranted, range };
})();
