'use strict';
/* Module 01: Dissolution Index. This file also holds what the statewide and metro modules share: the county layer catalog (LAYERS_CTY,
   each layer with its group, direction, grade and a note for the legend), the map decorations (the firm's service counties, dimming,
   the firm's offices and the watched firms as pins) and the index's own checks (equal weights, the composite without its filing
   component against outcomes it was not built from, the year to date test it fails, and the three way count of divorces).
   The pure helpers (idx*) run in node too: tests/index.test.mjs checks them against the data. */
const IDX_COMP = [['filing', 'Filing intensity'], ['haz', 'Composition hazard'], ['sep', 'Separation'], ['econ', 'Economic shock'], ['struct', 'Family structure'], ['strain', 'Financial strain'], ['supply', 'Supply gap']];
const IDX_FLOOR = 1000;   // married adults: below this one filing moves a county's rate by a full point per 1,000 or more
// the composite as the data builds it: a weighted mean of the component percentiles a county has (the weights of the missing ones drop
// out), optionally without one component
function idxComposite(c, w, drop) { let s = 0, d = 0; Object.keys(w || {}).forEach(k => { if (k === drop || !c || !c.pct || !isN(c.pct[k]) || !(w[k] > 0)) return; s += w[k] * c.pct[k]; d += w[k]; }); return d ? s / d : null; }
const IDX_EQW = (() => { const o = {}; Object.keys(D.weights || {}).forEach(k => { o[k] = 1; }); return o; })();
function idxEqual(c) { return idxComposite(c, IDX_EQW); }
// the mean and standard deviation of each raw component (c.comp_<key>) across the counties that have it; idxZ is a county's distance from
// that mean in standard deviations, positive where the component adds to the index
function idxZStats(rows) { const S = SEV_STATS, o = {}; IDX_COMP.forEach(([k]) => { const v = rows.map(c => c['comp_' + k]); o[k] = { m: S.mean(v), s: S.sd(v), n: v.filter(isN).length }; }); return o; }
function idxZ(c, k, zs) { const v = c && c['comp_' + k], z = zs && zs[k]; return isN(v) && z && z.s ? (v - z.m) / z.s : null; }
// the 90th percentile of the threshold measures among counties at or above the married floor (the callouts' cut points)
function idxThresholds(rows) {
  const ok = rows.filter(c => (c.acs.married || 0) >= IDX_FLOOR); const q = f => SEV_STATS.quantile(ok.map(f), 0.9);
  return { n: ok.length, sep: q(c => c.acs.sep_per_1k_married), dur59: q(c => c.risk.dur_5_9), rem: q(c => c.risk.remarried), m55: q(c => c.acs.mar_55p_sh), mil: q(c => c.risk.mil_active), po: q(c => c.rates.po_per_10k), fpo: q(c => c.rates.filings_per_lawoffice) };
}
// a county's place on the two paid percentiles, as module 07 places a ZIP: opportunity is private family filings, room is filings per law
// office (the supply component); both at 50 or above is prime, room alone a niche, opportunity alone contested, neither thin
function idxQuad(c, oppPct) { const e = c.pct ? c.pct.supply : null; if (!isN(e)) return { q: 'No law office counted', t: 'The Census counts no law office with a payroll in this county (CBP 2023), so it has no filings per office to rank.' }; const o = oppPct(c.filings.ttm.priv) * 100; const q = e >= 50 ? (o >= 50 ? 'Prime' : 'Niche') : (o >= 50 ? 'Contested' : 'Thin'); return { q, o, e, t: `Opportunity percentile ${N(o, 0)} (private family filings), room percentile ${N(e, 0)} (filings per law office). Prime: both 50 or above; Niche: room only; Contested: opportunity only; Thin: neither.` }; }
const idxR = (x, y) => { const S = SEV_STATS; const p = S.pearson(x, y), s = S.spearman(x, y); return { r: p.r, lo: p.lo, hi: p.hi, p: p.p, n: p.n, rho: s.rho, prho: s.p }; };
// the checks: equal weights, the composite without filings against two outcomes it was not built from (grade A and B counties), and the
// out of time test against the 2026 year to date change (counties with monthly reports, no reporting gap, 50 or more filings a year
// earlier). Each verdict follows from its numbers.
function idxValidate(rows) {
  const W = D.weights; const out = {};
  const di = rows.map(c => c.di), eq = rows.map(idxEqual); out.eq = idxR(di, eq);
  const rk = a => { const ix = a.map((v, i) => i).sort((i, j) => (a[j] == null ? -1e9 : a[j]) - (a[i] == null ? -1e9 : a[i])); const r = new Array(a.length); ix.forEach((i, n) => { r[i] = n + 1; }); return r; };
  const r1 = rk(di), r2 = rk(eq); out.movers = rows.map((c, i) => ({ fips: c.fips, name: c.name, from: r1[i], to: r2[i], d: r1[i] - r2[i] })).sort((a, b) => Math.abs(b.d) - Math.abs(a.d)).slice(0, 5);
  const AB = rows.filter(c => c.grade === 'A' || c.grade === 'B'); const nf = AB.map(c => idxComposite(c, W, 'filing'));
  out.ab = AB.map(c => c.fips); out.filing = idxR(nf, AB.map(c => c.rates.div_per_1k_married)); out.hazobs = idxR(nf, AB.map(c => c.risk.haz_obs));
  out.diFiling = idxR(AB.map(c => c.di), AB.map(c => c.rates.div_per_1k_married));
  const Y = rows.filter(c => c.filings.ytd26 && c.filings.ytd25 && (c.filings.ytd25.f_div || 0) >= 50 && !repGap(c)); const ch = Y.map(c => c.filings.ytd26.f_div / c.filings.ytd25.f_div - 1);
  out.ytd = { fips: Y.map(c => c.fips), ch, di: idxR(Y.map(c => c.di), ch), nf: idxR(Y.map(c => idxComposite(c, W, 'filing')), ch), esi: idxR(Y.map(c => c.esi), ch), lift: idxR(Y.map(c => c.econ && c.econ.expected ? c.econ.expected.m12_pct : null), ch), months: (ST.annual['2026'] || {}).months || null, up: ch.filter(v => v > 0).length };
  const verdict = (t, strong) => !isN(t.r) ? 'no data' : t.p < 0.05 && t.r >= (strong || 0.5) ? 'holds' : t.p < 0.05 && t.r > 0 ? 'weak' : 'fails';
  out.v = { eq: isN(out.eq.r) && out.eq.r >= 0.9 ? 'holds' : 'fails', filing: verdict(out.filing), hazobs: verdict(out.hazobs), ytdDi: verdict(out.ytd.di), ytdNf: verdict(out.ytd.nf) };
  return out;
}
// the three counts of divorces for an area: court filings and dispositions (OCA, the NCHS year and the latest full year), Texans who
// report a divorce in the past year (PUMS; two spouses per divorce), and the NCHS Texas rate applied to the ACS population
function idxSanity(cs, isState) {
  const nys = Object.keys(ST.nchs.divorce).sort(); const yr = nys[nys.length - 1]; const full = Object.keys(ST.annual).filter(y => (ST.annual[y].months || 12) === 12).sort(); const last = full[full.length - 1];
  const oca = y => isState ? { f: ST.annual[y].f_div, d: ST.annual[y].d_div } : { f: sum(cs.map(c => (c.filings.hist[y] || {}).div || 0)), d: sum(cs.map(c => (c.filings.hist[y] || {}).d_div || 0)) };
  const persons = isState ? D.pums.div_ly_w : sum(cs.map(c => c.pools.div_ly_all_w || 0)); const pop = isState ? ST.acs.pop : sum(cs.map(c => c.acs.pop || 0)); const rate = ST.nchs.divorce[yr];
  return { yr, last, oca: oca(yr), ocaLast: oca(last), persons, pums: persons / 2, pop, rate, nchs: rate * pop / 1000, n: cs.length };
}
/* ---- the county layer catalog: one entry per layer, grouped; dir 1 means a higher value adds to the reading, 0 a diverging change */
const IDX_GROUPS = ['Index', 'Filings', 'Marriage stock', 'Family structure', 'Strain', 'Economic shock', 'Supply', 'Context'];
const LAYERS_CTY = {
  di: { l: 'Dissolution Index (composite, percentile)', grp: 'Index', dir: 1, g: 'B', ramp: 'ember', v: c => c.di, f: v => N(v, 0), q: false, note: 'The weighted mean of the seven component percentiles. A percentile scale: 100 is the top of Texas, not 100% of anything.' },
  di_eq: { l: 'Dissolution Index, equal weights (percentile)', grp: 'Index', dir: 1, g: 'B', ramp: 'ember', v: c => idxEqual(c), f: v => N(v, 0), q: false, note: 'The same seven components with every weight equal: the sensitivity check for the weights (the method card gives r and Spearman against the index).' },
  di_nf: { l: 'Index without the filing component (percentile mean)', grp: 'Index', dir: 1, g: 'B', ramp: 'ember', v: c => idxComposite(c, D.weights, 'filing'), f: v => N(v, 0), q: false, note: 'The six components that are not court counts, reweighted. The validation panel tests it against the filing rate it never saw.' },
  filing: { l: 'Divorce filings per 1,000 married adults (trailing 12 months)', grp: 'Filings', dir: 1, g: 'A', ramp: 'ember', v: c => c.rates.div_per_1k_married, f: v => N(v, 1), note: 'Office of Court Administration filings over ACS married adults. Under 1,000 married adults a single filing moves the rate a full point.' },
  filing10k: { l: 'Divorce filings per 10,000 residents', grp: 'Filings', dir: 1, g: 'A', ramp: 'ember', v: c => c.rates.div_per_10k_pop, f: v => N(v, 1), note: 'Filings over the Census Vintage 2025 population: a rate that ignores how many residents are married.' },
  yoy: { l: 'Divorce filings, change vs prior 12 months', grp: 'Filings', dir: 0, g: 'A', ramp: 'div', v: c => c.rates.div_yoy, f: v => sgn(v, 1), note: 'The trailing twelve months against the twelve before. A clerk who stopped reporting shows as a steep fall; the county detail flags it.' },
  vs2019: { l: 'Divorce filings, change vs 2019', grp: 'Filings', dir: 0, g: 'A', ramp: 'div', v: c => c.rates.div_vs_2019, f: v => sgn(v, 1), note: 'The trailing twelve months against calendar 2019, the last year before the pandemic.' },
  divk: { l: 'Share of divorce filings with children', grp: 'Filings', dir: 1, g: 'A', ramp: 'ember', v: c => c.rates.div_k_share, f: v => P(v, 0), note: 'Divorces with minor children carry conservatorship, possession and child support (Family Code ch. 153 and 154).' },
  sapcr: { l: 'Custody suits (SAPCR) per 10,000 residents', grp: 'Filings', dir: 1, g: 'A', ramp: 'ember', v: c => isN(c.filings.ttm.sapcr) && c.pop2025 ? c.filings.ttm.sapcr / c.pop2025 * 1e4 : null, f: v => N(v, 1), note: 'Suits affecting the parent child relationship filed without a divorce, trailing twelve months.' },
  po: { l: 'Protective order filings per 10,000 residents', grp: 'Filings', dir: 1, g: 'A', ramp: 'ember', v: c => c.rates.po_per_10k, f: v => N(v, 1), note: 'Protective order applications under Family Code Title 4, trailing twelve months.' },
  haz: { l: 'Composition hazard: modeled divorces per 1,000 married (PUMS model)', grp: 'Marriage stock', dir: 1, g: 'B', ramp: 'ember', v: c => c.risk.haz_pred, f: v => N(v, 1), note: 'The Texas microdata model applied to who is married here (age, years married, marriage order, schooling, service, age at marriage). It describes the county\'s married population, never a couple.' },
  hazobs: { l: 'Observed divorces per 1,000 married (PUMS, 2020 to 2024)', grp: 'Marriage stock', dir: 1, g: 'C', ramp: 'ember', v: c => c.risk.haz_obs, f: v => N(v, 1), note: 'Texans who report a divorce in the past year, from the survey areas covering the county. Counties under about 100,000 residents share a survey area with neighbors, so this is regional.' },
  sep: { l: 'Separated adults per 1,000 married (ACS)', grp: 'Marriage stock', dir: 1, g: 'B', ramp: 'ember', v: c => c.acs.sep_per_1k_married, f: v => N(v, 1), note: 'Texas has no legal separation, so most separations end in a filing. A survey estimate: small counties carry wide margins, which the index shrinks.' },
  dur59: { l: 'Married 5 to 9 years, the peak hazard band (share, PUMS)', grp: 'Marriage stock', dir: 1, g: 'B', ramp: 'ember', v: c => c.risk.dur_5_9, f: v => P(v, 0), note: 'Years five to nine of a marriage carry the highest divorce hazard after the first year in the Texas microdata.' },
  rem: { l: 'Remarried, second or later marriage (share, PUMS)', grp: 'Marriage stock', dir: 1, g: 'B', ramp: 'ember', v: c => c.risk.remarried, f: v => P(v, 0), note: 'Second and later marriages carry higher odds of divorce in the hazard model; blended family custody and modification work follow.' },
  m55: { l: 'Married adults 55 and over (share of married, ACS)', grp: 'Marriage stock', dir: 1, g: 'A', ramp: 'slate', v: c => c.acs.mar_55p_sh, f: v => P(v, 0), note: 'The gray divorce pool: retirement division and spousal maintenance questions (Family Code ch. 8).' },
  struct: { l: 'Family structure component (z score)', grp: 'Family structure', dir: 1, g: 'B', ramp: 'amber', v: c => c.comp_struct, f: v => N(v, 2), note: 'Married with children, cohabiting with children, unmarried births, single parents, grandparents responsible and married 25 to 44, standardized and averaged.' },
  kids: { l: 'Married couple families with children (share, ACS)', grp: 'Family structure', dir: 1, g: 'A', ramp: 'amber', v: c => c.acs.mc_kids_sh, f: v => P(v, 0), note: 'Where a divorce turns into a custody case.' },
  cohab: { l: 'Cohabiting couples with children (share of couples with kids)', grp: 'Family structure', dir: 1, g: 'A', ramp: 'amber', v: c => c.acs.cohab_kids_sh, f: v => P(v, 0), note: 'Not a divorce pool, a custody pool: these households end in SAPCR suits, paternity and support orders.' },
  unmar: { l: 'Births to unmarried mothers (share of births)', grp: 'Family structure', dir: 1, g: 'A', ramp: 'amber', v: c => c.acs.births_unmar_sh, f: v => P(v, 0), note: 'Feeds paternity, Title IV-D and custody filings in later years.' },
  strain: { l: 'Financial strain component (z score)', grp: 'Strain', dir: 1, g: 'B', ramp: 'amber', v: c => c.comp_strain, f: v => N(v, 2), note: 'Rent and mortgage burden, SNAP, married with children in poverty and households under $35,000, standardized and averaged.' },
  rentb: { l: 'Renters paying 35% or more of income on rent (ACS)', grp: 'Strain', dir: 1, g: 'A', ramp: 'amber', v: c => c.acs.rent_burden35_sh, f: v => P(v, 0), note: 'Strain provokes conflict and also blocks a filing that needs two households.' },
  snap: { l: 'Households receiving SNAP (ACS)', grp: 'Strain', dir: 1, g: 'A', ramp: 'amber', v: c => c.acs.snap_sh, f: v => P(v, 0), note: 'Tracks fee sensitivity and Title IV-D rather than private representation.' },
  esi: { l: 'Economic Shock Index (percentile)', grp: 'Economic shock', dir: 1, g: 'B', ramp: 'steel', v: c => c.esi, f: v => N(v, 0), note: 'Claims, unemployment, WARN notices and payrolls against each county\'s own 2019 baseline, ranked. A percentile: a fifth of counties always sit at 80 or above.' },
  urchg: { l: 'Unemployment rate change vs a year earlier (points)', grp: 'Economic shock', dir: 0, g: 'A', ramp: 'div', v: c => c.econ.ur_chg_yoy, f: v => sgn(v, 1, ' pts'), note: 'BLS LAUS, latest month against the same month a year earlier.' },
  c19: { l: 'UI initial claims, last 13 weeks vs the same weeks of 2019 (ratio)', grp: 'Economic shock', dir: 1, g: 'A', ramp: 'steel', v: c => c.econ.claims_vs_2019, f: v => isN(v) ? N(v, 2) + '×' : NA, note: 'Texas Workforce Commission weekly claims. A county with no claims in the 2019 weeks has no ratio.' },
  supply: { l: 'Private family filings per law office (competition gap)', grp: 'Supply', dir: 1, g: 'C', ramp: 'moss', v: c => c.rates.filings_per_lawoffice, f: v => N(v, 1), note: 'All offices of lawyers stand in for family law offices (CBP 2023 counts only offices with a payroll), so cities with corporate firms look more crowded than they are.' },
  off10k: { l: 'Law offices per 10,000 residents (CBP 2023)', grp: 'Supply', dir: 1, g: 'A', ramp: 'slate', v: c => c.rates.lawoffices ? c.rates.lawoffices / c.pop2025 * 1e4 : null, f: v => N(v, 2), note: 'Counties with no law office with a payroll show as no data.' },
  pop: { l: 'Population 2025', grp: 'Context', dir: 1, g: 'A', ramp: 'slate', v: c => c.pop2025, f: v => K(v), log: true, note: 'Census Vintage 2025 estimates.' },
  married: { l: 'Married adults (ACS, spouse present)', grp: 'Context', dir: 1, g: 'A', ramp: 'slate', v: c => c.acs.married, f: v => K(v), log: true, note: 'ACS 2020 to 2024. The denominator of every rate per 1,000 married.' },
  inc: { l: 'Median household income (ACS)', grp: 'Context', dir: 1, g: 'A', ramp: 'moss', v: c => c.acs.med_hh_inc, f: v => $$$(v), note: 'Ability to pay is left out of the index on purpose; modules 06 and 07 bring it in.' }
};
function idxLayerOptions(keys, cur) { const grp = k => (LAYERS_CTY[k] || {}).grp || 'Other'; return [...new Set(keys.map(grp))].sort((a, b) => IDX_GROUPS.indexOf(a) - IDX_GROUPS.indexOf(b)).map(g => `<optgroup label="${esc(g)}">${keys.filter(k => grp(k) === g).map(k => `<option value="${esc(k)}"${k === cur ? ' selected' : ''}>${esc(LAYERS_CTY[k].l)}</option>`).join('')}</optgroup>`).join(''); }
// the legend's second line: which way the ramp reads, the grade, the note, and what the pale and dashed counties are
function idxLegendNote(L, extra) { const dir = L.dir === 0 || L.ramp === 'div' || L.ramp === 'divinv' ? 'Above zero runs to the green end of the ramp, below zero to the slate end.' : L.dir === -1 ? 'Lower values sit toward the right end of the ramp.' : 'Higher values sit toward the right end of the ramp.'; return `<div class="ix-legnote"><span class="grade ${esc(L.g || 'C')}" title="Confidence grade ${esc(L.g || 'C')}">${esc(L.g || 'C')}</span> <b>${esc(dir)}</b> ${esc(L.note || '')}${extra || ''}</div>`; }
function layerScale(L, objs) {
  const vals = objs.map(L.v);
  // the color scale stops at the 2nd and 98th percentiles (97th for diverging layers); a legend end that is a stop, not the real
  // minimum or maximum, reads '≤' or '≥'
  const ok = vals.filter(isN);
  // diverging legends print their ends in the layer's own unit (points stay points, percents stay percents)
  if (L.ramp === 'div' || L.ramp === 'divinv') { const inv = L.ramp === 'divinv' ? -1 : 1; const mx = Math.max(...ok.map(Math.abs).sort((a, b) => a - b).slice(0, Math.floor(vals.length * 0.97)), 1); const neg = inv > 0 ? RAMPS.slate : RAMPS.leaf, pos = inv > 0 ? RAMPS.leaf : RAMPS.slate; const lf = L.lf || L.f || (v => sgn(v, 0)); return { color: v => divergeColor(inv * clamp(v / mx, -1, 1)), legend: { min: (ok.some(v => v < -mx) ? '≤ ' : '') + lf(-mx), max: (ok.some(v => v > mx) ? '≥ ' : '') + lf(mx), css: `linear-gradient(90deg,${neg[7]},${neg[4]},var(--rp-mid),${pos[4]},${pos[7]})` } }; }
  // a log layer colors a true zero with the lowest step (a map can give zero its own class with drawMap's alt); its legend runs over the values above zero
  const sc = L.log ? (() => { const q = quantScale(vals.map(v => isN(v) && v > 0 ? Math.log(v) : null)); return v => v > 0 ? q(Math.log(v)) : 0; })() : (L.q === false ? (v => clamp(v / 100, 0, 1)) : quantScale(vals));
  const sorted = (L.log ? ok.filter(v => v > 0) : ok).slice().sort((a, b) => a - b); if (!sorted.length) return { color: () => null, legend: { min: NA, max: NA, css: rampCSS(L.ramp) } };
  const pick = p => sorted[clamp(Math.floor(p * (sorted.length - 1)), 0, sorted.length - 1)];
  const lo = L.q === false ? 0 : pick(0.02), hi = L.q === false ? 100 : pick(0.98);
  const lo_c = L.q !== false && sorted[0] < lo, hi_c = L.q !== false && sorted[sorted.length - 1] > hi;
  return { color: v => rampColor(L.ramp, sc(v)), legend: { min: (lo_c ? '≤ ' : '') + L.f(lo), max: (hi_c ? '≥ ' : '') + L.f(hi), css: rampCSS(L.ramp) } };
}
// the map view of a metro: its counties' extent in state map units, padded, at the state map's shape so the map keeps its size
const IDX_BOX = {};
function metroBox(code) {
  if (IDX_BOX[code]) return IDX_BOX[code]; const G = GEO.state; let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  ((MSA[code] || {}).counties || []).forEach(f => { const n = (G.county[f] || '').match(/-?\d+(?:\.\d+)?/g) || []; for (let i = 0; i + 1 < n.length; i += 2) { const x = +n[i], y = +n[i + 1]; if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; } });
  if (!isFinite(x0)) return null; let w = x1 - x0, h = y1 - y0; const pad = Math.max(w, h) * 0.08 + 6; x0 -= pad; y0 -= pad; w += 2 * pad; h += 2 * pad;
  const asp = G.W / G.H; if (w / h < asp) { const nw = h * asp; x0 -= (nw - w) / 2; w = nw; } else { const nh = w / asp; y0 -= (nh - h) / 2; h = nh; }
  return (IDX_BOX[code] = [x0, y0, w, h]);
}
// the extent of a set of path strings (map units), padded, at a map's shape: the view drawMap zooms to
function ixBox(ds, W, H, padF) {
  let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  ds.forEach(d => { const n = String(d || '').match(/-?\d+(?:\.\d+)?/g) || []; for (let i = 0; i + 1 < n.length; i += 2) { const x = +n[i], y = +n[i + 1]; if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; } });
  if (!isFinite(x0)) return null; let w = x1 - x0, h = y1 - y0; const pad = Math.max(w, h) * (padF == null ? 0.08 : padF) + 4; x0 -= pad; y0 -= pad; w += 2 * pad; h += 2 * pad;
  const asp = W / H; if (w / h < asp) { const nw = h * asp; x0 -= (nw - w) / 2; w = nw; } else { const nh = w / asp; y0 -= (nh - h) / 2; h = nh; }
  return [x0, y0, w, h];
}
/* ---- map decorations shared by modules 01, 03, 04, 05, 08 and the metro tabs. With the zoomable core map (mapHandle in 00_core.js) the
   pins and the dimming go through its handle, so they follow zoom and pan; without it they are drawn into the svg here. A map keeps them
   through a redraw only when the caller decorates again. Pin clicks need onPin in the drawMap options (o.onPin below). */
const IX_CORE = typeof mapHandle === 'function' && typeof mapPinsSVG === 'function';
const IX_FIRM = () => { try { return typeof FIRM !== 'undefined' && FIRM.counties ? FIRM.counties().filter(f => CI[f]) : []; } catch (e) { return []; } };
// the firm's service counties get a heavy outline on a county map
function ixMarkFirm(mapEl, fips) { const s = new Set(fips || IX_FIRM()); $$('path.area', mapEl).forEach(p => p.classList.toggle('ix-firm', s.has(p.dataset.id))); }
// on a ZIP map the county outlines carry it: the i-th path.cty is the i-th county of the metro's geometry
function ixMarkFirmZip(mapEl, M, fips) { const s = new Set(fips || IX_FIRM()); const ks = Object.keys((M && M.county) || {}); $$('path.cty', mapEl).forEach((p, i) => p.classList.toggle('ix-firm', s.has(ks[i]))); }
// dim every area outside keep (a Set of ids); null clears
function ixDim(mapEl, keep) { if (IX_CORE && mapEl.__mz) { mapHandle(mapEl).dim(keep || null); return; } $$('path.area', mapEl).forEach(p => p.classList.toggle('ix-dim', !!keep && !keep.has(p.dataset.id))); }
const IX_PINFILL = { firm: 'var(--firm-accent, var(--s2))', watch: 'var(--s3)' };
// pins: [{id, x, y, r (px), kind: 'firm'|'watch', label, tip}] in map units; hover shows tip, click calls o.onPin(id)
function ixPins(mapEl, pins, o) {
  o = o || {}; pins = pins || [];
  if (IX_CORE && mapEl.__mz) { mapHandle(mapEl).pins(pins.length ? pins.map(p => ({ id: p.id, x: p.x, y: p.y, shape: p.kind === 'firm' ? 'diamond' : 'circle', r: p.r, fill: IX_PINFILL[p.kind] || 'var(--ink)', tip: p.tip, title: p.label, cls: 'ix-pin ' + (p.kind || 'watch') })) : null); return; }
  const svg = mapEl && mapEl.querySelector('svg'); if (!svg) return; const old = svg.querySelector('g.ix-pins'); if (old) old.remove(); if (!pins.length) return;
  const vb = (svg.getAttribute('viewBox') || '0 0 900 900').split(/\s+/).map(Number); const u = (vb[2] || 900) / Math.max(1, svg.clientWidth || 900);   // px to map units
  const seen = {}; const ns = 'http://www.w3.org/2000/svg'; const g = document.createElementNS(ns, 'g'); g.setAttribute('class', 'ix-pins');
  pins.slice().sort((a, b) => (a.kind === 'firm') - (b.kind === 'firm') || (b.r || 0) - (a.r || 0)).forEach(p => {
    if (!isN(p.x) || !isN(p.y)) return; const k = Math.round(p.x) + ',' + Math.round(p.y); const n = seen[k] = (seen[k] || 0) + 1; const ang = n * 2.4, rad = n > 1 ? 7 * u * Math.sqrt(n - 1) : 0; const x = p.x + rad * Math.cos(ang), y = p.y + rad * Math.sin(ang); const r = (p.r || 5) * u;
    const e2 = document.createElementNS(ns, p.kind === 'firm' ? 'path' : 'circle');
    if (p.kind === 'firm') e2.setAttribute('d', `M${x.toFixed(1)} ${(y - r * 1.35).toFixed(1)}L${(x + r * 1.35).toFixed(1)} ${y.toFixed(1)}L${x.toFixed(1)} ${(y + r * 1.35).toFixed(1)}L${(x - r * 1.35).toFixed(1)} ${y.toFixed(1)}Z`); else { e2.setAttribute('cx', x.toFixed(1)); e2.setAttribute('cy', y.toFixed(1)); e2.setAttribute('r', r.toFixed(1)); }
    e2.setAttribute('class', 'ix-pin ' + (p.kind || 'watch')); e2.setAttribute('fill', IX_PINFILL[p.kind] || 'var(--ink)'); e2.setAttribute('data-pin', p.id); const t = document.createElementNS(ns, 'title'); t.textContent = p.label || ''; e2.appendChild(t); g.appendChild(e2);
  });
  const by = {}; pins.forEach(p => { by[p.id] = p; });
  g.addEventListener('mousemove', e => { const t = e.target.closest && e.target.closest('[data-pin]'); if (!t) return; e.stopPropagation(); const p = by[t.getAttribute('data-pin')]; if (p) showTip(p.tip || esc(p.label), e.clientX, e.clientY); });
  g.addEventListener('mouseleave', hideTip);
  g.addEventListener('click', e => { const t = e.target.closest && e.target.closest('[data-pin]'); if (!t) return; e.stopPropagation(); if (o.onPin) o.onPin(t.getAttribute('data-pin')); });
  svg.appendChild(g);
}
// where an office goes on a map: its ZIP's center (the core's zipXY when present), else its county's center; null when off this map.
// geo is 'state' or a metro code.
function ixPlace(geo) {
  return (zip, cty) => {
    zip = String(zip || '').trim(); if (typeof zipXY === 'function' && zip) { const xy = zipXY(geo, zip); if (xy) return xy; }
    if (geo === 'state') { if (zip && !cty && ZI[zip]) cty = ZI[zip].county; return cty && GEO.state.cent[cty] ? GEO.state.cent[cty] : null; }
    const M = GEO.metros[geo]; if (!M) return null; if (zip && M.zcent && M.zcent[zip]) return M.zcent[zip]; if (!cty && ZI[zip]) cty = ZI[zip].county; return cty && M.ccent && M.ccent[cty] ? M.ccent[cty] : null;
  };
}
// the pins for a map: the firm's offices (diamonds) and the watched firms' offices (circles sized by their latest logged review count).
// place(zip, county) returns map coordinates or null; nothing is placed that the firm profile or the watch roster does not hold.
function ixFirmPins(place) {
  const out = [];
  try { if (typeof FIRM !== 'undefined') { const f = FIRM.get(); (f.offices || []).forEach((o, i) => { const zip = String(o.zip || '').trim(); const cty = o.county || (ZI[zip] || {}).county || ''; const xy = (zip || cty) ? place(zip, cty) : null; if (!xy) return; const nm = f.name || 'Your firm'; out.push({ id: 'firm:' + i, kind: 'firm', x: xy[0], y: xy[1], r: 6, label: `${nm}${o.label ? ', ' + o.label : ''}`, tip: `<b>${esc(nm)}</b><div class="small">${esc(o.label || 'Office')}${o.primary ? ' (primary practice location)' : ''} · ${esc([o.city, zip].filter(Boolean).join(' '))}</div><div class="small">At its ZIP's center, or its county's when the ZIP is off this map. Click to open the firm profile.</div>` }); }); } } catch (e) { }
  try { if (typeof WATCH !== 'undefined') WATCH.list().forEach(c => { const rv = WATCH.reviews(c.key); const n = rv.latest ? rv.latest.count : 0; const sd = WATCH.scoreDetail ? WATCH.scoreDetail(c) : { score: WATCH.score(c) }; (c.offices || []).forEach((o, i) => { const zip = String(o.zip || '').trim(); const xy = (zip || o.county) ? place(zip, o.county) : null; if (!xy) return; out.push({ id: 'watch:' + c.key + ':' + i, kind: 'watch', key: c.key, x: xy[0], y: xy[1], r: 3.5 + 1.8 * Math.log10(n + 1), label: c.name, tip: `<b>${esc(c.name)}</b><div class="small">${esc((WATCH.TIERS || {})[c.tier] || c.tier)} · ${esc([o.city, zip].filter(Boolean).join(' ') || cname(o.county))}</div><div class="row"><span>Reviews logged</span><span>${rv.latest ? N(rv.latest.count) + (rv.latest.rating != null ? ' · ' + N(rv.latest.rating, 1) + ' stars' : '') : 'none'}</span></div><div class="row"><span>Activity score</span><span>${N(sd.score)}</span></div><div class="small">Sized by the latest review count logged in Competitor Watch. Click to open it there.</div>` }); }); }); } catch (e) { }
  return out;
}
// what a pin click opens: the firm profile, or the watched firm in Competitor Watch
function ixPinGo(id, from) { if (id && typeof id === 'object') id = id.id; if (/^firm:/.test(id)) { if (typeof FIRM !== 'undefined') FIRM.panel(); return; } const m = String(id).match(/^watch:(.+):\d+$/); if (m) goModule('watch', { comp: m[1], from }); }
// the firm's own observed numbers from Accounts, guarded (Accounts may hold nothing or not be loaded)
function ixAcctZip(days) { try { return typeof ACCT !== 'undefined' && ACCT.byZip ? ACCT.byZip(days || 90) || [] : []; } catch (e) { return []; } }
function ixAcctCounty(days) { try { return typeof ACCT !== 'undefined' && ACCT.byCounty ? ACCT.byCounty(days || 90) || [] : []; } catch (e) { return []; } }
// the watched firms serving a county (roster counties or an office there)
function ixWatchIn(fips) { try { if (typeof WATCH === 'undefined') return []; if (WATCH.tracked) return WATCH.tracked({ county: fips }) || []; const m = WATCH.rosterByCounty ? WATCH.rosterByCounty() : {}; return (m[fips] || []).map(k => WATCH.get(k)).filter(Boolean); } catch (e) { return []; } }
// advertisers logged in Competitor Watch whose observations name the county (or ZIP), roster or not: [{key, name, live, n, platforms, last}]
function ixAdvertisersIn(o) { try { return typeof WATCH !== 'undefined' && WATCH.advertisersIn ? WATCH.advertisersIn(o) || [] : []; } catch (e) { return []; } }
// a one line ledger of the firm's observed activity in a county, or '' when Accounts holds none there
function ixAcctLine(fips) { const a = ixAcctCounty(90).find(o => o.county === fips); if (!a) return ''; return `<div class="ix-own"><b>Your accounts, last 90 days.</b> ${$$$(a.spend)} spend · ${N(a.leads)} leads · ${N(a.intake)} intakes · ${N(a.retained)} retained${isN(a.cpl) ? ' · ' + $$$(a.cpl) + ' per lead' : ''} (module 23).</div>`; }
function countyTipHTML(c, extra) {
  const firm = IX_FIRM().includes(c.fips);
  return `<b>${esc(c.name)} County</b>${firm ? '<div class="small">A county the firm serves</div>' : ''}<div class="row"><span>Dissolution Index</span><span>${N(c.di, 0)} (rank ${c.di_rank})</span></div><div class="row"><span>Divorce filings, 12 mo</span><span>${N(c.filings.ttm.div)}</span></div><div class="row"><span>per 1,000 married</span><span>${N(c.rates.div_per_1k_married, 1)}</span></div><div class="row"><span>Economic shock</span><span>${N(c.esi, 0)}</span></div><div class="row"><span>Grade</span><span>${c.grade}</span></div>${(c.acs.married || 0) < IDX_FLOOR ? `<div class="small">Under ${N(IDX_FLOOR)} married adults: rates swing with a single filing.</div>` : ''}${(ST.imputed || {})[c.fips] ? `<div class="small">Imputed filing months: ${esc(ST.imputed[c.fips].map(tLabel).join(', '))}.</div>` : ''}${extra || ''}`;
}
function countyDetailHTML(c) {
  const a = c.acs, r = c.risk, f = c.filings.ttm, e = c.econ, p = c.pools, la = c.laus || {}, ui = c.ui || {}, w = c.warn || {}, q = c.qcew || {};
  const hist = Object.keys(c.filings.hist).sort().map(y => ({ y: +y, v: c.filings.hist[y].div, m: c.filings.hist[y].months }));
  const g = c.grade; const gap = repGap(c); const noOff = !c.rates.lawoffices; const mcv = a.married_cv; const moe = isN(mcv) && isN(a.married) ? 1.645 * mcv * a.married : null;
  return `<div class="detail">
  <div><h4>Identity</h4><dl class="kv"><dt>County</dt><dd>${esc(c.name)}</dd><dt>Metro</dt><dd>${esc((c.msa_title ? MNAME(c.msa_title) : 'non metro'))}</dd><dt>Population 2025</dt><dd>${N(c.pop2025)}</dd><dt>Growth since 2020</dt><dd>${sgn(c.pop_growth)}</dd><dt>Married adults</dt><dd>${N(a.married)}${isN(moe) ? ` <span class="small">± ${N(moe)}</span>` : ''}</dd><dt>Married couple families with kids</dt><dd>${N(a.mc_fam_kids)}</dd><dt>Confidence</dt><dd><span class="grade ${g}">${g}</span></dd><dt>Google Ads criterion</dt><dd>${esc(c.gt || NA)}</dd></dl></div>
  <div><h4>Court filings, ${esc(c.filings.ttm_label)}</h4>${gap ? `<p class="small" style="margin:0 0 6px"><b>Possible clerk reporting gap:</b> no divorce filings reported in the last ${gap.months} months after about ${N(gap.avg, 0)} a month the year before. Read these counts as incomplete.</p>` : ''}<dl class="kv"><dt>Divorce, with children</dt><dd>${N(f.div_k)}</dd><dt>Divorce, no children</dt><dd>${N((f.div || 0) - (f.div_k || 0))}</dd><dt>Custody (SAPCR)</dt><dd>${N(f.sapcr)}</dd><dt>Protective orders</dt><dd>${N(f.po)}</dd><dt>Modifications</dt><dd>${N(f.mod)}</dd><dt>Enforcement</dt><dd>${N(f.enf)}</dd><dt>Title IV-D support</dt><dd>${N(f.ivd)}</dd><dt>CPS</dt><dd>${N(f.cps)}</dd><dt>Adoption</dt><dd>${N(f.adopt)}</dd><dt>Divorces disposed</dt><dd>${N(f.d_div)}</dd><dt>Divorce filings vs prior 12 mo</dt><dd>${sgn(c.rates.div_yoy)}</dd><dt>vs 2019</dt><dd>${sgn(c.rates.div_vs_2019)}</dd></dl><div style="margin-top:6px">${spark(hist.filter(h => h.m === 12).map(h => h.v), 200, 30, 'var(--s1)')} <span class="small">annual divorce filings ${hist[0] ? hist[0].y : ''} to 2025</span></div></div>
  <div><h4>Composition (PUMS model, married adults)</h4><dl class="kv"><dt>Observed hazard per 1,000</dt><dd>${N(r.haz_obs, 1)}</dd><dt>Modeled hazard per 1,000</dt><dd>${N(r.haz_pred, 1)}</dd><dt>Married under 5 years</dt><dd>${P(r.dur_lt5, 0)}</dd><dt>Married 5 to 9 years</dt><dd>${P(r.dur_5_9, 0)}</dd><dt>Remarried (2nd+ marriage)</dt><dd>${P(r.remarried, 0)}</dd><dt>Married before 23</dt><dd>${P(r.young_mar, 0)}</dd><dt>Aged 18 to 34</dt><dd>${P(r.age_18_34, 0)}</dd><dt>Aged 50 to 64</dt><dd>${P(r.age_50_64, 0)}</dd><dt>Bachelor's or higher</dt><dd>${P(r.ba_plus, 0)}</dd><dt>Renters</dt><dd>${P(r.renter, 0)}</dd><dt>Spouse or self unemployed</dt><dd>${P(r.any_unemp, 1)}</dd><dt>Wife out earns husband</dt><dd>${P(r.wife_more, 0)}</dd><dt>Active duty in household</dt><dd>${P(r.mil_active, 1)}</dd><dt>Veteran</dt><dd>${P(r.veteran, 0)}</dd><dt>Commute 45 min or more</dt><dd>${P(r.long_commute, 0)}</dd></dl></div>
  <div><h4>Signals (ACS 2020 to 2024)</h4><dl class="kv"><dt>Separated per 1,000 married</dt><dd>${N(a.sep_per_1k_married, 1)}</dd><dt>Divorced adults (stock)</dt><dd>${N(a.divorced)}</dd><dt>Married aged 25 to 44</dt><dd>${P(a.mar_25_44_sh, 0)}</dd><dt>Married aged 55 and over</dt><dd>${P(a.mar_55p_sh, 0)}</dd><dt>Cohabiting couples with kids</dt><dd>${N(a.cohab_hh_kids)}</dd><dt>Single parent families</dt><dd>${N(a.sp_fam_kids)}</dd><dt>Births to unmarried mothers</dt><dd>${P(a.births_unmar_sh, 0)}</dd><dt>Grandparents responsible</dt><dd>${N(a.gp_resp)}</dd><dt>Median household income</dt><dd>${$$$(a.med_hh_inc)}</dd><dt>Rent burden 35%+</dt><dd>${P(a.rent_burden35_sh, 0)}</dd><dt>Mortgage burden 35%+</dt><dd>${P(a.mort_burden35_sh, 0)}</dd><dt>SNAP households</dt><dd>${P(a.snap_sh, 0)}</dd><dt>Married with kids in poverty</dt><dd>${P(a.mc_kids_pov_sh, 0)}</dd><dt>Moved in past year</dt><dd>${P(a.moved_sh, 0)}</dd></dl></div>
  <div><h4>Economy</h4><dl class="kv"><dt>Unemployment rate, ${esc(fmtDate(la.last))}</dt><dd>${P1(la.ur)}</dd><dt>Year earlier</dt><dd>${P1(la.ur_yago)}</dd><dt>2019 average</dt><dd>${P1(la.ur_2019)}</dd><dt>UI initial claims, last 13 weeks</dt><dd>${N(ui.w13)}</dd><dt>Same 13 weeks of 2019</dt><dd>${N(ui.w13_2019)}</dd><dt>Prior year window</dt><dd>${N(ui.w13_yago)}</dd><dt>WARN workers, last 12 months</dt><dd>${N(w.last12 ? w.last12.workers : 0)}</dd><dt>Payroll jobs, ${esc(fmtQ(q.last))}</dt><dd>${N(q.emp)}</dd><dt>Jobs, year over year</dt><dd>${sgn(q.emp_pct)}</dd><dt>Married adults where either spouse is unemployed</dt><dd>${N(e.married_exposed)}</dd><dt>Economic Shock Index</dt><dd>${N(c.esi, 0)}</dd><dt>Expected filings lift at 12 months</dt><dd>${sgn(e.expected.m12_pct)}</dd></dl></div>
  <div><h4>Supply and protection</h4><dl class="kv"><dt>Law offices (CBP 2023)</dt><dd>${noOff ? 'none recorded' : N(c.rates.lawoffices)}</dd><dt>Legal services jobs</dt><dd>${isN(c.rates.legal_emp) ? N(c.rates.legal_emp) : 'not published'}</dd><dt>Private family filings per office</dt><dd>${noOff ? 'no office' : N(c.rates.filings_per_lawoffice, 1)}</dd><dt>CPS removals FY2025</dt><dd>${c.dfps && isN(c.dfps.removals['2025']) ? N(c.dfps.removals['2025']) : 'not reported'}</dd><dt>Abuse investigations with family violence, FY2025</dt><dd>${c.dfps && isN(c.dfps.inv_fv['2025']) ? N(c.dfps.inv_fv['2025']) : 'not reported'}</dd></dl></div>
  </div><h4 class="ix-h4">Index components (percentile rank among the counties with data, with weights; supply ranks the ${CTY.filter(x => isN(x.pct.supply)).length} counties with a law office count)</h4><div class="chart" id="compChart_${c.fips}" style="max-width:640px"></div>`;
}
// a component with no data (supply where the Census counts no law office) reads n/a, not a percentile of 0
function mountCompChart(c, host) { const el = host ? host.querySelector('#compChart_' + c.fips) : $('#compChart_' + c.fips); if (!el) return; const nm = { filing: 'Filing intensity', haz: 'Composition hazard', sep: 'Separation', econ: 'Economic shock', struct: 'Family structure', strain: 'Financial strain', supply: 'Supply gap' }; barChart(el, { title: c.name + ' County index components', rows: Object.keys(D.weights).map(k => { const v = isN(c.pct[k]) ? c.pct[k] : null; return { label: nm[k] + ' ' + Math.round(D.weights[k] * 100) + '%', value: v, color: rampColor('ember', 0.35 + 0.6 * (v || 0) / 100) }; }), W: 640, lw: 200, max: 100, fmt: v => isN(v) ? N(v, 0) : 'n/a' }); }
// a diverging σ bar: the county's distance from the county mean on one component, right of center adds to the index
function idxZbar(label, val, z) { const w = isN(z) ? Math.min(48, Math.abs(z) * 16) : 0; const left = isN(z) && z < 0 ? 50 - w : 50; const zt = isN(z) ? (z > 0 ? '+' : '') + MINUS(z.toFixed(1)) + 'σ' : NA; return `<div class="ix-zbar"><div class="ix-zl">${esc(label)} <span>${esc(val)}</span></div><div class="ix-zt" role="img" aria-label="${esc(label + ' ' + val + ', ' + zt + ' from the county mean')}"><i class="ix-zm"></i>${isN(z) ? `<i class="ix-zf ${z >= 0 ? 'up' : 'dn'}" style="left:${left.toFixed(1)}%;width:${Math.max(w, 0.6).toFixed(1)}%"></i>` : ''}</div><div class="ix-zv">${esc(zt)}</div></div>`; }
// two stacked share bars, the county over Texas, with one key that gives both shares; parts [{l, v, color}]
function idxStackPair(name, cp, tp) {
  const tc = sum(cp.map(p => p.v || 0)), tt = sum(tp.map(p => p.v || 0));
  const bar = (lab, ps, t) => !t ? `<div class="ix-stackrow"><span>${esc(lab)}</span><div class="small">no data</div></div>` : `<div class="ix-stackrow"><span>${esc(lab)}</span><div class="ix-stack" role="img" aria-label="${esc(lab + ': ' + ps.filter(p => p.v > 0).map(p => p.l + ' ' + P(p.v / t, 0)).join(', '))}">${ps.filter(p => p.v > 0).map(p => `<i style="flex:${p.v};background:${p.color}" title="${esc(p.l)}: ${P(p.v / t, 0)}"></i>`).join('')}</div></div>`;
  return bar(name, cp, tc) + bar('Texas', tp, tt) + `<div class="ix-skey">${cp.map((p, i) => `<span><i style="background:${p.color}"></i>${esc(p.l)} <b>${tc ? P((p.v || 0) / tc, 0) : NA}</b> <em>${tt ? P((tp[i].v || 0) / tt, 0) : NA}</em></span>`).join('')}</div>`;
}
const IDX_DUR = [['dur_lt5', 'Under 5 years', 'var(--rp-forest-7)'], ['dur_5_9', '5 to 9', 'var(--rp-forest-5)'], ['dur_10_19', '10 to 19', 'var(--rp-forest-3)'], ['dur_20p', '20 or more', 'var(--rp-slate-3)']];
const IDX_MIX = [['div_k', 'Divorce with children', 'var(--s1)'], ['div_nk', 'Divorce, no children', 'var(--s3)'], ['sapcr', 'Custody (SAPCR)', 'var(--s4)'], ['po', 'Protective orders', 'var(--s2)'], ['mod', 'Modifications', 'var(--s5)'], ['enf', 'Enforcement', 'var(--s6)'], ['ivd', 'Title IV-D', 'var(--s7)'], ['cps', 'CPS', 'var(--s8)'], ['adopt', 'Adoption', 'var(--rp-slate-4)']];
// the threshold callouts: county level readings only, never a statement about a household or a couple
function idxNotes(c, T) {
  const out = []; const G = D.pums.groups, OR = D.pums.coefs; const small = (c.acs.married || 0) < IDX_FLOOR; const LM = typeof LINE_META !== 'undefined' ? LINE_META : {};
  const add = (kind, title, html) => out.push({ kind, title, html });
  const gap = repGap(c); if (gap) add('', 'Clerk reporting gap', `No divorce filings reported for the last ${gap.months} months after about ${N(gap.avg, 0)} a month the year before. Every filing figure for ${esc(c.name)} County reads low until the clerk reports again.`);
  const imp = (ST.imputed || {})[c.fips]; if (imp) add('note', 'Imputed filing months', `The court series has no clerk report for ${esc(imp.map(tLabel).join(', '))}; those months are filled with the same month of the adjacent year, as for every county that normally files 30 or more cases.`);
  if (small) add('note', 'A small married population', `${N(c.acs.married)} married adults: under ${N(IDX_FLOOR)}, a single filing moves the rate by a full point per 1,000 or more. The map shows the county pale and the callouts below are not drawn.`);
  if (!small) {
    if (isN(c.acs.sep_per_1k_married) && c.acs.sep_per_1k_married >= T.sep) add('judg', 'Separated, not yet divorced', `${N(c.acs.sep_per_1k_married, 0)} separated adults per 1,000 married adults, in the top tenth of counties (the cut is ${N(T.sep, 0)}). Texas has no legal separation, so a separated population is where filings form. A county figure; it says nothing about any household.`);
    if (isN(c.risk.dur_5_9) && c.risk.dur_5_9 >= T.dur59 && G['dur_5-9']) add('judg', 'The peak hazard years', `${P(c.risk.dur_5_9, 0)} of married adults here are in years five to nine of their marriage (top tenth; the cut is ${P(T.dur59, 0)}). In the Texas microdata that band divorces at ${N(G['dur_5-9'].haz, 1)} per 1,000 a year against ${N(G.all.haz, 1)} overall.`);
    if (isN(c.risk.remarried) && c.risk.remarried >= T.rem && OR.timesb_2) add('judg', 'Second marriages', `${P(c.risk.remarried, 0)} of married adults are in a second or later marriage (top tenth). The hazard model puts a second marriage at ${N(OR.timesb_2.or, 2)} times the odds of a first; blended family custody, stepparent adoption and modification work follow.`);
    if (isN(c.acs.mar_55p_sh) && c.acs.mar_55p_sh >= T.m55) add('judg', 'Gray divorce pool', `${P(c.acs.mar_55p_sh, 0)} of married adults are 55 or older (top tenth). Retirement division and spousal maintenance lead the questions${LM.gray && LM.gray.law ? ` (Family Code ${esc(LM.gray.law.replace(/\.$/, ''))})` : ''}; module 06 sizes the gray divorce line.`);
    if (isN(c.risk.mil_active) && c.risk.mil_active >= T.mil && c.risk.mil_active >= 0.01 && OR.mil_own) add('judg', 'Active duty households', `${P(c.risk.mil_active, 1)} of married adults live with an active duty service member (top tenth). Own active duty service carries ${N(OR.mil_own.or, 2)} times the odds in the hazard model${LM.mil && LM.mil.law ? `; residency, retirement division and the federal rules follow ${esc(LM.mil.law.replace(/\.$/, ''))}` : ''}.`);
  }
  if (isN(c.esi) && c.esi >= 80) { const P12 = D.panel && D.panel['ldiv|claims_0_12']; const dbl = b => (Math.exp(b * Math.log(2)) - 1) * 100; add('judg', 'Economic shock', `Shock index ${N(c.esi, 0)}, in the top fifth of counties.${P12 ? ` In the 43 county panel a doubling of unemployment claims comes with ${sgn(dbl(P12.coefs.lclaims.coef), 1)} in divorce filings the same month and ${sgn(dbl(P12.coefs.lclaims_l12.coef), 1)} twelve months later (module 05)` : ' Module 05 gives the lag structure'}: a shock delays filings before it adds to them.`); }
  if (isN(c.rates.div_k_share) && c.rates.div_k_share >= 0.5 && !small) add('judg', 'Most divorces involve children', `${P(c.rates.div_k_share, 0)} of divorce filings here involve minor children, so conservatorship, possession and child support (Family Code ch. 153 and 154) come with most cases.`);
  if (isN(c.rates.po_per_10k) && c.rates.po_per_10k >= T.po && !small) add('judg', 'Protective order load', `${N(c.rates.po_per_10k, 1)} protective order applications per 10,000 residents, in the top tenth (the cut is ${N(T.po, 1)}). Protective orders run under Family Code Title 4; intake here needs a protocol for urgent safety calls.`);
  if (!c.rates.lawoffices) add('note', 'No law office counted', 'County Business Patterns 2023 counts no office of lawyers with a payroll here. Residents use solo lawyers the count leaves out, or offices in the next county.');
  else if (isN(c.rates.filings_per_lawoffice) && c.rates.filings_per_lawoffice >= T.fpo && !small) add('judg', 'Thin supply', `${N(c.rates.filings_per_lawoffice, 1)} private family filings per law office, in the top tenth (the cut is ${N(T.fpo, 1)}): fewer offices per case than almost anywhere in Texas.`);
  return out;
}
registerModule({
  key: 'index', num: '01', title: 'Dissolution Index', desc: 'Where Texas marriages are ending and where the next filings are forming, county by county',
  mount(root) {
    const R = s => $(s, root), RR = s => $$(s, root);
    const st = { layer: LAYERS_CTY[store.get('sev.index.layer', 'di')] ? store.get('sev.index.layer', 'di') : 'di', sel: store.get('sev.county', '48201'), metro: '', pins: store.get('sev.index.pins', true) !== false, cleared: null };
    if (!CI[st.sel]) st.sel = '48201';
    const tx = ST.annual; const y25 = tx['2025'], y19 = tx['2019'];
    const top = CTY.slice().sort((a, b) => (b.di || 0) - (a.di || 0));
    const totMarried = ST.acs.married; const ttmState = stTTM('div');
    const ZS = idxZStats(CTY), TH = idxThresholds(CTY), VAL = idxValidate(CTY); const oppPct = pctScale(CTY.map(c => c.filings.ttm.priv));
    const nThin = CTY.filter(c => (c.acs.married || 0) < IDX_FLOOR).length, nImp = Object.keys(ST.imputed || {}).length;
    const metroOpts = () => [['', 'All Texas']].concat(IX_FIRM().length ? [['firm', 'Your counties (' + IX_FIRM().length + ')']] : []).concat(Object.keys(MSA).sort((a, b) => MSA[b].pop2025 - MSA[a].pop2025).map(k => [k, MNAME(MSA[k].title)]));
    root.innerHTML = mastHTML({ eyebrow: 'Module 01 · Dissolution Index · all 254 Texas counties', title: 'Dissolution Index', ribbon: { text: 'Open the Metro Atlas', go: 'atlas' }, dek: `Every Texas county scored on seven measured things: how many divorces its residents actually filed in the last twelve months (Office of Court Administration), how divorce prone its married population is by composition (a hazard model fit on ${N(D.pums.n)} married Texans in the Census microdata), how many couples are already separated but not yet filed, how hard the local economy is shocking families right now, the family structure that turns a divorce into a custody case, the financial strain that turns it into a fight, and how thin the supply of lawyers is against it. The map is where a family law firm should be looking; the tabs after it say what to do there.`, facts: [[N(ttmState), 'divorce filings statewide, ' + ttmSpan()], [N(y25.f_div), 'in calendar 2025 (' + sgn((y25.f_div / y19.f_div - 1) * 100) + ' vs 2019)'], [N(totMarried), 'married Texans (ACS 2020 to 2024)'], ['Data through', fmtDateL(META.oca_through) + ' filings, ' + fmtDate(META.ui_through) + ' claims']] }) + `
    ${toolbarHTML('Dissolution Index', 'Seven graded components · county resolution · trailing twelve months', [{ id: 'idxCsv', label: '↓ County CSV' }, { id: 'idxGoLedger', label: 'Filings Ledger ↗' }, { id: 'idxGoEcon', label: 'Economic Shock ↗' }, { id: 'idxGoPaid', label: 'Paid Acquisition ↗' }, { id: 'idxGoDesk', label: 'Campaign Desk ↗', title: 'Send the selected county, the metro in view, your counties or the top counties in view to the Campaign Desk' }, { id: 'idxGoForge', label: 'Site Forge ↗', title: 'Send the selected county or the counties in view to the Site Forge' }])}
    <div class="callout"><div class="h">Read this first: what the index is and is not</div><p>This maps <b>demand for family law work</b>, not misery. The filing component is real court activity reported monthly by every district clerk to the Office of Court Administration and pulled here for all 254 counties. The composition component is a model: it applies divorce hazards learned from 2020 to 2024 Census microdata (age, marriage duration, number of marriages, education, military service, age at marriage) to each county's married population. The economic component is live: weekly unemployment claims, monthly unemployment rates, WARN layoff notices and quarterly job counts. A high index means many filings per married adult, a married population built like the ones that divorce, a visible pipeline of separated couples, an economy under stress, and fewer law offices per case. <b>Grade A</b> counties have monthly filing data and tight Census margins; <b>grade D</b> counties are small enough that one busy month moves the number. It does not describe any household, it does not forecast which counties will rise this year (the validation panel shows that test failing), and ability to pay is left to modules 06 and 07. Module 05 explains why an economic shock lowers filings first and raises them a year later.</p></div>
    <div class="tiles" id="idxTiles"></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', `<select id="idxLayer">${idxLayerOptions(Object.keys(LAYERS_CTY), st.layer)}</select>`)}${ctl('Metro filter', sel('idxMetro', metroOpts(), ''))}${ctl('Find a county', `<input type="search" id="idxQ" list="idxQList" placeholder="Harris or 48201" autocomplete="off" aria-describedby="idxQMsg"><datalist id="idxQList">${CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => `<option value="${esc(c.name)}"></option>`).join('')}</datalist><span class="small" id="idxQMsg" role="status" aria-live="polite"></span>`)}<label class="chk"><input type="checkbox" id="idxLabels" checked> Label the largest counties</label><label class="chk"><input type="checkbox" id="idxPins"${st.pins ? ' checked' : ''}> Show your offices and watched firms</label><button type="button" class="btn sm" id="idxClear">Texas view</button></div>
    <div class="split"><div><div class="mapwrap" id="idxMap"></div><div id="idxLegNote"></div></div><div id="idxSide" class="ix-side"></div></div></div>
    <div class="panel" style="margin-bottom:14px"><h3>County detail</h3><div class="sub" id="idxDetailSub"></div><div id="idxDetail"></div></div>
    <div class="grid2"><div class="panel"><h3>How the index is built</h3><div class="sub">Seven components, each oriented so a higher value means more demand. Every weight, measure, source and grade, at county and at ZIP.</div><div id="idxMethod"></div></div>
    <div class="panel"><h3>Is this one variable or seven?</h3><div class="sub">Correlation of the component percentiles across the counties that have both (Pearson r). A pair near 0 adds independent information to the index; a strong pair partly counts the same thing twice. Supply covers the ${CTY.filter(c => isN(c.pct.supply)).length} counties with a law office count.</div><div id="idxCorr"></div><div id="idxSens"></div></div></div>
    <div class="panel" style="margin-bottom:14px"><h3>Does the index predict anything it was not built from?</h3><div class="sub">The filing component carries ${Math.round(D.weights.filing * 100)}% of the weight, so testing the index against court filings would be circular. These tests drop that component and compare the other six with outcomes they never saw, then test the full index out of time against the 2026 year so far.</div><div class="grid2 even ix-scat"><div><div class="chart" id="idxSc1"></div><p class="small" id="idxSc1n"></p></div><div><div class="chart" id="idxSc2"></div><p class="small" id="idxSc2n"></p></div></div><div id="idxVal"></div></div>
    <div class="panel"><h3>All counties ranked</h3><div class="sub">Click a row to select it on the map. Sort any column. Filings are the trailing twelve months where monthly data exists (all metro counties) and calendar 2025 elsewhere.</div><div id="idxTable"></div></div>
    ${srcFoot([['Sources', `Texas Office of Court Administration court activity, ${esc(seriesSpan())}; ACS 2020 to 2024 county estimates and the 2020 to 2024 Texas PUMS (${N(D.pums.n)} married adults); Texas Workforce Commission claims and WARN notices; BLS LAUS and QCEW; DFPS Data Book; County Business Patterns 2023; NCHS state divorce rates through ${esc(Object.keys(ST.nchs.divorce).sort().pop())}. Evidence (module 27) holds the spatial clusters, capture ratios and the signal matrix; Ground Truth (module 28) the filing record, survey precision and the data inventory.`], ['Judgment calls', `The weights are set by hand (method card); equal weights move the ranking little (r ${N(VAL.eq.r, 3)}). Counties under ${N(IDX_FLOOR)} married adults are drawn pale and get no threshold callouts; counties with imputed filing months are outlined with a dash.`], ['Caveats', 'Every figure is ecological: it describes a county\'s population, never a household or a couple. ZIP filings elsewhere in Severance are allocations of these county counts.']])}`;
    const mapEl = R('#idxMap'); let tbl = null;
    const hand = k => { const c = CI[st.sel]; if (!c) return k === 'paid' && st.metro && MSA[st.metro] ? { metro: st.metro } : null; return k === 'paid' || k === 'atlas' ? (c.msa ? { metro: c.msa } : null) : { county: st.sel }; };
    R('#idxGoLedger').onclick = () => goModule('ledger', hand('ledger')); R('#idxGoEcon').onclick = () => goModule('econ', hand('econ')); R('#idxGoPaid').onclick = () => goModule('paid', hand('paid'));
    const inView = () => objs().slice().sort((a, b) => (b.di || 0) - (a.di || 0));
    const deskLoad = () => { if (CI[st.sel]) return { geo: 'cty:' + st.sel, counties: [st.sel] }; if (st.metro && MSA[st.metro]) return { geo: 'msa:' + st.metro }; const fs = st.metro === 'firm' ? IX_FIRM() : inView().slice(0, 10).map(c => c.fips); return fs.length ? { geo: 'cty:' + fs[0], counties: fs } : null; };
    const forgeLoad = () => ({ counties: CI[st.sel] ? [st.sel] : inView().slice(0, 10).map(c => c.fips) });
    R('#idxGoDesk').onclick = () => { const p = deskLoad(); if (p) goModule('desk', p); };
    R('#idxGoForge').onclick = () => goModule('forge', forgeLoad());
    function objs() { const f = st.metro === 'firm' ? new Set(IX_FIRM()) : null; return CTY.filter(c => !st.metro || (f ? f.has(c.fips) : c.msa === st.metro)); }
    function tiles() {
      const c = CI[st.sel]; const hi = top[0];
      R('#idxTiles').innerHTML = tile('Highest index', esc(hi.name), `${N(hi.di, 0)} · ${N(hi.rates.div_per_1k_married, 1)} filings per 1,000 married`, hi.grade) + tile('Statewide filing rate', N(ttmState / totMarried * 1000, 1), 'divorce filings per 1,000 married adults, last 12 months', 'A') + tile('With children', P(stTTM('div_k') / ttmState, 0), 'of divorce filings involve minor children (custody attached)', 'A') + tile('Separated, not yet filed', N(ST.acs.separated), `separated Texans (ACS): ${N(ST.acs.sep_per_1k_married, 0)} per 1,000 married`, 'A') + tile('Composition hazard', N(D.pums.groups.all.haz, 1), 'divorces per 1,000 married adults per year, Texas microdata (SE ' + N(D.pums.groups.all.se, 2) + ')', 'A') + (c ? tile('Selected county', esc(c.name), `index ${N(c.di, 0)}, rank ${c.di_rank} of 254 · ${N(c.filings.ttm.div)} filings`, c.grade) : tile('Selected county', 'none', 'Texas view: the three way count of divorces is beside the map'));
    }
    // pins sit at the county center on the state map (the ZIP centers belong to the metro maps)
    const pinsState = () => ixFirmPins(ixPlace('state'));
    function decorate() {
      const imp = ST.imputed || {};
      RR('#idxMap path.area').forEach(p => { const c = CI[p.dataset.id]; if (!c) return; p.classList.toggle('ix-thin', (c.acs.married || 0) < IDX_FLOOR); p.classList.toggle('ix-imp', !!imp[c.fips]); });
      const firm = IX_FIRM(); ixMarkFirm(mapEl, firm); const pins = st.pins ? pinsState() : []; ixPins(mapEl, pins, { onPin: id => ixPinGo(id, 'index') });
      const L = LAYERS_CTY[st.layer]; const nW = pins.filter(p => p.kind === 'watch').length, nF = pins.filter(p => p.kind === 'firm').length;
      R('#idxLegNote').innerHTML = idxLegendNote(L, `<div class="ix-legkeys"><span><i class="ix-sw thin"></i>Pale: under ${N(IDX_FLOOR)} married adults (${nThin} counties; one filing swings the rate)</span><span><i class="ix-sw imp"></i>Dashed outline: imputed filing months (${nImp} counties)</span>${firm.length ? `<span><i class="ix-sw firm"></i>Heavy outline: the ${firm.length === 1 ? 'county' : firm.length + ' counties'} the firm serves</span>` : ''}${st.pins ? `<span><i class="ix-sw pinf"></i>Your offices (${nF})</span><span><i class="ix-sw pinw"></i>Watched firms' offices (${nW}), sized by logged reviews</span>` : ''}</div>${st.pins && !nF && !nW ? '<div class="small">No office to pin yet: add offices in the firm profile (the Firm button) and firms with offices in Competitor Watch (module 24).</div>' : ''}`);
    }
    function drawIdx() {
      const L = LAYERS_CTY[st.layer]; const os = objs(); const sc = layerScale(L, os); const inSet = new Set(os.map(c => c.fips));
      const big = (st.metro ? os : CTY).slice().sort((a, b) => b.pop2025 - a.pop2025).slice(0, 30).map(c => c.fips);
      const view = st.metro === 'firm' ? ixBox(os.map(c => GEO.state.county[c.fips]), GEO.state.W, GEO.state.H) : st.metro ? metroBox(st.metro) : null;
      drawMap(mapEl, { W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => inSet.has(id) ? L.v(CI[id]) : null, color: sc.color, label: id => countyTipHTML(CI[id], ['di', 'filing', 'esi'].includes(st.layer) ? '' : `<div class="row"><span>${esc(L.l)}</span><span>${esc(L.f(L.v(CI[id])))}</span></div>`), onSelect: id => select(id), onPin: p => ixPinGo(p, 'index'), selected: st.sel, outline: GEO.state.outline, cent: GEO.state.cent, labels: R('#idxLabels').checked ? big : [], labelText: id => CI[id].name, legend: Object.assign({ title: L.l }, sc.legend), title: (st.metro === 'firm' ? 'Your counties, ' : st.metro ? MNAME(MSA[st.metro].title) + ' counties, ' : 'Texas counties, ') + L.l, view, noDataLabel: st.metro ? 'outside the filter or no data' : 'no data' });
      decorate();
    }
    // the side card: the selected county, or the area in view with the three way count when nothing is selected
    function side() {
      const c = CI[st.sel]; const host = R('#idxSide');
      if (!c) {
        const os = objs(); const isState = !st.metro; const S = idxSanity(os, isState); const nm = isState ? 'Texas' : st.metro === 'firm' ? 'Your counties' : MNAME(MSA[st.metro].title);
        const f = isState ? stTTM('div') : sum(os.map(x => x.filings.ttm.div || 0)), m = isState ? ST.acs.married : sum(os.map(x => x.acs.married || 0));
        const rows = [[`Court filings, ${S.yr}`, N(S.oca.f), `Office of Court Administration; ${N(S.oca.d)} divorces disposed (decrees, dismissals and other endings)`, 'A'], [`Court filings, ${S.last}`, N(S.ocaLast.f), `${N(S.ocaLast.d)} disposed`, 'A'], ['Survey, a typical year of 2020 to 2024', N(S.pums), `${N(S.persons)} ${isState ? 'Texans' : 'residents'} report a divorce in the past year (PUMS, weighted); halved at two spouses per divorce`, 'B'], [`Vital statistics, ${S.yr}`, N(S.nchs), `NCHS Texas rate of ${N(S.rate, 1)} per 1,000 residents${isState ? '' : ' (the state rate; NCHS publishes no county rates)'} times ${N(S.pop)} ACS residents`, 'B']];
        host.innerHTML = `<div class="ix-head"><div><div class="ix-eb">${isState ? 'No county selected' : 'Filter in view, no county selected'}</div><h3>${esc(nm)}</h3><div class="small">${N(os.length)} counties · ${N(f)} divorce filings in 12 months${isState ? '' : ' (calendar 2025 where a county has no monthly reports)'} · ${N(m ? f / m * 1000 : null, 1)} per 1,000 married</div></div></div>
          <div class="ix-sec">Three ways to count a year of divorces</div><div class="tblwrap"><table class="t ix-san"><caption class="vh">Three counts of divorces, ${esc(nm)}</caption><thead><tr><th scope="col" class="l">Count</th><th scope="col">Divorces</th><th scope="col">Grade</th></tr></thead><tbody>${rows.map(r => `<tr><td class="l"><b>${esc(r[0])}</b><div class="small">${r[2]}</div></td><td>${r[1]}</td><td><span class="grade ${r[3]}">${r[3]}</span></td></tr>`).join('')}</tbody></table></div>
          <p class="small">The survey implies ${P(S.pums / (S.oca.f || 1), 0)} of the ${S.yr} filings and the vital statistics ${P(S.nchs / (S.oca.d || 1), 0)} of the ${S.yr} dispositions. They should not agree exactly: a filing is not a decree (cases are dismissed or nonsuited), the survey counts people rather than cases and misses spouses who left the area, and divorce counts reach NCHS through district clerk reports that undercount in some years. ${S.oca.f >= S.pums && S.pums >= S.nchs ? 'The order holds here: filings run highest, then the survey, then vital statistics.' : 'Here the usual order (filings, then the survey, then vital statistics) does not hold, which points at a small sample or a clerk reporting gap.'} Size a market with the court filings; read the other two as checks.</p>
          <p class="small">Select a county on the map, in the table or with Find for its components, rank, marriage years, case mix and readings.</p>`;
        return;
      }
      const a = c.acs, r = c.risk, t = c.filings.ttm; const quad = idxQuad(c, oppPct); const mcs = c.msa ? CTY.filter(x => x.msa === c.msa).sort((x, y) => (y.di || 0) - (x.di || 0)) : []; const mr = mcs.findIndex(x => x.fips === c.fips) + 1;
        const vals = { filing: N(c.rates.div_per_1k_married, 1) + ' per 1k married', haz: N(r.haz_pred, 1) + ' per 1k', sep: N(a.sep_per_1k_married, 0) + ' per 1k', econ: 'shock ' + N(c.esi, 0), struct: 'z ' + N(c.comp_struct, 2), strain: 'z ' + N(c.comp_strain, 2), supply: c.rates.lawoffices ? N(c.rates.filings_per_lawoffice, 1) + ' per office' : 'no office' };
        const wDur = k => { let s = 0, w = 0; CTY.forEach(x => { if (isN(x.risk[k]) && x.acs.married) { s += x.risk[k] * x.acs.married; w += x.acs.married; } }); return w ? s / w : null; };
        const durTX = IDX_DUR.map(d => ({ l: d[1], v: wDur(d[0]), color: d[2] })), durC = IDX_DUR.map(d => ({ l: d[1], v: r[d[0]], color: d[2] }));
        const mixOf = o => IDX_MIX.map(m => ({ l: m[1], v: m[0] === 'div_nk' ? (o.div || 0) - (o.div_k || 0) : (o[m[0]] || 0), color: m[2] }));
        const txMix = {}; ['div', 'div_k', 'sapcr', 'po', 'mod', 'enf', 'ivd', 'cps', 'adopt'].forEach(k => { txMix[k] = stTTM(k); });
        const notes = idxNotes(c, TH); const watched = ixWatchIn(c.fips); const firm = IX_FIRM().includes(c.fips);
        host.innerHTML = `<div class="ix-head"><div><div class="ix-eb">${esc(c.msa_title ? MNAME(c.msa_title) : 'Non metro')} · grade ${esc(c.grade)}${firm ? ' · a county you serve' : ''}</div><h3>${esc(c.name)} County</h3><div class="small">${N(a.married)} married adults · ${N(t.div)} divorce filings in 12 months</div></div><span class="pill" title="${esc(quad.t)}">${esc(quad.q === 'No law office counted' ? quad.q : 'Paid: ' + quad.q)}</span></div>
          <div class="ix-big"><b>${N(c.di, 0)}</b><span>Dissolution Index · rank ${c.di_rank} of 254 (1 is the highest)${mr ? ` · ${mr} of ${mcs.length} in the metro` : ''}</span></div>
          <div class="ix-sec">Components against the Texas county mean</div>${IDX_COMP.map(([k, nm]) => idxZbar(`${nm} ${Math.round(D.weights[k] * 100)}%`, vals[k], idxZ(c, k, ZS))).join('')}
          <p class="small ix-fine">Bars are standard deviations from the mean of the counties with data; right of center adds to the index.</p>
          <div class="ix-sec">Years married (PUMS)</div>${idxStackPair(c.name, durC, durTX)}<p class="small ix-fine">Shares in bold are the county, the others Texas.</p>
          <div class="ix-sec">Case mix, ${esc(c.filings.ttm_label)}</div>${idxStackPair(c.name, mixOf(t), mixOf(txMix))}
          ${notes.map(n => callout(n.kind, n.title, n.html)).join('')}
          ${ixAcctLine(c.fips)}${watched.length ? `<div class="ix-own"><b>Firms watched here:</b> ${watched.slice(0, 6).map(w => esc(w.name)).join(', ')}${watched.length > 6 ? ` and ${watched.length - 6} more` : ''}.</div>` : ''}
          <div class="ix-btns"><button type="button" class="btn sm" data-h="desk">Campaign Desk ↗</button><button type="button" class="btn sm" data-h="forge">Site Forge ↗</button><button type="button" class="btn sm" data-h="lines">Service Lines ↗</button><button type="button" class="btn sm" data-h="econ">Economic Shock ↗</button><button type="button" class="btn sm" data-h="ground">Ground Truth ↗</button><button type="button" class="btn sm" data-h="watch">Competitor Watch ↗</button>${c.msa && AT_BY_CODE[c.msa] ? '<button type="button" class="btn sm" data-h="atlas">Metro Atlas ↗</button>' : ''}<button type="button" class="btn sm" data-h="clear">Texas view</button></div>`;
        const go = { desk: () => goModule('desk', { geo: 'cty:' + c.fips, counties: [c.fips] }), forge: () => goModule('forge', { counties: [c.fips] }), lines: () => goModule('lines', { county: c.fips }), econ: () => goModule('econ', { county: c.fips }), ground: () => goModule('ground', { county: c.fips }), watch: () => goModule('watch', { county: c.fips, from: 'index' }), atlas: () => openAtlas(AT_BY_CODE[c.msa]), clear: () => clear() };
        $$('[data-h]', host).forEach(b => b.onclick = () => go[b.dataset.h]());
    }
    function detail() { const c = CI[st.sel]; if (!c) { R('#idxDetailSub').textContent = 'No county selected.'; R('#idxDetail').innerHTML = '<p class="small">Select a county on the map, in the table or with Find to see every figure behind its index.</p>'; return; } R('#idxDetailSub').textContent = c.name + ' County, ' + (c.msa_title ? MNAME(c.msa_title) : 'outside any metro'); R('#idxDetail').innerHTML = countyDetailHTML(c); mountCompChart(c, root); }
    // the Texas view button clears the selection; a map click, the table and Find select
    function select(id, quiet) {
      if (!CI[id]) return; st.sel = id; st.cleared = null; store.set('sev.county', id); markSel(mapEl, id); side(); detail(); tiles(); if (tbl) tbl.setSel(id, quiet);
    }
    function clear() { st.cleared = store.get('sev.county', st.sel); st.sel = null; markSel(mapEl, null); side(); detail(); tiles(); if (tbl) tbl.setSel(null, true); }
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'di', l: 'Index', fmt: v => N(v, 0), h: 'Dissolution Index (percentile)', d: 0 }, { k: 'rank', l: 'Rank', h: 'Rank of 254' }, { k: 'grade', l: 'Grade', fmt: v => `<span class="grade ${v}">${v}</span>`, h: 'Confidence grade' }, { k: 'eq', l: 'Equal wt', fmt: v => N(v, 0), h: 'Dissolution Index, equal weights', d: 1 }, { k: 'nf', l: 'No filing', fmt: v => N(v, 0), h: 'Index without the filing component', d: 1 }, { k: 'pop', l: 'Pop 2025', fmt: v => N(v), h: 'Population 2025 (Census Vintage 2025)', d: 0 }, { k: 'married', l: 'Married', fmt: (v, r) => N(v) + (v < IDX_FLOOR ? ' <span class="small">small</span>' : ''), h: 'Married adults (ACS)', d: 0 }, { k: 'div', l: 'Divorce filings', fmt: v => N(v), h: 'Divorce filings, last 12 months', d: 0 }, { k: 'rate', l: 'per 1k married', fmt: v => N(v, 1), h: 'Divorce filings per 1,000 married adults', d: 1 }, { k: 'yoy', l: 'vs prior yr', fmt: v => sgn(v), h: 'Divorce filings change vs prior 12 months (%)', d: 1 }, { k: 'v19', l: 'vs 2019', fmt: v => sgn(v), h: 'Divorce filings change vs 2019 (%)', d: 1 }, { k: 'divk', l: 'with kids', fmt: v => P(v, 0), h: 'Divorce filings with children (%)', d: 0, pct: true }, { k: 'sapcr', l: 'SAPCR', fmt: v => N(v), h: 'SAPCR filings, last 12 months', d: 0 }, { k: 'po', l: 'PO', fmt: v => N(v), h: 'Protective order filings, last 12 months', d: 0 }, { k: 'haz', l: 'Hazard', fmt: v => N(v, 1), h: 'Composition hazard (divorces per 1,000 married a year, model)', d: 1 }, { k: 'sep', l: 'Separated /1k', fmt: v => N(v, 1), h: 'Separated per 1,000 married (ACS)', d: 1 }, { k: 'esi', l: 'Econ shock', fmt: v => N(v, 0), h: 'Economic Shock Index (percentile)', d: 0 }, { k: 'ur', l: 'Unemp', fmt: v => P1(v), h: 'Unemployment rate, latest month (%)', d: 1 }, { k: 'offices', l: 'Law offices', fmt: v => v ? N(v) : 'none', h: 'Law offices (CBP 2023)', d: 0 }, { k: 'fpo', l: 'Filings/office', fmt: (v, r) => r.offices ? N(v, 1) : 'no office', h: 'Private family filings per law office', d: 1 }, { k: 'quad', l: 'Paid', fmt: v => esc(v), cls: 'l', h: 'Paid quadrant (opportunity and room percentiles at 50)' }, { k: 'firm', l: 'Yours', fmt: v => v ? 'served' : '', h: 'Served by the firm (firm profile)' }, { k: 'msa', l: 'Metro', fmt: v => esc(v), cls: 'l wrap', h: 'Metro area' }];
    const rowsOf = () => { const fs = new Set(IX_FIRM()); return objs().map(c => ({ _id: c.fips, fips: c.fips, name: c.name, di: c.di, rank: c.di_rank, grade: c.grade, eq: idxEqual(c), nf: idxComposite(c, D.weights, 'filing'), pop: c.pop2025, married: c.acs.married, div: c.filings.ttm.div, rate: c.rates.div_per_1k_married, yoy: c.rates.div_yoy, v19: c.rates.div_vs_2019, divk: c.rates.div_k_share, sapcr: c.filings.ttm.sapcr, po: c.filings.ttm.po, haz: c.risk.haz_pred, sep: c.acs.sep_per_1k_married, esi: c.esi, ur: c.laus ? c.laus.ur : null, offices: c.rates.lawoffices || 0, fpo: c.rates.filings_per_lawoffice, quad: idxQuad(c, oppPct).q, firm: fs.has(c.fips) ? 1 : 0, msa: c.msa_title ? MNAME(c.msa_title) : 'non metro' })); };
    tbl = table(R('#idxTable'), { cols, rows: rowsOf(), sort: { k: 'di', dir: -1 }, onRow: id => select(id), selected: st.sel, caption: 'All Texas counties ranked by the Dissolution Index' });
    R('#idxLayer').onchange = e => { st.layer = e.target.value; store.set('sev.index.layer', st.layer); drawIdx(); markSel(mapEl, st.sel); };
    R('#idxMetro').onchange = e => { st.metro = e.target.value; drawIdx(); markSel(mapEl, st.sel); tbl.setRows(rowsOf()); if (!CI[st.sel]) side(); };
    R('#idxLabels').onchange = () => { drawIdx(); markSel(mapEl, st.sel); };
    R('#idxPins').onchange = e => { st.pins = e.target.checked; store.set('sev.index.pins', st.pins); decorate(); };
    R('#idxClear').onclick = () => clear();
    // find: a name or FIPS code; 'Harris County' and 'harris co' work, an exact name wins, then a prefix, then any part of a name
    const findCounty = raw => { const q = String(raw || '').trim().toLowerCase().replace(/\s+/g, ' ').replace(/,?\s*(county|cnty|co\.?)(,?\s*(tx|texas))?$/, '').trim(); if (!q) return null; const f = /^\d+$/.test(q) ? (q.length === 3 ? '48' + q : q) : null; const big = a => a.sort((x, y) => y.pop2025 - x.pop2025)[0] || null; return CTY.find(c => c.fips === f) || CTY.find(c => c.name.toLowerCase() === q) || big(CTY.filter(c => c.name.toLowerCase().startsWith(q))) || big(CTY.filter(c => c.name.toLowerCase().includes(q))) || null; };
    const qMsg = R('#idxQMsg');
    let qT = 0; R('#idxQ').oninput = e => { clearTimeout(qT); const t = e.target; qT = setTimeout(() => qFind({ target: t }), 250); };
    const qFind = e => { const v = e.target.value; if (!v.trim()) { qMsg.textContent = ''; e.target.removeAttribute('aria-invalid'); return; } const hit = findCounty(v); e.target.setAttribute('aria-invalid', String(!hit)); qMsg.textContent = hit ? '' : 'No county matches. Try a county name or a FIPS code.'; if (hit && hit.fips !== st.sel) select(hit.fips); };
    R('#idxQ').onkeydown = e => { if (e.key === 'Enter') { clearTimeout(qT); const hit = findCounty(e.target.value); if (hit) { select(hit.fips); qMsg.textContent = hit.name + ' County selected.'; } else qMsg.textContent = 'No county matches. Try a county name or a FIPS code.'; } };
    R('#idxCsv').onclick = () => exportText(expName('index', st.metro === 'firm' ? 'your counties' : st.metro ? MNAME(MSA[st.metro].title) : 'texas'), csv(tbl.sorted(), xcols([cols[0], { k: 'fips', l: 'FIPS' }].concat(cols.slice(1))), { note: typeof csvNote === 'function' ? csvNote('index', [`Dissolution Index: the weighted mean of seven component percentiles (weights ${IDX_COMP.map(([k, n]) => n.toLowerCase() + ' ' + Math.round(D.weights[k] * 100) + '%').join(', ')}). Equal weight and no filing columns are the checks in the method card.`, `Counties under ${N(IDX_FLOOR)} married adults are small: one filing moves their rates a full point per 1,000. ${st.metro ? 'Filtered to ' + (st.metro === 'firm' ? 'your counties' : MNAME(MSA[st.metro].title)) + '.' : 'All 254 counties.'}`]) : null }));
    // ---- the method card: weights at county and ZIP, what each component measures, its source and grade
    const MEAS = { filing: ['Divorce filings per 1,000 married adults, shrunk toward the state rate with weight n/(n+60)', 'Office of Court Administration', 'A'], haz: ['The PUMS hazard model applied to the county\'s married population', 'ACS 2020 to 2024 PUMS', 'B'], sep: ['Separated per 1,000 married, shrunk by the ACS coefficient of variation', 'ACS 2020 to 2024', 'B'], econ: ['Mean of six standardized measures: claims vs 2019 and vs a year ago, unemployment change vs a year ago and vs 2019, WARN workers per 1,000 jobs, payroll change; each shrunk by county size', 'TWC, BLS LAUS and QCEW', 'B'], struct: ['Married with children, cohabiting with children, unmarried births, single parents, grandparents responsible, married 25 to 44', 'ACS 2020 to 2024', 'B'], strain: ['Rent and mortgage burden, SNAP, married with children in poverty, households under $35,000', 'ACS 2020 to 2024', 'B'], supply: ['Log private family filings per law office (ZIP: log expected filings per law office plus one)', 'CBP and ZBP 2023 with OCA', 'C'] };
    const wsum = sum(Object.values(D.weights)), zsum = sum(Object.values(D.zweights || {}));
    R('#idxMethod').innerHTML = `<p class="small">Each component is ranked across the counties that have it (a percentile), multiplied by its weight and summed; the weights of a component a county lacks drop out (the supply gap is missing in the ${CTY.filter(c => !isN(c.pct.supply)).length} counties with no law office counted). The ZIP index used by modules 07 and 12 drops the filing component, which does not exist below the county, and reweights the rest.</p>
      <div class="tblwrap"><table class="t ix-meth"><caption class="vh">Index components, weights, sources and grades</caption><thead><tr><th scope="col" class="l">Component</th><th scope="col">County</th><th scope="col">ZIP</th><th scope="col">Grade</th></tr></thead><tbody>${IDX_COMP.map(([k, nm]) => `<tr><td class="l wrap"><b>${esc(nm)}</b><div class="small">${esc(MEAS[k][0])}. ${esc(MEAS[k][1])}.</div></td><td>${Math.round(D.weights[k] * 100)}%</td><td>${D.zweights && isN(D.zweights[k]) ? Math.round(D.zweights[k] * 100) + '%' : 'none'}</td><td><span class="grade ${MEAS[k][2]}">${MEAS[k][2]}</span></td></tr>`).join('')}<tr><td class="l"><b>Total</b></td><td>${Math.round(wsum * 100)}%</td><td>${Math.round(zsum * 100)}%</td><td></td></tr></tbody></table></div>
      ${callout('judg', 'Judgment call: the weights are set, not fitted', `No study gives the causal share of each component in a filing, so the weights are a stated judgment: court filings, the one direct measure, carry ${Math.round(D.weights.filing * 100)}%; composition, separation and the economy ${Math.round(D.weights.haz * 100)}% each; structure and strain ${Math.round(D.weights.struct * 100)}%; supply ${Math.round(D.weights.supply * 100)}% because the office count includes every kind of law office. The sensitivity panel shows how little the ranking depends on them.`)}
      ${callout('judg', 'Judgment call: ability to pay is left out on purpose', 'Income and home value are not in the index. Demand is a property of the married population and the courts; whether a household can pay a retainer belongs to the paid acquisition model (module 07) and the fee pools (module 06). Keeping them apart lets the maps disagree usefully.')}`;
    // ---- the component correlation matrix (a table, so a screen reader reads it cell by cell), from SEV_STATS
    (function corr() {
      const ks = IDX_COMP.map(x => x[0]); const nm = {}; IDX_COMP.forEach(x => { nm[x[0]] = x[1]; }); const cols2 = {}; ks.forEach(k => { cols2[k] = CTY.map(c => c.pct[k]); }); const M = SEV_STATS.corr(cols2, ks);
      if (typeof corrMatrix === 'function') { const lab = {}; ks.forEach(k => { lab[k] = nm[k] + ' ' + Math.round(D.weights[k] * 100) + '%'; }); corrMatrix(R('#idxCorr'), { keys: ks, labels: lab, matrix: M, caption: 'Correlation of the index components across Texas counties', corner: 'Component and weight' }); } else R('#idxCorr').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t corr"><caption class="vh">Correlation of the index components</caption><thead><tr><th scope="col">Component</th>${ks.map(k => `<th scope="col">${esc(nm[k])}</th>`).join('')}</tr></thead><tbody>${ks.map(a => `<tr><th scope="row">${esc(nm[a])} <span class="small">${Math.round(D.weights[a] * 100)}%</span></th>${ks.map(b => { const v = M[a][b]; const bg = isN(v) && a !== b ? divergeColor(v) : 'var(--sunk)'; return `<td style="background:${bg};color:${a === b ? 'var(--ink-3)' : inkOn(bg)}">${isN(v) ? MINUS(v.toFixed(2)) : NA}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div></div>`;
      const pairs = []; ks.forEach((a, i) => ks.slice(i + 1).forEach(b => { if (isN(M[a][b])) pairs.push([a, b, M[a][b]]); })); pairs.sort((x, y) => Math.abs(y[2]) - Math.abs(x[2])); const s0 = pairs[0], w0 = pairs[pairs.length - 1];
      const mv = VAL.movers.filter(m => m.d);
      R('#idxSens').innerHTML = `<p class="small" style="margin-top:10px"><b>They are not one variable.</b> The strongest pair is ${esc(nm[s0[0]].toLowerCase())} with ${esc(nm[s0[1]].toLowerCase())} (r ${MINUS(s0[2].toFixed(2))}); the weakest ${esc(nm[w0[0]].toLowerCase())} with ${esc(nm[w0[1]].toLowerCase())} (r ${MINUS(w0[2].toFixed(2))}).</p>
        <p class="small"><b>Sensitivity.</b> An index with every weight equal correlates r = ${N(VAL.eq.r, 3)} with the weighted one (Spearman ρ = ${N(VAL.eq.rho, 3)}, ${N(VAL.eq.n)} counties). ${VAL.v.eq === 'holds' ? 'The ranking barely depends on the weights.' : 'The ranking depends on the weights; read the equal weight layer beside the index.'} The counties that move most${mv.length ? ': ' + mv.map(m => `${esc(m.name)} (rank ${m.from} to ${m.to})`).join(', ') : ' do not move'}. Map the <button type="button" class="linkbtn" id="idxEqLayer">equal weight layer</button> to see them.</p>`;
      const b = R('#idxEqLayer'); if (b) b.onclick = () => { st.layer = 'di_eq'; R('#idxLayer').value = 'di_eq'; drawIdx(); markSel(mapEl, st.sel); mapEl.scrollIntoView({ block: 'center', behavior: 'smooth' }); };
    })();
    // ---- validation: the composite without filings against the filing rate (grade A and B), and the out of time test
    (function validate() {
      const AB = VAL.ab.map(f => CI[f]); const nf = c => idxComposite(c, D.weights, 'filing');
      const gcol = g => g === 'A' ? 'var(--s1)' : g === 'B' ? 'var(--s3)' : 'var(--s4)'; const gkey = cd => `<span class="legendc"><span><i style="background:var(--s1)"></i>Grade A</span><span><i style="background:var(--s3)"></i>Grade B</span>${cd ? '<span><i style="background:var(--s4)"></i>Grade C or D</span>' : ''}</span>`;
      scatter(R('#idxSc1'), { title: 'Index without filings against divorce filings per 1,000 married, grade A and B counties', W: 560, H: 300, ylog: true, xlab: 'Index without the filing component', ylab: 'Divorce filings per 1,000 married (log)', xfmt: v => N(v, 0), yfmt: v => N(v), onPoint: id => select(id), points: AB.map(c => ({ id: c.fips, label: c.name, x: nf(c), y: c.rates.div_per_1k_married, r: c.acs.married, color: gcol(c.grade) })), tip: p => `<b>${esc(p.label)} County</b><div class="row"><span>Index without filings</span><span>${N(p.x, 0)}</span></div><div class="row"><span>Filings per 1,000 married</span><span>${N(p.y, 1)}</span></div><div class="row"><span>Grade</span><span>${esc(CI[p.id].grade)}</span></div>` });
      R('#idxSc1n').innerHTML = gkey(false) + `<b>Held out filings:</b> Pearson r ${N(VAL.filing.r, 2)} (95% interval ${N(VAL.filing.lo, 2)} to ${N(VAL.filing.hi, 2)}), Spearman ρ ${N(VAL.filing.rho, 2)}, ${N(VAL.filing.n)} counties graded A or B, sized by married adults. ${VAL.v.filing === 'holds' ? 'The six components that never saw a court count rank the counties the way the courts do.' : VAL.v.filing === 'weak' ? 'Positive but weak.' : 'This check fails.'}`;
      const Y = VAL.ytd.fips.map(f => CI[f]);
      scatter(R('#idxSc2'), { title: 'Dissolution Index against the 2026 year to date change in divorce filings', W: 560, H: 300, xlab: 'Dissolution Index', ylab: `Divorce filings, Jan to ${MO[((VAL.ytd.months || 8) - 1) % 12]} 2026 vs 2025 (%)`, xfmt: v => N(v, 0), yfmt: v => sgn(v, 0), onPoint: id => select(id), points: Y.map((c, i) => ({ id: c.fips, label: c.name, x: c.di, y: VAL.ytd.ch[i] * 100, r: c.acs.married, color: gcol(c.grade) })), tip: p => `<b>${esc(p.label)} County</b><div class="row"><span>Index</span><span>${N(p.x, 0)}</span></div><div class="row"><span>2026 so far vs 2025</span><span>${sgn(p.y, 1)}</span></div>` });
      R('#idxSc2n').innerHTML = gkey(true) + `<b>Out of time:</b> Pearson r ${N(VAL.ytd.di.r, 2)} (95% interval ${N(VAL.ytd.di.lo, 2)} to ${N(VAL.ytd.di.hi, 2)}), Spearman ρ ${N(VAL.ytd.di.rho, 2)}, ${N(VAL.ytd.di.n)} counties with monthly reports, no reporting gap and 50 or more filings in the same months of 2025. ${VAL.v.ytdDi === 'fails' ? 'This check fails.' : VAL.v.ytdDi === 'weak' ? 'Positive but weak.' : 'This check holds.'}`;
      const vt = v => v === 'holds' ? '<span class="pill good">holds</span>' : v === 'weak' ? '<span class="pill p-warn">weak</span>' : v === 'fails' ? '<span class="pill bad">fails</span>' : '<span class="pill">n/a</span>';
      const row = (name, what, t, v) => `<tr><td class="l wrap"><b>${esc(name)}</b><div class="small">${esc(what)}</div></td><td>${N(t.r, 2)}</td><td>${N(t.rho, 2)}</td><td>${N(t.n)}</td><td>${isN(t.p) ? (t.p < 0.001 ? 'under 0.001' : N(t.p, 3)) : NA}</td><td>${vt(v)}</td></tr>`;
      const mo = MO[((VAL.ytd.months || 8) - 1) % 12];
      R('#idxVal').innerHTML = `<div class="tblwrap" style="margin-top:12px"><table class="t ix-val"><caption class="vh">Index checks</caption><thead><tr><th scope="col" class="l">Check</th><th scope="col">Pearson r</th><th scope="col">Spearman</th><th scope="col">Counties</th><th scope="col">p</th><th scope="col">Verdict</th></tr></thead><tbody>
        ${row('Equal weights', 'The index with every weight equal against the weighted index, all counties', VAL.eq, VAL.v.eq)}
        ${row('Held out: court filing rate', 'The six non filing components against divorce filings per 1,000 married adults, grade A and B', VAL.filing, VAL.v.filing)}
        ${row('Held out: survey divorces', 'The same composite against Texans who report a divorce in the past year per 1,000 married (PUMS, regional for small counties), grade A and B', VAL.hazobs, VAL.v.hazobs)}
        ${row('Out of time: the index', `The full index against the change in divorce filings, January to ${mo} 2026 against the same months of 2025`, VAL.ytd.di, VAL.v.ytdDi)}
        ${row('Out of time: without filings', 'The six non filing components against the same change', VAL.ytd.nf, VAL.v.ytdNf)}
        ${row('Out of time: the shock index alone', 'The Economic Shock Index against the same change', VAL.ytd.esi, VAL.ytd.esi.p < 0.05 && VAL.ytd.esi.r > 0 ? 'weak' : 'fails')}
      </tbody></table></div>
      ${callout('judg', 'Judgment call: these are checks, not proofs, and the out of time test fails', `The composite that never saw a court count tracks the filing rate across graded counties (r ${N(VAL.filing.r, 2)}), so the non filing components measure the same demand the courts record. Against the survey's own divorce reports the link is ${VAL.v.hazobs === 'holds' ? 'as clear' : VAL.v.hazobs === 'weak' ? 'positive but weaker' : 'absent'} (r ${N(VAL.hazobs.r, 2)}): those reports come from survey areas that pool small counties, and the composition model was fit on the same microdata, so this check is the less independent of the two. <b>Where it fails:</b> the index does not say which counties' filings rise in 2026. Against the change from January to ${mo} (${N(VAL.ytd.up)} of ${N(VAL.ytd.di.n)} counties up), r is ${N(VAL.ytd.di.r, 2)} for the index, ${N(VAL.ytd.nf.r, 2)} without filings and ${N(VAL.ytd.esi.r, 2)} for the shock index alone; the expected lift from claims ${VAL.ytd.lift.p < 0.05 && VAL.ytd.lift.r > 0 ? 'is the only measure that registers' : 'does not register either'} (r ${N(VAL.ytd.lift.r, 2)}, p ${N(VAL.ytd.lift.p, 2)}). The index ranks the level of demand, not its direction this year: use it to choose where to compete and the monthly series (module 02) and the Live Desk (module 25) to time it. Evidence (module 27) carries the spatial clusters, the court capture ratio and the signal matrix.`)}
      <div class="ix-btns"><button type="button" class="btn sm" id="idxGoEvidence">Evidence ↗</button><button type="button" class="btn sm" id="idxGoGround">Ground Truth ↗</button></div>`;
      R('#idxGoEvidence').onclick = () => goModule('evidence', CI[st.sel] ? { county: st.sel } : undefined); R('#idxGoGround').onclick = () => goModule('ground', CI[st.sel] ? { county: st.sel } : undefined);
    })();
    drawIdx(); if (CI[st.sel]) select(st.sel, true); else { side(); detail(); tiles(); }
    const live = () => root.isConnected;
    BUS.on('firm', () => { if (!live()) return; const cur = R('#idxMetro').value; R('#idxMetro').innerHTML = metroOpts().map(o => `<option value="${esc(o[0])}">${esc(o[1])}</option>`).join(''); R('#idxMetro').value = metroOpts().some(o => o[0] === cur) ? cur : ''; st.metro = R('#idxMetro').value; drawIdx(); markSel(mapEl, st.sel); tbl.setRows(rowsOf()); side(); });
    BUS.on('watch', () => { if (live()) { decorate(); side(); } });
    BUS.on('actuals', () => { if (live() && CI[st.sel]) side(); });
    this.sync = () => { const f = store.get('sev.county', st.sel); if (CI[f] && f !== st.sel && f !== st.cleared) select(f); };
    // goModule('index', {county}) or the link #index/<FIPS or county name>; #index/texas clears the selection
    this.receive = p => { if (!p) return; if (CI[p.county]) { if (p.county !== st.sel) select(p.county); return; } if (p.arg) { if (/^(texas|tx|state)$/i.test(p.arg)) { clear(); return; } const hit = findCounty(p.arg); if (hit && hit.fips !== st.sel) select(hit.fips); } };
  },
  onShow() { if (this.sync) this.sync(); }
});
function toggleTheme() { const r = document.documentElement; const cur = r.getAttribute('data-theme'); const sysDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches; const isDark = cur ? cur === 'dark' : sysDark; r.setAttribute('data-theme', isDark ? 'light' : 'dark'); store.set('sev.theme', isDark ? 'light' : 'dark'); }
