'use strict';
/* Module 01: Dissolution Index */
const LAYERS_CTY = {
  di: { l: 'Dissolution Index (composite, percentile)', ramp: 'ember', v: c => c.di, f: v => N(v, 0), q: false },
  filing: { l: 'Divorce filings per 1,000 married adults (trailing 12 months)', ramp: 'ember', v: c => c.rates.div_per_1k_married, f: v => N(v, 1) },
  filing10k: { l: 'Divorce filings per 10,000 residents', ramp: 'ember', v: c => c.rates.div_per_10k_pop, f: v => N(v, 1) },
  yoy: { l: 'Divorce filings, change vs prior 12 months', ramp: 'div', v: c => c.rates.div_yoy, f: v => sgn(v, 1) },
  vs2019: { l: 'Divorce filings, change vs 2019', ramp: 'div', v: c => c.rates.div_vs_2019, f: v => sgn(v, 1) },
  haz: { l: 'Composition hazard: modeled divorces per 1,000 married (PUMS model)', ramp: 'ember', v: c => c.risk.haz_pred, f: v => N(v, 1) },
  sep: { l: 'Separated adults per 1,000 married (ACS)', ramp: 'ember', v: c => c.acs.sep_per_1k_married, f: v => N(v, 1) },
  esi: { l: 'Economic Shock Index (percentile)', ramp: 'steel', v: c => c.esi, f: v => N(v, 0) },
  struct: { l: 'Family structure component (z score)', ramp: 'amber', v: c => c.comp_struct, f: v => N(v, 2) },
  strain: { l: 'Financial strain component (z score)', ramp: 'amber', v: c => c.comp_strain, f: v => N(v, 2) },
  supply: { l: 'Private family filings per law office (competition gap)', ramp: 'moss', v: c => c.rates.filings_per_lawoffice, f: v => N(v, 1) },
  divk: { l: 'Share of divorce filings with children', ramp: 'ember', v: c => c.rates.div_k_share, f: v => P(v, 0) },
  po: { l: 'Protective order filings per 10,000 residents', ramp: 'ember', v: c => c.rates.po_per_10k, f: v => N(v, 1) },
  pop: { l: 'Population 2025', ramp: 'slate', v: c => c.pop2025, f: v => K(v), log: true }
};
function layerScale(L, objs) {
  const vals = objs.map(L.v);
  // the color scale stops at the 2nd and 98th percentiles (97th for diverging layers); a legend end that is a stop, not the real
  // minimum or maximum, reads '≤' or '≥'
  const ok = vals.filter(isN);
  // diverging legends print their ends in the layer's own unit (points stay points, percents stay percents)
  if (L.ramp === 'div' || L.ramp === 'divinv') { const inv = L.ramp === 'divinv' ? -1 : 1; const mx = Math.max(...ok.map(Math.abs).sort((a, b) => a - b).slice(0, Math.floor(vals.length * 0.97)), 1); const neg = inv > 0 ? RAMPS.slate : RAMPS.leaf, pos = inv > 0 ? RAMPS.leaf : RAMPS.slate; const lf = L.lf || L.f || (v => sgn(v, 0)); return { color: v => divergeColor(inv * clamp(v / mx, -1, 1)), legend: { min: (ok.some(v => v < -mx) ? '≤ ' : '') + lf(-mx), max: (ok.some(v => v > mx) ? '≥ ' : '') + lf(mx), css: `linear-gradient(90deg,${neg[7]},${neg[4]},var(--rp-mid),${pos[4]},${pos[7]})` } }; }
  // a log layer colors a true zero with the lowest step (a map can give zero its own class with drawMap's alt); its legend runs over the values above zero
  const sc = L.log ? (() => { const q = quantScale(vals.map(v => isN(v) && v > 0 ? Math.log(v) : null)); return v => v > 0 ? q(Math.log(v)) : 0; })() : (L.q === false ? (v => clamp(v / 100, 0, 1)) : quantScale(vals));
  const sorted = (L.log ? ok.filter(v => v > 0) : ok).slice().sort((a, b) => a - b); if (!sorted.length) return { color: () => null, legend: { min: NA, max: NA, css: rampCSS(L.ramp) } };
  const pick = p => sorted[clamp(Math.floor(p * (sorted.length - 1)), 0, sorted.length - 1)];
  const lo = L.q === false ? 0 : pick(0.02), hi = L.q === false ? 100 : pick(0.98);
  const lo_c = L.q !== false && sorted[0] < lo, hi_c = L.q !== false && sorted[sorted.length - 1] > hi;
  return { color: v => rampColor(L.ramp, sc(v)), legend: { min: (lo_c ? '≤ ' : '') + L.f(lo), max: (hi_c ? '≥ ' : '') + L.f(hi), css: rampCSS(L.ramp) } };
}
// the map view of a metro: its counties' extent in state map units, padded, at the state map's shape so the map keeps its size
const IDX_BOX = {};
function metroBox(code) {
  if (IDX_BOX[code]) return IDX_BOX[code]; const G = GEO.state; let x0 = Infinity, y0 = Infinity, x1 = -Infinity, y1 = -Infinity;
  ((MSA[code] || {}).counties || []).forEach(f => { const n = (G.county[f] || '').match(/-?\d+(?:\.\d+)?/g) || []; for (let i = 0; i + 1 < n.length; i += 2) { const x = +n[i], y = +n[i + 1]; if (x < x0) x0 = x; if (x > x1) x1 = x; if (y < y0) y0 = y; if (y > y1) y1 = y; } });
  if (!isFinite(x0)) return null; let w = x1 - x0, h = y1 - y0; const pad = Math.max(w, h) * 0.08 + 6; x0 -= pad; y0 -= pad; w += 2 * pad; h += 2 * pad;
  const asp = G.W / G.H; if (w / h < asp) { const nw = h * asp; x0 -= (nw - w) / 2; w = nw; } else { const nh = w / asp; y0 -= (nh - h) / 2; h = nh; }
  return (IDX_BOX[code] = [x0, y0, w, h]);
}
function countyTipHTML(c, extra) {
  return `<b>${esc(c.name)} County</b><div class="row"><span>Dissolution Index</span><span>${N(c.di, 0)} (rank ${c.di_rank})</span></div><div class="row"><span>Divorce filings, 12 mo</span><span>${N(c.filings.ttm.div)}</span></div><div class="row"><span>per 1,000 married</span><span>${N(c.rates.div_per_1k_married, 1)}</span></div><div class="row"><span>Economic shock</span><span>${N(c.esi, 0)}</span></div><div class="row"><span>Grade</span><span>${c.grade}</span></div>${extra || ''}`;
}
function countyDetailHTML(c) {
  const a = c.acs, r = c.risk, f = c.filings.ttm, e = c.econ, p = c.pools, la = c.laus || {}, ui = c.ui || {}, w = c.warn || {}, q = c.qcew || {};
  const hist = Object.keys(c.filings.hist).sort().map(y => ({ y: +y, v: c.filings.hist[y].div, m: c.filings.hist[y].months }));
  const g = c.grade; const gap = repGap(c); const noOff = !c.rates.lawoffices;
  return `<div class="detail">
  <div><h4>Identity</h4><dl class="kv"><dt>County</dt><dd>${esc(c.name)}</dd><dt>Metro</dt><dd>${esc((c.msa_title ? MNAME(c.msa_title) : 'non metro'))}</dd><dt>Population 2025</dt><dd>${N(c.pop2025)}</dd><dt>Growth since 2020</dt><dd>${sgn(c.pop_growth)}</dd><dt>Married adults</dt><dd>${N(a.married)}</dd><dt>Married couple families with kids</dt><dd>${N(a.mc_fam_kids)}</dd><dt>Confidence</dt><dd><span class="grade ${g}">${g}</span></dd><dt>Google Ads criterion</dt><dd>${esc(c.gt || NA)}</dd></dl></div>
  <div><h4>Court filings, ${esc(c.filings.ttm_label)}</h4>${gap ? `<p class="small" style="margin:0 0 6px"><b>Possible clerk reporting gap:</b> no divorce filings reported in the last ${gap.months} months after about ${N(gap.avg, 0)} a month the year before. Read these counts as incomplete.</p>` : ''}<dl class="kv"><dt>Divorce, with children</dt><dd>${N(f.div_k)}</dd><dt>Divorce, no children</dt><dd>${N((f.div || 0) - (f.div_k || 0))}</dd><dt>Custody (SAPCR)</dt><dd>${N(f.sapcr)}</dd><dt>Protective orders</dt><dd>${N(f.po)}</dd><dt>Modifications</dt><dd>${N(f.mod)}</dd><dt>Enforcement</dt><dd>${N(f.enf)}</dd><dt>Title IV-D support</dt><dd>${N(f.ivd)}</dd><dt>CPS</dt><dd>${N(f.cps)}</dd><dt>Adoption</dt><dd>${N(f.adopt)}</dd><dt>Divorces disposed</dt><dd>${N(f.d_div)}</dd><dt>Divorce filings vs prior 12 mo</dt><dd>${sgn(c.rates.div_yoy)}</dd><dt>vs 2019</dt><dd>${sgn(c.rates.div_vs_2019)}</dd></dl><div style="margin-top:6px">${spark(hist.filter(h => h.m === 12).map(h => h.v), 200, 30, 'var(--s1)')} <span class="small">annual divorce filings ${hist[0] ? hist[0].y : ''} to 2025</span></div></div>
  <div><h4>Composition (PUMS model, married adults)</h4><dl class="kv"><dt>Observed hazard per 1,000</dt><dd>${N(r.haz_obs, 1)}</dd><dt>Modeled hazard per 1,000</dt><dd>${N(r.haz_pred, 1)}</dd><dt>Married under 5 years</dt><dd>${P(r.dur_lt5, 0)}</dd><dt>Married 5 to 9 years</dt><dd>${P(r.dur_5_9, 0)}</dd><dt>Remarried (2nd+ marriage)</dt><dd>${P(r.remarried, 0)}</dd><dt>Married before 23</dt><dd>${P(r.young_mar, 0)}</dd><dt>Aged 18 to 34</dt><dd>${P(r.age_18_34, 0)}</dd><dt>Aged 50 to 64</dt><dd>${P(r.age_50_64, 0)}</dd><dt>Bachelor's or higher</dt><dd>${P(r.ba_plus, 0)}</dd><dt>Renters</dt><dd>${P(r.renter, 0)}</dd><dt>Spouse or self unemployed</dt><dd>${P(r.any_unemp, 1)}</dd><dt>Wife out earns husband</dt><dd>${P(r.wife_more, 0)}</dd><dt>Active duty in household</dt><dd>${P(r.mil_active, 1)}</dd><dt>Veteran</dt><dd>${P(r.veteran, 0)}</dd><dt>Commute 45 min or more</dt><dd>${P(r.long_commute, 0)}</dd></dl></div>
  <div><h4>Signals (ACS 2020 to 2024)</h4><dl class="kv"><dt>Separated per 1,000 married</dt><dd>${N(a.sep_per_1k_married, 1)}</dd><dt>Divorced adults (stock)</dt><dd>${N(a.divorced)}</dd><dt>Married aged 25 to 44</dt><dd>${P(a.mar_25_44_sh, 0)}</dd><dt>Married aged 55 and over</dt><dd>${P(a.mar_55p_sh, 0)}</dd><dt>Cohabiting couples with kids</dt><dd>${N(a.cohab_hh_kids)}</dd><dt>Single parent families</dt><dd>${N(a.sp_fam_kids)}</dd><dt>Births to unmarried mothers</dt><dd>${P(a.births_unmar_sh, 0)}</dd><dt>Grandparents responsible</dt><dd>${N(a.gp_resp)}</dd><dt>Median household income</dt><dd>${$$$(a.med_hh_inc)}</dd><dt>Rent burden 35%+</dt><dd>${P(a.rent_burden35_sh, 0)}</dd><dt>Mortgage burden 35%+</dt><dd>${P(a.mort_burden35_sh, 0)}</dd><dt>SNAP households</dt><dd>${P(a.snap_sh, 0)}</dd><dt>Married with kids in poverty</dt><dd>${P(a.mc_kids_pov_sh, 0)}</dd><dt>Moved in past year</dt><dd>${P(a.moved_sh, 0)}</dd></dl></div>
  <div><h4>Economy</h4><dl class="kv"><dt>Unemployment rate, ${esc(fmtDate(la.last))}</dt><dd>${P1(la.ur)}</dd><dt>Year earlier</dt><dd>${P1(la.ur_yago)}</dd><dt>2019 average</dt><dd>${P1(la.ur_2019)}</dd><dt>UI initial claims, last 13 weeks</dt><dd>${N(ui.w13)}</dd><dt>Same 13 weeks of 2019</dt><dd>${N(ui.w13_2019)}</dd><dt>Prior year window</dt><dd>${N(ui.w13_yago)}</dd><dt>WARN workers, last 12 months</dt><dd>${N(w.last12 ? w.last12.workers : 0)}</dd><dt>Payroll jobs, ${esc(fmtQ(q.last))}</dt><dd>${N(q.emp)}</dd><dt>Jobs, year over year</dt><dd>${sgn(q.emp_pct)}</dd><dt>Married adults where either spouse is unemployed</dt><dd>${N(e.married_exposed)}</dd><dt>Economic Shock Index</dt><dd>${N(c.esi, 0)}</dd><dt>Expected filings lift at 12 months</dt><dd>${sgn(e.expected.m12_pct)}</dd></dl></div>
  <div><h4>Supply and protection</h4><dl class="kv"><dt>Law offices (CBP 2023)</dt><dd>${noOff ? 'none recorded' : N(c.rates.lawoffices)}</dd><dt>Legal services jobs</dt><dd>${isN(c.rates.legal_emp) ? N(c.rates.legal_emp) : 'not published'}</dd><dt>Private family filings per office</dt><dd>${noOff ? 'no office' : N(c.rates.filings_per_lawoffice, 1)}</dd><dt>CPS removals FY2025</dt><dd>${c.dfps && isN(c.dfps.removals['2025']) ? N(c.dfps.removals['2025']) : 'not reported'}</dd><dt>Abuse investigations with family violence, FY2025</dt><dd>${c.dfps && isN(c.dfps.inv_fv['2025']) ? N(c.dfps.inv_fv['2025']) : 'not reported'}</dd></dl></div>
  </div><h4 style="font-family:var(--mono);font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--ink-3);margin:14px 0 6px;border-bottom:1px solid var(--line);padding-bottom:3px">Index components (percentile rank among the counties with data, with weights; supply ranks the 146 counties with a law office count)</h4><div class="chart" id="compChart_${c.fips}" style="max-width:640px"></div>`;
}
// a component with no data (supply where the Census counts no law office) reads n/a, not a percentile of 0
function mountCompChart(c) { const el = $('#compChart_' + c.fips); if (!el) return; const nm = { filing: 'Filing intensity', haz: 'Composition hazard', sep: 'Separation', econ: 'Economic shock', struct: 'Family structure', strain: 'Financial strain', supply: 'Supply gap' }; barChart(el, { title: c.name + ' County index components', rows: Object.keys(D.weights).map(k => { const v = isN(c.pct[k]) ? c.pct[k] : null; return { label: nm[k] + ' ' + Math.round(D.weights[k] * 100) + '%', value: v, color: rampColor('ember', 0.35 + 0.6 * (v || 0) / 100) }; }), W: 640, lw: 200, max: 100, fmt: v => isN(v) ? N(v, 0) : 'n/a' }); }
registerModule({
  key: 'index', num: '01', title: 'Dissolution Index', desc: 'Where Texas marriages are ending and where the next filings are forming, county by county',
  mount(root) {
    const st = { layer: 'di', sel: store.get('sev.county', '48201'), metro: '', q: '' };
    const tx = ST.annual; const y25 = tx['2025'], y19 = tx['2019'];
    const top = CTY.slice().sort((a, b) => (b.di || 0) - (a.di || 0));
    const totMarried = ST.acs.married; const ttmState = stTTM('div');
    root.innerHTML = mastHTML({ eyebrow: 'Module 01 · Dissolution Index · all 254 Texas counties', title: 'Dissolution Index', ribbon: { text: 'Open the Metro Atlas', go: 'atlas' }, dek: `Every Texas county scored on seven measured things: how many divorces its residents actually filed in the last twelve months (Office of Court Administration), how divorce prone its married population is by composition (a hazard model fit on ${N(D.pums.n)} married Texans in the Census microdata), how many couples are already separated but not yet filed, how hard the local economy is shocking families right now, the family structure that turns a divorce into a custody case, the financial strain that turns it into a fight, and how thin the supply of lawyers is against it. The map is where a family law firm should be looking; the tabs after it say what to do there.`, facts: [[N(ttmState), 'divorce filings statewide, ' + ttmSpan()], [N(y25.f_div), 'in calendar 2025 (' + sgn((y25.f_div / y19.f_div - 1) * 100) + ' vs 2019)'], [N(totMarried), 'married Texans (ACS 2020 to 2024)'], ['Data through', fmtDateL(META.oca_through) + ' filings, ' + fmtDate(META.ui_through) + ' claims']] }) + `
    <div class="toolbar"><span class="ttl">Dissolution Index</span><span class="sub">Seven graded components · county resolution · trailing twelve months</span><span class="sp"></span><button class="btn" id="idxCsv">↓ County CSV</button><button class="btn" data-go="ledger">Filings Ledger ↗</button><button class="btn" data-go="econ">Economic Shock ↗</button><button class="btn" data-go="paid">Paid Acquisition ↗</button></div>
    <div class="callout"><div class="h">Read this first: what the index is and is not</div><p>This maps <b>demand for family law work</b>, not misery. The filing component is real court activity reported monthly by every district clerk to the Office of Court Administration and pulled here for all 254 counties. The composition component is a model: it applies divorce hazards learned from 2020 to 2024 Census microdata (age, marriage duration, number of marriages, education, military service, age at marriage) to each county's married population. The economic component is live: weekly unemployment claims, monthly unemployment rates, WARN layoff notices and quarterly job counts. A high index means many filings per married adult, a married population built like the ones that divorce, a visible pipeline of separated couples, an economy under stress, and fewer law offices per case. <b>Grade A</b> counties have monthly filing data and tight Census margins; <b>grade D</b> counties are small enough that one busy month moves the number. Module 05 explains why an economic shock lowers filings first and raises them a year later.</p></div>
    <div class="tiles" id="idxTiles"></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', sel('idxLayer', Object.keys(LAYERS_CTY).map(k => [k, LAYERS_CTY[k].l]), st.layer))}${ctl('Metro filter', sel('idxMetro', [['', 'All Texas']].concat(Object.keys(MSA).sort((a, b) => MSA[b].pop2025 - MSA[a].pop2025).map(k => [k, MNAME(MSA[k].title)])), ''))}${ctl('Find a county', `<input type="search" id="idxQ" list="idxQList" placeholder="Harris or 48201" autocomplete="off" aria-describedby="idxQMsg"><datalist id="idxQList">${CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => `<option value="${esc(c.name)}"></option>`).join('')}</datalist><span class="small" id="idxQMsg" role="status" aria-live="polite"></span>`)}<label class="chk"><input type="checkbox" id="idxLabels" checked> Label the largest counties</label></div>
    <div class="split"><div class="mapwrap" id="idxMap"></div><div><h3 style="font-family:var(--display);font-size:20px" id="idxSelTitle"></h3><div id="idxSelBody" class="small"></div></div></div></div>
    <div class="panel" style="margin-bottom:14px"><h3>County detail</h3><div class="sub" id="detailSub"></div><div id="idxDetail"></div></div>
    <div class="panel" style="margin-bottom:14px"><h3>How the seven components move together</h3><div class="sub">Correlation of the component percentiles across the counties that have both (Pearson r). A pair near 0 adds independent information to the index; a strong pair partly counts the same thing twice. Supply covers the 146 counties with a law office count.</div><div id="idxCorr"></div></div>
    <div class="panel"><h3>All counties ranked</h3><div class="sub">Click a row to select it on the map. Sort any column. Filings are the trailing twelve months where monthly data exists (all metro counties) and calendar 2025 elsewhere.</div><div id="idxTable"></div></div>`;
    // links carry the selection: the county to the county modules, its metro to Paid Acquisition and the Metro Atlas
    const hand = k => { const c = CI[st.sel] || {}; return k === 'paid' || k === 'atlas' ? (c.msa ? { metro: c.msa } : null) : { county: st.sel }; };
    $$('[data-go]', root).forEach(b => b.onclick = () => goModule(b.dataset.go, hand(b.dataset.go)));
    function tiles() {
      const c = CI[st.sel];
      const hi = top[0];
      $('#idxTiles').innerHTML = tile('Highest index', esc(hi.name), `${N(hi.di, 0)} · ${N(hi.rates.div_per_1k_married, 1)} filings per 1,000 married`, hi.grade) + tile('Statewide filing rate', N(ttmState / totMarried * 1000, 1), 'divorce filings per 1,000 married adults, last 12 months', 'A') + tile('With children', P(stTTM('div_k') / ttmState, 0), 'of divorce filings involve minor children (custody attached)', 'A') + tile('Separated, not yet filed', N(ST.acs.separated), `separated Texans (ACS): ${N(ST.acs.sep_per_1k_married, 0)} per 1,000 married`, 'A') + tile('Composition hazard', N(D.pums.groups.all.haz, 1), 'divorces per 1,000 married adults per year, Texas microdata (SE ' + N(D.pums.groups.all.se, 2) + ')', 'A') + tile('Selected county', esc(c.name), `index ${N(c.di, 0)}, rank ${c.di_rank} of 254 · ${N(c.filings.ttm.div)} filings`, c.grade);
    }
    let mapEl = $('#idxMap'), tbl;
    function objs() { return CTY.filter(c => !st.metro || c.msa === st.metro); }
    function drawIdx() {
      const L = LAYERS_CTY[st.layer]; const os = objs(); const sc = layerScale(L, os); const inSet = new Set(os.map(c => c.fips));
      const big = (st.metro ? os : CTY).slice().sort((a, b) => b.pop2025 - a.pop2025).slice(0, 30).map(c => c.fips);
      drawMap(mapEl, { W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => inSet.has(id) ? L.v(CI[id]) : null, color: sc.color, label: id => countyTipHTML(CI[id], ['di', 'filing', 'esi'].includes(st.layer) ? '' : `<div class="row"><span>${esc(L.l)}</span><span>${esc(L.f(L.v(CI[id])))}</span></div>`), onSelect: id => select(id), selected: st.sel, outline: GEO.state.outline, cent: GEO.state.cent, labels: $('#idxLabels').checked ? big : [], labelText: id => CI[id].name, legend: Object.assign({ title: L.l }, sc.legend), title: st.metro ? MNAME(MSA[st.metro].title) + ' counties, ' + L.l : 'Texas counties, ' + L.l, view: st.metro ? metroBox(st.metro) : null, noDataLabel: st.metro ? 'outside the metro or no data' : 'no data' });
    }
    function select(id, quiet) { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); const c = CI[id]; $('#idxSelTitle').textContent = c.name + ' County'; $('#idxSelBody').innerHTML = `<dl class="kv" style="font-size:13px"><dt>Index</dt><dd>${N(c.di, 0)} · rank ${c.di_rank}</dd><dt>Divorce filings (12 mo)</dt><dd>${N(c.filings.ttm.div)}</dd><dt>per 1,000 married</dt><dd>${N(c.rates.div_per_1k_married, 1)}</dd><dt>Custody (SAPCR)</dt><dd>${N(c.filings.ttm.sapcr)}</dd><dt>Protective orders</dt><dd>${N(c.filings.ttm.po)}</dd><dt>Economic shock</dt><dd>${N(c.esi, 0)}</dd><dt>Metro</dt><dd>${esc((c.msa_title ? MNAME(c.msa_title) : 'non metro'))}</dd></dl>`; $('#detailSub').textContent = c.name + ' County, ' + (c.msa_title ? MNAME(c.msa_title) : 'outside any metro'); $('#idxDetail').innerHTML = countyDetailHTML(c); mountCompChart(c); tiles(); if (tbl) tbl.setSel(id, quiet); }
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'di', l: 'Index', fmt: v => N(v, 0), h: 'Dissolution Index (percentile)', d: 0 }, { k: 'rank', l: 'Rank', h: 'Rank of 254' }, { k: 'grade', l: 'Grade', fmt: v => `<span class="grade ${v}">${v}</span>`, h: 'Confidence grade' }, { k: 'pop', l: 'Pop 2025', fmt: v => N(v), h: 'Population 2025 (Census Vintage 2025)', d: 0 }, { k: 'div', l: 'Divorce filings', fmt: v => N(v), h: 'Divorce filings, last 12 months', d: 0 }, { k: 'rate', l: 'per 1k married', fmt: v => N(v, 1), h: 'Divorce filings per 1,000 married adults', d: 1 }, { k: 'yoy', l: 'vs prior yr', fmt: v => sgn(v), h: 'Divorce filings change vs prior 12 months (%)', d: 1 }, { k: 'v19', l: 'vs 2019', fmt: v => sgn(v), h: 'Divorce filings change vs 2019 (%)', d: 1 }, { k: 'divk', l: 'with kids', fmt: v => P(v, 0), h: 'Divorce filings with children (%)', d: 0, pct: true }, { k: 'sapcr', l: 'SAPCR', fmt: v => N(v), h: 'SAPCR filings, last 12 months', d: 0 }, { k: 'po', l: 'PO', fmt: v => N(v), h: 'Protective order filings, last 12 months', d: 0 }, { k: 'haz', l: 'Hazard', fmt: v => N(v, 1), h: 'Composition hazard (divorces per 1,000 married a year, model)', d: 1 }, { k: 'sep', l: 'Separated /1k', fmt: v => N(v, 1), h: 'Separated per 1,000 married (ACS)', d: 1 }, { k: 'esi', l: 'Econ shock', fmt: v => N(v, 0), h: 'Economic Shock Index (percentile)', d: 0 }, { k: 'ur', l: 'Unemp', fmt: v => P1(v), h: 'Unemployment rate, latest month (%)', d: 1 }, { k: 'offices', l: 'Law offices', fmt: v => v ? N(v) : 'none', h: 'Law offices (CBP 2023)', d: 0 }, { k: 'fpo', l: 'Filings/office', fmt: (v, r) => r.offices ? N(v, 1) : 'no office', h: 'Private family filings per law office', d: 1 }, { k: 'msa', l: 'Metro', fmt: v => esc(v), cls: 'l wrap', h: 'Metro area' }];
    const rowsOf = () => objs().map(c => ({ _id: c.fips, fips: c.fips, name: c.name, di: c.di, rank: c.di_rank, grade: c.grade, pop: c.pop2025, div: c.filings.ttm.div, rate: c.rates.div_per_1k_married, yoy: c.rates.div_yoy, v19: c.rates.div_vs_2019, divk: c.rates.div_k_share, sapcr: c.filings.ttm.sapcr, po: c.filings.ttm.po, haz: c.risk.haz_pred, sep: c.acs.sep_per_1k_married, esi: c.esi, ur: c.laus ? c.laus.ur : null, offices: c.rates.lawoffices || 0, fpo: c.rates.filings_per_lawoffice, msa: c.msa_title ? MNAME(c.msa_title) : 'non metro' }));
    tbl = table($('#idxTable'), { cols, rows: rowsOf(), sort: { k: 'di', dir: -1 }, onRow: select, selected: st.sel, caption: 'All Texas counties ranked by the Dissolution Index' });
    $('#idxLayer').onchange = e => { st.layer = e.target.value; drawIdx(); markSel(mapEl, st.sel); };
    $('#idxMetro').onchange = e => { st.metro = e.target.value; drawIdx(); markSel(mapEl, st.sel); tbl.setRows(rowsOf()); };
    $('#idxLabels').onchange = () => { drawIdx(); markSel(mapEl, st.sel); };
    // find: a name or FIPS code; 'Harris County' and 'harris co' work, an exact name wins, then a prefix, then any part of a name
    const findCounty = raw => { const q = String(raw || '').trim().toLowerCase().replace(/\s+/g, ' ').replace(/,?\s*(county|cnty|co\.?)(,?\s*(tx|texas))?$/, '').trim(); if (!q) return null; const f = /^\d+$/.test(q) ? (q.length === 3 ? '48' + q : q) : null; const big = a => a.sort((x, y) => y.pop2025 - x.pop2025)[0] || null; return CTY.find(c => c.fips === f) || CTY.find(c => c.name.toLowerCase() === q) || big(CTY.filter(c => c.name.toLowerCase().startsWith(q))) || big(CTY.filter(c => c.name.toLowerCase().includes(q))) || null; };
    const qMsg = $('#idxQMsg');
    let qT = 0; $('#idxQ').oninput = e => { clearTimeout(qT); const t = e.target; qT = setTimeout(() => qFind({ target: t }), 250); };
    const qFind = e => { const v = e.target.value; if (!v.trim()) { qMsg.textContent = ''; e.target.removeAttribute('aria-invalid'); return; } const hit = findCounty(v); e.target.setAttribute('aria-invalid', String(!hit)); qMsg.textContent = hit ? '' : 'No county matches. Try a county name or a FIPS code.'; if (hit && hit.fips !== st.sel) select(hit.fips); };
    $('#idxQ').onkeydown = e => { if (e.key === 'Enter') { clearTimeout(qT); const hit = findCounty(e.target.value); if (hit) { select(hit.fips); qMsg.textContent = hit.name + ' County selected.'; } else qMsg.textContent = 'No county matches. Try a county name or a FIPS code.'; } };
    $('#idxCsv').onclick = () => exportText(expName('index', st.metro ? MNAME(MSA[st.metro].title) : 'texas'), csv(tbl.sorted(), xcols([cols[0], { k: 'fips', l: 'FIPS' }].concat(cols.slice(1)))));
    // the component correlation matrix (a table, so a screen reader reads it cell by cell)
    (function corr() { const ks = Object.keys(D.weights); const nm = { filing: 'Filing intensity', haz: 'Composition hazard', sep: 'Separation', econ: 'Economic shock', struct: 'Family structure', strain: 'Financial strain', supply: 'Supply gap' }; const r = (a, b) => { const xs = [], ys = []; CTY.forEach(c => { const x = c.pct[a], y = c.pct[b]; if (isN(x) && isN(y)) { xs.push(x); ys.push(y); } }); const n = xs.length; if (n < 3) return null; const mx = mean(xs), my = mean(ys); let sxy = 0, sxx = 0, syy = 0; for (let i = 0; i < n; i++) { sxy += (xs[i] - mx) * (ys[i] - my); sxx += (xs[i] - mx) ** 2; syy += (ys[i] - my) ** 2; } return sxx && syy ? sxy / Math.sqrt(sxx * syy) : null; };
      $('#idxCorr').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t corr"><caption class="vh">Correlation of the index components</caption><thead><tr><th scope="col">Component</th>${ks.map(k => `<th scope="col">${esc(nm[k] || k)}</th>`).join('')}</tr></thead><tbody>${ks.map(a => `<tr><th scope="row">${esc(nm[a] || a)} <span class="small">${Math.round(D.weights[a] * 100)}%</span></th>${ks.map(b => { const v = a === b ? 1 : r(a, b); const bg = isN(v) && a !== b ? divergeColor(v) : 'var(--sunk)'; return `<td style="background:${bg};color:${a === b ? 'var(--ink-3)' : inkOn(bg)}">${isN(v) ? MINUS(v.toFixed(2)) : NA}</td>`; }).join('')}</tr>`).join('')}</tbody></table></div></div>`; })();
    drawIdx(); select(st.sel, true);
    this.sync = () => { const f = store.get('sev.county', st.sel); if (CI[f] && f !== st.sel) select(f); };
    this.receive = p => { if (p && CI[p.county] && p.county !== st.sel) { store.set('sev.county', p.county); select(p.county); } };
  },
  onShow() { if (this.sync) this.sync(); }
});
function toggleTheme() { const r = document.documentElement; const cur = r.getAttribute('data-theme'); const sysDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches; const isDark = cur ? cur === 'dark' : sysDark; r.setAttribute('data-theme', isDark ? 'light' : 'dark'); store.set('sev.theme', isDark ? 'light' : 'dark'); }
