'use strict';
/* Module 02: Filings Ledger */
const CASE_TYPES = [['div', 'Divorce (all)', 'var(--s1)'], ['po', 'Protective orders', 'var(--s2)'], ['sapcr', 'Custody, SAPCR', 'var(--s3)'], ['div_k', 'Divorce with children', 'var(--s4)'], ['mod', 'Modifications', 'var(--s5)'], ['enf', 'Enforcement', 'var(--s6)'], ['ivd', 'Title IV-D support', 'var(--s7)'], ['cps', 'CPS', 'var(--s8)'], ['priv', 'Private family law (all)', 'var(--ink-2)']];
registerModule({
  key: 'ledger', num: '02', title: 'Filings Ledger', desc: 'Court filings by case type, month and county: the demand as the district clerks report it',
  mount(root) {
    const st = { types: ['div', 'sapcr', 'po'], cty: store.get('sev.county', '48201'), yearCol: 'div', scale: 'n' };
    const m = ST.monthly; const t0 = m.t0; const n = m.div.length;
    const ann = ST.annual; const yrs = Object.keys(ann).sort();
    const y25 = ann['2025'], y19 = ann['2019'], y26 = ann['2026'];
    const ytdDiv26 = y26.f_div, ytdDiv25 = sum(m.div.slice((2025 * 12) - t0, (2025 * 12) - t0 + 8));
    const pending = m.p_div[n - 1];
    root.innerHTML = mastHTML({ eyebrow: 'Module 02 · Filings Ledger · Office of Court Administration district court activity, January 2019 to August 2026', title: 'Filings Ledger', dek: `The one number nobody has to model. Every Texas district clerk reports new family cases to the Office of Court Administration each month by type: divorce with and without children, suits affecting the parent child relationship, protective orders, modifications, enforcements, Title IV-D support, CPS, termination and adoption. This module holds 92 months for the state and for every county in a metropolitan area, and annual totals for the other 168 counties, 9,348 clerk reports in all.`, facts: [[N(y25.f_div), 'divorces filed in 2025'], [N(ytdDiv26), 'January to August 2026 (' + sgn((ytdDiv26 / ytdDiv25 - 1) * 100) + ' vs same months 2025)'], [N(pending), 'divorces pending statewide, end of August 2026'], [N(y25.f_po), 'protective orders filed in 2025 (' + sgn((y25.f_po / y19.f_po - 1) * 100) + ' vs 2019)']] }) + `
    <div class="toolbar"><span class="ttl">Filings Ledger</span><span class="sub">Statewide series, county series, annual tables</span><span class="sp"></span><button class="btn" id="ledCsvState">↓ Statewide monthly CSV</button><button class="btn" id="ledCsvCounty">↓ County annual CSV</button></div>
    <div class="callout note"><div class="h">Read this first: what filings are and are not</div><p>A filing is a petition, not a decree: about a fifth of divorce petitions are dismissed, withdrawn or reconciled. Filings are the right demand measure for a law firm because the consultation happens before the petition. Divorces fell from ${N(y19.f_div)} in 2019 to ${N(y25.f_div)} in 2025 while Texas added roughly two million people, so the per capita rate keeps falling. Protective orders moved the other way (${sgn((y25.f_po / y19.f_po - 1) * 100)} since 2019), custody suits without a divorce are ${updown((y25.f_sapcr / y19.f_sapcr - 1) * 100)}, and Title IV-D filings collapsed after the Attorney General's office changed its reporting. The last two months are provisional: late clerk reports get added for up to 90 days. In ${Object.keys(ST.ccl_div_2025 || {}).length} counties a county court at law shares family jurisdiction with the district courts, and those filings are included here (${N(sum(Object.values(ST.ccl_div_2025 || {})))} divorces in 2025, led by ${Object.keys(ST.ccl_div_2025 || {}).sort((a, b) => ST.ccl_div_2025[b] - ST.ccl_div_2025[a]).slice(0, 6).map(f => cname(f)).join(', ')}); a county that looked empty on district court data alone, like Wise or Hood, is whole once they are added. Modification and enforcement counts depend on how each clerk codes post judgment actions; a few counties file them under other family law.</p></div>
    <div class="tiles" id="ledTiles"></div>
    <div class="panel" style="margin-bottom:14px"><h3>Statewide filings by month</h3><div class="sub">New cases filed, all district courts. Toggle case types. The shaded band marks the 2020 court closures. Divorce runs near ten thousand a month and the other lines near one thousand, so the indexed view (each line's 2019 monthly average = 100) puts their trends on one scale.</div><div class="tabs" id="ledTypes" role="group" aria-label="Case types shown">${CASE_TYPES.map(t => `<button type="button" data-t="${t[0]}" aria-pressed="${st.types.includes(t[0])}" class="${st.types.includes(t[0]) ? 'on' : ''}">${t[1]}</button>`).join('')}</div><div class="seg" id="ledScale" role="group" aria-label="Scale" style="margin:0 0 10px"><button type="button" data-v="n" aria-pressed="true">Filings a month</button><button type="button" data-v="i" aria-pressed="false">Indexed, 2019 = 100</button></div><div class="chart" id="ledChart"></div></div>
    <div class="grid2"><div class="panel"><h3>Seasonality of divorce filings</h3><div class="sub">Index of monthly filings, 2022 to 2025 average = 100. March is the peak; the January spike is folklore in Texas. November and December run 17 to 19 points below average.</div><div id="ledSeas"></div><p class="small" style="margin-top:8px">Other lines: SAPCR ${MO[ST.seas.sapcr.indexOf(Math.max(...ST.seas.sapcr))]} peak, protective orders ${MO[ST.seas.po.indexOf(Math.max(...ST.seas.po))]} peak, modifications ${MO[ST.seas.mod.indexOf(Math.max(...ST.seas.mod))]} peak. Module 09 turns this into a media calendar.</p></div>
    <div class="panel"><h3>Annual totals, statewide</h3><div class="sub">Calendar years; 2026 is January to August.</div><div id="ledAnnual"></div></div></div>
    <div class="panel" style="margin-bottom:14px"><h3>County series</h3><div class="sub">Monthly filings for any county in a metropolitan area (86 counties). Pending divorces show the court backlog a firm walks into.</div><div class="controls">${ctl('County', sel('ledCty', CTY.filter(c => c.filings.series).sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.cty))}</div><div class="chart" id="ledCtyChart"></div><div class="small" id="ledCtyNote"></div></div>
    <div class="panel"><h3>Counties, annual filings</h3><div class="sub">All 254 counties. Pick the case type for the year columns.</div><div class="controls">${ctl('Case type', sel('ledYearCol', [['div', 'Divorce'], ['div_k', 'Divorce with children'], ['sapcr', 'SAPCR'], ['po', 'Protective orders'], ['mod', 'Modifications'], ['enf', 'Enforcement'], ['ivd', 'Title IV-D'], ['cps', 'CPS'], ['adopt', 'Adoption'], ['priv', 'Private family law']], 'div'))}</div><div id="ledTable"></div></div>`;
    $('#ledTiles').innerHTML = tile('Divorce filings 2025', N(y25.f_div), `${N(y25.f_div_k)} with children (${P(y25.f_div_k / y25.f_div, 0)})`, 'A') + tile('Divorces disposed 2025', N(y25.d_div), 'decrees, dismissals and withdrawals combined', 'A') + tile('SAPCR 2025', N(y25.f_sapcr), 'custody suits with no divorce attached', 'A') + tile('Protective orders 2025', N(y25.f_po), 'applications filed in district court', 'A') + tile('Modifications 2025', N(y25.f_mod_cust + y25.f_mod_other), `${N(y25.f_mod_cust)} custody, ${N(y25.f_mod_other)} other`, 'A') + tile('Enforcement 2025', N(y25.f_enf), 'post judgment enforcement actions', 'A');
    // indexed view: each series over its own 2019 monthly average
    const base19 = k => { const a = m[k].slice(2019 * 12 - t0, 2019 * 12 - t0 + 12).filter(isN); return a.length ? mean(a) : null; };
    function stateChart() { const x = i => t0 + i; const ix = st.scale === 'i'; const sel = CASE_TYPES.filter(t => st.types.includes(t[0])); if (!sel.length) { $('#ledChart').innerHTML = '<div class="small" style="padding:24px 0">Pick at least one case type above.</div>'; return; } lineChart($('#ledChart'), { title: 'Statewide filings by month', series: sel.map(t => { const b = ix ? base19(t[0]) : 1; return { name: t[1], color: t[2], values: m[t[0]].map((v, i) => ({ x: x(i), y: isN(v) && b ? (ix ? v / b * 100 : v) : null })) }; }), W: 900, H: 260, xfmt: tLabel, xTicks: [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026].map(y => y * 12), xTickFmt: v => String(v / 12), bands: [{ x0: 2020 * 12 + 2, x1: 2020 * 12 + 5, label: 'courts closed' }], yfmt: ix ? (v => N(v, 0)) : (v => N(v)) }); }
    $$('#ledTypes button').forEach(b => b.onclick = () => { const t = b.dataset.t; if (st.types.includes(t)) st.types = st.types.filter(x => x !== t); else st.types.push(t); const on = st.types.includes(t); b.classList.toggle('on', on); b.setAttribute('aria-pressed', String(on)); stateChart(); });
    $$('#ledScale button').forEach(b => b.onclick = () => { st.scale = b.dataset.v; $$('#ledScale button').forEach(x => x.setAttribute('aria-pressed', String(x === b))); stateChart(); });
    stateChart();
    seasBlock($('#ledSeas'), ST.seas.div, 'ember');
    // annual table
    const ak = [['f_div', 'Divorce'], ['f_div_k', 'with kids'], ['f_sapcr', 'SAPCR'], ['f_po', 'Prot. orders'], ['f_mod_cust', 'Mod custody'], ['f_mod_other', 'Mod other'], ['f_enf', 'Enforce'], ['f_cps', 'CPS'], ['f_tpr', 'Termination'], ['f_adopt', 'Adoption'], ['f_ivd_pat', 'IV-D paternity'], ['f_ivd_sup', 'IV-D support'], ['f_other', 'Other'], ['d_div', 'Div disposed']];
    $('#ledAnnual').innerHTML = `<div class="tblwrap"><table class="t"><thead><tr><th>Year</th>${ak.map(k => `<th>${k[1]}</th>`).join('')}</tr></thead><tbody>${yrs.map(y => `<tr><td>${y}${y === '2026' ? ' (8 mo)' : ''}</td>${ak.map(k => `<td>${N(ann[y][k[0]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;
    function ctyChart() { const c = CI[st.cty]; const s = c.filings.series; if (!s) return; lineChart($('#ledCtyChart'), { series: [{ name: 'Divorce filed', color: 'var(--s1)', values: s.div.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'Protective orders', color: 'var(--s2)', values: s.po.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'SAPCR', color: 'var(--s3)', values: s.sapcr.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'Divorce disposed', color: 'var(--s4)', values: s.d_div.map((v, i) => ({ x: s.t0 + i, y: v })) }], W: 900, H: 240, title: c.name + ' County filings by month', xfmt: tLabel, xTicks: [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026].map(y => y * 12), xTickFmt: v => String(v / 12), yfmt: v => N(v) }); const last = s.p_div[s.p_div.length - 1]; const ttm = c.filings.ttm; $('#ledCtyNote').innerHTML = `${esc(c.name)} County: ${N(ttm.div)} divorces filed and ${N(ttm.d_div)} disposed in the last twelve months; ${N(last)} divorces pending at the end of August 2026 (${N(last / (ttm.d_div / 12), 1)} months of dispositions). Trailing twelve months vs the prior twelve: divorce ${sgn(c.rates.div_yoy)}, SAPCR ${sgn((ttm.sapcr / (c.filings.ttm_prev.sapcr || 1) - 1) * 100)}, protective orders ${sgn((ttm.po / (c.filings.ttm_prev.po || 1) - 1) * 100)}, modifications ${sgn((ttm.mod / (c.filings.ttm_prev.mod || 1) - 1) * 100)}.`; }
    $('#ledCty').onchange = e => { st.cty = e.target.value; ctyChart(); };
    ctyChart();
    const yl = ['2019', '2020', '2021', '2022', '2023', '2024', '2025', '2026'];
    function rows() { return CTY.map(c => { const o = { _id: c.fips, name: c.name, pop: c.pop2025, msa: c.msa_title ? MNAME(c.msa_title) : 'non metro' }; yl.forEach(y => { const h = c.filings.hist[y]; o['y' + y] = h ? h[st.yearCol] : null; }); const h19 = c.filings.hist['2019'], h25 = c.filings.hist['2025']; o.chg = (h19 && h25 && h19[st.yearCol]) ? (h25[st.yearCol] / h19[st.yearCol] - 1) * 100 : null; o.per10k = h25 ? h25[st.yearCol] / c.pop2025 * 10000 : null; return o; }); }
    const YCOL = { div: 'Divorce', div_k: 'Divorce with children', sapcr: 'SAPCR', po: 'Protective orders', mod: 'Modifications', enf: 'Enforcement', ivd: 'Title IV-D', cps: 'CPS', adopt: 'Adoption', priv: 'Private family law' };
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'pop', l: 'Pop 2025', fmt: v => N(v), h: 'Population 2025 (Census Vintage 2025)', d: 0 }].concat(yl.map(y => ({ k: 'y' + y, l: y + (y === '2026' ? ' (8mo)' : ''), fmt: v => N(v), d: 0 }))).concat([{ k: 'chg', l: '2025 vs 2019', fmt: v => sgn(v), d: 1 }, { k: 'per10k', l: '2025 per 10k pop', fmt: v => N(v, 1), d: 1 }, { k: 'msa', l: 'Metro', fmt: v => esc(v), cls: 'l wrap', h: 'Metro area' }]);
    const xc = () => { const t = YCOL[st.yearCol] || st.yearCol; return xcols([cols[0], { k: '_id', l: 'FIPS' }].concat(cols.slice(1))).map(c => /^y\d{4}$/.test(c.k) ? Object.assign(c, { l: `${t} filings ${c.k.slice(1)}${c.k === 'y2026' ? ' (January to August)' : ''}` }) : c.k === 'chg' ? Object.assign(c, { l: `${t} filings 2025 vs 2019 (%)` }) : c.k === 'per10k' ? Object.assign(c, { l: `${t} filings 2025 per 10,000 residents` }) : c); };
    const tbl = table($('#ledTable'), { cols, rows: rows(), sort: { k: 'y2025', dir: -1 }, caption: 'Counties, annual filings' });
    $('#ledYearCol').onchange = e => { st.yearCol = e.target.value; tbl.setRows(rows()); };
    const SCOLS = [['month', 'Month'], ['div', 'Divorce filed'], ['div_k', 'Divorce with children filed'], ['sapcr', 'SAPCR filed'], ['po', 'Protective orders filed'], ['mod', 'Modifications filed'], ['enf', 'Enforcement filed'], ['ivd', 'Title IV-D filed'], ['cps', 'CPS filed'], ['adopt', 'Adoption filed'], ['priv', 'Private family law filed'], ['d_div', 'Divorces disposed'], ['p_div', 'Divorces pending at month end'], ['total', 'All family cases filed']];
    $('#ledCsvState').onclick = () => exportText(expName('ledger_monthly', 'texas'), csv(m.div.map((v, i) => { const t = t0 + i; const o = { month: `${Math.floor(t / 12)}-${String(t % 12 + 1).padStart(2, '0')}` }; SCOLS.slice(1).forEach(([k]) => o[k] = m[k] ? m[k][i] : null); return o; }), SCOLS.map(([k, l]) => ({ k, l, d: k === 'month' ? null : 0 }))));
    $('#ledCsvCounty').onclick = () => exportText(expName('ledger_annual_' + st.yearCol, 'texas'), csv(tbl.sorted(), xc()));
  }
});
