'use strict';
/* Module 03: Marriage Market */
const MARKET_LAYERS = {
  married_sh: { l: 'Married share of adults 15+', ramp: 'steel', v: c => c.acs.married_sh15, f: v => P(v, 0) },
  mar_25_44: { l: 'Married adults aged 25 to 44 (share of married)', ramp: 'ember', v: c => c.acs.mar_25_44_sh, f: v => P(v, 0) },
  mar_55p: { l: 'Married adults aged 55 and over (share of married)', ramp: 'slate', v: c => c.acs.mar_55p_sh, f: v => P(v, 0) },
  dur_lt5: { l: 'Married under five years (share, PUMS)', ramp: 'ember', v: c => c.risk.dur_lt5, f: v => P(v, 0) },
  dur_5_9: { l: 'Married five to nine years, the peak hazard band (share, PUMS)', ramp: 'ember', v: c => c.risk.dur_5_9, f: v => P(v, 0) },
  remarried: { l: 'Remarried, second or later marriage (share, PUMS)', ramp: 'ember', v: c => c.risk.remarried, f: v => P(v, 0) },
  young: { l: 'Married before age 23 (share, PUMS)', ramp: 'ember', v: c => c.risk.young_mar, f: v => P(v, 0) },
  inflow: { l: 'Marriage inflow: married in the past year per 1,000 married', ramp: 'moss', v: c => c.pools.married_ly_w && c.acs.married ? c.pools.married_ly_w / c.acs.married * 1000 : null, f: v => N(v, 0) },
  divstock: { l: 'Divorced adults per married adult (stock)', ramp: 'ember', v: c => c.acs.div_stock_per_married, f: v => N(v, 2) },
  cohab: { l: 'Cohabiting couple households (share of households)', ramp: 'amber', v: c => c.acs.cohab_sh, f: v => P(v, 1) },
  ba: { l: 'Married adults with a bachelor\'s degree (share, PUMS)', ramp: 'steel', v: c => c.risk.ba_plus, f: v => P(v, 0) },
  hazobs: { l: 'Observed divorces per 1,000 married (PUMS, 2020 to 2024)', ramp: 'ember', v: c => c.risk.haz_obs, f: v => N(v, 1) }
};
registerModule({
  key: 'market', num: '03', title: 'Marriage Market', desc: 'The installed base: 11 million married Texans, how long they have been married, how many times, and the hazard curve that turns them into clients',
  mount(root) {
    const st = { layer: 'dur_5_9', sel: store.get('sev.county', '48201') };
    const G = D.pums.groups, curve = D.pums.curve, OR = D.pums.coefs;
    const s = ST.acs;
    root.innerHTML = mastHTML({ eyebrow: 'Module 03 · Marriage Market · ACS 2020 to 2024 and the Texas PUMS hazard model', title: 'Marriage Market', dek: `A divorce practice sells to married people, so the installed base is marriages. Texas has ${K(s.married)} married adults (spouse present), ${K(s.separated)} separated, ${K(s.divorced)} currently divorced and ${K(ST.acs.never)} never married. Each year about ${K(D.pums.div_ly_w)} of the married report a divorce, ${N(G.all.haz, 1)} per 1,000, and about ${K(sum(CTY.map(c => c.pools.married_ly_w || 0)))} people marry. The hazard is not flat: it peaks in years one and five to ten of a marriage, at ages 30 to 44, and doubles for anyone on a second marriage.`, facts: [[N(G.all.haz, 1), 'divorces per 1,000 married adults a year (Texas microdata, SE ' + N(G.all.se, 2) + ')'], ['29.9 / 27.7', 'median age at first marriage, Texas men / women (US 30.6 / 28.7)'], ['17.6 yrs', 'median duration of current marriages in Texas'], ['24.7%', 'of ever married Texans have married two or more times']] }) + `
    <div class="toolbar"><span class="ttl">Marriage Market</span><span class="sub">Hazard curves, cohorts and the county composition layers</span><span class="sp"></span><button class="btn" id="mktCsv">↓ County composition CSV</button></div>
    <div class="callout"><div class="h">Read this first: what the hazard model learned from 569,350 married Texans</div><p>Among Texans who were married at some point in the prior twelve months in the 2020 to 2024 American Community Survey, ${N(D.pums.div_ly_w)} (weighted) reported a divorce in that year. A logistic model on the things that do not change when a marriage ends (age, sex, years since the wedding, number of marriages, education, military service, age at marriage) fits those odds. The findings that matter for targeting: a second marriage carries <b>${N(OR.timesb_2.or, 2)}×</b> the odds of a first and a third marriage <b>${N(OR['timesb_3+'].or, 2)}×</b>; a bachelor's degree cuts the odds to <b>${N(OR.edu_bachelors.or, 2)}×</b>; current active duty service raises them <b>${N(OR.mil_own.or, 2)}×</b> and prior service <b>${N(OR.veteran.or, 2)}×</b>; marrying before 23 adds <b>${N(OR.young_mar.or, 2)}×</b>; marriages past thirty years run at <b>${N(OR['durb_30+'].or, 2)}×</b> the odds of a ten to fourteen year marriage. Income, employment, renting and having children were deliberately left out of the fit because the survey measures them after the divorce, which makes them consequences as much as causes; they appear as exposure pools in modules 04 and 05 instead.</p></div>
    <div class="tiles" id="mktTiles"></div>
    <div class="grid2"><div class="panel"><h3>Divorce hazard by years since the wedding</h3><div class="sub">Divorces in the past year per 1,000 married adults by years since the wedding, Texas 2020 to 2024, three year centered average to take out marriage cohort bumps. Band shows one standard error from the 80 replicate weights.</div><div class="chart" id="mktCurve"></div></div>
    <div class="panel"><h3>Hazard by group</h3><div class="sub">Same measure, per 1,000 married adults a year.</div><div class="chart" id="mktGroups"></div></div></div>
    <div class="grid2"><div class="panel"><h3>Marriage and divorce rates, Texas 1990 to 2023</h3><div class="sub">Per 1,000 residents, National Center for Health Statistics. Texas divorce counts reach NCHS through district clerk reports and undercount in some years (2019 to 2021 especially); the court filings in module 02 are the reliable series after 2019.</div><div class="chart" id="mktNchs"></div></div>
    <div class="panel"><h3>Married adults by age, Texas</h3><div class="sub">Where the installed base sits. The 25 to 44 band carries most divorces with children; 55 and over is the gray divorce pool.</div><div class="chart" id="mktAge"></div></div></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', sel('mktLayer', Object.keys(MARKET_LAYERS).map(k => [k, MARKET_LAYERS[k].l]), st.layer))}</div><div class="split"><div class="mapwrap" id="mktMap"></div><div id="mktSide"></div></div></div>
    <div class="panel"><h3>Counties</h3><div id="mktTable"></div></div>`;
    $('#mktTiles').innerHTML = tile('Married Texans', K(s.married), 'spouse present, ACS 2020 to 2024') + tile('Peak hazard band', N(G['dur_5-9'].haz, 1), 'per 1,000, married 5 to 9 years (0 to 1 yrs: ' + N(G['dur_0-1'].haz, 1) + ', 30+ yrs: ' + N(G['dur_30+'].haz, 1) + ')') + tile('Second marriages', N(G.times_2.haz, 1), 'per 1,000 vs ' + N(G.times_1.haz, 1) + ' for first marriages; third or later ' + N(G['times_3+'].haz, 1)) + tile('Bachelor\'s or higher', N(G.edu_bachelors.haz, 1), 'per 1,000 vs ' + N(G.edu_hs.haz, 1) + ' for high school only') + tile('Active duty', N(G.mil_active.haz, 1), 'per 1,000 married adults with a service member in the household; veterans ' + N(G.veteran.haz, 1)) + tile('Ages 30 to 44', N((G['age_30-34'].haz + G['age_35-39'].haz + G['age_40-44'].haz) / 3, 1), 'per 1,000; ages 60 to 64 ' + N(G['age_60-64'].haz, 1) + ', 65 and over ' + N(G['age_65+'].haz, 1));
    const raw = curve.filter(c => c.dur <= 36); const cv = raw.map((c, i) => { const w = raw.slice(Math.max(0, i - 1), i + 2); return { dur: c.dur, haz_per_1000: mean(w.map(x => x.haz_per_1000)), se: mean(w.map(x => x.se)) / Math.sqrt(w.length) }; }).filter(c => c.dur <= 35);
    lineChart($('#mktCurve'), { series: [{ name: 'Upper bound, 1 SE', lname: 'One standard error band', color: 'var(--line-strong)', dash: true, values: cv.map(c => ({ x: c.dur, y: c.haz_per_1000 + c.se })) }, { name: 'Divorces per 1,000 married', color: 'var(--s1)', values: cv.map(c => ({ x: c.dur, y: c.haz_per_1000 })) }, { name: 'Lower bound, 1 SE', nolegend: true, color: 'var(--line-strong)', dash: true, values: cv.map(c => ({ x: c.dur, y: Math.max(0, c.haz_per_1000 - c.se) })) }], W: 640, H: 240, ymin: 0, xfmt: v => 'Year ' + v + ' of marriage', xTicks: [0, 5, 10, 15, 20, 25, 30, 35], yfmt: v => N(v, 0) });
    const gk = [['age_18-24', 'Age 18 to 24'], ['age_25-29', '25 to 29'], ['age_30-34', '30 to 34'], ['age_35-39', '35 to 39'], ['age_40-44', '40 to 44'], ['age_45-49', '45 to 49'], ['age_50-54', '50 to 54'], ['age_55-59', '55 to 59'], ['age_60-64', '60 to 64'], ['age_65+', '65 and over'], ['times_1', 'First marriage'], ['times_2', 'Second marriage'], ['times_3+', 'Third or later'], ['edu_lt_hs', 'Less than high school'], ['edu_hs', 'High school'], ['edu_some_college', 'Some college'], ['edu_bachelors', "Bachelor's"], ['edu_graduate', 'Graduate degree'], ['young_mar', 'Married before 23'], ['mar_23plus', 'Married at 23 or later'], ['mil_active', 'Active duty household'], ['veteran', 'Veteran'], ['civilian', 'No service']];
    barChart($('#mktGroups'), { rows: gk.map(k => ({ label: k[1], value: G[k[0]].haz, color: k[0].startsWith('age') ? 'var(--s1)' : k[0].startsWith('times') ? 'var(--s2)' : k[0].startsWith('edu') ? 'var(--s3)' : ['young_mar', 'mar_23plus'].includes(k[0]) ? 'var(--s4)' : 'var(--s5)' })), W: 520, lw: 150, fmt: v => N(v, 1) });
    const nY = Object.keys(ST.nchs.divorce).map(Number).sort((a, b) => a - b);
    lineChart($('#mktNchs'), { series: [{ name: 'Marriage rate', color: 'var(--s1)', values: nY.map(y => ({ x: y, y: ST.nchs.marriage[y] })) }, { name: 'Divorce rate', color: 'var(--s2)', values: nY.map(y => ({ x: y, y: ST.nchs.divorce[y] })) }], W: 640, H: 220, ymin: 0, xfmt: v => String(v), xTicks: [1990, 1995, 2000, 2005, 2010, 2015, 2020, 2023], yfmt: v => N(v, 1) });
    const A = F_state_age();
    barChart($('#mktAge'), { rows: A, W: 520, lw: 120, fmt: v => K(v) });
    function F_state_age() { const tot = CTY.reduce((o, c) => { o.a += c.acs.mar_15_29 || 0; o.b += c.acs.mar_25_44 || 0; o.c += c.acs.mar_55_64 || 0; o.d += c.acs.mar_65p || 0; o.m += c.acs.married || 0; return o; }, { a: 0, b: 0, c: 0, d: 0, m: 0 }); const mid = tot.m - tot.a - tot.b - tot.c - tot.d; return [{ label: '15 to 24', value: tot.a, color: 'var(--s1)' }, { label: '25 to 44', value: tot.b, color: 'var(--hl)' }, { label: '45 to 54', value: mid, color: 'var(--s1)' }, { label: '55 to 64', value: tot.c, color: 'var(--s7)' }, { label: '65 and over', value: tot.d, color: 'var(--s7)' }]; }
    const mapEl = $('#mktMap');
    function draw() { const L = MARKET_LAYERS[st.layer]; const sc = layerScale(L, CTY); drawMap(mapEl, { W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => L.v(CI[id]), color: sc.color, label: id => countyTipHTML(CI[id], `<div class="row"><span>${esc(L.l)}</span><span>${esc(L.f(L.v(CI[id])))}</span></div>`), onSelect: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); tbl.setSel(id); }, selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: L.l }, sc.legend) }); }
    function side() { const c = CI[st.sel]; const r = c.risk, a = c.acs; $('#mktSide').innerHTML = `<h3 style="font-family:var(--display);font-size:20px">${esc(c.name)} County</h3><dl class="kv"><dt>Married adults</dt><dd>${N(a.married)}</dd><dt>Married share of adults</dt><dd>${P(a.married_sh15, 0)}</dd><dt>Married 25 to 44</dt><dd>${P(a.mar_25_44_sh, 0)}</dd><dt>Married 55 and over</dt><dd>${P(a.mar_55p_sh, 0)}</dd><dt>Under 5 years married</dt><dd>${P(r.dur_lt5, 0)}</dd><dt>5 to 9 years</dt><dd>${P(r.dur_5_9, 0)}</dd><dt>10 to 19 years</dt><dd>${P(r.dur_10_19, 0)}</dd><dt>20 years or more</dt><dd>${P(r.dur_20p, 0)}</dd><dt>Remarried</dt><dd>${P(r.remarried, 0)}</dd><dt>Married before 23</dt><dd>${P(r.young_mar, 0)}</dd><dt>Bachelor's or higher</dt><dd>${P(r.ba_plus, 0)}</dd><dt>Marriages in past year</dt><dd>${N(c.pools.married_ly_w)}</dd><dt>Divorces in past year (ACS)</dt><dd>${N(c.pools.div_ly_all_w)}</dd><dt>Observed hazard per 1,000</dt><dd>${N(r.haz_obs, 1)}</dd><dt>Modeled hazard per 1,000</dt><dd>${N(r.haz_pred, 1)}</dd><dt>Court filings per 1,000 married</dt><dd>${N(c.rates.div_per_1k_married, 1)}</dd></dl><p class="small" style="margin-top:8px">Composition shares come from the Public Use Microdata Areas that cover the county, weighted by population. Counties with fewer than about 100,000 residents share a PUMA with neighbors, so their composition is a regional estimate.</p>`; }
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'married', l: 'Married', fmt: v => N(v) }, { k: 'msh', l: 'Married share', fmt: v => P(v, 0) }, { k: 'm2544', l: '25 to 44', fmt: v => P(v, 0) }, { k: 'm55', l: '55+', fmt: v => P(v, 0) }, { k: 'd5', l: '<5 yrs', fmt: v => P(v, 0) }, { k: 'd59', l: '5 to 9 yrs', fmt: v => P(v, 0) }, { k: 'rem', l: 'Remarried', fmt: v => P(v, 0) }, { k: 'young', l: 'Married <23', fmt: v => P(v, 0) }, { k: 'ba', l: 'BA+', fmt: v => P(v, 0) }, { k: 'inflow', l: 'Married last yr', fmt: v => N(v) }, { k: 'hobs', l: 'Obs hazard', fmt: v => N(v, 1) }, { k: 'hpred', l: 'Model hazard', fmt: v => N(v, 1) }, { k: 'filing', l: 'Filings /1k', fmt: v => N(v, 1) }];
    const rows = () => CTY.map(c => ({ _id: c.fips, name: c.name, married: c.acs.married, msh: c.acs.married_sh15, m2544: c.acs.mar_25_44_sh, m55: c.acs.mar_55p_sh, d5: c.risk.dur_lt5, d59: c.risk.dur_5_9, rem: c.risk.remarried, young: c.risk.young_mar, ba: c.risk.ba_plus, inflow: c.pools.married_ly_w, hobs: c.risk.haz_obs, hpred: c.risk.haz_pred, filing: c.rates.div_per_1k_married }));
    const tbl = table($('#mktTable'), { cols, rows: rows(), sort: { k: 'married', dir: -1 }, onRow: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); tbl.setSel(id); }, selected: st.sel });
    $('#mktLayer').onchange = e => { st.layer = e.target.value; draw(); };
    $('#mktCsv').onclick = () => exportText('severance_marriage_market.csv', csv(rows(), cols.map(c => ({ l: c.l, k: c.k }))));
    draw(); side();
  }
});
