'use strict';
/* Module 03: Marriage Market */
const MARKET_LAYERS = {
  married_sh: { g: 'A', l: 'Married share of adults 15+', ramp: 'steel', v: c => c.acs.married_sh15, f: v => P(v, 0) },
  mar_25_44: { g: 'A', l: 'Married adults aged 25 to 44 (share of married)', ramp: 'ember', v: c => c.acs.mar_25_44_sh, f: v => P(v, 0) },
  mar_55p: { g: 'A', l: 'Married adults aged 55 and over (share of married)', ramp: 'slate', v: c => c.acs.mar_55p_sh, f: v => P(v, 0) },
  dur_lt5: { g: 'B', l: 'Married under five years (share, PUMS)', ramp: 'ember', v: c => c.risk.dur_lt5, f: v => P(v, 0) },
  dur_5_9: { g: 'B', l: 'Married five to nine years, the peak hazard band (share, PUMS)', ramp: 'ember', v: c => c.risk.dur_5_9, f: v => P(v, 0) },
  remarried: { g: 'B', l: 'Remarried, second or later marriage (share, PUMS)', ramp: 'ember', v: c => c.risk.remarried, f: v => P(v, 0) },
  young: { g: 'B', l: 'Married before age 23 (share, PUMS)', ramp: 'ember', v: c => c.risk.young_mar, f: v => P(v, 0) },
  inflow: { g: 'B', l: 'Marriage inflow: married in the past year per 1,000 married', ramp: 'moss', v: c => c.pools.married_ly_w && c.acs.married ? c.pools.married_ly_w / c.acs.married * 1000 : null, f: v => N(v, 0) },
  divstock: { g: 'A', l: 'Divorced adults per married adult (stock)', ramp: 'ember', v: c => c.acs.div_stock_per_married, f: v => N(v, 2) },
  cohab: { g: 'A', l: 'Cohabiting couple households (share of households)', ramp: 'amber', v: c => c.acs.cohab_sh, f: v => P(v, 1) },
  ba: { g: 'B', l: 'Married adults with a bachelor\'s degree or higher (share, PUMS)', ramp: 'steel', v: c => c.risk.ba_plus, f: v => P(v, 0) },
  hazobs: { g: 'C', l: 'Observed divorces per 1,000 married (PUMS, 2020 to 2024)', ramp: 'ember', v: c => c.risk.haz_obs, f: v => N(v, 1) }
};
// the hazard model's terms in reading order with plain labels (module 20 shows the same table); the reference categories are age 40 to 44,
// married 10 to 14 years, first marriage, high school, male, civilian, married at 23 or later
const PUMS_TERMS = [['ageb_18-24', 'Age 18 to 24'], ['ageb_25-29', 'Age 25 to 29'], ['ageb_30-34', 'Age 30 to 34'], ['ageb_35-39', 'Age 35 to 39'], ['ageb_45-49', 'Age 45 to 49'], ['ageb_50-54', 'Age 50 to 54'], ['ageb_55-59', 'Age 55 to 59'], ['ageb_60-64', 'Age 60 to 64'], ['ageb_65+', 'Age 65 and over'], ['durb_0-1', 'Married 0 to 1 years'], ['durb_2-4', 'Married 2 to 4 years'], ['durb_5-9', 'Married 5 to 9 years'], ['durb_15-19', 'Married 15 to 19 years'], ['durb_20-29', 'Married 20 to 29 years'], ['durb_30+', 'Married 30 or more years'], ['timesb_2', 'Second marriage'], ['timesb_3+', 'Third or later marriage'], ['edu_lt_hs', 'Less than high school'], ['edu_some_college', 'Some college'], ['edu_bachelors', "Bachelor's degree"], ['edu_graduate', 'Graduate degree'], ['female', 'Female respondent'], ['mil_own', 'On active duty'], ['veteran', 'Veteran'], ['young_mar', 'Married before age 23']];
registerModule({
  key: 'market', num: '03', title: 'Marriage Market', desc: 'The installed base: 11 million married Texans, how long they have been married, how many times, and the hazard curve that turns them into clients',
  mount(root) {
    const st = { layer: 'dur_5_9', sel: store.get('sev.county', '48201') };
    const G = D.pums.groups, curve = D.pums.curve, OR = D.pums.coefs;
    const s = ST.acs;
    root.innerHTML = mastHTML({ eyebrow: 'Module 03 · Marriage Market · ACS 2020 to 2024 and the Texas PUMS hazard model', title: 'Marriage Market', dek: `A divorce practice sells to married people, so the installed base is marriages. Texas has ${K(s.married)} married adults (spouse present), ${K(s.separated)} separated, ${K(s.divorced)} currently divorced and ${K(ST.acs.never)} never married. Each year about ${K(D.pums.div_ly_w)} of the married report a divorce, ${N(G.all.haz, 1)} per 1,000, and about ${K(sum(CTY.map(c => c.pools.married_ly_w || 0)))} people marry. The hazard is not flat: it peaks in years one and five to ten of a marriage, at ages 30 to 44, and runs ${N((G.times_2.haz / G.times_1.haz - 1) * 100, 0)}% higher on a second marriage (${N(OR.timesb_2.or, 2)}× the odds) and about ${N(OR['timesb_3+'].or, 1)}× the odds on a third or later.`, facts: [[N(G.all.haz, 1), 'divorces per 1,000 married adults a year (Texas microdata, SE ' + N(G.all.se, 2) + ')'], ['29.9 / 27.7', 'median age at first marriage, Texas men / women (US 30.6 / 28.7)'], ['17.6 yrs', 'median duration of current marriages in Texas'], ['24.7%', 'of ever married Texans have married two or more times']] }) + `
    <div class="toolbar"><span class="ttl">Marriage Market</span><span class="sub">Hazard curves, cohorts and the county composition layers</span><span class="sp"></span><button class="btn" id="mktCsv">↓ County composition CSV</button></div>
    <div class="callout"><div class="h">Read this first: what the hazard model learned from ${N(D.pums.n)} married Texans</div><p>Among Texans who were married at some point in the prior twelve months in the 2020 to 2024 American Community Survey, ${N(D.pums.div_ly_w)} (weighted) reported a divorce in that year. A logistic model on the things that do not change when a marriage ends (age, sex, years since the wedding, number of marriages, education, military service, age at marriage) fits those odds. The findings that matter for targeting: a second marriage carries <b>${N(OR.timesb_2.or, 2)}×</b> the odds of a first and a third marriage <b>${N(OR['timesb_3+'].or, 2)}×</b>; a bachelor's degree cuts the odds to <b>${N(OR.edu_bachelors.or, 2)}×</b>; current active duty service raises them <b>${N(OR.mil_own.or, 2)}×</b> and prior service <b>${N(OR.veteran.or, 2)}×</b>; marrying before 23 adds <b>${N(OR.young_mar.or, 2)}×</b>; marriages past thirty years run at <b>${N(OR['durb_30+'].or, 2)}×</b> the odds of a ten to fourteen year marriage. Income, employment, renting and having children were deliberately left out of the fit because the survey measures them after the divorce, which makes them consequences as much as causes; they appear as exposure pools in modules 04 and 05 instead.</p></div>
    <div class="tiles" id="mktTiles"></div>
    <div class="grid2"><div class="panel"><h3>Divorce hazard by years since the wedding</h3><div class="sub">Divorces in the past year per 1,000 married adults by years since the wedding, Texas 2020 to 2024, three year centered average to take out marriage cohort bumps. The dashed lines mark one standard error either side, from the 80 replicate weights.</div><div class="chart" id="mktCurve"></div></div>
    <div class="panel"><h3>Hazard by group</h3><div class="sub">Same measure, per 1,000 married adults a year.</div><div class="chart" id="mktGroups"></div></div></div>
    <div class="grid2"><div class="panel"><h3>Marriage and divorce rates, Texas 1990 to 2023</h3><div class="sub">Per 1,000 residents, National Center for Health Statistics. Texas divorce counts reach NCHS through district clerk reports and undercount in some years (2019 to 2021 especially); the court filings in module 02 are the reliable series after 2019.</div><div class="chart" id="mktNchs"></div></div>
    <div class="panel"><h3>Married adults by age, Texas</h3><div class="sub">Where the installed base sits. The 25 to 44 band carries most divorces with children; 55 and over is the gray divorce pool. Weighted counts from the same 2020 to 2024 microdata as the hazard model, one band per age group; they count everyone married at some point in the year, so the total (${K(D.pums.married_w)}) runs above the ${K(s.married)} currently married in the ACS tables.</div><div class="chart" id="mktAge"></div></div></div>
    <div class="panel" style="margin-bottom:14px"><h3>What the model learned: odds ratios with 95% intervals</h3><div class="sub">Each term against its reference group (age 40 to 44, married 10 to 14 years, first marriage, high school, male, civilian, married at 23 or later). Right of the line raises the odds of a divorce in a given year, left lowers them; the bar is the 95% interval. The axis is logarithmic, so 0.5 and 2 sit the same distance from 1.</div><div class="chart" id="mktOR"></div></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', sel('mktLayer', Object.keys(MARKET_LAYERS).map(k => [k, MARKET_LAYERS[k].l]), st.layer))}${ctl('County', sel('mktCty', CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.sel))}</div><div class="split"><div><div class="mapwrap" id="mktMap"></div><p class="small" id="mktFirmN"></p></div><div id="mktSide"></div></div></div>
    <div class="panel"><h3>Counties</h3><div id="mktTable"></div></div>`;
    $('#mktTiles').innerHTML = tile('Married Texans', K(s.married), 'spouse present, ACS 2020 to 2024') + tile('Peak hazard band', N(G['dur_5-9'].haz, 1), 'per 1,000, married 5 to 9 years (0 to 1 yrs: ' + N(G['dur_0-1'].haz, 1) + ', 30+ yrs: ' + N(G['dur_30+'].haz, 1) + ')') + tile('Second marriages', N(G.times_2.haz, 1), 'per 1,000 vs ' + N(G.times_1.haz, 1) + ' for first marriages; third or later ' + N(G['times_3+'].haz, 1)) + tile('Bachelor\'s or higher', N(G.edu_bachelors.haz, 1), 'per 1,000 vs ' + N(G.edu_hs.haz, 1) + ' for high school only') + tile('Active duty', N(G.mil_active.haz, 1), 'per 1,000 married adults with a service member in the household; veterans ' + N(G.veteran.haz, 1)) + tile('Ages 30 to 44', N((G['age_30-34'].haz + G['age_35-39'].haz + G['age_40-44'].haz) / 3, 1), 'per 1,000; ages 60 to 64 ' + N(G['age_60-64'].haz, 1) + ', 65 and over ' + N(G['age_65+'].haz, 1));
    const raw = curve.filter(c => c.dur <= 36); const cv = raw.map((c, i) => { const w = raw.slice(Math.max(0, i - 1), i + 2); return { dur: c.dur, haz_per_1000: mean(w.map(x => x.haz_per_1000)), se: mean(w.map(x => x.se)) / Math.sqrt(w.length) }; }).filter(c => c.dur <= 35);
    lineChart($('#mktCurve'), { title: 'Divorce hazard by years since the wedding', series: [{ name: 'Upper bound, 1 SE', lname: 'One standard error band', color: 'var(--line-strong)', dash: true, values: cv.map(c => ({ x: c.dur, y: c.haz_per_1000 + c.se })) }, { name: 'Divorces per 1,000 married', color: 'var(--s1)', values: cv.map(c => ({ x: c.dur, y: c.haz_per_1000 })) }, { name: 'Lower bound, 1 SE', nolegend: true, color: 'var(--line-strong)', dash: true, values: cv.map(c => ({ x: c.dur, y: Math.max(0, c.haz_per_1000 - c.se) })) }], W: 640, H: 240, ymin: 0, xfmt: v => v < 1 ? 'Under 1 year since the wedding' : v + (v === 1 ? ' year' : ' years') + ' since the wedding', xTicks: [0, 5, 10, 15, 20, 25, 30, 35], yfmt: v => N(v, 0) });
    const gk = [['age_18-24', 'Age 18 to 24'], ['age_25-29', '25 to 29'], ['age_30-34', '30 to 34'], ['age_35-39', '35 to 39'], ['age_40-44', '40 to 44'], ['age_45-49', '45 to 49'], ['age_50-54', '50 to 54'], ['age_55-59', '55 to 59'], ['age_60-64', '60 to 64'], ['age_65+', '65 and over'], ['times_1', 'First marriage'], ['times_2', 'Second marriage'], ['times_3+', 'Third or later'], ['edu_lt_hs', 'Less than high school'], ['edu_hs', 'High school'], ['edu_some_college', 'Some college'], ['edu_bachelors', "Bachelor's"], ['edu_graduate', 'Graduate degree'], ['young_mar', 'Married before 23'], ['mar_23plus', 'Married at 23 or later'], ['mil_active', 'Active duty household'], ['veteran', 'Veteran'], ['civilian', 'No service']];
    barChart($('#mktGroups'), { title: 'Divorce hazard by group', rows: gk.map(k => ({ label: k[1], value: G[k[0]].haz, color: k[0].startsWith('age') ? 'var(--s1)' : k[0].startsWith('times') ? 'var(--s2)' : k[0].startsWith('edu') ? 'var(--s3)' : ['young_mar', 'mar_23plus'].includes(k[0]) ? 'var(--s4)' : 'var(--s5)' })), W: 520, lw: 150, fmt: v => N(v, 1) });
    const grpColor = k => /^ageb/.test(k) ? 'var(--s1)' : /^durb/.test(k) ? 'var(--s5)' : /^timesb/.test(k) ? 'var(--s2)' : /^edu/.test(k) ? 'var(--s3)' : k === 'young_mar' ? 'var(--s4)' : 'var(--s6)';
    coefPlot($('#mktOR'), { title: 'Hazard model odds ratios with 95% intervals', log: true, ref: 1, fmt: v => N(v, 2), lw: 190, rows: PUMS_TERMS.filter(t => OR[t[0]]).map(([k, label]) => { const c = OR[k]; const z = 1.96 * (c.se || 0); return { label, est: c.or, lo: c.or * Math.exp(-z), hi: c.or * Math.exp(z), color: grpColor(k) }; }) });
    const nY = Object.keys(ST.nchs.divorce).map(Number).sort((a, b) => a - b);
    lineChart($('#mktNchs'), { title: 'Marriage and divorce rates, Texas', series: [{ name: 'Marriage rate', color: 'var(--s1)', values: nY.map(y => ({ x: y, y: ST.nchs.marriage[y] })) }, { name: 'Divorce rate', color: 'var(--s2)', values: nY.map(y => ({ x: y, y: ST.nchs.divorce[y] })) }], W: 640, H: 220, ymin: 0, xfmt: v => String(v), xTicks: [1990, 1995, 2000, 2005, 2010, 2015, 2020, 2023], yfmt: v => N(v, 1) });
    // married adults by age: the microdata's own age groups (the county ACS fields overlap, 15 to 29 against 25 to 44, and have no
    // 45 to 54 column, so they cannot make clean bands); each band adds whole groups, none is a remainder
    const ageBands = [['18 to 24', ['age_18-24'], 'var(--s1)'], ['25 to 34', ['age_25-29', 'age_30-34'], 'var(--hl)'], ['35 to 44', ['age_35-39', 'age_40-44'], 'var(--hl)'], ['45 to 54', ['age_45-49', 'age_50-54'], 'var(--s1)'], ['55 to 64', ['age_55-59', 'age_60-64'], 'var(--s7)'], ['65 and over', ['age_65+'], 'var(--s7)']];
    barChart($('#mktAge'), { title: 'Married adults by age, Texas', rows: ageBands.map(([label, ks, color]) => ({ label, value: sum(ks.map(k => (G[k] || {}).w || 0)), color })), W: 520, lw: 120, fmt: v => K(v) });
    const mapEl = $('#mktMap');
    function draw() { const L = MARKET_LAYERS[st.layer]; const sc = layerScale(L, CTY); drawMap(mapEl, { title: 'Texas counties, ' + L.l, W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => L.v(CI[id]), color: sc.color, label: id => countyTipHTML(CI[id], `<div class="row"><span>${esc(L.l)}</span><span>${esc(L.f(L.v(CI[id])))}</span></div>`), onSelect: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); tbl.setSel(id); }, selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: L.l, grade: L.g }, sc.legend) }); ixMarkFirm(mapEl); const n = IX_FIRM().length; $('#mktFirmN').innerHTML = n ? `<span class="ix-legkeys"><span><i class="ix-sw firm"></i>Heavy outline: the ${n === 1 ? 'county' : n + ' counties'} the firm serves</span></span>` : ''; }
    function side() { const c = CI[st.sel]; if ($('#mktCty').value !== st.sel) $('#mktCty').value = st.sel; const r = c.risk, a = c.acs; $('#mktSide').innerHTML = `<h3 style="font-family:var(--display);font-size:20px">${esc(c.name)} County</h3><dl class="kv"><dt>Married adults</dt><dd>${N(a.married)}</dd><dt>Married share of adults</dt><dd>${P(a.married_sh15, 0)}</dd><dt>Married 25 to 44</dt><dd>${P(a.mar_25_44_sh, 0)}</dd><dt>Married 55 and over</dt><dd>${P(a.mar_55p_sh, 0)}</dd><dt>Under 5 years married</dt><dd>${P(r.dur_lt5, 0)}</dd><dt>5 to 9 years</dt><dd>${P(r.dur_5_9, 0)}</dd><dt>10 to 19 years</dt><dd>${P(r.dur_10_19, 0)}</dd><dt>20 years or more</dt><dd>${P(r.dur_20p, 0)}</dd><dt>Remarried</dt><dd>${P(r.remarried, 0)}</dd><dt>Married before 23</dt><dd>${P(r.young_mar, 0)}</dd><dt>Bachelor's or higher</dt><dd>${P(r.ba_plus, 0)}</dd><dt>Marriages in past year</dt><dd>${N(c.pools.married_ly_w)}</dd><dt>Divorces in past year (ACS)</dt><dd>${N(c.pools.div_ly_all_w)}</dd><dt>Observed hazard per 1,000</dt><dd>${N(r.haz_obs, 1)}</dd><dt>Modeled hazard per 1,000</dt><dd>${N(r.haz_pred, 1)}</dd><dt>Court filings per 1,000 married</dt><dd>${N(c.rates.div_per_1k_married, 1)}</dd></dl><p class="small" style="margin-top:8px">Composition shares come from the Public Use Microdata Areas that cover the county, weighted by population. Counties with fewer than about 100,000 residents share a PUMA with neighbors, so their composition is a regional estimate.</p>${IX_FIRM().includes(c.fips) ? '<div class="ix-own"><b>A county you serve</b> (firm profile).</div>' : ''}${ixAcctLine(c.fips)}<div class="ix-btns"><button type="button" class="btn sm" data-mh="index">Dissolution Index ↗</button><button type="button" class="btn sm" data-mh="lines">Service Lines ↗</button><button type="button" class="btn sm" data-mh="forecast">Filings Forecast ↗</button><button type="button" class="btn sm" data-mh="desk">Campaign Desk ↗</button><button type="button" class="btn sm" data-mh="ground">Ground Truth ↗</button></div>`; const go = { index: () => goModule('index', { county: c.fips }), lines: () => goModule('lines', { county: c.fips }), forecast: () => goModule('forecast', { county: c.fips }), desk: () => goModule('desk', { geo: 'cty:' + c.fips, counties: [c.fips] }), ground: () => goModule('ground', { county: c.fips }) }; $$('#mktSide [data-mh]').forEach(b => b.onclick = () => go[b.dataset.mh]()); }
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'married', l: 'Married', fmt: v => N(v), h: 'Married adults, spouse present (ACS)', d: 0 }, { k: 'msh', l: 'Married share', fmt: v => P(v, 0), h: 'Married share of adults 15 and over (%)', d: 0, pct: true }, { k: 'm2544', l: '25 to 44', fmt: v => P(v, 0), h: 'Married aged 25 to 44, share of married (%)', d: 0, pct: true }, { k: 'm55', l: '55+', fmt: v => P(v, 0), h: 'Married aged 55 and over, share of married (%)', d: 0, pct: true }, { k: 'd5', l: '<5 yrs', fmt: v => P(v, 0), h: 'Married under 5 years (%, PUMS)', d: 0, pct: true }, { k: 'd59', l: '5 to 9 yrs', fmt: v => P(v, 0), h: 'Married 5 to 9 years (%, PUMS)', d: 0, pct: true }, { k: 'rem', l: 'Remarried', fmt: v => P(v, 0), h: 'Remarried (%, PUMS)', d: 0, pct: true }, { k: 'young', l: 'Married <23', fmt: v => P(v, 0), h: 'Married before 23 (%, PUMS)', d: 0, pct: true }, { k: 'ba', l: 'BA+', fmt: v => P(v, 0), h: "Bachelor's or higher (%, PUMS)", d: 0, pct: true }, { k: 'inflow', l: 'Married last yr', fmt: v => N(v), h: 'Married in the past year (weighted survey count)', d: 0 }, { k: 'hobs', l: 'Obs hazard', fmt: v => N(v, 1), h: 'Observed divorces per 1,000 married (PUMS)', d: 1 }, { k: 'hpred', l: 'Model hazard', fmt: v => N(v, 1), h: 'Modeled divorces per 1,000 married', d: 1 }, { k: 'filing', l: 'Filings /1k', fmt: v => N(v, 1), h: 'Divorce filings per 1,000 married (court, last 12 months)', d: 1 }, { k: 'firm', l: 'Yours', fmt: v => v ? 'served' : '', h: 'Served by the firm (firm profile)' }];
    const rows = () => CTY.map(c => ({ _id: c.fips, name: c.name, married: c.acs.married, msh: c.acs.married_sh15, m2544: c.acs.mar_25_44_sh, m55: c.acs.mar_55p_sh, d5: c.risk.dur_lt5, d59: c.risk.dur_5_9, rem: c.risk.remarried, young: c.risk.young_mar, ba: c.risk.ba_plus, inflow: c.pools.married_ly_w, hobs: c.risk.haz_obs, hpred: c.risk.haz_pred, filing: c.rates.div_per_1k_married, firm: IX_FIRM().includes(c.fips) ? 1 : 0 }));
    const tbl = table($('#mktTable'), { caption: 'Counties, marriage composition', cols, rows: rows(), sort: { k: 'married', dir: -1 }, onRow: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); tbl.setSel(id); }, selected: st.sel });
    $('#mktLayer').onchange = e => { st.layer = e.target.value; draw(); };
    $('#mktCty').onchange = e => { const f = e.target.value; if (!CI[f]) return; st.sel = f; store.set('sev.county', f); markSel(mapEl, f); side(); tbl.setSel(f); };
    $('#mktCsv').onclick = () => exportText(expName('market', 'texas'), csv(tbl.sorted(), xcols([cols[0], { k: '_id', l: 'FIPS' }].concat(cols.slice(1))), { note: typeof csvNote === 'function' ? csvNote('market', ['Composition shares come from the survey areas covering each county; counties under about 100,000 residents share one with neighbors.']) : null }));
    draw(); side();
    this.sync = () => { const f = store.get('sev.county', st.sel); if (!CI[f] || f === st.sel) return; st.sel = f; markSel(mapEl, f); side(); tbl.setSel(f); };
    // the firm's counties are outlined and its accounts show beside the county; both follow the firm profile and Accounts
    const live = () => root.isConnected;
    BUS.on('firm', () => { if (!live()) return; draw(); side(); tbl.setRows(rows()); });
    BUS.on('actuals', () => { if (live()) side(); });
  },
  onShow() { if (this.sync) this.sync(); }
});
