'use strict';
/* Module 04: Risk Signals */
const SIGNALS = [
  { k: 'sep', n: 'Separated, not yet divorced', d: 'Separated adults per 1,000 married (ACS). The visible pipeline: Texas has no legal separation, so most of these become filings.', v: c => c.acs.sep_per_1k_married, f: v => N(v, 1), ramp: 'ember', ev: 'Pipeline measure', src: 'ACS B12001' },
  { k: 'dur59', n: 'Married 5 to 9 years', d: 'Share of married adults in the peak hazard band. Texas microdata: 22.6 divorces per 1,000 in this band vs 15.1 overall.', v: c => c.risk.dur_5_9, f: v => P(v, 0), ramp: 'ember', ev: 'Hazard 1.10× (model), 22.6 per 1,000', src: 'PUMS MARHYP' },
  { k: 'dur01', n: 'Married in the past year', d: 'Share of married adults who married in the last twelve months. Newlyweds carry the single highest hazard year (23 per 1,000 in year one). Also the prenup and annulment audience.', v: c => c.risk.mar_ly, f: v => P(v, 1), ramp: 'ember', ev: 'Hazard 1.13× in years 0 to 1', src: 'PUMS MARHM' },
  { k: 'rem', n: 'Remarried', d: 'Share of married adults on a second or later marriage. Second marriages carry 1.71× the odds, third or later 2.15×. Also the blended family, stepparent adoption and modification audience.', v: c => c.risk.remarried, f: v => P(v, 0), ramp: 'ember', ev: 'Odds 1.71× / 2.15×', src: 'PUMS MARHT' },
  { k: 'young', n: 'Married before 23', d: 'Early marriage raises the odds 1.21× in the Texas fit and is the most replicated predictor in the national literature.', v: c => c.risk.young_mar, f: v => P(v, 0), ramp: 'ember', ev: 'Odds 1.21×', src: 'PUMS' },
  { k: 'a2544', n: 'Married adults 25 to 44', d: 'Peak ages for divorce with children. Ages 30 to 44 run 20 per 1,000; ages 65 and over 6.', v: c => c.acs.mar_25_44_sh, f: v => P(v, 0), ramp: 'ember', ev: '20 per 1,000 at ages 30 to 44', src: 'ACS B12002' },
  { k: 'hs', n: 'High school or less', d: 'Share of married adults without college. A bachelor\'s degree cuts the odds to 0.64×; the effect is one of the largest in the model.', v: c => (c.risk.lt_hs || 0) + (c.risk.hs_only || 0), f: v => P(v, 0), ramp: 'ember', ev: 'BA odds 0.64×', src: 'PUMS SCHL' },
  { k: 'unemp', n: 'Unemployment in the marriage', d: 'Married adults who are unemployed or whose spouse is. Killewald: husband not employed full time 3.3% vs 2.5% annual divorce; Banzhaf: a husband\'s displacement raises the annual probability 56%.', v: c => c.risk.any_unemp, f: v => P(v, 1), ramp: 'steel', ev: 'Literature: +32% to +56%', src: 'PUMS couples' },
  { k: 'husb', n: 'Husband unemployed, kids at home', d: 'Married couple families with children where the husband is unemployed (ACS). The exposure the job loss literature is about.', v: c => c.acs.mc_kids_husb_unemp_sh, f: v => P(v, 1), ramp: 'steel', ev: 'Literature: husband\'s job loss', src: 'ACS B23007' },
  { k: 'wife', n: 'Wife out earns husband', d: 'Opposite sex couples where the wife\'s earnings exceed the husband\'s. Associated with higher dissolution in older cohorts; weak or absent in marriages formed after 1975 (Killewald). Shown as context, not weighted.', v: c => c.risk.wife_more, f: v => P(v, 0), ramp: 'amber', ev: 'Context', src: 'PUMS couples' },
  { k: 'dual', n: 'Dual earner couples', d: 'Both spouses employed. Two incomes make a divorce affordable, which matters when the economy turns.', v: c => c.risk.dual, f: v => P(v, 0), ramp: 'amber', ev: 'Affordability', src: 'PUMS couples' },
  { k: 'commute', n: 'Commute 45 minutes or more', d: 'Long commutes are linked to separation in Swedish registry work (about 40% higher over a decade). Texas microdata shows the same direction but the survey measures it after the fact.', v: c => c.risk.long_commute, f: v => P(v, 0), ramp: 'amber', ev: 'Literature', src: 'PUMS JWMNP' },
  { k: 'mil', n: 'Active duty households', d: 'Married adults with a service member in the household. Own active duty raises the odds 1.46×; Bell, Coryell, El Paso and Bexar hold most of the pool. Military divorce is its own service line.', v: c => c.risk.mil_active, f: v => P(v, 1), ramp: 'amber', ev: 'Odds 1.46×', src: 'PUMS MIL' },
  { k: 'vet', n: 'Veterans', d: 'Prior service raises the odds 1.37×. Also the audience for retirement division (USFSPA) and VA benefit questions.', v: c => c.acs.vet_sh, f: v => P(v, 0), ramp: 'amber', ev: 'Odds 1.37×', src: 'ACS B21001' },
  { k: 'cohab', n: 'Cohabiting couples with children', d: 'Not a divorce pool, a custody pool: these households end in SAPCR suits, paternity and support orders rather than decrees.', v: c => c.acs.cohab_kids_sh, f: v => P(v, 0), ramp: 'amber', ev: 'SAPCR demand', src: 'ACS B11012' },
  { k: 'unmar', n: 'Births to unmarried mothers', d: 'Share of births in the past year to unmarried women. Feeds paternity, Title IV-D and SAPCR filings two to five years later.', v: c => c.acs.births_unmar_sh, f: v => P(v, 0), ramp: 'amber', ev: 'Paternity and support demand', src: 'ACS B13002' },
  { k: 'single', n: 'Single parent families', d: 'Share of families with children headed by one parent. The modification and enforcement audience; existing orders get relitigated when incomes change.', v: c => c.acs.sp_kids_sh, f: v => P(v, 0), ramp: 'amber', ev: 'Modification demand', src: 'ACS B11003' },
  { k: 'gp', n: 'Grandparents raising grandchildren', d: 'Share of grandparents living with grandchildren under 18 who are responsible for them. Nonparent conservatorship and kinship placement work, harder to win since SB 2052 (2025).', v: c => c.acs.gp_resp_sh, f: v => P(v, 0), ramp: 'amber', ev: 'Nonparent suits', src: 'ACS B10051' },
  { k: 'rent', n: 'Rent burden 35% or more', d: 'Renter households paying 35% or more of income in rent. Financial strain both provokes conflict and blocks a filing that needs two households.', v: c => c.acs.rent_burden35_sh, f: v => P(v, 0), ramp: 'steel', ev: 'Strain', src: 'ACS B25070' },
  { k: 'mort', n: 'Mortgage burden 35% or more', d: 'Owner households with a mortgage paying 35% or more of income. The house is usually the contested asset.', v: c => c.acs.mort_burden35_sh, f: v => P(v, 0), ramp: 'steel', ev: 'Strain', src: 'ACS B25091' },
  { k: 'snap', n: 'SNAP households', d: 'Share of households receiving food assistance. Correlates with fee sensitivity and with Title IV-D rather than private representation.', v: c => c.acs.snap_sh, f: v => P(v, 0), ramp: 'steel', ev: 'Fee sensitivity', src: 'ACS B22010' },
  { k: 'pov', n: 'Married with kids, in poverty', d: 'Married couple families with children below the poverty line.', v: c => c.acs.mc_kids_pov_sh, f: v => P(v, 0), ramp: 'steel', ev: 'Strain', src: 'ACS B17010' },
  { k: 'renter', n: 'Renters among the married', d: 'Renting couples divorce more in every survey; part cause (less to divide, easier to leave), part effect.', v: c => c.risk.renter, f: v => P(v, 0), ramp: 'ember', ev: 'Mixed cause and effect', src: 'PUMS TEN' },
  { k: 'moved', n: 'Moved in the past year', d: 'Population churn. Newcomers have thinner local support networks and no lawyer yet.', v: c => c.acs.moved_sh, f: v => P(v, 0), ramp: 'slate', ev: 'Churn', src: 'ACS B07003' },
  { k: 'flfp', n: 'Married women in the labor force', d: 'Labor force participation among married women. Economic independence lowers the barrier to filing.', v: c => c.acs.mar_f_lf_sh, f: v => P(v, 0), ramp: 'slate', ev: 'Barrier to filing', src: 'ACS B12006' },
  { k: 'fv', n: 'Family violence in abuse investigations', d: 'DFPS abuse and neglect investigations with family violence indicated, FY2025, per 10,000 residents. The protective order pool.', v: c => c.dfps && c.dfps.inv_fv['2025'] != null ? c.dfps.inv_fv['2025'] / c.pop2025 * 10000 : null, f: v => N(v, 1), ramp: 'ember', ev: 'Protective order demand', src: 'DFPS CPI 3.3' },
  { k: 'cps', n: 'CPS removals', d: 'Children removed by DFPS in FY2025 per 10,000 residents. CPS defense and termination work.', v: c => c.dfps && c.dfps.removals['2025'] != null ? c.dfps.removals['2025'] / c.pop2025 * 10000 : null, f: v => N(v, 1), ramp: 'ember', ev: 'CPS defense demand', src: 'DFPS CPS 2.1' },
  { k: 'ur', n: 'Unemployment rate', d: 'Latest monthly county unemployment rate (LAUS via Texas LMI).', v: c => c.laus ? c.laus.ur : null, f: v => P1(v), ramp: 'steel', ev: 'Cycle', src: 'BLS LAUS' },
  { k: 'urchg', n: 'Unemployment rate change, 12 months', d: 'Percentage point change in the county unemployment rate against a year earlier.', v: c => c.econ.ur_chg_yoy, f: v => sgn(v, 1, ' pts'), ramp: 'div', ev: 'Cycle', src: 'BLS LAUS' },
  { k: 'gap', n: 'Age gap of 8 years or more', d: 'Couples with a large age gap. Not significant in the Texas fit once age and duration are held fixed.', v: c => c.risk.agegap8, f: v => P(v, 0), ramp: 'slate', ev: 'Not significant', src: 'PUMS couples' }
];
function wcorr(xs, ys, ws) { let sw = 0, mx = 0, my = 0; for (let i = 0; i < xs.length; i++) { if (!isN(xs[i]) || !isN(ys[i])) continue; sw += ws[i]; mx += ws[i] * xs[i]; my += ws[i] * ys[i]; } if (!sw) return null; mx /= sw; my /= sw; let cxy = 0, cxx = 0, cyy = 0; for (let i = 0; i < xs.length; i++) { if (!isN(xs[i]) || !isN(ys[i])) continue; cxy += ws[i] * (xs[i] - mx) * (ys[i] - my); cxx += ws[i] * (xs[i] - mx) ** 2; cyy += ws[i] * (ys[i] - my) ** 2; } return cxy / Math.sqrt(cxx * cyy || 1); }
registerModule({
  key: 'signals', num: '04', title: 'Risk Signals', desc: 'Thirty variables that precede a filing: separation, marriage cohorts, job loss in the household, custody pools, strain, violence',
  mount(root) {
    const st = { sig: 'sep', sel: store.get('sev.county', '48201') };
    const good = CTY.filter(c => c.grade === 'A' || c.grade === 'B');
    const ys = good.map(c => Math.log(c.rates.div_per_1k_married || 1)); const ws = good.map(c => Math.sqrt(c.pop2025));
    SIGNALS.forEach(s => { s.r = wcorr(good.map(s.v), ys, ws); });
    root.innerHTML = mastHTML({ eyebrow: 'Module 04 · Risk Signals · what precedes a filing, by county', title: 'Risk Signals', dek: `Thirty measured signals of marital dissolution and of the custody, support and protection work that follows it. Each card shows the direction, the evidence behind it (the Texas hazard model, the job loss literature, or a pool that feeds a specific case type) and its correlation with the divorce filing rate across the ${good.length} counties graded A or B. Click a card to map it and see where it concentrates. These feed the index in module 01 through the composition, separation, structure and strain components.`, facts: [[String(SIGNALS.length), 'signals'], [N(D.pums.n), 'married Texans in the hazard fit'], ['r', 'weighted correlation with log filings per 1,000 married'], [META.acs, 'and ' + META.pums]] }) + `
    <div class="toolbar"><span class="ttl">Risk Signals</span><span class="sub">Click a signal to map it</span><span class="sp"></span><button class="btn" id="sigCsv">↓ All signals by county CSV</button></div>
    <div class="callout judg"><div class="h">Judgment call: which signals carry weight</div><p>Only signals with a mechanism and a defensible estimate move the index: the composition hazard (age, duration, remarriage, education, military, age at marriage), separation, the economic shock, family structure and financial strain. Signals that are as much consequence as cause (renting, moving, the wife's earnings, commuting) are mapped for context and left out of the score. Nothing here uses race, ethnicity, religion, national origin or disability; those are excluded by design because ad platforms prohibit targeting on them and because a firm should not want to.</p></div>
    <div class="sig" id="sigCards"></div>
    <div class="panel" style="margin:14px 0"><div class="split"><div><h3 id="sigTitle"></h3><div class="sub" id="sigSub"></div><div class="mapwrap" id="sigMap"></div></div><div><h3>Top counties</h3><div class="sub">Grade A and B counties, highest values of the selected signal.</div><div id="sigTop"></div><h3 style="margin-top:12px">Selected county</h3><div class="controls" style="margin:6px 0">${ctl('County', sel('sigCty', CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.sel))}</div><div id="sigSel" class="small"></div></div></div></div>
    <div class="panel" style="margin:0 0 14px"><h3 id="sigScH"></h3><div class="sub" id="sigScSub"></div><div class="chart" id="sigScatter"></div></div>`;
    function cards() { $('#sigCards').innerHTML = SIGNALS.map(s => `<button type="button" data-k="${s.k}" aria-pressed="${st.sig === s.k}" class="${st.sig === s.k ? 'on' : ''}"><span class="n">${esc(s.n)}</span><span class="d">${esc(s.d)}</span><span class="m">${esc(s.ev)} · r = ${isN(s.r) ? MINUS(s.r.toFixed(2)) : NA} · ${esc(s.src)}</span></button>`).join(''); $$('#sigCards button').forEach(b => b.onclick = () => { st.sig = b.dataset.k; cards(); draw(); const nb = $(`#sigCards button[data-k="${st.sig}"]`); if (nb) nb.focus({ preventScroll: true }); }); }
    const mapEl = $('#sigMap');
    function draw() { const s = SIGNALS.find(x => x.k === st.sig); const L = { l: s.n, ramp: s.ramp, v: s.v, f: s.f }; const sc = layerScale(L, CTY); $('#sigTitle').textContent = s.n; $('#sigSub').textContent = s.d + ' Source: ' + s.src + '.'; drawMap(mapEl, { title: 'Texas counties, ' + s.n, W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => s.v(CI[id]), color: sc.color, label: id => countyTipHTML(CI[id], `<div class="row"><span>${esc(s.n)}</span><span>${esc(s.f(s.v(CI[id])))}</span></div>`), onSelect: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); selBox(); }, selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: s.n }, sc.legend) }); const top = good.slice().filter(c => isN(s.v(c))).sort((a, b) => s.v(b) - s.v(a)).slice(0, 12); $('#sigTop').innerHTML = `<table class="t"><caption class="vh">Top counties for ${esc(s.n)}</caption><thead><tr><th scope="col">County</th><th scope="col">${esc(s.n)}</th><th scope="col">Filings /1k married</th><th scope="col">Grade</th></tr></thead><tbody>${top.map(c => `<tr><td class="name"><button type="button" class="linkbtn" data-id="${c.fips}">${esc(c.name)}</button></td><td>${esc(s.f(s.v(c)))}</td><td>${N(c.rates.div_per_1k_married, 1)}</td><td><span class="grade ${c.grade}">${c.grade}</span></td></tr>`).join('')}</tbody></table>`; $$('#sigTop .linkbtn').forEach(td => td.onclick = () => { st.sel = td.dataset.id; store.set('sev.county', st.sel); markSel(mapEl, st.sel); selBox(); }); selBox(); }
    // the selected signal against the filing rate, the relation the card's r summarizes
    function plot() {
      const s = SIGNALS.find(x => x.k === st.sig);
      $('#sigScH').textContent = s.n + ' against the filing rate';
      $('#sigScSub').textContent = `Each dot is a county graded A or B (${good.length} counties), sized by population; filings per 1,000 married adults on a log scale. r = ${isN(s.r) ? MINUS(s.r.toFixed(2)) : NA}, weighted by the square root of population. Click a dot to select the county.`;
      scatter($('#sigScatter'), { title: s.n + ' against divorce filings per 1,000 married adults', W: 900, H: 320, ylog: true, xlab: s.n, xfmt: v => s.f(v), yfmt: v => N(v), selected: st.sel, onPoint: pick,
        points: good.map(c => ({ id: c.fips, label: c.name, x: s.v(c), y: c.rates.div_per_1k_married, r: c.pop2025, color: s.ramp === 'steel' ? 'var(--s3)' : s.ramp === 'amber' ? 'var(--s4)' : s.ramp === 'slate' ? 'var(--rp-slate-5)' : 'var(--s1)' })),
        tip: p => `<b>${esc(p.label)} County</b><div class="row"><span>${esc(s.n)}</span><span>${esc(s.f(p.x))}</span></div><div class="row"><span>Filings per 1,000 married</span><span>${N(p.y, 1)}</span></div>` });
    }
    function pick(f) { if (!CI[f]) return; st.sel = f; store.set('sev.county', f); markSel(mapEl, f); selBox(); }
    function selBox() { const c = CI[st.sel]; if ($('#sigCty').value !== st.sel) $('#sigCty').value = st.sel; plot(); $('#sigSel').innerHTML = `<b>${esc(c.name)} County</b><dl class="kv" style="margin-top:4px">${SIGNALS.map(s => `<dt>${esc(s.n)}</dt><dd>${esc(s.f(s.v(c)))}</dd>`).join('')}</dl>`; }
    cards(); draw();
    $('#sigCty').onchange = e => pick(e.target.value);
    this.sync = () => { const f = store.get('sev.county', st.sel); if (CI[f] && f !== st.sel) { st.sel = f; markSel(mapEl, f); selBox(); } };
    // export: each signal at the precision the cards show, shares as percents, units in the headers
    const SIGX = { dur01: [1, true], sep: [1, false, 'per 1,000 married'], unemp: [1, true], husb: [1, true], mil: [1, true], fv: [1, false, 'per 10,000 residents'], cps: [1, false, 'per 10,000 residents'], ur: [1, false, '%'], urchg: [1, false, 'points'] };
    $('#sigCsv').onclick = () => exportText(expName('signals', 'texas'), csv(CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => { const o = { fips: c.fips, county: c.name, grade: c.grade, filings_per_1k_married: c.rates.div_per_1k_married }; SIGNALS.forEach(s => o[s.k] = s.v(c)); return o; }), [{ l: 'County', k: 'county' }, { l: 'FIPS', k: 'fips' }, { l: 'Confidence grade', k: 'grade' }, { l: 'Divorce filings per 1,000 married adults', k: 'filings_per_1k_married', d: 1 }].concat(SIGNALS.map(s => { const x = SIGX[s.k] || [0, true]; return { l: `${s.n} (${x[1] ? '%' : x[2]})`, k: s.k, d: x[0], pct: x[1] }; }))));
  },
  onShow() { if (this.sync) this.sync(); }
});
