'use strict';
/* Module 05: Economic Shock */
const ECON_LAYERS = {
  esi: { l: 'Economic Shock Index (percentile)', ramp: 'steel', v: c => c.esi, f: v => N(v, 0), q: false },
  c19: { l: 'UI initial claims, last 13 weeks vs same weeks of 2019 (ratio)', ramp: 'steel', v: c => c.econ.claims_vs_2019, f: v => ecoX(v, 'no 2019 claims') },
  cyago: { l: 'UI initial claims, last 13 weeks vs a year earlier (ratio)', ramp: 'steel', v: c => c.econ.claims_vs_yago, f: v => ecoX(v, 'no claims a year earlier') },
  crate: { l: 'UI initial claims per 1,000 labor force, last 13 weeks', ramp: 'steel', v: c => c.econ.claims_per_1k_lf_13w, f: v => N(v, 1) },
  ur: { l: 'Unemployment rate, latest month', ramp: 'steel', v: c => c.laus ? c.laus.ur : null, f: v => P1(v) },
  urchg: { l: 'Unemployment rate change vs year earlier (points)', ramp: 'div', v: c => c.econ.ur_chg_yoy, f: v => sgn(v, 1, ' pts') },
  ur19: { l: 'Unemployment rate vs 2019 average (points)', ramp: 'div', v: c => c.econ.ur_vs_2019, f: v => sgn(v, 1, ' pts') },
  warn: { l: 'WARN layoff notices, workers per 1,000 jobs, last 12 months', ramp: 'steel', v: c => c.econ.warn_per_1k, f: v => N(v, 1) },
  qcew: { l: 'Payroll jobs, year over year change (QCEW ' + qcewQ() + ')', ramp: 'divinv', v: c => c.econ.qcew_pct, f: v => sgn(v, 1) },
  exposed: { l: 'Married adults where either spouse is unemployed (count, ACS 2020 to 2024)', ramp: 'steel', v: c => c.econ.married_exposed, f: v => N(v, 0), log: true },
  lift: { l: 'Expected divorce filings lift at 12 months from the claims change', ramp: 'div', v: c => c.econ.expected.m12_pct, f: v => sgn(v, 1) }
};
// a claims ratio, or what its missing base means (a county with no claims in the base weeks has no ratio, not 'n/a×')
function ecoX(v, none) { return isN(v) ? N(v, 2) + '×' : (none || NA); }
registerModule({
  key: 'econ', num: '05', title: 'Economic Shock', desc: 'Job losses by county, week by week: claims, unemployment, WARN notices, payrolls, and what they do to filings at 3 and 12 months',
  mount(root) {
    const st = { layer: 'esi', sel: store.get('sev.county', '48201'), skip2020: true };
    const pr = D.panel; const P12 = pr['ldiv|claims_0_12'], PP = pr['ldiv|claims_0_12|post2022'];
    const sw = ST.claims; const wk = sw.weekly; const n = wk.length; const w13 = sum(wk.slice(n - 13)); const w13p = sum(wk.slice(n - 65, n - 52));
    // the 2019 base is the sum of the county baselines (the statewide series is the sum of the counties week by week), so the statewide
    // ratio and the county ratios use the same 2019 weeks
    const w13_19 = sum(CTY.map(c => (c.ui && c.ui.w13_2019) || 0));
    const txl = ST.laus; const urNow = txl.ur[txl.ur.length - 1]; const urAgo = txl.ur[txl.ur.length - 13];
    const warn12 = sum(CTY.map(c => c.warn.last12.workers)); const exposed = sum(CTY.map(c => c.econ.married_exposed || 0));
    const shocked = CTY.filter(c => (c.esi || 0) >= 80);
    const dbl = b => (Math.exp(b * Math.log(2)) - 1) * 100;   // percent change per doubling of claims
    const sm = dbl(P12.coefs.lclaims.coef), sm2 = dbl(PP.coefs.lclaims.coef), r12 = dbl(P12.coefs.lclaims_l12.coef), r12b = dbl(PP.coefs.lclaims_l12.coef), pR = PP.coefs.lclaims_l12.p;
    const supWord = sm2 >= 0 ? 'has disappeared' : Math.abs(sm2) > Math.abs(sm) + 0.3 ? 'has been stronger' : Math.abs(sm2) < Math.abs(sm) - 0.3 ? 'has been weaker' : 'has been about the same';
    const rebWord = r12b < r12 - 0.3 ? 'smaller' : r12b > r12 + 0.3 ? 'larger' : 'about the same'; const rebSig = isN(pR) && pR >= 0.05 ? ` and not statistically significant (p = ${N(pR, 2)})` : '';
    const ladTo = MOL[txl.t0 % 12] + ' ' + Math.floor(txl.t0 / 12);
    const nSec = CTY.filter(c => c.sectors && c.sectors.length).length;
    root.innerHTML = mastHTML({ eyebrow: 'Module 05 · Economic Shock · Texas Workforce Commission claims, BLS LAUS and QCEW, WARN Act notices', title: 'Economic Shock', dek: `Where families are losing jobs, and what that does to family law demand. Weekly unemployment insurance initial claims for all 254 counties since January 2019, monthly unemployment rates since ${ladTo}, WARN layoff notices filed with the Texas Workforce Commission (yearly counts for every county and each county's 12 most recent notices), and quarterly payroll counts from the Census of Employment and Wages. The module scores each county's shock against its own 2019 baseline and against the rest of the state, then applies the lag structure estimated from the counties' own filing histories.`, facts: [[N(w13), 'initial claims statewide, last 13 weeks (' + sgn((w13 / w13_19 - 1) * 100) + ' vs 2019, ' + sgn((w13 / w13p - 1) * 100) + ' vs a year ago)'], [P1(urNow), 'Texas unemployment, ' + fmtDate(META.laus_through) + ' (' + sgn(urNow - urAgo, 1, ' pts') + ' vs year earlier)'], [N(warn12), 'workers on WARN notices, last 12 months'], [N(exposed), 'married Texans where either spouse is unemployed']] }) + `
    <div class="toolbar"><span class="ttl">Economic Shock</span><span class="sub">County shock index, weekly claims, layoffs, payrolls, lag model</span><span class="sp"></span><button class="btn" id="ecoCsv">↓ County shock CSV</button><button class="btn" id="ecoWarnCsv">↓ Recent WARN notices CSV (12 per county)</button></div>
    <div class="callout"><div class="h">Read this first: job loss raises a couple's divorce risk, and lowers the county's filings, at the same time</div><p>Two things are true and both show up in the data. At the household level, a job loss, especially the husband's, raises the chance of divorce: 3.3% a year against 2.5% when he works full time (Killewald, PSID), and a displacement raises the annual probability by roughly half (Banzhaf, SIPP), with layoffs mattering and plant closings not (Charles and Stephens). At the county level, a wave of job losses <b>suppresses filings first</b>: in the 43 Texas counties over 100,000 people, a doubling of weekly claims is followed by ${sgn(sm, 1)} in divorce filings the same month and ${sgn(dbl(P12.coefs.lclaims_l3.coef), 1)} three months later, then <b>${sgn(r12, 1)} twelve months later</b> (county, calendar month and year fixed effects, standard errors clustered by county). The statewide cross correlation between claims and divorce filings peaks at a twelve month lag. People who lose a job cannot afford two households or a retainer; the marriages that break under the strain reach the courthouse about a year later. For a firm that means: a county in shock today is a modification, enforcement and flat fee market now, and a contested divorce market next year. Since 2022 the same month suppression ${supWord} (${sgn(sm2, 1)} per doubling against ${sgn(sm, 1)} over the whole period) and the twelve month rebound ${rebWord} (${sgn(r12b, 1)} against ${sgn(r12, 1)})${rebSig}.</p></div>
    <div class="tiles">${tile('Top fifth on the shock index', String(shocked.length), 'counties at 80 or more on the shock index (a percentile rank): ' + shocked.slice().sort((a, b) => b.pop2025 - a.pop2025).slice(0, 6).map(c => c.name).join(', ') + (shocked.length > 6 ? ' and others' : ''))}${tile('Claims vs 2019', N(w13 / w13_19, 2) + '×', 'statewide initial claims, last 13 weeks against the same weeks of 2019')}${tile('Unemployment', P1(urNow), 'Texas, ' + fmtDate(META.laus_through) + '; 2019 average ' + P1(mean(txl.ur.slice(0, 12))))}${tile('WARN workers', N(warn12), 'on notices dated in the last 12 months (portal through ' + fmtDate(META.warn_through) + ')')}${tile('Same month effect', sgn(sm, 1), 'divorce filings per doubling of claims, same month (SE ' + N(P12.coefs.lclaims.se * 100 * Math.log(2), 1) + ' pts)')}${tile('Twelve month effect', sgn(r12, 1), 'divorce filings per doubling of claims, 12 months later (SE ' + N(P12.coefs.lclaims_l12.se * 100 * Math.log(2), 1) + ' pts)')}</div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', sel('ecoLayer', Object.keys(ECON_LAYERS).map(k => [k, ECON_LAYERS[k].l]), st.layer))}</div><div class="split"><div class="mapwrap" id="ecoMap"></div><div id="ecoSide"></div></div></div>
    <div class="grid2"><div class="panel"><h3>Statewide weekly initial claims</h3><div class="sub">Texas Workforce Commission, weeks ending ${esc(fmtDate(sw.week0))} to ${esc(fmtDate(META.ui_through))}. The 2020 spike (${N(Math.max(...wk))} in its peak week) is cut from the axis by default.</div><label class="chk"><input type="checkbox" id="ecoSkip" checked> Hide 2020 so the current level is readable</label><div class="chart" id="ecoClaims"></div></div>
    <div class="panel"><h3>What a claims surge does to filings, by lag</h3><div class="sub">Change in divorce filings per doubling of weekly claims at each lag, with its standard error in points; 43 large counties, 2019 to 2026. Positive means more filings.</div><div class="chart" id="ecoLag"></div><div class="small" id="ecoLagNote"></div></div></div>
    <div class="grid2"><div class="panel"><h3>County: weekly claims and unemployment</h3><div class="controls">${ctl('County', sel('ecoCty', CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.sel))}</div><div class="chart" id="ecoCtyClaims"></div><div class="chart" id="ecoCtyUr" style="margin-top:8px"></div></div>
    <div class="panel"><h3>County: layoffs and payrolls</h3><div class="sub" id="ecoWarnSub"></div><p class="small" id="ecoWarnCap" style="margin:-6px 0 6px"></p><div class="warnlist" id="ecoWarn"></div><h3 style="margin-top:12px">Payroll jobs by sector, year over year</h3><div class="sub">QCEW private employment, ${qcewQ()} vs ${qcewPrev()}, published for ${nSec} metro counties.</div><div class="chart" id="ecoSectors"></div></div></div>
    <div class="panel"><h3>Counties by shock</h3><div id="ecoTable"></div></div>${srcFoot([['Sources', `Texas Workforce Commission weekly unemployment insurance initial claims by county, weeks ending ${esc(fmtDate(sw.week0))} to ${esc(fmtDate(META.ui_through))}; BLS Local Area Unemployment Statistics, ${esc(ladTo)} to ${esc(fmtDate(META.laus_through))}; Texas Workforce Commission WARN notices (data.texas.gov 8w53-c4f6) through ${esc(fmtDate(META.warn_through))}; BLS QCEW through ${esc(qcewQ())}; ACS 2020 to 2024 for married adults.`], ['Judgment calls', 'The Economic Shock Index is a percentile rank, so a fifth of the counties are always at 80 or above; read the claims ratios and unemployment change for the size of a shock. Expected filings apply the 43 county panel elasticities to each county\'s change in claims.'], ['Caveats', 'WARN covers only layoffs large enough to require a notice, and the data keeps each county\'s 12 most recent notices; QCEW suppresses some county sectors; a county with no claims in a base period has no ratio.']])}`;
    const mapEl = $('#ecoMap');
    function draw() { const L = ECON_LAYERS[st.layer]; const sc = layerScale(L, CTY); drawMap(mapEl, { W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => L.v(CI[id]), color: sc.color, label: id => countyTipHTML(CI[id], st.layer === 'esi' ? '' : `<div class="row"><span>${esc(L.l)}</span><span>${esc(L.f(L.v(CI[id])))}</span></div>`), onSelect: id => select(id), selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: L.l }, sc.legend) }); }
    function side() { const c = CI[st.sel]; const e = c.econ, la = c.laus || {}, ui = c.ui || {}, q = c.qcew || {}; $('#ecoSide').innerHTML = `<h3 style="font-family:var(--display);font-size:20px">${esc(c.name)} County</h3><dl class="kv"><dt>Economic Shock Index</dt><dd>${N(c.esi, 0)}</dd><dt>Claims, last 13 weeks</dt><dd>${N(ui.w13)}</dd><dt>vs same weeks 2019</dt><dd>${ecoX(e.claims_vs_2019, 'no 2019 claims')}</dd><dt>vs a year earlier</dt><dd>${ecoX(e.claims_vs_yago, 'no claims a year earlier')}</dd><dt>Unemployment, ${esc(fmtDate(la.last))}</dt><dd>${P1(la.ur)}</dd><dt>Change vs year earlier</dt><dd>${sgn(e.ur_chg_yoy, 1, ' pts')}</dd><dt>vs 2019 average</dt><dd>${sgn(e.ur_vs_2019, 1, ' pts')}</dd><dt>WARN workers, 12 mo</dt><dd>${N(c.warn.last12.workers)} (${N(e.warn_per_1k, 1)} per 1,000 jobs)</dd><dt>Payroll jobs, ${esc(fmtQ(q.last))}</dt><dd>${N(q.emp)} (${sgn(q.emp_pct)})</dd><dt>Average weekly wage</dt><dd>${$$$(q.wage)} (${sgn(q.wage_pct)})</dd><dt>Married adults where either spouse is unemployed</dt><dd>${N(e.married_exposed)}</dd><dt>Expected filings, same month</dt><dd>${sgn(e.expected.now_pct, 1)}</dd><dt>at 3 months</dt><dd>${sgn(e.expected.m3_pct, 1)}</dd><dt>at 12 months</dt><dd>${sgn(e.expected.m12_pct, 1)}</dd></dl><p class="small" style="margin-top:6px">Expected filings apply the panel elasticities to this county's change in claims against a year earlier. They describe the county's aggregate, not any household.</p>`; }
    function select(id) { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); ctyCharts(); $('#ecoCty').value = id; if (tbl) tbl.setSel(id); }
    function claimsChart() { const vals = wk.map((v, i) => ({ x: i, y: v })); const flt = st.skip2020 ? vals.filter(p => { const d = dLocal(sw.week0); d.setDate(d.getDate() + p.x * 7); return d.getFullYear() !== 2020; }) : vals; const t = i => { const d = dLocal(sw.week0); d.setDate(d.getDate() + i * 7); return d; }; lineChart($('#ecoClaims'), { title: 'Texas weekly initial claims', series: [{ name: 'Initial claims', color: 'var(--s1)', values: flt }], W: 640, H: 220, area: true, ymin: 0, xfmt: v => 'Week ending ' + dateOf(t(v)), xTicks: wkYearTicks(sw.week0, n), gapBreak: 3, xTickFmt: v => String(t(v).getFullYear()), yfmt: v => K(v) }); }
    $('#ecoSkip').onchange = e => { st.skip2020 = e.target.checked; claimsChart(); ctyCharts(); };
    claimsChart();
    // percent per doubling of claims, as the tiles and module 06 show it, with the standard error in points; up is leaf, down is slate
    const lagRows = [['lclaims', 'Same month'], ['lclaims_l3', '3 months'], ['lclaims_l6', '6 months'], ['lclaims_l9', '9 months'], ['lclaims_l12', '12 months']].map(k => ({ label: k[1] + ' (SE ' + N(P12.coefs[k[0]].se * 100 * Math.log(2), 1) + ')', value: dbl(P12.coefs[k[0]].coef), color: P12.coefs[k[0]].coef >= 0 ? 'var(--rp-leaf-5)' : 'var(--rp-slate-5)' }));
    barChart($('#ecoLag'), { title: 'Change in divorce filings per doubling of claims, by lag', rows: lagRows, W: 520, lw: 150, fmt: v => sgn(v, 1) });
    const xc = pr.xcorr_state; const best = Object.keys(xc).reduce((a, b) => xc[b] > xc[a] ? b : a);
    $('#ecoLagNote').innerHTML = `Raw elasticities (log points of filings per log point of claims): ${['lclaims', 'lclaims_l3', 'lclaims_l6', 'lclaims_l9', 'lclaims_l12'].map(k => (P12.coefs[k].coef >= 0 ? '+' : '') + MINUS(P12.coefs[k].coef.toFixed(3))).join(', ')} at 0, 3, 6, 9 and 12 months. n = ${N(P12.n)} county months, R² ${N(P12.r2, 2)} with county, calendar month and year effects. Cumulative 0 to 12 months ${sgn(P12.cum * 100, 1)} per log point of claims (SE ${N(P12.cum_se * 100, 1)}). Modifications are the least cyclical line (cumulative ${sgn(pr['lmod|claims_0_12'].cum * 100, 1)}), enforcement since 2022 rises at 3 to 6 months (${sgn(pr['lenf|claims_0_12|post2022'].coefs.lclaims_l3.coef * 100, 1)} and ${sgn(pr['lenf|claims_0_12|post2022'].coefs.lclaims_l6.coef * 100, 1)} per log point). Statewide, the correlation between monthly claims and divorce filings peaks at a ${best} month lag (r = ${N(xc[best], 2)}, 2020 excluded).`;
    function ctyCharts() { const c = CI[st.sel]; const ui = c.ui, la = c.laus; if (ui) { const t = i => { const d = dLocal(ui.week0); d.setDate(d.getDate() + i * 7); return d; }; const vals = ui.weekly.map((v, i) => ({ x: i, y: v })).filter(p => !st.skip2020 || t(p.x).getFullYear() !== 2020); lineChart($('#ecoCtyClaims'), { series: [{ name: c.name + ' weekly initial claims', color: 'var(--s1)', values: vals }], W: 640, H: 180, area: true, ymin: 0, xfmt: v => 'Week ending ' + dateOf(t(v)), xTicks: wkYearTicks(ui.week0, ui.weekly.length), gapBreak: 3, xTickFmt: v => String(t(v).getFullYear()), yfmt: v => N(v) }); } else $('#ecoCtyClaims').innerHTML = `<div class="small">No weekly claims series for ${esc(c.name)} County.</div>`; if (la && la.ur_series) { lineChart($('#ecoCtyUr'), { series: [{ name: c.name + ' unemployment rate', color: 'var(--s2)', values: la.ur_series.map((v, i) => ({ x: la.series_t0 + i, y: v })) }, { name: 'Texas', color: 'var(--ink-3)', dash: true, values: txl.ur.map((v, i) => ({ x: txl.t0 + i, y: v })) }], W: 640, H: 160, ymin: 0, xfmt: tLabel, xTicks: [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026].map(y => y * 12), xTickFmt: v => String(v / 12), yfmt: v => P1(v) }); } else $('#ecoCtyUr').innerHTML = `<div class="small">No monthly unemployment series for ${esc(c.name)} County.</div>`; const w = c.warn; const wy = y => w['y' + y] ? N(w['y' + y].workers) : '0'; $('#ecoWarnSub').textContent = `${c.name} County: ${w.last12.notices} WARN notices covering ${N(w.last12.workers)} workers in the last 12 months; ${wy(2025)} workers in 2025, ${wy(2024)} in 2024, ${wy(2020)} in 2020.`;
      // the data keeps each county's 12 most recent notices of the last 24 months, so the list says when it is not the whole count
      $('#ecoWarnCap').textContent = w.recent.length ? `The ${w.recent.length === 1 ? 'notice' : w.recent.length + ' notices'} below ${w.recent.length === 1 ? 'is' : 'are'} the most recent on file${w.recent.length >= 12 ? ' (the data keeps 12 per county' + (w.last12.notices > w.recent.length ? `; the last 12 months alone had ${w.last12.notices}` : '') + ')' : ''}, dated ${fmtDate(w.recent[w.recent.length - 1].notice)} to ${fmtDate(w.recent[0].notice)}.` : '';
      $('#ecoWarn').innerHTML = w.recent.length ? w.recent.map(r => `<div><span title="${esc(CO(r.co))}">${esc(CO(r.co))} · ${esc(r.city)}</span><span>${esc(fmtDate(r.notice))}</span><span class="num">${N(r.n)}</span></div>`).join('') : '<div class="small">No WARN notices in the last 24 months.</div>';
      const sec = c.sectors; if (sec && sec.length) { const rows = sec.filter(s => isN(s.chg)).sort((a, b) => a.chg - b.chg).map(s => ({ label: s.name, value: s.chg, color: s.chg < 0 ? 'var(--rp-slate-5)' : 'var(--rp-leaf-5)' })); barChart($('#ecoSectors'), { title: c.name + ' County payroll change by sector', rows, W: 560, lw: 200, fmt: v => sgn(v, 0, '') }); } else $('#ecoSectors').innerHTML = `<div class="small">${c.msa ? `QCEW publishes no private sector detail for ${esc(c.name)} County; the sector panel covers the ${nSec} metro counties with published detail.` : `${esc(c.name)} County is outside the metro areas; QCEW sector detail is loaded for the ${nSec} metro counties with published detail.`}</div>`; }
    $('#ecoCty').onchange = e => select(e.target.value);
    $('#ecoLayer').onchange = e => { st.layer = e.target.value; draw(); };
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'esi', l: 'Shock idx', fmt: v => N(v, 0), h: 'Economic Shock Index (percentile)', d: 0 }, { k: 'w13', l: 'Claims 13w', fmt: v => N(v), h: 'UI initial claims, last 13 weeks', d: 0 }, { k: 'c19', l: 'vs 2019', fmt: v => ecoX(v, 'no base'), h: 'Claims vs same weeks of 2019 (ratio)', d: 2 }, { k: 'cy', l: 'vs yr ago', fmt: v => ecoX(v, 'no base'), h: 'Claims vs a year earlier (ratio)', d: 2 }, { k: 'ur', l: 'Unemp', fmt: v => P1(v), h: 'Unemployment rate, latest month (%)', d: 1 }, { k: 'urc', l: 'Δ 12mo', fmt: v => sgn(v, 1, ''), h: 'Unemployment rate change vs a year earlier (points)', d: 1 }, { k: 'warn', l: 'WARN 12mo', fmt: v => N(v), h: 'WARN workers, last 12 months', d: 0 }, { k: 'qcew', l: 'Jobs YoY', fmt: v => sgn(v), h: 'Payroll jobs change, year over year (%)', d: 1 }, { k: 'exp', l: 'Married exposed', fmt: v => N(v), h: 'Married adults where either spouse is unemployed (ACS)', d: 0 }, { k: 'lift', l: 'Lift 12mo', fmt: v => sgn(v, 1), h: 'Expected divorce filings lift at 12 months (%)', d: 1 }, { k: 'div', l: 'Divorce filings', fmt: v => N(v), h: 'Divorce filings, last 12 months', d: 0 }, { k: 'msa', l: 'Metro', fmt: v => esc(v), cls: 'l wrap', h: 'Metro area' }];
    const rows = () => CTY.map(c => ({ _id: c.fips, name: c.name, esi: c.esi, w13: c.ui ? c.ui.w13 : null, c19: c.econ.claims_vs_2019, cy: c.econ.claims_vs_yago, ur: c.laus ? c.laus.ur : null, urc: c.econ.ur_chg_yoy, warn: c.warn.last12.workers, qcew: c.econ.qcew_pct, exp: c.econ.married_exposed, lift: c.econ.expected.m12_pct, div: c.filings.ttm.div, msa: c.msa_title ? MNAME(c.msa_title) : 'non metro' }));
    const tbl = table($('#ecoTable'), { caption: 'Counties by economic shock', cols, rows: rows(), sort: { k: 'esi', dir: -1 }, onRow: select, selected: st.sel });
    $('#ecoCsv').onclick = () => exportText(expName('econ', 'texas'), csv(tbl.sorted(), xcols([cols[0], { k: '_id', l: 'FIPS' }].concat(cols.slice(1)))));
    // the 12 most recent notices per county (all the data keeps); each row carries the county's full 12 month count so the cap shows
    $('#ecoWarnCsv').onclick = () => { const rows = []; CTY.forEach(c => c.warn.recent.forEach(r => rows.push({ county: c.name, fips: c.fips, company: CO(r.co), filed: r.co, city: r.city, workers: r.n, notice: r.notice, layoff: r.layoff, n12: c.warn.last12.notices, w12: c.warn.last12.workers, kept: c.warn.recent.length }))); rows.sort((a, b) => String(b.notice || '').localeCompare(String(a.notice || '')) || (b.workers || 0) - (a.workers || 0)); exportText(expName('econ_warn_recent', 'texas'), csv(rows, [['county', 'County'], ['fips', 'FIPS'], ['company', 'Company'], ['filed', 'Company as filed'], ['city', 'City'], ['workers', 'Workers'], ['notice', 'Notice date'], ['layoff', 'Layoff date'], ['kept', 'Notices in this file for the county (12 most recent at most)'], ['n12', 'County notices, last 12 months (all)'], ['w12', 'County workers on notices, last 12 months (all)']].map(([k, l]) => ({ l, k, d: ['workers', 'n12', 'w12', 'kept'].includes(k) ? 0 : null })))); };
    draw(); side(); ctyCharts();
    this.sync = () => { const f = store.get('sev.county', st.sel); if (CI[f] && f !== st.sel) select(f); };
    this.receive = p => { if (p && CI[p.county]) { store.set('sev.county', p.county); this.sync(); } };
  },
  onShow() { if (this.sync) this.sync(); }
});
