'use strict';
/* Module 05: Economic Shock */
const ECON_LAYERS = {
  esi: { l: 'Economic Shock Index (percentile)', ramp: 'steel', v: c => c.esi, f: v => N(v, 0), q: false },
  c19: { l: 'UI initial claims, last 13 weeks vs same weeks of 2019 (ratio)', ramp: 'steel', v: c => c.econ.claims_vs_2019, f: v => N(v, 2) + '×' },
  cyago: { l: 'UI initial claims, last 13 weeks vs a year earlier (ratio)', ramp: 'steel', v: c => c.econ.claims_vs_yago, f: v => N(v, 2) + '×' },
  crate: { l: 'UI initial claims per 1,000 labor force, last 13 weeks', ramp: 'steel', v: c => c.econ.claims_per_1k_lf_13w, f: v => N(v, 1) },
  ur: { l: 'Unemployment rate, latest month', ramp: 'steel', v: c => c.laus ? c.laus.ur : null, f: v => P1(v) },
  urchg: { l: 'Unemployment rate change vs year earlier (points)', ramp: 'div', v: c => c.econ.ur_chg_yoy, f: v => sgn(v, 1, '') },
  ur19: { l: 'Unemployment rate vs 2019 average (points)', ramp: 'div', v: c => c.econ.ur_vs_2019, f: v => sgn(v, 1, '') },
  warn: { l: 'WARN layoff notices, workers per 1,000 jobs, last 12 months', ramp: 'steel', v: c => c.econ.warn_per_1k, f: v => N(v, 1) },
  qcew: { l: 'Payroll jobs, year over year change (QCEW Q1 2026)', ramp: 'divinv', v: c => c.econ.qcew_pct, f: v => sgn(v, 1) },
  exposed: { l: 'Married adults in a household with an unemployed spouse (count)', ramp: 'steel', v: c => c.econ.married_exposed, f: v => N(v, 0), log: true },
  lift: { l: 'Expected divorce filings lift at 12 months from the claims change', ramp: 'div', v: c => c.econ.expected.m12_pct, f: v => sgn(v, 1) }
};
registerModule({
  key: 'econ', num: '05', title: 'Economic Shock', desc: 'Job losses by county, week by week: claims, unemployment, WARN notices, payrolls, and what they do to filings at 3 and 12 months',
  mount(root) {
    const st = { layer: 'esi', sel: store.get('sev.county', '48201'), skip2020: true };
    const pr = D.panel; const P12 = pr['ldiv|claims_0_12'], PP = pr['ldiv|claims_0_12|post2022'];
    const sw = ST.claims; const wk = sw.weekly; const n = wk.length; const w13 = sum(wk.slice(n - 13)); const w13p = sum(wk.slice(n - 65, n - 52)); const w13_19 = sum(wk.slice(n - 13 - 52 * 7, n - 52 * 7));
    const txl = ST.laus; const urNow = txl.ur[txl.ur.length - 1]; const urAgo = txl.ur[txl.ur.length - 13];
    const warn12 = sum(CTY.map(c => c.warn.last12.workers)); const exposed = sum(CTY.map(c => c.econ.married_exposed || 0));
    const shocked = CTY.filter(c => (c.esi || 0) >= 80);
    root.innerHTML = mastHTML({ eyebrow: 'Module 05 · Economic Shock · Texas Workforce Commission claims, BLS LAUS and QCEW, WARN Act notices', title: 'Economic Shock', dek: `Where families are losing jobs, and what that does to family law demand. Weekly unemployment insurance initial claims for all 254 counties since January 2019, monthly unemployment rates since 2010, every WARN layoff notice filed with the Texas Workforce Commission, and quarterly payroll counts from the Census of Employment and Wages. The module scores each county's shock against its own 2019 baseline and against the rest of the state, then applies the lag structure estimated from the counties' own filing histories.`, facts: [[N(w13), 'initial claims statewide, last 13 weeks (' + sgn((w13 / w13_19 - 1) * 100) + ' vs 2019, ' + sgn((w13 / w13p - 1) * 100) + ' vs a year ago)'], [P1(urNow), 'Texas unemployment, ' + fmtDate(META.laus_through) + ' (' + sgn(urNow - urAgo, 1, ' pts') + ' vs year earlier)'], [N(warn12), 'workers on WARN notices, last 12 months'], [N(exposed), 'married Texans with an unemployed spouse or own unemployment']] }) + `
    <div class="toolbar"><span class="ttl">Economic Shock</span><span class="sub">County shock index, weekly claims, layoffs, payrolls, lag model</span><span class="sp"></span><button class="btn" id="ecoCsv">↓ County shock CSV</button><button class="btn" id="ecoWarnCsv">↓ WARN notices CSV</button></div>
    <div class="callout"><div class="h">Read this first: job loss raises a couple's divorce risk, and lowers the county's filings, at the same time</div><p>Two things are true and both show up in the data. At the household level, a job loss, especially the husband's, raises the chance of divorce: 3.3% a year against 2.5% when he works full time (Killewald, PSID), and a displacement raises the annual probability by roughly half (Banzhaf, SIPP), with layoffs mattering and plant closings not (Charles and Stephens). At the county level, a wave of job losses <b>suppresses filings first</b>: in the 43 Texas counties over 100,000 people, a doubling of weekly claims is followed by ${sgn((Math.exp(P12.coefs.lclaims.coef * Math.log(2)) - 1) * 100, 1)} in divorce filings the same month and ${sgn((Math.exp(P12.coefs.lclaims_l3.coef * Math.log(2)) - 1) * 100, 1)} three months later, then <b>${sgn((Math.exp(P12.coefs.lclaims_l12.coef * Math.log(2)) - 1) * 100, 1)} twelve months later</b> (county and month fixed effects, standard errors clustered by county). The statewide cross correlation between claims and divorce filings peaks at a twelve month lag. People who lose a job cannot afford two households or a retainer; the marriages that break under the strain reach the courthouse about a year later. For a firm that means: a county in shock today is a modification, enforcement and flat fee market now, and a contested divorce market next year. Since 2022 the same month suppression has been stronger (${sgn((Math.exp(PP.coefs.lclaims.coef * Math.log(2)) - 1) * 100, 1)} per doubling) and the twelve month rebound similar (${sgn((Math.exp(PP.coefs.lclaims_l12.coef * Math.log(2)) - 1) * 100, 1)}).</p></div>
    <div class="tiles">${tile('Counties in shock', String(shocked.length), 'Economic Shock Index of 80 or higher: ' + shocked.slice().sort((a, b) => b.pop2025 - a.pop2025).slice(0, 6).map(c => c.name).join(', ') + (shocked.length > 6 ? ' and others' : ''))}${tile('Claims vs 2019', N(w13 / w13_19, 2) + '×', 'statewide initial claims, last 13 weeks against the same weeks of 2019')}${tile('Unemployment', P1(urNow), 'Texas, ' + fmtDate(META.laus_through) + '; 2019 average ' + P1(mean(txl.ur.slice(0, 12))))}${tile('WARN workers', N(warn12), 'on notices dated in the last 12 months (portal through ' + fmtDate(META.warn_through) + ')')}${tile('Same month effect', sgn((Math.exp(P12.coefs.lclaims.coef * Math.log(2)) - 1) * 100, 1), 'divorce filings per doubling of claims, same month (SE ' + N(P12.coefs.lclaims.se * 100 * Math.log(2), 1) + ' pts)')}${tile('Twelve month effect', sgn((Math.exp(P12.coefs.lclaims_l12.coef * Math.log(2)) - 1) * 100, 1), 'divorce filings per doubling of claims, 12 months later (SE ' + N(P12.coefs.lclaims_l12.se * 100 * Math.log(2), 1) + ' pts)')}</div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', sel('ecoLayer', Object.keys(ECON_LAYERS).map(k => [k, ECON_LAYERS[k].l]), st.layer))}</div><div class="split"><div class="mapwrap" id="ecoMap"></div><div id="ecoSide"></div></div></div>
    <div class="grid2"><div class="panel"><h3>Statewide weekly initial claims</h3><div class="sub">Texas Workforce Commission, weeks ending ${esc(fmtDate(sw.week0))} to ${esc(fmtDate(META.ui_through))}. The 2020 spike (over 300,000 a week) is cut from the axis by default.</div><label class="chk"><input type="checkbox" id="ecoSkip" checked> Hide 2020 so the current level is readable</label><div class="chart" id="ecoClaims"></div></div>
    <div class="panel"><h3>What a claims surge does to filings, by lag</h3><div class="sub">Coefficients on log claims at each lag (elasticities), divorce filings, 43 large counties, 2019 to 2026. Positive means more filings.</div><div class="chart" id="ecoLag"></div><div class="small" id="ecoLagNote"></div></div></div>
    <div class="grid2"><div class="panel"><h3>County: weekly claims and unemployment</h3><div class="controls">${ctl('County', sel('ecoCty', CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.sel))}</div><div class="chart" id="ecoCtyClaims"></div><div class="chart" id="ecoCtyUr" style="margin-top:8px"></div></div>
    <div class="panel"><h3>County: layoffs and payrolls</h3><div class="sub" id="ecoWarnSub"></div><div class="warnlist" id="ecoWarn"></div><h3 style="margin-top:12px">Payroll jobs by sector, year over year</h3><div class="sub">QCEW private employment, 2026 Q1 vs 2025 Q1, metro counties only.</div><div class="chart" id="ecoSectors"></div></div></div>
    <div class="panel"><h3>Counties by shock</h3><div id="ecoTable"></div></div>`;
    const mapEl = $('#ecoMap');
    function draw() { const L = ECON_LAYERS[st.layer]; const sc = layerScale(L, CTY); drawMap(mapEl, { W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => L.v(CI[id]), color: sc.color, label: id => countyTipHTML(CI[id], `<div class="row"><span>${esc(L.l)}</span><span>${esc(L.f(L.v(CI[id])))}</span></div>`), onSelect: id => select(id), selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: L.l }, sc.legend) }); }
    function side() { const c = CI[st.sel]; const e = c.econ, la = c.laus || {}, ui = c.ui || {}, q = c.qcew || {}; $('#ecoSide').innerHTML = `<h3 style="font-family:var(--display);font-size:20px">${esc(c.name)} County</h3><dl class="kv"><dt>Economic Shock Index</dt><dd>${N(c.esi, 0)}</dd><dt>Claims, last 13 weeks</dt><dd>${N(ui.w13)}</dd><dt>vs same weeks 2019</dt><dd>${N(e.claims_vs_2019, 2)}×</dd><dt>vs a year earlier</dt><dd>${N(e.claims_vs_yago, 2)}×</dd><dt>Unemployment, ${esc(fmtDate(la.last))}</dt><dd>${P1(la.ur)}</dd><dt>Change vs year earlier</dt><dd>${sgn(e.ur_chg_yoy, 1, ' pts')}</dd><dt>vs 2019 average</dt><dd>${sgn(e.ur_vs_2019, 1, ' pts')}</dd><dt>WARN workers, 12 mo</dt><dd>${N(c.warn.last12.workers)} (${N(e.warn_per_1k, 1)} per 1,000 jobs)</dd><dt>Payroll jobs, ${esc(fmtQ(q.last))}</dt><dd>${N(q.emp)} (${sgn(q.emp_pct)})</dd><dt>Average weekly wage</dt><dd>${$$$(q.wage)} (${sgn(q.wage_pct)})</dd><dt>Married adults exposed</dt><dd>${N(e.married_exposed)}</dd><dt>Expected filings, same month</dt><dd>${sgn(e.expected.now_pct, 1)}</dd><dt>at 3 months</dt><dd>${sgn(e.expected.m3_pct, 1)}</dd><dt>at 12 months</dt><dd>${sgn(e.expected.m12_pct, 1)}</dd></dl><p class="small" style="margin-top:6px">Expected filings apply the panel elasticities to this county's change in claims against a year earlier. They describe the county's aggregate, not any household.</p>`; }
    function select(id) { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); ctyCharts(); $('#ecoCty').value = id; if (tbl) tbl.setSel(id); }
    function claimsChart() { const vals = wk.map((v, i) => ({ x: i, y: v })); const flt = st.skip2020 ? vals.filter(p => { const d = dLocal(sw.week0); d.setDate(d.getDate() + p.x * 7); return d.getFullYear() !== 2020; }) : vals; const t = i => { const d = dLocal(sw.week0); d.setDate(d.getDate() + i * 7); return d; }; lineChart($('#ecoClaims'), { series: [{ name: 'Initial claims', color: 'var(--s1)', values: flt }], W: 640, H: 220, area: true, ymin: 0, xfmt: v => 'Week ending ' + dateOf(t(v)), xTicks: wkYearTicks(sw.week0, n), gapBreak: 3, xTickFmt: v => String(t(v).getFullYear()), yfmt: v => K(v) }); }
    $('#ecoSkip').onchange = e => { st.skip2020 = e.target.checked; claimsChart(); };
    claimsChart();
    const lagRows = [['lclaims', 'Same month'], ['lclaims_l3', '3 months'], ['lclaims_l6', '6 months'], ['lclaims_l9', '9 months'], ['lclaims_l12', '12 months']].map(k => ({ label: k[1] + ' (±' + N(P12.coefs[k[0]].se, 2) + ')', value: P12.coefs[k[0]].coef, color: P12.coefs[k[0]].coef >= 0 ? 'var(--hl)' : 'var(--s1)' }));
    barChart($('#ecoLag'), { rows: lagRows, W: 520, lw: 150, fmt: v => (v >= 0 ? '+' : '') + MINUS(v.toFixed(3)) });
    const xc = pr.xcorr_state; const best = Object.keys(xc).reduce((a, b) => xc[b] > xc[a] ? b : a);
    $('#ecoLagNote').innerHTML = `n = ${N(P12.n)} county months, R² ${N(P12.r2, 2)} with county, month and year effects. Cumulative 0 to 12 months ${sgn(P12.cum * 100, 1)} per log point of claims (SE ${N(P12.cum_se * 100, 1)}). Modifications are the least cyclical line (cumulative ${sgn(pr['lmod|claims_0_12'].cum * 100, 1)}), enforcement since 2022 rises at 3 to 6 months (${sgn(pr['lenf|claims_0_12|post2022'].coefs.lclaims_l3.coef * 100, 1)} and ${sgn(pr['lenf|claims_0_12|post2022'].coefs.lclaims_l6.coef * 100, 1)} per log point). Statewide, the correlation between monthly claims and divorce filings peaks at a ${best} month lag (r = ${N(xc[best], 2)}, 2020 excluded).`;
    function ctyCharts() { const c = CI[st.sel]; const ui = c.ui, la = c.laus; if (ui) { const t = i => { const d = dLocal(ui.week0); d.setDate(d.getDate() + i * 7); return d; }; const vals = ui.weekly.map((v, i) => ({ x: i, y: v })).filter(p => !st.skip2020 || t(p.x).getFullYear() !== 2020); lineChart($('#ecoCtyClaims'), { series: [{ name: c.name + ' weekly initial claims', color: 'var(--s1)', values: vals }], W: 640, H: 180, area: true, ymin: 0, xfmt: v => 'Week ending ' + dateOf(t(v)), xTicks: wkYearTicks(ui.week0, ui.weekly.length), gapBreak: 3, xTickFmt: v => String(t(v).getFullYear()), yfmt: v => N(v) }); } if (la && la.ur_series) { lineChart($('#ecoCtyUr'), { series: [{ name: c.name + ' unemployment rate', color: 'var(--s2)', values: la.ur_series.map((v, i) => ({ x: la.series_t0 + i, y: v })) }, { name: 'Texas', color: 'var(--ink-3)', dash: true, values: txl.ur.map((v, i) => ({ x: txl.t0 + i, y: v })) }], W: 640, H: 160, ymin: 0, xfmt: tLabel, xTicks: [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026].map(y => y * 12), xTickFmt: v => String(v / 12), yfmt: v => P1(v) }); } const w = c.warn; $('#ecoWarnSub').textContent = `${c.name} County: ${w.last12.notices} WARN notices covering ${N(w.last12.workers)} workers in the last 12 months; ${w.y2025 ? N(w.y2025.workers) : 0} workers in 2025, ${w.y2024 ? N(w.y2024.workers) : 0} in 2024, ${w.y2020 ? N(w.y2020.workers) : 0} in 2020.`; $('#ecoWarn').innerHTML = w.recent.length ? w.recent.map(r => `<div><span title="${esc(CO(r.co))}">${esc(CO(r.co))} · ${esc(r.city)}</span><span>${esc(fmtDate(r.notice))}</span><span class="num">${N(r.n)}</span></div>`).join('') : '<div class="small">No WARN notices in the last 24 months.</div>'; const sec = c.sectors; if (sec && sec.length) { const rows = sec.filter(s => isN(s.chg)).sort((a, b) => a.chg - b.chg).map(s => ({ label: s.name, value: s.chg, color: s.chg < 0 ? 'var(--hl)' : 'var(--s3)' })); barChart($('#ecoSectors'), { rows, W: 560, lw: 200, fmt: v => sgn(v, 0, '') }); } else $('#ecoSectors').innerHTML = '<div class="small">Sector detail is loaded for the 86 metropolitan counties.</div>'; }
    $('#ecoCty').onchange = e => select(e.target.value);
    $('#ecoLayer').onchange = e => { st.layer = e.target.value; draw(); };
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'esi', l: 'Shock idx', fmt: v => N(v, 0) }, { k: 'w13', l: 'Claims 13w', fmt: v => N(v) }, { k: 'c19', l: 'vs 2019', fmt: v => N(v, 2) + '×' }, { k: 'cy', l: 'vs yr ago', fmt: v => N(v, 2) + '×' }, { k: 'ur', l: 'Unemp', fmt: v => P1(v) }, { k: 'urc', l: 'Δ 12mo', fmt: v => sgn(v, 1, '') }, { k: 'warn', l: 'WARN 12mo', fmt: v => N(v) }, { k: 'qcew', l: 'Jobs YoY', fmt: v => sgn(v) }, { k: 'exp', l: 'Married exposed', fmt: v => N(v) }, { k: 'lift', l: 'Lift 12mo', fmt: v => sgn(v, 1) }, { k: 'div', l: 'Divorce filings', fmt: v => N(v) }, { k: 'msa', l: 'Metro', fmt: v => esc(v) }];
    const rows = () => CTY.map(c => ({ _id: c.fips, name: c.name, esi: c.esi, w13: c.ui ? c.ui.w13 : null, c19: c.econ.claims_vs_2019, cy: c.econ.claims_vs_yago, ur: c.laus ? c.laus.ur : null, urc: c.econ.ur_chg_yoy, warn: c.warn.last12.workers, qcew: c.econ.qcew_pct, exp: c.econ.married_exposed, lift: c.econ.expected.m12_pct, div: c.filings.ttm.div, msa: MNAME(c.msa_title || '') }));
    const tbl = table($('#ecoTable'), { cols, rows: rows(), sort: { k: 'esi', dir: -1 }, onRow: select, selected: st.sel });
    $('#ecoCsv').onclick = () => exportText('severance_economic_shock.csv', csv(rows(), cols.map(c => ({ l: c.l, k: c.k }))));
    $('#ecoWarnCsv').onclick = () => { const rows = []; CTY.forEach(c => c.warn.recent.forEach(r => rows.push({ county: c.name, company: r.co, city: r.city, workers: r.n, notice: r.notice, layoff: r.layoff }))); exportText('severance_warn_recent.csv', csv(rows, ['county', 'company', 'city', 'workers', 'notice', 'layoff'].map(k => ({ l: k, k })))); };
    draw(); side(); ctyCharts();
  }
});
