'use strict';
/* Module 06: Service Lines */
// protective orders, last twelve months against calendar 2019, statewide (the angle quotes it)
const LN_PO19 = (() => { try { const a = ST.annual && ST.annual['2019']; const t = stTTM('po'); const v = a && a.f_po ? (t / a.f_po - 1) * 100 : null; return typeof v === 'number' && isFinite(v) ? v : null; } catch (e) { return null; } })();   // null where the data is not loaded (unit tests)
// lc: the name inside a sentence (legal acronyms keep their case); lcs: the short name inside a sentence
const LINE_META = {
  div_k: { name: 'Divorce with children', short: 'Divorce, kids', lc: 'divorce with children', lcs: 'divorce with children', cnt: c => c.lines.div_k.n, pool: c => c.lines.div_k.pool, poolName: 'married couple families with children', seas: 'div_k', cyc: 'ldiv', fee: 9500, kw: ['divorce lawyer', 'divorce attorney', 'child custody lawyer', 'divorce with kids', 'family law attorney', 'how to file for divorce in Texas', 'divorce mediation'], angle: 'Custody and the primary residence right decide the case; lead with conservatorship, the expanded standard possession order (default inside 50 miles since 2021) and child support guidelines (cap $11,700 net since September 2025). Texas terms: conservatorship, possession and access, SAPCR.', law: 'Tex. Fam. Code §§ 6.702 (60 day wait), 153.131 (JMC presumption), 153.3171 (ESPO), 154.125 (guidelines, $11,700 cap).' },
  div_nk: { name: 'Divorce without children', short: 'Divorce, no kids', lc: 'divorce without children', lcs: 'divorce without children', cnt: c => c.lines.div_nk.n, pool: c => c.lines.div_nk.pool, poolName: 'married couples without children at home', seas: 'div', cyc: 'ldiv', fee: 4500, kw: ['uncontested divorce', 'agreed divorce', 'divorce without kids', 'cheap divorce lawyer', 'flat fee divorce', 'divorce papers Texas', 'how long does divorce take in Texas'], angle: 'Half of these are agreed. Flat fee and prove up by affidavit offers convert; the 60 day floor and the property division standard (just and right, not 50/50) are the two facts to state.', law: '§ 7.001 (just and right division), § 3.003 (community presumption), § 6.702.' },
  sapcr: { name: 'Custody and SAPCR', short: 'Custody / SAPCR', lc: 'custody suits (SAPCR)', lcs: 'custody (SAPCR)', cnt: c => c.lines.sapcr.n, pool: c => c.lines.sapcr.pool, poolName: 'cohabiting couples with children plus single parent families', seas: 'sapcr', cyc: 'lsapcr', fee: 6500, kw: ['child custody attorney', 'custody lawyer', 'fathers rights lawyer', 'unmarried parents custody Texas', 'SAPCR', 'paternity lawyer', 'custody agreement Texas'], angle: 'Unmarried parents. Rights attach through an acknowledgment of paternity or adjudication, not the birth certificate; the geographic restriction and the primary residence designation are what parents search for.', law: 'ch. 153, ch. 160 (paternity), § 153.009 (child interview at 12).' },
  mod: { name: 'Modification', short: 'Modification', lc: 'modifications', lcs: 'modification', cnt: c => c.lines.mod.n, pool: c => c.lines.mod.pool, poolName: 'single parent households (existing orders)', seas: 'mod', cyc: 'lmod', fee: 4000, kw: ['modify child support Texas', 'custody modification lawyer', 'change custody order', 'reduce child support after job loss', 'modification attorney', 'relocation custody Texas'], angle: 'The counter cyclical line. Income drops trigger support modifications (material change, or 3 years and 20% or $100), and the 2025 rule that three possession contempt findings are a material change opens custody modifications. Lead with job loss language when the county shock index is high.', law: '§ 156.101, § 156.401, § 156.107 (new 2025).' },
  enf: { name: 'Enforcement', short: 'Enforcement', lc: 'enforcement', lcs: 'enforcement', cnt: c => c.lines.enf.n, pool: c => c.lines.enf.pool, poolName: 'single parent households (existing orders)', seas: 'enf', cyc: 'lenf', fee: 3500, kw: ['child support enforcement lawyer', 'contempt of court child support', 'enforce visitation order', 'ex not following custody order', 'back child support Texas', 'possession enforcement'], angle: 'In the 2022 on panel, enforcement filings rise three to six months after a claims surge (the Cycle chart, 2022 on). Each missed support payment becomes a judgment carrying 6% simple interest, income withholding can continue until the arrears are paid, and the court can confirm the arrears in a money judgment within ten years after the child turns 18 or the order ends. Support and possession are independent obligations (the § 105.006(e) warning), which is the fact parents get wrong.', law: 'ch. 157 (§ 157.005, § 157.166, § 157.261, § 157.265), § 105.006(e).' },
  po: { name: 'Protective orders', short: 'Protective orders', lc: 'protective orders', lcs: 'protective order', cnt: c => c.lines.po.n, pool: c => c.lines.po.pool, poolName: 'DFPS investigations with family violence indicated, FY2025', seas: 'po', cyc: 'lpo', fee: 3000, kw: ['protective order lawyer', 'restraining order Texas', 'family violence attorney', 'emergency protective order', 'domestic violence lawyer', 'defend protective order'], angle: (LN_PO19 != null ? `${LN_PO19 >= 0 ? 'Up' : 'Down'} ${Math.round(Math.abs(LN_PO19))}% statewide in the last twelve months against calendar 2019. ` : '') + 'Since 2023 the applicant proves violence occurred, not that it will recur; since September 2025 an order tied to a pending divorce or SAPCR runs until two years after the final decree. Two audiences: applicants and respondents. A TRO is not a protective order.', law: 'ch. 85, § 85.025, SB 1120 (2025), § 81.012.' },
  ivd: { name: 'Child support and paternity (IV-D)', short: 'Support / paternity', lc: 'child support and paternity (IV-D)', lcs: 'support or paternity', cnt: c => c.lines.ivd.n, pool: c => c.lines.ivd.pool, poolName: 'births to unmarried mothers in the past year', seas: 'ivd', cyc: null, fee: 2500, kw: ['child support lawyer', 'paternity test Texas', 'establish paternity', 'child support calculator Texas', 'attorney general child support hearing', 'IV-D court lawyer'], angle: 'Most IV-D cases are handled by the Attorney General; private demand is the parent who wants representation at the IV-D docket or a deviation from guidelines. Volume fell sharply after 2019 as OAG reporting changed; treat counts as a floor.', law: 'ch. 154, ch. 160, ch. 231 (Title IV-D agency).' },
  adopt: { name: 'Adoption', short: 'Adoption', lc: 'adoption', lcs: 'adoption', cnt: c => c.lines.adopt.n, pool: c => null, poolName: 'stepparent, kinship and private adoptions', seas: null, cyc: null, fee: 4000, kw: ['adoption attorney', 'stepparent adoption Texas', 'kinship adoption', 'terminate parental rights', 'adoption lawyer near me', 'adult adoption Texas'], angle: 'Stepparent adoption follows remarriage; the remarried share in module 04 is the audience. Termination first, child 12 or older consents, six month residence.', law: 'ch. 162, § 161.001.' },
  cps: { name: 'CPS and termination defense', short: 'CPS defense', lc: 'CPS and termination defense', lcs: 'CPS defense', cnt: c => c.lines.cps.n, pool: c => c.lines.cps.pool, poolName: 'CPS removals FY2025', seas: null, cyc: null, fee: 5000, kw: ['CPS lawyer', 'CPS investigation attorney', 'DFPS removal lawyer', 'terminate parental rights defense', 'child protective services attorney Texas', 'family preservation'], angle: 'Removals halved statewide after 2021 but the 14 day adversary hearing and the one year dismissal clock make speed the pitch. Ground (O) was repealed in 2025; anonymous reports are no longer accepted.', law: '§ 262.201, § 263.401, HB 116 (2025).' },
  prenup: { name: 'Premarital agreements', short: 'Prenups', lc: 'premarital agreements', lcs: 'premarital agreement', est: true, cnt: c => c.lines.prenup.est, pool: c => c.lines.prenup.pool, poolName: 'people who married in the past year (inflow)', seas: null, cyc: null, fee: 2500, kw: ['prenup lawyer', 'prenuptial agreement Texas', 'postnuptial agreement', 'premarital agreement attorney', 'how much does a prenup cost', 'partition agreement'], angle: 'Texas prenups are among the most enforceable anywhere (§ 4.006 exclusive defenses). Estimate assumes 6% of new marriages retain counsel; the affluent ZIPs in the metro tabs carry most of it.', law: 'ch. 4, § 4.006.' },
  high: { name: 'Divorce over $150,000 (high asset)', short: 'High asset', lc: 'high asset divorce (households over $150,000)', lcs: 'high asset divorce', est: true, cnt: c => c.lines.high.n, pool: c => c.lines.high.pool, poolName: 'married adults in households over $150,000', seas: 'div', cyc: 'ldiv', fee: 35000, kw: ['high net worth divorce attorney', 'business owner divorce Texas', 'executive divorce lawyer', 'divorce stock options', 'separate property tracing', 'complex property division'], angle: 'Filings scaled by the county share of married adults in households over $150,000 and the 0.59 relative hazard of that income band. Seven figure estates (business interests, stock plans, multiple properties) are roughly a fifth of this pool. Reimbursement claims run on the unified unjust enrichment standard since 2023; tracing and the clear and convincing burden for separate property are the technical hooks.', law: '§ 3.001, § 3.003, ch. 3 subch. E (HB 1547, 2023).' },
  mil: { name: 'Military divorce', short: 'Military', lc: 'military divorce', lcs: 'military divorce', est: true, cnt: c => c.lines.mil.n, pool: c => c.lines.mil.pool, poolName: 'active duty service members', seas: 'div', cyc: null, fee: 8000, kw: ['military divorce lawyer', 'Fort Hood divorce attorney', 'Fort Bliss divorce lawyer', 'military custody deployment', 'USFSPA retirement division', 'SCRA divorce'], angle: 'Filings scaled by active duty exposure and the 1.46× hazard. Bell and Coryell (Fort Hood, named Fort Cavazos from 2023 to June 2025), El Paso (Fort Bliss) and Bexar (JBSA) hold the pool. Residency counts military stationing (§§ 6.303 to 6.304); the Servicemembers Civil Relief Act stays proceedings.', law: '§§ 6.303 to 6.304, 10 U.S.C. § 1408 (USFSPA).' },
  gray: { name: 'Gray divorce (50 and over)', short: 'Gray divorce', lc: 'gray divorce (50 and over)', lcs: 'gray divorce', est: true, cnt: c => c.lines.gray.n, pool: c => c.lines.gray.pool, poolName: 'married adults aged 55 and over', seas: 'div', cyc: 'ldiv', fee: 12000, kw: ['divorce after 50', 'gray divorce attorney', 'divorce retirement accounts Texas', 'QDRO lawyer', 'divorce social security', 'late life divorce'], angle: 'Filings scaled by the age specific hazard (ages 50 to 64 run 13 per 1,000, 65 and over 6). Retirement division, QDROs and spousal maintenance (10 year marriages, capped at the lesser of $5,000 or 20% of gross) are the topics.', law: 'ch. 8 (§ 8.051, § 8.055), § 7.001.' }
};
registerModule({
  key: 'lines', num: '06', title: 'Service Lines', desc: 'Thirteen family law service lines resolved to the county: counts, pools, seasons, cyclicality and the Texas facts that sell each one',
  mount(root) {
    const st = { line: 'div_k', sel: store.get('sev.county', '48201'), period: null };
    const ids = Object.keys(LINE_META);
    const stateTot = id => sum(CTY.map(c => LINE_META[id].cnt(c) || 0));
    root.innerHTML = mastHTML({ eyebrow: 'Module 06 · Service Lines · what the demand splits into', title: 'Service Lines', dek: `A family law firm does not sell "family law"; it sells thirteen distinct things to thirteen distinct audiences with different seasons, different price points and different reactions to a recession. This module splits every county's demand into those lines. Nine come straight from the court filing categories; four (prenups, high asset, military and gray divorce) are estimated by scaling divorce filings with the composition of the county's married population and the hazard model.`, facts: [[N(stateTot('div_k')), 'divorces with children, statewide, last 12 months'], [N(stateTot('sapcr')), 'custody suits without a divorce'], [N(stateTot('mod') + stateTot('enf')), 'modifications and enforcements'], [N(stateTot('po')), 'protective orders']] }) + `
    <div class="toolbar"><span class="ttl">Service Lines</span><span class="sub">Pick a line; the map, table and playbook follow</span><span class="sp"></span><button class="btn" id="lnCsv">↓ Lines by county CSV</button><button class="btn" id="lnLineCsv">↓ This line by county CSV</button><button class="btn" id="lnZipCsv">↓ ZIPs by line CSV</button></div>
    <div id="lnCards" class="lncards"></div>
    <div class="panel" style="margin:14px 0"><div class="split"><div><h3 id="lnTitle"></h3><div class="sub" id="lnSub"></div><div class="mapwrap" id="lnMap"></div></div><div id="lnPlay"></div></div></div>
    <div class="grid2"><div class="panel"><h3>Season</h3><div class="sub" id="lnSeasSub"></div><div id="lnSeas"></div></div><div class="panel"><h3>Cycle</h3><div class="sub">How this line responds to a doubling of unemployment claims, by lag, from the county panel.</div><div id="lnCycSeg"></div><div class="chart" id="lnCyc"></div><div class="small" id="lnCycNote"></div></div></div>
    <div class="panel"><h3>Counties</h3><div id="lnTable"></div></div>`;
    // nine lines are court counts and four are estimates; two groups, laid out so no card sits alone on a row
    const EST_LINES = ['prenup', 'high', 'mil', 'gray'];
    function cards() {
      const card = id => { const L = LINE_META[id]; const tot = stateTot(id); return `<div class="line ${st.line === id ? 'on' : ''}" data-id="${id}" role="button" tabindex="0" data-kbd aria-pressed="${st.line === id}"><div class="t">${esc(L.name)}</div><div class="v">${N(tot)}</div><div class="s">${id === 'prenup' ? 'estimated retained matters a year' : ['high', 'mil', 'gray'].includes(id) ? 'estimated filings, last 12 months' : 'filings, last 12 months'} · pool: ${esc(L.poolName)}</div></div>`; };
      const court = ids.filter(id => !EST_LINES.includes(id)), est = ids.filter(id => EST_LINES.includes(id));
      $('#lnCards').innerHTML = `<p class="small" style="margin:0 0 4px">Statewide totals add each county's latest twelve months: ${esc(ttmSpan())} for the ${CTY.filter(c => c.filings.series).length} counties with monthly clerk reports, calendar 2025 for the rest.</p><h2 class="minihd" id="lnCourtH">Court counts</h2><div class="linebox ln-court" role="group" aria-labelledby="lnCourtH">${court.map(card).join('')}</div>${est.length ? `<h2 class="minihd" id="lnEstH">Estimated from the married population and the hazard model</h2><div class="linebox ln-est" role="group" aria-labelledby="lnEstH">${est.map(card).join('')}</div>` : ''}`;
      $$('#lnCards .line').forEach(d => d.onclick = () => { const keep = document.activeElement === d; st.line = d.dataset.id; cards(); draw(); if (keep) { const n = $(`#lnCards .line[data-id="${st.line}"]`); if (n) n.focus({ preventScroll: true }); } });
    }
    const mapEl = $('#lnMap');
    function draw() {
      const L = LINE_META[st.line]; const v = c => { const n = L.cnt(c); return isN(n) ? n / c.pop2025 * 10000 : null; };
      const lay = { l: L.name + ' per 10,000 residents', ramp: 'ember', v, f: x => N(x, 1) }; const sc = layerScale(lay, CTY);
      $('#lnTitle').textContent = L.name; $('#lnSub').textContent = 'Per 10,000 residents, last twelve months. Hover for counts and pools.';
      drawMap(mapEl, { W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => v(CI[id]), color: sc.color, label: id => { const c = CI[id]; return `<b>${esc(c.name)} County</b><div class="row"><span>${esc(L.name)}</span><span>${N(L.cnt(c))}</span></div><div class="row"><span>per 10,000</span><span>${N(v(c), 1)}</span></div><div class="row"><span>Pool: ${esc(L.poolName)}</span><span>${isN(L.pool(c)) ? N(L.pool(c)) : 'not modeled'}</span></div>`; }, onSelect: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); play(); tbl.setSel(id); }, selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: lay.l }, sc.legend) });
      if (L.seas && ST.seas[L.seas]) { seasBlock($('#lnSeas'), ST.seas[L.seas], 'ember'); const s = ST.seas[L.seas]; const proxy = L.seas !== st.line; $('#lnSeasSub').textContent = proxy ? `The courts report no separate monthly count for ${L.lc}, so this is the statewide monthly index for all divorce filings, used as the proxy (2022 to 2025 average = 100). Peak ${MOL[s.indexOf(Math.max(...s))]}, trough ${MOL[s.indexOf(Math.min(...s))]}.` : `Statewide monthly index for ${L.lc} (2022 to 2025 average = 100). Peak ${MOL[s.indexOf(Math.max(...s))]}, trough ${MOL[s.indexOf(Math.min(...s))]}.`; } else { $('#lnSeas').innerHTML = '<div class="small">No monthly court series for this line; use the divorce season as the proxy.</div>'; $('#lnSeasSub').textContent = ''; }
      cycle();
      tbl.setRows(rows());
      play();
    }
    function cycle() {
      const L = LINE_META[st.line]; const post = L.cyc && D.panel[L.cyc + '|claims_0_12|post2022']; const per = post ? (st.period || (st.line === 'enf' ? 'post' : 'all')) : 'all';
      $('#lnCycSeg').innerHTML = post ? `<div class="seg" role="group" aria-label="Panel period" style="margin:0 0 8px"><button type="button" data-v="all" aria-pressed="${per === 'all'}">2019 to 2026</button><button type="button" data-v="post" aria-pressed="${per === 'post'}">2022 on</button></div>` : '';
      $$('#lnCycSeg button').forEach(b => b.onclick = () => { st.period = b.dataset.v; cycle(); });
      if (L.cyc && D.panel[L.cyc + '|claims_0_12']) { const pr = per === 'post' ? post : D.panel[L.cyc + '|claims_0_12']; barChart($('#lnCyc'), { title: L.name + ': change in filings per doubling of claims, by lag' + (per === 'post' ? ', 2022 on' : ''), rows: [['lclaims', 'Same month'], ['lclaims_l3', '3 months'], ['lclaims_l6', '6 months'], ['lclaims_l9', '9 months'], ['lclaims_l12', '12 months']].map(k => ({ label: k[1], value: (Math.exp(pr.coefs[k[0]].coef * Math.log(2)) - 1) * 100, color: pr.coefs[k[0]].coef >= 0 ? 'var(--rp-leaf-5)' : 'var(--rp-slate-5)' })), W: 460, lw: 110, fmt: x => sgn(x, 1) }); $('#lnCycNote').textContent = `Percent change in filings per doubling of claims, ${per === 'post' ? 'panel from 2022 on' : 'panel 2019 to 2026'}${L.cyc === 'ldiv' && st.line !== 'div_k' && st.line !== 'div_nk' ? ', all divorce filings (no separate series for this line)' : ''}. Cumulative through 12 months: ${sgn((Math.exp(pr.cum * Math.log(2)) - 1) * 100, 1)}.`; } else { $('#lnCyc').innerHTML = '<div class="small">No monthly series to estimate a cycle for this line.</div>'; $('#lnCycNote').textContent = ''; }
    }
    function play() { const L = LINE_META[st.line]; const c = CI[st.sel]; const n = L.cnt(c); const est = L.est ? ' (est.)' : ''; const pl = L.pool(c); $('#lnPlay').innerHTML = `<h3 style="font-family:var(--display);font-size:20px">${esc(c.name)} County · ${esc(L.name)}</h3>${L.est ? '<p class="small" style="margin:2px 0 6px">An estimate, not a court count: divorce filings scaled by the married population and the hazard model (module 20 has the method).</p>' : ''}<dl class="kv"><dt>${st.line === 'prenup' ? 'Retained matters a year' : 'Matters, last 12 months'}${est}</dt><dd>${N(n)}</dd><dt>Per 10,000 residents</dt><dd>${N(isN(n) ? n / c.pop2025 * 10000 : null, 1)}</dd><dt>Statewide rate</dt><dd>${N(stateTot(st.line) / sum(CTY.map(x => x.pop2025)) * 10000, 1)}</dd><dt>Pool (${esc(L.poolName)})</dt><dd>${isN(pl) ? N(pl) : 'not modeled'}</dd><dt>Default value per retained matter</dt><dd>${$$$(L.fee)}</dd><dt>Annual value at 100% share</dt><dd>${$$$(isN(n) ? n * L.fee : null)}</dd></dl><h4 style="font-family:var(--mono);font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--ink-3);margin:12px 0 4px">Angle</h4><p style="font-size:13px">${esc(L.angle)}</p><h4 style="font-family:var(--mono);font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--ink-3);margin:10px 0 4px">Seed keywords</h4><p style="font-size:13px">${L.kw.map(k => `<code>${esc(k)}</code>`).join(' ')}</p><p class="small">Add the city and county modifiers from the metro tabs. Authority: ${esc(L.law)}</p>`; }
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'n', l: 'Matters 12mo', fmt: v => N(v), h: 'Matters, last 12 months', d: 0 }, { k: 'per10k', l: 'per 10k pop', fmt: v => N(v, 1), h: 'Matters per 10,000 residents', d: 1 }, { k: 'pool', l: 'Pool', fmt: v => isN(v) ? N(v) : 'not modeled', h: 'Pool', d: 0 }, { k: 'value', l: 'Value at 100%', fmt: v => $$$(v), h: 'Annual value at 100% share ($, default value per matter)', d: 0 }, { k: 'offices', l: 'Law offices', fmt: v => v ? N(v) : 'none (CBP)', h: 'Law offices (CBP 2023)', d: 0 }, { k: 'per_office', l: 'Matters/office', fmt: (v, r) => r.offices ? N(v, 1) : 'no office', h: 'Matters per law office', d: 1 }, { k: 'esi', l: 'Shock idx', fmt: v => N(v, 0), h: 'Economic Shock Index (percentile)', d: 0 }, { k: 'grade', l: 'Grade', fmt: v => `<span class="grade ${esc(v)}">${esc(v)}</span>`, h: 'Confidence grade' }];
    const rows = () => CTY.map(c => { const L = LINE_META[st.line]; const n = L.cnt(c); return { _id: c.fips, fips: c.fips, name: c.name, n, per10k: isN(n) ? n / c.pop2025 * 10000 : null, pool: L.pool(c), value: isN(n) ? n * L.fee : null, offices: c.rates.lawoffices || 0, per_office: isN(n) && c.rates.lawoffices ? n / c.rates.lawoffices : null, esi: c.esi, grade: c.grade }; });
    const tbl = table($('#lnTable'), { caption: 'Counties for the selected service line', cols, rows: rows(), sort: { k: 'n', dir: -1 }, onRow: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); play(); tbl.setSel(id); }, selected: st.sel });
    $('#lnCsv').onclick = () => exportText(expName('lines', 'texas'), csv(CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => { const o = { fips: c.fips, county: c.name, pop: c.pop2025 }; ids.forEach(id => o[id] = LINE_META[id].cnt(c)); return o; }), [{ l: 'County', k: 'county' }, { l: 'FIPS', k: 'fips' }, { l: 'Population 2025 (Census Vintage 2025)', k: 'pop', d: 0 }].concat(ids.map(id => ({ l: LINE_META[id].name + (id === 'prenup' ? ' (estimated retained matters a year)' : EST_LINES.includes(id) ? ' (estimated filings, last 12 months)' : ' (filings, last 12 months)'), k: id, d: 0 })))));
    // the selected line, county by county, as the table shows it (estimate flagged in the header)
    $('#lnLineCsv').onclick = () => { const L = LINE_META[st.line]; const lab = L.name + (L.est ? ' (estimated)' : ''); exportText(expName('lines_' + st.line, 'texas'), csv(tbl.sorted(), xcols([cols[0], { k: 'fips', l: 'FIPS' }].concat(cols.slice(1).map(c => c.k === 'n' ? Object.assign({}, c, { h: lab + ', ' + (st.line === 'prenup' ? 'retained matters a year' : 'last 12 months') }) : c.k === 'pool' ? Object.assign({}, c, { h: 'Pool: ' + L.poolName }) : c))))); };
    // every ZIP's allocated filings by court line, long format (one row per ZIP and line), as the Thermal Atlas writes its ZIP file
    $('#lnZipCsv').onclick = () => { const K = [['div', 'Divorce'], ['div_k', 'Divorce with children'], ['sapcr', 'Custody (SAPCR)'], ['po', 'Protective orders'], ['mod', 'Modification'], ['enf', 'Enforcement'], ['ivd', 'Title IV-D'], ['priv', 'All private family law']]; const out = []; ZC.slice().sort((a, b) => a.zip.localeCompare(b.zip)).forEach(z => K.forEach(([k, l]) => { if (z.alloc && isN(z.alloc[k])) out.push({ zip: z.zip, city: z.city, county: z.county_name, fips: z.county, metro: z.msa && MSA[z.msa] ? MNAME(MSA[z.msa].title) : '', line: l, key: k, n: z.alloc[k] }); })); exportText(expName('lines_by_zip', 'texas'), csv(out, [{ l: 'ZIP', k: 'zip' }, { l: 'City', k: 'city' }, { l: 'County', k: 'county' }, { l: 'County FIPS', k: 'fips' }, { l: 'Metro', k: 'metro' }, { l: 'Line', k: 'line' }, { l: 'Line key', k: 'key' }, { l: 'Expected filings a year (county filings allocated to the ZIP)', k: 'n', d: 1 }])); };
    cards(); draw();
    this.sync = () => { const f = store.get('sev.county', st.sel); if (CI[f] && f !== st.sel) { st.sel = f; markSel(mapEl, f); play(); tbl.setSel(f); } };
    // goModule('lines', {line, county})
    this.receive = p => { if (!p) return; if (CI[p.county]) { store.set('sev.county', p.county); this.sync(); } if (p.line && LINE_META[p.line] && p.line !== st.line) { st.line = p.line; st.period = null; cards(); draw(); } };
  },
  onShow() { if (this.sync) this.sync(); }
});
