'use strict';
/* Module 06: Service Lines */
// protective orders, last twelve months against calendar 2019, statewide (the angle quotes it)
const LN_PO19 = (() => { try { const a = ST.annual && ST.annual['2019']; const t = stTTM('po'); const v = a && a.f_po ? (t / a.f_po - 1) * 100 : null; return typeof v === 'number' && isFinite(v) ? v : null; } catch (e) { return null; } })();   // null where the data is not loaded (unit tests)
// lc: the name inside a sentence (legal acronyms keep their case); lcs: the short name inside a sentence
const LINE_META = {
  div_k: { name: 'Divorce with children', short: 'Divorce, kids', lc: 'divorce with children', lcs: 'divorce with children', cnt: c => c.lines.div_k.n, pool: c => c.lines.div_k.pool, poolName: 'married couple families with children', seas: 'div_k', cyc: 'ldiv', fee: 9500, kw: ['divorce lawyer', 'divorce attorney', 'child custody lawyer', 'divorce with kids', 'family law attorney', 'how to file for divorce in Texas', 'divorce mediation'], angle: 'Custody and the primary residence right decide the case; lead with conservatorship, the expanded standard possession order (default inside 50 miles since 2021) and child support guidelines (cap $11,700 net since September 2025). Texas terms: conservatorship, possession and access, SAPCR.', law: 'Tex. Fam. Code §§ 6.702 (60 day wait), 153.131 (JMC presumption), 153.3171 (ESPO), 154.125 (guidelines, $11,700 cap).' },
  div_nk: { name: 'Divorce without children', short: 'Divorce, no kids', lc: 'divorce without children', lcs: 'divorce without children', cnt: c => c.lines.div_nk.n, pool: c => c.lines.div_nk.pool, poolName: 'married couples without children at home', seas: 'div', cyc: 'ldiv', fee: 4500, kw: ['uncontested divorce', 'agreed divorce', 'divorce without kids', 'cheap divorce lawyer', 'flat fee divorce', 'divorce papers Texas', 'how long does divorce take in Texas'], angle: 'Half of these are agreed. Flat fee and prove up by affidavit offers convert; the 60 day floor and the property division standard (just and right, not 50/50) are the two facts to state.', law: '§ 7.001 (just and right division), § 3.003 (community presumption), § 6.702.' },
  sapcr: { name: 'Custody and SAPCR', short: 'Custody / SAPCR', lc: 'custody suits (SAPCR)', lcs: 'custody (SAPCR)', cnt: c => c.lines.sapcr.n, pool: c => c.lines.sapcr.pool, poolName: 'cohabiting couples with children plus single parent families', seas: 'sapcr', cyc: 'lsapcr', fee: 6500, kw: ['child custody attorney', 'custody lawyer', 'fathers rights lawyer', 'unmarried parents custody Texas', 'SAPCR', 'paternity lawyer', 'custody agreement Texas'], angle: 'Unmarried parents. Rights attach through an acknowledgment of paternity or adjudication, not the birth certificate; the geographic restriction and the primary residence designation are what parents search for.', law: 'ch. 153, ch. 160 (paternity), § 153.009 (child interview at 12).' },
  mod: { name: 'Modification', short: 'Modification', lc: 'modifications', lcs: 'modification', cnt: c => c.lines.mod.n, pool: c => c.lines.mod.pool, poolName: 'single parent households (existing orders)', seas: 'mod', cyc: 'lmod', fee: 4000, kw: ['modify child support Texas', 'custody modification lawyer', 'change custody order', 'reduce child support after job loss', 'modification attorney', 'relocation custody Texas'], angle: 'The counter cyclical line. Income drops trigger support modifications (material change, or 3 years and 20% or $100), and the 2025 rule that three possession contempt findings are a material change opens custody modifications. Lead with job loss language when the county shock index is high.', law: '§ 156.101, § 156.401, § 156.107 (new 2025).' },
  enf: { name: 'Enforcement', short: 'Enforcement', lc: 'enforcement', lcs: 'enforcement', cnt: c => c.lines.enf.n, pool: c => c.lines.enf.pool, poolName: 'single parent households (existing orders)', seas: 'enf', cyc: 'lenf', fee: 3500, kw: ['child support enforcement lawyer', 'contempt of court child support', 'enforce visitation order', 'ex not following custody order', 'back child support Texas', 'possession enforcement'], angle: 'In the 2022 on panel, enforcement filings rise three to six months after a claims surge (the Cycle chart, 2022 on). Each missed support payment becomes a judgment carrying 6% simple interest, income withholding can continue until the arrears are paid, and the court can confirm the arrears in a money judgment within ten years after the child turns 18 or the order ends. Support and possession are independent obligations (the § 105.006(e) warning), which is the fact parents get wrong.', law: 'ch. 157 (§ 157.005, § 157.166, § 157.261, § 157.265), § 105.006(e).' },
  po: { name: 'Protective orders', short: 'Protective orders', lc: 'protective orders', lcs: 'protective order', cnt: c => c.lines.po.n, pool: c => c.lines.po.pool, poolName: 'DFPS investigations with family violence indicated, FY2025', seas: 'po', cyc: 'lpo', fee: 3000, kw: ['protective order lawyer', 'restraining order Texas', 'family violence attorney', 'emergency protective order', 'domestic violence lawyer', 'defend protective order'], angle: (LN_PO19 != null ? `${LN_PO19 >= 0 ? 'Up' : 'Down'} ${Math.round(Math.abs(LN_PO19))}% statewide in the last twelve months against calendar 2019. ` : '') + 'Since 2023 the applicant proves violence occurred, not that it will recur; since September 2025 an order tied to a pending divorce or SAPCR runs until two years after the final decree. Two audiences: applicants and respondents. A TRO is not a protective order.', law: 'ch. 85, § 85.025, SB 1120 (2025), § 81.012.' },
  ivd: { name: 'Child support and paternity (IV-D)', short: 'Support / paternity', lc: 'child support and paternity (IV-D)', lcs: 'support or paternity', cnt: c => c.lines.ivd.n, pool: c => c.lines.ivd.pool, poolName: 'births to unmarried mothers in the past year', seas: 'ivd', cyc: null, fee: 2500, kw: ['child support lawyer', 'paternity test Texas', 'establish paternity', 'child support calculator Texas', 'attorney general child support hearing', 'IV-D court lawyer'], angle: 'Most IV-D cases are handled by the Attorney General; private demand is the parent who wants representation at the IV-D docket or a deviation from guidelines. Volume fell sharply after 2019 as OAG reporting changed; treat counts as a floor.', law: 'ch. 154, ch. 160, ch. 231 (Title IV-D agency).' },
  adopt: { name: 'Adoption', short: 'Adoption', lc: 'adoption', lcs: 'adoption', cnt: c => c.lines.adopt.n, pool: c => null, poolName: 'stepparent, kinship and private adoptions', seas: null, cyc: null, fee: 4000, kw: ['adoption attorney', 'stepparent adoption Texas', 'kinship adoption', 'terminate parental rights', 'adoption lawyer near me', 'adult adoption Texas'], angle: 'Stepparent adoption follows remarriage; the remarried share in module 04 is the audience. Termination first, child 12 or older consents, six month residence.', law: 'ch. 162, § 161.001.' },
  cps: { name: 'CPS and termination defense', short: 'CPS defense', lc: 'CPS and termination defense', lcs: 'CPS defense', cnt: c => c.lines.cps.n, pool: c => c.lines.cps.pool, poolName: 'CPS removals FY2025', seas: null, cyc: null, fee: 5000, kw: ['CPS lawyer', 'CPS investigation attorney', 'DFPS removal lawyer', 'terminate parental rights defense', 'child protective services attorney Texas', 'family preservation'], angle: 'Removals halved statewide after 2021 but the 14 day adversary hearing and the one year dismissal clock make speed the pitch. Ground (O) was repealed in 2025; anonymous reports are no longer accepted.', law: '§ 262.201, § 263.401, HB 116 (2025).' },
  prenup: { name: 'Premarital agreements', short: 'Prenups', lc: 'premarital agreements', lcs: 'premarital agreement', est: true, cnt: c => c.lines.prenup.est, pool: c => c.lines.prenup.pool, poolName: 'people who married in the past year (inflow)', seas: null, cyc: null, fee: 2500, kw: ['prenup lawyer', 'prenuptial agreement Texas', 'postnuptial agreement', 'premarital agreement attorney', 'how much does a prenup cost', 'partition agreement'], angle: 'Texas prenups are among the most enforceable anywhere (§ 4.006 exclusive defenses). Estimate assumes 6% of new marriages retain counsel; the affluent ZIPs in the metro tabs carry most of it.', law: 'ch. 4, § 4.006.' },
  high: { name: 'Divorce over $150,000 (high asset)', short: 'High asset', lc: 'high asset divorce (households over $150,000)', lcs: 'high asset divorce', est: true, cnt: c => c.lines.high.n, pool: c => c.lines.high.pool, poolName: 'married adults in households over $150,000', seas: 'div', cyc: 'ldiv', fee: 35000, kw: ['high net worth divorce attorney', 'business owner divorce Texas', 'executive divorce lawyer', 'divorce stock options', 'separate property tracing', 'complex property division'], angle: 'Filings scaled by the county share of married adults in households over $150,000 and the 0.59 relative hazard of that income band. Seven figure estates (business interests, stock plans, multiple properties) are roughly a fifth of this pool. Reimbursement claims run on the unified unjust enrichment standard since 2023; tracing and the clear and convincing burden for separate property are the technical hooks.', law: '§ 3.001, § 3.003, ch. 3 subch. E (HB 1547, 2023).' },
  mil: { name: 'Military divorce', short: 'Military', lc: 'military divorce', lcs: 'military divorce', est: true, cnt: c => c.lines.mil.n, pool: c => c.lines.mil.pool, poolName: 'active duty service members', seas: 'div', cyc: null, fee: 8000, kw: ['military divorce lawyer', 'Fort Hood divorce attorney', 'Fort Bliss divorce lawyer', 'military custody deployment', 'USFSPA retirement division', 'SCRA divorce'], angle: 'Filings scaled by active duty exposure and the 1.46× hazard. Bell and Coryell (Fort Hood, named Fort Cavazos from 2023 to June 2025), El Paso (Fort Bliss) and Bexar (JBSA) hold the pool. Residency counts military stationing (§§ 6.303 to 6.304); the Servicemembers Civil Relief Act stays proceedings.', law: '§§ 6.303 to 6.304, 10 U.S.C. § 1408 (USFSPA).' },
  gray: { name: 'Gray divorce (50 and over)', short: 'Gray divorce', lc: 'gray divorce (50 and over)', lcs: 'gray divorce', est: true, cnt: c => c.lines.gray.n, pool: c => c.lines.gray.pool, poolName: 'married adults aged 55 and over', seas: 'div', cyc: 'ldiv', fee: 12000, kw: ['divorce after 50', 'gray divorce attorney', 'divorce retirement accounts Texas', 'QDRO lawyer', 'divorce social security', 'late life divorce'], angle: 'Filings scaled by the age specific hazard (ages 50 to 64 run 13 per 1,000, 65 and over 6). Retirement division, QDROs and spousal maintenance (10 year marriages, capped at the lesser of $5,000 or 20% of gross) are the topics.', law: 'ch. 8 (§ 8.051, § 8.055), § 7.001.' }
};
/* build 2: how each line is bought. kind: 'base' lines are additive (every matter once); high asset, military and gray divorce are
   'lens' lines inside the divorce counts (they rank ZIPs and shape creative, and are never added to the divorce lines). fit: channel fit
   0 to 3 for the Campaign Desk's nine platforms; dayparts: the template (urgent, considered, business); mobile: the expected mobile
   share of clicks. Fit, dayparts and mobile shares are judgment (grade C) until the account's own device and hour reports replace them.
   intent, hooks, negatives and triggers are planning notes: no copy here leaves the atlas without LINT. */
const LINE_EXT = {
  div_k: { kind: 'base', intent: 'A considered decision over weeks: parents research conservatorship, possession and support before the first call.', fit: { google: 3, lsa: 3, dg: 1, meta: 2, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 1, tiktok: 1 }, dayparts: 'considered', mobile: 62,
    hooks: ['Conservatorship and the right to designate the primary residence, in Texas terms', 'The expanded standard possession order is the default within 50 miles (§ 153.3171)', 'Child support guidelines and the $11,700 net resources cap (§ 154.125)', 'The consultation fee and terms exactly as the firm profile states them (Rule 7.02)'],
    negs: ['divorce records', 'divorce decree copy', 'custody forms', 'parenting plan template'],
    triggers: ['January: filings climb from the December trough', 'February and March: tax refunds fund retainers', 'By April 1: the summer possession notice (§ 153.312(b))', 'August: school start brings primary residence and relocation questions'] },
  div_nk: { kind: 'base', intent: 'Price and speed: agreed divorces compare flat fees and timelines.', fit: { google: 3, lsa: 3, dg: 1, meta: 2, microsoft: 2, linkedin: 0, yelp: 2, nextdoor: 1, tiktok: 1 }, dayparts: 'considered', mobile: 64,
    hooks: ['The 60 day waiting period from filing, stated plainly (§ 6.702)', 'Just and right division, not automatically half and half (§ 7.001)', 'A flat fee only as the firm profile states it, with what the fee covers', 'The agreed decree and the prove up, step by step'],
    negs: ['divorce records', 'divorce decree copy', 'marriage license', 'name change only'],
    triggers: ['January: filings climb from the December trough', 'February and March: tax refunds fund retainers; flat fee and payment terms creative'] },
  sapcr: { kind: 'base', intent: 'Unmarried parents establishing rights: fathers and mothers search custody and paternity.', fit: { google: 3, lsa: 3, dg: 1, meta: 2, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 0, tiktok: 1 }, dayparts: 'considered', mobile: 70,
    hooks: ['Rights attach through an acknowledgment of paternity or an adjudication, not the birth certificate', 'No preference for either parent by gender (§ 153.003)', 'Joint managing conservatorship does not mean equal time (§ 153.135)', 'A judge interviews a child 12 or older on request; the preference never controls (§ 153.009)'],
    negs: ['paternity test kit', 'dna test cost', 'birth certificate copy', 'child support payment portal'],
    triggers: ['By April 1: the summer possession notice (§ 153.312(b))', 'Thanksgiving and Christmas possession exchanges (§ 153.314)', 'August: school start, primary residence and relocation'] },
  mod: { kind: 'base', intent: 'Orders that no longer fit: a job loss, a move, a child\'s preference.', fit: { google: 3, lsa: 2, dg: 1, meta: 2, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 1, tiktok: 0 }, dayparts: 'considered', mobile: 66,
    hooks: ['Support modification: a material change, or 3 years and a 20% or $100 difference (§ 156.401)', 'Three possession contempt findings are a material change since 2025 (§ 156.107)', 'Job loss language where the county shock index is high', 'Relocation and geographic restriction questions before the school year'],
    negs: ['oag child support login', 'child support payment portal', 'pay child support online'],
    triggers: ['WARN notices and claims jumps: orders come under strain 3 to 12 months later (Live Desk)', 'August: school start', 'May to August near the installations: military moving season'] },
  enf: { kind: 'base', intent: 'A missed payment or a denied weekend: urgent to the parent, handled in business hours.', fit: { google: 3, lsa: 2, dg: 0, meta: 1, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 0, tiktok: 0 }, dayparts: 'business', mobile: 68,
    hooks: ['Support and possession are independent obligations (§ 105.006(e))', 'Each missed payment becomes a judgment carrying 6% simple interest', 'Contempt, income withholding and license suspension in plain terms (ch. 157)', 'Possession enforcement after the holiday and summer exchanges'],
    negs: ['oag child support login', 'child support payment portal', 'pay child support online'],
    triggers: ['After the summer, Thanksgiving and Christmas exchanges (§ 153.312, § 153.314)', 'Three to six months after a claims surge (the Cycle chart, 2022 on)'] },
  po: { kind: 'base', intent: 'An urgent safety need with two audiences: applicants and respondents.', fit: { google: 3, lsa: 3, dg: 0, meta: 0, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 0, tiktok: 0 }, dayparts: 'urgent', mobile: 80,
    hooks: ['Applicants pay no filing or service fee (§ 81.002); say so on the applicant page', 'Respondent defense: the hearing comes within 14 days of filing (§ 84.001)', 'The finding is that family violence occurred (§ 85.001, since 2023)', 'A protective order prevails over a conflicting divorce or custody order (§ 81.012)', 'Never imply the viewer is a victim or an abuser (personal attributes policies)'],
    negs: ['protective order records', 'restraining order lookup', 'protective order form'],
    triggers: ['Around the clock, every day: the urgent template never bids below 0', 'The statewide protective order series sets the heavy months'] },
  ivd: { kind: 'base', intent: 'A parent facing the Attorney General\'s IV-D docket who wants a lawyer of their own.', fit: { google: 3, lsa: 2, dg: 0, meta: 1, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 0, tiktok: 0 }, dayparts: 'business', mobile: 72,
    hooks: ['The Attorney General is the Title IV-D agency and its lawyers represent the state, not either parent (ch. 231)', 'Private counsel at the IV-D docket, or for a deviation from the guidelines', 'Paternity: genetic testing and acknowledgments explained (ch. 160)'],
    negs: ['oag login', 'child support payment portal', 'child support office hours', 'case status'],
    triggers: ['Weekday business hours, when the IV-D dockets sit', 'February and March: tax refund intercepts bring arrears questions'] },
  adopt: { kind: 'base', intent: 'Planned and personal, often a stepparent after a remarriage.', fit: { google: 3, lsa: 2, dg: 2, meta: 3, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 1, tiktok: 1 }, dayparts: 'business', mobile: 56,
    hooks: ['Stepparent adoption follows remarriage', 'Termination comes first; a child 12 or older consents, waivable for best interest; six months of residence, waivable', 'Kinship adoption for grandparents and relatives'],
    negs: ['adoption agency', 'pet adoption', 'adopt a pet', 'adoption records search', 'foster care jobs'],
    triggers: ['No monthly series in the data: spend follows the county counts', 'Remarried share sets the stepparent angle by ZIP'] },
  cps: { kind: 'base', intent: 'A removal or an investigation: days matter.', fit: { google: 3, lsa: 2, dg: 0, meta: 1, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 0, tiktok: 0 }, dayparts: 'urgent', mobile: 82,
    hooks: ['The adversary hearing comes within 14 days of removal (§ 262.201)', 'Automatic dismissal after one year of DFPS temporary conservatorship, with one extension of up to 180 days (§ 263.401)', 'Indigent parents receive appointed counsel (§ 107.013): the paying market is the parent who is not indigent or wants a lawyer of their own', 'Ground (O) was repealed in 2025'],
    negs: ['cps jobs', 'cps caseworker', 'report child abuse', 'cps hotline'],
    triggers: ['Around the clock: the urgent template', 'No monthly series in the data: spend follows the county removal counts'] },
  prenup: { kind: 'base', intent: 'Planned months ahead of a wedding; second marriages and business owners.', fit: { google: 3, lsa: 1, dg: 2, meta: 3, microsoft: 2, linkedin: 0, yelp: 1, nextdoor: 0, tiktok: 2 }, dayparts: 'considered', mobile: 58,
    hooks: ['Texas premarital agreements are enforced unless a § 4.006 defense applies', 'Partition and postnuptial agreements for married couples (ch. 4)', 'Business owners and second marriages'],
    negs: ['prenup template', 'prenup form', 'celebrity prenup'],
    triggers: ['No monthly series in the data: the marriage inflow sets the ZIPs'] },
  high: { kind: 'lens', of: 'div', intent: 'Complex property: business interests, stock plans, separate property tracing.', fit: { google: 3, lsa: 2, dg: 1, meta: 1, microsoft: 3, linkedin: 0, yelp: 0, nextdoor: 0, tiktok: 0 }, dayparts: 'considered', mobile: 50,
    hooks: ['Separate property is proved by clear and convincing evidence (§ 3.003)', 'Reimbursement claims run on the 2023 unjust enrichment standard', 'Just and right division of business interests and stock plans (§ 7.001)'],
    negs: ['cheap divorce', 'flat fee divorce', 'uncontested divorce', 'divorce papers'],
    triggers: ['Follows the divorce season: the January rise and the March peak'] },
  mil: { kind: 'lens', of: 'div', intent: 'Residency, deployment and retirement division; the installations hold the pool.', fit: { google: 3, lsa: 2, dg: 1, meta: 2, microsoft: 1, linkedin: 0, yelp: 0, nextdoor: 0, tiktok: 1 }, dayparts: 'considered', mobile: 72,
    hooks: ['Texas residency counts military stationing (§§ 6.303 to 6.304)', 'The Servicemembers Civil Relief Act can stay proceedings', 'Retirement division under the USFSPA (10 U.S.C. § 1408)'],
    negs: ['military jobs', 'enlist', 'va benefits', 'military records'],
    triggers: ['May to August: military moving season (Live Desk)', 'Near Fort Hood, Fort Bliss and Joint Base San Antonio'] },
  gray: { kind: 'lens', of: 'div', intent: 'Long marriages: retirement accounts, maintenance and the house.', fit: { google: 3, lsa: 2, dg: 1, meta: 3, microsoft: 3, linkedin: 0, yelp: 0, nextdoor: 1, tiktok: 0 }, dayparts: 'considered', mobile: 45,
    hooks: ['Retirement division and QDROs', 'Spousal maintenance after a 10 year marriage, capped at the lesser of $5,000 a month or 20% of average monthly gross income (§ 8.055)', 'Phone first: call assets on every ad'],
    negs: ['social security office', 'retirement calculator', 'medicare'],
    triggers: ['Follows the divorce season: the January rise and the March peak'] }
};
Object.keys(LINE_EXT).forEach(k => Object.assign(LINE_META[k], LINE_EXT[k], { desk: k }));
/* the ZIP view's map layers for the selected line: one value per ZIP cell (FLM.compute) */
const LN_LAYERS = {
  pri: { l: 'Campaign priority (percentile)', g: 'C', ramp: 'ember', q: false, v: c => c.pri, f: v => N(v, 0), note: 'Contribution per relative click cost, discounted by the competition for this line; percentile across the metro\'s ZIPs.' },
  matters: { l: 'Matters a year', g: 'B', ramp: 'ember', v: c => c.matters, f: v => N(v, 1), note: 'Court filings allocated to the ZIP where the courts report the line; the county count spread by composition for the rest.' },
  contrib: { l: 'Contribution ($ a year, at 100% share)', g: 'C', ramp: 'ember', v: c => c.contrib, f: v => $$$(v), note: 'Fee paying matters times the payer weight times the collected value per retained matter, plus the pipeline credit.' },
  press: { l: 'Competition (percentile)', g: 'C', ramp: 'slate', q: false, v: c => c.presspct, f: v => N(v, 0), note: 'Law offices per 1,000 married within the radius, raised where Competitor Watch logs live rival ads for the line in the county.' },
  bid: { l: 'Starting bid modifier', g: 'C', cat: 'bid', note: 'Six priority bands: +45 at the 90th percentile and up, then +30, +15, 0, minus 20, minus 40.' },
  quiet: { l: 'Quiet auction (yes or no)', g: 'C', cat: 'quiet', note: 'Contribution in the top 40% of the metro\'s ZIPs with competition in the bottom 45%.' },
  levers: { l: 'Dominant audience lever', g: 'C', cat: 'lev', note: 'The lever whose metro percentile is highest in the ZIP. It changes the creative and the call to action, never who is reached.' }
};
const LN_LEV_C = { pay: 'var(--s4)', premium: 'var(--s5)', gray: 'var(--s6)', movers: 'var(--s7)', renters: 'var(--s8)', kids: 'var(--s1)', unmarried: 'var(--s3)', shock: 'var(--s2)', mil: 'var(--ink-2)', gap: 'var(--rp-sage-3)' };
const LN_BIDC = { 45: 'var(--rp-forest-7)', 30: 'var(--rp-forest-6)', 15: 'var(--rp-forest-4)', 0: 'var(--rp-forest-2)', '-20': 'var(--rp-slate-3)', '-40': 'var(--rp-slate-5)' };
registerModule({
  key: 'lines', num: '06', title: 'Service Lines', desc: 'Thirteen family law service lines resolved to the county and the ZIP: counts, pools, economics, seasons, dayparts, competition and bids',
  mount(root) {
    const SVL = store.get('sev.lines', null) || {};
    const metroOK = c => !!(MSA[c] && GEO.metros && GEO.metros[c]);
    const st = { line: LINE_META[SVL.line] ? SVL.line : 'div_k', sel: store.get('sev.county', '48201'), period: null, view: SVL.view === 'county' ? 'county' : 'zip', metro: metroOK(SVL.metro) ? SVL.metro : metroOK(store.get('sev.metro', '')) ? store.get('sev.metro', '') : '19100', layer: LN_LAYERS[SVL.layer] ? SVL.layer : 'pri', cty: '', n: clamp(Math.round(+SVL.n) || 40, 5, 300), zip: null, month: -1, obs: false, chart: Array.isArray(SVL.chart) ? SVL.chart.filter(k => LINE_META[k]) : ['div_k', 'div_nk', 'sapcr', 'po', 'mod'] };
    if (!CI[st.sel]) st.sel = '48201';
    const saveSt = () => store.set('sev.lines', { line: st.line, view: st.view, metro: st.metro, layer: st.layer, n: st.n, chart: st.chart });
    const ids = Object.keys(LINE_META);
    const stateTot = id => sum(CTY.map(c => LINE_META[id].cnt(c) || 0));
    const L = () => LINE_META[st.line];
    const C = () => FLM.compute(st.metro);
    const mName = () => MNAME(MSA[st.metro].title);
    const metroOpts = Object.keys(MSA).filter(metroOK).sort((a, b) => MSA[b].pop2025 - MSA[a].pop2025).map(k => [k, MNAME(MSA[k].title)]);
    const lensTag = id => LINE_META[id].kind === 'lens' ? ' <span class="pill ln-lens" title="A lens inside the divorce counts: it ranks ZIPs and shapes creative, and is never added to the divorce lines">inside divorce</span>' : '';
    const gradeB = g => g ? (typeof gradeChip === 'function' ? gradeChip(g) : `<span class="grade ${g}" title="Confidence grade ${g}">${g}</span>`) : '';
    const lnM = v => isN(v) && Math.abs(v) >= 1e6 ? '$' + K(v) : $$$(v);   // money in a tile: $243.34M, not nine digits
    root.innerHTML = mastHTML({ eyebrow: 'Module 06 · Service Lines · thirteen lines, resolved to the county and the ZIP', title: 'Service Lines', dek: `A family law firm does not sell "family law"; it sells thirteen distinct things to thirteen distinct audiences with different seasons, prices, channels and hours. Nine lines come straight from the court filing categories; four (prenups, high asset, military and gray divorce) are estimated by scaling filings with the composition of the married population. The ZIP view resolves every line to the ZIPs of a metro: matters a year, the fee paying share, a payer weight from household income, the collected value per matter, a pipeline credit, competition, cost, a priority percentile and a starting bid. The county view keeps the statewide map, the season and the cycle.`, facts: [[N(stateTot('div_k')), 'divorces with children, statewide, last 12 months'], [N(stateTot('sapcr')), 'custody suits without a divorce'], [N(stateTot('mod') + stateTot('enf')), 'modifications and enforcements'], [N(stateTot('po')), 'protective orders']] }) +
      toolbarHTML('Service Lines', 'Pick a line; the maps, tables, economics and playbook follow', [{ id: 'lnLong', label: '↓ Line × ZIP CSV', title: 'One row per ZIP per line in the metro' }, { id: 'lnWide', label: '↓ Priority matrix' }, { id: 'lnG', label: '↓ Google locations', title: 'Location bid modifiers for the selected line (Ads Editor)' }, { id: 'lnM', label: '↓ Meta ZIPs', title: 'Ad set ZIP keys for the selected line' }, { id: 'lnCal', label: '↓ Flight calendar' }, { id: 'lnHour', label: '↓ Hourly plan', title: 'Hour by hour bid adjustments for the next 7 days' }, { id: 'lnAsm', label: '↓ Assumptions JSON' }, { id: 'lnCsv', label: '↓ Lines by county CSV' }, { id: 'lnLineCsv', label: '↓ This line by county CSV' }, { id: 'lnZipCsv', label: '↓ ZIPs by line CSV', title: 'Every ZIP\'s allocated court filings, statewide' }, { id: 'lnDesk', label: 'Build in the Campaign Desk ↗', primary: true }]) +
      `<p class="small" id="lnMsg" role="status" aria-live="polite" style="margin:-8px 0 12px"></p>
      ${callout('note', 'Read this first: what a service line is here, and what the numbers are', `<p>A <b>line</b> is a campaign the firm would actually build: its own keywords, creative, landing page, budget, hours and season. <b>Matters a year</b> come from the courts: county filings for the last twelve months, allocated to ZIPs by married adults times the modeled hazard where the courts report the line (grades A and B), and the county count spread by a composition weight where they do not (adoption, CPS, prenups, and the high asset, military and gray lenses, grades C and D). <b>Economics</b> are stated assumptions in one shared store, graded D until the Accounts module's actuals replace them: the value per retained matter, the share collected, the click to lead, show and retained rates, the share of protective order, IV-D and CPS matters that pay a private fee. Edit them below; Paid Acquisition and the Campaign Desk read the same store. <b>Competition</b> is law office density, which counts every kind of law office, raised where Competitor Watch logs live rival ads. <b>Lenses</b> (high asset, military, gray divorce) sit inside the divorce counts: they rank ZIPs and shape creative, and the portfolio never adds them. This module does not price keywords, see competitor spend or use client data.</p>`)}
      <div class="tiles" id="lnKpis"></div>
      <div id="lnCards" class="lncards"></div>
      <div class="ln-viewbar">${segHTML('lnView', [['zip', 'ZIP view, by metro'], ['county', 'County view, statewide']], st.view)}</div>
      <div id="lnZipView">
        <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Metro', sel('lnMetro', metroOpts, st.metro))}${ctl('Map layer', sel('lnLayer', Object.keys(LN_LAYERS).map(k => [k, LN_LAYERS[k].l]), st.layer))}${ctl('County', '<select id="lnCty"></select>')}${ctl('ZIPs in the buy', `<input type="number" id="lnN" value="${st.n}" min="5" max="300" step="1" inputmode="numeric" style="width:80px">`)}<div id="lnFindBox" class="ln-find">${ctl('Find a ZIP, city or county', '<input type="search" id="lnFind" placeholder="75201, Plano or Collin" autocomplete="off" aria-describedby="lnFindMsg">')}</div><span class="small" id="lnFindMsg" role="status" aria-live="polite"></span></div>
          <div class="split"><div><div class="mapwrap" id="lnZMap"></div><div class="ln-leg" id="lnZLeg"></div></div><div id="lnBrief" class="ln-brief"></div></div></div>
        <div class="grid2"><div class="panel"><h3 id="lnTblH">Ranked ZIPs</h3><div class="sub">Priority first. A row opens the ZIP card; the top ZIPs in the buy are what the exports and the desk receive.</div><div id="lnZTbl"></div></div><div class="panel"><h3 id="lnZCardH">ZIP card</h3><div class="sub" id="lnZCardSub">Click a ZIP on the map or a row in the ranking.</div><div id="lnZCard"></div></div></div>
      </div>
      <div id="lnCtyView">
        <div class="panel" style="margin:0 0 14px"><div class="split"><div><h3 id="lnTitle"></h3><div class="sub" id="lnSub"></div><div class="mapwrap" id="lnMap"></div></div><div id="lnPlay"></div></div></div>
        <div class="grid2"><div class="panel"><h3>Season</h3><div class="sub" id="lnSeasSub"></div><div id="lnSeas"></div></div><div class="panel"><h3>Cycle</h3><div class="sub">How this line responds to a doubling of unemployment claims, by lag, from the county panel.</div><div id="lnCycSeg"></div><div class="chart" id="lnCyc"></div><div class="small" id="lnCycNote"></div></div></div>
        <div class="panel"><h3>Counties</h3><div id="lnTable"></div></div>
      </div>
      <div class="panel"><h3>The year, line by line</h3><div class="sub">Season indices with mean 100 from the statewide monthly court series (2022 to 2025 average = 100). Lines the courts do not report by month show flat, which means the data does not know their season, not that they have none.</div><div id="lnHeat"></div></div>
      <div class="grid2"><div class="panel"><h3>Unit economics: <span id="lnEName"></span></h3><div class="sub">Edit the line's assumptions; every module that reads the shared store recomputes. Each field says where its value comes from: the default (grade D), the Accounts actuals you applied (grade B) or your input.</div><div id="lnEcon"></div></div>
        <div class="panel"><h3>Dayparts and devices: <span id="lnDName"></span></h3><div class="sub">Starting bid adjustments by day and hour block, and the mobile share to expect. Four templates, grade C, until the account's hour of day report replaces them.</div><div id="lnDay"></div></div></div>
      <div class="panel"><h3>Portfolio: where a month of media should go</h3><div class="sub">The ten additive lines compete for one budget in the metro (and county) chosen above. Each line's weight is its contribution in scope, times its season index for the month, times the value it returns per media dollar, raised to the concentration power: 1 spends in proportion to value, below 1 spreads the buy, above 1 concentrates it. The lenses are never added.</div><div class="controls">${ctl('Monthly media $', '<input type="number" id="lnBud" min="0" step="500" inputmode="decimal" style="width:110px">')}${ctl('Month', sel('lnMo', [['-1', 'Annual average']].concat(MOL.map((m, i) => [String(i), m])), '-1'))}${ctl('Concentration', '<input type="range" id="lnAlpha" min="0.5" max="2.5" step="0.1" aria-describedby="lnAlphaV">')}<span class="small" id="lnAlphaV"></span>${ctl('Account average CPC $', '<input type="number" id="lnCpc" min="0" step="0.05" inputmode="decimal" style="width:90px">')}<button type="button" class="btn sm" id="lnReset">Reset every assumption</button></div><div id="lnPort"></div><h4 class="ln-h4">Twelve months of suggested media by line</h4><div class="chart" id="lnPortChart"></div><p class="small" id="lnPortN"></p></div>
      <div class="grid2"><div class="panel"><h3>Audience and creative levers</h3><div class="sub">Ten levers scored for every ZIP in the metro as percentiles within the metro. A lever changes the creative, the call to action or the platform mix; it never changes who is allowed to be reached.</div><div id="lnLev"></div></div>
        <div class="panel"><h3>Competition by line</h3><div class="sub">Contested ZIPs (contribution and competition both at the 60th percentile or above), quiet ZIPs and the live rival ads logged in Competitor Watch for the metro's counties.</div><div id="lnPress"></div></div></div>
      <div class="panel"><h3>How the model is built</h3><ol class="ln-meth" id="lnMeth"></ol></div>
      <div class="grid2"><div class="panel"><h3>Judgment calls</h3><div id="lnJudg"></div></div><div class="panel"><h3>What this module does not use</h3><div id="lnNot"></div></div></div>
      ${srcFoot([['Sources', `Texas Office of Court Administration court activity, ${esc(ttmSpan())} (calendar 2025 for counties without monthly reports), allocated to ZIPs; ACS 2020 to 2024 five year estimates for ZIPs and counties; the PUMS composition model for the estimated lines and the $35,000 to $60,000 income band; ZIP Business Patterns 2023 law offices; DFPS Data Book FY2025; the statewide monthly series for the seasons; the Campaign Desk platform benchmarks (WordStream and LocaliQ legal medians, grades C and D) for the cost per lead.`], ['Judgment calls', 'Ability to pay is weighted, not excluded; protective order applicants pay no filing or service fee (§ 81.002) and prosecutors can apply (§ 82.002), so only the respondent share pays; indigent parents in DFPS suits receive appointed counsel (§ 107.013); IV-D is the Attorney General\'s docket (ch. 231); a contingent fee is never offered or advertised in a family matter. The four daypart templates are grade C.'], ['Caveats', 'Title IV-D counts are floors (Attorney General reporting changed after 2019); law office counts include every kind of law office; a county whose clerk reported nothing for months gives its ZIPs near zero matters; ZIP filings are an allocation, not counts.']])}`;
    const R = s => $(s, root);
    /* ---------- line cards ---------- */
    const EST_LINES = ['prenup', 'high', 'mil', 'gray'];
    function cards() {
      const card = id => { const M = LINE_META[id]; const tot = stateTot(id); return `<div class="line ${st.line === id ? 'on' : ''}" data-id="${id}" role="button" tabindex="0" data-kbd aria-pressed="${st.line === id}"><div class="t">${esc(M.name)}${M.kind === 'lens' ? ' <span class="ln-lensmark">inside divorce</span>' : ''}</div><div class="v">${N(tot)}</div><div class="s">${id === 'prenup' ? 'estimated retained matters a year' : ['high', 'mil', 'gray'].includes(id) ? 'estimated filings, last 12 months' : 'filings, last 12 months'} · pool: ${esc(M.poolName)}</div></div>`; };
      const court = ids.filter(id => !EST_LINES.includes(id)), est = ids.filter(id => EST_LINES.includes(id));
      R('#lnCards').innerHTML = `<p class="small" style="margin:0 0 4px">Statewide totals add each county's latest twelve months: ${esc(ttmSpan())} for the ${CTY.filter(c => c.filings.series).length} counties with monthly clerk reports, calendar 2025 for the rest.</p><h2 class="minihd" id="lnCourtH">Court counts</h2><div class="linebox ln-court" role="group" aria-labelledby="lnCourtH">${court.map(card).join('')}</div>${est.length ? `<h2 class="minihd" id="lnEstH">Estimated from the married population and the hazard model</h2><div class="linebox ln-est" role="group" aria-labelledby="lnEstH">${est.map(card).join('')}</div>` : ''}`;
      $$('#lnCards .line', root).forEach(d => d.onclick = () => { const keep = document.activeElement === d; setLine(d.dataset.id); if (keep) { const n = R(`#lnCards .line[data-id="${st.line}"]`); if (n) n.focus({ preventScroll: true }); } });
    }
    function setLine(id) { if (!LINE_META[id]) return; st.line = id; st.period = null; saveSt(); cards(); renderLine(); }
    /* ---------- the county view (statewide) ---------- */
    const mapEl = R('#lnMap');
    function draw() {
      const M = L(); const v = c => { const n = M.cnt(c); return isN(n) ? n / c.pop2025 * 10000 : null; };
      const lay = { l: M.name + ' per 10,000 residents', ramp: 'ember', v, f: x => N(x, 1) }; const sc = layerScale(lay, CTY);
      R('#lnTitle').textContent = M.name; R('#lnSub').textContent = 'Per 10,000 residents, last twelve months. Hover for counts and pools.';
      drawMap(mapEl, { W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => v(CI[id]), color: sc.color, label: id => { const c = CI[id]; return `<b>${esc(c.name)} County</b><div class="row"><span>${esc(M.name)}</span><span>${N(M.cnt(c))}</span></div><div class="row"><span>per 10,000</span><span>${N(v(c), 1)}</span></div><div class="row"><span>Pool: ${esc(M.poolName)}</span><span>${isN(M.pool(c)) ? N(M.pool(c)) : 'not modeled'}</span></div>`; }, onSelect: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); play(); tbl.setSel(id); }, selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: lay.l }, sc.legend) });
      if (M.seas && ST.seas[M.seas]) { seasBlock(R('#lnSeas'), ST.seas[M.seas], 'ember'); const s = ST.seas[M.seas]; const proxy = M.seas !== st.line; R('#lnSeasSub').textContent = proxy ? `The courts report no separate monthly count for ${M.lc}, so this is the statewide monthly index for all divorce filings, used as the proxy (2022 to 2025 average = 100). Peak ${MOL[s.indexOf(Math.max(...s))]}, trough ${MOL[s.indexOf(Math.min(...s))]}.` : `Statewide monthly index for ${M.lc} (2022 to 2025 average = 100). Peak ${MOL[s.indexOf(Math.max(...s))]}, trough ${MOL[s.indexOf(Math.min(...s))]}.`; } else { R('#lnSeas').innerHTML = '<div class="small">No monthly court series for this line; use the divorce season as the proxy.</div>'; R('#lnSeasSub').textContent = ''; }
      cycle(); tbl.setRows(rows()); play();
    }
    function cycle() {
      const M = L(); const post = M.cyc && D.panel[M.cyc + '|claims_0_12|post2022']; const per = post ? (st.period || (st.line === 'enf' ? 'post' : 'all')) : 'all';
      R('#lnCycSeg').innerHTML = post ? `<div class="seg" role="group" aria-label="Panel period" style="margin:0 0 8px"><button type="button" data-v="all" aria-pressed="${per === 'all'}">2019 to 2026</button><button type="button" data-v="post" aria-pressed="${per === 'post'}">2022 on</button></div>` : '';
      $$('#lnCycSeg button', root).forEach(b => b.onclick = () => { st.period = b.dataset.v; cycle(); });
      if (M.cyc && D.panel[M.cyc + '|claims_0_12']) { const pr = per === 'post' ? post : D.panel[M.cyc + '|claims_0_12']; barChart(R('#lnCyc'), { title: M.name + ': change in filings per doubling of claims, by lag' + (per === 'post' ? ', 2022 on' : ''), rows: [['lclaims', 'Same month'], ['lclaims_l3', '3 months'], ['lclaims_l6', '6 months'], ['lclaims_l9', '9 months'], ['lclaims_l12', '12 months']].map(k => ({ label: k[1], value: (Math.exp(pr.coefs[k[0]].coef * Math.log(2)) - 1) * 100, color: pr.coefs[k[0]].coef >= 0 ? 'var(--rp-leaf-5)' : 'var(--rp-slate-5)' })), W: 460, lw: 110, fmt: x => sgn(x, 1) }); R('#lnCycNote').textContent = `Percent change in filings per doubling of claims, ${per === 'post' ? 'panel from 2022 on' : 'panel 2019 to 2026'}${M.cyc === 'ldiv' && st.line !== 'div_k' && st.line !== 'div_nk' ? ', all divorce filings (no separate series for this line)' : ''}. Cumulative through 12 months: ${sgn((Math.exp(pr.cum * Math.log(2)) - 1) * 100, 1)}.`; } else { R('#lnCyc').innerHTML = '<div class="small">No monthly series to estimate a cycle for this line.</div>'; R('#lnCycNote').textContent = ''; }
    }
    function play() { const M = L(); const c = CI[st.sel]; const n = M.cnt(c); const est = M.est ? ' (est.)' : ''; const pl = M.pool(c); const fee = SEV_MODEL.line(st.line).fee; R('#lnPlay').innerHTML = `<h3 class="ln-h3">${esc(c.name)} County · ${esc(M.name)}</h3>${M.est ? '<p class="small" style="margin:2px 0 6px">An estimate, not a court count: divorce filings scaled by the married population and the hazard model (module 20 has the method).</p>' : ''}<dl class="kv"><dt>${st.line === 'prenup' ? 'Retained matters a year' : 'Matters, last 12 months'}${est}</dt><dd>${N(n)}</dd><dt>Per 10,000 residents</dt><dd>${N(isN(n) ? n / c.pop2025 * 10000 : null, 1)}</dd><dt>Statewide rate</dt><dd>${N(stateTot(st.line) / sum(CTY.map(x => x.pop2025)) * 10000, 1)}</dd><dt>Pool (${esc(M.poolName)})</dt><dd>${isN(pl) ? N(pl) : 'not modeled'}</dd><dt>Value per retained matter (shared store)</dt><dd>${$$$(fee)}</dd><dt>Annual value at 100% share</dt><dd>${$$$(isN(n) && isN(fee) ? n * fee : null)}</dd></dl><h4 class="ln-h4">Angle</h4><p style="font-size:13px">${esc(M.angle)}</p><h4 class="ln-h4">Seed keywords</h4><p style="font-size:13px">${M.kw.map(k => `<code>${esc(k)}</code>`).join(' ')}</p><p class="small">Add the city and county modifiers from the metro tabs. Authority: ${esc(M.law)}</p>`; }
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'n', l: 'Matters 12mo', fmt: v => N(v), h: 'Matters, last 12 months', d: 0 }, { k: 'per10k', l: 'per 10k pop', fmt: v => N(v, 1), h: 'Matters per 10,000 residents', d: 1 }, { k: 'pool', l: 'Pool', fmt: v => isN(v) ? N(v) : 'not modeled', h: 'Pool', d: 0 }, { k: 'value', l: 'Value at 100%', fmt: v => $$$(v), h: 'Annual value at 100% share ($, value per matter from the shared store)', d: 0 }, { k: 'offices', l: 'Law offices', fmt: v => v ? N(v) : 'none (CBP)', h: 'Law offices (CBP 2023)', d: 0 }, { k: 'per_office', l: 'Matters/office', fmt: (v, r) => r.offices ? N(v, 1) : 'no office', h: 'Matters per law office', d: 1 }, { k: 'esi', l: 'Shock idx', fmt: v => N(v, 0), h: 'Economic Shock Index (percentile)', d: 0 }, { k: 'grade', l: 'Grade', fmt: v => `<span class="grade ${esc(v)}">${esc(v)}</span>`, h: 'Confidence grade' }];
    const rows = () => { const M = L(); const fee = SEV_MODEL.line(st.line).fee; return CTY.map(c => { const n = M.cnt(c); return { _id: c.fips, fips: c.fips, name: c.name, n, per10k: isN(n) ? n / c.pop2025 * 10000 : null, pool: M.pool(c), value: isN(n) && isN(fee) ? n * fee : null, offices: c.rates.lawoffices || 0, per_office: isN(n) && c.rates.lawoffices ? n / c.rates.lawoffices : null, esi: c.esi, grade: c.grade }; }); };
    const tbl = table(R('#lnTable'), { caption: 'Counties for the selected service line', cols, rows: rows(), sort: { k: 'n', dir: -1 }, onRow: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); play(); tbl.setSel(id); }, selected: st.sel });
    /* ---------- the ZIP view ---------- */
    const zMap = R('#lnZMap');
    const ctyOpts = () => [['', 'All counties']].concat(MSA[st.metro].counties.filter(f => CI[f]).map(f => [f, CI[f].name + ' County']));
    const scopeRows = () => C().rows.filter(r => !st.cty || r.z.county === st.cty);
    const ranked = () => scopeRows().map(r => C().cells[r.zip][st.line]).sort((a, b) => b.pri - a.pri || a.z.zip.localeCompare(b.z.zip));
    const buy = () => ranked().filter(c => c.contrib > 0).slice(0, st.n);
    function zipView() {
      if (!R('#lnCty').options.length || R('#lnCty').dataset.m !== st.metro) { R('#lnCty').innerHTML = ctyOpts().map(o => `<option value="${esc(o[0])}">${esc(o[1])}</option>`).join(''); R('#lnCty').dataset.m = st.metro; }
      R('#lnCty').value = st.cty; kpis(); zDraw(); brief(); zTable(); zCard(); levers(); press(); port();
    }
    function zDraw() {
      const G = GEO.metros[st.metro]; const Cc = C(); const lay = LN_LAYERS[st.layer]; const cell = id => Cc.cells[id] ? Cc.cells[id][st.line] : null;
      let value, color, legend = null, leg = '';
      if (lay.cat === 'bid') { const bands = FLM.BANDS.map(b => b[1]); value = id => { const c = cell(id); return c && c.contrib > 0 ? bands.indexOf(c.bid) : null; }; color = i => LN_BIDC[bands[i]]; leg = bands.map(b => `<span><i style="background:${LN_BIDC[b]}"></i>${b > 0 ? '+' : b < 0 ? '−' : ''}${Math.abs(b)}% (${Cc.rows.filter(r => { const c = cell(r.zip); return c && c.contrib > 0 && c.bid === b; }).length})</span>`).join(''); }
      else if (lay.cat === 'quiet') { value = id => { const c = cell(id); return c ? (c.quiet ? 1 : 0) : null; }; color = i => i ? 'var(--s1)' : 'var(--sunk-2)'; leg = `<span><i style="background:var(--s1)"></i>Quiet auction (${Cc.rows.filter(r => cell(r.zip).quiet).length})</span><span><i style="background:var(--sunk-2)"></i>Other</span>`; }
      else if (lay.cat === 'lev') { const ks = FLM.LEVERS.map(x => x[0]); value = id => Cc.by[id] && Cc.by[id].lev.dom ? ks.indexOf(Cc.by[id].lev.dom) : null; color = i => LN_LEV_C[ks[i]]; leg = FLM.LEVERS.map(([k, n]) => { const c = Cc.rows.filter(r => r.lev.dom === k).length; return c ? `<span><i style="background:${LN_LEV_C[k]}"></i>${esc(n)} (${c})</span>` : ''; }).join(''); }
      else { const sc = layerScale({ ramp: lay.ramp, v: c => lay.v(c), f: lay.f, q: lay.q, log: lay.log }, Cc.rows.map(r => cell(r.zip))); value = id => { const c = cell(id); return c ? lay.v(c) : null; }; color = sc.color; legend = Object.assign({ title: `${L().short}: ${lay.l}` }, sc.legend); }
      // the zoomable core map fits and dims the county; without it, a fixed view of the county and a dim class
      const MZ = typeof mapHandle === 'function'; const ctyZ = st.cty ? Cc.rows.filter(r => r.z.county === st.cty).map(r => r.zip) : null;
      const zo = MZ ? { dim: ctyZ, fit: ctyZ, reset: st.reset || undefined } : { view: ctyZ ? FLM.box(st.metro, ctyZ) : null }; st.reset = false; if (legend) legend.grade = lay.g;
      drawMap(zMap, Object.assign({ title: `${L().short}: ${lay.l}, ${mName()}`, W: G.W, H: G.H, paths: G.zcta, value, color, label: id => zTip(id), onSelect: id => pickZip(id), selected: st.zip, counties: G.county, cent: G.ccent, labels: Object.keys(G.county), labelText: id => CI[id] ? CI[id].name : id, legend, noDataLabel: 'no matters or under 200 residents' }, zo));
      if (st.cty && !MZ) $$('path.area', zMap).forEach(p => { const z = ZI[p.dataset.id]; if (!z || z.county !== st.cty) p.classList.add('ln-dim'); });
      R('#lnZLeg').innerHTML = (leg ? `<div class="ln-catleg">${leg}</div>` : '') + `<p class="small">${lay.cat ? gradeB(lay.g) + ' ' : ''}${esc(lay.note)}${st.cty ? ` Zoomed to ${esc(CI[st.cty].name)} County; other ZIPs are dimmed.` : ''}</p>`;
    }
    function zTip(id) {
      const Cc = C(); const r = Cc.by[id]; if (!r) return `<b>${esc(id)}</b><div class="small">Under 200 residents: no estimates for this ZIP.</div>`; const c = Cc.cells[id][st.line];
      return `<b>${esc(id)} · ${esc(r.z.city || '')}</b><div class="row"><span>${esc(L().short)}</span><span>priority ${N(c.pri, 0)} · bid ${c.bid > 0 ? '+' : ''}${N(c.bid)}%</span></div><div class="row"><span>Matters a year</span><span>${N(c.matters, 1)}</span></div><div class="row"><span>Contribution a year</span><span>${$$$(c.contrib)}</span></div><div class="row"><span>Competition</span><span>${N(c.presspct, 0)}</span></div><div class="row"><span>Top line here</span><span>${esc(r.top ? LINE_META[r.top].short : NA)}</span></div>${c.quiet ? '<div class="small">Quiet auction</div>' : ''}`;
    }
    function pickZip(id) { if (!C().by[id]) { st.zip = null; zCard(id); return; } st.zip = id; if (typeof mapHandle === 'function') mapHandle(zMap).select(id); else markSel(zMap, id); zCard(); if (ztbl) ztbl.setSel(id); econ(); }
    /* the line brief */
    const sparkS = (m) => { const w = 240, h = 46, bw = w / 12, mx = Math.max(...m, 1); return `<svg class="ln-spark" viewBox="0 0 ${w} ${h + 14}" role="img" aria-label="Season index by month">${m.map((v, i) => `<rect x="${(i * bw + 1).toFixed(1)}" y="${(h - v / mx * h).toFixed(1)}" width="${(bw - 2).toFixed(1)}" height="${(v / mx * h).toFixed(1)}" class="${v >= 110 ? 'hi' : v <= 90 ? 'lo' : ''}"><title>${MOL[i]} ${N(v, 0)}</title></rect>`).join('')}${MO.map((m0, i) => `<text x="${(i * bw + bw / 2).toFixed(1)}" y="${h + 11}" text-anchor="middle">${m0[0]}</text>`).join('')}</svg>`; };
    const fitBars = fit => `<div class="ln-fit">${FLM.PLATS.map(p => `<div class="ln-fitc" title="${esc(FLM.PLAB[p])}: fit ${fit[p] || 0} of 3"><span>${esc(FLM.PLAB[p].replace('YouTube and Demand Gen', 'YouTube').replace('Local Services Ads', 'LSA').replace('Google Search', 'Search'))}</span><i aria-hidden="true">${[1, 2, 3].map(k => `<b class="${(fit[p] || 0) >= k ? 'on' : ''}"></b>`).join('')}</i><span class="vh">${fit[p] || 0} of 3</span></div>`).join('')}</div>`;
    function brief() {
      const M = L(), Cc = C(); const cs = scopeRows().map(r => Cc.cells[r.zip][st.line]); const s = FLM.season(st.line); const mm = s.months; const ord = mm.map((v, i) => [v, i]).sort((a, b) => b[0] - a[0]);
      const heavy = mm.map((v, i) => v >= 110 ? MO[i] : null).filter(Boolean), light = mm.map((v, i) => v <= 90 ? MO[i] : null).filter(Boolean); const ln = SEV_MODEL.line(st.line);
      const act = (() => { const a = FLM.activity(); return sum(MSA[st.metro].counties.map(f => (a[f] && a[f][st.line]) || 0)); })();
      R('#lnBrief').innerHTML = `<div class="ln-bhead"><h3 class="ln-h3">${esc(M.name)}</h3>${M.kind === 'lens' ? pill('Lens inside divorce') : pill('Additive line')}</div><p class="small" style="margin:2px 0 8px">${esc(M.intent || '')}</p>
        <h4 class="ln-h4">Scope: ${st.cty ? esc(CI[st.cty].name) + ' County' : esc(mName())} · ${N(cs.length)} ZIPs</h4>
        <dl class="kv"><dt>Matters a year ${gradeB(M.est ? 'C' : 'B')}</dt><dd>${N(sum(cs.map(c => c.matters)))}</dd><dt>Fee paying ${FLM.PAYER[st.line] ? `(${N(SEV_MODEL.rate(FLM.PAYER[st.line]))}% pay a private fee)` : ''}</dt><dd>${N(sum(cs.map(c => c.payable)))}</dd><dt>Payer weighted</dt><dd>${N(sum(cs.map(c => c.mass)))}</dd><dt>Collected value per retained matter ${gradeB(ln.src.fee === 'actuals' ? 'B' : ln.src.fee === 'you' ? '' : 'D')}</dt><dd>${$$$(FLM.valueAt(st.line, 1))}</dd><dt>Contribution a year at 100% share</dt><dd>${$$$(sum(cs.map(c => c.contrib)))}</dd><dt>Quiet auction ZIPs</dt><dd>${N(cs.filter(c => c.quiet).length)}</dd><dt>Live rival ads logged for the line</dt><dd>${act ? N(act) : 'none logged'}</dd></dl>
        <h4 class="ln-h4">Season</h4>${sparkS(mm)}<p class="small">${s.flat ? esc(s.src) + '.' : `Peak ${MOL[ord[0][1]]} (${N(ord[0][0], 0)}), trough ${MOL[ord[11][1]]} (${N(ord[11][0], 0)}). Heavy: ${heavy.join(', ') || 'none'}. Light: ${light.join(', ') || 'none'}. ${esc(s.src)}.`}</p>
        <h4 class="ln-h4">Channel fit ${gradeB('C')}</h4>${fitBars(M.fit || {})}<p class="small">Mobile share to expect: about ${N(M.mobile)}% (judgment, grade C). Dayparts: the ${esc((FLM.DAYPARTS[M.dayparts] || {}).l || 'considered')} template.</p>
        <h4 class="ln-h4">Creative hooks</h4><ul class="ln-list">${(M.hooks || []).map(h => `<li>${esc(h)}</li>`).join('')}</ul>
        <h4 class="ln-h4">Calendar and data triggers</h4><ul class="ln-list">${(M.triggers || []).map(h => `<li>${esc(h)}</li>`).join('')}</ul>
        <h4 class="ln-h4">Line negatives beyond the shared list</h4><div class="ln-negs">${(M.negs || []).map(n => `<code>${esc(n)}</code>`).join(' ')}</div>
        <div class="btnrow" style="margin-top:12px"><button type="button" class="btn sm primary" id="lnBDesk">Build this line in the Campaign Desk ↗</button><button type="button" class="btn sm" id="lnBWatch">Who is advertising it ↗</button><button type="button" class="btn sm" id="lnBPaid">Paid Acquisition ↗</button><button type="button" class="btn sm" id="lnBForge">Site Forge ↗</button></div>`;
      R('#lnBDesk').onclick = toDesk; R('#lnBWatch').onclick = () => goModule('watch', { line: st.line, metro: st.metro }); R('#lnBPaid').onclick = () => goModule('paid', { metro: st.metro, line: st.line }); R('#lnBForge').onclick = () => { const b = buy().slice(0, 20); if (!b.length) { R('#lnMsg').textContent = 'No ZIP in scope has matters for this line.'; return; } goModule('forge', { zips: b.map(c => c.z.zip) }); };
    }
    function toDesk() { const b = buy(); if (!b.length) { R('#lnMsg').textContent = 'No ZIP in scope has matters for this line; pick another line, county or metro.'; return; } const bids = {}; b.forEach(c => bids[c.z.zip] = c.bid); goModule('desk', { geo: 'msa:' + st.metro, zips: b.map(c => c.z.zip), line: st.line, bids }); }
    /* the ranked ZIP table */
    let ztbl = null;
    const zcols = [{ k: 'rank', l: '#', fmt: v => N(v) }, { k: 'zip', l: 'ZIP', fmt: v => esc(v) }, { k: 'city', l: 'City', fmt: v => esc(v), cls: 'l' }, { k: 'pri', l: 'Priority', fmt: v => N(v, 0), h: 'Priority percentile', d: 1 }, { k: 'matters', l: 'Matters/yr', fmt: v => N(v, 1), h: 'Matters a year', d: 2 }, { k: 'contrib', l: 'Contribution', fmt: v => $$$(v), h: 'Contribution a year ($)', d: 0 }, { k: 'press', l: 'Competition', fmt: v => N(v, 0), h: 'Competition percentile', d: 1 }, { k: 'cost', l: 'Cost idx', fmt: v => N(v, 2), h: 'Cost index', d: 3 }, { k: 'bid', l: 'Bid', fmt: v => (v > 0 ? '+' : '') + N(v) + '%', h: 'Bid modifier (%)', d: 0 }, { k: 'quiet', l: 'Quiet', fmt: v => v ? 'yes' : '', h: 'Quiet auction' }, { k: 'lev', l: 'Levers', fmt: v => esc(v), cls: 'l' }];
    const zrows = () => ranked().map((c, i) => ({ _id: c.z.zip, rank: i + 1, zip: c.z.zip, city: c.z.city, pri: c.pri, matters: c.matters, contrib: c.contrib, press: c.presspct, cost: c.cost, bid: c.bid, quiet: c.quiet, lev: C().by[c.z.zip].lev.tags.slice(0, 2).map(k => (FLM.LEVERS.find(x => x[0] === k) || [])[1]).join(', ') }));
    function zTable() { R('#lnTblH').textContent = `Ranked ZIPs: ${L().short}, ${st.cty ? CI[st.cty].name + ' County' : mName()}`; if (!ztbl) ztbl = table(R('#lnZTbl'), { caption: 'ZIPs ranked by priority for the selected line', cols: zcols, rows: zrows(), sort: { k: 'pri', dir: -1 }, onRow: pickZip, selected: st.zip }); else { ztbl.setRows(zrows()); ztbl.setSel(st.zip, true); } }
    /* the ZIP card: every line ranked in the ZIP */
    function zCard(miss) {
      const Cc = C(); const r = st.zip ? Cc.by[st.zip] : null;
      if (!r) { R('#lnZCardH').textContent = 'ZIP card'; R('#lnZCardSub').textContent = miss ? `${miss}: under 200 residents, so no estimates for this ZIP.` : 'Click a ZIP on the map or a row in the ranking.'; R('#lnZCard').innerHTML = `<p class="small">Every ZIP carries all ${ids.length} lines with matters, contribution, competition, priority and bid, the audience levers, the angles its data triggers and a suggested share of the media.</p>`; return; }
      const z = r.z; const rowsL = FLM.ALL.map(id => ({ id, c: Cc.cells[z.zip][id] })).sort((a, b) => b.c.contrib - a.c.contrib);
      const sc = scopeRows(); const tot = sum(sc.map(x => x.opp)) || 1; const sh = r.opp / tot; const b = buy(); const inBuy = b.some(c => c.z.zip === z.zip); const bud = SEV_MODEL.get('budget'); const buyTot = sum(b.map(c => Cc.by[c.z.zip].opp)) || 1;
      R('#lnZCardH').textContent = `${z.zip} · ${z.city}`; R('#lnZCardSub').innerHTML = `${esc(z.county_name)} County · ${N(z.acs.hh)} households · Google criterion ${esc(z.gt || 'resolve by name')} · Meta key US:${esc(z.zip)}`;
      R('#lnZCard').innerHTML = `<p class="small">Best ranked additive line here: <b>${esc(r.best ? LINE_META[r.best].short : NA)}</b>${r.best ? ` (${N(Cc.cells[z.zip][r.best].pri, 0)}th percentile)` : ''}. Largest by contribution: <b>${esc(r.top ? LINE_META[r.top].short : NA)}</b>.</p>
        <div class="tblbox"><div class="tblwrap" style="max-height:420px"><table class="t"><caption class="vh">Every line in ${esc(z.zip)}, by contribution</caption><thead><tr><th scope="col" class="l">Line</th><th scope="col">Matters/yr</th><th scope="col">Contribution</th><th scope="col">Competition</th><th scope="col">Priority</th><th scope="col">Bid</th></tr></thead><tbody>${rowsL.map(({ id, c }) => `<tr class="${id === st.line ? 'sel' : ''}"><td class="l">${esc(LINE_META[id].short)}${LINE_META[id].kind === 'lens' ? ' <span class="ln-lensmark">lens</span>' : ''}${c.quiet ? ' <span class="pill">quiet</span>' : ''}</td><td>${N(c.matters, 1)}</td><td>${$$$(c.contrib)}</td><td>${N(c.presspct, 0)}</td><td>${N(c.pri, 0)}</td><td>${c.bid > 0 ? '+' : ''}${N(c.bid)}%</td></tr>`).join('')}</tbody></table></div></div>
        <h4 class="ln-h4">Audience levers</h4><div>${r.lev.tags.length ? r.lev.tags.map(k => `<span class="pill">${esc((FLM.LEVERS.find(x => x[0] === k) || [])[1])}</span>`).join(' ') : '<span class="small">No lever stands out against the metro.</span>'}</div><p class="small">Dominant: ${esc(r.lev.dom ? (FLM.LEVERS.find(x => x[0] === r.lev.dom) || [])[1] : NA)}. Spanish creative follows the firm profile's languages: the data carries no ZIP language counts.</p>
        <h4 class="ln-h4">Angles this ZIP triggers</h4><div>${r.angles.length ? r.angles.map(a => { const A = FL_ANGLES.find(x => x.id === a); return `<span class="pill" title="${esc(A.why)}">${esc(A.short)}</span>`; }).join(' ') : '<span class="small">None of the angle thresholds.</span>'}</div>
        ${(() => { if (typeof WATCH === 'undefined' || !WATCH || typeof WATCH.advertisersIn !== 'function') return ''; let adv = []; try { adv = WATCH.advertisersIn({ zip: z.zip }) || []; } catch (e) { return ''; } return `<h4 class="ln-h4">Advertisers logged here</h4><p class="small">${adv.length ? adv.slice(0, 5).map(a => `${esc(a.name)} (${a.live ? N(a.live) + ' live' : 'no live ad'})`).join('; ') + (adv.length > 5 ? ' and ' + (adv.length - 5) + ' more' : '') + '. Only what the firm logged in Competitor Watch.' : 'None logged in Competitor Watch for this ZIP or its county.'}</p>`; })()}
        <h4 class="ln-h4">Media</h4><dl class="kv"><dt>Share of the scope's contribution</dt><dd>${P(sh, 2)}</dd><dt>In the buy (top ${N(st.n)} for ${esc(L().short)})</dt><dd>${inBuy ? 'yes' : 'no'}</dd><dt>Indicative monthly media at ${$$$(bud)} across the buy</dt><dd>${inBuy ? $$$(bud * r.opp / buyTot) : NA}</dd></dl>
        <div class="btnrow" style="margin-top:10px"><button type="button" class="btn sm primary" id="lnZDesk">Campaign Desk: ${esc(L().short)} in ${esc(z.zip)} ↗</button><button type="button" class="btn sm" id="lnZPaid">Paid Acquisition ↗</button><button type="button" class="btn sm" id="lnZWatch">Competitor Watch ↗</button></div>`;
      R('#lnZDesk').onclick = () => { const c = Cc.cells[z.zip][st.line]; goModule('desk', { geo: 'msa:' + st.metro, zips: [z.zip], line: st.line, bids: { [z.zip]: c.bid } }); };
      R('#lnZPaid').onclick = () => goModule('paid', { metro: st.metro, zip: z.zip, line: st.line }); R('#lnZWatch').onclick = () => goModule('watch', { zip: z.zip, county: z.county, line: st.line });
    }
    /* KPIs for the metro */
    function kpis() {
      const Cc = C(); const add = FLM.ADD.map(id => ({ id, a: Cc.lines[id] })).sort((a, b) => b.a.contrib - a.a.contrib);
      const seas = ids.map(id => ({ id, s: FLM.season(id) })).filter(x => !x.s.flat && LINE_META[x.id].seas === x.id).map(x => ({ id: x.id, r: Math.max(...x.s.months) / Math.max(1, Math.min(...x.s.months)) })).sort((a, b) => b.r - a.r)[0];
      const bestC = {}; Cc.rows.forEach(r => { if (r.best) bestC[r.best] = (bestC[r.best] || 0) + 1; }); const bt = Object.entries(bestC).sort((a, b) => b[1] - a[1]);
      R('#lnKpis').innerHTML = tile('Contribution pool', lnM(sum(add.map(x => x.a.contrib))), `ten additive lines, a year, ${esc(mName())}, at 100% share`, 'C') + tile('Largest line', esc(LINE_META[add[0].id].short), `${lnM(add[0].a.contrib)} · ${N(add[0].a.matters)} matters a year`, 'C') + tile('Second line', esc(LINE_META[add[1].id].short), `${lnM(add[1].a.contrib)} · ${N(add[1].a.matters)} matters a year`, 'C') + (seas ? tile('Most seasonal', esc(LINE_META[seas.id].short), `peak month ${N(seas.r, 2)} times the trough (statewide series)`, 'B') : '') + (bt.length ? tile('Comparative advantage', esc(LINE_META[bt[0][0]].short), `the line most ZIPs rank highest in: ${bt.slice(0, 3).map(([k, v]) => esc(LINE_META[k].short) + ' ' + v).join(', ')}`, 'C') : '') + tile('Quiet auction ZIPs', N(Cc.rows.filter(r => r.quiet >= 3).length), 'three or more additive lines with high contribution and low competition', 'C');
    }
    /* the heat table: every line by month */
    function heat() {
      const cell = v => { const t = clamp((v - 100) / 25, -1, 1); const pct = Math.round(Math.abs(t) * 55); return `<td style="background:color-mix(in srgb, ${t >= 0 ? 'var(--s2)' : 'var(--s3)'} ${pct}%, var(--card))">${N(v, 0)}</td>`; };
      R('#lnHeat').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t ln-heat"><caption class="vh">Season index by line and month</caption><thead><tr><th scope="col" class="l">Line</th>${MO.map(m => `<th scope="col">${m}</th>`).join('')}<th scope="col">Peak to trough</th><th scope="col" class="l">Series</th></tr></thead><tbody>${ids.map(id => { const s = FLM.season(id); const m = s.months; return `<tr class="${id === st.line ? 'sel' : ''}"><th scope="row" class="l">${esc(LINE_META[id].short)}${LINE_META[id].kind === 'lens' ? ' <span class="ln-lensmark">lens</span>' : ''}</th>${s.flat ? `<td colspan="12" class="ln-flat">no monthly series: flat</td>` : m.map(cell).join('')}<td>${s.flat ? NA : N(Math.max(...m) / Math.max(1, Math.min(...m)), 2) + '×'}</td><td class="l small">${esc(s.flat ? 'none' : LINE_META[id].seas === id ? 'own series' : 'divorce proxy')}</td></tr>`; }).join('')}</tbody></table></div></div><p class="small">Read an index of 121 in March as March carrying 1.21 times the average month of 2022 to 2025, not as a forecast. Red is above the average month, blue below.</p>`;
    }
    /* unit economics editor, saved to the shared store */
    const srcBadge = x => x.src === 'actuals' ? `<span class="ln-src act" title="From the Accounts actuals you applied${x.since ? ', since ' + esc(x.since) : ''}">actuals ${gradeB('B')}</span>` : x.src === 'you' ? '<span class="ln-src you">your input</span>' : `<span class="ln-src def" title="${esc('Default: ' + (x.F || ''))}">default ${gradeB('D')}</span>`;
    function econ() {
      const M = L(), id = st.line; R('#lnEName').textContent = M.short; const Cc = C(); const r = st.zip ? Cc.by[st.zip] : null; const rel = r ? r.cpc_rel : Cc.med.cpc_rel; const fvi = r ? r.fvi : 1; const u = FLM.econ(id, rel, fvi, r ? r.divMix : 0.5);
      const fld = (sc, k, F) => { const x = SEV_MODEL.info(sc, sc === 'line' ? id : null, k); const v = x.v; const fid = `lnE_${sc}_${k}`; return `<div class="ctl"><label for="${fid}">${esc(F.l)}</label><input type="number" id="${fid}" data-sc="${sc}" data-k="${k}" value="${v == null ? '' : +(+v).toFixed(4)}" min="${F.min}" max="${F.max}" step="${F.step}" inputmode="decimal"${k === 'flat' ? ` placeholder="same as the fee"` : ''}>${srcBadge(Object.assign({ F: F.src }, x))}</div>`; };
      const LF = SEV_MODEL.LF; const lineKeys = ['fee', 'realization', 'cvr', 'show', 'close', 'cpcMult', 'contested', 'flat', 'pipe', 'lsaCpl', 'metaCpl'].filter(k => k !== 'pipe' || FLM.PIPE_TO[id]);
      const ae = document.activeElement; const fid = ae && ae.id && R('#lnEcon').contains(ae) ? ae.id : null;   // a re-render keeps the field the user tabbed to
      const PT = FLM.PIPE_TO[id]; const pipeTxt = PT ? `The pipeline credit values the follow on matter (${PT === 'div' ? 'a divorce, at the ZIP\'s mix with and without children' : esc(LINE_META[PT].lc)}) at its own collected value.` : 'This line carries no pipeline credit.';
      R('#lnEcon').innerHTML = `<div class="formgrid ln-form">${lineKeys.map(k => fld('line', k, LF[k])).join('')}</div>
        <details class="ln-rates"${st.ratesOpen ? ' open' : ''}><summary>Shared rates and weights (every line)</summary><div class="formgrid ln-form">${Object.keys(SEV_MODEL.RF).map(k => fld('rate', k, SEV_MODEL.RF[k])).join('')}</div><p class="small">Ability to pay is a weight, never an exclusion. The fee paying shares exist because protective order applicants pay no filing or service fee (§ 81.002), indigent parents in DFPS suits receive appointed counsel (§ 107.013) and the Attorney General's IV-D lawyers represent the state (ch. 231).</p></details>
        <h4 class="ln-h4">Cost per lead by platform ${r ? `in ${esc(r.zip)} (click cost index ${N(rel, 2)})` : `at the metro median click cost index (${N(rel, 2)})`}</h4>
        <div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">Cost per lead by platform for ${esc(M.short)}</caption><thead><tr><th scope="col" class="l">Platform</th><th scope="col">Fit</th><th scope="col">Weight</th><th scope="col">Cost per lead</th></tr></thead><tbody>${FLM.PLATS.map(p => { const part = u.parts.find(x => x.p === p); return `<tr><td class="l">${esc(FLM.PLAB[p])}</td><td>${N((M.fit || {})[p] || 0)}</td><td>${part ? P(part.share, 0) : NA}</td><td>${isN(u.byPlat[p]) ? $$$(u.byPlat[p]) : p === 'linkedin' ? 'referral only' : NA}</td></tr>`; }).join('')}</tbody></table></div></div>
        <div class="tiles ln-etiles">${tile('Blended cost per lead', $$$(u.cpl), 'weights are channel fit squared', 'D')}${tile('Cost per retained matter', $$$(u.cpr), `at ${N(u.L.show, 0)}% show and ${N(u.L.close, 0)}% retained`, 'D')}${tile('Value per retained matter', $$$(u.perRet), `${$$$(u.value)} collected${u.pipe ? ` plus ${$$$(u.pipe)} pipeline` : ''}`, 'D')}${tile('Break even cost per lead', $$$(u.beCpl), u.cpl != null && u.cpl > u.beCpl ? 'above break even at these assumptions' : 'room to bid up at these assumptions', 'D')}${tile('Value per media dollar', u.roas != null ? N(u.roas, 1) + '×' : NA, 'value per retained over cost per retained', 'D')}</div>
        <p class="small">Search cost per lead is the account CPC (${$$$(SEV_MODEL.get('cpc'), 2)}) times the line's multiple times the ZIP's click cost index over the click to lead rate; Microsoft is priced at the desk's Microsoft to Google CPC ratio; Local Services and Meta are the stated costs; YouTube, Nextdoor, TikTok and Yelp come from the Campaign Desk benchmarks. ${pipeTxt} A contingent fee is never part of a family matter's value.</p>
        <div class="btnrow"><button type="button" class="btn sm" id="lnELine">Reset ${esc(M.short)}</button></div>`;
      $$('#lnEcon input[data-k]', root).forEach(i => i.onchange = () => { const sc = i.dataset.sc, k = i.dataset.k; const raw = String(i.value).trim(); const v = raw === '' ? null : +raw; if (v != null && !isFinite(v)) return; setTimeout(() => { if (sc === 'line') SEV_MODEL.set({ lines: { [id]: { [k]: v } } }); else SEV_MODEL.set({ rates: { [k]: v } }); }, 0); });
      if (fid) { const f = R('#' + fid); if (f) f.focus({ preventScroll: true }); }
      R('#lnELine').onclick = () => { SEV_MODEL.reset(id); toast(`${M.short}: assumptions back to the defaults`); };
      const dt = R('#lnEcon details.ln-rates'); dt.ontoggle = () => { st.ratesOpen = dt.open; };
    }
    /* dayparts */
    function dayparts() {
      const M = L(); R('#lnDName').textContent = M.short; const obs = FLM.observed(); const g = FLM.grid(st.line, st.obs && !!obs); const T = FLM.DAYPARTS[g.key];
      const cell = v => { const t = clamp(v / 50, -1, 1); return `<td style="background:color-mix(in srgb, ${t >= 0 ? 'var(--s1)' : 'var(--s3)'} ${Math.round(Math.abs(t) * 60)}%, var(--card))">${v > 0 ? '+' : v < 0 ? '−' : ''}${Math.abs(v)}%</td>`; };
      const gridT = (gr, cap) => `<div class="tblbox"><div class="tblwrap"><table class="t ln-day"><caption class="vh">${esc(cap)}</caption><thead><tr><th scope="col"></th>${FLM.BLOCKS.map(b => `<th scope="col">${esc(b)}</th>`).join('')}</tr></thead><tbody>${FLM.DAYS.map((d, i) => `<tr><th scope="row">${d}</th>${gr[i].map(cell).join('')}</tr>`).join('')}</tbody></table></div></div>`;
      R('#lnDay').innerHTML = `${gridT(g.grid, 'Bid adjustments by day and block for ' + M.short)}<dl class="kv" style="margin-top:8px"><dt>Template</dt><dd>${esc(g.l)} ${gradeB(g.g)}</dd><dt>Mobile share to expect</dt><dd>about ${N(M.mobile)}% (grade C)</dd><dt>Primary conversion</dt><dd>${M.mobile >= 75 ? 'Phone call' : M.mobile >= 60 ? 'Call and consultation form' : 'Consultation form and callback request'}</dd></dl><p class="small">${esc(T.note)}</p>${obs ? `<label class="chk"><input type="checkbox" id="lnObs"${st.obs ? ' checked' : ''}> Use the hours observed in Accounts (90 days, every line)</label>` : '<p class="small">Connect or import an account with hour of day rows in Accounts to replace the template with the observed hours.</p>'}<h4 class="ln-h4">LinkedIn referral and recruiting campaigns</h4>${gridT(FLM.DAYPARTS.referral.grid, 'Bid adjustments for LinkedIn referral campaigns')}<p class="small">${esc(FLM.DAYPARTS.referral.note)} The hourly plan file writes the next 7 days hour by hour for the selected line.</p><div class="btnrow"><button type="button" class="btn sm" id="lnHour2">↓ Hourly plan CSV</button></div>`;
      const o = R('#lnObs'); if (o) o.onchange = () => { st.obs = o.checked; dayparts(); };
      R('#lnHour2').onclick = hourly;
    }
    /* portfolio */
    function stackChart(el, cats, series, fmt) {
      const o = { W: 760, H: 260 }; const bx = chartBox(el, o, o.W, o.H); const W = bx.W, H = bx.H; sizeWatch(el, { fn: (e) => stackChart(e, cats, series, fmt), o, w: bx.live ? W : 0 });
      const tot = cats.map((_, i) => sum(series.map(s => s.values[i] || 0))); const mx = Math.max(...tot, 1); const yt = niceTicks(0, mx, 4); const ymax = Math.max(mx, yt[yt.length - 1] || mx);
      const yl = yt.map(v => fmt(v)); const m = { l: Math.max(44, Math.round(Math.max(...yl.map(s => textW(s, 11.5))) + 12)), r: 8, t: 10, b: 24 }; const bw = (W - m.l - m.r) / cats.length; const Y = v => m.t + (1 - v / ymax) * (H - m.t - m.b);
      const svg = [`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="Suggested media by month and line">`];
      yt.forEach((v, i) => svg.push(`<line class="gridl" x1="${m.l}" x2="${W - m.r}" y1="${Y(v)}" y2="${Y(v)}"></line><text class="ax" x="${m.l - 6}" y="${Y(v) + 4}" text-anchor="end">${esc(yl[i])}</text>`));
      cats.forEach((c, i) => { let acc = 0; series.forEach(s => { const v = s.values[i] || 0; if (v <= 0) return; const y0 = Y(acc), y1 = Y(acc + v); acc += v; svg.push(`<rect x="${(m.l + i * bw + bw * 0.12).toFixed(1)}" y="${y1.toFixed(1)}" width="${(bw * 0.76).toFixed(1)}" height="${Math.max(0.5, y0 - y1).toFixed(1)}" fill="${s.color}"><title>${esc(c)} · ${esc(s.name)}: ${esc(fmt(v))}</title></rect>`); }); if (bw > 22 || i % 2 === 0) svg.push(`<text class="ax" x="${(m.l + i * bw + bw / 2).toFixed(1)}" y="${H - 8}" text-anchor="middle">${esc(c)}</text>`); });
      svg.push('</svg>'); el.innerHTML = svg.join('') + `<div class="legendc">${series.map(s => `<span><i style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')}</div>`;
    }
    function port() {
      const bud = SEV_MODEL.get('budget'), alpha = SEV_MODEL.get('alpha'); const zs = scopeRows().map(r => r.zip);
      if (document.activeElement !== R('#lnBud')) R('#lnBud').value = bud; R('#lnAlpha').value = alpha; R('#lnAlphaV').textContent = 'concentration ' + N(alpha, 1); if (document.activeElement !== R('#lnCpc')) R('#lnCpc').value = SEV_MODEL.get('cpc'); R('#lnMo').value = String(st.month);
      const rs = FLM.allocate(st.metro, bud, st.month < 0 ? null : st.month, zs, alpha); const T = { b: sum(rs.map(r => r.budget)), leads: sum(rs.map(r => r.leads)), con: sum(rs.map(r => r.consults)), ret: sum(rs.map(r => r.retained)), rev: sum(rs.map(r => r.revenue)) };
      R('#lnPort').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">Portfolio allocation by line</caption><thead><tr><th scope="col" class="l">Line</th><th scope="col">Season</th><th scope="col">Contribution in scope</th><th scope="col">Media</th><th scope="col">Share</th><th scope="col">Cost per lead</th><th scope="col">Leads</th><th scope="col">Consultations</th><th scope="col">Retained</th><th scope="col">Value</th><th scope="col">Value per media $</th><th scope="col">Share of the month's paying matters</th></tr></thead><tbody>${rs.map(r => `<tr class="${r.id === st.line ? 'sel' : ''}"><td class="l">${esc(LINE_META[r.id].short)}</td><td>${N(r.season, 0)}</td><td>${$$$(r.contrib)}</td><td>${$$$(r.budget)}</td><td>${T.b > 0 ? P(r.budget / T.b, 0) : NA}</td><td>${$$$(r.u.cpl)}</td><td>${N(r.leads, 1)}</td><td>${N(r.consults, 1)}</td><td>${N(r.retained, 1)}</td><td>${$$$(r.revenue)}</td><td>${r.budget > 0 ? N(r.revenue / r.budget, 1) + '×' : NA}</td><td>${r.share != null ? P(r.share, 1) : NA}</td></tr>`).join('')}<tr class="ln-tot"><td class="l"><b>Total</b></td><td></td><td>${$$$(sum(rs.map(r => r.contrib)))}</td><td><b>${$$$(T.b)}</b></td><td>${T.b > 0 ? '100%' : NA}</td><td>${T.leads > 0 ? $$$(T.b / T.leads) : NA}</td><td><b>${N(T.leads, 1)}</b></td><td>${N(T.con, 1)}</td><td><b>${N(T.ret, 1)}</b></td><td><b>${$$$(T.rev)}</b></td><td>${T.b > 0 ? N(T.rev / T.b, 1) + '×' : NA}</td><td></td></tr></tbody></table></div></div>`;
      const monthly = MO.map((_, m) => FLM.allocate(st.metro, bud, m, zs, alpha)); const ann = {}; monthly.forEach(a => a.forEach(r => ann[r.id] = (ann[r.id] || 0) + r.budget)); const order = Object.keys(ann).sort((a, b) => ann[b] - ann[a]); const top = order.slice(0, 6), rest = order.slice(6);
      const cols0 = ['var(--s1)', 'var(--s3)', 'var(--s4)', 'var(--s5)', 'var(--s8)', 'var(--s6)']; const series = top.map((id, i) => ({ name: LINE_META[id].short, color: cols0[i], values: monthly.map(a => (a.find(r => r.id === id) || {}).budget || 0) })); if (rest.length) series.push({ name: 'Other lines', color: 'var(--ink-3)', values: monthly.map(a => sum(a.filter(r => rest.includes(r.id)).map(r => r.budget))) });
      if (typeof colBars === 'function') colBars(R('#lnPortChart'), { cats: MO, series, stacked: true, fmt: v => $$$(v), yfmt: v => '$' + K(v), title: 'Suggested media by month and line' }); else stackChart(R('#lnPortChart'), MO, series, v => '$' + K(v));
      R('#lnPortN').textContent = `The same monthly budget, re-split each month by season: ${$$$(bud * 12)} a year at ${$$$(bud)} a month, ${st.cty ? CI[st.cty].name + ' County' : mName()}. Adoption, CPS defense and prenups have no monthly series, so their months are flat.`;
    }
    /* levers and competition tables */
    function levers() {
      const Cc = C(); R('#lnLev').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">Audience levers in the metro</caption><thead><tr><th scope="col" class="l">Lever</th><th scope="col">ZIPs tagged</th><th scope="col">Dominant in</th><th scope="col" class="l">What it changes</th></tr></thead><tbody>${FLM.LEVERS.map(([k, n, d]) => `<tr><td class="l"><span class="ln-sw" style="background:${LN_LEV_C[k]}"></span>${esc(n)}</td><td>${N(Cc.rows.filter(r => r.lev.tags.includes(k)).length)}</td><td>${N(Cc.rows.filter(r => r.lev.dom === k).length)}</td><td class="l ln-wrap">${esc(d)}</td></tr>`).join('')}<tr><td class="l"><span class="ln-sw" style="background:var(--line-strong)"></span>Spanish</td><td>${NA}</td><td>${NA}</td><td class="l ln-wrap">No ZIP language counts ship with this build (ACS C16002); Spanish ad sets follow the languages in the firm profile, always paired with English.</td></tr></tbody></table></div></div><p class="small">A ZIP is tagged when its lever percentile within the metro is 75 or more (military also needs 3% active duty exposure among the married). Map layer: Dominant audience lever.</p>`;
    }
    function press() {
      const Cc = C(); const a = FLM.activity(); const cts = MSA[st.metro].counties; const n = id => sum(cts.map(f => (a[f] && a[f][id]) || 0));
      R('#lnPress').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">Competition by line in the metro</caption><thead><tr><th scope="col" class="l">Line</th><th scope="col">Contested ZIPs</th><th scope="col">Quiet ZIPs</th><th scope="col">Contribution in quiet ZIPs</th><th scope="col">Rival ads logged</th></tr></thead><tbody>${FLM.ALL.map(id => { const x = Cc.lines[id]; return `<tr class="${id === st.line ? 'sel' : ''}"><td class="l">${esc(LINE_META[id].short)}</td><td>${N(x.contested)}</td><td>${N(x.quiet)}</td><td>${x.contrib > 0 ? P(x.quietContrib / x.contrib, 0) : NA}</td><td>${n(id) ? N(n(id)) : 'none'}</td></tr>`; }).join('')}</tbody></table></div></div><p class="small">Competition is ${N(Cc.lines.div_k.medPress, 2)} law offices per 1,000 married within ${N(Cc.radius)} km at the median ZIP. ${Cc.logged ? 'Live rival ads logged in Competitor Watch for these counties raise the competition of their ZIPs (each ad adds ' + N(SEV_MODEL.rate('pressStep'), 1) + ' times, capped at ' + N(SEV_MODEL.rate('pressCap'), 1) + ' times).' : 'No live rival ads are logged in Competitor Watch for these counties, so competition is law office density alone.'} The module recomputes on every Competitor Watch save.</p><div class="btnrow"><button type="button" class="btn sm" id="lnPWatch">Competitor Watch ↗</button></div>`;
      R('#lnPWatch').onclick = () => goModule('watch', { line: st.line, metro: st.metro });
    }
    /* method, judgment calls and exclusions */
    function prose() {
      R('#lnMeth').innerHTML = [
        `<b>Matters a year ${gradeB('B')}.</b> Divorce with children, custody suits, modifications, enforcements, protective orders and IV-D come from each county's filings for the last twelve months, allocated to its ZIPs by married adults times the modeled hazard; divorce without children is divorce less divorce with children. Adoption and CPS take the county count times the ZIP's share; prenups and the high asset, military and gray lenses spread the county estimate by married adults married in the past year, in households over $150,000, on active duty and aged 55 and over.`,
        `<b>Fee paying and payer weighted ${gradeB('C')}.</b> Protective orders keep the respondent share, IV-D the privately paying share, CPS the share of parents who are not indigent (editable, grade D). Each ZIP's payer weight is ${N(SEV_MODEL.rate('payLow'), 2)} for households under $35,000 (ACS), ${N(SEV_MODEL.rate('payMid'), 2)} for $35,000 to $60,000 (the married adults' households in the composition model, the only ZIP source for that band) and 1 above.`,
        `<b>Value ${gradeB('D')}.</b> The value per retained matter (module 06's defaults, a placeholder for the firm's fee history) times the fee value index, the square root of the ZIP's median household income over the metro median, bounded 0.7 to 1.6, for the contested share; the flat fee for the rest; times the share collected. The pipeline credit adds the follow on matter: custody suits to modification, protective order respondents to divorce, divorces with children to enforcement.`,
        `<b>Competition and cost ${gradeB('C')}.</b> Law offices within ${N(SEV_MODEL.rate('radiusKm'))} km per 1,000 married within the same radius (ZIP centers in the metro map's projection), raised by the live rival ads logged in Competitor Watch for the ZIP's county, ranked within the metro and the line. The click cost index is 0.55 plus 1.55 times (0.6 competition percentile plus 0.4 fee value percentile), 0.55 to 2.10.`,
        `<b>Priority and bids ${gradeB('C')}.</b> Contribution over (click cost index times the line's CPC multiple times (0.55 plus 0.9 times the competition percentile)), ranked within the metro: +45 at the 90th percentile and up, +30 at 75, +15 at 55, 0 at 35, minus 20 at 15, minus 40 below. A quiet auction is contribution in the top 40% with competition in the bottom 45%.`,
        `<b>Economics ${gradeB('D')}.</b> Cost per lead by platform blended by the square of channel fit; cost per retained matter divides by the show and retained rates; break even cost per lead is the value per retained matter times the retained share of leads. Accounts' Apply replaces the defaults with observed CPC, conversion, lead to retained and realized fee (grade B).`,
        `<b>Portfolio and season ${gradeB('B')}.</b> The statewide monthly court series by line (2022 to 2025 average = 100); military, high asset and gray divorce use the divorce series; adoption, CPS and prenups are flat. The allocation weights each additive line by contribution in scope times season times value per media dollar, to the concentration power.`,
        `<b>Levers ${gradeB('C')}.</b> Percentiles within the metro for payment led (the divorce with children fee against household income, with renters), premium property, married 55 and over, recent movers, renters, children at home, unmarried parents, the county shock index, military and few law offices nearby. The dominant lever is the highest.`
      ].map(x => `<li>${x}</li>`).join('');
      const jl = a => `<dl class="ln-judg">${a.map(([t, d]) => `<dt>${esc(t)}</dt><dd>${esc(d)}</dd>`).join('')}</dl>`;
      R('#lnJudg').innerHTML = jl([
        ['Lenses are never added', 'High asset, military and gray divorce are ways to target and write the divorce campaigns; their matters sit inside the divorce counts, so the portfolio allocates across the ten additive lines only.'],
        ['Ability to pay is weighted, not excluded', 'Lower income households file and retain lawyers too; a weight keeps them in the ranking without letting volume alone lead it.'],
        ['Protective order applicants pay nothing to file', 'Applicants pay no filing or service fee (§ 81.002) and prosecutors can apply for them (§ 82.002); the respondent share is the private fee market, and applicant pages still belong on the site.'],
        ['CPS defense and appointed counsel', 'Indigent parents in DFPS suits receive appointed counsel (§ 107.013); only the share of parents who are not indigent is counted as fee paying.'],
        ['IV-D is the Attorney General\'s', 'The Attorney General is the Title IV-D agency (ch. 231); private demand is the parent who wants representation at the IV-D docket.'],
        ['No contingent fees', 'A contingent fee is never offered, advertised or modeled for a family matter (Rule 1.04, the compliance engine blocks the language).'],
        ['Dayparts are templates', 'Four templates cover thirteen lines; they are the shape of the demand, not this account\'s. The account\'s hour report replaces them.'],
        ['Seasons are indices, not forecasts', 'An index of 121 in March is March over 2022 to 2025, not next March.']
      ]);
      R('#lnNot').innerHTML = jl([
        ['Keyword volumes', 'No keyword tool was queried; demand is the court counts.'],
        ['Competitor spend', 'Nothing here estimates what any firm spends; Competitor Watch logs what the firm observes.'],
        ['Client data', 'No client names or matter details (Rule 1.05); Accounts reads counts and rates only.'],
        ['Protected characteristics', 'No targeting by race, religion, national origin, sex or family status; levers change the creative, never the audience.'],
        ['Spanish by ZIP', 'No ZIP language counts ship with this build; the firm profile decides Spanish creative.']
      ]);
    }
    /* exports */
    const geoName = () => st.cty ? CI[st.cty].name + ' County' : mName();
    const zipsIn = () => scopeRows().map(r => r.zip);
    const camp = () => (typeof DK_TAB_OF === 'function' ? DK_TAB_OF(st.metro) : 'TX') + '_' + st.line.toUpperCase() + '_SEARCH';
    function hourly() { exportText(expName('lines_hourly_plan_' + st.line, geoName()), FLM.hourlyCSV(st.line, todayISO(), 7, st.obs)); }
    R('#lnLong').onclick = () => exportText(expName('lines_by_zip_long', geoName()), FLM.matrixLong(st.metro, zipsIn()));
    R('#lnWide').onclick = () => exportText(expName('lines_priority_matrix', geoName()), FLM.matrixWide(st.metro, zipsIn()));
    R('#lnG').onclick = () => { const b = buy(); const miss = b.filter(c => !c.z.gt).map(c => c.z.zip); R('#lnMsg').textContent = `Google locations for ${L().short}: the top ${b.length} ZIPs by priority with their bid modifiers, campaign ${camp()}.${miss.length ? ` ${miss.length} ZIPs (${miss.join(', ')}) have no criterion ID; Ads Editor matches them by the Location text.` : ''}`; exportText(expName('lines_google_locations_' + st.line, geoName()), FLM.googleLocations(st.metro, st.line, zipsIn(), st.n, camp())); };
    R('#lnM').onclick = () => { R('#lnMsg').textContent = `Meta ZIP list for ${L().short}: paste the Zip column into the ad set's locations. Write to the situation in the third person; Meta rejects ad text that asserts or implies the viewer's own situation (module 11 screens for it).`; exportText(expName('lines_meta_zips_' + st.line, geoName()), FLM.metaZips(st.metro, st.line, zipsIn(), st.n)); };
    R('#lnCal').onclick = () => exportText(expName('lines_flight_calendar', geoName()), FLM.calendarCSV(st.metro, SEV_MODEL.get('budget'), zipsIn(), SEV_MODEL.get('alpha')));
    R('#lnHour').onclick = hourly;
    R('#lnAsm').onclick = () => exportText(expName('lines_assumptions', geoName(), 'json'), JSON.stringify({ module: 'Service Lines (06)', exported: todayISO(), metro: { code: st.metro, name: mName() }, county: st.cty || null, line: st.line, model: SEV_MODEL.snapshot(), seasons: Object.fromEntries(ids.map(id => [id, FLM.season(id).months.map(v => Math.round(v * 10) / 10)])), dayparts: Object.fromEntries(Object.keys(FLM.DAYPARTS).map(k => [k, { blocks: FLM.BLOCKS, days: FLM.DAYS, grid: FLM.DAYPARTS[k].grid, grade: FLM.DAYPARTS[k].g }])), lines: Object.fromEntries(ids.map(id => [id, { kind: LINE_META[id].kind, fit: LINE_META[id].fit, dayparts: LINE_META[id].dayparts, mobile: LINE_META[id].mobile, negatives: LINE_META[id].negs, triggers: LINE_META[id].triggers }])) }, null, 2), 'application/json');
    R('#lnDesk').onclick = toDesk;
    const lNote = extra => ({ note: typeof csvNote === 'function' ? csvNote('lines', extra) : null });
    R('#lnCsv').onclick = () => exportText(expName('lines', 'texas'), csv(CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => { const o = { fips: c.fips, county: c.name, pop: c.pop2025 }; ids.forEach(id => o[id] = LINE_META[id].cnt(c)); return o; }), [{ l: 'County', k: 'county' }, { l: 'FIPS', k: 'fips' }, { l: 'Population 2025 (Census Vintage 2025)', k: 'pop', d: 0 }].concat(ids.map(id => ({ l: LINE_META[id].name + (id === 'prenup' ? ' (estimated retained matters a year)' : EST_LINES.includes(id) ? ' (estimated filings, last 12 months)' : ' (filings, last 12 months)'), k: id, d: 0 }))), lNote()));
    R('#lnLineCsv').onclick = () => { const M = L(); const lab = M.name + (M.est ? ' (estimated)' : ''); exportText(expName('lines_' + st.line, 'texas'), csv(tbl.sorted(), xcols([cols[0], { k: 'fips', l: 'FIPS' }].concat(cols.slice(1).map(c => c.k === 'n' ? Object.assign({}, c, { h: lab + ', ' + (st.line === 'prenup' ? 'retained matters a year' : 'last 12 months') }) : c.k === 'pool' ? Object.assign({}, c, { h: 'Pool: ' + M.poolName }) : c))), lNote())); };
    R('#lnZipCsv').onclick = () => { const K = [['div', 'Divorce'], ['div_k', 'Divorce with children'], ['sapcr', 'Custody (SAPCR)'], ['po', 'Protective orders'], ['mod', 'Modification'], ['enf', 'Enforcement'], ['ivd', 'Title IV-D'], ['priv', 'All private family law']]; const out = []; ZC.slice().sort((a, b) => a.zip.localeCompare(b.zip)).forEach(z => K.forEach(([k, l]) => { if (z.alloc && isN(z.alloc[k])) out.push({ zip: z.zip, city: z.city, county: z.county_name, fips: z.county, metro: z.msa && MSA[z.msa] ? MNAME(MSA[z.msa].title) : '', line: l, key: k, n: z.alloc[k] }); })); exportText(expName('lines_by_zip', 'texas'), csv(out, [{ l: 'ZIP', k: 'zip' }, { l: 'City', k: 'city' }, { l: 'County', k: 'county' }, { l: 'County FIPS', k: 'fips' }, { l: 'Metro', k: 'metro' }, { l: 'Line', k: 'line' }, { l: 'Line key', k: 'key' }, { l: 'Expected filings a year (county filings allocated to the ZIP)', k: 'n', d: 1 }], lNote('County filings allocated to ZIPs by married adults times the modeled hazard.'))); };
    /* controls */
    wireSeg(R('#lnView'), v => { st.view = v; saveSt(); showView(); });
    function showView() { R('#lnZipView').hidden = st.view !== 'zip'; R('#lnCtyView').hidden = st.view !== 'county'; if (st.view === 'county') draw(); else zipView(); }
    R('#lnMetro').onchange = e => { if (!metroOK(e.target.value)) return; st.metro = e.target.value; st.cty = ''; st.zip = null; store.set('sev.metro', st.metro); saveSt(); zipView(); econ(); };
    R('#lnLayer').onchange = e => { st.layer = e.target.value; saveSt(); zDraw(); };
    R('#lnCty').onchange = e => { st.cty = e.target.value; if (!st.cty) st.reset = true; if (st.zip && st.cty && ZI[st.zip].county !== st.cty) st.zip = null; zipView(); };
    R('#lnN').onchange = e => { st.n = clamp(Math.round(+e.target.value) || 40, 5, 300); e.target.value = st.n; saveSt(); zCard(); };
    /* find: the core's place finder (a ZIP, a city, a county or a courthouse) where it exists, else a ZIP or city prefix */
    function goPlace(p) {
      const m = R('#lnFindMsg'); if (!p) { m.textContent = 'No metro ZIP, city or county matches.'; return; }
      const z = p.zip && ZI[p.zip] && metroOK(ZI[p.zip].msa) ? ZI[p.zip] : null; const msa = (z && z.msa) || p.msa || (CI[p.fips] && CI[p.fips].msa);
      if (!msa || !metroOK(msa)) { m.textContent = `${p.label || p.zip || ''} is outside the 26 metros the ZIP view covers.`; return; }
      if (msa !== st.metro) { st.metro = msa; R('#lnMetro').value = msa; st.cty = ''; store.set('sev.metro', msa); saveSt(); }
      if (p.kind === 'county' || p.kind === 'court') { st.cty = p.fips; st.zip = null; m.textContent = `${CI[p.fips].name} County`; }
      else { st.zip = z ? z.zip : null; if (st.cty && z && z.county !== st.cty) st.cty = ''; m.textContent = z ? `${z.zip} ${z.city}` : (p.label || ''); }
      zipView(); econ();
    }
    const fbScope = () => Object.keys(MSA).filter(metroOK);
    if (typeof findBox === 'function' && typeof findPlace === 'function') findBox(R('#lnFindBox'), goPlace, { scope: fbScope, label: 'Find a ZIP, city or county', placeholder: '75201, Plano or Collin', where: 'the metros' });
    else { let fT = 0; R('#lnFind').oninput = e => { clearTimeout(fT); fT = setTimeout(() => { const q = String(e.target.value).trim().toLowerCase(); if (!q) { R('#lnFindMsg').textContent = ''; return; } const pool = ZC.filter(z => z.cent && metroOK(z.msa)); const hit = pool.find(z => z.zip === q) || pool.filter(z => z.msa === st.metro).find(z => z.zip.startsWith(q) || String(z.city || '').toLowerCase().startsWith(q)) || pool.find(z => z.zip.startsWith(q) || String(z.city || '').toLowerCase().startsWith(q)); goPlace(hit ? { kind: 'zip', zip: hit.zip, msa: hit.msa, label: hit.zip } : null); }, 300); }; }
    R('#lnBud').onchange = e => { const v = +e.target.value; if (isFinite(v) && v >= 0 && String(e.target.value).trim() !== '') SEV_MODEL.set({ budget: v }); else e.target.value = SEV_MODEL.get('budget'); };
    R('#lnMo').onchange = e => { st.month = +e.target.value; port(); };
    R('#lnAlpha').oninput = e => { R('#lnAlphaV').textContent = 'concentration ' + N(+e.target.value, 1); }; R('#lnAlpha').onchange = e => SEV_MODEL.set({ alpha: +e.target.value });
    R('#lnCpc').onchange = e => { const raw = String(e.target.value).trim(); const v = +raw; if (raw !== '' && isFinite(v) && v >= 0) SEV_MODEL.set({ cpc: v }); else e.target.value = SEV_MODEL.get('cpc'); };
    R('#lnReset').onclick = () => { SEV_MODEL.reset(); toast('Every assumption is back to the build defaults'); };
    /* the selected line drives everything below the cards */
    function renderLine() { if (st.view === 'county') draw(); else { kpis(); zDraw(); brief(); zTable(); zCard(); press(); } heat(); econ(); dayparts(); port(); }
    // every module reading the shared store recomputes on 'model' (a set, a reset, an Accounts Apply, a Competitor Watch save)
    const self = this; const redraw = () => { if (st.view === 'zip') zipView(); else { draw(); port(); } heat(); econ(); dayparts(); }; self._redraw = redraw;
    BUS.on('model', () => { if (!root.isConnected) return; if (root.hidden) { self._dirty = true; return; } redraw(); });
    cards(); prose(); heat(); showView(); econ(); dayparts(); if (st.view === 'county') port();
    this.sync = () => { const f = store.get('sev.county', st.sel); if (CI[f] && f !== st.sel) { st.sel = f; if (st.view === 'county') { markSel(mapEl, f); play(); tbl.setSel(f); } } };
    // goModule('lines', {line, county, zip, metro})
    this.receive = p => {
      if (!p) return; if (p.line && LINE_META[p.line] && p.line !== st.line) { st.line = p.line; st.period = null; cards(); }
      if (p.zip && ZI[p.zip] && metroOK(ZI[p.zip].msa)) { const z = ZI[p.zip]; st.metro = z.msa; R('#lnMetro').value = st.metro; st.cty = ''; st.zip = z.zip; st.view = 'zip'; }
      else if (p.metro && metroOK(p.metro)) { if (p.metro !== st.metro) { st.metro = p.metro; R('#lnMetro').value = st.metro; st.cty = ''; st.zip = null; } }
      if (CI[p.county]) { store.set('sev.county', p.county); st.sel = p.county; const m = CI[p.county].msa; if (!p.zip && m && metroOK(m)) { st.metro = m; R('#lnMetro').value = m; st.cty = p.county; st.zip = null; } }
      $$('#lnView button', root).forEach(b => b.setAttribute('aria-pressed', String(b.dataset.v === st.view))); saveSt(); showView(); heat(); econ(); dayparts();
    };
  },
  onShow() { if (this._dirty && this._redraw) { this._dirty = false; this._redraw(); } if (this.sync) this.sync(); }
});
