'use strict';
/* Module 07: Paid Acquisition */
const ZIP_LAYERS = {
  eff: { l: 'Efficiency percentile (expected filings per competing law office)', ramp: 'ember', v: z => z.paid.eff_pct, f: v => N(v, 0), q: false },
  opp: { l: 'Opportunity percentile (expected private family filings)', ramp: 'ember', v: z => z.paid.opp_pct, f: v => N(v, 0), q: false },
  di: { l: 'ZIP Dissolution Index (composition, separation, shock, structure, strain, supply)', ramp: 'ember', v: z => z.di, f: v => N(v, 0), q: false },
  div: { l: 'Expected divorce filings a year (allocated from county filings)', ramp: 'ember', v: z => z.alloc.div, f: v => N(v, 0), log: true },
  priv: { l: 'Expected private family law filings a year', ramp: 'ember', v: z => z.alloc.priv, f: v => N(v, 0), log: true },
  rate: { l: 'Expected divorce filings per 1,000 married', ramp: 'ember', v: z => z.exp_div_per_1k_married, f: v => N(v, 1) },
  haz: { l: 'Composition hazard per 1,000 married (PUMS)', ramp: 'ember', v: z => z.risk.haz_pred, f: v => N(v, 1) },
  sep: { l: 'Separated per 1,000 married (ACS)', ramp: 'ember', v: z => z.acs.sep_per_1k_married, f: v => N(v, 0) },
  inc: { l: 'Median household income', ramp: 'moss', v: z => z.acs.med_hh_inc, f: v => $$$(v) },
  inc150: { l: 'Households over $150,000 (share)', ramp: 'moss', v: z => z.acs.inc_150k_sh, f: v => P(v, 0) },
  kids: { l: 'Married couple families with children (share)', ramp: 'amber', v: z => z.acs.mc_kids_sh, f: v => P(v, 0) },
  cohab: { l: 'Cohabiting couples with children (share of couples with kids)', ramp: 'amber', v: z => z.acs.cohab_kids_sh, f: v => P(v, 0) },
  offices: { l: 'Law offices in the ZIP (ZIP Business Patterns 2023)', ramp: 'slate', v: z => z.lawoffices, f: v => N(v), log: true },
  rent: { l: 'Renters (share of households)', ramp: 'amber', v: z => z.acs.renter_sh, f: v => P(v, 0) },
  mil: { l: 'Active duty exposure among married (PUMS)', ramp: 'amber', v: z => z.risk.mil_active, f: v => P(v, 1) },
  m55: { l: 'Married 55 and over (share of married)', ramp: 'slate', v: z => z.acs.mar_55p_sh, f: v => P(v, 0) }
};
function zipTipHTML(z, extra) { return `<b>${esc(z.zip)} · ${esc(z.city || '')}</b><div class="row"><span>${esc(z.county_name)} County</span><span>${esc(z.msa && MSA[z.msa] ? MNAME(MSA[z.msa].title) : '')}</span></div><div class="row"><span>Expected divorce filings / yr</span><span>${N(z.alloc.div, 0)}</span></div><div class="row"><span>Private family filings / yr</span><span>${N(z.alloc.priv, 0)}</span></div><div class="row"><span>Law offices</span><span>${N(z.lawoffices)}</span></div><div class="row"><span>Efficiency pct</span><span>${N(z.paid.eff_pct, 0)}</span></div><div class="row"><span>ZIP index</span><span>${N(z.di, 0)}</span></div>${extra || ''}`; }
function drawZipMap(el, codes, L, st, onSel) {
  const code0 = codes[0]; const M = GEO.metros[code0];
  // for RGV two metros: merge geometry by re-projecting is not possible; show first metro and second below via separate maps. Handled by caller.
  const zs = metroZctas([code0]); const sc = layerScale(L, zs);
  const zi = {}; zs.forEach(z => zi[z.zip] = z);
  drawMap(el, { W: M.W, H: M.H, paths: M.zcta, value: id => zi[id] ? L.v(zi[id]) : null, color: sc.color, label: id => zi[id] ? zipTipHTML(zi[id], `<div class="row"><span>${esc(L.l)}</span><span>${esc(L.f(L.v(zi[id])))}</span></div>`) : `<b>${id}</b><div class="small">no data (small population)</div>`, onSelect: onSel, selected: st.sel, counties: M.county, cent: M.ccent, labels: Object.keys(M.county), labelText: id => CI[id].name, legend: Object.assign({ title: L.l }, sc.legend), noDataLabel: 'under 200 residents' });
}
registerModule({
  key: 'paid', num: '07', title: 'Paid Acquisition', desc: 'Where an ad dollar reaches the most filings per competing firm, resolved to the ZIP code, with a budget model and export lists',
  mount(root) {
    const st = { metro: store.get('sev.metro', '19100'), layer: 'eff', sel: null, line: 'div_k', n: 25, cpc: 9.87, cvr: 6.0, retain: 22, budget: 10000 };
    const metroOpts = Object.keys(MSA).sort((a, b) => MSA[b].pop2025 - MSA[a].pop2025).map(k => [k, MNAME(MSA[k].title)]);
    root.innerHTML = mastHTML({ eyebrow: 'Module 07 · Paid Acquisition · 1,127 metropolitan ZIP codes', title: 'Paid Acquisition', dek: `County filings allocated to ZIP codes by each ZIP's married population and its composition hazard, then set against the law offices already in the ZIP. Efficiency is filings per competing office; opportunity is raw filings. Both are percentiles across all metro ZIPs, so a ZIP scoring 90 on efficiency is in the top tenth statewide. The budget model below uses the 2026 legal search benchmarks and the fee defaults from module 06; change any assumption and the math follows.`, facts: [[N(ZC.length), 'ZIP codes across 26 metros'], ['$9.87', 'median legal services CPC, Google search, Apr 2025 to Mar 2026 (WordStream)'], ['5.55%', 'median legal conversion rate; family law 8.52% in the 2023 LocaliQ cut'], ['$131.63', 'median legal cost per lead']] }) + `
    <div class="toolbar"><span class="ttl">Paid Acquisition</span><span class="sub">ZIP maps, ranked lists, budget model, exports</span><span class="sp"></span><button class="btn" id="pdGoogle">↓ Google Ads location CSV</button><button class="btn" id="pdMeta">↓ Meta ZIP list</button><button class="btn" id="pdAll">↓ All ZIPs CSV</button></div>
    <div class="callout note"><div class="h">Read this first: what the ZIP numbers can and cannot say</div><p>The Office of Court Administration reports filings by county, not ZIP, so ZIP filings are an allocation: the county's filings spread across its ZIPs in proportion to married adults times the modeled hazard. That captures where the married people are and how divorce prone they are by composition; it cannot see a neighborhood that is unusually unhappy. Law office counts come from ZIP Business Patterns and include every kind of law office, so downtown ZIPs with corporate firms look more competitive than they are for family law. Use efficiency to shortlist and the county filing rate (module 01) to size.</p></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Metro', sel('pdMetro', metroOpts, st.metro))}${ctl('Map layer', sel('pdLayer', Object.keys(ZIP_LAYERS).map(k => [k, ZIP_LAYERS[k].l]), st.layer))}${ctl('Shortlist size', '<input type="number" id="pdN" value="25" min="5" max="200" style="width:80px">')}</div><div class="split"><div class="mapwrap" id="pdMap"></div><div><h3 style="font-family:var(--display);font-size:20px" id="pdMetroTitle"></h3><div id="pdMetroBody" class="small"></div><h3 style="font-family:var(--display);font-size:20px;margin-top:12px">Selected ZIP</h3><div id="pdZip" class="small"></div></div></div></div>
    <div class="grid2"><div class="panel"><h3>Budget model</h3><div class="sub">Monthly search budget through to retained matters and revenue, against the expected filings in the shortlisted ZIPs.</div><div class="controls">${ctl('Service line', sel('pdLine', Object.keys(LINE_META).map(k => [k, LINE_META[k].name]), st.line))}${ctl('Monthly budget $', '<input type="number" id="pdBudget" value="10000" step="500" style="width:100px">')}${ctl('CPC $', '<input type="number" id="pdCpc" value="9.87" step="0.25" style="width:80px">')}${ctl('Conversion %', '<input type="number" id="pdCvr" value="6.0" step="0.5" style="width:80px">')}${ctl('Lead to retained %', '<input type="number" id="pdRet" value="22" step="1" style="width:80px">')}${ctl('Value per matter $', '<input type="number" id="pdFee" value="9500" step="500" style="width:100px">')}</div><div class="tiles" id="pdCalc"></div><p class="small">Share of market compares retained matters a year with the expected filings for the chosen line in the shortlisted ZIPs (the divorce lines use divorce filings, custody uses SAPCR, protective orders their own filings, modification and enforcement theirs; the estimated lines use the county scaling from module 06).</p></div>
    <div class="panel"><h3>Shortlist</h3><div class="sub">Top ZIPs in the metro by the current map layer. These are the rows the exports carry.</div><div id="pdShort"></div></div></div>
    <div class="panel"><h3>All ZIPs in the metro</h3><div id="pdTable"></div></div>`;
    const mapEl = $('#pdMap');
    function zs() { return metroZctas([st.metro]); }
    function draw() { const L = ZIP_LAYERS[st.layer]; drawZipMap(mapEl, [st.metro], L, st, id => { st.sel = id; markSel(mapEl, id); zipBox(); }); const m = MSA[st.metro]; $('#pdMetroTitle').textContent = MNAME(m.title); $('#pdMetroBody').innerHTML = `<dl class="kv"><dt>Population 2025</dt><dd>${N(m.pop2025)}</dd><dt>Married adults</dt><dd>${N(m.married)}</dd><dt>Divorce filings, 12 mo</dt><dd>${N(m.ttm.div)} (${sgn((m.ttm.div / (m.prev.div || 1) - 1) * 100)})</dd><dt>per 1,000 married</dt><dd>${N(m.div_per_1k_married, 1)}</dd><dt>Private family filings</dt><dd>${N(m.ttm.priv)}</dd><dt>Law offices</dt><dd>${N(m.lawoffices)}</dd><dt>Shock index (pop weighted)</dt><dd>${N(m.esi, 0)}</dd><dt>ZIPs mapped</dt><dd>${N(m.zctas)}</dd></dl>`; shortlist(); tbl.setRows(rows()); }
    function zipBox() { const z = ZI[st.sel]; if (!z) { $('#pdZip').innerHTML = '<span class="small">Click a ZIP on the map.</span>'; return; } const a = z.acs, r = z.risk; $('#pdZip').innerHTML = `<b>${esc(z.zip)} ${esc(z.city)}</b>, ${esc(z.county_name)} County · Google criterion ${esc(z.gt || NA)}<dl class="kv" style="margin-top:4px"><dt>Population</dt><dd>${N(a.pop)}</dd><dt>Married adults</dt><dd>${N(a.married)}</dd><dt>Expected divorce filings / yr</dt><dd>${N(z.alloc.div, 0)}</dd><dt>Expected SAPCR</dt><dd>${N(z.alloc.sapcr, 0)}</dd><dt>Expected protective orders</dt><dd>${N(z.alloc.po, 0)}</dd><dt>Expected modifications + enforcement</dt><dd>${N((z.alloc.mod || 0) + (z.alloc.enf || 0), 0)}</dd><dt>Composition hazard /1k</dt><dd>${N(r.haz_pred, 1)}</dd><dt>Separated /1k married</dt><dd>${N(a.sep_per_1k_married, 0)}</dd><dt>Married with kids</dt><dd>${P(a.mc_kids_sh, 0)}</dd><dt>Cohabiting with kids</dt><dd>${N(a.cohab_hh_kids)}</dd><dt>Median HH income</dt><dd>${$$$(a.med_hh_inc)}</dd><dt>Over $150k</dt><dd>${P(a.inc_150k_sh, 0)}</dd><dt>Renters</dt><dd>${P(a.renter_sh, 0)}</dd><dt>Rent burden 35%+</dt><dd>${P(a.rent_burden35_sh, 0)}</dd><dt>Law offices</dt><dd>${N(z.lawoffices)}</dd><dt>Efficiency / opportunity pct</dt><dd>${N(z.paid.eff_pct, 0)} / ${N(z.paid.opp_pct, 0)}</dd><dt>ZIP index</dt><dd>${N(z.di, 0)}</dd></dl>`; }
    function short() { const L = ZIP_LAYERS[st.layer]; return zs().filter(z => isN(L.v(z))).sort((a, b) => L.v(b) - L.v(a)).slice(0, st.n); }
    function lineKey() { return { div_k: 'div', div_nk: 'div', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', high: 'div', mil: 'div', gray: 'div', prenup: 'div', adopt: 'div', cps: 'div' }[st.line]; }
    function shortlist() { const s = short(); const L = ZIP_LAYERS[st.layer]; $('#pdShort').innerHTML = `<div class="tblwrap" style="max-height:360px"><table class="t"><thead><tr><th>ZIP</th><th style="text-align:left">City</th><th style="text-align:left">County</th><th>${esc(L.l.split(' (')[0])}</th><th>Div/yr</th><th>Offices</th><th>Criterion</th></tr></thead><tbody>${s.map(z => `<tr><td class="name" data-id="${z.zip}">${z.zip}</td><td style="text-align:left">${esc(z.city)}</td><td style="text-align:left">${esc(z.county_name)}</td><td>${esc(L.f(L.v(z)))}</td><td>${N(z.alloc.div, 0)}</td><td>${N(z.lawoffices)}</td><td>${esc(z.gt || '')}</td></tr>`).join('')}</tbody></table></div>`; $$('#pdShort td.name').forEach(td => td.onclick = () => { st.sel = td.dataset.id; markSel(mapEl, st.sel); zipBox(); }); calc(); }
    function calc() { const s = short(); const k = lineKey(); const Lm = LINE_META[st.line]; let expected = sum(s.map(z => z.alloc[k] || 0)); if (['high', 'mil', 'gray', 'prenup', 'adopt', 'cps', 'div_k', 'div_nk'].includes(st.line)) { const ctyF = {}; s.forEach(z => { ctyF[z.county] = ctyF[z.county] || 0; ctyF[z.county] += z.alloc_share; }); expected = sum(Object.keys(ctyF).map(f => (Lm.cnt(CI[f]) || 0) * ctyF[f])); } const clicks = st.budget / st.cpc; const leads = clicks * st.cvr / 100; const ret = leads * st.retain / 100; const rev = ret * st.fee; const cpl = st.budget / Math.max(leads, 1e-9); const cpa = st.budget / Math.max(ret, 1e-9); $('#pdCalc').innerHTML = tile('Clicks / month', N(clicks), 'at $' + N(st.cpc, 2) + ' CPC') + tile('Leads / month', N(leads, 1), 'at ' + N(st.cvr, 1) + '% conversion · $' + N(cpl, 0) + ' per lead') + tile('Retained / month', N(ret, 1), 'at ' + N(st.retain, 0) + '% lead to retained · $' + N(cpa, 0) + ' per matter') + tile('Revenue / month', $$$(rev), 'at $' + N(st.fee, 0) + ' per ' + Lm.short.toLowerCase() + ' matter · ' + N(rev / st.budget, 1) + '× return') + tile('Expected filings / yr', N(expected, 0), Lm.name + ' in the ' + s.length + ' shortlisted ZIPs') + tile('Share of market', P(ret * 12 / Math.max(expected, 1), 1), 'retained matters a year against expected filings'); }
    const cols = [{ k: 'zip', l: 'ZIP', fmt: v => esc(v) }, { k: 'city', l: 'City', fmt: v => esc(v), cls: 'l' }, { k: 'county', l: 'County', fmt: v => esc(v) }, { k: 'eff', l: 'Efficiency', fmt: v => N(v, 0) }, { k: 'opp', l: 'Opportunity', fmt: v => N(v, 0) }, { k: 'di', l: 'ZIP index', fmt: v => N(v, 0) }, { k: 'div', l: 'Div /yr', fmt: v => N(v, 0) }, { k: 'priv', l: 'Private /yr', fmt: v => N(v, 0) }, { k: 'rate', l: 'Div /1k married', fmt: v => N(v, 1) }, { k: 'haz', l: 'Hazard', fmt: v => N(v, 1) }, { k: 'sep', l: 'Sep /1k', fmt: v => N(v, 0) }, { k: 'married', l: 'Married', fmt: v => N(v) }, { k: 'inc', l: 'Med income', fmt: v => $$$(v) }, { k: 'inc150', l: '>$150k', fmt: v => P(v, 0) }, { k: 'kids', l: 'MC w/ kids', fmt: v => P(v, 0) }, { k: 'offices', l: 'Offices', fmt: v => N(v) }, { k: 'gt', l: 'Criterion', fmt: v => esc(v) }];
    const rows = () => zs().map(z => ({ _id: z.zip, zip: z.zip, city: z.city, county: z.county_name, eff: z.paid.eff_pct, opp: z.paid.opp_pct, di: z.di, div: z.alloc.div, priv: z.alloc.priv, rate: z.exp_div_per_1k_married, haz: z.risk.haz_pred, sep: z.acs.sep_per_1k_married, married: z.acs.married, inc: z.acs.med_hh_inc, inc150: z.acs.inc_150k_sh, kids: z.acs.mc_kids_sh, offices: z.lawoffices, gt: z.gt }));
    const tbl = table($('#pdTable'), { cols, rows: rows(), sort: { k: 'eff', dir: -1 }, onRow: id => { st.sel = id; markSel(mapEl, id); zipBox(); } });
    $('#pdMetro').onchange = e => { st.metro = e.target.value; store.set('sev.metro', st.metro); st.sel = null; draw(); zipBox(); };
    $('#pdLayer').onchange = e => { st.layer = e.target.value; draw(); };
    $('#pdN').onchange = e => { st.n = clamp(+e.target.value || 25, 5, 200); shortlist(); };
    $('#pdLine').onchange = e => { st.line = e.target.value; st.fee = LINE_META[st.line].fee; $('#pdFee').value = st.fee; calc(); };
    ['pdBudget', 'pdCpc', 'pdCvr', 'pdRet', 'pdFee'].forEach(id => $('#' + id).oninput = () => { st.budget = +$('#pdBudget').value || 0; st.cpc = +$('#pdCpc').value || 1; st.cvr = +$('#pdCvr').value || 0; st.retain = +$('#pdRet').value || 0; st.fee = +$('#pdFee').value || 0; calc(); });
    st.fee = LINE_META[st.line].fee;
    $('#pdGoogle').onclick = () => { const s = short(); exportText('google_ads_locations_' + st.metro + '.csv', csv(s.map(z => ({ Location: z.zip + ', Texas, United States', ID: z.gt || '', Type: 'Postal Code', 'Bid adjustment': (z.paid.eff_pct >= 80 ? '+20%' : z.paid.eff_pct >= 60 ? '+10%' : '0%'), County: z.county_name, City: z.city, 'Expected divorce filings': Math.round(z.alloc.div || 0) })), ['Location', 'ID', 'Type', 'Bid adjustment', 'County', 'City', 'Expected divorce filings'].map(k => ({ l: k, k })))); };
    $('#pdMeta').onclick = () => { const s = short(); exportText('meta_zips_' + st.metro + '.txt', s.map(z => z.zip).join('\n'), 'text/plain'); };
    $('#pdAll').onclick = () => exportText('severance_zips_' + st.metro + '.csv', csv(rows(), cols.map(c => ({ l: c.l, k: c.k }))));
    draw(); zipBox();
  }
});
