'use strict';
/* Module 07: Paid Acquisition */
const ZIP_LAYERS = {
  eff: { l: 'Efficiency percentile (expected filings per competing law office)', ramp: 'ember', v: z => z.paid.eff_pct, f: v => N(v, 0), q: false },
  opp: { l: 'Opportunity percentile (expected private family filings)', ramp: 'ember', v: z => z.paid.opp_pct, f: v => N(v, 0), q: false },
  di: { l: 'ZIP Dissolution Index (composition, separation, shock, structure, strain, supply)', ramp: 'ember', v: z => z.di, f: v => N(v, 0), q: false },
  div: { l: 'Expected divorce filings a year (allocated from county filings)', ramp: 'ember', v: z => z.alloc.div, f: v => N(v, 0), log: true },
  priv: { l: 'Expected private family law filings a year', ramp: 'ember', v: z => z.alloc.priv, f: v => N(v, 0), log: true },
  rate: { l: 'Expected divorce filings per 1,000 married', ramp: 'ember', v: z => z.exp_div_per_1k_married, f: v => N(v, 1) },
  haz: { l: 'Composition hazard per 1,000 married (PUMS)', ramp: 'ember', v: z => z.risk.haz_pred, f: v => N(v, 1) },
  sep: { l: 'Separated per 1,000 married (ACS)', ramp: 'ember', v: z => z.acs.sep_per_1k_married, f: v => N(v, 0) },
  inc: { l: 'Median household income', ramp: 'moss', v: z => z.acs.med_hh_inc, f: v => $$$(v) },
  inc150: { l: 'Households over $150,000 (share)', ramp: 'moss', v: z => z.acs.inc_150k_sh, f: v => P(v, 0) },
  kids: { l: 'Married couple families with children (share)', ramp: 'amber', v: z => z.acs.mc_kids_sh, f: v => P(v, 0) },
  cohab: { l: 'Cohabiting couples with children (share of couples with kids)', ramp: 'amber', v: z => z.acs.cohab_kids_sh, f: v => P(v, 0) },
  offices: { l: 'Law offices in the ZIP (ZIP Business Patterns 2023)', ramp: 'slate', v: z => z.lawoffices, f: v => N(v), log: true, zero: z => !z.lawoffices, zeroLabel: 'no law office (ZBP 2023)' },
  rent: { l: 'Renters (share of households)', ramp: 'amber', v: z => z.acs.renter_sh, f: v => P(v, 0) },
  mil: { l: 'Active duty exposure among married (PUMS)', ramp: 'amber', v: z => z.risk.mil_active, f: v => P(v, 1) },
  m55: { l: 'Married 55 and over (share of married)', ramp: 'slate', v: z => z.acs.mar_55p_sh, f: v => P(v, 0) }
};
// the shortlist's ranking, kept apart from the map layer (which only colors the map); every key ranks high to low
const PD_RANK = {
  eff: { l: 'Efficiency percentile', h: 'Efficiency', v: z => z.paid ? z.paid.eff_pct : null, f: v => N(v, 0) },
  opp: { l: 'Opportunity percentile', h: 'Opportunity', v: z => z.paid ? z.paid.opp_pct : null, f: v => N(v, 0) },
  div: { l: 'Expected divorce filings a year', h: 'Div /yr', v: z => z.alloc.div, f: v => N(v, 0) },
  priv: { l: 'Expected private family filings a year', h: 'Private /yr', v: z => z.alloc.priv, f: v => N(v, 0) },
  di: { l: 'ZIP Dissolution Index', h: 'ZIP index', v: z => z.di, f: v => N(v, 0) }
};
// a county whose clerk reported no filings for months (module 01 calls it a reporting gap) gives its ZIPs near zero expected filings
const zipGapNote = z => { const c = CI[z.county]; const g = c && repGap(c); return g ? `<div class="small">${esc(c.name)} County's clerk reported no divorce filings for the last ${g.months} months, so its expected filings read low.</div>` : ''; };
function zipTipHTML(z, extra) { return `<b>${esc(z.zip)} · ${esc(z.city || '')}</b><div class="row"><span>${esc(z.county_name)} County</span><span>${esc(z.msa && MSA[z.msa] ? MNAME(MSA[z.msa].title) : '')}</span></div><div class="row"><span>Expected divorce filings / yr</span><span>${N(z.alloc.div, 0)}</span></div><div class="row"><span>Private family filings / yr</span><span>${N(z.alloc.priv, 0)}</span></div><div class="row"><span>Law offices</span><span>${z.lawoffices ? N(z.lawoffices) : 'none'}</span></div><div class="row"><span>Efficiency pct</span><span>${N(z.paid.eff_pct, 0)}</span></div><div class="row"><span>ZIP index</span><span>${N(z.di, 0)}</span></div>${extra || ''}${zipGapNote(z)}`; }
// the ZIP table columns (Paid Acquisition); h, d and pct are the export header, decimals and percent flag
function ZIP_COLS() { return [{ k: 'zip', l: 'ZIP', fmt: v => esc(v) }, { k: 'city', l: 'City', fmt: v => esc(v), cls: 'l' }, { k: 'county', l: 'County', fmt: v => esc(v), cls: 'l' }, { k: 'eff', l: 'Efficiency', fmt: v => N(v, 0), h: 'Efficiency percentile (filings per competing law office)', d: 0 }, { k: 'opp', l: 'Opportunity', fmt: v => N(v, 0), h: 'Opportunity percentile (expected private family filings)', d: 0 }, { k: 'di', l: 'ZIP index', fmt: v => N(v, 0), h: 'ZIP Dissolution Index', d: 0 }, { k: 'div', l: 'Div /yr', fmt: v => N(v, 0), h: 'Expected divorce filings a year', d: 0 }, { k: 'priv', l: 'Private /yr', fmt: v => N(v, 0), h: 'Expected private family filings a year', d: 0 }, { k: 'rate', l: 'Div /1k married', fmt: v => N(v, 1), h: 'Expected divorce filings per 1,000 married', d: 1 }, { k: 'haz', l: 'Hazard', fmt: v => N(v, 1), h: 'Composition hazard per 1,000 married (model)', d: 1 }, { k: 'sep', l: 'Sep /1k', fmt: v => N(v, 0), h: 'Separated per 1,000 married (ACS)', d: 0 }, { k: 'married', l: 'Married', fmt: v => N(v), h: 'Married adults (ACS)', d: 0 }, { k: 'inc', l: 'Med income', fmt: v => $$$(v), h: 'Median household income ($)', d: 0 }, { k: 'inc150', l: '>$150k', fmt: v => P(v, 0), h: 'Households over $150,000 (%)', d: 0, pct: true }, { k: 'kids', l: 'MC w/ kids', fmt: v => P(v, 0), h: 'Married couple families with children (%)', d: 0, pct: true }, { k: 'offices', l: 'Offices', fmt: v => N(v), h: 'Law offices in the ZIP (ZBP 2023)', d: 0 }, { k: 'gt', l: 'Criterion', fmt: v => esc(v), h: 'Google Ads location ID' }]; }
function drawZipMap(el, codes, L, st, onSel) {
  const code0 = codes[0]; const M = GEO.metros[code0];
  // for RGV two metros: merge geometry by re-projecting is not possible; show first metro and second below via separate maps. Handled by caller.
  const zs = metroZctas([code0]); const sc = layerScale(L, zs);
  const zi = {}; zs.forEach(z => zi[z.zip] = z);
  // a layer with a true zero (law offices) gives zero its own swatch instead of the lowest step
  const isZero = id => !!(L.zero && zi[id] && L.zero(zi[id])); const alt = L.zero ? { test: isZero, color: 'var(--alt-fill)', label: L.zeroLabel || 'none' } : null;
  drawMap(el, { title: L.l, W: M.W, H: M.H, paths: M.zcta, value: id => zi[id] && !isZero(id) ? L.v(zi[id]) : null, color: sc.color, alt, label: id => zi[id] ? zipTipHTML(zi[id], `<div class="row"><span>${esc(L.l)}</span><span>${isZero(id) ? esc(L.zeroLabel || 'none') : esc(L.f(L.v(zi[id])))}</span></div>`) : `<b>${esc(id)}</b><div class="small">Under 200 residents: no estimates for this ZIP.</div>`, onSelect: onSel, selected: st.sel, counties: M.county, cent: M.ccent, labels: Object.keys(M.county), labelText: id => CI[id].name, legend: Object.assign({ title: L.l }, sc.legend), noDataLabel: 'under 200 residents' });
}
registerModule({
  key: 'paid', num: '07', title: 'Paid Acquisition', desc: 'Where an ad dollar reaches the most filings per competing firm, resolved to the ZIP code, with a budget model and export lists',
  mount(root) {
    // the budget model's inputs, line, layer and shortlist size persist in sev.paid
    const SV = store.get('sev.paid', null) || {};
    const st = { metro: store.get('sev.metro', '19100'), layer: ZIP_LAYERS[SV.layer] ? SV.layer : 'eff', rank: PD_RANK[SV.rank] ? SV.rank : 'eff', sel: null, line: LINE_META[SV.line] ? SV.line : 'div_k', n: clamp(Math.round(+SV.n) || 25, 5, 200), cpc: 9.87, cvr: 5.55, retain: 22, budget: 10000 };
    if (!MSA[st.metro]) st.metro = '19100';
    const savePaid = () => store.set('sev.paid', { line: st.line, layer: st.layer, rank: st.rank, n: st.n, budget: st.budget, cpc: st.cpc, cvr: st.cvr, retain: st.retain, fee: st.fee });
    const metroOpts = Object.keys(MSA).sort((a, b) => MSA[b].pop2025 - MSA[a].pop2025).map(k => [k, MNAME(MSA[k].title)]);
    root.innerHTML = mastHTML({ eyebrow: 'Module 07 · Paid Acquisition · 1,127 metropolitan ZIP codes', title: 'Paid Acquisition', dek: `County filings allocated to ZIP codes by each ZIP's married population and its composition hazard, then set against the law offices already in the ZIP. Efficiency is filings per competing office; opportunity is raw filings. Both are percentiles across all metro ZIPs, so a ZIP scoring 90 on efficiency is in the top tenth statewide. The budget model below uses the 2026 legal search benchmarks and the fee defaults from module 06; change any assumption and the math follows.`, facts: [[N(ZC.length), 'ZIP codes across 26 metros'], ['$9.87', 'median legal services CPC, Google search, Apr 2025 to Mar 2026 (WordStream)'], ['5.55%', 'median legal conversion rate; family law 8.52% in the 2023 LocaliQ cut'], ['$131.63', 'median legal cost per lead']] }) + `
    <div class="toolbar"><span class="ttl">Paid Acquisition</span><span class="sub">ZIP maps, ranked lists, budget model, exports</span><span class="sp"></span><button class="btn" id="pdGoogle">↓ Google Ads location CSV</button><button class="btn" id="pdMeta">↓ Meta ZIP CSV</button><button class="btn" id="pdAll">↓ All ZIPs CSV</button><button class="btn" id="pdAsm">↓ Assumptions JSON</button><button class="btn" id="pdDesk">Send shortlist to Campaign Desk ↗</button></div><p class="small" id="pdExpMsg" role="status" aria-live="polite" style="margin:-8px 0 12px"></p>
    <div class="callout note"><div class="h">Read this first: what the ZIP numbers can and cannot say</div><p>The Office of Court Administration reports filings by county, not ZIP, so ZIP filings are an allocation: the county's filings spread across its ZIPs in proportion to married adults times the modeled hazard. That captures where the married people are and how divorce prone they are by composition; it cannot see a neighborhood that is unusually unhappy. Law office counts come from ZIP Business Patterns and include every kind of law office, so downtown ZIPs with corporate firms look more competitive than they are for family law. Use efficiency to shortlist and the county filing rate (module 01) to size.</p></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Metro', sel('pdMetro', metroOpts, st.metro))}${ctl('Map layer', sel('pdLayer', Object.keys(ZIP_LAYERS).map(k => [k, ZIP_LAYERS[k].l]), st.layer))}${ctl('Shortlist size', '<input type="number" id="pdN" value="25" min="5" max="200" step="1" inputmode="numeric" style="width:80px">')}</div><div class="split"><div class="mapwrap" id="pdMap"></div><div><h3 style="font-family:var(--display);font-size:20px" id="pdMetroTitle"></h3><div id="pdMetroBody" class="small"></div><h3 style="font-family:var(--display);font-size:20px;margin-top:12px">Selected ZIP</h3><div id="pdZip" class="small"></div></div></div></div>
    <div class="grid2"><div class="panel"><h3>Budget model</h3><div class="sub">Monthly search budget through to retained matters and revenue, against the expected filings in the shortlisted ZIPs.</div><div class="controls">${ctl('Service line', sel('pdLine', Object.keys(LINE_META).map(k => [k, LINE_META[k].name]), st.line))}${ctl('Monthly budget $', '<input type="number" id="pdBudget" value="10000" min="0" step="500" inputmode="decimal" aria-describedby="pdHint" style="width:100px">')}${ctl('CPC $', '<input type="number" id="pdCpc" value="9.87" min="0" step="0.25" inputmode="decimal" aria-describedby="pdHint" style="width:80px">')}${ctl('Conversion %', '<input type="number" id="pdCvr" value="5.55" min="0" max="100" step="0.05" inputmode="decimal" aria-describedby="pdHint" style="width:80px">')}${ctl('Lead to retained %', '<input type="number" id="pdRet" value="22" min="0" max="100" step="1" inputmode="decimal" aria-describedby="pdHint" style="width:80px">')}${ctl('Value per matter $', '<input type="number" id="pdFee" value="9500" min="0" step="500" inputmode="decimal" aria-describedby="pdHint" style="width:100px">')}</div><div class="hintbad" id="pdHint" role="status" aria-live="polite"></div><p class="small" style="margin:0 0 8px">Defaults: a $9.87 CPC and 5.55% conversion are the legal medians in the facts above (family law converted at 8.52% in the 2023 LocaliQ cut); lead to retained (22%) and the value per matter (module 06 by line) are assumptions to replace with the firm's own numbers.</p><div class="tiles" id="pdCalc"></div><p class="small">Share of market compares retained matters a year with the expected filings for the chosen line in the shortlisted ZIPs (the divorce lines use divorce filings, custody uses SAPCR, protective orders their own filings, modification and enforcement theirs; the estimated lines use the county scaling from module 06).</p></div>
    <div class="panel"><h3>Shortlist</h3><div class="controls" style="margin-bottom:6px">${ctl('Rank the shortlist by', sel('pdRank', Object.keys(PD_RANK).map(k => [k, PD_RANK[k].l]), st.rank))}</div><div class="sub" id="pdShortSub"></div><div id="pdShort"></div></div></div>
    <div class="panel"><h3>All ZIPs in the metro</h3><div id="pdTable"></div></div>`;
    const mapEl = $('#pdMap');
    function zs() { return metroZctas([st.metro]); }
    function pick(id) { st.sel = id; markSel(mapEl, id); zipBox(); if (tbl) tbl.setSel(id); }
    function draw() { const L = ZIP_LAYERS[st.layer]; drawZipMap(mapEl, [st.metro], L, st, pick); const m = MSA[st.metro]; $('#pdMetroTitle').textContent = MNAME(m.title); $('#pdMetroBody').innerHTML = `<dl class="kv"><dt>Population 2025</dt><dd>${N(m.pop2025)}</dd><dt>Married adults</dt><dd>${N(m.married)}</dd><dt>Divorce filings, 12 mo</dt><dd>${N(m.ttm.div)} (${sgn((m.ttm.div / (m.prev.div || 1) - 1) * 100)})</dd><dt>per 1,000 married</dt><dd>${N(m.div_per_1k_married, 1)}</dd><dt>Private family filings</dt><dd>${N(m.ttm.priv)}</dd><dt>Law offices</dt><dd>${N(m.lawoffices)}</dd><dt>Shock index (pop weighted)</dt><dd>${N(m.esi, 0)}</dd><dt>ZIPs mapped</dt><dd>${N(m.zctas)}</dd></dl>`; shortlist(); tbl.setRows(rows()); }
    function zipBox() { const z = ZI[st.sel]; if (!z) { $('#pdZip').innerHTML = st.sel ? `<span class="small"><b>${esc(st.sel)}</b>: under 200 residents, so no estimates for this ZIP.</span>` : '<span class="small">Click a ZIP on the map.</span>'; return; } const a = z.acs, r = z.risk; $('#pdZip').innerHTML = `<b>${esc(z.zip)} ${esc(z.city)}</b>, ${esc(z.county_name)} County · Google criterion ${esc(z.gt || NA)}<dl class="kv" style="margin-top:4px"><dt>Population</dt><dd>${N(a.pop)}</dd><dt>Married adults</dt><dd>${N(a.married)}</dd><dt>Expected divorce filings / yr</dt><dd>${N(z.alloc.div, 0)}</dd><dt>Expected SAPCR</dt><dd>${N(z.alloc.sapcr, 0)}</dd><dt>Expected protective orders</dt><dd>${N(z.alloc.po, 0)}</dd><dt>Expected modifications + enforcement</dt><dd>${N((z.alloc.mod || 0) + (z.alloc.enf || 0), 0)}</dd><dt>Composition hazard /1k</dt><dd>${N(r.haz_pred, 1)}</dd><dt>Separated /1k married</dt><dd>${N(a.sep_per_1k_married, 0)}</dd><dt>Married couple families with children (share)</dt><dd>${P(a.mc_kids_sh, 0)}</dd><dt>Couples with children who cohabit (share)</dt><dd>${P(a.cohab_kids_sh, 0)}</dd><dt>Median HH income</dt><dd>${$$$(a.med_hh_inc)}</dd><dt>Over $150k</dt><dd>${P(a.inc_150k_sh, 0)}</dd><dt>Renters</dt><dd>${P(a.renter_sh, 0)}</dd><dt>Rent burden 35%+</dt><dd>${P(a.rent_burden35_sh, 0)}</dd><dt>Law offices</dt><dd>${z.lawoffices ? N(z.lawoffices) : 'none (ZBP 2023)'}</dd><dt>Efficiency / opportunity pct</dt><dd>${N(z.paid.eff_pct, 0)} / ${N(z.paid.opp_pct, 0)}</dd><dt>ZIP index</dt><dd>${N(z.di, 0)}</dd></dl>${zipGapNote(z)}`; }
    function short() { const R = PD_RANK[st.rank]; return zs().filter(z => isN(R.v(z))).sort((a, b) => R.v(b) - R.v(a) || a.zip.localeCompare(b.zip)).slice(0, st.n); }
    function lineKey() { return { div_k: 'div', div_nk: 'div', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', high: 'div', mil: 'div', gray: 'div', prenup: 'div', adopt: 'div', cps: 'div' }[st.line]; }
    function shortlist() { const s = short(); const R = PD_RANK[st.rank]; const none = s.filter(z => !z.lawoffices).length; $('#pdShortSub').textContent = `The top ${s.length} ZIPs in the metro by ${R.l.toLowerCase().replace('zip', 'ZIP')}, high to low. The budget model and the Google, Meta and Campaign Desk exports carry these rows; the map layer above only colors the map.`; $('#pdShort').innerHTML = `<div class="tblbox"><div class="tblwrap" style="max-height:360px"><table class="t"><caption class="vh">Shortlisted ZIP codes, ranked by ${esc(R.l)}</caption><thead><tr><th scope="col">ZIP</th><th scope="col" class="l">City</th><th scope="col" class="l">County</th><th scope="col">${esc(R.h)}</th><th scope="col">Div/yr</th><th scope="col">Offices</th><th scope="col">Criterion</th></tr></thead><tbody>${s.map(z => `<tr><td class="name"><button type="button" class="linkbtn" data-id="${esc(z.zip)}">${esc(z.zip)}</button></td><td class="l">${esc(z.city)}</td><td class="l">${esc(z.county_name)}</td><td>${esc(R.f(R.v(z)))}</td><td>${N(z.alloc.div, 0)}</td><td>${z.lawoffices ? N(z.lawoffices) : '<span class="small">none</span>'}</td><td>${esc(z.gt || '')}</td></tr>`).join('')}</tbody></table></div></div>${none ? `<p class="small" style="margin-top:6px">${none} of these ${s.length} ZIPs have no law office in the ZIP Business Patterns count, which is what lifts their efficiency; families there use offices in nearby ZIPs, so check the drive to the firm before bidding them up.</p>` : ''}`; $$('#pdShort .linkbtn').forEach(td => td.onclick = () => pick(td.dataset.id)); calc(); }
    function calc() { const s = short(); const k = lineKey(); const Lm = LINE_META[st.line]; let expected = sum(s.map(z => z.alloc[k] || 0)); if (['high', 'mil', 'gray', 'prenup', 'adopt', 'cps', 'div_k', 'div_nk'].includes(st.line)) { const ctyF = {}; s.forEach(z => { ctyF[z.county] = ctyF[z.county] || 0; ctyF[z.county] += z.alloc_share; }); expected = sum(Object.keys(ctyF).map(f => (Lm.cnt(CI[f]) || 0) * ctyF[f])); }
      // a CPC of 0 has no click count, and 0 leads or 0 matters have no cost per lead or per matter: those read n/a, never a stand in value
      const clicks = st.cpc > 0 ? st.budget / st.cpc : null; const leads = isN(clicks) ? clicks * st.cvr / 100 : null; const ret = isN(leads) ? leads * st.retain / 100 : null; const rev = isN(ret) ? ret * st.fee : null;
      const cpl = leads > 0 ? st.budget / leads : null; const cpa = ret > 0 ? st.budget / ret : null;
      $('#pdCalc').innerHTML = tile('Clicks / month', N(clicks), st.cpc > 0 ? 'at ' + $$$(st.cpc, 2) + ' CPC' : 'enter a CPC above $0') + tile('Leads / month', N(leads, 1), 'at ' + N(st.cvr, 1) + '% conversion · ' + (isN(cpl) ? $$$(cpl) + ' per lead' : 'no cost per lead without leads')) + tile('Retained / month', N(ret, 1), 'at ' + N(st.retain, 0) + '% lead to retained · ' + (isN(cpa) ? $$$(cpa) + ' per matter' : 'no cost per matter without matters')) + tile('Revenue / month', $$$(rev), 'at ' + $$$(st.fee) + ' per ' + Lm.lcs + ' matter' + (isN(rev) && st.budget > 0 ? ' · ' + N(rev / st.budget, 1) + '× return' : '')) + tile('Expected filings / yr', N(expected, 0), Lm.name + ' in the ' + s.length + ' shortlisted ZIPs') + tile('Share of market', isN(ret) && expected > 0 ? P(ret * 12 / expected, 1) : NA, 'retained matters a year against expected filings'); }
    const cols = ZIP_COLS();
    const rows = () => zs().map(z => ({ _id: z.zip, zip: z.zip, city: z.city, county: z.county_name, eff: z.paid.eff_pct, opp: z.paid.opp_pct, di: z.di, div: z.alloc.div, priv: z.alloc.priv, rate: z.exp_div_per_1k_married, haz: z.risk.haz_pred, sep: z.acs.sep_per_1k_married, married: z.acs.married, inc: z.acs.med_hh_inc, inc150: z.acs.inc_150k_sh, kids: z.acs.mc_kids_sh, offices: z.lawoffices, gt: z.gt }));
    let tbl = null; tbl = table($('#pdTable'), { caption: 'All ZIP codes in the metro', cols, rows: rows(), sort: { k: 'eff', dir: -1 }, onRow: pick });
    function setMetro(code) { if (!MSA[code]) return; st.metro = code; store.set('sev.metro', code); $('#pdMetro').value = code; st.sel = null; draw(); zipBox(); }
    $('#pdMetro').onchange = e => setMetro(e.target.value);
    $('#pdRank').onchange = e => { st.rank = PD_RANK[e.target.value] ? e.target.value : 'eff'; savePaid(); shortlist(); };
    $('#pdLayer').onchange = e => { st.layer = e.target.value; savePaid(); draw(); };
    $('#pdN').onchange = e => { st.n = clamp(Math.round(+e.target.value) || 25, 5, 200); e.target.value = st.n; savePaid(); shortlist(); };
    $('#pdLine').onchange = e => { st.line = e.target.value; st.fee = LINE_META[st.line].fee; $('#pdFee').value = st.fee; readInputs(); calc(); };
    // inputs: blank or out of range is flagged and clamped (0 and up; percents 0 to 100); the tiles say n/a where a figure has no meaning
    const PD_IN = { pdBudget: ['budget', 0, 1e8, 'The monthly budget'], pdCpc: ['cpc', 0, 1e4, 'The CPC'], pdCvr: ['cvr', 0, 100, 'The conversion rate'], pdRet: ['retain', 0, 100, 'Lead to retained'], pdFee: ['fee', 0, 1e8, 'The value per matter'] };
    function readInputs() {
      const msgs = [];
      Object.keys(PD_IN).forEach(id => { const [k, lo, hi, nm] = PD_IN[id]; const el = $('#' + id); const raw = String(el.value).trim(); const v = raw === '' ? NaN : +raw; const bad = !isFinite(v) || v < lo || v > hi; st[k] = isFinite(v) ? clamp(v, lo, hi) : 0; el.setAttribute('aria-invalid', String(bad)); if (bad) msgs.push(!isFinite(v) ? `${nm} is empty, so it counts as 0.` : v < lo ? `${nm} cannot be below ${lo}; it counts as ${lo}.` : `${nm} cannot be above ${N(hi)}; it counts as ${N(hi)}.`); });
      if (!(st.cpc > 0)) { $('#pdCpc').setAttribute('aria-invalid', 'true'); if (!msgs.some(m => /CPC/.test(m))) msgs.push('A CPC of $0 gives no click count; enter the cost per click you expect.'); }
      if (st.cpc > 0 && !(st.cvr > 0)) msgs.push('A conversion rate of 0% gives no leads, so cost per lead reads n/a.');
      $('#pdHint').textContent = msgs.join(' ');
      savePaid();
    }
    ['pdBudget', 'pdCpc', 'pdCvr', 'pdRet', 'pdFee'].forEach(id => $('#' + id).oninput = () => { readInputs(); calc(); });
    // restore the saved inputs (the fee follows the line unless one was saved)
    $('#pdN').value = st.n; ['budget', 'cpc', 'cvr', 'retain'].forEach(k => { if (isN(SV[k])) $('#' + { budget: 'pdBudget', cpc: 'pdCpc', cvr: 'pdCvr', retain: 'pdRet' }[k]).value = SV[k]; });
    $('#pdFee').value = isN(SV.fee) && SV.line === st.line ? SV.fee : LINE_META[st.line].fee;
    const geo = () => MNAME(MSA[st.metro].title);
    // bid steps from efficiency (the Campaign Desk uses the same steps); the campaign name follows the Thermal Atlas pattern <METRO>_<LINE>_SEARCH
    const bidOf = z => z.paid && z.paid.eff_pct >= 80 ? 20 : z.paid && z.paid.eff_pct >= 60 ? 10 : 0;
    const campName = () => (DK_TAB_OF(st.metro) + '_' + st.line.toUpperCase() + '_SEARCH');
    const noIdMsg = s => { const miss = s.filter(z => !z.gt).map(z => z.zip); $('#pdExpMsg').textContent = miss.length ? `${miss.length} of these ZIPs (${miss.join(', ')}) have no Google criterion ID in the August 2026 geotargets file; the Location text lets Ads Editor match them by name, so check them after the import.` : ''; };
    // the ZIP count the line has: its own allocation where the courts report the line, all divorce filings for the estimated lines
    const zipExp = z => { const al = z.alloc || {}; const own = { div_k: al.div_k, div_nk: isN(al.div) && isN(al.div_k) ? al.div - al.div_k : null, sapcr: al.sapcr, po: al.po, mod: al.mod, enf: al.enf, ivd: al.ivd }; return st.line in own ? own[st.line] : al.div; };
    const zipExpL = () => ['div_k', 'div_nk', 'sapcr', 'po', 'mod', 'enf', 'ivd'].includes(st.line) ? `Expected ${LINE_META[st.line].lc} filings a year` : `Expected divorce filings a year (all divorce; no ZIP count for ${LINE_META[st.line].lc})`;
    $('#pdGoogle').onclick = () => { const s = short(); noIdMsg(s); exportText(expName('paid_google_locations', geo()), csv(s.map(z => ({ camp: campName(), loc: z.zip + ', Texas, United States', id: z.gt || '', bid: (bidOf(z) > 0 ? '+' : '') + bidOf(z) + '%', type: 'Location', status: 'Enabled', county: z.county_name, city: z.city, exp: zipExp(z) })), [{ l: 'Campaign', k: 'camp' }, { l: 'Location', k: 'loc' }, { l: 'ID', k: 'id' }, { l: 'Bid Modifier', k: 'bid' }, { l: 'Criterion Type', k: 'type' }, { l: 'Status', k: 'status' }, { l: 'County', k: 'county' }, { l: 'City', k: 'city' }, { l: zipExpL(), k: 'exp', d: 0 }])); };
    $('#pdMeta').onclick = () => { const s = short(); const R = PD_RANK[st.rank]; exportText(expName('paid_meta_zips', geo()), toCSV(['Zip', 'zip', 'city', 'county', 'rank_by', 'rank_value', 'expected_divorce_filings'], s.map(z => ['US:' + z.zip, z.zip, z.city, z.county_name, R.l, Math.round(R.v(z)), Math.round(z.alloc.div || 0)]), `Meta ad set ZIP list for ${LINE_META[st.line].name}, ${geo()}: the top ${s.length} ZIPs by ${R.l.toLowerCase()}. Paste the Zip column into the ad set's locations. Write the ads to the situation in the third person: Meta rejects ad text that asserts or implies the viewer's own situation (module 11 screens for it).`)); };
    $('#pdDesk').onclick = () => { const s = short(); const bids = {}; s.forEach(z => { bids[z.zip] = bidOf(z); }); goModule('desk', { geo: 'msa:' + st.metro, zips: s.map(z => z.zip), line: st.line, bids }); };
    $('#pdAsm').onclick = () => exportText(expName('paid_assumptions', geo(), 'json'), JSON.stringify({ module: 'Paid Acquisition (07)', exported: todayISO(), metro: { code: st.metro, name: geo() }, line: { key: st.line, name: LINE_META[st.line].name }, shortlist: { rank_by: PD_RANK[st.rank].l, size: st.n, zips: short().map(z => z.zip) }, inputs: { monthly_budget: st.budget, cpc: st.cpc, conversion_pct: st.cvr, lead_to_retained_pct: st.retain, value_per_matter: st.fee }, sources: { cpc: 'median legal services CPC, Google search, Apr 2025 to Mar 2026 (WordStream)', conversion: 'median legal conversion 5.55%; family law 8.52% in the 2023 LocaliQ cut', lead_to_retained: 'assumption', value_per_matter: 'module 06 default for the line unless changed', filings: 'county filings (Texas OCA, ' + ttmSpan() + ') allocated to ZIPs by married adults times the modeled hazard' } }, null, 2), 'application/json');
    $('#pdAll').onclick = () => exportText(expName('paid_zips', geo()), csv(tbl.sorted(), xcols(cols)));
    readInputs(); draw(); zipBox();
    // goModule('paid', {metro, zip, line}): the metro tabs and the index hand over their metro
    this.receive = p => { if (!p) return; if (p.metro && MSA[p.metro] && p.metro !== st.metro) setMetro(p.metro); if (p.line && LINE_META[p.line] && p.line !== st.line) { st.line = p.line; $('#pdLine').value = st.line; st.fee = LINE_META[st.line].fee; $('#pdFee').value = st.fee; readInputs(); calc(); } if (p.zip && ZI[p.zip] && ZI[p.zip].msa === st.metro) pick(p.zip); };
  }
});
// a metro's short campaign code: the six big metros by their usual letters, the rest by their first city
function DK_TAB_OF(code) { const k = { '19100': 'DFW', '26420': 'HOU', '41700': 'SAT', '12420': 'AUS', '21340': 'ELP', '32580': 'RGV', '15180': 'RGV' }[code]; return k || (MNAME((MSA[code] || {}).title || 'TX').split(' / ')[0].toUpperCase().replace(/[^A-Z0-9]+/g, '').slice(0, 10) || 'TX'); }
