'use strict';
/* Module 07: Paid Acquisition. The computed layers come from FLM.compute(metro) (src/14_model_core.js): matter mass with payer weights,
   the fee value index, competition, the click cost index, opportunity and efficiency (radius blended), the quadrant and the tiers with
   their bids. The economics read SEV_MODEL, so Accounts actuals and the Service Lines editor reach this module. ZIP_LAYERS, drawZipMap
   and zipTipHTML are shared with the metro tabs (module 12). */
const pdRow = z => { const C = z && z.msa ? FLM.compute(z.msa) : null; return C ? C.by[z.zip] || null : null; };
const pdV = k => z => { const r = pdRow(z); return r && isN(r[k]) ? r[k] : null; };
const ZIP_LAYERS = {
  effb: { l: 'Efficiency percentile (fee pool per click cost, radius blended)', ramp: 'ember', v: pdV('effb'), f: v => N(v, 0), q: false, g: 'C' },
  oppb: { l: 'Opportunity percentile (fee pool, radius blended)', ramp: 'ember', v: pdV('oppb'), f: v => N(v, 0), q: false, g: 'C' },
  opp_usd: { l: 'Fee pool a year ($, payer weighted, at 100% share)', ramp: 'ember', v: pdV('opp'), f: v => $$$(v), g: 'C' },
  mass: { l: 'Matter mass (payer weighted fee paying matters a year)', ramp: 'ember', v: pdV('mass'), f: v => N(v, 1), g: 'B' },
  fvi: { l: 'Fee value index (100 = the metro median household income)', ramp: 'moss', v: z => { const r = pdRow(z); return r ? r.fvi * 100 : null; }, f: v => N(v, 0), g: 'C' },
  comp: { l: 'Competition percentile (law offices per 1,000 married nearby)', ramp: 'slate', v: pdV('comp_pct'), f: v => N(v, 0), q: false, g: 'C' },
  cpc_rel: { l: 'Click cost index (times a flat CPC)', ramp: 'slate', v: pdV('cpc_rel'), f: v => N(v, 2) + '×', g: 'D' },
  eff: { l: 'Filings per law office in the ZIP (percentile, statewide)', ramp: 'ember', v: z => z.paid.eff_pct, f: v => N(v, 0), q: false, g: 'C' },
  opp: { l: 'Expected private family filings (percentile, statewide)', ramp: 'ember', v: z => z.paid.opp_pct, f: v => N(v, 0), q: false, g: 'B' },
  di: { l: 'ZIP Dissolution Index (composition, separation, shock, structure, strain, supply)', ramp: 'ember', v: z => z.di, f: v => N(v, 0), q: false, g: 'C' },
  div: { l: 'Expected divorce filings a year (allocated from county filings)', ramp: 'ember', v: z => z.alloc.div, f: v => N(v, 0), log: true, g: 'B' },
  priv: { l: 'Expected private family law filings a year', ramp: 'ember', v: z => z.alloc.priv, f: v => N(v, 0), log: true, g: 'B' },
  rate: { l: 'Expected divorce filings per 1,000 married', ramp: 'ember', v: z => z.exp_div_per_1k_married, f: v => N(v, 1), g: 'B' },
  haz: { l: 'Composition hazard per 1,000 married (PUMS)', ramp: 'ember', v: z => z.risk.haz_pred, f: v => N(v, 1), g: 'B' },
  sep: { l: 'Separated per 1,000 married (ACS)', ramp: 'ember', v: z => z.acs.sep_per_1k_married, f: v => N(v, 0), g: 'A' },
  inc: { l: 'Median household income', ramp: 'moss', v: z => z.acs.med_hh_inc, f: v => $$$(v), g: 'A' },
  inc150: { l: 'Households over $150,000 (share)', ramp: 'moss', v: z => z.acs.inc_150k_sh, f: v => P(v, 0), g: 'A' },
  kids: { l: 'Married couple families with children (share)', ramp: 'amber', v: z => z.acs.mc_kids_sh, f: v => P(v, 0), g: 'A' },
  cohab: { l: 'Cohabiting couples with children (share of couples with kids)', ramp: 'amber', v: z => z.acs.cohab_kids_sh, f: v => P(v, 0), g: 'A' },
  offices: { l: 'Law offices in the ZIP (ZIP Business Patterns 2023)', ramp: 'slate', v: z => z.lawoffices, f: v => N(v), log: true, zero: z => !z.lawoffices, zeroLabel: 'no law office (ZBP 2023)', g: 'A' },
  rent: { l: 'Renters (share of households)', ramp: 'amber', v: z => z.acs.renter_sh, f: v => P(v, 0), g: 'A' },
  mil: { l: 'Active duty exposure among married (PUMS)', ramp: 'amber', v: z => z.risk.mil_active, f: v => P(v, 1), g: 'B' },
  m55: { l: 'Married 55 and over (share of married)', ramp: 'slate', v: z => z.acs.mar_55p_sh, f: v => P(v, 0), g: 'A' }
};
// the shortlist's ranking, kept apart from the map layer (which only colors the map); every key ranks high to low
const PD_RANK = {
  effb: { l: 'Efficiency percentile', h: 'Efficiency', v: r => r.effb, f: v => N(v, 0) },
  oppb: { l: 'Opportunity percentile', h: 'Opportunity', v: r => r.oppb, f: v => N(v, 0) },
  opp: { l: 'Fee pool a year', h: 'Fee pool', v: r => r.opp, f: v => $$$(v) },
  mass: { l: 'Matter mass', h: 'Mass', v: r => r.mass, f: v => N(v, 1) },
  quick: { l: 'Quick turn matters', h: 'Quick turn', v: r => r.quick, f: v => N(v, 1) },
  div: { l: 'Expected divorce filings a year', h: 'Div /yr', v: r => r.z.alloc.div, f: v => N(v, 0) },
  di: { l: 'ZIP Dissolution Index', h: 'ZIP index', v: r => r.z.di, f: v => N(v, 0) }
};
// a county whose clerk reported no filings for months (module 01 calls it a reporting gap) gives its ZIPs near zero expected filings
const zipGapNote = z => { const c = CI[z.county]; const g = c && repGap(c); return g ? `<div class="small">${esc(c.name)} County's clerk reported no divorce filings for the last ${g.months} months, so its expected filings read low.</div>` : ''; };
function zipTipHTML(z, extra) { const r = pdRow(z); return `<b>${esc(z.zip)} · ${esc(z.city || '')}</b><div class="row"><span>${esc(z.county_name)} County</span><span>${esc(z.msa && MSA[z.msa] ? MNAME(MSA[z.msa].title) : '')}</span></div><div class="row"><span>Expected divorce filings / yr</span><span>${N(z.alloc.div, 0)}</span></div><div class="row"><span>Private family filings / yr</span><span>${N(z.alloc.priv, 0)}</span></div><div class="row"><span>Law offices</span><span>${z.lawoffices ? N(z.lawoffices) : 'none'}</span></div>${r ? `<div class="row"><span>Efficiency · tier</span><span>${N(r.effb, 0)} · ${esc(r.tier)} (${r.bid > 0 ? '+' : ''}${N(r.bid)}%)</span></div><div class="row"><span>Quadrant</span><span>${esc(FLM.QN[r.quad])}</span></div>` : ''}<div class="row"><span>ZIP index</span><span>${N(z.di, 0)}</span></div>${extra || ''}${zipGapNote(z)}`; }
function drawZipMap(el, codes, L, st, onSel) {
  const code0 = codes[0]; const M = GEO.metros[code0];
  const zs = metroZctas([code0]); const sc = layerScale(L, zs);
  const zi = {}; zs.forEach(z => zi[z.zip] = z);
  // a layer with a true zero (law offices) gives zero its own swatch instead of the lowest step
  const isZero = id => !!(L.zero && zi[id] && L.zero(zi[id])); const alt = L.zero ? { test: isZero, color: 'var(--alt-fill)', label: L.zeroLabel || 'none' } : null;
  // st may carry the zoomable map's options (dim, fit, pins, onPin, reset) and a view; the metro tabs pass only {sel}
  const o = { title: L.l, W: M.W, H: M.H, paths: M.zcta, value: id => zi[id] && !isZero(id) ? L.v(zi[id]) : null, color: sc.color, alt, label: id => zi[id] ? zipTipHTML(zi[id], `<div class="row"><span>${esc(L.l)}</span><span>${isZero(id) ? esc(L.zeroLabel || 'none') : esc(L.f(L.v(zi[id])))}</span></div>`) : `<b>${esc(id)}</b><div class="small">Under 200 residents: no estimates for this ZIP.</div>`, onSelect: onSel, selected: st.sel, counties: M.county, cent: M.ccent, labels: Object.keys(M.county), labelText: id => CI[id].name, legend: Object.assign({ title: L.l, grade: L.g }, sc.legend), noDataLabel: 'under 200 residents' };
  ['view', 'dim', 'fit', 'pins', 'onPin', 'reset'].forEach(k => { if (st[k] !== undefined) o[k] = st[k]; });
  return drawMap(el, o);
}
const PD_QC = ['var(--s3)', 'var(--s1)', 'var(--s4)', 'var(--s2)'];   // Anchor, Whitespace, Niche, Avoid
const PD_TC = ['var(--rp-forest-7)', 'var(--rp-forest-6)', 'var(--rp-forest-4)', 'var(--rp-forest-2)', 'var(--rp-slate-3)', 'var(--rp-slate-5)'];
/* competition against opportunity, both percentiles on fixed 0 to 100 axes, with the crosshairs at 60 and 65; a click selects the ZIP */
function pdScatter(el, o) {
  const bx = chartBox(el, o, 560, 330); const W = bx.W, H = bx.H; sizeWatch(el, { fn: pdScatter, o, w: bx.live ? W : 0 });
  const m = { l: 40, r: 12, t: 12, b: 40 }; const X = v => m.l + v / 100 * (W - m.l - m.r), Y = v => m.t + (1 - v / 100) * (H - m.t - m.b);
  const svg = [`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(o.title)}">`];
  [0, 25, 50, 75, 100].forEach(v => svg.push(`<line class="gridl" x1="${m.l}" x2="${W - m.r}" y1="${Y(v)}" y2="${Y(v)}"></line><text class="ax" x="${m.l - 6}" y="${Y(v) + 4}" text-anchor="end">${v}</text><text class="ax" x="${X(v)}" y="${H - 22}" text-anchor="middle">${v}</text>`));
  svg.push(`<text class="ax" x="${m.l + (W - m.l - m.r) / 2}" y="${H - 4}" text-anchor="middle">${esc(o.xlab)}</text><text class="ax" x="${m.l + 4}" y="${m.t + 10}">${esc(o.ylab)}</text>`);
  svg.push(`<line class="pd-xh" x1="${X(o.vx)}" x2="${X(o.vx)}" y1="${m.t}" y2="${H - m.b}"></line><line class="pd-xh" x1="${m.l}" x2="${W - m.r}" y1="${Y(o.hy)}" y2="${Y(o.hy)}"></line>`);
  o.pts.forEach(p => svg.push(`<circle class="pd-pt" data-id="${esc(p.id)}" cx="${X(p.x).toFixed(1)}" cy="${Y(p.y).toFixed(1)}" r="${p.dim ? 2.6 : 4}" fill="${p.c}" opacity="${p.dim ? 0.3 : 0.85}"></circle>`));
  const sp = o.pts.find(p => p.id === o.sel); if (sp) svg.push(`<circle class="ptsel" cx="${X(sp.x).toFixed(1)}" cy="${Y(sp.y).toFixed(1)}" r="8"></circle>`);
  svg.push('</svg>'); el.innerHTML = svg.join('');
  const s = el.querySelector('svg'); const by = {}; o.pts.forEach(p => by[p.id] = p);
  s.addEventListener('mousemove', e => { const c = e.target.closest('circle.pd-pt'); if (!c) { hideTip(); return; } showTip(o.tip(by[c.dataset.id]), e.clientX, e.clientY); });
  s.addEventListener('mouseleave', hideTip);
  s.addEventListener('click', e => { const c = e.target.closest('circle.pd-pt'); if (c && o.onPick) o.onPick(c.dataset.id); if (tipFromTouch()) hideTip(); });
}
registerModule({
  key: 'paid', num: '07', title: 'Paid Acquisition', desc: 'Where an ad dollar reaches the most fee paying family law matters per unit of competition, resolved to the ZIP code, with a budget model and export lists',
  mount(root) {
    const SV = store.get('sev.paid', null) || {};
    const metroOK = c => !!(MSA[c] && GEO.metros && GEO.metros[c]);
    const MIG = { eff: 'effb', opp: 'oppb' };
    const PDL = Object.assign({}, ...['effb', 'oppb', 'opp_usd', 'mass', 'fvi', 'comp', 'cpc_rel'].map(k => ({ [k]: ZIP_LAYERS[k] })), { quad: { l: 'Quadrant (opportunity against competition)', cat: 'quad', g: 'C' }, tier: { l: 'Tier and starting bid modifier', cat: 'tier', g: 'C' }, acct_spend: { l: 'Your spend, last 90 days (Accounts)', acct: 'spend', g: 'A' }, acct_intake: { l: 'Your leads and intake, last 90 days (Accounts)', acct: 'intake', g: 'A' } }, ...Object.keys(ZIP_LAYERS).filter(k => !['effb', 'oppb', 'opp_usd', 'mass', 'fvi', 'comp', 'cpc_rel'].includes(k)).map(k => ({ [k]: ZIP_LAYERS[k] })));
    const st = { metro: metroOK(store.get('sev.metro', '19100')) ? store.get('sev.metro', '19100') : '19100', layer: PDL[SV.layer] ? SV.layer : 'effb', rank: PD_RANK[MIG[SV.rank] || SV.rank] ? (MIG[SV.rank] || SV.rank) : 'effb', sel: null, line: LINE_META[SV.line] ? SV.line : 'div_k', n: clamp(Math.round(+SV.n) || 25, 5, 300), cty: '', quad: '', angle: '', pins: { firm: !(SV.pins && SV.pins.firm === false), watch: !(SV.pins && SV.pins.watch === false) }, searches: SV.searches && typeof SV.searches === 'object' ? SV.searches : {} };
    const savePaid = () => store.set('sev.paid', { line: st.line, layer: st.layer, rank: st.rank, n: st.n, pins: st.pins, searches: st.searches });
    /* the build 2 budget inputs move into the shared store once (only values that differ from the old defaults) */
    (() => { const old = { cpc: 9.87, budget: 10000, cvr: 5.55, retain: 22 }; const p = { lines: {} }; const ln = LINE_META[SV.line] ? SV.line : 'div_k'; let n = 0;
      if (isN(SV.cpc) && SV.cpc !== old.cpc) { p.cpc = SV.cpc; n++; } if (isN(SV.budget) && SV.budget !== old.budget) { p.budget = SV.budget; n++; }
      const L0 = {}; if (isN(SV.cvr) && SV.cvr !== old.cvr) L0.cvr = SV.cvr; if (isN(SV.fee) && SV.fee !== LINE_META[ln].fee) L0.fee = SV.fee; if (isN(SV.retain) && SV.retain !== old.retain) { const sh = SEV_MODEL.line(ln).show; if (sh > 0) L0.close = clamp(SV.retain / sh * 100, 0, 100); }
      if (Object.keys(L0).length) { p.lines[ln] = L0; n++; } if (n) SEV_MODEL.set(p); if (['cpc', 'budget', 'cvr', 'retain', 'fee'].some(k => k in SV)) savePaid(); })();
    const metroOpts = Object.keys(MSA).filter(metroOK).sort((a, b) => MSA[b].pop2025 - MSA[a].pop2025).map(k => [k, MNAME(MSA[k].title)]);
    const gradeB = g => g ? (typeof gradeChip === 'function' ? gradeChip(g) : `<span class="grade ${g}" title="Confidence grade ${g}">${g}</span>`) : '';
    const pdM = v => isN(v) && Math.abs(v) >= 1e6 ? '$' + K(v) : $$$(v);   // money in a tile: $243.34M, not nine digits
    const inp = (id, attrs) => `<input type="number" id="${id}" ${attrs} inputmode="decimal" aria-describedby="pdHint">`;
    root.innerHTML = mastHTML({ eyebrow: 'Module 07 · Paid Acquisition · 1,127 metropolitan ZIP codes', title: 'Paid Acquisition', dek: `Where a family law firm should buy search, resolved to the ZIP code. County filings are allocated to ZIPs; each line's fee paying share and a payer weight from household income turn them into matter mass; the value per matter, scaled by a fee value index from income, turns mass into a fee pool; law office density nearby, raised by the rival ads logged in Competitor Watch, is the competition. Crossing the two gives four quadrants, and efficiency (fee pool per click cost) gives six tiers with starting bid modifiers. The budget model reads the shared assumptions store, so the Service Lines editor and the Accounts actuals reach it.`, facts: [[N(ZC.length), 'ZIP codes across 26 metros'], ['$9.87', 'median legal services CPC, Google search, Apr 2025 to Mar 2026 (WordStream), the default'], ['5.55%', 'median legal conversion rate; family law 8.52% in the 2023 LocaliQ cut'], ['$131.63', 'median legal cost per lead']] }) +
      toolbarHTML('Paid Acquisition', 'ZIP maps, quadrants, tiers, budget model, exports', [{ id: 'pdGoogle', label: '↓ Google Ads locations CSV', title: 'The shortlist with tier bid modifiers, for Ads Editor' }, { id: 'pdMeta', label: '↓ Meta ZIP CSV' }, { id: 'pdAll', label: '↓ All ZIPs CSV' }, { id: 'pdCoX', label: '↓ County rollup CSV' }, { id: 'pdCiX', label: '↓ City rollup CSV' }, { id: 'pdAsm', label: '↓ Assumptions JSON' }, { id: 'pdDesk', label: 'Send shortlist to Campaign Desk ↗', primary: true }, { id: 'pdLines', label: 'Service Lines ↗' }, { id: 'pdWatch', label: 'Competitor Watch ↗' }]) +
      `<p class="small" id="pdExpMsg" role="status" aria-live="polite" style="margin:-8px 0 12px"></p>
      ${callout('note', 'Read this first: what the ZIP numbers can and cannot say', `<p>The Office of Court Administration reports filings by county, not ZIP, so ZIP matters are an allocation: the county's filings spread across its ZIPs in proportion to married adults times the modeled hazard. That captures where the married people are and how divorce prone they are by composition; it cannot see a neighborhood that is unusually unhappy. The paid model then weighs those matters by who pays (protective order applicants pay no filing or service fee, indigent parents in DFPS suits receive appointed counsel, IV-D is the Attorney General's docket) and by household income, values them with the shared assumptions (grade D until the Accounts actuals replace them) and sets them against law office density, which counts every kind of law office, so downtown ZIPs look more crowded than they are for family law. It does not price keywords, see competitor spend or use client data. The quadrants exist because opportunity and competition travel together: the best ZIPs are crowded because they are good.</p>`)}
      <div class="tiles" id="pdKpis"></div>
      <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Metro', sel('pdMetro', metroOpts, st.metro))}${ctl('Map layer', sel('pdLayer', Object.keys(PDL).map(k => [k, PDL[k].l]), st.layer))}${ctl('County', '<select id="pdCty"></select>')}${ctl('Quadrant', sel('pdQuadF', [['', 'All']].concat(FLM.QN.map((q, i) => [String(i), q])), ''))}${ctl('Angle', sel('pdAng', [['', 'Any']].concat(FL_ANGLES.map(a => [a.id, a.short])), ''))}<label class="chk"><input type="checkbox" id="pdPinF"${st.pins.firm ? ' checked' : ''}> Your offices</label><label class="chk"><input type="checkbox" id="pdPinW"${st.pins.watch ? ' checked' : ''}> Watched firms</label></div>
        <div class="split"><div><div class="mapwrap" id="pdMap"></div><div id="pdLeg" class="pd-leg"></div></div><div><h3 class="pd-h3" id="pdMetroTitle"></h3><div id="pdMetroBody" class="small"></div><h3 class="pd-h3" id="pdZipH" style="margin-top:12px">Selected ZIP</h3><div id="pdZip" class="small"></div></div></div></div>
      <div class="grid2"><div class="panel"><h3>The four quadrants</h3><div class="sub">Opportunity is the fee pool, blended with its neighborhood; competition is law office density, raised by the rival ads logged in Competitor Watch. Crosshairs at the 60th percentile of competition and the 65th of opportunity; a point opens the ZIP.</div><div class="pd-quads" id="pdQuads"></div><div class="chart" id="pdSc"></div></div>
        <div class="panel"><h3>Coherence with the Dissolution Index</h3><div class="sub">ZIP level correlations in the metro between the ZIP index, opportunity, value and competition, and where need and payable demand part company.</div><div id="pdCoh"></div></div></div>
      <div class="grid2"><div class="panel"><h3>Budget model</h3><div class="sub">A monthly search budget through to retained matters and value in the shortlisted ZIPs, and what holding a click share there would cost. Every input reads and writes the shared store; each says where its value comes from.</div>
        <div class="controls">${ctl('Service line', sel('pdLine', Object.keys(LINE_META).map(k => [k, LINE_META[k].name]), st.line))}${ctl('Monthly budget $', inp('pdBudget', 'min="0" step="500" style="width:100px"'))}${ctl('Account CPC $', inp('pdCpc', 'min="0" step="0.05" style="width:80px"'))}${ctl('Click to lead %', inp('pdCvr', 'min="0" max="100" step="0.05" style="width:80px"'))}${ctl('Consultation show rate %', inp('pdShow', 'min="0" max="100" step="1" style="width:80px"'))}${ctl('Consultations retained %', inp('pdClose', 'min="0" max="100" step="1" style="width:80px"'))}${ctl('Value per matter $', inp('pdFee', 'min="0" step="250" style="width:100px"'))}${ctl('Contested share %', inp('pdCont', 'min="0" max="100" step="1" style="width:80px"'))}${ctl('Flat fee $', inp('pdFlat', 'min="0" step="250" placeholder="same as the fee" style="width:110px"'))}${ctl('Click share wanted %', inp('pdShare', 'min="0" max="100" step="1" style="width:80px"'))}${ctl('Metro searches a month', inp('pdSrch', 'min="0" step="1000" style="width:110px"'))}</div>
        <div class="pd-src" id="pdSrc"></div><div class="hintbad" id="pdHint" role="status" aria-live="polite"></div>
        <h4 class="pd-h4">The budget, spent in the shortlist</h4><div class="tiles" id="pdCalc"></div>
        <h4 class="pd-h4">What holding the click share costs</h4><div class="tiles" id="pdOwn"></div><div id="pdOwnTbl"></div>
        <p class="small" id="pdCalcNote"></p></div>
        <div class="panel"><h3>Shortlist</h3><div class="controls" style="margin-bottom:6px">${ctl('Rank the shortlist by', sel('pdRank', Object.keys(PD_RANK).map(k => [k, PD_RANK[k].l]), st.rank))}${ctl('Shortlist size', `<input type="number" id="pdN" value="${st.n}" min="5" max="300" step="1" inputmode="numeric" style="width:80px">`)}</div><div class="sub" id="pdShortSub"></div><div id="pdShort"></div></div></div>
      <div class="panel"><h3>All ZIPs in the metro</h3><div class="sub">The county, quadrant and angle above set the scope; the box below filters it further by ZIP, city or county name.</div><div class="controls">${ctl('Filter by ZIP, city or county', '<input type="search" id="pdFilter" placeholder="Plano or 750" autocomplete="off" aria-describedby="pdFilterMsg">')}<span class="small" id="pdFilterMsg" role="status" aria-live="polite"></span></div><div id="pdTable"></div></div>
      <div class="grid2"><div class="panel"><h3>County rollup</h3><div class="sub">Where the fee pool sits; the pool per household is the rate that survives size.</div><div id="pdCo"></div></div><div class="panel"><h3>City rollup</h3><div class="sub">ZIPs grouped by their city name (a ZIP's post office city, not the city limits).</div><div id="pdCi"></div></div></div>
      <div class="panel"><h3>How the model is built</h3><ol class="pd-meth" id="pdMeth"></ol></div>
      <div class="grid2"><div class="panel"><h3>Judgment calls</h3><div id="pdJudg"></div></div><div class="panel"><h3>What this module deliberately does not use</h3><div id="pdNot"></div></div></div>
      ${srcFoot([['Sources', `County filings from the Texas Office of Court Administration, ${esc(ttmSpan())}, allocated to ZIPs; ACS 2020 to 2024 ZIP code tabulation areas (income bands, home values, households); the PUMS composition model for the $35,000 to $60,000 band and the estimated lines; ZIP Business Patterns 2023 law offices; Google Ads geotargets of August 12, 2026 for criterion IDs; WordStream (Apr 2025 to Mar 2026) and LocaliQ (2023) legal benchmarks for the defaults; Competitor Watch observations and Accounts actuals where the firm has them.`], ['Caveats', 'Relative, not absolute: the model ranks ZIPs, and the dollar outputs are only as good as the assumptions typed. Law office counts include corporate and litigation firms. ZIP distances are straight lines between ZIP centers in the metro map\'s projection. Radius blending smooths edges: a strong ZIP beside a lake or an airport reads lower than its polygon, so check the unblended fee pool. These are annual figures; the Service Lines portfolio and the Timing Desk pace them by month. ZIPs under 200 residents carry no estimates.']])}`;
    const R = s => $(s, root);
    const mapEl = R('#pdMap');
    const C = () => FLM.compute(st.metro);
    const geo = () => MNAME(MSA[st.metro].title);
    const geoScope = () => st.cty ? CI[st.cty].name + ' County' : geo();
    const hasACCT = () => typeof ACCT !== 'undefined' && ACCT && typeof ACCT.byZip === 'function';
    const acctZ = () => { if (!hasACCT()) return null; try { const o = {}; (ACCT.byZip(90) || []).forEach(x => { o[x.zip] = x; }); return o; } catch (e) { return null; } };
    const inScope = r => (!st.cty || r.z.county === st.cty) && (st.quad === '' || String(r.quad) === st.quad) && (!st.angle || r.angles.includes(st.angle));
    const scope = () => C().rows.filter(inScope);
    function short() { const K = PD_RANK[st.rank]; return scope().filter(r => isN(K.v(r)) && r.mass > 0).sort((a, b) => K.v(b) - K.v(a) || a.zip.localeCompare(b.zip)).slice(0, st.n); }
    /* ---------- map ---------- */
    function pins(svg) {
      const G = GEO.metros[st.metro]; const u = G.W / 190; const out = [];
      if (st.pins.firm && typeof FIRM !== 'undefined') (FIRM.get().offices || []).forEach(o => { const z = ZI[String(o.zip || '').trim()]; if (!z || z.msa !== st.metro) return; const [x, y] = z.cent; out.push(`<path class="pd-pin firm" d="M${x},${y - u * 1.5}L${x + u * 1.5},${y}L${x},${y + u * 1.5}L${x - u * 1.5},${y}Z"><title>${esc(o.label || 'Office')}${o.primary ? ' (primary)' : ''} · ${esc(z.zip)} ${esc(z.city)}</title></path>`); });
      if (st.pins.watch) watched().forEach(w => { const [x, y] = w.z.cent; out.push(`<circle class="pd-pin rival" data-c="${esc(w.z.county)}" cx="${x}" cy="${y}" r="${u}"><title>${esc(w.name)} · office in ${esc(w.z.zip)} ${esc(w.z.city)} (Competitor Watch)</title></circle>`); });
      if (!out.length || !svg) return; const g = document.createElementNS('http://www.w3.org/2000/svg', 'g'); g.setAttribute('class', 'pd-pins'); g.innerHTML = out.join(''); svg.appendChild(g);
      g.addEventListener('click', e => { const c = e.target.closest('circle.rival'); if (c) goModule('watch', { county: c.dataset.c }); });
    }
    const watched = () => { if (typeof WATCH === 'undefined' || !WATCH || typeof WATCH.list !== 'function') return []; try { const out = []; WATCH.list().forEach(c => (c.offices || []).forEach(o => { const z = ZI[String(o.zip || '').trim()]; if (z && z.msa === st.metro && z.cent) out.push({ name: c.name, key: c.key, z }); })); return out; } catch (e) { return []; } };
    /* the zoomable map (core drawMap with fit, dim and pins) where the core has it; else a fixed view, a dim class and a pin overlay */
    const MZ = typeof mapHandle === 'function';
    function pinList() {
      const G = GEO.metros[st.metro]; const out = []; if (st.pins.firm && typeof firmPins === 'function') out.push(...firmPins(st.metro));
      if (st.pins.watch) watched().forEach(w => out.push({ x: w.z.cent[0], y: w.z.cent[1], shape: 'circle', r: 5, fill: 'var(--s2)', cls: 'rivalpin', county: w.z.county, tip: `<b>${esc(w.name)}</b><div class="small">Office in ${esc(w.z.zip)} ${esc(w.z.city)} (Competitor Watch). Click to open the watch for ${esc(w.z.county_name)} County.</div>` }));
      return out.length ? out : null;
    }
    const onPin = p => { if (p && p.cls === 'rivalpin') goModule('watch', { county: p.county }); else if (p && typeof mapAreaAt === 'function') { const a = mapAreaAt(GEO.metros[st.metro].zcta, p.x, p.y); if (a) pick(a); } };
    function draw() {
      const G = GEO.metros[st.metro]; const Cc = C(); const L = PDL[st.layer]; let leg = ''; let svg;
      const ctyZ = st.cty ? Cc.rows.filter(r => r.z.county === st.cty).map(r => r.zip) : null; const ins0 = new Set(scope().map(r => r.zip)); const filt0 = st.cty || st.quad !== '' || st.angle;
      const zo = MZ ? { dim: filt0 ? ins0 : null, fit: ctyZ, pins: pinList(), onPin, reset: st.reset || undefined } : { view: ctyZ ? FLM.box(st.metro, ctyZ) : null }; st.reset = false;
      const view = zo.view;
      if (L.cat || L.acct) {
        let value, color, legend = null;
        if (L.cat === 'quad') { value = id => Cc.by[id] ? Cc.by[id].quad : null; color = i => PD_QC[i]; leg = FLM.QN.map((q, i) => `<span><i style="background:${PD_QC[i]}"></i>${q} (${Cc.rows.filter(r => r.quad === i).length})</span>`).join(''); }
        else if (L.cat === 'tier') { value = id => Cc.by[id] ? FLM.TIERS.indexOf(Cc.by[id].tier) : null; color = i => PD_TC[i]; leg = FLM.TIERS.map((t, i) => `<span><i style="background:${PD_TC[i]}"></i>${t} ${FLM.TIER_BID[i] > 0 ? '+' : FLM.TIER_BID[i] < 0 ? '−' : ''}${Math.abs(FLM.TIER_BID[i])}% (${Cc.rows.filter(r => r.tier === t).length})</span>`).join(''); }
        else { const A = acctZ() || {}; const k = L.acct; const f = id => { const a = A[id]; return a ? (k === 'spend' ? a.spend : Math.max(a.leads, a.intake)) : null; }; const vals = Cc.rows.map(r => f(r.zip)); const sc = layerScale({ ramp: 'teal', v: v => v, f: v => k === 'spend' ? $$$(v) : N(v) }, vals); value = id => { const v = f(id); return isN(v) && v > 0 ? v : null; }; color = sc.color; legend = Object.assign({ title: L.l }, sc.legend); }
        if (legend) legend.grade = L.g;
        svg = drawMap(mapEl, Object.assign({ title: `${L.l}, ${geo()}`, W: G.W, H: G.H, paths: G.zcta, value, color, label: id => ZI[id] && ZI[id].msa === st.metro ? zipTipHTML(ZI[id]) : `<b>${esc(id)}</b><div class="small">Under 200 residents: no estimates for this ZIP.</div>`, onSelect: pick, selected: st.sel, counties: G.county, cent: G.ccent, labels: Object.keys(G.county), labelText: id => CI[id] ? CI[id].name : id, legend, noDataLabel: L.acct ? 'no rows in Accounts' : 'under 200 residents' }, zo));
      } else svg = drawZipMap(mapEl, [st.metro], L, Object.assign({ sel: st.sel }, zo), pick);
      const filt = filt0;
      if (!MZ) { if (filt) $$('path.area', mapEl).forEach(p => { if (!ins0.has(p.dataset.id)) p.classList.add('pd-dim'); }); pins(svg || mapEl.querySelector('svg')); }
      const A = acctZ(); const nA = A ? Object.keys(A).filter(z => ZI[z] && ZI[z].msa === st.metro).length : 0;
      let flags = '';
      if (nA) { const low = Cc.rows.filter(r => A[r.zip] && A[r.zip].spend > 0 && r.effb < 30); const miss = Cc.rows.filter(r => r.effb >= 90 && !(A[r.zip] && A[r.zip].spend > 0)); flags = `<p class="small pd-flag">Accounts: spend in ${N(nA)} ZIPs of the metro in the last 90 days. ${low.length ? `${low.length} with spend sit below the 30th efficiency percentile (${low.slice(0, 6).map(r => r.zip).join(', ')}${low.length > 6 ? ' and more' : ''}).` : 'No spend below the 30th efficiency percentile.'} ${miss.length ? `${miss.length} top decile ZIPs have no spend (${miss.slice(0, 6).map(r => r.zip).join(', ')}${miss.length > 6 ? ' and more' : ''}).` : ''}</p>`; }
      R('#pdLeg').innerHTML = (leg ? `<div class="pd-catleg">${leg}</div>` : '') + `<p class="small">${gradeB(L.g)} ${L.cat === 'quad' ? 'Opportunity at the 65th percentile and competition at the 60th.' : L.cat === 'tier' ? 'Efficiency percentile bands: A+ 95 and up, A 85, B 70, C 50, D 30, E below 30.' : L.acct ? (hasACCT() ? (nA ? 'From the rows Accounts holds for this metro.' : 'No ZIP rows in Accounts for this metro yet: connect an account or import a sheet with ZIPs.') : 'Accounts is not loaded in this view.') : ''}${filt ? ' ZIPs outside the scope are dimmed.' : ''}${st.cty ? ' Zoomed to ' + esc(CI[st.cty].name) + ' County.' : ''}${(st.pins.firm || st.pins.watch) ? ' Pins sit on the office ZIP\'s center: diamonds are your offices (firm profile), circles the offices of watched firms (Competitor Watch).' : ''}</p>${flags}`;
      const m = MSA[st.metro]; R('#pdMetroTitle').textContent = geo();
      R('#pdMetroBody').innerHTML = `<dl class="kv"><dt>Population 2025</dt><dd>${N(m.pop2025)}</dd><dt>Married adults</dt><dd>${N(m.married)}</dd><dt>Divorce filings, 12 mo</dt><dd>${N(m.ttm.div)} (${sgn((m.ttm.div / (m.prev.div || 1) - 1) * 100)})</dd><dt>Private family filings</dt><dd>${N(m.ttm.priv)}</dd><dt>Law offices</dt><dd>${N(m.lawoffices)}</dd><dt>ZIPs mapped</dt><dd>${N(Cc.rows.length)}</dd><dt>Radius for neighbors and density</dt><dd>${N(Cc.radius)} km</dd><dt>Rival ads logged (Competitor Watch)</dt><dd>${Cc.logged ? 'yes, in these counties' : 'none'}</dd></dl>`;
    }
    function pick(id) { st.sel = id; if (MZ) mapHandle(mapEl).select(id); else markSel(mapEl, id); zipBox(); if (tbl) tbl.setSel(id); scatterDraw(); }
    /* ---------- the ZIP card ---------- */
    function zipBox() {
      const z = ZI[st.sel]; const r = z ? C().by[z.zip] : null;
      if (!r) { R('#pdZipH').textContent = 'Selected ZIP'; R('#pdZip').innerHTML = st.sel ? `<span class="small"><b>${esc(st.sel)}</b>: ${z ? 'outside this metro.' : 'under 200 residents, so no estimates for this ZIP.'}</span>` : '<span class="small">Click a ZIP on the map, a point on the quadrant chart or a row in a table.</span>'; return; }
      const Cc = C(); const a = z.acs, k = z.risk; const cell = Cc.cells[z.zip];
      const prim = typeof FIRM !== 'undefined' ? FIRM.primary() : {}; const pz = ZI[String((prim || {}).zip || '').trim()]; const dist = pz && pz.msa === st.metro ? FLM.distKm(st.metro, z.cent, pz.cent) : null;
      const near = watched().map(w => ({ w, d: FLM.distKm(st.metro, z.cent, w.z.cent) })).sort((x, y) => x.d - y.d).slice(0, 4);
      const act = (Cc.by[z.zip].act || null); const A = acctZ(); const me = A && A[z.zip];
      R('#pdZipH').textContent = `${z.zip} · ${z.city}`;
      R('#pdZip').innerHTML = `${esc(z.county_name)} County · ${esc(FLM.QN[r.quad])} · tier ${esc(r.tier)}
        <div class="pd-big"><div><b>${N(r.effb, 0)}</b><span>efficiency</span></div><div><b>${N(r.oppb, 0)}</b><span>opportunity</span></div><div><b class="${r.bid >= 0 ? 'up' : 'dn'}">${r.bid > 0 ? '+' : r.bid < 0 ? '−' : ''}${Math.abs(r.bid)}%</b><span>starting bid</span></div></div>
        <h4 class="pd-h4">Matter mass, a year ${gradeB('C')}</h4><dl class="kv">${FLM.ADD.filter(id => cell[id].matters > 0.05).map(id => `<dt>${esc(LINE_META[id].short)}${FLM.PAYER[id] ? ' (fee paying share)' : ''}</dt><dd>${N(cell[id].mass, 1)}</dd>`).join('')}<dt><b>All lines, payer weighted</b></dt><dd><b>${N(r.mass, 1)}</b></dd><dt>Quick turn (modification, enforcement, protective order respondent)</dt><dd>${N(r.quick, 1)}</dd><dt>Fee pool a year at 100% share</dt><dd>${$$$(r.opp)}</dd></dl>
        <h4 class="pd-h4">Value and competition</h4><dl class="kv"><dt>Payer weight (income bands)</dt><dd>${N(r.w, 2)}</dd><dt>Fee value index</dt><dd>${N(r.fvi * 100, 0)}</dd><dt>Competition percentile</dt><dd>${N(r.comp_pct, 0)}</dd><dt>Click cost index</dt><dd>${N(r.cpc_rel, 2)}×</dd><dt>Law offices within ${N(Cc.radius)} km · in the ZIP</dt><dd>${N(r.off8)} · ${z.lawoffices ? N(z.lawoffices) : 'none'}</dd><dt>Offices per 1,000 married nearby</dt><dd>${N(r.dens, 2)}</dd><dt>Live rival ads logged for the county</dt><dd>${act ? N(act._all || 0) : 'none'}</dd><dt>Distance to your primary office</dt><dd>${dist != null ? N(dist, 1) + ' km' : pz ? 'outside this metro' : 'set it in the firm profile'}</dd></dl>
        ${near.length ? `<p class="small">Nearest watched firms: ${near.map(x => `${esc(x.w.name)} (${N(x.d, 1)} km)`).join('; ')}.</p>` : ''}
        <h4 class="pd-h4">Angles this ZIP triggers</h4><div>${r.angles.length ? r.angles.map(id => { const A0 = FL_ANGLES.find(x => x.id === id); return `<span class="pill" title="${esc(A0.why)}">${esc(A0.short)}</span>`; }).join(' ') : '<span class="small">None.</span>'}</div>
        <h4 class="pd-h4">Audience levers</h4><div>${r.lev.tags.length ? r.lev.tags.map(t => `<span class="pill">${esc((FLM.LEVERS.find(x => x[0] === t) || [])[1])}</span>`).join(' ') : '<span class="small">No lever stands out against the metro.</span>'}</div>
        ${me ? `<h4 class="pd-h4">Your actuals here, last 90 days</h4><dl class="kv"><dt>Spend · clicks</dt><dd>${$$$(me.spend)} · ${N(me.clicks)}</dd><dt>Leads · intake · retained</dt><dd>${N(me.leads)} · ${N(me.intake)} · ${N(me.retained)}</dd><dt>Cost per lead</dt><dd>${$$$(me.cpl)}</dd></dl>` : ''}
        <h4 class="pd-h4">Targeting</h4><dl class="kv"><dt>Google location</dt><dd class="pd-mono">${esc(z.zip)}, Texas, United States</dd><dt>Google criterion ID</dt><dd class="pd-mono">${esc(z.gt || 'resolve by name')}</dd><dt>Meta ZIP key</dt><dd class="pd-mono">US:${esc(z.zip)}</dd></dl>
        <h4 class="pd-h4">Census and court</h4><dl class="kv"><dt>Population · married adults</dt><dd>${N(a.pop)} · ${N(a.married)}</dd><dt>Expected divorce filings / yr</dt><dd>${N(z.alloc.div, 0)}</dd><dt>Expected SAPCR · protective orders</dt><dd>${N(z.alloc.sapcr, 0)} · ${N(z.alloc.po, 0)}</dd><dt>Composition hazard /1k · separated /1k</dt><dd>${N(k.haz_pred, 1)} · ${N(a.sep_per_1k_married, 0)}</dd><dt>Median HH income · over $150k</dt><dd>${$$$(a.med_hh_inc)} · ${P(a.inc_150k_sh, 0)}</dd><dt>Under $35k · renters</dt><dd>${P(a.inc_lt35k_sh, 0)} · ${P(a.renter_sh, 0)}</dd><dt>ZIP index</dt><dd>${N(z.di, 0)}</dd></dl>${zipGapNote(z)}
        <div class="btnrow" style="margin-top:10px"><button type="button" class="btn sm primary" id="pdZDesk">Campaign Desk ↗</button><button type="button" class="btn sm" id="pdZLines">Service Lines ↗</button><button type="button" class="btn sm" id="pdZWatch">Competitor Watch ↗</button></div>`;
      R('#pdZDesk').onclick = () => goModule('desk', { geo: 'msa:' + st.metro, zips: [z.zip], line: st.line, bids: { [z.zip]: r.bid } });
      R('#pdZLines').onclick = () => goModule('lines', { zip: z.zip, line: st.line }); R('#pdZWatch').onclick = () => goModule('watch', { county: z.county, zip: z.zip });
    }
    /* ---------- KPIs, quadrants, scatter, coherence ---------- */
    function kpis() {
      const Cc = C(); const rs = Cc.rows; const q = [0, 1, 2, 3].map(i => rs.filter(r => r.quad === i).length);
      R('#pdKpis').innerHTML = tile('Buyable ZIPs', N(rs.filter(r => r.mass > 0).length), `of ${N(rs.length)} mapped in ${esc(geo())}; the rest have no allocated matters`, 'A') + tile('Fee pool a year', pdM(sum(rs.map(r => r.opp))), 'payer weighted, collected, pipeline included, at 100% share', 'C') + tile('Retainable matters', N(sum(rs.map(r => r.mass))), 'fee paying matters a year, payer weighted, ten additive lines', 'C') + tile('Quick turn matters', N(sum(rs.map(r => r.quick))), 'modification, enforcement and the protective order respondent', 'C') + tile('Anchor ZIPs', N(q[0]), 'high opportunity, high competition', 'C') + tile('Whitespace ZIPs', N(q[1]), 'high opportunity, competition below the 60th percentile', 'C') + tile('Median click cost index', N(Cc.med.cpc_rel, 2) + '×', 'relative to a flat CPC; range 0.55 to 2.10', 'D');
      R('#pdQuads').innerHTML = FLM.QN.map((n, i) => `<div class="pd-qb"><div class="pd-qt"><span class="pd-sw" style="background:${PD_QC[i]}"></span>${n}</div><div class="pd-qv">${N(q[i])}</div><div class="small">${esc(FLM.QD[i])} · ${pdM(sum(rs.filter(r => r.quad === i).map(r => r.opp)))} a year</div></div>`).join('');
      scatterDraw(); coherence();
    }
    function scatterDraw() {
      const ins = new Set(scope().map(r => r.zip)); const filt = st.cty || st.quad !== '' || st.angle;
      pdScatter(R('#pdSc'), { title: 'Competition against opportunity, ZIPs of ' + geo(), xlab: 'Competition percentile', ylab: 'Opportunity percentile', vx: 60, hy: 65, sel: st.sel, pts: C().rows.map(r => ({ id: r.zip, x: r.comp_pct, y: r.oppb, c: PD_QC[r.quad], dim: filt && !ins.has(r.zip) })), tip: p => { const r = C().by[p.id]; return `<b>${esc(r.zip)} · ${esc(r.z.city)}</b><div class="row"><span>Opportunity</span><span>${N(r.oppb, 0)}</span></div><div class="row"><span>Competition</span><span>${N(r.comp_pct, 0)}</span></div><div class="row"><span>Quadrant · tier</span><span>${esc(FLM.QN[r.quad])} · ${esc(r.tier)}</span></div>`; }, onPick: pick });
    }
    function pearson(x, y) { if (typeof SEV_STATS !== 'undefined' && SEV_STATS.pearson) { try { const p = SEV_STATS.pearson(x, y); return p && isN(p.r) ? p.r : null; } catch (e) { return null; } } return null; }
    function coherence() {
      const rs = C().rows.filter(r => isN(r.z.di) && r.mass > 0); const V = [['ZIP index', r => r.z.di], ['Opportunity', r => r.oppb], ['Value (fee index)', r => r.fvi], ['Competition', r => r.comp_pct]];
      const M = V.map(a => V.map(b => pearson(rs.map(a[1]), rs.map(b[1]))));
      const cell = v => !isN(v) ? `<td>${NA}</td>` : `<td style="background:color-mix(in srgb, ${v >= 0 ? 'var(--s1)' : 'var(--s2)'} ${Math.round(Math.abs(v) * 55)}%, var(--card))">${N(v, 2)}</td>`;
      const dis = rs.map(r => ({ r, d: r.z.di - r.oppb })).sort((a, b) => b.d - a.d);
      const tb = (title, a, cre) => `<div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">${esc(title)}</caption><thead><tr><th scope="col" class="l">${esc(title)}</th><th scope="col">Index</th><th scope="col">Opportunity</th><th scope="col">Tier</th></tr></thead><tbody>${a.map(x => `<tr><td class="l"><button type="button" class="linkbtn" data-z="${esc(x.r.zip)}">${esc(x.r.zip)}</button> ${esc(x.r.z.city)}</td><td>${N(x.r.z.di, 0)}</td><td>${N(x.r.oppb, 0)}</td><td>${esc(x.r.tier)}</td></tr>`).join('')}</tbody></table></div></div><p class="small">${cre}</p>`;
      const cm = typeof corrMatrix === 'function' ? corrMatrix(null, { keys: V.map((v, i) => 'k' + i), labels: V.map(v => v[0]), matrix: M, caption: 'Correlations across the metro\'s ZIPs' }) : `<div class="tblbox"><div class="tblwrap"><table class="t pd-corr"><caption class="vh">Correlations across the metro's ZIPs</caption><thead><tr><th scope="col"></th>${V.map(v => `<th scope="col">${esc(v[0])}</th>`).join('')}</tr></thead><tbody>${V.map((v, i) => `<tr><th scope="row" class="l">${esc(v[0])}</th>${M[i].map(cell).join('')}</tr>`).join('')}</tbody></table></div></div>`;
      R('#pdCoh').innerHTML = `${cm}
        <p class="small">Pearson r across ${N(rs.length)} ZIPs with matters. The ZIP index measures need (composition, separation, shock, strain, supply); opportunity measures payable demand. Index and opportunity r = ${N(M[0][1], 2)}; index and value r = ${N(M[0][2], 2)}; opportunity and competition r = ${N(M[1][3], 2)}, which is why the quadrants exist. The map disagrees with module 01 on purpose: need and payable demand are different things.</p>
        ${tb('Need outruns payable demand', dis.slice(0, 6), 'Lead with flat fees and limited scope offers as the firm profile states them, payment terms and Spanish creative where the firm serves clients in Spanish; never a contingent fee.')}${tb('Payable demand outruns need', dis.slice(-6).reverse(), 'Larger households and incomes, fewer filings per married adult: high asset and gray divorce creative, separate property and retirement division.')}`;
      $$('#pdCoh .linkbtn', root).forEach(b => b.onclick = () => pick(b.dataset.z));
    }
    /* ---------- the budget model (shared store) ---------- */
    const BIND = { pdBudget: ['g', 'budget', 'The monthly budget'], pdCpc: ['g', 'cpc', 'The account CPC'], pdShare: ['g', 'share', 'The click share'], pdCvr: ['line', 'cvr', 'The click to lead rate'], pdShow: ['line', 'show', 'The show rate'], pdClose: ['line', 'close', 'The retained rate'], pdFee: ['line', 'fee', 'The value per matter'], pdCont: ['line', 'contested', 'The contested share'], pdFlat: ['line', 'flat', 'The flat fee'] };
    const srcTxt = x => x.src === 'actuals' ? 'actuals (grade B)' : x.src === 'you' ? 'your input' : 'default (grade D)';
    const srchDef = () => SEV_MODEL.rate('searchPerFiling') * (MSA[st.metro].ttm.priv || 0);
    const srch = () => isN(st.searches[st.metro]) ? st.searches[st.metro] : srchDef();
    function fillInputs() {
      Object.keys(BIND).forEach(id => { const [sc, k] = BIND[id]; const el = R('#' + id); if (document.activeElement === el) return; const x = SEV_MODEL.info(sc, sc === 'line' ? st.line : null, k); el.value = x.v == null ? '' : +(+x.v).toFixed(4); el.removeAttribute('aria-invalid'); });
      if (document.activeElement !== R('#pdSrch')) R('#pdSrch').value = Math.round(srch());
      const ln = LINE_META[st.line].short; R('#pdSrc').innerHTML = `<p class="small">${Object.keys(BIND).map(id => { const [sc, k, nm] = BIND[id]; const x = SEV_MODEL.info(sc, sc === 'line' ? st.line : null, k); return `<span class="pd-tag ${x.src}">${esc(nm.replace(/^The /, ''))}${sc === 'line' ? ' (' + esc(ln) + ')' : ''}: ${srcTxt(x)}</span>`; }).join(' ')} <span class="pd-tag ${isN(st.searches[st.metro]) ? 'you' : 'default'}">metro searches: ${isN(st.searches[st.metro]) ? 'your input' : `default (grade D), ${N(SEV_MODEL.rate('searchPerFiling'), 1)} a month per private family filing a year`}</span></p>`;
    }
    const writeIn = debounce(el => {
      const id = el.id; const raw = String(el.value).trim(); const msgs = [];
      if (id === 'pdSrch') { const v = +raw; if (raw === '') delete st.searches[st.metro]; else if (isFinite(v) && v >= 0) st.searches[st.metro] = v; else msgs.push('Metro searches must be a number of 0 or more.'); savePaid(); fillInputs(); calc(); R('#pdHint').textContent = msgs.join(' '); return; }
      const [sc, k, nm] = BIND[id]; const F = sc === 'g' ? SEV_MODEL.GF[k] : SEV_MODEL.LF[k];
      if (raw === '') { msgs.push(`${nm} is empty, so it returns to ${k === 'flat' ? 'the value per matter' : 'the default or the applied actuals'}.`); }
      const v = raw === '' ? null : +raw; if (v != null && !isFinite(v)) { el.setAttribute('aria-invalid', 'true'); R('#pdHint').textContent = `${nm} must be a number.`; return; }
      if (v != null && (v < F.min || v > F.max)) { el.setAttribute('aria-invalid', 'true'); msgs.push(`${nm} must be between ${N(F.min)} and ${N(F.max)}; it counts as ${N(clamp(v, F.min, F.max), 2)}.`); } else el.removeAttribute('aria-invalid');
      if (k === 'cpc' && v === 0) msgs.push('A CPC of $0 gives no click count; enter the cost per click you expect.'); if (k === 'cvr' && v === 0) msgs.push('A click to lead rate of 0% gives no leads, so cost per lead reads n/a.');
      R('#pdHint').textContent = msgs.join(' ');
      if (sc === 'g') SEV_MODEL.set({ [k]: v }); else SEV_MODEL.set({ lines: { [st.line]: { [k]: v } } });
    }, 350);
    function calc() {
      const s = short(); const Cc = C(); const L = SEV_MODEL.line(st.line); const cpc = SEV_MODEL.get('cpc'), bud = SEV_MODEL.get('budget'), share = SEV_MODEL.get('share'); const Lm = LINE_META[st.line];
      const cl = s.map(r => ({ r, c: Cc.cells[r.zip][st.line] })); const wm = sum(cl.map(x => x.c.mass));
      const avg = f => wm > 0 ? sum(cl.map(x => x.c.mass * f(x))) / wm : (cl.length ? sum(cl.map(f)) / cl.length : null);
      const rel = avg(x => x.r.cpc_rel) || Cc.med.cpc_rel; const fvi = avg(x => x.r.fvi) || 1; const dm = avg(x => x.r.divMix); const u = FLM.econ(st.line, rel, fvi, dm == null ? 0.5 : dm);
      const ecpc = cpc * (L.cpcMult || 0) * rel; const clicks = ecpc > 0 ? bud / ecpc : null; const leads = isN(clicks) ? clicks * (L.cvr || 0) / 100 : null; const cons = isN(leads) ? leads * (L.show || 0) / 100 : null; const ret = isN(cons) ? cons * (L.close || 0) / 100 : null; const val = isN(ret) ? ret * u.perRet : null;
      const matters = sum(cl.map(x => x.c.matters)), pay = sum(cl.map(x => x.c.payable));
      R('#pdCalc').innerHTML = tile('Clicks / month', N(clicks), ecpc > 0 ? `at ${$$$(ecpc, 2)} a click (the account CPC times the shortlist's click cost index ${N(rel, 2)}${L.cpcMult !== 1 ? ' and the line multiple ' + N(L.cpcMult, 2) : ''})` : 'enter a CPC above $0', 'D') + tile('Leads / month', N(leads, 1), `at ${N(L.cvr, 2)}% · ${leads > 0 ? $$$(bud / leads) + ' per lead' : 'no cost per lead without leads'}`, 'D') + tile('Consultations / month', N(cons, 1), `at ${N(L.show, 0)}% show`, 'D') + tile('Retained / month', N(ret, 1), `at ${N(L.close, 0)}% of consultations · ${ret > 0 ? $$$(bud / ret) + ' per matter' : 'no cost per matter without matters'}`, 'D') + tile('Value / month', pdM(val), `${$$$(u.perRet)} per retained ${Lm.lcs} matter${isN(val) && bud > 0 ? ' · ' + N(val / bud, 1) + '× the budget' : ''}`, 'D') + tile('Matters a year in the shortlist', N(matters, 0), `${Lm.name}; ${N(pay, 0)} fee paying`, Lm.est ? 'C' : 'B') + tile('Share of fee paying matters', isN(ret) && pay > 0 ? P(ret * 12 / pay, 1) : NA, 'retained a year against fee paying matters a year', 'D');
      /* click share: the metro's searches spread over the ZIPs by matter mass (this line's share of all additive mass) */
      const S = srch(); const mTot = sum(Cc.rows.map(r => r.mass)) || 1; const e = s.map(r => { const c = Cc.cells[r.zip][st.line]; const sz = S * c.mass / mTot; const cl2 = sz * share / 100; const cost = cl2 * cpc * (L.cpcMult || 0) * r.cpc_rel; const ld = cl2 * (L.cvr || 0) / 100; const cn = ld * (L.show || 0) / 100; const rt = cn * (L.close || 0) / 100; const pv = FLM.econ(st.line, r.cpc_rel, r.fvi, r.divMix).perRet; return { r, srch: sz, clicks: cl2, cost, leads: ld, cons: cn, ret: rt, val: rt * pv }; });
      const T = { srch: sum(e.map(x => x.srch)), clicks: sum(e.map(x => x.clicks)), cost: sum(e.map(x => x.cost)), ret: sum(e.map(x => x.ret)), val: sum(e.map(x => x.val)), leads: sum(e.map(x => x.leads)) };
      R('#pdOwn').innerHTML = tile('Monthly media to hold the share', pdM(T.cost), `${N(share, 0)}% of ${N(T.srch)} searches a month in the top ${s.length} ZIPs`, 'D') + tile('Retained / month', N(T.ret, 1), `${N(T.clicks)} clicks, ${N(T.leads, 1)} leads`, 'D') + tile('Cost per retained matter', T.ret > 0 ? $$$(T.cost / T.ret) : NA, 'before intake handling', 'D') + tile('Value retained / month', pdM(T.val), T.cost > 0 ? N(T.val / T.cost, 1) + '× the media' : 'no media at these inputs', 'D');
      R('#pdOwnTbl').innerHTML = `<div class="tblbox"><div class="tblwrap" style="max-height:340px"><table class="t"><caption class="vh">The top 25 shortlisted ZIPs at the click share wanted</caption><thead><tr><th scope="col">ZIP</th><th scope="col" class="l">City</th><th scope="col">Tier</th><th scope="col">Searches/mo</th><th scope="col">Clicks</th><th scope="col">Media/mo</th><th scope="col">Leads</th><th scope="col">Consults</th><th scope="col">Retained</th><th scope="col">Cost/retained</th><th scope="col">Value/mo</th></tr></thead><tbody>${e.slice(0, 25).map(x => `<tr><td class="name"><button type="button" class="linkbtn" data-z="${esc(x.r.zip)}">${esc(x.r.zip)}</button></td><td class="l">${esc(x.r.z.city)}</td><td>${esc(x.r.tier)}</td><td>${N(x.srch)}</td><td>${N(x.clicks, 1)}</td><td>${$$$(x.cost)}</td><td>${N(x.leads, 2)}</td><td>${N(x.cons, 2)}</td><td>${N(x.ret, 2)}</td><td>${x.ret > 0 ? $$$(x.cost / x.ret) : NA}</td><td>${$$$(x.val)}</td></tr>`).join('')}</tbody></table></div></div>`;
      $$('#pdOwnTbl .linkbtn', root).forEach(b => b.onclick = () => pick(b.dataset.z));
      R('#pdCalcNote').innerHTML = `Value per retained matter: ${N(L.contested, 0)}% contested at ${$$$(L.fee)} times the shortlist's fee value index (${N(fvi * 100, 0)}), the rest at ${$$$(isN(L.flat) ? L.flat : L.fee)} flat, times ${N(L.realization, 0)}% collected${u.pipe ? `, plus ${$$$(u.pipe)} of pipeline credit` : ''}. Metro searches (grade D) only spread demand over the ZIPs by matter mass; they scale every search figure in proportion and nothing else. Defaults are the legal medians and stated assumptions; the Accounts module's Apply replaces them with the firm's own numbers. Never advertise a contingent fee in a family matter.`;
    }
    /* ---------- shortlist ---------- */
    function shortlist() {
      const s = short(); const K = PD_RANK[st.rank]; const none = s.filter(r => !r.z.lawoffices).length;
      R('#pdShortSub').textContent = `The top ${s.length} ZIPs of ${geoScope()} by ${K.l.toLowerCase().replace('zip', 'ZIP')}, high to low, within the quadrant and angle above. The budget model and the Google, Meta and Campaign Desk exports carry these rows with their tier bids; the map layer only colors the map.`;
      R('#pdShort').innerHTML = `<div class="tblbox"><div class="tblwrap" style="max-height:420px"><table class="t"><caption class="vh">Shortlisted ZIP codes, ranked by ${esc(K.l)}</caption><thead><tr><th scope="col">ZIP</th><th scope="col" class="l">City</th><th scope="col">Tier</th><th scope="col" class="l">Quadrant</th><th scope="col">${esc(K.h)}</th><th scope="col">Bid</th><th scope="col">Criterion</th></tr></thead><tbody>${s.map(r => `<tr><td class="name"><button type="button" class="linkbtn" data-id="${esc(r.zip)}">${esc(r.zip)}</button></td><td class="l">${esc(r.z.city)}</td><td>${esc(r.tier)}</td><td class="l">${esc(FLM.QN[r.quad])}</td><td>${esc(K.f(K.v(r)))}</td><td>${r.bid > 0 ? '+' : ''}${N(r.bid)}%</td><td>${esc(r.z.gt || '')}</td></tr>`).join('')}</tbody></table></div></div>${none ? `<p class="small" style="margin-top:6px">${none} of these ${s.length} ZIPs have no law office in the ZIP Business Patterns count; families there use offices in nearby ZIPs, so check the drive to the firm before bidding them up.</p>` : ''}${!s.length ? '<p class="small">No ZIP in this scope has matters; widen the county, quadrant or angle.</p>' : ''}`;
      $$('#pdShort .linkbtn', root).forEach(b => b.onclick = () => pick(b.dataset.id)); calc();
    }
    /* ---------- the ZIP table and rollups ---------- */
    const cols = [{ k: 'zip', l: 'ZIP', fmt: v => esc(v) }, { k: 'city', l: 'City', fmt: v => esc(v), cls: 'l' }, { k: 'county', l: 'County', fmt: v => esc(v), cls: 'l' }, { k: 'tier', l: 'Tier', fmt: v => esc(v), h: 'Tier' }, { k: 'quad', l: 'Quadrant', fmt: v => esc(v), cls: 'l', h: 'Quadrant (opportunity 65th, competition 60th percentile)' }, { k: 'effb', l: 'Efficiency', fmt: v => N(v, 0), h: 'Efficiency percentile', d: 1 }, { k: 'oppb', l: 'Opportunity', fmt: v => N(v, 0), h: 'Opportunity percentile', d: 1 }, { k: 'opp', l: 'Fee pool', fmt: v => $$$(v), h: 'Fee pool a year ($)', d: 0 }, { k: 'mass', l: 'Mass', fmt: v => N(v, 1), h: 'Matter mass (payer weighted fee paying matters a year)', d: 2 }, { k: 'quick', l: 'Quick turn', fmt: v => N(v, 1), h: 'Quick turn matters a year', d: 2 }, { k: 'fvi', l: 'Fee idx', fmt: v => N(v, 0), h: 'Fee value index (100 = metro median income)', d: 0 }, { k: 'w', l: 'Payer wt', fmt: v => N(v, 2), h: 'Payer weight', d: 3 }, { k: 'comp', l: 'Competition', fmt: v => N(v, 0), h: 'Competition percentile', d: 1 }, { k: 'cpc', l: 'CPC idx', fmt: v => N(v, 2), h: 'Click cost index', d: 3 }, { k: 'bid', l: 'Bid', fmt: v => (v > 0 ? '+' : '') + N(v) + '%', h: 'Starting bid modifier (%)', d: 0 }, { k: 'angles', l: 'Angles', fmt: v => esc(v), cls: 'l' }, { k: 'di', l: 'ZIP index', fmt: v => N(v, 0), h: 'ZIP Dissolution Index', d: 0 }, { k: 'div', l: 'Div /yr', fmt: v => N(v, 0), h: 'Expected divorce filings a year', d: 0 }, { k: 'priv', l: 'Private /yr', fmt: v => N(v, 0), h: 'Expected private family filings a year', d: 0 }, { k: 'married', l: 'Married', fmt: v => N(v), h: 'Married adults (ACS)', d: 0 }, { k: 'inc', l: 'Med income', fmt: v => $$$(v), h: 'Median household income ($)', d: 0 }, { k: 'offices', l: 'Offices', fmt: v => N(v), h: 'Law offices in the ZIP (ZBP 2023)', d: 0 }, { k: 'gt', l: 'Criterion', fmt: v => esc(v), h: 'Google Ads location ID' }];
    const rowsT = () => { const q = String((R('#pdFilter') || {}).value || '').trim().toLowerCase(); const all = scope(); const out = all.filter(r => !q || r.zip.startsWith(q) || String(r.z.city || '').toLowerCase().includes(q) || String(r.z.county_name || '').toLowerCase().includes(q)); const m = R('#pdFilterMsg'); if (m) m.textContent = q ? `${out.length} of ${all.length} ZIPs in scope` : `${all.length} ZIPs in scope`; return out.map(r => ({ _id: r.zip, zip: r.zip, city: r.z.city, county: r.z.county_name, tier: r.tier, quad: FLM.QN[r.quad], effb: r.effb, oppb: r.oppb, opp: r.opp, mass: r.mass, quick: r.quick, fvi: r.fvi * 100, w: r.w, comp: r.comp_pct, cpc: r.cpc_rel, bid: r.bid, angles: r.angles.map(a => (FL_ANGLES.find(x => x.id === a) || {}).short).join(', '), di: r.z.di, div: r.z.alloc.div, priv: r.z.alloc.priv, married: r.z.acs.married, inc: r.z.acs.med_hh_inc, offices: r.z.lawoffices, gt: r.z.gt })); };
    let tbl = table(R('#pdTable'), { caption: 'All ZIP codes in scope', cols, rows: rowsT(), sort: { k: 'effb', dir: -1 }, onRow: pick });
    const med = a => { const v = a.filter(isN).sort((x, y) => x - y); return v.length ? (v[(v.length - 1) >> 1] + v[v.length >> 1]) / 2 : null; };
    const roll = keyOf => { const g = {}; C().rows.forEach(r => { const k = keyOf(r); if (!k) return; (g[k] = g[k] || []).push(r); }); return Object.keys(g).map(k => { const rs = g[k]; const hh = sum(rs.map(r => r.z.acs.hh || 0)); const counties = [...new Set(rs.map(r => r.z.county_name))]; return { _id: k, name: k, counties: counties.join(', '), zips: rs.length, hh, pop: sum(rs.map(r => r.z.acs.pop || 0)), mass: sum(rs.map(r => r.mass)), opp: sum(rs.map(r => r.opp)), perhh: hh > 0 ? sum(rs.map(r => r.opp)) / hh : null, eff: med(rs.map(r => r.effb)), comp: med(rs.map(r => r.comp_pct)), anchors: rs.filter(r => r.quad === 0).length, white: rs.filter(r => r.quad === 1).length }; }); };
    const coCols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'zips', l: 'ZIPs', fmt: v => N(v), d: 0 }, { k: 'opp', l: 'Fee pool', fmt: v => $$$(v), h: 'Fee pool a year ($)', d: 0 }, { k: 'perhh', l: 'Per household', fmt: v => $$$(v), h: 'Fee pool per household ($)', d: 2 }, { k: 'mass', l: 'Mass', fmt: v => N(v, 0), h: 'Matter mass a year', d: 1 }, { k: 'eff', l: 'Median eff.', fmt: v => N(v, 0), h: 'Median efficiency percentile', d: 1 }, { k: 'comp', l: 'Median comp.', fmt: v => N(v, 0), h: 'Median competition percentile', d: 1 }, { k: 'anchors', l: 'Anchor', fmt: v => N(v), d: 0 }, { k: 'white', l: 'Whitespace', fmt: v => N(v), d: 0 }];
    const ciCols = [{ k: 'name', l: 'City', fmt: v => esc(v) }, { k: 'counties', l: 'County', fmt: v => esc(v), cls: 'l' }, { k: 'zips', l: 'ZIPs', fmt: v => N(v), d: 0 }, { k: 'pop', l: 'Population', fmt: v => N(v), d: 0 }, { k: 'opp', l: 'Fee pool', fmt: v => $$$(v), h: 'Fee pool a year ($)', d: 0 }, { k: 'perhh', l: 'Per household', fmt: v => $$$(v), h: 'Fee pool per household ($)', d: 2 }, { k: 'eff', l: 'Median eff.', fmt: v => N(v, 0), h: 'Median efficiency percentile', d: 1 }, { k: 'anchors', l: 'Anchor', fmt: v => N(v), d: 0 }, { k: 'white', l: 'Whitespace', fmt: v => N(v), d: 0 }];
    const coRows = () => roll(r => r.z.county_name); const ciRows = () => roll(r => r.z.city);
    const coT = table(R('#pdCo'), { caption: 'County rollup', cols: coCols, rows: coRows(), sort: { k: 'opp', dir: -1 } });
    const ciT = table(R('#pdCi'), { caption: 'City rollup', cols: ciCols, rows: ciRows(), sort: { k: 'opp', dir: -1 }, limit: 60 });
    /* ---------- method ---------- */
    function prose() {
      R('#pdMeth').innerHTML = [
        `<b>Matter mass ${gradeB('B')} to ${gradeB('C')}.</b> Each ZIP's allocated filings by line for the last twelve months (county filings spread by married adults times the modeled hazard; adoption, CPS and prenups by the ZIP's share or composition), kept at the fee paying share (protective order respondents ${N(SEV_MODEL.rate('poRespondentShare'))}%, privately paying IV-D parents ${N(SEV_MODEL.rate('ivdPrivShare'))}%, CPS parents who are not indigent ${N(SEV_MODEL.rate('cpsNonIndigentShare'))}%, grade D) and weighted by who can pay: ${N(SEV_MODEL.rate('payLow'), 2)} for households under $35,000, ${N(SEV_MODEL.rate('payMid'), 2)} for $35,000 to $60,000, 1 above. The ten additive lines only; the high asset, military and gray lenses sit inside divorce.`,
        `<b>Fee value ${gradeB('C')}.</b> The fee value index is the square root of the ZIP's median household income over the metro median, bounded 0.7 to 1.6: a ZIP with four times the median income is worth twice the fee, not four times. The fee pool is mass times the collected value per matter (the shared store, grade D) plus the pipeline credit for follow on matters.`,
        `<b>Competition and cost ${gradeB('C')}.</b> Law offices within ${N(SEV_MODEL.rate('radiusKm'))} km per 1,000 married within the same radius (ZIP centers in the metro map's projection, about 1% at metro scale), raised where Competitor Watch logs live rival ads for the county, ranked within the metro. The click cost index is 0.55 plus 1.55 times (0.6 competition percentile plus 0.4 fee value percentile), bounded 0.55 to 2.10 (grade D): auctions are dearer where firms are dense and incomes high.`,
        `<b>Opportunity and efficiency.</b> Opportunity is the fee pool; efficiency is the fee pool over the click cost index. Both are percentile ranked within the metro and blended 65/35 with the same measure summed over the radius, because search is bought in radii and a strong ZIP among weak ones is worth less than its polygon.`,
        `<b>Quadrants and tiers.</b> Opportunity at the 65th percentile or above and competition at the 60th or above is an Anchor; high opportunity with competition below the 60th is Whitespace; the rest are Niche and Avoid. Efficiency bands map to tiers A+ (95 and up), A (85), B (70), C (50), D (30) and E (below 30) with starting bid modifiers of +45%, +30%, +15%, 0, minus 20% and minus 40%: a cold start prior, replaced by the observed cost per retained matter after sixty to ninety days.`,
        `<b>Search demand ${gradeB('D')}.</b> A stated metro total of monthly searches (default ${N(SEV_MODEL.rate('searchPerFiling'), 1)} for every private family filing a year) is spread across ZIPs by matter mass. Replace it with the metro total from Keyword Planner inside the account.`
      ].map(x => `<li>${x}</li>`).join('');
      const jl = a => `<dl class="pd-judg">${a.map(([t, d]) => `<dt>${esc(t)}</dt><dd>${esc(d)}</dd>`).join('')}</dl>`;
      R('#pdJudg').innerHTML = jl([
        ['Ability to pay is weighted, not excluded', 'Lower income households file and retain lawyers too. Weights of 0.35 and 0.7 keep them in the ranking without letting volume alone lead it.'],
        ['Protective order applicants pay nothing to file', 'Applicants pay no filing, service or clerk fee (Fam. Code § 81.002) and prosecutors can apply for them (§ 82.002), so the respondent share is the private fee market.'],
        ['Appointed counsel in DFPS suits', 'Indigent parents in suits filed by DFPS receive appointed counsel (§ 107.013); only the parents who are not indigent count as fee paying.'],
        ['IV-D is the Attorney General\'s', 'The Attorney General is the Title IV-D agency (ch. 231) and its lawyers represent the state; private demand is the parent who wants representation at the IV-D docket.'],
        ['Never a contingent fee', 'A contingent fee is never offered, advertised or modeled for a family matter (Rule 1.04; the compliance engine blocks the language).'],
        ['Law offices are the competition', 'The ZIP Business Patterns count every kind of law office. It misses firms that only advertise, which Competitor Watch adds when the firm logs them.'],
        ['The radius', `${N(SEV_MODEL.rate('radiusKm'))} km (about 5 miles) is the radius a local search campaign buys inside a metro; it is editable in the Service Lines rates.`],
        ['Benchmarks are national', 'The WordStream and LocaliQ CPC and conversion rates average the country and the year; they are defaults, graded D for this firm.']
      ]);
      R('#pdNot').innerHTML = jl([['Keyword volumes', 'No keyword tool was queried; search figures are a stated total spread by matter mass.'], ['Local Services pricing', 'Local Services cost per lead varies by market and week; the stated cost is a default.'], ['Competitor spend', 'Nothing estimates what any firm spends; Competitor Watch logs what the firm observes.'], ['Client data', 'No client names or matter details (Rule 1.05); Accounts reads counts, spend and rates only.'], ['Protected characteristics', 'No targeting by race, religion, national origin, sex or family status. Spanish creative follows the firm profile\'s languages and is always paired with English.']]);
    }
    /* ---------- render ---------- */
    function renderAll() { fillCty(); draw(); kpis(); zipBox(); shortlist(); tbl.setRows(rowsT()); coT.setRows(coRows()); ciT.setRows(ciRows()); fillInputs(); prose(); }
    function fillCty() { const s = R('#pdCty'); if (s.dataset.m !== st.metro) { s.innerHTML = [['', 'All counties']].concat(MSA[st.metro].counties.filter(f => CI[f]).map(f => [f, CI[f].name + ' County'])).map(o => `<option value="${esc(o[0])}">${esc(o[1])}</option>`).join(''); s.dataset.m = st.metro; } s.value = st.cty; }
    function scopeChanged() { draw(); scatterDraw(); shortlist(); tbl.setRows(rowsT()); }
    function setMetro(code) { if (!metroOK(code)) return; st.metro = code; store.set('sev.metro', code); R('#pdMetro').value = code; st.sel = null; st.cty = ''; renderAll(); }
    R('#pdMetro').onchange = e => setMetro(e.target.value);
    R('#pdLayer').onchange = e => { st.layer = e.target.value; savePaid(); draw(); };
    R('#pdCty').onchange = e => { st.cty = e.target.value; if (!st.cty) st.reset = true; scopeChanged(); };
    R('#pdQuadF').onchange = e => { st.quad = e.target.value; scopeChanged(); };
    R('#pdAng').onchange = e => { st.angle = e.target.value; scopeChanged(); };
    R('#pdPinF').onchange = e => { st.pins.firm = e.target.checked; savePaid(); draw(); }; R('#pdPinW').onchange = e => { st.pins.watch = e.target.checked; savePaid(); draw(); };
    let fT = 0; R('#pdFilter').oninput = () => { clearTimeout(fT); fT = setTimeout(() => tbl.setRows(rowsT()), 200); };
    R('#pdRank').onchange = e => { st.rank = PD_RANK[e.target.value] ? e.target.value : 'effb'; savePaid(); shortlist(); };
    R('#pdN').onchange = e => { st.n = clamp(Math.round(+e.target.value) || 25, 5, 300); e.target.value = st.n; savePaid(); shortlist(); };
    R('#pdLine').onchange = e => { st.line = e.target.value; savePaid(); fillInputs(); calc(); };
    Object.keys(BIND).concat(['pdSrch']).forEach(id => { R('#' + id).oninput = e => writeIn(e.target); });
    /* ---------- exports ---------- */
    const campName = () => DK_TAB_OF(st.metro) + '_' + st.line.toUpperCase() + '_SEARCH';
    const noIdMsg = s => { const miss = s.filter(r => !r.z.gt).map(r => r.zip); return miss.length ? ` ${miss.length} of these ZIPs (${miss.join(', ')}) have no Google criterion ID in the August 2026 geotargets file; the Location text lets Ads Editor match them by name, so check them after the import.` : ''; };
    R('#pdGoogle').onclick = () => { const s = short(); R('#pdExpMsg').textContent = `Google Ads locations: the top ${s.length} ZIPs by ${PD_RANK[st.rank].l.toLowerCase()} with their tier bid modifiers, campaign ${campName()}.${noIdMsg(s)}`; exportText(expName('paid_google_locations', geoScope()), csv(s.map(r => ({ camp: campName(), loc: r.zip + ', Texas, United States', id: r.z.gt || '', bid: (r.bid > 0 ? '+' : '') + r.bid + '%', type: 'Location', status: 'Enabled' })), [{ l: 'Campaign', k: 'camp' }, { l: 'Location', k: 'loc' }, { l: 'ID', k: 'id' }, { l: 'Bid Modifier', k: 'bid' }, { l: 'Criterion Type', k: 'type' }, { l: 'Status', k: 'status' }], { platform: true })); };
    R('#pdMeta').onclick = () => { const s = short(); const K = PD_RANK[st.rank]; R('#pdExpMsg').textContent = `Meta ad set ZIP list for ${LINE_META[st.line].name}, ${geoScope()}: the top ${s.length} ZIPs by ${K.l.toLowerCase()}. Paste the Zip column into the ad set's locations. Write the ads to the situation in the third person: Meta rejects ad text that asserts or implies the viewer's own situation (module 11 screens for it).`; exportText(expName('paid_meta_zips', geoScope()), csv(s.map(r => ({ k: 'US:' + r.zip, zip: r.zip, city: r.z.city, county: r.z.county_name, tier: r.tier, quad: FLM.QN[r.quad], rank: K.v(r) })), [{ l: 'Zip', k: 'k' }, { l: 'zip', k: 'zip' }, { l: 'city', k: 'city' }, { l: 'county', k: 'county' }, { l: 'tier', k: 'tier' }, { l: 'quadrant', k: 'quad' }, { l: 'rank_value', k: 'rank', d: 2 }], { platform: true })); };
    R('#pdAll').onclick = () => exportText(expName('paid_zips', geoScope()), csv(tbl.sorted(), xcols(cols)));
    R('#pdCoX').onclick = () => exportText(expName('paid_county_rollup', geo()), csv(coT.sorted(), xcols(coCols)));
    R('#pdCiX').onclick = () => exportText(expName('paid_city_rollup', geo()), csv(ciT.sorted(), xcols(ciCols)));
    R('#pdDesk').onclick = () => { const s = short(); if (!s.length) { R('#pdExpMsg').textContent = 'No ZIP in this scope has matters; widen the county, quadrant or angle.'; return; } const bids = {}; s.forEach(r => { bids[r.zip] = r.bid; }); goModule('desk', { geo: 'msa:' + st.metro, zips: s.map(r => r.zip), line: st.line, bids }); };
    R('#pdLines').onclick = () => goModule('lines', st.sel && C().by[st.sel] ? { zip: st.sel, line: st.line } : { metro: st.metro, county: st.cty || undefined, line: st.line });
    R('#pdWatch').onclick = () => goModule('watch', st.sel && ZI[st.sel] ? { county: ZI[st.sel].county, zip: st.sel } : { metro: st.metro });
    R('#pdAsm').onclick = () => exportText(expName('paid_assumptions', geoScope(), 'json'), JSON.stringify({ module: 'Paid Acquisition (07)', exported: todayISO(), metro: { code: st.metro, name: geo() }, scope: { county: st.cty || null, quadrant: st.quad === '' ? null : FLM.QN[+st.quad], angle: st.angle || null }, line: { key: st.line, name: LINE_META[st.line].name }, shortlist: { rank_by: PD_RANK[st.rank].l, size: st.n, zips: short().map(r => ({ zip: r.zip, tier: r.tier, bid: r.bid })) }, metro_searches_a_month: { value: Math.round(srch()), source: isN(st.searches[st.metro]) ? 'your input' : 'default (grade D): ' + SEV_MODEL.rate('searchPerFiling') + ' a month per private family filing a year' }, model: SEV_MODEL.snapshot(), method: { payer_weight: 'payLow under $35,000, payMid $35,000 to $60,000, 1 above', fee_value_index: 'sqrt(ZIP median household income / metro median), 0.7 to 1.6', click_cost_index: '0.55 + 1.55 x (0.6 competition pct + 0.4 value pct)', blend: '65/35 with the radius sum', quadrant: 'opportunity 65th, competition 60th percentile', tiers: FLM.TIERS.map((t, i) => ({ tier: t, from_pct: Math.max(0, FLM.TIER_CUT[i]), bid_pct: FLM.TIER_BID[i] })) }, sources: { cpc: 'median legal services CPC, Google search, Apr 2025 to Mar 2026 (WordStream)', conversion: 'median legal conversion 5.55%; family law 8.52% in the 2023 LocaliQ cut', filings: 'county filings (Texas OCA, ' + ttmSpan() + ') allocated to ZIPs by married adults times the modeled hazard', offices: 'ZIP Business Patterns 2023' } }, null, 2), 'application/json');
    // the shared store, the firm's offices and the watch list redraw what depends on them
    BUS.on('model', () => { if (root.isConnected) renderAll(); });
    BUS.on('firm', () => { if (root.isConnected) { draw(); zipBox(); } });
    renderAll();
    // goModule('paid', {metro, zip, line}): the metro tabs and the index hand over their metro
    this.receive = p => { if (!p) return; if (p.metro && metroOK(p.metro) && p.metro !== st.metro) setMetro(p.metro); if (p.zip && ZI[p.zip] && metroOK(ZI[p.zip].msa) && ZI[p.zip].msa !== st.metro) setMetro(ZI[p.zip].msa); if (p.line && LINE_META[p.line] && p.line !== st.line) { st.line = p.line; R('#pdLine').value = st.line; savePaid(); fillInputs(); calc(); } if (p.zip && ZI[p.zip] && ZI[p.zip].msa === st.metro) pick(p.zip); };
  }
});
// a metro's short campaign code: the six big metros by their usual letters, the rest by their first city
function DK_TAB_OF(code) { const k = { '19100': 'DFW', '26420': 'HOU', '41700': 'SAT', '12420': 'AUS', '21340': 'ELP', '32580': 'RGV', '15180': 'RGV' }[code]; return k || (MNAME((MSA[code] || {}).title || 'TX').split(' / ')[0].toUpperCase().replace(/[^A-Z0-9]+/g, '').slice(0, 10) || 'TX'); }
