'use strict';
/* Module 08: Supply Line */
registerModule({
  key: 'supply', num: '08', title: 'Supply Line', desc: 'Law offices and legal jobs against the filings they compete for, by county and ZIP',
  mount(root) {
    const st = { layer: 'fpo', sel: store.get('sev.county', '48201') };
    const L = {
      fpo: { l: 'Private family filings per law office (higher = less competition)', ramp: 'moss', v: c => c.rates.filings_per_lawoffice, f: v => N(v, 1) },
      offices: { l: 'Law offices (County Business Patterns 2023)', ramp: 'slate', v: c => c.rates.lawoffices, f: v => N(v), log: true },
      per10k: { l: 'Law offices per 10,000 residents', ramp: 'slate', v: c => c.rates.lawoffices ? c.rates.lawoffices / c.pop2025 * 10000 : null, f: v => N(v, 2) },
      emp: { l: 'Legal services employment', ramp: 'slate', v: c => c.rates.legal_emp, f: v => N(v), log: true },
      divpo: { l: 'Divorce filings per law office', ramp: 'moss', v: c => c.rates.lawoffices ? (c.filings.ttm.div || 0) / c.rates.lawoffices : null, f: v => N(v, 1) }
    };
    const offices = sum(CTY.map(c => c.rates.lawoffices || 0)); const emp = sum(CTY.map(c => c.rates.legal_emp || 0)); const priv = sum(CTY.map(c => c.filings.ttm.priv || 0));
    const none = CTY.filter(c => !c.rates.lawoffices);
    // the range in the dek comes from the data: counties with 200 or more private filings, the most crowded and the least
    const rng = CTY.filter(c => (c.filings.ttm.priv || 0) >= 200 && c.rates.filings_per_lawoffice).sort((a, b) => a.rates.filings_per_lawoffice - b.rates.filings_per_lawoffice);
    const lo2 = rng.slice(0, 2), hi2 = rng.slice(-2).reverse(); const offs = c => `${N(c.rates.lawoffices)} office${c.rates.lawoffices === 1 ? '' : 's'}`;
    root.innerHTML = mastHTML({ eyebrow: 'Module 08 · Supply Line · County and ZIP Business Patterns 2023 against court filings', title: 'Supply Line', dek: `Demand means nothing without the other side of the ratio. The Census counts ${N(offices)} offices of lawyers in Texas employing ${N(emp)} people; set against ${N(priv)} private family law filings a year that is ${N(priv / offices, 1)} filings per office statewide. Among counties with 200 or more private filings a year the range runs from about ${N(lo2[0].rates.filings_per_lawoffice, 0)} in ${esc(lo2[0].name)} and ${N(lo2[1].rates.filings_per_lawoffice, 0)} in ${esc(lo2[1].name)} to ${N(hi2[0].rates.filings_per_lawoffice, 0)} in ${esc(hi2[0].name)} (${offs(hi2[0])}) and ${N(hi2[1].rates.filings_per_lawoffice, 0)} in ${esc(hi2[1].name)} (${offs(hi2[1])}). ${none.length} counties have no law office with employees in the Census count; their filings go to solo lawyers the count leaves out (County Business Patterns counts only offices with a payroll) or to lawyers in the next county over.`, facts: [[N(offices), 'law offices, Texas (NAICS 541110)'], [N(emp), 'legal services jobs'], [N(priv / offices, 1), 'private family filings per office'], [String(none.length), 'counties with no employer law office']] }) + `
    <div class="toolbar"><span class="ttl">Supply Line</span><span class="sub">Offices, jobs and filings per office</span><span class="sp"></span><button class="btn" id="spCsv">↓ Supply by county CSV</button></div>
    <div class="callout judg"><div class="h">Judgment call: all law offices, not family law offices</div><p>The Census does not separate family law from other practices, and no public file counts Texas family lawyers by county (the State Bar publishes attorney counts by county in its statistical profile, not by practice area; Board Certified family law specialists are listed by the Texas Board of Legal Specialization but not in a downloadable file). The office count therefore overstates competition in downtown ZIPs full of corporate and litigation firms and is close to right in suburban and rural counties, where most offices are general practices that take family cases. Read the ratio as a floor on opportunity in the big cities and as an honest number everywhere else. One more gap runs the other way: County Business Patterns counts only offices with a payroll, so solo lawyers without employees (the Census nonemployer statistics) are not in any of these counts, and a county shown with no law office may still have a lawyer or two.</p></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', sel('spLayer', Object.keys(L).map(k => [k, L[k].l]), st.layer))}</div><div class="split"><div class="mapwrap" id="spMap"></div><div id="spSide"></div></div></div>
    <div class="grid2 even"><div class="panel"><h3>Most underserved counties</h3><div class="sub">Highest private family filings per law office among counties with at least 200 filings a year.</div><div class="chart" id="spUnder"></div></div><div class="panel"><h3>Most crowded counties</h3><div class="sub">Lowest filings per office among counties with at least 200 filings a year, on the same scale as the chart beside it.</div><div class="chart" id="spCrowd"></div></div></div>
    <div class="panel"><h3>Counties</h3><div id="spTable"></div></div>`;
    const mapEl = $('#spMap');
    // counties with no law office are a true zero, not missing data: they get their own swatch (legal jobs can still be reported there)
    const noOffice = id => !CI[id].rates.lawoffices;
    function draw() { const lay = L[st.layer]; const sc = layerScale(lay, CTY); const alt = st.layer === 'emp' ? null : { test: noOffice, color: 'var(--alt-fill)', label: 'no law office' }; drawMap(mapEl, { title: lay.l, W: GEO.state.W, H: GEO.state.H, paths: GEO.state.county, value: id => lay.v(CI[id]), color: sc.color, alt, noDataLabel: st.layer === 'emp' ? 'not published' : 'no data', label: id => countyTipHTML(CI[id], `<div class="row"><span>${esc(lay.l)}</span><span>${alt && noOffice(id) && !isN(lay.v(CI[id])) ? 'no law office' : esc(lay.f(lay.v(CI[id])))}</span></div>`), onSelect: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); tbl.setSel(id); }, selected: st.sel, outline: GEO.state.outline, legend: Object.assign({ title: lay.l }, sc.legend) }); }
    function side() { const c = CI[st.sel]; const cb = c.cbp || {}; const zips = ZC.filter(z => z.county === c.fips).sort((a, b) => (b.lawoffices || 0) - (a.lawoffices || 0)).slice(0, 8); $('#spSide').innerHTML = `<h3 style="font-family:var(--display);font-size:20px">${esc(c.name)} County</h3><dl class="kv"><dt>Law offices</dt><dd>${c.rates.lawoffices ? N(c.rates.lawoffices) : 'none in the Census count'}</dd><dt>Legal services establishments</dt><dd>${N(cb.legal ? cb.legal.est : null)}</dd><dt>Legal services jobs</dt><dd>${N(c.rates.legal_emp)}</dd><dt>Offices under 5 employees</dt><dd>${N(cb.lawoffices ? +cb.lawoffices['n<5'] : null)}</dd><dt>Offices with 20 or more employees</dt><dd>${(() => { const lo = cb.lawoffices; if (!lo || !isN(+lo.est)) return NA; const big = +lo.est - (+lo['n<5'] || 0) - (+lo.n5_9 || 0) - (+lo.n10_19 || 0); const mid = +lo.n20_49 || 0; return N(big) + (big > mid ? ` (${N(big - mid)} with 50 or more)` : ''); })()}</dd><dt>Private family filings, 12 mo</dt><dd>${N(c.filings.ttm.priv)}</dd><dt>Filings per office</dt><dd>${N(c.rates.filings_per_lawoffice, 1)}</dd><dt>Divorce filings per office</dt><dd>${N(c.rates.lawoffices ? (c.filings.ttm.div || 0) / c.rates.lawoffices : null, 1)}</dd><dt>Offices per 10,000 residents</dt><dd>${N(c.rates.lawoffices ? c.rates.lawoffices / c.pop2025 * 10000 : null, 2)}</dd></dl>${zips.length ? `<h4 style="font-family:var(--mono);font-size:10.5px;letter-spacing:.1em;text-transform:uppercase;color:var(--ink-3);margin:10px 0 4px">ZIPs with the most law offices</h4><table class="t"><caption class="vh">ZIPs in ${esc(c.name)} County with the most law offices</caption><thead><tr><th scope="col">ZIP</th><th scope="col" class="l">City</th><th scope="col">Offices</th><th scope="col">Expected div/yr</th></tr></thead><tbody>${zips.map(z => `<tr><td>${esc(z.zip)}</td><td class="l">${esc(z.city)}</td><td>${z.lawoffices ? N(z.lawoffices) : 'none'}</td><td>${N(z.alloc.div, 0)}</td></tr>`).join('')}</tbody></table>` : ''}`; }
    // a matched pair: equal widths, one scale (the larger chart's maximum), the supply ramp's colors
    const big = rng; const spMax = Math.max(...big.map(c => c.rates.filings_per_lawoffice));
    barChart($('#spUnder'), { title: 'Most underserved counties', rows: big.slice().reverse().slice(0, 14).map(c => ({ label: c.name + ' (' + offs(c) + ')', value: c.rates.filings_per_lawoffice, color: 'var(--rp-teal-6)' })), W: 520, lw: 190, max: spMax, fmt: v => N(v, 1) });
    barChart($('#spCrowd'), { title: 'Most crowded counties', rows: big.slice(0, 14).map(c => ({ label: c.name + ' (' + offs(c) + ')', value: c.rates.filings_per_lawoffice, color: 'var(--rp-teal-3)' })), W: 520, lw: 190, max: spMax, fmt: v => N(v, 1) });
    const cols = [{ k: 'name', l: 'County', fmt: v => esc(v) }, { k: 'pop', l: 'Pop 2025', fmt: v => N(v), h: 'Population 2025 (Census Vintage 2025)', d: 0 }, { k: 'offices', l: 'Law offices', fmt: v => N(v), h: 'Law offices (CBP 2023, NAICS 541110)', d: 0 }, { k: 'emp', l: 'Legal jobs', fmt: v => isN(v) ? N(v) : 'not published', h: 'Legal services jobs (CBP 2023)', d: 0 }, { k: 'per10k', l: 'Offices /10k', fmt: v => N(v, 2), h: 'Law offices per 10,000 residents', d: 2 }, { k: 'priv', l: 'Private filings', fmt: v => N(v), h: 'Private family filings, last 12 months', d: 0 }, { k: 'fpo', l: 'Filings/office', fmt: (v, r) => r.offices ? N(v, 1) : 'no office', h: 'Private family filings per law office', d: 1 }, { k: 'div', l: 'Divorce', fmt: v => N(v), h: 'Divorce filings, last 12 months', d: 0 }, { k: 'dpo', l: 'Divorce/office', fmt: (v, r) => r.offices ? N(v, 1) : 'no office', h: 'Divorce filings per law office', d: 1 }, { k: 'di', l: 'Index', fmt: v => N(v, 0), h: 'Dissolution Index (percentile)', d: 0 }, { k: 'msa', l: 'Metro', fmt: v => esc(v), cls: 'l wrap', h: 'Metro area' }];
    const rows = () => CTY.map(c => ({ _id: c.fips, name: c.name, pop: c.pop2025, offices: c.rates.lawoffices || 0, emp: c.rates.legal_emp, per10k: c.rates.lawoffices ? c.rates.lawoffices / c.pop2025 * 10000 : 0, priv: c.filings.ttm.priv, fpo: c.rates.filings_per_lawoffice, div: c.filings.ttm.div, dpo: c.rates.lawoffices ? (c.filings.ttm.div || 0) / c.rates.lawoffices : null, di: c.di, msa: c.msa_title ? MNAME(c.msa_title) : 'non metro' }));
    const tbl = table($('#spTable'), { caption: 'Counties by law office supply', cols, rows: rows(), sort: { k: 'fpo', dir: -1 }, onRow: id => { st.sel = id; store.set('sev.county', id); markSel(mapEl, id); side(); tbl.setSel(id); }, selected: st.sel });
    $('#spLayer').onchange = e => { st.layer = e.target.value; draw(); };
    $('#spCsv').onclick = () => exportText(expName('supply', 'texas'), csv(tbl.sorted(), xcols([cols[0], { k: '_id', l: 'FIPS' }].concat(cols.slice(1)))));
    draw(); side();
    this.sync = () => { const f = store.get('sev.county', st.sel); if (CI[f] && f !== st.sel) { st.sel = f; markSel(mapEl, f); side(); tbl.setSel(f); } };
    this.receive = p => { if (p && CI[p.county]) { store.set('sev.county', p.county); this.sync(); } };
  },
  onShow() { if (this.sync) this.sync(); }
});
