'use strict';
/* Module 09: Timing Desk */
registerModule({
  key: 'timing', num: '09', title: 'Timing Desk', desc: 'Seasons, lags and the twelve month media calendar: when each line files, and when a shock pays out',
  mount(root) {
    const st = { cty: store.get('sev.county', '48201'), line: 'div' };
    const S = ST.seas; const lines = [['div', 'Divorce'], ['div_k', 'Divorce with children'], ['sapcr', 'Custody, SAPCR'], ['po', 'Protective orders'], ['mod', 'Modifications'], ['enf', 'Enforcement'], ['ivd', 'Title IV-D'], ['priv', 'All private family law']];
    const m = ST.monthly; const t0 = m.t0;
    // month-of-year averages by year for divorce, to show Jan vs Mar each year
    const byYear = {}; m.div.forEach((v, i) => { const y = Math.floor((t0 + i) / 12), mo = (t0 + i) % 12; (byYear[y] = byYear[y] || [])[mo] = v; });
    // 'Protective orders peak in August, modifications in March' or, when the months coincide, 'Protective orders, modifications and
    // custody suits all peak in August'
    const peakOf = k => MOL[S[k].indexOf(Math.max(...S[k]))];
    const andList = a => a.length < 2 ? a.join('') : a.slice(0, -1).join(', ') + ' and ' + a[a.length - 1];
    const peaks = (() => { const items = [['Protective orders', 'po'], ['modifications', 'mod'], ['custody suits', 'sapcr']].map(([n, k]) => [n, peakOf(k)]); const by = []; items.forEach(([n, mo]) => { const g = by.find(x => x.mo === mo); if (g) g.n.push(n); else by.push({ mo, n: [n] }); }); if (by.length === 1) return `${andList(by[0].n)} all peak in ${by[0].mo}.`; return by.map((g, i) => `${andList(g.n)}${i === 0 ? (g.n.length > 1 ? ' both peak in ' : ' peak in ') : ' in '}${g.mo}`).join(', ') + '.'; })();
    root.innerHTML = mastHTML({ eyebrow: 'Module 09 · Timing Desk · seasonality from 92 months of statewide filings and the lag model', title: 'Timing Desk', dek: `The divorce industry's calendar says January. The Texas courthouse says March: filings run ${N(S.div[2], 0)} against an average month of 100, with a second lift in August (${N(S.div[7], 0)}) when school starts and a trough in November and December (${N(S.div[10], 0)} and ${N(S.div[11], 0)}). The consult happens four to eight weeks before the petition and the decree cannot come before day 61, so the search calendar sits about a month ahead of the filing calendar. ${peaks}`, facts: [['March', 'peak divorce filing month, index ' + N(S.div[2], 0)], ['December', 'trough, index ' + N(S.div[11], 0)], ['12 months', 'lag at which a claims surge lifts filings most'], ['Day 61', 'earliest decree after filing (§ 6.702)']] }) + `
    <div class="toolbar"><span class="ttl">Timing Desk</span><span class="sub">Season by line, county calendar, budget weights</span><span class="sp"></span><button class="btn" id="tmCsv">↓ Monthly weights CSV</button></div>
    <div class="callout note"><div class="h">Read this first: three clocks</div><p><b>The season clock.</b> Every line has a shape and they are not the same: divorce and custody rise into spring, protective orders climb through the summer, modifications and enforcement track the school calendar and the support paperwork cycle. <b>The shock clock.</b> When claims surge in a county, divorce filings fall the same month and recover about twelve months later; enforcement and modification move first. <b>The court clock.</b> Sixty days minimum, two to four months for an agreed divorce, nine to twenty four months contested; fee revenue lands months after the click. Plan spend against the first two and cash against the third.</p></div>
    <div class="panel" style="margin-bottom:14px"><h3>Season by line</h3><div class="sub">Statewide monthly index, 2022 to 2025 average = 100.</div><div class="tabs" id="tmLines" role="group" aria-label="Service line">${lines.map(l => `<button type="button" data-l="${l[0]}" aria-pressed="${st.line === l[0]}" class="${st.line === l[0] ? 'on' : ''}">${l[1]}</button>`).join('')}</div><div id="tmSeas"></div><div class="chart" id="tmYears" style="margin-top:10px"></div></div>
    <div class="grid2"><div class="panel"><h3>County calendar</h3><div class="sub">Expected filings by month for the next twelve months: the county's trailing twelve month total spread by the statewide season for the chosen line, adjusted by the county's own monthly pattern where a series exists.</div><div class="controls">${ctl('County', sel('tmCty', CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.cty))}</div><div class="cal" id="tmCal"></div></div>
    <div class="panel"><h3>Budget weights</h3><div class="sub">Share of an annual search budget to place in each month if spend follows expected consultations (filings shifted one month earlier), for the chosen line.</div><div id="tmWeights"></div><p class="small" style="margin-top:8px">Weights sum to 100. A flat calendar would be 8.3 in every month. The shift assumes the consultation precedes the petition by about a month; move it to two months for contested lines and to zero for protective orders, which file the week of the incident.</p></div></div>
    <div class="panel"><h3>Shock calendar</h3><div class="sub" id="tmShockSub"></div><div class="seg" id="tmShockSeg" role="group" aria-label="Which counties" style="margin:0 0 10px"><button type="button" data-v="up" aria-pressed="true">Claims rising</button><button type="button" data-v="all" aria-pressed="false">Largest changes, either way</button></div><div id="tmShock"></div></div>`;
    function seas() { const idx = S[st.line]; seasBlock($('#tmSeas'), idx, 'ember'); const yrs = Object.keys(byYear).map(Number).filter(y => y >= 2022 && y <= 2025); lineChart($('#tmYears'), { title: 'Divorce filings by month, 2022 to 2025', series: yrs.map((y, i) => ({ name: String(y), color: ['var(--s1)', 'var(--s2)', 'var(--s3)', 'var(--s4)'][i], values: (byYear[y] || []).map((v, mo) => ({ x: mo, y: v })) })), W: 900, H: 200, ymin: 0, xfmt: v => MOL[v], xTicks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], xTickFmt: v => MO[v], yfmt: v => N(v) }); weights(); cal(); }
    function ctySeason() { const c = CI[st.cty]; const s = c.filings.series; const key = { div: 'div', div_k: 'div_k', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', priv: 'priv' }[st.line]; if (!s || !s[key]) return S[st.line]; const arr = s[key]; const acc = Array(12).fill(0), cnt = Array(12).fill(0); arr.forEach((v, i) => { const t = s.t0 + i; const y = Math.floor(t / 12); if (y >= 2022 && y <= 2025) { acc[t % 12] += v; cnt[t % 12]++; } }); const mm = acc.map((v, i) => cnt[i] ? v / cnt[i] : null); const avg = mean(mm); const own = mm.map(v => isN(v) && avg ? v / avg * 100 : 100); const tot = sum(arr.slice(-12)); const w = tot / (tot + 600); return own.map((v, i) => w * v + (1 - w) * S[st.line][i]); }
    function cal() { const c = CI[st.cty]; const key = { div: 'div', div_k: 'div_k', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', priv: 'priv' }[st.line]; const tot = c.filings.ttm[key] || 0; const idx = ctySeason(); const isum = sum(idx); const now = new Date(2026, 8); const out = []; for (let i = 0; i < 12; i++) { const d = new Date(now.getFullYear(), now.getMonth() + 1 + i); const mo = d.getMonth(); out.push({ label: MO[mo] + ' ' + d.getFullYear(), v: tot * idx[mo] / isum, idx: idx[mo] }); } $('#tmCal').innerHTML = out.map(o => `<div><span class="small">${o.label}</span><b>${N(o.v, 0)}</b><span class="small">index ${N(o.idx, 0)}</span></div>`).join(''); }
    // budget weight of each month: the season index shifted one month earlier (none for protective orders), as a percent of the year
    function weightsOf(line) { const idx = S[line]; const shift = line === 'po' ? 0 : 1; const w = idx.map((v, i) => idx[(i + shift) % 12]); const ws = sum(w); return w.map(v => v / ws * 100); }
    function weights() { const w = weightsOf(st.line); $('#tmWeights').innerHTML = `<div class="seas">${w.map((v, i) => { const bg = rampColor('ember', clamp((v - 6) / 6, 0, 1) * 0.85 + 0.05); return `<div style="background:${bg};color:${inkOn(bg)}"><b>${v.toFixed(1)}</b>${MO[i]}</div>`; }).join('')}</div>`; }
    $$('#tmLines button').forEach(b => b.onclick = () => { st.line = b.dataset.l; $$('#tmLines button').forEach(x => { x.classList.toggle('on', x === b); x.setAttribute('aria-pressed', String(x === b)); }); seas(); });
    $('#tmCty').onchange = e => { st.cty = e.target.value; cal(); };
    // the shock calendar: counties with 150 or more claims in 13 weeks. The lag model's largest positive divorce effect is at twelve
    // months, so each county's 12 month effect lands twelve months after the week in its window that moved most against a year earlier.
    const wkDate = (c, i) => { const d = dLocal(c.ui.week0); d.setDate(d.getDate() + i * 7); return d; };
    const moY = d => MO[d.getMonth()] + ' ' + d.getFullYear();
    const moveWeek = (c, up) => { const w = c.ui.weekly, n = w.length; let best = null, bi = n - 1; for (let i = Math.max(52, n - 13); i < n; i++) { if (!isN(w[i]) || !isN(w[i - 52])) continue; const d = (w[i] - w[i - 52]) * (up ? 1 : -1); if (best == null || d > best) { best = d; bi = i; } } return bi; };
    const prE = D.panel['lenf|claims_0_12|post2022'];
    const pool = CTY.filter(c => c.ui && c.ui.weekly && c.ui.w13 >= 150 && isN(c.econ.claims_vs_yago) && c.econ.claims_vs_yago > 0);
    function shockTable() {
      const up = st.shock !== 'all';
      const list = up ? pool.filter(c => c.econ.claims_vs_yago > 1).sort((a, b) => b.econ.claims_vs_yago - a.econ.claims_vs_yago).slice(0, 15) : pool.slice().sort((a, b) => Math.abs(Math.log(b.econ.claims_vs_yago)) - Math.abs(Math.log(a.econ.claims_vs_yago))).slice(0, 15);
      $('#tmShockSub').textContent = up ? `Counties where unemployment claims over the last 13 weeks run above the same weeks a year earlier (counties with 150 or more claims), with the filing changes the lag model expects: a dip in the same month, then a rise that peaks twelve months on.` : `The 15 counties whose claims moved most against a year earlier, rises and falls (counties with 150 or more claims). A fall in claims reverses the signs: a small lift in filings now and a small dip a year out.`;
      if (!list.length) { $('#tmShock').innerHTML = `<p class="small">No county with 150 or more claims in the last 13 weeks is running above a year earlier (claims through ${esc(fmtDate(META.ui_through))}). Switch to the largest changes either way to see where claims fell.</p>`; return; }
      $('#tmShock').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">Shock calendar</caption><thead><tr><th scope="col">County</th><th scope="col">Claims 13w</th><th scope="col">vs yr ago</th><th scope="col">Divorce now</th><th scope="col">+3 mo</th><th scope="col">+12 mo</th><th scope="col" class="l">12 month effect lands</th><th scope="col" title="Enforcement filings three months after the claims change, from the 2022 on enforcement model">Enforcement +3 mo</th></tr></thead><tbody>${list.map(c => { const e = c.econ.expected; const enf = (Math.exp(prE.coefs.lclaims_l3.coef * e.dlog_claims) - 1) * 100; const r = c.econ.claims_vs_yago; const lands = wkDate(c, moveWeek(c, r >= 1) + 52); return `<tr><td>${esc(c.name)}</td><td>${N(c.ui.w13)}</td><td>${r >= 1 ? '▲' : '▼'} ${N(r, 2)}×</td><td>${sgn(e.now_pct, 1)}</td><td>${sgn(e.m3_pct, 1)}</td><td>${sgn(e.m12_pct, 1)}</td><td class="l">${moY(lands)}</td><td>${sgn(enf, 1)}</td></tr>`; }).join('')}</tbody></table></div></div>${up && list.length < 5 ? `<p class="small" style="margin-top:6px">Only ${list.length === 1 ? 'one county is' : atWord(list.length) + ' counties are'} running above a year earlier; claims are flat or falling everywhere else.</p>` : ''}`;
    }
    const atWord = n => ['no', 'one', 'two', 'three', 'four', 'five'][n] || String(n);
    st.shock = 'up'; $$('#tmShockSeg button').forEach(b => b.onclick = () => { st.shock = b.dataset.v; $$('#tmShockSeg button').forEach(x => x.setAttribute('aria-pressed', String(x === b))); shockTable(); });
    shockTable();
    // both columns per line: the season index and the budget weight exactly as the Budget weights panel computes it
    $('#tmCsv').onclick = () => { const W = {}; lines.forEach(l => { W[l[0]] = weightsOf(l[0]); }); exportText(expName('timing_weights', 'texas'), csv(MOL.map((mo, i) => { const o = { month: mo }; lines.forEach(l => { o[l[0] + '_i'] = S[l[0]][i]; o[l[0] + '_w'] = W[l[0]][i]; }); return o; }), [{ l: 'Month', k: 'month' }].concat(...lines.map(l => [{ l: `${l[1]} season index (2022 to 2025 = 100)`, k: l[0] + '_i', d: 1 }, { l: `${l[1]} budget weight (% of the year${l[0] === 'po' ? ', no shift' : ', one month early'})`, k: l[0] + '_w', d: 1 }])))); };
    seas();
  }
});
