'use strict';
/* Module 09: Timing Desk */
registerModule({
  key: 'timing', num: '09', title: 'Timing Desk', desc: 'Seasons, lags and the twelve month media calendar: when each line files, and when a shock pays out',
  mount(root) {
    const st = { cty: store.get('sev.county', '48201'), line: 'div' };
    const S = ST.seas; const lines = [['div', 'Divorce'], ['div_k', 'Divorce with children'], ['sapcr', 'Custody, SAPCR'], ['po', 'Protective orders'], ['mod', 'Modifications'], ['enf', 'Enforcement'], ['ivd', 'Title IV-D'], ['priv', 'All private family law']];
    const m = ST.monthly; const t0 = m.t0;
    // month-of-year averages by year for divorce, to show Jan vs Mar each year
    const byYear = {}; m.div.forEach((v, i) => { const y = Math.floor((t0 + i) / 12), mo = (t0 + i) % 12; (byYear[y] = byYear[y] || [])[mo] = v; });
    root.innerHTML = mastHTML({ eyebrow: 'Module 09 · Timing Desk · seasonality from 92 months of statewide filings and the lag model', title: 'Timing Desk', dek: `The divorce industry's calendar says January. The Texas courthouse says March: filings run ${N(S.div[2], 0)} against an average month of 100, with a second lift in August (${N(S.div[7], 0)}) when school starts and a trough in November and December (${N(S.div[10], 0)} and ${N(S.div[11], 0)}). The consult happens four to eight weeks before the petition and the decree cannot come before day 61, so the search calendar sits about a month ahead of the filing calendar. Protective orders peak in ${MOL[S.po.indexOf(Math.max(...S.po))]}, modifications in ${MOL[S.mod.indexOf(Math.max(...S.mod))]}, custody suits in ${MOL[S.sapcr.indexOf(Math.max(...S.sapcr))]}.`, facts: [['March', 'peak divorce filing month, index ' + N(S.div[2], 0)], ['December', 'trough, index ' + N(S.div[11], 0)], ['12 months', 'lag at which a claims surge lifts filings most'], ['Day 61', 'earliest decree after filing (§ 6.702)']] }) + `
    <div class="toolbar"><span class="ttl">Timing Desk</span><span class="sub">Season by line, county calendar, budget weights</span><span class="sp"></span><button class="btn" id="tmCsv">↓ Monthly weights CSV</button></div>
    <div class="callout note"><div class="h">Read this first: three clocks</div><p><b>The season clock.</b> Every line has a shape and they are not the same: divorce and custody rise into spring, protective orders climb through the summer, modifications and enforcement track the school calendar and the support paperwork cycle. <b>The shock clock.</b> When claims surge in a county, divorce filings fall the same month and recover about twelve months later; enforcement and modification move first. <b>The court clock.</b> Sixty days minimum, two to four months for an agreed divorce, nine to twenty four months contested; fee revenue lands months after the click. Plan spend against the first two and cash against the third.</p></div>
    <div class="panel" style="margin-bottom:14px"><h3>Season by line</h3><div class="sub">Statewide monthly index, 2022 to 2025 average = 100.</div><div class="tabs" id="tmLines">${lines.map(l => `<button data-l="${l[0]}" class="${st.line === l[0] ? 'on' : ''}">${l[1]}</button>`).join('')}</div><div id="tmSeas"></div><div class="chart" id="tmYears" style="margin-top:10px"></div></div>
    <div class="grid2"><div class="panel"><h3>County calendar</h3><div class="sub">Expected filings by month for the next twelve months: the county's trailing twelve month total spread by the statewide season for the chosen line, adjusted by the county's own monthly pattern where a series exists.</div><div class="controls">${ctl('County', sel('tmCty', CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.cty))}</div><div class="cal" id="tmCal"></div></div>
    <div class="panel"><h3>Budget weights</h3><div class="sub">Share of an annual search budget to place in each month if spend follows expected consultations (filings shifted one month earlier), for the chosen line.</div><div id="tmWeights"></div><p class="small" style="margin-top:8px">Weights sum to 100. A flat calendar would be 8.3 in every month. The shift assumes the consultation precedes the petition by about a month; move it to two months for contested lines and to zero for protective orders, which file the week of the incident.</p></div></div>
    <div class="panel"><h3>Shock calendar</h3><div class="sub">Counties with the largest claims increase against a year earlier, and the months their filings are expected to dip and rebound.</div><div id="tmShock"></div></div>`;
    function seas() { const idx = S[st.line]; seasBlock($('#tmSeas'), idx, 'ember'); const yrs = Object.keys(byYear).map(Number).filter(y => y >= 2022 && y <= 2025); lineChart($('#tmYears'), { series: yrs.map((y, i) => ({ name: String(y), color: ['var(--s1)', 'var(--s2)', 'var(--s3)', 'var(--s4)'][i], values: (byYear[y] || []).map((v, mo) => ({ x: mo, y: v })) })), W: 900, H: 200, ymin: 0, xfmt: v => MOL[v], xTicks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], xTickFmt: v => MO[v], yfmt: v => N(v) }); weights(); cal(); }
    function ctySeason() { const c = CI[st.cty]; const s = c.filings.series; const key = { div: 'div', div_k: 'div_k', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', priv: 'priv' }[st.line]; if (!s || !s[key]) return S[st.line]; const arr = s[key]; const acc = Array(12).fill(0), cnt = Array(12).fill(0); arr.forEach((v, i) => { const t = s.t0 + i; const y = Math.floor(t / 12); if (y >= 2022 && y <= 2025) { acc[t % 12] += v; cnt[t % 12]++; } }); const mm = acc.map((v, i) => cnt[i] ? v / cnt[i] : null); const avg = mean(mm); const own = mm.map(v => isN(v) && avg ? v / avg * 100 : 100); const tot = sum(arr.slice(-12)); const w = tot / (tot + 600); return own.map((v, i) => w * v + (1 - w) * S[st.line][i]); }
    function cal() { const c = CI[st.cty]; const key = { div: 'div', div_k: 'div_k', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', priv: 'priv' }[st.line]; const tot = c.filings.ttm[key] || 0; const idx = ctySeason(); const isum = sum(idx); const now = new Date(2026, 8); const out = []; for (let i = 0; i < 12; i++) { const d = new Date(now.getFullYear(), now.getMonth() + 1 + i); const mo = d.getMonth(); out.push({ label: MO[mo] + ' ' + d.getFullYear(), v: tot * idx[mo] / isum, idx: idx[mo] }); } $('#tmCal').innerHTML = out.map(o => `<div><span class="small">${o.label}</span><b>${N(o.v, 0)}</b><span class="small">index ${N(o.idx, 0)}</span></div>`).join(''); }
    function weights() { const idx = S[st.line]; const shift = st.line === 'po' ? 0 : 1; const w = idx.map((v, i) => idx[(i + shift) % 12]); const ws = sum(w); $('#tmWeights').innerHTML = `<div class="seas">${w.map((v, i) => { const bg = rampColor('ember', clamp((v / ws * 100 - 6) / 6, 0, 1) * 0.85 + 0.05); return `<div style="background:${bg};color:${inkOn(bg)}"><b>${(v / ws * 100).toFixed(1)}</b>${MO[i]}</div>`; }).join('')}</div>`; }
    $$('#tmLines button').forEach(b => b.onclick = () => { st.line = b.dataset.l; $$('#tmLines button').forEach(x => x.classList.toggle('on', x === b)); seas(); });
    $('#tmCty').onchange = e => { st.cty = e.target.value; cal(); };
    const shock = CTY.filter(c => c.ui && c.ui.w13 >= 150 && c.econ.claims_vs_yago).sort((a, b) => b.econ.claims_vs_yago - a.econ.claims_vs_yago).slice(0, 15);
    $('#tmShock').innerHTML = `<div class="tblwrap"><table class="t"><thead><tr><th>County</th><th>Claims 13w</th><th>vs yr ago</th><th>Dip now</th><th>+3 mo</th><th>+12 mo</th><th style="text-align:left">Rebound lands</th><th>Enforcement now</th></tr></thead><tbody>${shock.map(c => { const e = c.econ.expected; const pr = D.panel['lenf|claims_0_12|post2022']; const enf = (Math.exp(pr.coefs.lclaims_l3.coef * e.dlog_claims) - 1) * 100; return `<tr><td>${esc(c.name)}</td><td>${N(c.ui.w13)}</td><td>${N(c.econ.claims_vs_yago, 2)}×</td><td>${sgn(e.now_pct, 1)}</td><td>${sgn(e.m3_pct, 1)}</td><td>${sgn(e.m12_pct, 1)}</td><td style="text-align:left">${MO[dLocal(META.ui_through).getMonth()]} ${dLocal(META.ui_through).getFullYear() + 1}</td><td>${sgn(enf, 1)}</td></tr>`; }).join('')}</tbody></table></div>`;
    $('#tmCsv').onclick = () => exportText('severance_monthly_weights.csv', csv(MO.map((mo, i) => { const o = { month: mo }; lines.forEach(l => o[l[0]] = S[l[0]][i]); return o; }), [{ l: 'month', k: 'month' }].concat(lines.map(l => ({ l: l[1] + ' index', k: l[0] })))));
    seas();
  }
});
