'use strict';
/* Module 09: Timing Desk */
registerModule({
  key: 'timing', num: '09', title: 'Timing Desk', desc: 'Seasons, lags and the twelve month media calendar: when each line files, and when a shock pays out',
  mount(root) {
    const st = { cty: CI[store.get('sev.county', '48201')] ? store.get('sev.county', '48201') : '48201', line: 'div', lead: null, wgeo: 'tx' };
    const S = ST.seas; const lines = [['div', 'Divorce'], ['div_k', 'Divorce with children'], ['sapcr', 'Custody, SAPCR'], ['po', 'Protective orders'], ['mod', 'Modifications'], ['enf', 'Enforcement'], ['ivd', 'Title IV-D'], ['priv', 'All private family law']];
    const m = ST.monthly; const t0 = m.t0;
    // month-of-year averages by year for divorce, to show Jan vs Mar each year
    // monthly filings by calendar year for a line, to set this year's months against the last four
    const byYearOf = k => { const out = {}; (m[k] || m.div).forEach((v, i) => { const y = Math.floor((t0 + i) / 12), mo = (t0 + i) % 12; (out[y] = out[y] || [])[mo] = v; }); return out; };
    // 'Protective orders peak in August, modifications in March' or, when the months coincide, 'Protective orders, modifications and
    // custody suits all peak in August'
    const peakOf = k => MOL[S[k].indexOf(Math.max(...S[k]))];
    // the season words come from the index: the peak, a second local high (a month above both neighbors, away from the peak), the trough
    const sd = S.div; const pk = sd.indexOf(Math.max(...sd)); const order = sd.map((v, i) => i).sort((a, b) => sd[a] - sd[b]); const tr1 = order[0], tr2 = order[1];
    const lift2 = sd.map((v, i) => i).filter(i => Math.abs(i - pk) > 1 && Math.abs(i - pk) < 11 && sd[i] > sd[(i + 11) % 12] && sd[i] > sd[(i + 1) % 12] && sd[i] > 100).sort((a, b) => sd[b] - sd[a])[0];
    const near = k => { const a = S[k]; const p = a.indexOf(Math.max(...a)); const r = a.map((v, i) => i).filter(i => i !== p && Math.abs(i - p) > 1 && Math.abs(i - p) < 11).sort((x, y) => a[y] - a[x])[0]; return isN(r) && a[p] - a[r] <= 1.5 ? MOL[r] : null; };
    const pr12 = D.panel['ldiv|claims_0_12']; const dblC = b => (Math.exp(b * Math.log(2)) - 1) * 100; const xc = D.panel.xcorr_state || {}; const xBest = Object.keys(xc).reduce((a, b) => xc[b] > xc[a] ? b : a, '12');
    const lagBest = ['lclaims_l3', 'lclaims_l6', 'lclaims_l9', 'lclaims_l12'].reduce((a, b) => pr12.coefs[b].coef > pr12.coefs[a].coef ? b : a); const lagN = +lagBest.replace('lclaims_l', '');
    const enfP = D.panel['lenf|claims_0_12|post2022'];
    const andList = a => a.length < 2 ? a.join('') : a.slice(0, -1).join(', ') + ' and ' + a[a.length - 1];
    const peaks = (() => { const items = [['Protective orders', 'po'], ['modifications', 'mod'], ['custody suits', 'sapcr']].map(([n, k]) => [n, peakOf(k)]); const by = []; items.forEach(([n, mo]) => { const g = by.find(x => x.mo === mo); if (g) g.n.push(n); else by.push({ mo, n: [n] }); }); if (by.length === 1) return `${andList(by[0].n)} all peak in ${by[0].mo}.`; return by.map((g, i) => `${andList(g.n)}${i === 0 ? (g.n.length > 1 ? ' both peak in ' : ' peak in ') : ' in '}${g.mo}`).join(', ') + '.'; })();
    root.innerHTML = mastHTML({ eyebrow: `Module 09 · Timing Desk · seasonality from ${m.div.length} months of statewide filings and the lag model`, title: 'Timing Desk', dek: `The divorce industry's calendar says January. The Texas courthouse says ${MOL[pk]}: filings run ${N(sd[pk], 0)} against an average month of 100${isN(lift2) ? `, with a second lift in ${MOL[lift2]} (${N(sd[lift2], 0)})${lift2 === 7 ? ' when school starts' : ''}` : ''} and a trough in ${MOL[Math.min(tr1, tr2)]} and ${MOL[Math.max(tr1, tr2)]} (${N(sd[Math.min(tr1, tr2)], 0)} and ${N(sd[Math.max(tr1, tr2)], 0)}). The consult happens four to eight weeks before the petition and the decree cannot come before day 61, so the search calendar sits about a month ahead of the filing calendar. ${peaks}`, facts: [[MOL[pk], 'peak divorce filing month, index ' + N(sd[pk], 0)], [MOL[tr1], 'trough, index ' + N(sd[tr1], 0)], [xBest + ' months', `lag at which statewide claims and divorce filings correlate most; the county panel's largest lift comes at ${lagN} months`], ['Day 61', 'earliest decree after filing (§ 6.702)']] }) + `
    <div class="toolbar"><span class="ttl">Timing Desk</span><span class="sub">Season by line, county calendar, budget weights</span><span class="sp"></span><button class="btn" id="tmCsv">↓ Monthly weights CSV</button></div>
    <div class="callout note"><div class="h">Read this first: three clocks</div><p><b>The season clock.</b> Every line has a shape and they are not the same: ${[['divorce', 'div'], ['custody suits', 'sapcr'], ['protective orders', 'po'], ['modifications', 'mod'], ['enforcement', 'enf']].map(([n, k]) => `${n} ${k === 'div' ? 'peak' + (n === 'divorce' ? 's' : '') + ' in ' : 'in '}${peakOf(k)}${near(k) ? ` (${near(k)} close behind)` : ''}`).join(', ').replace(/, ([^,]*)$/, ' and $1')}, and ${Object.keys(S).every(k => [tr1, tr2].includes(S[k].indexOf(Math.min(...S[k])))) ? 'every line bottoms out' : 'divorce bottoms out'} in ${MOL[Math.min(tr1, tr2)]} or ${MOL[Math.max(tr1, tr2)]}. <b>The shock clock.</b> When claims double in a county, divorce filings move ${sgn(dblC(pr12.coefs.lclaims.coef), 1)} the same month, ${sgn(dblC(pr12.coefs.lclaims_l3.coef), 1)} three months on and ${sgn(dblC(pr12.coefs.lclaims_l12.coef), 1)} twelve months on; statewide, claims and divorce filings correlate most at a ${xBest} month lag.${enfP ? ` Since 2022 enforcement moves early: ${sgn(dblC(enfP.coefs.lclaims_l3.coef), 1)} three months after a doubling.` : ''} <b>The court clock.</b> Sixty days minimum, two to four months for an agreed divorce, nine to twenty four months contested; fee revenue lands months after the click. Plan spend against the first two and cash against the third.</p></div>
    <div class="panel" style="margin-bottom:14px"><h3>Season by line</h3><div class="sub">Statewide monthly index, 2022 to 2025 average = 100; below it, the same line's statewide filings month by month for each year.</div><div class="tabs" id="tmLines" role="group" aria-label="Service line">${lines.map(l => `<button type="button" data-l="${l[0]}" aria-pressed="${st.line === l[0]}" class="${st.line === l[0] ? 'on' : ''}">${l[1]}</button>`).join('')}</div><div id="tmSeas"></div><div class="chart" id="tmYears" style="margin-top:10px"></div></div>
    <div class="grid2"><div class="panel"><h3>County calendar</h3><div class="sub">Expected filings by month for the next twelve months: the county's trailing twelve month total spread by the statewide season for the chosen line, adjusted by the county's own monthly pattern where a series exists.</div><div class="controls">${ctl('County', sel('tmCty', CTY.slice().sort((a, b) => a.name.localeCompare(b.name)).map(c => [c.fips, c.name]), st.cty))}</div><div class="cal" id="tmCal"></div></div>
    <div class="panel"><h3>Budget weights</h3><div class="sub" id="tmWeightsSub"></div><div class="controls" style="margin-bottom:8px"><div class="ctl"><span class="ctlh" id="tmLeadL">Lead time</span><div class="seg" id="tmLead" role="group" aria-labelledby="tmLeadL"><button type="button" data-v="0">None</button><button type="button" data-v="1">1 month</button><button type="button" data-v="2">2 months</button></div></div><div class="ctl"><span class="ctlh" id="tmWgeoL">Season</span><div class="seg" id="tmWgeo" role="group" aria-labelledby="tmWgeoL"><button type="button" data-v="tx">Texas</button><button type="button" data-v="cty" id="tmWgeoC">County</button></div></div></div><div id="tmWeights"></div><p class="small" style="margin-top:8px">Weights sum to 100. A flat calendar would be 8.3 in every month. The lead time moves spend ahead of the filing month, because the consultation comes before the petition: about a month for most lines (the default), two for contested matters, none for protective orders, which file the week of the incident. The county season blends the county's own monthly pattern with the state's, more of its own the more it files.</p></div></div>
    <div class="panel"><h3>Shock calendar</h3><div class="sub" id="tmShockSub"></div><div class="seg" id="tmShockSeg" role="group" aria-label="Which counties" style="margin:0 0 10px"><button type="button" data-v="up" aria-pressed="true">Claims rising</button><button type="button" data-v="all" aria-pressed="false">Largest changes, either way</button></div><div id="tmShock"></div></div>${srcFoot([['Sources', `Texas Office of Court Administration monthly filings, ${esc(seriesSpan())} (the season index averages 2022 to 2025); Texas Workforce Commission weekly claims through ${esc(fmtDate(META.ui_through))}; the county panel model (module 20).`], ['Judgment calls', 'The lead time between a consultation and a petition (one month by default, none for protective orders) is a judgment; the county season is shrunk toward the state by its size.'], ['Caveats', 'The last two months of filings are provisional; the shock calendar applies statewide elasticities to one county\'s claims.']])}`;
    function seas() { const idx = S[st.line]; seasBlock($('#tmSeas'), idx, 'ember'); const byYear = byYearOf(st.line); const yrs = Object.keys(byYear).map(Number).filter(y => y >= 2022 && y <= 2025); lineChart($('#tmYears'), { title: (lines.find(l => l[0] === st.line) || lines[0])[1] + ' filings by month, 2022 to 2025', series: yrs.map((y, i) => ({ name: String(y), color: ['var(--s1)', 'var(--s2)', 'var(--s3)', 'var(--s4)'][i], values: (byYear[y] || []).map((v, mo) => ({ x: mo, y: v })) })), W: 900, H: 200, ymin: 0, xfmt: v => MOL[v], xTicks: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11], xTickFmt: v => MO[v], yfmt: v => N(v) }); weights(); cal(); }
    function ctySeason() { const c = CI[st.cty]; const s = c.filings.series; const key = { div: 'div', div_k: 'div_k', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', priv: 'priv' }[st.line]; if (!s || !s[key]) return S[st.line]; const arr = s[key]; const acc = Array(12).fill(0), cnt = Array(12).fill(0); arr.forEach((v, i) => { const t = s.t0 + i; const y = Math.floor(t / 12); if (y >= 2022 && y <= 2025) { acc[t % 12] += v; cnt[t % 12]++; } }); const mm = acc.map((v, i) => cnt[i] ? v / cnt[i] : null); const avg = mean(mm); const own = mm.map(v => isN(v) && avg ? v / avg * 100 : 100); const tot = sum(arr.slice(-12)); const w = tot / (tot + 600); return own.map((v, i) => w * v + (1 - w) * S[st.line][i]); }
    function cal() { const c = CI[st.cty]; const key = { div: 'div', div_k: 'div_k', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', priv: 'priv' }[st.line]; const tot = c.filings.ttm[key] || 0; const idx = ctySeason(); const isum = sum(idx); const today = new Date(); const dm = String(META.oca_through || '').match(/^(\d{4})-(\d{2})/); const dataNext = dm ? new Date(+dm[1], +dm[2]) : today; const now = dataNext > today ? new Date(dataNext.getFullYear(), dataNext.getMonth() - 1) : new Date(today.getFullYear(), today.getMonth() - 1); /* the calendar starts with the current month, never before the month after the data */ const out = []; for (let i = 0; i < 12; i++) { const d = new Date(now.getFullYear(), now.getMonth() + 1 + i); const mo = d.getMonth(); out.push({ label: MO[mo] + ' ' + d.getFullYear(), v: tot * idx[mo] / isum, idx: idx[mo] }); } $('#tmCal').innerHTML = out.map(o => `<div><span class="small">${o.label}</span><b>${N(o.v, 0)}</b><span class="small">index ${N(o.idx, 0)}</span></div>`).join(''); }
    // budget weight of each month: the season index shifted one month earlier (none for protective orders), as a percent of the year
    const leadOf = line => st.lead != null ? st.lead : line === 'po' ? 0 : 1;
    function weightsOf(line, idx0) { const idx = idx0 || S[line]; const shift = leadOf(line); const w = idx.map((v, i) => idx[(i + shift) % 12]); const ws = sum(w); return w.map(v => v / ws * 100); }
    function weights() { const lead = leadOf(st.line); const cty = st.wgeo === 'cty'; const c = CI[st.cty]; const w = weightsOf(st.line, cty ? ctySeason() : null);
      $('#tmWeightsSub').textContent = `Share of an annual search budget to place in each month if spend follows expected consultations, for ${(lines.find(l => l[0] === st.line) || lines[0])[1].toLowerCase().replace('sapcr', 'SAPCR').replace('title iv-d', 'Title IV-D')}, ${cty ? c.name + ' County season' : 'the statewide season'}, filings shifted ${lead === 0 ? 'not at all' : lead === 1 ? 'one month earlier' : 'two months earlier'}.`;
      $$('#tmLead button').forEach(b => b.setAttribute('aria-pressed', String(+b.dataset.v === lead))); $$('#tmWgeo button').forEach(b => b.setAttribute('aria-pressed', String(b.dataset.v === st.wgeo))); $('#tmWgeoC').textContent = c.name + ' County';
      $('#tmWeights').innerHTML = `<div class="seas">${w.map((v, i) => { const bg = rampColor('ember', clamp((v - 6) / 6, 0, 1) * 0.85 + 0.05); return `<div style="background:${bg};color:${inkOn(bg)}"><b>${v.toFixed(1)}</b>${MO[i]}</div>`; }).join('')}</div>`; }
    $$('#tmLines button').forEach(b => b.onclick = () => { st.line = b.dataset.l; $$('#tmLines button').forEach(x => { x.classList.toggle('on', x === b); x.setAttribute('aria-pressed', String(x === b)); }); seas(); });
    $('#tmCty').onchange = e => { st.cty = e.target.value; store.set('sev.county', st.cty); cal(); weights(); };
    $$('#tmLead button').forEach(b => b.onclick = () => { st.lead = +b.dataset.v; weights(); });
    $$('#tmWgeo button').forEach(b => b.onclick = () => { st.wgeo = b.dataset.v; weights(); });
    this.sync = () => { const f = store.get('sev.county', st.cty); if (CI[f] && f !== st.cty) { st.cty = f; $('#tmCty').value = f; cal(); weights(); } };
    // goModule('timing', {county, line})
    this.receive = p => { if (!p) return; if (CI[p.county]) { store.set('sev.county', p.county); this.sync(); } const ln = p.line && ({ div_k: 'div_k', div_nk: 'div', high: 'div', mil: 'div', gray: 'div', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd', div: 'div', priv: 'priv' })[p.line]; if (ln && ln !== st.line) { st.line = ln; $$('#tmLines button').forEach(x => { x.classList.toggle('on', x.dataset.l === ln); x.setAttribute('aria-pressed', String(x.dataset.l === ln)); }); seas(); } };
    // the shock calendar: counties with 150 or more claims in 13 weeks. The lag model's largest positive divorce effect is at twelve
    // months, so each county's 12 month effect lands twelve months after the week in its window that moved most against a year earlier.
    const wkDate = (c, i) => { const d = dLocal(c.ui.week0); d.setDate(d.getDate() + i * 7); return d; };
    const moY = d => MO[d.getMonth()] + ' ' + d.getFullYear();
    const moveWeek = (c, up) => { const w = c.ui.weekly, n = w.length; let best = null, bi = n - 1; for (let i = Math.max(52, n - 13); i < n; i++) { if (!isN(w[i]) || !isN(w[i - 52])) continue; const d = (w[i] - w[i - 52]) * (up ? 1 : -1); if (best == null || d > best) { best = d; bi = i; } } return bi; };
    const prE = D.panel['lenf|claims_0_12|post2022'];
    const pool = CTY.filter(c => c.ui && c.ui.weekly && c.ui.w13 >= 150 && isN(c.econ.claims_vs_yago) && c.econ.claims_vs_yago > 0);
    function shockTable() {
      const up = st.shock !== 'all';
      const list = up ? pool.filter(c => c.econ.claims_vs_yago > 1).sort((a, b) => b.econ.claims_vs_yago - a.econ.claims_vs_yago).slice(0, 15) : pool.slice().sort((a, b) => Math.abs(Math.log(b.econ.claims_vs_yago)) - Math.abs(Math.log(a.econ.claims_vs_yago))).slice(0, 15);
      $('#tmShockSub').textContent = up ? `Counties where unemployment claims over the last 13 weeks run above the same weeks a year earlier (counties with 150 or more claims), with the filing changes the lag model expects: a dip in the same month, a rise at three months and another at twelve, when the twelve month effect lands.` : `The 15 counties whose claims moved most against a year earlier, rises and falls (counties with 150 or more claims). A fall in claims reverses the signs: a small lift in filings now and a small dip a year out.`;
      if (!list.length) { $('#tmShock').innerHTML = `<p class="small">No county with 150 or more claims in the last 13 weeks is running above a year earlier (claims through ${esc(fmtDate(META.ui_through))}). Switch to the largest changes either way to see where claims fell.</p>`; return; }
      $('#tmShock').innerHTML = `<div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">Shock calendar</caption><thead><tr><th scope="col">County</th><th scope="col">Claims 13w</th><th scope="col">vs yr ago</th><th scope="col">Divorce now</th><th scope="col">+3 mo</th><th scope="col">+12 mo</th><th scope="col" class="l">12 month effect lands</th><th scope="col" title="Enforcement filings three months after the claims change, from the 2022 on enforcement model">Enforcement +3 mo</th></tr></thead><tbody>${list.map(c => { const e = c.econ.expected; const enf = (Math.exp(prE.coefs.lclaims_l3.coef * e.dlog_claims) - 1) * 100; const r = c.econ.claims_vs_yago; const lands = wkDate(c, moveWeek(c, r >= 1) + 52); return `<tr><td>${esc(c.name)}</td><td>${N(c.ui.w13)}</td><td>${r >= 1 ? '▲' : '▼'} ${N(r, 2)}×</td><td>${sgn(e.now_pct, 1)}</td><td>${sgn(e.m3_pct, 1)}</td><td>${sgn(e.m12_pct, 1)}</td><td class="l">${moY(lands)}</td><td>${sgn(enf, 1)}</td></tr>`; }).join('')}</tbody></table></div></div>${up && list.length < 5 ? `<p class="small" style="margin-top:6px">Only ${list.length === 1 ? 'one county is' : atWord(list.length) + ' counties are'} running above a year earlier; claims are flat or falling everywhere else.</p>` : ''}`;
    }
    const atWord = n => ['no', 'one', 'two', 'three', 'four', 'five'][n] || String(n);
    st.shock = 'up'; $$('#tmShockSeg button').forEach(b => b.onclick = () => { st.shock = b.dataset.v; $$('#tmShockSeg button').forEach(x => x.setAttribute('aria-pressed', String(x === b))); shockTable(); });
    shockTable();
    // both columns per line: the season index and the budget weight exactly as the Budget weights panel computes it
    $('#tmCsv').onclick = () => { const W = {}; lines.forEach(l => { W[l[0]] = weightsOf(l[0]); }); exportText(expName('timing_weights', 'texas'), csv(MOL.map((mo, i) => { const o = { month: mo }; lines.forEach(l => { o[l[0] + '_i'] = S[l[0]][i]; o[l[0] + '_w'] = W[l[0]][i]; }); return o; }), [{ l: 'Month', k: 'month' }].concat(...lines.map(l => [{ l: `${l[1]} season index (2022 to 2025 = 100)`, k: l[0] + '_i', d: 1 }, { l: `${l[1]} budget weight (% of the year, Texas season, ${['no shift', 'one month early', 'two months early'][leadOf(l[0])]})`, k: l[0] + '_w', d: 1 }])))); };
    seas();
  },
  onShow() { if (this.sync) this.sync(); }
});
