'use strict';
/* Module 10: Campaign Desk */
const NEGATIVES = ['free', 'pro bono', 'legal aid', 'forms', 'form', 'pdf', 'template', 'do it yourself', 'diy', 'without a lawyer', 'pro se', 'how to become', 'salary', 'jobs', 'career', 'paralegal', 'school', 'degree', 'definition', 'meaning', 'statistics', 'rate', 'records', 'lookup', 'search records', 'public records', 'movie', 'song', 'lyrics', 'reddit', 'quotes', 'memes', 'wedding', 'anniversary', 'counseling', 'therapist', 'church', 'texas law help', 'texaslawhelp'];
const HEADLINES = {
  div_k: ['[City] Divorce Lawyer, Children First', 'Custody Decided Right, Not Fast', 'Conservatorship And Support Explained'],
  div_nk: ['Agreed Divorce From $[Fee] Flat', 'Uncontested Divorce In [County] County', 'Done In About 60 Days When You Both Agree'],
  sapcr: ['[City] Child Custody Attorney', 'Unmarried Parents: Establish Your Rights', 'Fathers Get Equal Standing In Texas'],
  mod: ['Lost Income? Modify Child Support', 'Change A Custody Order In [County] County', 'Modification Reviews This Week'],
  enf: ['Unpaid Child Support? Enforce The Order', 'Denied Visitation? Enforce Possession', 'Contempt Actions In [County] County'],
  po: ['Protective Order Help Today', 'Family Violence? Talk To A Lawyer Now', 'Served With A Protective Order? Respond In Time'],
  ivd: ['Child Support Hearing Coming Up?', 'Paternity And Support In [County] County', 'Represented At The IV-D Docket'],
  adopt: ['Stepparent Adoption In [City]', 'Adopt A Grandchild Or Relative', 'Adoption Attorney, [County] County'],
  cps: ['CPS Investigating Your Family?', 'DFPS Removal? Act Before The 14 Day Hearing', 'CPS Defense Lawyer In [City]'],
  prenup: ['Texas Prenup, Drafted To Hold Up', 'Premarital Agreement From $[Fee]', 'Protect A Business Before The Wedding'],
  high: ['Divorce With A Business Or Stock', 'Separate Property Traced And Proved', 'High Asset Divorce, [City]'],
  mil: ['Military Divorce Near [Base]', 'Deployment, Custody And USFSPA Retirement', 'SCRA Rights In A Texas Divorce'],
  gray: ['Divorce After 50, Retirement Divided Right', 'QDROs, Pensions And Spousal Maintenance', 'Gray Divorce Attorney, [City]']
};
registerModule({
  key: 'desk', num: '10', title: 'Campaign Desk', desc: 'Budgets, ZIP targets, keyword sets, copy angles and month weights for a chosen metro or county, exported for Google and Meta',
  mount(root) {
    const st = Object.assign({ geo: 'msa:19100', lines: ['div_k', 'div_nk', 'sapcr', 'mod'], budget: 12000, cpc: 9.87, cvr: 6.0, retain: 22, n: 30, firm: 'Your firm', atty: 'Responsible attorney', city: '' }, store.get('sev.desk', {}));
    const geoOpts = Object.keys(MSA).sort((a, b) => MSA[b].pop2025 - MSA[a].pop2025).map(k => ['msa:' + k, 'Metro: ' + MNAME(MSA[k].title)]).concat(CTY.slice().sort((a, b) => b.pop2025 - a.pop2025).map(c => ['cty:' + c.fips, c.name + ' County']));
    root.innerHTML = mastHTML({ eyebrow: 'Module 10 · Campaign Desk · plans built from the modules before it', title: 'Campaign Desk', dek: `Pick a metro or county and the lines to sell; the desk allocates the budget by expected filings times matter value, shortlists ZIPs by efficiency, writes the keyword sets with the local city and county modifiers, drafts headlines in Texas terms, and spreads spend across the year by season. Every number traces back to a module: filings from 02, pools from 06, ZIPs from 07, seasons from 09. Exports are formatted for Google Ads Editor and for Meta's location upload.`, facts: [['13', 'service lines'], ['1,127', 'metro ZIPs with criteria IDs'], ['3', 'exports: keywords, ZIPs, plan'], ['Rule 7.02', 'every ad names a responsible lawyer and a primary practice location']] }) + `
    <div class="toolbar"><span class="ttl">Campaign Desk</span><span class="sub">Plan, keywords, copy, calendar</span><span class="sp"></span><button class="btn" id="dkKw">↓ Keywords CSV</button><button class="btn" id="dkNeg">↓ Negatives</button><button class="btn" id="dkZip">↓ ZIP targets</button><button class="btn primary" id="dkPlan">↓ Plan CSV</button></div>
    <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Geography', sel('dkGeo', geoOpts, st.geo))}${ctl('Monthly budget $', `<input type="number" id="dkBudget" value="${st.budget}" step="500" style="width:100px">`)}${ctl('CPC $', `<input type="number" id="dkCpc" value="${st.cpc}" step="0.25" style="width:80px">`)}${ctl('Conversion %', `<input type="number" id="dkCvr" value="${st.cvr}" step="0.5" style="width:80px">`)}${ctl('Lead to retained %', `<input type="number" id="dkRet" value="${st.retain}" step="1" style="width:80px">`)}${ctl('ZIP targets', `<input type="number" id="dkN" value="${st.n}" min="5" max="150" style="width:80px">`)}${ctl('Firm name', `<input type="text" id="dkFirm" value="${esc(st.firm)}" style="width:160px">`)}${ctl('Responsible attorney', `<input type="text" id="dkAtty" value="${esc(st.atty)}" style="width:180px">`)}</div><div class="controls" id="dkLines">${Object.keys(LINE_META).map(k => `<label class="chk"><input type="checkbox" data-l="${k}" ${st.lines.includes(k) ? 'checked' : ''}> ${esc(LINE_META[k].short)}</label>`).join('')}</div></div>
    <div class="tiles" id="dkTiles"></div>
    <div class="grid2"><div class="panel"><h3>Budget by line</h3><div class="sub">Share follows expected matters times value per matter; edit a share to override.</div><div id="dkAlloc"></div></div><div class="panel"><h3>ZIP targets</h3><div class="sub" id="dkZipSub"></div><div id="dkZips"></div></div></div>
    <div class="panel" style="margin-bottom:14px"><h3>Keyword sets and copy</h3><div class="sub">Seeds from module 06 crossed with the local modifiers below. Phrase match for the seeds, exact match for the city forms. Headlines are 30 character drafts in Texas terms; run them through module 11 before they ship.</div><div id="dkKeys"></div></div>
    <div class="panel"><h3>Month plan</h3><div class="sub">Budget by month for the coming year, weighted by the divorce season (module 09) for divorce lines and each line's own season where one exists.</div><div id="dkMonths"></div></div>`;
    function geoObj() { const [t, id] = st.geo.split(':'); if (t === 'msa') return { type: 'msa', id, title: MNAME(MSA[id].title), counties: MSA[id].counties.map(f => CI[f]).sort((a, b) => (b.pop2025 || 0) - (a.pop2025 || 0)), zips: metroZctas([id]) }; const c = CI[id]; return { type: 'cty', id, title: c.name + ' County', counties: [c], zips: ZC.filter(z => z.county === id) }; }
    function expected(g, line) { return sum(g.counties.map(c => LINE_META[line].cnt(c) || 0)); }
    function save() { store.set('sev.desk', st); }
    function render() {
      const g = geoObj(); const lines = st.lines.filter(l => LINE_META[l]);
      const rows = lines.map(l => ({ l, n: expected(g, l), fee: LINE_META[l].fee })); const tot = sum(rows.map(r => r.n * r.fee)) || 1;
      rows.forEach(r => { r.share = st.shares && st.shares[r.l] != null ? st.shares[r.l] : r.n * r.fee / tot * 100; });
      const ss = sum(rows.map(r => r.share)) || 1; rows.forEach(r => { r.share = r.share / ss * 100; r.budget = st.budget * r.share / 100; r.clicks = r.budget / st.cpc; r.leads = r.clicks * st.cvr / 100; r.ret = r.leads * st.retain / 100; r.rev = r.ret * r.fee; });
      const totRet = sum(rows.map(r => r.ret)), totRev = sum(rows.map(r => r.rev)), totN = sum(rows.map(r => r.n));
      $('#dkTiles').innerHTML = tile('Geography', esc(g.title), `${g.counties.length} count${g.counties.length > 1 ? 'ies' : 'y'} · ${N(g.zips.length)} ZIPs · ${N(sum(g.counties.map(c => c.pop2025)))} people`) + tile('Expected matters / yr', N(totN, 0), 'across the chosen lines (court filings and estimates)') + tile('Retained / month', N(totRet, 1), 'at $' + N(st.cpc, 2) + ' CPC, ' + N(st.cvr, 1) + '% conversion, ' + N(st.retain, 0) + '% retained') + tile('Revenue / month', $$$(totRev), N(totRev / (st.budget || 1), 1) + '× the budget') + tile('Share of market', P(totRet * 12 / Math.max(totN, 1), 1), 'retained a year against expected matters') + tile('Shock index', N(mean(g.counties.map(c => c.esi)), 0), 'population unweighted average; lead with modification and enforcement where high');
      $('#dkAlloc').innerHTML = `<div class="tblwrap"><table class="t"><thead><tr><th>Line</th><th>Matters/yr</th><th>Value</th><th>Share %</th><th>Budget/mo</th><th>Leads/mo</th><th>Retained/mo</th><th>Revenue/mo</th></tr></thead><tbody>${rows.map(r => `<tr><td>${esc(LINE_META[r.l].name)}</td><td>${N(r.n, 0)}</td><td>${$$$(r.fee)}</td><td><input type="number" data-l="${r.l}" class="shareIn" value="${r.share.toFixed(0)}" style="width:60px;text-align:right"></td><td>${$$$(r.budget)}</td><td>${N(r.leads, 1)}</td><td>${N(r.ret, 2)}</td><td>${$$$(r.rev)}</td></tr>`).join('')}</tbody></table></div>`;
      $$('.shareIn').forEach(i => i.onchange = () => { st.shares = st.shares || {}; st.shares[i.dataset.l] = +i.value || 0; save(); render(); });
      const zips = g.zips.filter(z => isN(z.paid.eff_pct)).sort((a, b) => b.paid.eff_pct - a.paid.eff_pct).slice(0, st.n);
      $('#dkZipSub').textContent = `${zips.length} ZIPs by efficiency; ${N(sum(zips.map(z => z.alloc.div || 0)), 0)} expected divorce filings a year inside them (${P(sum(zips.map(z => z.alloc.div || 0)) / Math.max(1, sum(g.zips.map(z => z.alloc.div || 0))), 0)} of the geography).`;
      $('#dkZips').innerHTML = zips.length ? `<div class="tblwrap" style="max-height:300px"><table class="t"><thead><tr><th>ZIP</th><th style="text-align:left">City</th><th>Eff</th><th>Div/yr</th><th>Offices</th><th>Bid</th></tr></thead><tbody>${zips.map(z => `<tr><td>${z.zip}</td><td style="text-align:left">${esc(z.city)}</td><td>${N(z.paid.eff_pct, 0)}</td><td>${N(z.alloc.div, 0)}</td><td>${N(z.lawoffices)}</td><td>${z.paid.eff_pct >= 80 ? '+20%' : z.paid.eff_pct >= 60 ? '+10%' : '0%'}</td></tr>`).join('')}</tbody></table></div>` : '<div class="small">No ZIP geometry outside the metros; target the county.</div>';
      const cities = {}; g.zips.forEach(z => { if (z.city) { cities[z.city] = (cities[z.city] || 0) + (z.alloc.div || 0); } }); const topCities = Object.keys(cities).sort((a, b) => cities[b] - cities[a]).slice(0, 8);
      const geoMods = topCities.concat(g.counties.slice().sort((a, b) => b.pop2025 - a.pop2025).slice(0, 4).map(c => c.name + ' County'));
      st._kw = []; st._geoMods = geoMods;
      $('#dkKeys').innerHTML = lines.map(l => { const L = LINE_META[l]; const kws = []; L.kw.forEach(k => { kws.push({ kw: k, match: 'phrase' }); }); geoMods.slice(0, 6).forEach(gm => { L.kw.slice(0, 2).forEach(k => { kws.push({ kw: k + ' ' + gm, match: 'exact' }); kws.push({ kw: gm + ' ' + k, match: 'exact' }); }); }); kws.forEach(k => st._kw.push({ line: L.name, campaign: g.title + ' · ' + L.short, kw: k.kw, match: k.match })); const city = topCities[0] || g.counties[0].name; const heads = HEADLINES[l].map(h => h.replace('[City]', city).replace('[County]', g.counties[0].name).replace('[Fee]', N(L.fee)).replace('[Base]', { '48027': 'Fort Cavazos', '48099': 'Fort Cavazos', '48141': 'Fort Bliss', '48029': 'JBSA' }[g.counties[0].fips] || 'the base')); return `<div style="margin-bottom:12px"><b>${esc(L.name)}</b> <span class="small">${kws.length} keywords · seeds: ${L.kw.map(k => `<code>${esc(k)}</code>`).join(' ')}</span><div class="small" style="margin:4px 0">Modifiers: ${geoMods.map(m => esc(m)).join(', ')}</div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:4px">${heads.map(h => `<span class="pill" style="font-family:var(--sans);font-size:12px">${esc(h)}</span>`).join('')}<span class="pill" style="font-family:var(--sans);font-size:12px">${esc(st.firm)} · ${esc(st.atty)}, ${esc(city)}</span></div><div class="small" style="margin-top:4px">${esc(L.angle)}</div></div>`; }).join('');
      const seasKey = l => ({ div_k: 'div_k', div_nk: 'div', sapcr: 'sapcr', po: 'po', mod: 'mod', enf: 'enf', ivd: 'ivd' }[l] || 'div');
      const now = new Date(2026, 8); const months = []; for (let i = 0; i < 12; i++) { const d = new Date(now.getFullYear(), now.getMonth() + 1 + i); months.push({ mo: d.getMonth(), y: d.getFullYear() }); }
      const mrows = months.map(m => { let b = 0; rows.forEach(r => { const s = ST.seas[seasKey(r.l)]; const shift = r.l === 'po' ? 0 : 1; const w = s[(m.mo + shift) % 12] / sum(s); b += r.budget * 12 * w; }); return { label: MO[m.mo] + ' ' + m.y, b }; });
      $('#dkMonths').innerHTML = `<div class="cal">${mrows.map(r => `<div><span class="small">${r.label}</span><b>${$$$(r.b)}</b><span class="small">${P(r.b / (st.budget * 12), 1)} of year</span></div>`).join('')}</div>`;
      st._plan = rows.map(r => ({ geography: g.title, line: LINE_META[r.l].name, expected_matters: Math.round(r.n), value_per_matter: r.fee, share_pct: r.share.toFixed(1), budget_month: r.budget.toFixed(0), leads_month: r.leads.toFixed(1), retained_month: r.ret.toFixed(2), revenue_month: r.rev.toFixed(0) }));
      st._zips = zips;
    }
    $('#dkGeo').onchange = e => { st.geo = e.target.value; st.shares = null; save(); render(); };
    ['dkBudget', 'dkCpc', 'dkCvr', 'dkRet', 'dkN', 'dkFirm', 'dkAtty'].forEach(id => $('#' + id).onchange = () => { st.budget = +$('#dkBudget').value || 0; st.cpc = +$('#dkCpc').value || 1; st.cvr = +$('#dkCvr').value || 0; st.retain = +$('#dkRet').value || 0; st.n = clamp(+$('#dkN').value || 30, 5, 150); st.firm = $('#dkFirm').value; st.atty = $('#dkAtty').value; save(); render(); });
    $$('#dkLines input').forEach(i => i.onchange = () => { st.lines = $$('#dkLines input').filter(x => x.checked).map(x => x.dataset.l); st.shares = null; save(); render(); });
    $('#dkKw').onclick = () => exportText('severance_keywords.csv', csv(st._kw, [{ l: 'Campaign', k: 'campaign' }, { l: 'Ad Group', k: 'line' }, { l: 'Keyword', k: 'kw' }, { l: 'Match Type', k: 'match' }]));
    $('#dkNeg').onclick = () => exportText('severance_negatives.txt', NEGATIVES.join('\n'), 'text/plain');
    $('#dkZip').onclick = () => exportText('severance_zip_targets.csv', csv(st._zips.map(z => ({ Location: z.zip + ', Texas, United States', ID: z.gt || '', Type: 'Postal Code', 'Bid adjustment': (z.paid.eff_pct >= 80 ? '+20%' : z.paid.eff_pct >= 60 ? '+10%' : '0%'), City: z.city, County: z.county_name })), ['Location', 'ID', 'Type', 'Bid adjustment', 'City', 'County'].map(k => ({ l: k, k }))));
    $('#dkPlan').onclick = () => exportText('severance_plan.csv', csv(st._plan, Object.keys(st._plan[0] || { geography: 1 }).map(k => ({ l: k, k }))));
    render();
  }
});
