'use strict';
/* Module 11: Compliance Screen */
// SAMPLE_AD and COMP_RULES live in src/03_lint.js (the shared compliance engine)
registerModule({
  key: 'compliance', num: '11', title: 'Compliance Screen', desc: 'Ads and pages screened against Texas Rules 7.01 to 7.06, the family law myth list and the ad platform policies',
  mount(root) {
    const st = { resp: false, solicit: false, text: store.get('sev.comp.text', SAMPLE_AD) };
    root.innerHTML = mastHTML({ eyebrow: 'Module 11 · Compliance Screen · Texas Disciplinary Rules of Professional Conduct, Part VII (eff. July 1, 2021)', title: 'Compliance Screen', dek: `Paste an ad, a landing page or a social post. The screen reads it against the Texas advertising rules (false or misleading statements, special competence claims, contingent fees in family matters, past results, solicitation labels, the ten day filing requirement), against the twenty eight family law myths that get published most often, and against the Google and Meta policies that decide whether the campaign runs at all. It corrects nothing. It flags, cites the rule, and says why.`, facts: [[String(COMP_RULES.length), 'pattern checks'], ['10 days', 'to file a non exempt ad with the Advertising Review Committee (Rule 7.04)'], ['$11,700', 'current child support cap; the most common stale number'], ['7.02(a)', 'name of a responsible lawyer and primary practice location']] }) + `
    <div class="toolbar"><span class="ttl">Compliance Screen</span><span class="sub">Flags, never rewrites</span><span class="sp"></span><button class="btn" id="cpSample">Load the sample ad</button><button class="btn primary" id="cpRun">Screen this copy</button></div>
    <div class="callout judg"><div class="h">Judgment call: a screen, not a lawyer</div><p>Pattern matching catches the phrases that get firms grievances and the facts that went stale in September 2025. It cannot judge context: "the best interest of the child" is a statute, not a superlative, and the screen knows that one, but it will not know every case. Treat a flag as a reason to look, and file what needs filing.</p></div>
    <div class="grid2"><div class="panel"><h3>Copy</h3><textarea class="copy" id="cpText" style="min-height:220px">${esc(st.text)}</textarea><div class="controls" style="margin-top:8px"><label class="chk"><input type="checkbox" id="cpResp"> The ad names a responsible lawyer and the primary practice location (Rule 7.02(a))</label><label class="chk"><input type="checkbox" id="cpSol"> This is a solicitation communication sent to specific people known to need a lawyer (Rule 7.03)</label></div></div>
    <div class="panel"><h3>Findings</h3><div class="sub" id="cpSum"></div><div id="cpFind"></div></div></div>
    <div class="grid2"><div class="panel"><h3>The rules in one screen</h3><div class="prose" style="font-size:13.5px"><p><b>7.01 Communications.</b> No false or misleading communication about a lawyer's qualifications or services. Trade names are allowed if not misleading. A verdict later reduced or reversed must be advertised with the amount the client actually received, with equal or greater prominence.</p><p><b>7.02 Advertisements.</b> Publish the name of a lawyer responsible for the content and the lawyer's primary practice location. No claim of special competence except "Board Certified, [area], Texas Board of Legal Specialization" or a TBLS accredited organization. A contingent fee ad must say whether the client pays other expenses. An advertised fee must be honored while the ad runs.</p><p><b>7.03 Solicitation.</b> No in person, telephone, social media or electronic solicitation of a non client for pecuniary gain except to lawyers, family, prior clients and experienced users. A solicitation communication must be plainly marked "ADVERTISEMENT" and must not resemble a legal pleading. No payment to non lawyers for referrals beyond nominal gifts.</p><p><b>7.04 Filing.</b> Within ten days of first dissemination, file a copy, the application and the fee with the Advertising Review Committee, State Bar of Texas, unless exempt. Pre approval is available thirty days ahead and is binding if the ad is fairly described.</p><p><b>7.05 Exempt from filing.</b> Website content other than the homepage; law lists; announcement and business cards; newsletters to clients; informational or educational social media that does not offer services; sponsorship acknowledgments; basic information (name, address, practice areas, admissions, education, languages, TBLS certifications, fees for initial consultation).</p><p><b>7.06 Prohibited employment.</b> A lawyer may not accept a matter procured by conduct that violates 7.01 to 7.03, personally or through the firm.</p><p><b>1.04(e).</b> No contingent fee in a domestic relations matter contingent on securing a divorce or on the amount of support, maintenance or property.</p></div></div>
    <div class="panel"><h3>Platform policies that decide whether the campaign runs</h3><div class="prose" style="font-size:13.5px"><p><b>Google Ads.</b> Search ads on family law keywords are allowed. The personalized advertising policy lists "personal hardships", including relationship, marital or family difficulties, as a sensitive interest category: no audience segments, remarketing lists or customer match lists built on divorce status, and no ad copy that implies knowledge of the reader's situation ("going through a divorce?" targeted by list). Keyword targeting and the ZIP lists in modules 07 and 10 are geographic, not personal, and comply. Local Services Ads run for family law with Google Screened verification (bar license, background check).</p><p><b>Meta.</b> Detailed targeting on relationship status and most family attributes was retired; build audiences on geography, age and broad interests, and never upload lists of people believed to be divorcing. Ads asserting or implying personal attributes ("Are you getting divorced?") violate the personal attributes policy; write to the situation in the third person ("Divorce with children in Harris County").</p><p><b>Both.</b> Landing pages must show the firm's physical address and the responsible lawyer; a page that promises a result or a price the firm will not honor is disapproved by the platform before the bar ever sees it.</p><p><b>Content facts (module 06 and the Texas family law reference).</b> Cap $11,700 net; 60 day floor; ESPO default within 50 miles since 2021; no legal separation; just and right division; no sex preference; child interview at 12 without control; protective order on proof violence occurred (2023), durations tied to the divorce or SAPCR (2025); ground (O) repealed (2025); Prop 15 parental rights amendment adopted November 2025 with its effect undefined by the Supreme Court of Texas as of June 2026.</p></div></div></div>`;
    function run() { const t = $('#cpText').value; store.set('sev.comp.text', t); const finds = []; COMP_RULES.forEach(r => { const m = t.match(r.re); if (m && !(r.ok && r.ok.test(t))) finds.push({ sev: r.sev, t: r.t, rule: r.rule, why: r.why, hit: m[0] }); }); if (!$('#cpResp').checked) finds.push({ sev: 'review', t: 'Responsible lawyer and primary practice location not confirmed', rule: 'Rule 7.02(a)', why: 'Every advertisement must publish the name of a lawyer responsible for its content and identify the lawyer\'s primary practice location. Tick the box once the ad carries both.', hit: '' }); if ($('#cpSol').checked) { if (!/ADVERTISEMENT/.test(t)) finds.push({ sev: 'crit', t: 'Solicitation not marked ADVERTISEMENT', rule: 'Rule 7.03(c)', why: 'A solicitation communication must be plainly marked or clearly designated an "ADVERTISEMENT" unless directed to lawyers, family, prior clients or experienced users, and must not resemble a legal pleading.', hit: '' }); finds.push({ sev: 'info', t: 'Solicitation channel check', rule: 'Rule 7.03(a)', why: 'Written and mailed solicitations are permitted with the label; in person, telephone and real time electronic solicitation of non clients is not.', hit: '' }); } finds.push({ sev: 'info', t: 'Filing requirement', rule: 'Rule 7.04 and 7.05', why: 'Unless the piece is exempt (website pages other than the homepage, informational social posts, basic information), file it with the Advertising Review Committee within ten days of first dissemination, or seek pre approval thirty days ahead.', hit: '' }); const order = { crit: 0, review: 1, info: 2 }; finds.sort((a, b) => order[a.sev] - order[b.sev]); const nc = finds.filter(f => f.sev === 'crit').length, nr = finds.filter(f => f.sev === 'review').length; $('#cpSum').textContent = `${nc} likely violation${nc === 1 ? '' : 's'}, ${nr} to review, ${finds.length - nc - nr} reminder${finds.length - nc - nr === 1 ? '' : 's'}.`; $('#cpFind').innerHTML = finds.map(f => `<div class="finding ${f.sev === 'crit' ? 'crit' : f.sev === 'info' ? 'info' : ''}"><b>${esc(f.t)}${f.hit ? ` <span class="small">matched: "${esc(f.hit)}"</span>` : ''}</b><span class="rule">${esc(f.rule)}</span><div>${esc(f.why)}</div></div>`).join(''); }
    $('#cpRun').onclick = run; $('#cpSample').onclick = () => { $('#cpText').value = SAMPLE_AD; run(); }; $('#cpResp').onchange = run; $('#cpSol').onchange = run;
    run();
  }
});
