'use strict';
/* Metro tabs (12, 14 to 18) and Other Metros (19); the Metro Atlas is 13. Each tab maps its metro at ZIP resolution with a ZIPs or
   Counties toggle (county mode paints each county's value on all of its ZIPs), a county filter that dims, zooms and scopes the ranking,
   the exports and the hand offs, a sortable county table that selects on the map in place, a ledger with grades and margins of error,
   the firm's offices and the watched firms as pins, and the firm's own spend and intake from Accounts where it has any. */
function metroSummary(codes) {
  const cs = metroCounties(codes).map(f => CI[f]); const zs = metroZctas(codes);
  // a county whose clerk stopped reporting (San Jacinto) is left out of both sides of every comparison, so the change is like for like
  const gaps = cs.filter(c => repGap(c) || (!(c.filings.ttm.div || 0) && (c.filings.ttm_prev.div || 0) > 0)); const ok = c => !gaps.includes(c);
  const tt = k => sum(cs.map(c => c.filings.ttm[k] || 0)), pv = k => sum(cs.filter(ok).map(c => c.filings.ttm_prev[k] || 0));
  const married = sum(cs.map(c => c.acs.married || 0)); const pop = sum(cs.map(c => c.pop2025));
  // the margin of a sum of ACS estimates: the square root of the sum of the squared county margins (the Census approximation)
  const marriedMoe = Math.sqrt(sum(cs.map(c => isN(c.acs.married_cv) && isN(c.acs.married) ? (1.645 * c.acs.married_cv * c.acs.married) ** 2 : 0)));
  const y19 = sum(cs.filter(ok).map(c => (c.filings.hist['2019'] || {}).div || 0));
  const offices = sum(cs.map(c => c.rates.lawoffices || 0));
  const esi = sum(cs.map(c => (c.esi || 0) * c.pop2025)) / pop; const di = sum(cs.map(c => (c.di || 0) * c.pop2025)) / pop;
  const w13 = sum(cs.map(c => c.ui ? c.ui.w13 : 0)), w13_19 = sum(cs.map(c => c.ui && c.ui.w13_2019 ? c.ui.w13_2019 : 0)), w13y = sum(cs.map(c => c.ui && c.ui.w13_yago ? c.ui.w13_yago : 0));
  const lf = sum(cs.map(c => c.laus && c.laus.lf ? c.laus.lf : 0)), un = sum(cs.map(c => c.laus && c.laus.unemp ? c.laus.unemp : 0)), unY = sum(cs.map(c => c.laus && c.laus.unemp_yago ? c.laus.unemp_yago : 0));
  const warn12 = sum(cs.map(c => c.warn.last12.workers)); const exposed = sum(cs.map(c => c.econ.married_exposed || 0));
  // monthly series summed
  let series = null; const withS = cs.filter(c => c.filings.series); if (withS.length) { const t0 = Math.max(...withS.map(c => c.filings.series.t0)); const n = Math.min(...withS.map(c => c.filings.series.div.length)); series = { t0, div: [], sapcr: [], po: [], mod: [], enf: [], d_div: [], p_div: [] }; for (let i = 0; i < n; i++) ['div', 'sapcr', 'po', 'mod', 'enf', 'd_div', 'p_div'].forEach(k => series[k][i] = sum(withS.map(c => c.filings.series[k][i]))); }
  // QCEW suppresses some county sectors (disc N, carried as 0 jobs and 0 change); they add nothing to the sums and are counted for the note
  let suppressed = 0; const sectors = {}; cs.forEach(c => (c.sectors || []).forEach(s => { if (s.disc === 'N' || (!s.emp && !s.chg)) { suppressed++; return; } if (!sectors[s.code]) sectors[s.code] = { name: s.name, emp: 0, chg: 0 }; sectors[s.code].emp += s.emp; sectors[s.code].chg += (s.chg || 0); }));
  // the data keeps each county's 12 most recent WARN notices of the last 24 months; the metro list is the largest of those
  const warn = []; cs.forEach(c => c.warn.recent.forEach(r => warn.push(Object.assign({ county: c.name }, r)))); warn.sort((a, b) => (b.n || 0) - (a.n || 0)); const capped = cs.filter(c => c.warn.recent.length >= 12).map(c => c.name);
  return { cs, zs, married, marriedMoe, pop, ttm: { div: tt('div'), div_k: tt('div_k'), sapcr: tt('sapcr'), po: tt('po'), mod: tt('mod'), enf: tt('enf'), priv: tt('priv'), ivd: tt('ivd'), cps: tt('cps'), adopt: tt('adopt'), d_div: tt('d_div') }, prev: { div: pv('div'), sapcr: pv('sapcr'), po: pv('po'), mod: pv('mod'), enf: pv('enf'), priv: pv('priv') }, y19, offices, esi, di, w13, w13_19, w13y, ur: lf ? un / lf * 100 : null, urY: lf ? unY / lf * 100 : null, warn12, exposed, series, sectors: Object.values(sectors), suppressed, warn: warn.slice(0, 12), capped, gaps, rate: married ? tt('div') / married * 1000 : null };
}
/* ---- the metro layer catalog: z reads a ZIP, c reads a county (a layer without z paints county values in both modes); g and cg are the
   grades at ZIP and at county; the note goes in the legend. ZIP filings are allocations of the county counts (grade C). */
const MT_OPP = pctScale(CTY.map(c => c.filings.ttm.priv));
const MT_GROUPS = ['Index', 'Filings', 'Marriage stock', 'Family structure', 'Strain and means', 'Economic shock', 'Protection', 'Supply', 'Your accounts'];
const MT_LAYERS = {
  eff: { l: 'Efficiency percentile (expected filings per competing law office)', cl: 'Supply gap percentile (private family filings per law office, county rank)', grp: 'Index', g: 'C', cg: 'C', ramp: 'ember', z: z => z.paid ? z.paid.eff_pct : null, c: c => c.pct.supply, f: v => N(v, 0), q: false, note: 'ZIP: allocated filings over the law offices in the ZIP, ranked across all metro ZIPs. County: the index\'s supply gap percentile.' },
  opp: { l: 'Opportunity percentile (expected private family filings)', cl: 'Private family filings percentile (county rank)', grp: 'Index', g: 'C', cg: 'A', ramp: 'ember', z: z => z.paid ? z.paid.opp_pct : null, c: c => MT_OPP(c.filings.ttm.priv) * 100, f: v => N(v, 0), q: false, note: 'Where the most private family law cases are, before competition.' },
  di: { l: 'ZIP Dissolution Index (composition, separation, shock, structure, strain, supply)', cl: 'County Dissolution Index (with the filing component)', grp: 'Index', g: 'B', cg: 'B', ramp: 'ember', z: z => z.di, c: c => c.di, f: v => N(v, 0), q: false, note: 'The ZIP index has no filing component (filings exist only by county); the county index carries it at 30%.' },
  div: { l: 'Expected divorce filings a year (allocated from county filings)', cl: 'Divorce filings, trailing 12 months', grp: 'Filings', g: 'C', cg: 'A', ramp: 'ember', z: z => z.alloc.div, c: c => c.filings.ttm.div, f: v => N(v, 0), log: true, note: 'ZIP figures spread each county\'s clerk count over its ZIPs by married adults times the modeled hazard; they sum to the county.' },
  rate: { l: 'Expected divorce filings per 1,000 married', cl: 'Divorce filings per 1,000 married adults', grp: 'Filings', g: 'C', cg: 'A', ramp: 'ember', z: z => z.exp_div_per_1k_married, c: c => c.rates.div_per_1k_married, f: v => N(v, 1), note: 'A ZIP rate is the allocation over the ZIP\'s married adults, so it moves with the modeled hazard, not with local court records.' },
  priv: { l: 'Expected private family law filings a year', cl: 'Private family law filings, trailing 12 months', grp: 'Filings', g: 'C', cg: 'A', ramp: 'ember', z: z => z.alloc.priv, c: c => c.filings.ttm.priv, f: v => N(v, 0), log: true, note: 'Divorce, custody, protective orders, modifications and enforcement: the cases a private firm takes.' },
  sapcr: { l: 'Expected custody suits (SAPCR) a year', cl: 'Custody suits (SAPCR), trailing 12 months', grp: 'Filings', g: 'C', cg: 'A', ramp: 'ember', z: z => z.alloc.sapcr, c: c => c.filings.ttm.sapcr, f: v => N(v, 0), log: true, note: 'Suits affecting the parent child relationship without a divorce.' },
  po: { l: 'Expected protective order applications a year', cl: 'Protective order applications, trailing 12 months', grp: 'Filings', g: 'C', cg: 'A', ramp: 'ember', z: z => z.alloc.po, c: c => c.filings.ttm.po, f: v => N(v, 0), log: true, note: 'Family Code Title 4 protective orders.' },
  me: { l: 'Expected modifications and enforcements a year', cl: 'Modifications and enforcements, trailing 12 months', grp: 'Filings', g: 'C', cg: 'A', ramp: 'ember', z: z => (z.alloc.mod || 0) + (z.alloc.enf || 0), c: c => (c.filings.ttm.mod || 0) + (c.filings.ttm.enf || 0), f: v => N(v, 0), log: true, note: 'Existing orders relitigated: the least cyclical family law work (module 05).' },
  yoy: { l: 'Divorce filings, change vs prior 12 months (county)', grp: 'Filings', g: 'A', cg: 'A', ramp: 'div', c: c => c.rates.div_yoy, f: v => sgn(v, 1), note: 'County only: court counts do not exist by ZIP, so every ZIP shows its county.' },
  haz: { l: 'Composition hazard per 1,000 married (PUMS model)', grp: 'Marriage stock', g: 'B', cg: 'B', ramp: 'ember', z: z => z.risk.haz_pred, c: c => c.risk.haz_pred, f: v => N(v, 1), note: 'The Texas microdata model applied to who is married here. A population figure, never a statement about a couple.' },
  sep: { l: 'Separated per 1,000 married (ACS)', grp: 'Marriage stock', g: 'B', cg: 'B', ramp: 'ember', z: z => z.acs.sep_per_1k_married, c: c => c.acs.sep_per_1k_married, f: v => N(v, 0), note: 'Texas has no legal separation, so separations turn into filings. ZIP estimates carry wide survey margins.' },
  dur59: { l: 'Married 5 to 9 years, the peak hazard band (share)', grp: 'Marriage stock', g: 'B', cg: 'B', ramp: 'ember', z: z => z.risk.dur_5_9, c: c => c.risk.dur_5_9, f: v => P(v, 0), note: 'From the survey areas covering the ZIP or county, reweighted.' },
  rem: { l: 'Remarried, second or later marriage (share)', grp: 'Marriage stock', g: 'B', cg: 'B', ramp: 'ember', z: z => z.risk.remarried, c: c => c.risk.remarried, f: v => P(v, 0), note: 'Second marriages carry higher odds in the hazard model.' },
  m55: { l: 'Married 55 and over (share of married)', grp: 'Marriage stock', g: 'B', cg: 'A', ramp: 'slate', z: z => z.acs.mar_55p_sh, c: c => c.acs.mar_55p_sh, f: v => P(v, 0), note: 'The gray divorce pool.' },
  married: { l: 'Married adults (ACS, spouse present)', grp: 'Marriage stock', g: 'B', cg: 'A', ramp: 'slate', z: z => z.acs.married, c: c => c.acs.married, f: v => K(v), log: true, note: 'The ledger gives the 90% margin of error where the survey publishes one.' },
  mil: { l: 'Active duty exposure among married (PUMS)', grp: 'Marriage stock', g: 'B', cg: 'B', ramp: 'amber', z: z => z.risk.mil_active, c: c => c.risk.mil_active, f: v => P(v, 1), note: 'Military divorce is its own service line (module 06).' },
  kids: { l: 'Married couple families with children (share)', grp: 'Family structure', g: 'B', cg: 'A', ramp: 'amber', z: z => z.acs.mc_kids_sh, c: c => c.acs.mc_kids_sh, f: v => P(v, 0), note: 'Where a divorce becomes a custody case.' },
  cohab: { l: 'Cohabiting couples with children (share of couples with kids)', grp: 'Family structure', g: 'B', cg: 'A', ramp: 'amber', z: z => z.acs.cohab_kids_sh, c: c => c.acs.cohab_kids_sh, f: v => P(v, 0), note: 'A custody, paternity and support pool rather than a divorce pool.' },
  rentb: { l: 'Renters paying 35% or more on rent', grp: 'Strain and means', g: 'B', cg: 'A', ramp: 'amber', z: z => z.acs.rent_burden35_sh, c: c => c.acs.rent_burden35_sh, f: v => P(v, 0), note: 'Strain provokes conflict and blocks a filing that needs two households.' },
  rent: { l: 'Renters (share of households)', grp: 'Strain and means', g: 'B', cg: 'A', ramp: 'amber', z: z => z.acs.renter_sh, c: c => c.acs.renter_sh, f: v => P(v, 0), note: 'ACS tenure.' },
  inc: { l: 'Median household income', grp: 'Strain and means', g: 'B', cg: 'A', ramp: 'moss', z: z => z.acs.med_hh_inc, c: c => c.acs.med_hh_inc, f: v => $$$(v), note: 'Ability to pay a retainer; not part of any index.' },
  inc150: { l: 'Households over $150,000 (share)', grp: 'Strain and means', g: 'B', cg: 'A', ramp: 'moss', z: z => z.acs.inc_150k_sh, c: c => c.acs.inc_150k_sh, f: v => P(v, 0), note: 'The high asset line\'s pool (module 06).' },
  esi: { l: 'Economic Shock Index (county percentile)', grp: 'Economic shock', g: 'B', cg: 'B', ramp: 'steel', c: c => c.esi, f: v => N(v, 0), q: false, note: 'County only: claims, unemployment, WARN notices and payrolls against each county\'s 2019 baseline, ranked.' },
  urchg: { l: 'Unemployment rate change vs a year earlier (county, points)', grp: 'Economic shock', g: 'A', cg: 'A', ramp: 'div', c: c => c.econ.ur_chg_yoy, f: v => sgn(v, 1, ' pts'), note: 'County only: BLS LAUS.' },
  c19: { l: 'UI initial claims, last 13 weeks vs 2019 (county ratio)', grp: 'Economic shock', g: 'A', cg: 'A', ramp: 'steel', c: c => c.econ.claims_vs_2019, f: v => isN(v) ? N(v, 2) + '×' : NA, note: 'County only: Texas Workforce Commission weekly claims.' },
  fv: { l: 'Abuse investigations with family violence, FY2025, per 10,000 residents (county)', grp: 'Protection', g: 'A', cg: 'A', ramp: 'ember', c: c => c.dfps && isN(c.dfps.inv_fv['2025']) && c.pop2025 ? c.dfps.inv_fv['2025'] / c.pop2025 * 1e4 : null, f: v => N(v, 1), note: 'County only: DFPS Data Book. The protective order pool.' },
  offices: { l: 'Law offices (ZIP and County Business Patterns 2023)', grp: 'Supply', g: 'A', cg: 'A', ramp: 'slate', z: z => z.lawoffices, c: c => c.rates.lawoffices, f: v => N(v), log: true, zero: true, note: 'Every office of lawyers with a payroll, not only family law; solo lawyers without employees are not counted.' }
};
// the firm's own numbers from Accounts as layers, added only when Accounts holds rows for this metro (last 90 days)
const MT_ACCT = { aspend: ['Your spend, last 90 days (Accounts)', 'spend', v => $$$(v)], aleads: ['Your leads and calls, last 90 days (Accounts)', 'leads', v => N(v)], aintake: ['Your intakes, last 90 days (Accounts)', 'intake', v => N(v)] };
function mtOptions(cat, keys, cur) { const grp = k => (cat[k] || {}).grp || 'Other'; return [...new Set(keys.map(grp))].sort((a, b) => MT_GROUPS.indexOf(a) - MT_GROUPS.indexOf(b)).map(g => `<optgroup label="${esc(g)}">${keys.filter(k => grp(k) === g).map(k => `<option value="${esc(k)}"${k === cur ? ' selected' : ''}>${esc(cat[k].l)}</option>`).join('')}</optgroup>`).join(''); }
// a ledger row: label, value, grade, and an optional note line
const mtRow = (l, v, g, note) => `<div class="mt-row"><span>${esc(l)} ${g ? `<span class="grade ${g}">${g}</span>` : ''}${note ? `<em>${note}</em>` : ''}</span><b>${v}</b></div>`;
const mtMoe = (v, cv) => isN(v) && isN(cv) ? ` <span class="small">± ${N(1.645 * cv * v)}</span>` : '';
let MT_TOK = 0;
// every lookup is scoped to root, and num is unique per tab (Other Metros is 19), so two metro tabs never share an element
function metroHTML(root, codes, title, num, opt) {
  opt = opt || {}; const R = s => $(s, root), RR = s => $$(s, root); const tok = root.__mtTok = ++MT_TOK; const live = () => root.isConnected && root.__mtTok === tok;
  const S = metroSummary(codes); const SV = store.get('sev.metro.' + num, null) || {};
  const st = { layer: MT_LAYERS[SV.layer] ? SV.layer : 'eff', mode: SV.mode === 'county' ? 'county' : 'zip', sel: null, code: codes[0], cty: '', pins: SV.pins !== false };
  const save = () => store.set('sev.metro.' + num, { layer: st.layer, mode: st.mode, pins: st.pins });
  const cs = S.cs.slice().sort((a, b) => (b.filings.ttm.div || 0) - (a.filings.ttm.div || 0));
  const lead = cs[0]; const one = cs.length === 1; const scope = opt.scope || (codes.length > 1 ? "the valley's" : "the metro's");
  // growth: counties with 200 or more filings and a real year over year change; the fastest riser, or the smallest fall when none rose
  const g200 = cs.filter(c => (c.filings.ttm.div || 0) >= 200 && isN(c.rates.div_yoy) && !S.gaps.includes(c)); const risers = g200.filter(c => c.rates.div_yoy > 0).sort((a, b) => b.rates.div_yoy - a.rates.div_yoy);
  const growS = risers.length ? `${esc(risers[0].name)} County is ${updown(risers[0].rates.div_yoy)} on the prior twelve months${risers.length > 1 ? `, the fastest of the ${atNum(risers.length)} counties with 200 or more filings that grew` : ''}` : g200.length ? `No county with 200 or more filings grew; the smallest fall was ${esc(g200.slice().sort((a, b) => b.rates.div_yoy - a.rates.div_yoy)[0].name)} County (${updown(g200.slice().sort((a, b) => b.rates.div_yoy - a.rates.div_yoy)[0].rates.div_yoy)})` : 'No county here files 200 or more divorces a year, too few to read a trend county by county';
  const rx = (a, b) => isN(a) && isN(b) && b > 0 ? a / b : null; const cl19 = rx(S.w13, S.w13_19), clY = rx(S.w13, S.w13y); const odd = [cl19, clY].some(v => isN(v) && (v < 0.5 || v > 2));
  const hiZ = S.zs.filter(z => z.acs.married > 1500).sort((a, b) => (b.risk.haz_pred || 0) - (a.risk.haz_pred || 0)).slice(0, 5);
  const shockC = cs.slice().sort((a, b) => (b.esi || 0) - (a.esi || 0))[0]; const hiRate = cs.slice().sort((a, b) => (b.rates.div_per_1k_married || 0) - (a.rates.div_per_1k_married || 0))[0];
  const gapNote = S.gaps.length ? ` ${S.gaps.map(c => esc(c.name) + ' County').join(' and ')}'s clerk reported no filings for the last twelve months, so ${S.gaps.length > 1 ? 'they are' : 'it is'} left out of both sides of these comparisons.` : '';
  const shrink = S.sectors.filter(s => s.chg < 0).sort((a, b) => a.chg - b.chg).slice(0, 3);
  const ttG = k => S.ttm[k] - sum(S.gaps.map(c => c.filings.ttm[k] || 0));   // gap counties report 0, so this equals the total
  const atl = AT_BY_CODE[codes[0]]; const modKey = num === '19' ? 'others' : (METRO_TABS.find(t => t.num === num) || {}).key;
  root.innerHTML = mastHTML({ eyebrow: `Module ${num} · ${opt.group ? opt.group : title} · ${codes.map(c => MNAME(MSA[c].title)).join(' and ')} metropolitan statistical area${codes.length > 1 ? 's' : ''} (OMB 2023)`, title, dek: `${S.cs.length} count${S.cs.length > 1 ? 'ies' : 'y'}, ${N(S.pop)} residents (Census Vintage 2025 estimates), ${N(S.married)} married adults (ACS 2020 to 2024 county estimates, spouse present; the Metro Atlas adds up block groups instead, so its counts differ) and ${N(S.zs.length)} ZIP codes with data. Residents filed ${N(S.ttm.div)} divorces in the last twelve months (${sgn((ttG('div') / (S.prev.div || 1) - 1) * 100)} on the prior twelve, ${sgn((ttG('div') / (S.y19 || 1) - 1) * 100)} on 2019), ${N(S.ttm.sapcr)} custody suits, ${N(S.ttm.po)} protective order applications and ${N(S.ttm.mod + S.ttm.enf)} modifications and enforcements.${gapNote} The map resolves the metro to the ZIP code; the county table resolves it to the county.`, facts: [[N(S.rate, 1), 'divorce filings per 1,000 married (state ' + N(stTTM('div') / ST.acs.married * 1000, 1) + ')'], [N(S.esi, 0), 'economic shock index, population weighted'], [P1(S.ur), 'unemployment, ' + fmtDate(META.laus_through) + (isN(S.urY) ? ' (' + sgn(S.ur - S.urY, 1, ' pts') + ' vs year earlier)' : '')], [N(S.offices), 'law offices']] }) + `
  <div class="toolbar"><span class="ttl">${esc(title)}</span><span class="sub">ZIP or county map · county table · ledger · monthly series · layoffs</span>${opt.picker ? `<span class="tbpick">${opt.picker}</span>` : ''}<span class="sp"></span><button type="button" class="btn" id="mtZipCsv_${num}">↓ ZIP CSV</button><button type="button" class="btn" id="mtCtyCsv_${num}">↓ Counties CSV</button>${atl ? `<button type="button" class="btn" id="mtAtlas_${num}">Metro Atlas ↗</button>` : ''}<button type="button" class="btn" id="mtPaid_${num}">Paid Acquisition ↗</button><button type="button" class="btn" id="mtDesk_${num}" title="The metro, with the selected or filtered ZIPs">Campaign Desk ↗</button><button type="button" class="btn" id="mtForge_${num}" title="The selected or filtered counties and ZIPs">Site Forge ↗</button><button type="button" class="btn" id="mtWatch_${num}">Competitor Watch ↗</button><button type="button" class="btn" id="mtGround_${num}">Ground Truth ↗</button></div>
  <div class="callout"><div class="h">Read this first: ${esc(title)} in four parts</div><p><b>Where the filings are.</b> ${one ? `${esc(lead.name)} County is the whole metro: ${N(lead.filings.ttm.div)} divorce filings at ${N(lead.rates.div_per_1k_married, 1)} per 1,000 married` : `${esc(lead.name)} County carries ${N(lead.filings.ttm.div)} of ${scope} ${N(S.ttm.div)} divorce filings (${P(lead.filings.ttm.div / (S.ttm.div || 1), 0)}) at ${N(lead.rates.div_per_1k_married, 1)} per 1,000 married${hiRate !== lead ? `; the highest rate is ${esc(hiRate.name)} County at ${N(hiRate.rates.div_per_1k_married, 1)}` : ', the highest rate here too'}`}. <b>Where they are growing.</b> ${one ? (isN(lead.rates.div_yoy) && !S.gaps.length ? `${esc(lead.name)} County is ${updown(lead.rates.div_yoy)} on the prior twelve months` : 'No like for like change to report') : growS}${!one ? `; ${codes.length > 1 ? 'the valley' : 'the metro'} as a whole is ${updown((ttG('div') / (S.prev.div || 1) - 1) * 100)}` : ''}. <b>Where the married population is built to divorce.</b> The highest composition hazards among ZIPs with 1,500 or more married adults: ${hiZ.map(z => `${z.zip} ${esc(z.city)} (${N(z.risk.haz_pred, 1)})`).join(', ')}. <b>Where the economy is pushing.</b> ${one ? `${esc(shockC.name)} County's shock index is ${N(shockC.esi, 0)}` : `${esc(shockC.name)} County has ${scope} highest shock index (${N(shockC.esi, 0)})`}; claims run ${isN(cl19) ? N(cl19, 2) + '×' : 'n/a'} the same weeks of 2019 and ${isN(clY) ? N(clY, 2) + '×' : 'n/a'} a year ago${odd ? ' (a swing that large can be a change in how the county\'s claims are counted; check the Texas Workforce Commission series before acting on it)' : ''}, ${N(S.warn12)} workers were on WARN notices in the last twelve months${shrink.length ? `, and payrolls shrank most in ${shrink.map(s => s.name.toLowerCase() + ' (' + sgn(s.chg, 0, '') + ')').join(', ')}` : ''}. ${N(S.exposed)} married adults here live in a household where either spouse is unemployed.</p><p>Court counts exist by county only, so every ZIP filing figure here is an allocation of its county's count (grade C); the Counties view paints the county values themselves. Nothing on this tab describes a household. The filing record, survey precision and the data inventory for the metro are in Ground Truth (module 28).</p></div>
  <div class="tiles">${tile('Divorce filings', N(S.ttm.div), `${P(S.ttm.div_k / (S.ttm.div || 1), 0)} with children · ${N(S.ttm.d_div)} disposed`, 'A')}${tile('Custody, SAPCR', N(S.ttm.sapcr), sgn((S.ttm.sapcr / (S.prev.sapcr || 1) - 1) * 100) + ' vs prior 12 months', 'A')}${tile('Protective orders', N(S.ttm.po), sgn((S.ttm.po / (S.prev.po || 1) - 1) * 100) + ' vs prior 12 months', 'A')}${tile('Modification + enforcement', N(S.ttm.mod + S.ttm.enf), sgn(((S.ttm.mod + S.ttm.enf) / ((S.prev.mod + S.prev.enf) || 1) - 1) * 100) + ' vs prior 12 months', 'A')}${tile('Private filings per office', N(S.ttm.priv / (S.offices || 1), 1), N(S.ttm.priv) + ' private family filings, ' + N(S.offices) + ' offices', 'C')}${tile('Dissolution Index', N(S.di, 0), 'population weighted county average', 'B')}</div>
  <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', `<select id="mtLayer_${num}"></select>`)}<div class="ctl"><span class="ctlh" id="mtModeL_${num}">Show</span>${segHTML('mtMode_' + num, [['zip', 'ZIPs'], ['county', 'Counties']], st.mode).replace('role="group"', `role="group" aria-labelledby="mtModeL_${num}"`)}</div>${codes.length > 1 ? ctl('Area', sel('mtCode_' + num, codes.map(c => [c, MNAME(MSA[c].title)]), codes[0])) : ''}${ctl('County filter', `<select id="mtCtyF_${num}"></select>`)}<div id="mtFind_${num}" class="mt-find"></div><label class="chk"><input type="checkbox" id="mtPins_${num}"${st.pins ? ' checked' : ''}> Show your offices and watched firms</label><button type="button" class="btn sm" id="mtReset_${num}">Reset</button></div>
  <div class="split"><div><div class="mapwrap" id="mtMap_${num}"></div><div id="mtLeg_${num}"></div></div><div class="mt-led"><div class="ix-eb" id="mtLedE_${num}"></div><h3 id="mtLedT_${num}"></h3><div class="small" id="mtLedS_${num}"></div><div id="mtLed_${num}"></div></div></div></div>
  <div class="panel" style="margin-bottom:14px"><h3>Counties</h3><div class="sub">Sortable. Click a row (or focus it and press Enter) to select the county on the map and open its ledger beside it. Filings are the clerks' counts (grade A); a county with a reporting gap is marked.</div><div id="mtCty_${num}"></div></div>
  <div class="grid2"><div class="panel"><h3>Filings by month</h3><div class="sub">Sum of the metro's counties, ${seriesSpan()}.</div><div class="chart" id="mtChart_${num}"></div></div><div class="panel"><h3>Layoffs and payrolls</h3><div class="sub">The largest WARN notices among each county's 12 most recent of the last 24 months (all the data keeps${S.capped.length ? `; ${S.capped.map(esc).join(', ')} had more, which the Metro Atlas maps city by city` : ''}), then private payroll change by sector, ${qcewQ()} vs ${qcewPrev()}${S.suppressed ? ` (${S.suppressed} county sector${S.suppressed === 1 ? ' is' : 's are'} suppressed by QCEW and left out)` : ''}.</div><div class="warnlist">${S.warn.map(r => `<div><span title="${esc(CO(r.co))}">${esc(CO(r.co))} · ${esc(r.city)} (${esc(r.county)})</span><span>${esc(fmtDate(r.notice))}</span><span class="num">${N(r.n)}</span></div>`).join('') || '<div class="small">No WARN notices in the last 24 months.</div>'}</div><div class="chart" id="mtSect_${num}" style="margin-top:8px"></div></div></div>
  <div class="grid2"><div class="panel"><h3 id="mtEffH_${num}">Most efficient ZIPs</h3><div class="sub">Expected filings per competing law office, ranked across all metro ZIPs. Click a ZIP to select it.</div><div id="mtEff_${num}"></div></div><div class="panel"><h3>Firms watched in ${esc(title)}</h3><div class="sub">From your Competitor Watch roster (module 24): firms serving these counties, with what you have logged. Severance ships no competitor list.</div><div id="mtWatchL_${num}"></div></div></div>
  <div class="panel"><h3 id="mtZipH_${num}">ZIP codes</h3><div class="sub">All ZIPs in the metro with data, scoped by the county filter, sortable. Filings are allocations (grade C). Criterion is the Google Ads location ID.</div><div id="mtTable_${num}"></div></div>
  ${srcFoot([['Sources', `Texas Office of Court Administration filings, ${esc(ttmSpan())}; ACS 2020 to 2024 county and ZIP estimates with their margins of error; the Texas PUMS hazard model; Texas Workforce Commission claims and WARN notices; BLS LAUS and QCEW; DFPS Data Book; ZIP and County Business Patterns 2023; Google Ads geotargets for criterion IDs. Pins come only from your firm profile and your Competitor Watch roster; spend and intake layers only from Accounts.`], ['Judgment calls', 'ZIP filings spread each county\'s clerk count by married adults times the modeled hazard; each ZIP belongs to the county holding most of its residents where the data shows it (module 20). The Counties view paints a county\'s value on all of its ZIPs, including ZIPs too small to estimate.'], ['Caveats', 'ZIP survey estimates carry wide margins (the ledger shows the married adults margin); law office counts include every kind of law office; ZIPs under 200 residents carry no estimates.']])}`;
  const mapEl = R(`#mtMap_${num}`);
  const reduce = () => !!(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  const M = () => GEO.metros[st.code]; const ctys = () => MSA[st.code].counties.slice().sort((a, b) => cname(a).localeCompare(cname(b)));
  const cOf = id => (ZI[id] && ZI[id].county) || (M().zc_county || {})[id] || null;
  const zipsOfC = f => Object.keys(M().zcta).filter(id => cOf(id) === f);
  // the firm's own numbers from Accounts for this metro (last 90 days), refreshed on 'actuals'
  const acc = { z: {}, c: {}, n: 0 };
  function refreshAcct() { acc.z = {}; acc.c = {}; acc.n = 0; ixAcctZip(90).forEach(o => { const z = o.z || ZI[o.zip]; if (!z || !codes.includes(z.msa)) return; acc.z[o.zip] = o; const c = acc.c[z.county] = acc.c[z.county] || { spend: 0, leads: 0, intake: 0, retained: 0 }; ['spend', 'leads', 'intake', 'retained'].forEach(k => { c[k] += o[k] || 0; }); acc.n++; }); }
  const layers = () => { const L = Object.assign({}, MT_LAYERS); if (acc.n) Object.keys(MT_ACCT).forEach(k => { const [l, f, fmt] = MT_ACCT[k]; L[k] = { l, grp: 'Your accounts', g: 'A', cg: 'A', ramp: 'leaf', z: z => acc.z[z.zip] ? acc.z[z.zip][f] : null, c: c => acc.c[c.fips] ? acc.c[c.fips][f] : null, f: fmt, log: true, note: 'Rows from your connected ad accounts and imports with a ZIP, last 90 days (module 23). ZIPs with none show as no data.' }; }); return L; };
  function layerSel() { const L = layers(); if (!L[st.layer]) st.layer = 'eff'; R(`#mtLayer_${num}`).innerHTML = mtOptions(L, Object.keys(L), st.layer); }
  function ctySel() { const s = R(`#mtCtyF_${num}`); s.innerHTML = `<option value="">All ${MSA[st.code].counties.length} counties</option>` + ctys().map(f => `<option value="${f}"${f === st.cty ? ' selected' : ''}>${esc(cname(f))}</option>`).join(''); }
  // the ZIPs in scope: the filter's county, or the whole area
  const scoped = () => metroZctas([st.code]).filter(z => !st.cty || z.county === st.cty);
  function draw() {
    const g = M(); const L = layers()[st.layer]; const zs = metroZctas([st.code]); const zi = {}; zs.forEach(z => { zi[z.zip] = z; }); const cs2 = MSA[st.code].counties.map(f => CI[f]);
    const useZip = st.mode === 'zip' && !!L.z; const Lx = useZip ? { l: L.l, ramp: L.ramp, v: L.z, f: L.f, q: L.q, log: L.log } : { l: L.cl || L.l, ramp: L.ramp, v: L.c, f: L.cf || L.f, q: L.cq !== undefined ? L.cq : L.q, log: L.clog !== undefined ? L.clog : L.log };
    const sc = layerScale(Lx, useZip ? zs : cs2); const objOf = id => useZip ? zi[id] : CI[cOf(id)];
    const isZero = id => !!(L.zero && objOf(id) && !(Lx.v(objOf(id)) > 0)); const alt = L.zero ? { test: isZero, color: 'var(--alt-fill)', label: 'no law office (CBP 2023)' } : null;
    const value = id => { const o = objOf(id); if (!o || isZero(id)) return null; if (!useZip && !cs2.includes(o)) return null; return Lx.v(o); };
    const countyNote = useZip ? '' : st.mode === 'zip' ? ' (county values: no ZIP version)' : ', county values on every ZIP';
    const tip = id => { const z = zi[id]; const c = CI[cOf(id)]; const v = value(id); const vs = isZero(id) ? 'no law office' : isN(v) ? Lx.f(v) : NA; if (!useZip) return `<b>${c ? esc(c.name) + ' County' : esc(id)}</b><div class="small">ZIP ${esc(id)}${z ? ' · ' + esc(z.city) : ''}</div><div class="row"><span>${esc(Lx.l)}</span><span>${esc(vs)}</span></div>${c ? `<div class="row"><span>Divorce filings, 12 mo</span><span>${N(c.filings.ttm.div)}</span></div><div class="row"><span>Grade</span><span>${esc(c.grade)}</span></div>` : ''}`; return z ? zipTipHTML(z, `<div class="row"><span>${esc(L.l)}</span><span>${esc(vs)}</span></div>`) : `<b>${esc(id)}</b><div class="small">Under 200 residents: no estimates for this ZIP.</div>`; };
    const fitIds = st.cty ? zipsOfC(st.cty) : null; const box = !IX_CORE && fitIds ? ixBox(fitIds.map(id => g.zcta[id]), g.W, g.H) : null;
    drawMap(mapEl, { title: title + ', ' + Lx.l + countyNote, W: g.W, H: g.H, paths: g.zcta, value, color: sc.color, alt, label: tip, onSelect: pick, onPin: p => ixPinGo(p, modKey), selected: st.mode === 'zip' && ZI[st.sel] ? st.sel : null, counties: g.county, cent: g.ccent, labels: Object.keys(g.county), labelText: id => CI[id] ? CI[id].name : id, legend: Object.assign({ title: Lx.l + countyNote, grade: useZip ? L.g : L.cg }, sc.legend), noDataLabel: useZip ? 'under 200 residents or no data' : 'no data', view: box || undefined, fit: IX_CORE ? (fitIds || undefined) : undefined });
    decorate(L, useZip);
  }
  function decorate(L, useZip) {
    L = L || layers()[st.layer]; if (useZip === undefined) useZip = st.mode === 'zip' && !!L.z;
    const keep = /^c:/.test(st.sel || '') ? new Set(zipsOfC(st.sel.slice(2))) : st.cty ? new Set(zipsOfC(st.cty)) : null; ixDim(mapEl, keep);
    const firm = IX_FIRM(); ixMarkFirmZip(mapEl, M(), firm); const pins = st.pins ? ixFirmPins(ixPlace(st.code)) : []; ixPins(mapEl, pins, { onPin: id => ixPinGo(id, modKey) });
    const nW = pins.filter(p => p.kind === 'watch').length, nF = pins.filter(p => p.kind === 'firm').length; const fIn = firm.filter(f => MSA[st.code].counties.includes(f));
    R(`#mtLeg_${num}`).innerHTML = `<div class="ix-legnote"><span class="grade ${esc(useZip ? L.g : L.cg)}">${esc(useZip ? L.g : L.cg)}</span> <b>${useZip ? 'ZIP values.' : st.mode === 'zip' ? 'County values on every ZIP: this layer has no ZIP version.' : 'County values painted on every ZIP of the county.'}</b> ${L.ramp === 'div' ? 'Above zero runs to the green end of the ramp, below zero to the slate end.' : 'Higher values sit toward the right end of the ramp.'} ${esc(L.note || '')}<div class="ix-legkeys">${st.cty || /^c:/.test(st.sel || '') ? `<span><i class="ix-sw dim"></i>Faded: outside ${esc(cname(/^c:/.test(st.sel || '') ? st.sel.slice(2) : st.cty))} County</span>` : ''}${fIn.length ? `<span><i class="ix-sw firm"></i>Heavy outline: the ${fIn.length === 1 ? 'county' : fIn.length + ' counties'} the firm serves here</span>` : ''}${st.pins ? `<span><i class="ix-sw pinf"></i>Your offices (${nF})</span><span><i class="ix-sw pinw"></i>Watched firms' offices (${nW}), sized by logged reviews</span>` : ''}</div>${st.pins && !nF && !nW ? '<div class="small">No office in this metro to pin: add offices in the firm profile (the Firm button) or firms with offices in Competitor Watch.</div>' : ''}</div>`;
  }
  // ---- the ledger beside the map: the selected ZIP or county, else the filter's county, else the metro
  function ledger() {
    const E = R(`#mtLedE_${num}`), T = R(`#mtLedT_${num}`), Sb = R(`#mtLedS_${num}`), host = R(`#mtLed_${num}`);
    const btns = list => `<div class="ix-btns">${list.map(b => `<button type="button" class="btn sm" data-lg="${b[0]}">${esc(b[1])}</button>`).join('')}</div>`;
    const wire = map => $$('[data-lg]', host).forEach(b => b.onclick = () => map[b.dataset.lg]());
    const z = ZI[st.sel];
    if (z) {
      const a = z.acs, r = z.risk, c = CI[z.county]; const ac = acc.z[z.zip];
      E.textContent = `ZIP · ${c ? c.name + ' County' : ''}`; T.textContent = `${z.zip} ${z.city}`; Sb.textContent = `Google Ads criterion ${z.gt || NA} · ${IX_FIRM().includes(z.county) ? 'in a county you serve' : 'outside your counties'}`;
      host.innerHTML = mtRow('Residents', N(a.pop), 'B') + mtRow('Married adults', N(a.married) + mtMoe(a.married, a.married_cv), 'B', isN(a.married_cv) ? `90% margin from the survey's CV of ${P(a.married_cv, 1)}` : '') +
        mtRow('Expected divorce filings a year', N(z.alloc.div, 0), 'C', `an allocation of ${c ? esc(c.name) : 'the'} County's ${c ? N(c.filings.ttm.div) : ''} filings (${P(z.alloc_share, 1)} share)`) + mtRow('Expected per 1,000 married', N(z.exp_div_per_1k_married, 1), 'C') + mtRow('SAPCR / PO / mod + enf a year', `${N(z.alloc.sapcr, 0)} / ${N(z.alloc.po, 0)} / ${N((z.alloc.mod || 0) + (z.alloc.enf || 0), 0)}`, 'C', 'allocations') +
        mtRow('Composition hazard per 1,000', N(r.haz_pred, 1), 'B', 'model') + mtRow('Separated per 1,000 married', N(a.sep_per_1k_married, 0), 'B') + mtRow('Married 5 to 9 years / remarried', `${P(r.dur_5_9, 0)} / ${P(r.remarried, 0)}`, 'B') + mtRow('Married couple families with children', P(a.mc_kids_sh, 0), 'B') + mtRow('Couples with children who cohabit', P(a.cohab_kids_sh, 0), 'B') +
        mtRow('Median household income', $$$(a.med_hh_inc), 'B') + mtRow('Households over $150,000', P(a.inc_150k_sh, 0), 'B') + mtRow('Renters / rent burden 35%+', `${P(a.renter_sh, 0)} / ${P(a.rent_burden35_sh, 0)}`, 'B') + mtRow('Active duty / veterans', `${P(r.mil_active, 1)} / ${P(a.vet_sh, 0)}`, 'B') +
        mtRow('Law offices in the ZIP', z.lawoffices ? N(z.lawoffices) : 'none', 'A', 'ZIP Business Patterns 2023') + mtRow('Efficiency / opportunity / ZIP index', `${N(z.paid.eff_pct, 0)} / ${N(z.paid.opp_pct, 0)} / ${N(z.di, 0)}`, 'C', 'percentiles across metro ZIPs') +
        (ac ? mtRow('Your spend / leads / intakes, 90 days', `${$$$(ac.spend)} / ${N(ac.leads)} / ${N(ac.intake)}`, 'A', 'Accounts (module 23)') : '') + zipGapNote(z) +
        btns([['desk', 'Campaign Desk ↗'], ['forge', 'Site Forge ↗'], ['paid', 'Paid Acquisition ↗'], ['ground', 'Ground Truth ↗'], ['index', 'Dissolution Index ↗'], ['clear', 'Back to the metro']]);
      wire({ desk: () => goModule('desk', { geo: 'msa:' + z.msa, zips: [z.zip] }), forge: () => goModule('forge', { zips: [z.zip], counties: [z.county] }), paid: () => goModule('paid', { metro: z.msa, zip: z.zip }), ground: () => goModule('ground', { zip: z.zip }), index: () => goModule('index', { county: z.county }), clear: () => clearSel() });
      return;
    }
    const f = /^c:/.test(st.sel || '') ? st.sel.slice(2) : st.cty; const c = CI[f];
    if (c) {
      const t = c.filings.ttm, gap = S.gaps.includes(c), a = c.acs, ac = acc.c[f], w = ixWatchIn(f);
      E.textContent = (st.sel ? 'County selected' : 'County filter') + ' · grade ' + c.grade; T.textContent = c.name + ' County'; Sb.textContent = `${N(zipsOfC(f).filter(id => ZI[id]).length)} ZIPs with data · ${N(c.pop2025)} residents${IX_FIRM().includes(f) ? ' · a county you serve' : ''}`;
      host.innerHTML = mtRow('Divorce filings, ' + c.filings.ttm_label, gap ? 'no clerk report' : N(t.div), 'A', gap ? `${N(c.filings.ttm_prev.div)} the twelve months before` : `${P(c.rates.div_k_share, 0)} with children`) + mtRow('Per 1,000 married adults', N(c.rates.div_per_1k_married, 1), 'A') + mtRow('Change vs prior 12 months / vs 2019', `${sgn(c.rates.div_yoy)} / ${sgn(c.rates.div_vs_2019)}`, 'A') + mtRow('SAPCR / PO / mod + enf', `${N(t.sapcr)} / ${N(t.po)} / ${N((t.mod || 0) + (t.enf || 0))}`, 'A') + mtRow('Divorces disposed', N(t.d_div), 'A') +
        mtRow('Married adults', N(a.married) + mtMoe(a.married, a.married_cv), 'A', isN(a.married_cv) ? `90% margin, CV ${P(a.married_cv, 1)}` : '') + mtRow('Separated per 1,000 married', N(a.sep_per_1k_married, 1), 'B') + mtRow('Composition hazard per 1,000', N(c.risk.haz_pred, 1), 'B', 'model') + mtRow('Dissolution Index / rank', `${N(c.di, 0)} / ${c.di_rank} of 254`, 'B') + mtRow('Economic Shock Index', N(c.esi, 0), 'B') +
        mtRow('Unemployment, ' + fmtDate((c.laus || {}).last), `${P1(c.laus ? c.laus.ur : null)} (${sgn(c.econ.ur_chg_yoy, 1, ' pts')})`, 'A') + mtRow('Claims vs same weeks of 2019', isN(c.econ.claims_vs_2019) ? N(c.econ.claims_vs_2019, 2) + '×' : NA, 'A') + mtRow('WARN workers, last 12 months', N(c.warn.last12.workers), 'A') + mtRow('Law offices / private filings per office', `${c.rates.lawoffices ? N(c.rates.lawoffices) : 'none'} / ${c.rates.lawoffices ? N(c.rates.filings_per_lawoffice, 1) : 'no office'}`, 'C', 'CBP 2023, every kind of law office') +
        (c.dfps && isN(c.dfps.inv_fv['2025']) ? mtRow('Abuse investigations with family violence, FY2025', N(c.dfps.inv_fv['2025']), 'A', 'DFPS') : '') + (ac ? mtRow('Your spend / leads / intakes, 90 days', `${$$$(ac.spend)} / ${N(ac.leads)} / ${N(ac.intake)}`, 'A', 'Accounts (module 23)') : '') + (w.length ? `<div class="ix-own"><b>Firms watched here:</b> ${w.slice(0, 6).map(x => esc(x.name)).join(', ')}${w.length > 6 ? ` and ${w.length - 6} more` : ''}.</div>` : '') +
        btns([['desk', 'Campaign Desk ↗'], ['forge', 'Site Forge ↗'], ['index', 'Dissolution Index ↗'], ['watch', 'Competitor Watch ↗'], ['ground', 'Ground Truth ↗']].concat(st.sel ? [['clear', 'Back to the metro']] : []));
      wire({ desk: () => goModule('desk', { geo: 'msa:' + st.code, counties: [f], zips: zipsOfC(f).filter(id => ZI[id]) }), forge: () => goModule('forge', { counties: [f], zips: zipsOfC(f).filter(id => ZI[id]) }), index: () => goModule('index', { county: f }), watch: () => goModule('watch', { county: f, from: modKey }), ground: () => goModule('ground', { county: f }), clear: () => clearSel() });
      return;
    }
    const w = new Set(); S.cs.forEach(x => ixWatchIn(x.fips).forEach(c2 => w.add(c2.name)));
    E.textContent = 'Metro'; T.textContent = codes.length > 1 ? MNAME(MSA[st.code].title) : title; Sb.textContent = 'Click a ZIP or a county for its ledger.';
    const mm = codes.length > 1 ? metroSummary([st.code]) : S;
    host.innerHTML = mtRow('Divorce filings, last 12 months', N(mm.ttm.div), 'A', `${P(mm.ttm.div_k / (mm.ttm.div || 1), 0)} with children`) + mtRow('Per 1,000 married adults', N(mm.rate, 1), 'A', `Texas ${N(stTTM('div') / ST.acs.married * 1000, 1)}`) + mtRow('Custody suits / protective orders', `${N(mm.ttm.sapcr)} / ${N(mm.ttm.po)}`, 'A') + mtRow('Modifications and enforcements', N(mm.ttm.mod + mm.ttm.enf), 'A') +
      mtRow('Married adults', N(mm.married) + (isN(mm.marriedMoe) ? ` <span class="small">± ${N(mm.marriedMoe)}</span>` : ''), 'A', '90% margin combined from the county margins') + mtRow('Residents, 2025', N(mm.pop), 'A') + mtRow('Dissolution Index, population weighted', N(mm.di, 0), 'B') + mtRow('Economic Shock Index, population weighted', N(mm.esi, 0), 'B') + mtRow('Unemployment, ' + fmtDate(META.laus_through), P1(mm.ur), 'A') + mtRow('WARN workers, last 12 months', N(mm.warn12), 'A') + mtRow('Law offices / private filings per office', `${N(mm.offices)} / ${N(mm.ttm.priv / (mm.offices || 1), 1)}`, 'C') +
      (acc.n ? mtRow('Your spend / leads / intakes, 90 days', `${$$$(sum(Object.values(acc.z).filter(o => (o.z || ZI[o.zip] || {}).msa === st.code).map(o => o.spend)))} / ${N(sum(Object.values(acc.z).filter(o => (o.z || ZI[o.zip] || {}).msa === st.code).map(o => o.leads)))} / ${N(sum(Object.values(acc.z).filter(o => (o.z || ZI[o.zip] || {}).msa === st.code).map(o => o.intake)))}`, 'A', `${N(acc.n)} ZIPs with account rows`) : '') +
      mtRow('Firms on your watch roster serving here', N(w.size), '', w.size ? esc([...w].slice(0, 4).join(', ')) + (w.size > 4 ? ' and more' : '') : 'none yet');
  }
  // ---- the county table: sortable, a row selects the county on this map (module 01 stays as it is)
  let ctbl = null, tbl = null;
  const ctyRows = () => { const fs = new Set(IX_FIRM()); return S.cs.map(c => { const gp = S.gaps.includes(c); const mo = isN(c.acs.married_cv) ? 1.645 * c.acs.married_cv * c.acs.married : null; return { _id: c.fips, name: c.name, fips: c.fips, grade: c.grade, msa: MNAME(MSA[c.msa] ? MSA[c.msa].title : ''), div: gp ? null : c.filings.ttm.div, rate: c.rates.div_per_1k_married, yoy: gp ? null : c.rates.div_yoy, sapcr: c.filings.ttm.sapcr, po: c.filings.ttm.po, me: (c.filings.ttm.mod || 0) + (c.filings.ttm.enf || 0), di: c.di, esi: c.esi, offices: c.rates.lawoffices || 0, fpo: c.rates.filings_per_lawoffice, ur: c.laus ? c.laus.ur : null, pop: c.pop2025, married: c.acs.married, moe: mo, gap: gp ? 'no clerk report for the last 12 months' : '', firm: fs.has(c.fips) ? 1 : 0 }; }); };
  const ccols = [{ k: 'name', l: 'County', fmt: (v, r) => esc(v) + (r.gap ? ' <span class="small">no report</span>' : '') }, { k: 'grade', l: 'Grade', fmt: v => `<span class="grade ${esc(v)}">${esc(v)}</span>`, h: 'Confidence grade' }, { k: 'div', l: 'Divorce filings', fmt: v => isN(v) ? N(v) : 'no report', h: 'Divorce filings, last 12 months', d: 0 }, { k: 'rate', l: 'per 1k married', fmt: v => N(v, 1), h: 'Divorce filings per 1,000 married', d: 1 }, { k: 'yoy', l: 'vs prior', fmt: v => sgn(v), h: 'Change vs prior 12 months (%)', d: 1 }, { k: 'sapcr', l: 'SAPCR', fmt: v => N(v), h: 'SAPCR filings, last 12 months', d: 0 }, { k: 'po', l: 'PO', fmt: v => N(v), h: 'Protective orders, last 12 months', d: 0 }, { k: 'me', l: 'Mod+enf', fmt: v => N(v), h: 'Modifications and enforcements, last 12 months', d: 0 }, { k: 'di', l: 'Index', fmt: v => N(v, 0), h: 'Dissolution Index', d: 0 }, { k: 'esi', l: 'Shock', fmt: v => N(v, 0), h: 'Economic Shock Index', d: 0 }, { k: 'offices', l: 'Law offices', fmt: v => v ? N(v) : 'none', h: 'Law offices (CBP 2023)', d: 0 }, { k: 'fpo', l: 'Filings/office', fmt: (v, r) => r.offices ? N(v, 1) : 'no office', h: 'Private family filings per law office', d: 1 }, { k: 'ur', l: 'Unemp', fmt: v => P1(v), h: 'Unemployment rate (%)', d: 1 }, { k: 'married', l: 'Married', fmt: (v, r) => N(v) + (isN(r.moe) ? ` <span class="small">± ${N(r.moe)}</span>` : ''), h: 'Married adults (ACS, spouse present)', d: 0 }, { k: 'firm', l: 'Yours', fmt: v => v ? 'served' : '', h: 'Served by the firm (firm profile)' }];
  function selCounty(f, scroll) { if (!CI[f]) return; if (!MSA[st.code].counties.includes(f)) { const k = codes.find(c => MSA[c].counties.includes(f)); if (!k) return; st.code = k; if (codes.length > 1) R(`#mtCode_${num}`).value = k; st.cty = ''; ctySel(); } st.sel = 'c:' + f; draw(); ledger(); if (ctbl) ctbl.setSel(f, true); if (tbl) tbl.setSel(null, true); if (scroll) mapEl.scrollIntoView({ block: 'center', behavior: reduce() ? 'auto' : 'smooth' }); }
  function pick(id) { const zc = cOf(id); if (st.mode === 'county' || !ZI[id]) { if (zc && CI[zc]) { selCounty(zc); } return; } st.sel = id; markSel(mapEl, id); decorate(); ledger(); if (tbl) tbl.setSel(id, true); if (ctbl) ctbl.setSel(null, true); }
  function clearSel() { st.sel = null; markSel(mapEl, null); decorate(); ledger(); if (tbl) tbl.setSel(null, true); if (ctbl) ctbl.setSel(null, true); }
  function selZip(id, scroll) { const z = ZI[id]; if (!z) return; if (z.msa !== st.code) { st.code = z.msa; if (codes.length > 1) R(`#mtCode_${num}`).value = st.code; st.cty = ''; ctySel(); } if (st.cty && z.county !== st.cty) { st.cty = ''; R(`#mtCtyF_${num}`).value = ''; rescope(); } st.sel = id; if (st.mode === 'county') { st.mode = 'zip'; $$('button', R(`#mtMode_${num}`)).forEach(b => b.setAttribute('aria-pressed', String(b.dataset.v === 'zip'))); save(); } draw(); ledger(); if (tbl) tbl.setSel(id, true); if (scroll) mapEl.scrollIntoView({ block: 'center', behavior: reduce() ? 'auto' : 'smooth' }); }
  // ---- the ZIP ranking, the efficient list and the watch list follow the county filter
  const cols = [{ k: 'zip', l: 'ZIP', fmt: v => esc(v) }, { k: 'city', l: 'City', fmt: v => esc(v), cls: 'l' }, { k: 'county', l: 'County', fmt: v => esc(v), cls: 'l' }, { k: 'eff', l: 'Efficiency', fmt: v => N(v, 0), h: 'Efficiency percentile (filings per competing law office)', d: 0 }, { k: 'opp', l: 'Opportunity', fmt: v => N(v, 0), h: 'Opportunity percentile (expected private family filings)', d: 0 }, { k: 'di', l: 'Index', fmt: v => N(v, 0), h: 'ZIP Dissolution Index', d: 0 }, { k: 'div', l: 'Div/yr', fmt: v => N(v, 0), h: 'Expected divorce filings a year (allocation)', d: 0 }, { k: 'sapcr', l: 'SAPCR', fmt: v => N(v, 0), h: 'Expected SAPCR filings a year (allocation)', d: 0 }, { k: 'po', l: 'PO', fmt: v => N(v, 0), h: 'Expected protective orders a year (allocation)', d: 0 }, { k: 'me', l: 'Mod+Enf', fmt: v => N(v, 0), h: 'Expected modifications and enforcements a year (allocation)', d: 0 }, { k: 'haz', l: 'Hazard', fmt: v => N(v, 1), h: 'Composition hazard per 1,000 married (model)', d: 1 }, { k: 'sep', l: 'Sep/1k', fmt: v => N(v, 0), h: 'Separated per 1,000 married (ACS)', d: 0 }, { k: 'married', l: 'Married', fmt: (v, r) => N(v) + (isN(r.moe) ? ` <span class="small">± ${N(r.moe)}</span>` : ''), h: 'Married adults (ACS)', d: 0 }, { k: 'moe', l: '± 90%', fmt: v => N(v), h: 'Married adults, 90% margin of error', d: 0 }, { k: 'kids', l: 'Married w/ kids', fmt: v => P(v, 0), h: 'Married couple families with children (%)', d: 0, pct: true }, { k: 'inc', l: 'Income', fmt: v => $$$(v), h: 'Median household income ($)', d: 0 }, { k: 'offices', l: 'Offices', fmt: v => v ? N(v) : 'none', h: 'Law offices in the ZIP (ZBP 2023)', d: 0 }, { k: 'acct', l: 'Your spend 90d', fmt: v => isN(v) ? $$$(v) : '', h: 'Your spend, last 90 days (Accounts)', d: 0 }, { k: 'gt', l: 'Criterion', fmt: v => esc(v), h: 'Google Ads location ID' }];
  const viewCols = () => cols.filter(c => c.k !== 'moe' && (c.k !== 'acct' || acc.n));
  const zipRows = () => scoped().map(z => ({ _id: z.zip, zip: z.zip, city: z.city, county: z.county_name, eff: z.paid.eff_pct, opp: z.paid.opp_pct, di: z.di, div: z.alloc.div, sapcr: z.alloc.sapcr, po: z.alloc.po, me: (z.alloc.mod || 0) + (z.alloc.enf || 0), haz: z.risk.haz_pred, sep: z.acs.sep_per_1k_married, married: z.acs.married, moe: isN(z.acs.married_cv) && isN(z.acs.married) ? 1.645 * z.acs.married_cv * z.acs.married : null, kids: z.acs.mc_kids_sh, inc: z.acs.med_hh_inc, offices: z.lawoffices, acct: acc.z[z.zip] ? acc.z[z.zip].spend : null, gt: z.gt, msa: z.msa, metro: MSA[z.msa] ? MNAME(MSA[z.msa].title) : '', fips: z.county }));
  function effList() {
    const effZ = scoped().filter(z => isN(z.paid.eff_pct)).sort((a, b) => b.paid.eff_pct - a.paid.eff_pct).slice(0, 8); R(`#mtEffH_${num}`).textContent = 'Most efficient ZIPs' + (st.cty ? ', ' + cname(st.cty) + ' County' : '');
    R(`#mtEff_${num}`).innerHTML = effZ.length ? `<div class="tblwrap"><table class="t"><caption class="vh">Most efficient ZIPs</caption><thead><tr><th scope="col">ZIP</th><th scope="col" class="l">City</th><th scope="col">Efficiency</th><th scope="col">Div/yr</th><th scope="col" title="Law offices in the ZIP (ZIP Business Patterns 2023)">Offices</th></tr></thead><tbody>${effZ.map(z => `<tr><td class="name"><button type="button" class="linkbtn" data-z="${esc(z.zip)}">${esc(z.zip)}</button></td><td class="l">${esc(z.city)}</td><td>${N(z.paid.eff_pct, 0)}</td><td>${N(z.alloc.div, 0)}</td><td>${z.lawoffices ? N(z.lawoffices) : 'none'}</td></tr>`).join('')}</tbody></table></div>${effZ.some(z => !z.lawoffices) ? '<p class="small" style="margin-top:4px">Efficiency counts filings against law offices inside the ZIP; a ZIP with none scores high because its families use offices nearby.</p>' : ''}` : '<p class="small">No ZIP with data in this county.</p>';
    $$('.linkbtn[data-z]', R(`#mtEff_${num}`)).forEach(b => b.onclick = () => selZip(b.dataset.z, true));
  }
  function watchList() {
    const host = R(`#mtWatchL_${num}`); const fs = st.cty ? [st.cty] : S.cs.map(c => c.fips); const seen = new Map(); fs.forEach(f => ixWatchIn(f).forEach(c => { if (!seen.has(c.key)) seen.set(c.key, { c, fs: [] }); seen.get(c.key).fs.push(f); }));
    if (!seen.size) { host.innerHTML = `<p class="small">${typeof WATCH === 'undefined' ? 'Competitor Watch is not loaded.' : `No firm on your roster serves ${st.cty ? esc(cname(st.cty)) + ' County' : 'these counties'} yet. Add the firms you meet in consultations, in court and on the results page in Competitor Watch.`}</p><div class="ix-btns"><button type="button" class="btn sm" id="mtWGo_${num}">Competitor Watch ↗</button></div>`; R(`#mtWGo_${num}`).onclick = () => goModule('watch', { metro: st.code, from: modKey }); return; }
    const rows = [...seen.values()].map(({ c, fs: cf }) => { const rv = WATCH.reviews(c.key); const sd = WATCH.scoreDetail ? WATCH.scoreDetail(c) : { score: WATCH.score(c), live: 0 }; return { c, cf, rv, sd }; }).sort((a, b) => b.sd.score - a.sd.score);
    host.innerHTML = `<div class="tblwrap"><table class="t"><caption class="vh">Firms watched in ${esc(title)}</caption><thead><tr><th scope="col" class="l">Firm</th><th scope="col">Activity</th><th scope="col">Live ads</th><th scope="col">Reviews logged</th><th scope="col" class="l">Counties here</th></tr></thead><tbody>${rows.map(x => `<tr><td class="l"><button type="button" class="linkbtn" data-w="${esc(x.c.key)}">${esc(x.c.name)}</button></td><td>${N(x.sd.score)}</td><td>${N(x.sd.live || 0)}</td><td>${x.rv.latest ? N(x.rv.latest.count) + (x.rv.latest.rating != null ? ' · ' + N(x.rv.latest.rating, 1) + '★' : '') : 'none'}</td><td class="l">${esc(x.cf.map(cname).join(', '))}</td></tr>`).join('')}</tbody></table></div><div class="ix-btns"><button type="button" class="btn sm" id="mtWGo_${num}">Competitor Watch ↗</button></div>`;
    $$('[data-w]', host).forEach(b => b.onclick = () => goModule('watch', { comp: b.dataset.w, from: modKey })); R(`#mtWGo_${num}`).onclick = () => goModule('watch', { metro: st.code, from: modKey });
  }
  function rescope() { if (tbl) tbl.setRows(zipRows()); R(`#mtZipH_${num}`).textContent = 'ZIP codes' + (st.cty ? ', ' + cname(st.cty) + ' County' : ''); effList(); watchList(); }
  // ---- charts
  if (S.series) { const s = S.series; lineChart(R(`#mtChart_${num}`), { title: title + ' filings by month', series: [{ name: 'Divorce filed', color: 'var(--s1)', values: s.div.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'Protective orders', color: 'var(--s2)', values: s.po.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'SAPCR', color: 'var(--s3)', values: s.sapcr.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'Modification + enforcement', color: 'var(--s4)', values: s.mod.map((v, i) => ({ x: s.t0 + i, y: v + s.enf[i] })) }, { name: 'Divorce disposed', color: 'var(--s5)', values: s.d_div.map((v, i) => ({ x: s.t0 + i, y: v })) }], W: 640, H: 240, bands: [{ x0: s.t0 + s.div.length - 2, x1: s.t0 + s.div.length - 1, label: 'provisional' }], xfmt: tLabel, xTicks: [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026].map(y => y * 12), xTickFmt: v => String(v / 12), yfmt: v => N(v) }); }
  else R(`#mtChart_${num}`).innerHTML = '<p class="small">No monthly court series for these counties; their filings are annual.</p>';
  if (S.sectors.length) barChart(R(`#mtSect_${num}`), { title: title + ' payroll change by sector', rows: S.sectors.slice().sort((a, b) => a.chg - b.chg).map(s => ({ label: s.name, value: s.chg, color: s.chg < 0 ? 'var(--rp-slate-5)' : 'var(--rp-leaf-5)' })), W: 560, lw: 200, fmt: v => sgn(v, 0, '') });
  // ---- controls
  refreshAcct(); layerSel(); ctySel();
  R(`#mtLayer_${num}`).onchange = e => { st.layer = e.target.value; save(); draw(); };
  wireSeg(R(`#mtMode_${num}`), v => { st.mode = v; if (v === 'county' && ZI[st.sel]) st.sel = 'c:' + ZI[st.sel].county; else if (v === 'zip' && /^c:/.test(st.sel || '')) st.sel = null; save(); draw(); ledger(); if (tbl) tbl.setSel(ZI[st.sel] ? st.sel : null, true); });
  if (codes.length > 1) R(`#mtCode_${num}`).onchange = e => { st.code = e.target.value; st.sel = null; st.cty = ''; ctySel(); if (IX_CORE && mapEl.__mz) mapHandle(mapEl).reset(); draw(); ledger(); rescope(); };
  R(`#mtCtyF_${num}`).onchange = e => { st.cty = e.target.value; if (st.sel && !(ZI[st.sel] && ZI[st.sel].county === st.cty) && st.sel !== 'c:' + st.cty) st.sel = null; if (!st.cty && IX_CORE && mapEl.__mz) mapHandle(mapEl).reset(); draw(); ledger(); rescope(); };
  R(`#mtPins_${num}`).onchange = e => { st.pins = e.target.checked; save(); decorate(); };
  R(`#mtReset_${num}`).onclick = () => { st.sel = null; st.cty = ''; R(`#mtCtyF_${num}`).value = ''; if (IX_CORE && mapEl.__mz) mapHandle(mapEl).reset(); draw(); ledger(); rescope(); if (ctbl) ctbl.setSel(null, true); };
  // find: the core's find box scoped to the metro when it is there (a ZIP, a city or a county), else a ZIP or city field
  const onPlace = p => { if (!p) return; if (p.kind === 'zip' || (p.kind === 'city' && p.zip)) { selZip(p.zip, false); if (p.kind === 'city') toast(`${p.city}: its largest ZIP, ${p.zip}, is selected`); } else if (p.fips) selCounty(p.fips, false); };
  if (typeof findBox === 'function') findBox(R(`#mtFind_${num}`), onPlace, { scope: () => ({ msa: codes }), label: 'Find a ZIP, city or county', placeholder: (() => { const z = S.zs.slice().sort((a, b) => (b.acs.married || 0) - (a.acs.married || 0))[0]; return z ? `${z.zip} or ${z.city}` : 'a ZIP or a city'; })(), where: title, id: 'mtFindI_' + num });
  else { R(`#mtFind_${num}`).innerHTML = ctl('Find a ZIP or city', `<input type="search" id="mtFindI_${num}" autocomplete="off" placeholder="a ZIP or a city">`); const inp = R(`#mtFindI_${num}`); inp.onkeydown = e => { if (e.key !== 'Enter') return; const q = inp.value.trim().toLowerCase(); const z = ZI[q] && codes.includes(ZI[q].msa) ? ZI[q] : S.zs.filter(x => (x.city || '').toLowerCase().startsWith(q)).sort((a, b) => (b.acs.married || 0) - (a.acs.married || 0))[0]; inp.setAttribute('aria-invalid', String(!z)); if (z) selZip(z.zip, false); else toast('No ZIP or city in ' + title + ' matches'); }; }
  // ---- hand offs: the selected ZIP, else the filtered county's ZIPs, else the metro
  const scopeZips = () => ZI[st.sel] ? [st.sel] : /^c:/.test(st.sel || '') ? zipsOfC(st.sel.slice(2)).filter(id => ZI[id]) : st.cty ? scoped().map(z => z.zip) : [];
  const scopeCty = () => ZI[st.sel] ? [ZI[st.sel].county] : /^c:/.test(st.sel || '') ? [st.sel.slice(2)] : st.cty ? [st.cty] : MSA[st.code].counties.slice();
  R(`#mtDesk_${num}`).onclick = () => { const zs = scopeZips(); goModule('desk', Object.assign({ geo: 'msa:' + st.code }, zs.length ? { zips: zs } : {}, st.cty || /^c:/.test(st.sel || '') ? { counties: scopeCty() } : {})); };
  R(`#mtForge_${num}`).onclick = () => { const zs = scopeZips(); goModule('forge', Object.assign({ counties: scopeCty() }, zs.length ? { zips: zs } : {})); };
  R(`#mtWatch_${num}`).onclick = () => goModule('watch', st.cty ? { county: st.cty, from: modKey } : { metro: st.code, from: modKey });
  R(`#mtGround_${num}`).onclick = () => goModule('ground', ZI[st.sel] ? { zip: st.sel } : { metro: st.code });
  R(`#mtPaid_${num}`).onclick = () => goModule('paid', Object.assign({ metro: st.code }, ZI[st.sel] ? { zip: st.sel } : {}));
  if (atl) R(`#mtAtlas_${num}`).onclick = () => openAtlas(atl);
  // ---- tables and exports
  ctbl = table(R(`#mtCty_${num}`), { caption: title + ' counties', cols: ccols, rows: ctyRows(), sort: { k: 'div', dir: -1 }, onRow: id => selCounty(id, true) });
  tbl = table(R(`#mtTable_${num}`), { caption: title + ' ZIP codes', cols: viewCols(), rows: zipRows(), sort: { k: 'eff', dir: -1 }, onRow: id => selZip(id, true) });
  const note = extra => typeof csvNote === 'function' ? { note: csvNote(modKey, extra) } : undefined;
  R(`#mtZipCsv_${num}`).onclick = () => exportText(expName('metro_zips', title + (st.cty ? ' ' + cname(st.cty) : '')), csv(tbl.sorted(), xcols(cols.slice(0, 3).concat([{ k: 'fips', l: 'County FIPS' }, { k: 'metro', l: 'Metro' }], cols.slice(3))), note([`ZIP filings are allocations of each county's clerk count (grade C); margins of error are 90%.${st.cty ? ' Filtered to ' + cname(st.cty) + ' County.' : ''}`])));
  // the county table as a file: filings, rates, change, index and shock, offices, unemployment and the married margin
  R(`#mtCtyCsv_${num}`).onclick = () => exportText(expName('metro_counties', title), csv(ctbl.sorted(), [{ l: 'County', k: 'name' }, { l: 'FIPS', k: 'fips' }, { l: 'Confidence grade', k: 'grade' }, { l: 'Divorce filings, last 12 months', k: 'div', d: 0 }, { l: 'Divorce filings per 1,000 married', k: 'rate', d: 1 }, { l: 'Change vs prior 12 months (%)', k: 'yoy', d: 1 }, { l: 'SAPCR filings, last 12 months', k: 'sapcr', d: 0 }, { l: 'Protective orders, last 12 months', k: 'po', d: 0 }, { l: 'Modifications and enforcements, last 12 months', k: 'me', d: 0 }, { l: 'Dissolution Index', k: 'di', d: 0 }, { l: 'Economic Shock Index', k: 'esi', d: 0 }, { l: 'Law offices (CBP 2023)', k: 'offices', d: 0 }, { l: 'Private family filings per law office', k: 'fpo', d: 1 }, { l: 'Unemployment rate (%)', k: 'ur', d: 1 }, { l: 'Population 2025', k: 'pop', d: 0 }, { l: 'Married adults (ACS, spouse present)', k: 'married', d: 0 }, { l: 'Married adults, 90% margin of error', k: 'moe', d: 0 }, { l: 'Served by the firm', k: r => r.firm ? 'yes' : '' }, { l: 'Note', k: 'gap' }], note(['Filings are the clerks\' counts reported to the Office of Court Administration.'])));
  draw(); ledger(); rescope();
  // ---- the rest of the atlas: the firm, its accounts and its watch roster redraw what they feed
  BUS.on('firm', () => { if (!live()) return; decorate(); ctbl.setRows(ctyRows()); ledger(); });
  BUS.on('watch', () => { if (!live()) return; decorate(); ledger(); watchList(); });
  BUS.on('actuals', () => { if (!live()) return; refreshAcct(); layerSel(); tbl = table(R(`#mtTable_${num}`), { caption: title + ' ZIP codes', cols: viewCols(), rows: zipRows(), sort: tbl ? tbl.sort() : { k: 'eff', dir: -1 }, onRow: id => selZip(id, true) }); draw(); ledger(); });
  // goModule(<metro key>, {zip} | {county} | {arg: a ZIP, a FIPS code or a county name}) selects in place
  return { receive(p) { if (!p) return; const a = String(p.zip || p.county || p.arg || '').trim(); if (ZI[a] && codes.includes(ZI[a].msa)) { selZip(a, false); return; } const f = CI[a] ? a : /^\d{3}$/.test(a) ? '48' + a : (CTY.find(c => c.name.toLowerCase() === a.toLowerCase().replace(/\s+county$/, '')) || {}).fips; if (f && codes.some(c => MSA[c].counties.includes(f))) selCounty(f, false); } };
}
METRO_TABS.forEach(t => registerModule({ key: t.key, num: t.num, title: t.title, desc: ({ dfw: 'The 11 county metroplex at ZIP resolution: Collin, Dallas, Denton, Tarrant and the ring', hou: 'Harris, Fort Bend, Montgomery, Brazoria, Galveston and five more at ZIP resolution', sat: 'Bexar and its seven neighbors at ZIP resolution, with the military pool', aus: 'Travis, Williamson, Hays, Bastrop and Caldwell at ZIP resolution', elp: 'El Paso and Hudspeth at ZIP resolution, Fort Bliss included', rgv: 'McAllen and Brownsville, Hidalgo and Cameron counties at ZIP resolution' })[t.key], metro: true, mount(root) { this._mt = metroHTML(root, metroCodes(t), t.title, t.num); }, receive(p) { if (this._mt) this._mt.receive(p); } }));
registerModule({
  key: 'others', num: '19', title: 'Other Metros', desc: 'Corpus Christi, Killeen, Lubbock, Amarillo, Beaumont, Waco, Laredo, Tyler, Midland, Odessa and nine more, one at a time',
  metro: true,
  mount(root) {
    const st = { code: store.get('sev.other', OTHER_MSAS[0]) }; if (!MSA[st.code] || !OTHER_MSAS.includes(st.code)) st.code = OTHER_MSAS[0];
    const self = this;
    // the masthead first, as in every module; the metro picker sits in the toolbar
    function go(focus) { store.set('sev.other', st.code); hideTip(); try { if (/^#others\b/.test(location.hash || '')) history.replaceState(null, '', '#others/' + st.code); } catch (e) { } self._mt = metroHTML(root, [st.code], MNAME(MSA[st.code].title), '19', { group: 'Other Metros', picker: ctl('Metropolitan area', sel('otherSel', OTHER_MSAS.map(k => [k, MNAME(MSA[k].title) + ' · ' + N(MSA[k].pop2025) + ' people']), st.code)) }); const s = $('#otherSel', root); s.onchange = e => { st.code = e.target.value; go(true); }; if (focus) s.focus(); }
    go();
    // goModule('others', {code} | {metro} | {zip} | {county}) or the link #others/<MSA code, a city in its name, a ZIP or a county>
    this.receive = p => {
      if (!p) return; const q = String(p.code || p.metro || p.arg || '').trim().toLowerCase();
      const k = OTHER_MSAS.find(c => c === q) || OTHER_MSAS.find(c => MNAME(MSA[c].title).toLowerCase().split(' / ').some(n => n === q || n.replace(/\s+/g, '-') === q));
      if (k) { if (k !== st.code) { st.code = k; go(); } return; }
      const z = ZI[String(p.zip || p.arg || '').trim()]; const f = CI[p.county] ? p.county : z ? z.county : null; const m = z ? z.msa : f ? CI[f].msa : null;
      if (m && OTHER_MSAS.includes(m)) { if (m !== st.code) { st.code = m; go(); } if (self._mt) self._mt.receive(z ? { zip: z.zip } : { county: f }); }
    };
  }
});
