'use strict';
/* Metro tabs (12, 14 to 18) and Other Metros (19); the Metro Atlas is 13 */
function metroSummary(codes) {
  const cs = metroCounties(codes).map(f => CI[f]); const zs = metroZctas(codes);
  const tt = k => sum(cs.map(c => c.filings.ttm[k] || 0)), pv = k => sum(cs.map(c => c.filings.ttm_prev[k] || 0));
  const married = sum(cs.map(c => c.acs.married || 0)); const pop = sum(cs.map(c => c.pop2025));
  const y19 = sum(cs.map(c => (c.filings.hist['2019'] || {}).div || 0));
  const offices = sum(cs.map(c => c.rates.lawoffices || 0));
  const esi = sum(cs.map(c => (c.esi || 0) * c.pop2025)) / pop; const di = sum(cs.map(c => (c.di || 0) * c.pop2025)) / pop;
  const w13 = sum(cs.map(c => c.ui ? c.ui.w13 : 0)), w13_19 = sum(cs.map(c => c.ui && c.ui.w13_2019 ? c.ui.w13_2019 : 0)), w13y = sum(cs.map(c => c.ui && c.ui.w13_yago ? c.ui.w13_yago : 0));
  const lf = sum(cs.map(c => c.laus && c.laus.lf ? c.laus.lf : 0)), un = sum(cs.map(c => c.laus && c.laus.unemp ? c.laus.unemp : 0)), unY = sum(cs.map(c => c.laus && c.laus.unemp_yago ? c.laus.unemp_yago : 0));
  const warn12 = sum(cs.map(c => c.warn.last12.workers)); const exposed = sum(cs.map(c => c.econ.married_exposed || 0));
  // monthly series summed
  let series = null; const withS = cs.filter(c => c.filings.series); if (withS.length) { const t0 = Math.max(...withS.map(c => c.filings.series.t0)); const n = Math.min(...withS.map(c => c.filings.series.div.length)); series = { t0, div: [], sapcr: [], po: [], mod: [], enf: [], d_div: [], p_div: [] }; for (let i = 0; i < n; i++) ['div', 'sapcr', 'po', 'mod', 'enf', 'd_div', 'p_div'].forEach(k => series[k][i] = sum(withS.map(c => c.filings.series[k][i]))); }
  const sectors = {}; cs.forEach(c => (c.sectors || []).forEach(s => { if (!sectors[s.code]) sectors[s.code] = { name: s.name, emp: 0, chg: 0 }; sectors[s.code].emp += s.emp; sectors[s.code].chg += (s.chg || 0); }));
  const warn = []; cs.forEach(c => c.warn.recent.forEach(r => warn.push(Object.assign({ county: c.name }, r)))); warn.sort((a, b) => (b.n || 0) - (a.n || 0));
  return { cs, zs, married, pop, ttm: { div: tt('div'), div_k: tt('div_k'), sapcr: tt('sapcr'), po: tt('po'), mod: tt('mod'), enf: tt('enf'), priv: tt('priv'), ivd: tt('ivd'), cps: tt('cps'), adopt: tt('adopt'), d_div: tt('d_div') }, prev: { div: pv('div'), sapcr: pv('sapcr'), po: pv('po'), mod: pv('mod'), enf: pv('enf'), priv: pv('priv') }, y19, offices, esi, di, w13, w13_19, w13y, ur: lf ? un / lf * 100 : null, urY: lf ? unY / lf * 100 : null, warn12, exposed, series, sectors: Object.values(sectors), warn: warn.slice(0, 12), rate: married ? tt('div') / married * 1000 : null };
}
// every lookup is scoped to root, and num is unique per tab (Other Metros is 19), so two metro tabs never share an element
function metroHTML(root, codes, title, num, opt) {
  opt = opt || {}; const R = s => $(s, root);
  const S = metroSummary(codes); const st = { layer: 'eff', sel: null, code: codes[0] };
  const cs = S.cs.slice().sort((a, b) => (b.filings.ttm.div || 0) - (a.filings.ttm.div || 0));
  const lead = cs[0]; const fastest = cs.filter(c => c.filings.ttm.div >= 200).sort((a, b) => (b.rates.div_yoy || -99) - (a.rates.div_yoy || -99))[0];
  const hiZ = S.zs.filter(z => z.acs.married > 1500).sort((a, b) => (b.risk.haz_pred || 0) - (a.risk.haz_pred || 0)).slice(0, 5);
  const effZ = S.zs.filter(z => isN(z.paid.eff_pct)).sort((a, b) => b.paid.eff_pct - a.paid.eff_pct).slice(0, 8);
  const shockC = cs.slice().sort((a, b) => (b.esi || 0) - (a.esi || 0))[0];
  const shrink = S.sectors.filter(s => s.chg < 0).sort((a, b) => a.chg - b.chg).slice(0, 3);
  root.innerHTML = mastHTML({ eyebrow: `Module ${num} · ${opt.group ? opt.group + ' · ' : ''}${title} · ${codes.map(c => MNAME(MSA[c].title)).join(' and ')} metropolitan statistical area${codes.length > 1 ? 's' : ''} (OMB 2023)`, title, dek: `${S.cs.length} count${S.cs.length > 1 ? 'ies' : 'y'}, ${N(S.pop)} residents (Census Vintage 2025 estimates), ${N(S.married)} married adults (ACS 2020 to 2024, spouse present) and ${N(S.zs.length)} ZIP codes with data. Residents filed ${N(S.ttm.div)} divorces in the last twelve months (${sgn((S.ttm.div / (S.prev.div || 1) - 1) * 100)} on the prior twelve, ${sgn((S.ttm.div / (S.y19 || 1) - 1) * 100)} on 2019), ${N(S.ttm.sapcr)} custody suits, ${N(S.ttm.po)} protective order applications and ${N(S.ttm.mod + S.ttm.enf)} modifications and enforcements. The map resolves the metro to the ZIP code; the cards resolve it to the county.`, facts: [[N(S.rate, 1), 'divorce filings per 1,000 married (state ' + N(sum(CTY.map(c => c.filings.ttm.div || 0)) / ST.acs.married * 1000, 1) + ')'], [N(S.esi, 0), 'economic shock index, population weighted'], [P1(S.ur), 'unemployment, ' + fmtDate(META.laus_through) + (isN(S.urY) ? ' (' + sgn(S.ur - S.urY, 1, ' pts') + ' vs year earlier)' : '')], [N(S.offices), 'law offices']] }) + `
  <div class="toolbar"><span class="ttl">${esc(title)}</span><span class="sub">ZIP heatmap · county cards · monthly series · layoffs</span><span class="sp"></span><button class="btn" id="mtZipCsv_${num}">↓ ZIP CSV</button>${AT_BY_CODE[codes[0]] ? '<button class="btn" data-atlas="' + AT_BY_CODE[codes[0]] + '">Metro Atlas ↗</button>' : ''}<button class="btn" data-go="paid">Paid Acquisition ↗</button><button class="btn" data-go="desk">Campaign Desk ↗</button></div>
  <div class="callout"><div class="h">Read this first: ${esc(title)} in four sentences</div><p><b>Where the filings are.</b> ${esc(lead.name)} County carries ${N(lead.filings.ttm.div)} of the metro's ${N(S.ttm.div)} divorce filings (${P(lead.filings.ttm.div / S.ttm.div, 0)}) at ${N(lead.rates.div_per_1k_married, 1)} per 1,000 married${cs.length > 1 ? `; the highest rate is ${esc(cs.slice().sort((a, b) => (b.rates.div_per_1k_married || 0) - (a.rates.div_per_1k_married || 0))[0].name)} County at ${N(cs.slice().sort((a, b) => (b.rates.div_per_1k_married || 0) - (a.rates.div_per_1k_married || 0))[0].rates.div_per_1k_married, 1)}` : ''}. <b>Where they are growing.</b> ${fastest ? `${esc(fastest.name)} County is ${updown(fastest.rates.div_yoy)} on the prior twelve months` : 'No county with 200 or more filings grew'}${cs.length > 1 ? `; the metro as a whole is ${updown((S.ttm.div / (S.prev.div || 1) - 1) * 100)}` : ''}. <b>Where the married population is built to divorce.</b> The highest composition hazards among ZIPs with 1,500 or more married adults: ${hiZ.map(z => `${z.zip} ${esc(z.city)} (${N(z.risk.haz_pred, 1)})`).join(', ')}. <b>Where the economy is pushing.</b> ${esc(shockC.name)} County has the metro's highest shock index (${N(shockC.esi, 0)}); metro claims run ${N(S.w13 / (S.w13_19 || 1), 2)}× the same weeks of 2019 and ${N(S.w13 / (S.w13y || 1), 2)}× a year ago, ${N(S.warn12)} workers were on WARN notices in the last twelve months${shrink.length ? `, and payrolls shrank most in ${shrink.map(s => s.name.toLowerCase() + ' (' + sgn(s.chg, 0, '') + ')').join(', ')}` : ''}. ${N(S.exposed)} married adults here live with unemployment in the household.</p></div>
  <div class="tiles">${tile('Divorce filings', N(S.ttm.div), `${P(S.ttm.div_k / (S.ttm.div || 1), 0)} with children · ${N(S.ttm.d_div)} disposed`)}${tile('Custody, SAPCR', N(S.ttm.sapcr), sgn((S.ttm.sapcr / (S.prev.sapcr || 1) - 1) * 100) + ' vs prior 12 months')}${tile('Protective orders', N(S.ttm.po), sgn((S.ttm.po / (S.prev.po || 1) - 1) * 100) + ' vs prior 12 months')}${tile('Modification + enforcement', N(S.ttm.mod + S.ttm.enf), sgn(((S.ttm.mod + S.ttm.enf) / ((S.prev.mod + S.prev.enf) || 1) - 1) * 100) + ' vs prior 12 months')}${tile('Private filings per office', N(S.ttm.priv / (S.offices || 1), 1), N(S.ttm.priv) + ' private family filings, ' + N(S.offices) + ' offices')}${tile('Dissolution Index', N(S.di, 0), 'population weighted county average')}</div>
  <div class="panel" style="margin-bottom:14px"><h3>Counties</h3><div class="sub">Click a county card (or focus it and press Enter) to open it in module 01.</div><div class="linebox" id="mtCty_${num}">${cs.map(c => `<div class="line" data-f="${c.fips}" role="button" tabindex="0" data-kbd aria-label="${esc(c.name)} County: open in the Dissolution Index"><div class="t">${esc(c.name)} <span class="grade ${c.grade}">${c.grade}</span></div><div class="v">${N(c.filings.ttm.div)}</div><div class="s">divorce filings, 12 mo · ${N(c.rates.div_per_1k_married, 1)} per 1,000 married · ${sgn(c.rates.div_yoy)} vs prior · index ${N(c.di, 0)} · shock ${N(c.esi, 0)}<br>SAPCR ${N(c.filings.ttm.sapcr)} · PO ${N(c.filings.ttm.po)} · mod+enf ${N((c.filings.ttm.mod || 0) + (c.filings.ttm.enf || 0))} · ${N(c.rates.lawoffices)} offices · unemp ${P1(c.laus ? c.laus.ur : null)}</div></div>`).join('')}</div></div>
  <div class="panel" style="margin-bottom:14px"><div class="controls">${ctl('Map layer', sel('mtLayer_' + num, Object.keys(ZIP_LAYERS).map(k => [k, ZIP_LAYERS[k].l]), st.layer))}${codes.length > 1 ? ctl('Area', sel('mtCode_' + num, codes.map(c => [c, MNAME(MSA[c].title)]), codes[0])) : ''}</div><div class="split"><div class="mapwrap" id="mtMap_${num}"></div><div><h3 style="font-family:var(--display);font-size:20px">Selected ZIP</h3><div id="mtZip_${num}" class="small">Click a ZIP.</div><h3 style="font-family:var(--display);font-size:20px;margin-top:12px">Most efficient ZIPs</h3><table class="t"><thead><tr><th scope="col">ZIP</th><th scope="col" style="text-align:left">City</th><th scope="col">Eff</th><th scope="col">Div/yr</th></tr></thead><tbody>${effZ.map(z => `<tr><td class="name"><button type="button" class="linkbtn" data-z="${z.zip}">${z.zip}</button></td><td style="text-align:left">${esc(z.city)}</td><td>${N(z.paid.eff_pct, 0)}</td><td>${N(z.alloc.div, 0)}</td></tr>`).join('')}</tbody></table></div></div></div>
  <div class="grid2"><div class="panel"><h3>Filings by month</h3><div class="sub">Sum of the metro's counties, January 2019 to August 2026.</div><div class="chart" id="mtChart_${num}"></div></div><div class="panel"><h3>Layoffs and payrolls</h3><div class="sub">Largest WARN notices in the last 24 months, then private payroll change by sector, 2026 Q1 vs 2025 Q1.</div><div class="warnlist">${S.warn.map(r => `<div><span title="${esc(CO(r.co))}">${esc(CO(r.co))} · ${esc(r.city)} (${esc(r.county)})</span><span>${esc(fmtDate(r.notice))}</span><span class="num">${N(r.n)}</span></div>`).join('') || '<div class="small">No WARN notices in the last 24 months.</div>'}</div><div class="chart" id="mtSect_${num}" style="margin-top:8px"></div></div></div>
  <div class="panel"><h3>ZIP codes</h3><div class="sub">All ZIPs in the metro with data, sortable. Criterion is the Google Ads location ID.</div><div id="mtTable_${num}"></div></div>`;
  $$('[data-go]', root).forEach(b => b.onclick = () => showModule(b.dataset.go));
  $$('[data-atlas]', root).forEach(b => b.onclick = () => openAtlas(b.dataset.atlas));
  $$('.line', R(`#mtCty_${num}`)).forEach(d => d.onclick = () => { store.set('sev.county', d.dataset.f); const m = MODI.index; if (m.mounted) { m.mounted = false; } showModule('index'); });
  const mapEl = R(`#mtMap_${num}`);
  function zipBox() { const z = ZI[st.sel]; if (!z) return; const a = z.acs, r = z.risk; R(`#mtZip_${num}`).innerHTML = `<b>${esc(z.zip)} ${esc(z.city)}</b>, ${esc(z.county_name)} County · criterion ${esc(z.gt || NA)}<dl class="kv" style="margin-top:4px"><dt>Population / married</dt><dd>${N(a.pop)} / ${N(a.married)}</dd><dt>Expected divorce filings / yr</dt><dd>${N(z.alloc.div, 0)}</dd><dt>SAPCR / PO / mod+enf</dt><dd>${N(z.alloc.sapcr, 0)} / ${N(z.alloc.po, 0)} / ${N((z.alloc.mod || 0) + (z.alloc.enf || 0), 0)}</dd><dt>Hazard / separated per 1k</dt><dd>${N(r.haz_pred, 1)} / ${N(a.sep_per_1k_married, 0)}</dd><dt>Married with kids / cohabiting kids</dt><dd>${P(a.mc_kids_sh, 0)} / ${N(a.cohab_hh_kids)}</dd><dt>Remarried / married 5 to 9 yrs</dt><dd>${P(r.remarried, 0)} / ${P(r.dur_5_9, 0)}</dd><dt>Median income / over $150k</dt><dd>${$$$(a.med_hh_inc)} / ${P(a.inc_150k_sh, 0)}</dd><dt>Renters / rent burden</dt><dd>${P(a.renter_sh, 0)} / ${P(a.rent_burden35_sh, 0)}</dd><dt>Active duty / veterans</dt><dd>${P(r.mil_active, 1)} / ${P(a.vet_sh, 0)}</dd><dt>Law offices</dt><dd>${N(z.lawoffices)}</dd><dt>Efficiency / opportunity / index</dt><dd>${N(z.paid.eff_pct, 0)} / ${N(z.paid.opp_pct, 0)} / ${N(z.di, 0)}</dd></dl>`; }
  function draw() { drawZipMap(mapEl, [st.code], ZIP_LAYERS[st.layer], st, id => { st.sel = id; markSel(mapEl, id); zipBox(); }); }
  R(`#mtLayer_${num}`).onchange = e => { st.layer = e.target.value; draw(); };
  if (codes.length > 1) R(`#mtCode_${num}`).onchange = e => { st.code = e.target.value; st.sel = null; draw(); };
  $$('.linkbtn[data-z]', root).forEach(td => td.onclick = () => { const z = ZI[td.dataset.z]; if (z.msa !== st.code) { st.code = z.msa; if (codes.length > 1) R(`#mtCode_${num}`).value = st.code; draw(); } st.sel = td.dataset.z; markSel(mapEl, st.sel); zipBox(); });
  if (S.series) { const s = S.series; lineChart(R(`#mtChart_${num}`), { title: title + ' filings by month', series: [{ name: 'Divorce filed', color: 'var(--s1)', values: s.div.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'Protective orders', color: 'var(--s2)', values: s.po.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'SAPCR', color: 'var(--s3)', values: s.sapcr.map((v, i) => ({ x: s.t0 + i, y: v })) }, { name: 'Modification + enforcement', color: 'var(--s4)', values: s.mod.map((v, i) => ({ x: s.t0 + i, y: v + s.enf[i] })) }, { name: 'Divorce disposed', color: 'var(--s5)', values: s.d_div.map((v, i) => ({ x: s.t0 + i, y: v })) }], W: 640, H: 240, xfmt: tLabel, xTicks: [2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026].map(y => y * 12), xTickFmt: v => String(v / 12), yfmt: v => N(v) }); }
  if (S.sectors.length) barChart(R(`#mtSect_${num}`), { title: title + ' payroll change by sector', rows: S.sectors.slice().sort((a, b) => a.chg - b.chg).map(s => ({ label: s.name, value: s.chg, color: s.chg < 0 ? 'var(--rp-slate-5)' : 'var(--rp-leaf-5)' })), W: 560, lw: 200, fmt: v => sgn(v, 0, '') });
  const cols = [{ k: 'zip', l: 'ZIP', fmt: v => esc(v) }, { k: 'city', l: 'City', fmt: v => esc(v), cls: 'l' }, { k: 'county', l: 'County', fmt: v => esc(v), cls: 'l' }, { k: 'eff', l: 'Eff', fmt: v => N(v, 0), h: 'Efficiency percentile (filings per competing law office)', d: 0 }, { k: 'opp', l: 'Opp', fmt: v => N(v, 0), h: 'Opportunity percentile', d: 0 }, { k: 'di', l: 'Index', fmt: v => N(v, 0), h: 'ZIP Dissolution Index', d: 0 }, { k: 'div', l: 'Div/yr', fmt: v => N(v, 0), h: 'Expected divorce filings a year', d: 0 }, { k: 'sapcr', l: 'SAPCR', fmt: v => N(v, 0), h: 'Expected SAPCR filings a year', d: 0 }, { k: 'po', l: 'PO', fmt: v => N(v, 0), h: 'Expected protective orders a year', d: 0 }, { k: 'me', l: 'Mod+Enf', fmt: v => N(v, 0), h: 'Expected modifications and enforcements a year', d: 0 }, { k: 'haz', l: 'Hazard', fmt: v => N(v, 1), h: 'Composition hazard per 1,000 married (model)', d: 1 }, { k: 'sep', l: 'Sep/1k', fmt: v => N(v, 0), h: 'Separated per 1,000 married (ACS)', d: 0 }, { k: 'married', l: 'Married', fmt: v => N(v), h: 'Married adults (ACS)', d: 0 }, { k: 'kids', l: 'MC kids', fmt: v => P(v, 0), h: 'Married couple families with children (%)', d: 0, pct: true }, { k: 'inc', l: 'Income', fmt: v => $$$(v), h: 'Median household income ($)', d: 0 }, { k: 'offices', l: 'Offices', fmt: v => N(v), h: 'Law offices in the ZIP (ZBP 2023)', d: 0 }, { k: 'gt', l: 'Criterion', fmt: v => esc(v), h: 'Google Ads location ID' }];
  const rows = S.zs.map(z => ({ _id: z.zip, zip: z.zip, city: z.city, county: z.county_name, eff: z.paid.eff_pct, opp: z.paid.opp_pct, di: z.di, div: z.alloc.div, sapcr: z.alloc.sapcr, po: z.alloc.po, me: (z.alloc.mod || 0) + (z.alloc.enf || 0), haz: z.risk.haz_pred, sep: z.acs.sep_per_1k_married, married: z.acs.married, kids: z.acs.mc_kids_sh, inc: z.acs.med_hh_inc, offices: z.lawoffices, gt: z.gt, msa: z.msa }));
  const tbl = table(R(`#mtTable_${num}`), { caption: title + ' ZIP codes', cols, rows, sort: { k: 'eff', dir: -1 }, onRow: id => { const z = ZI[id]; if (z.msa !== st.code) { st.code = z.msa; if (codes.length > 1) R(`#mtCode_${num}`).value = st.code; draw(); } st.sel = id; markSel(mapEl, id); zipBox(); } });
  R(`#mtZipCsv_${num}`).onclick = () => exportText(expName('metro_zips', title), csv(tbl.sorted(), xcols(cols)));
  draw();
}
METRO_TABS.forEach(t => registerModule({ key: t.key, num: t.num, title: t.title, desc: ({ dfw: 'The 11 county metroplex at ZIP resolution: Collin, Dallas, Denton, Tarrant and the ring', hou: 'Harris, Fort Bend, Montgomery, Brazoria, Galveston and five more at ZIP resolution', sat: 'Bexar and its seven neighbors at ZIP resolution, with the military pool', aus: 'Travis, Williamson, Hays, Bastrop and Caldwell at ZIP resolution', elp: 'El Paso and Hudspeth at ZIP resolution, Fort Bliss included', rgv: 'McAllen and Brownsville, Hidalgo and Cameron counties at ZIP resolution' })[t.key], metro: true, mount(root) { metroHTML(root, metroCodes(t), t.title, t.num); } }));
registerModule({
  key: 'others', num: '19', title: 'Other Metros', desc: 'Corpus Christi, Killeen, Lubbock, Amarillo, Beaumont, Waco, Laredo, Tyler, Midland, Odessa and nine more, one at a time',
  metro: true,
  mount(root) {
    const st = { code: store.get('sev.other', OTHER_MSAS[0]) }; if (!MSA[st.code] || !OTHER_MSAS.includes(st.code)) st.code = OTHER_MSAS[0];
    root.innerHTML = `<div class="panel" style="margin:14px 0 0"><div class="controls">${ctl('Metropolitan area', sel('otherSel', OTHER_MSAS.map(k => [k, MNAME(MSA[k].title) + ' · ' + N(MSA[k].pop2025) + ' people']), st.code))}</div></div><div id="otherBody"></div>`;
    function go() { store.set('sev.other', st.code); hideTip(); metroHTML($('#otherBody', root), [st.code], MNAME(MSA[st.code].title), '19', { group: 'Other Metros' }); }
    $('#otherSel', root).onchange = e => { st.code = e.target.value; go(); };
    go();
  }
});
