'use strict';
/* Module 20: Method and Sources */
registerModule({
  key: 'method', num: '20', title: 'Method and Sources', desc: 'Every source with its date, every formula, the model tables, the judgment calls and the known limits',
  mount(root) {
    const OR = D.pums.coefs; const pr = D.panel;
    // terms in reading order (PUMS_TERMS, module 03): age, marriage duration, marriage count, education, sex, service, age at marriage; any
    // term not listed goes last in name order
    const orKey = k => { const i = PUMS_TERMS.findIndex(t => t[0] === k); return i < 0 ? PUMS_TERMS.length : i; };
    const orRows = Object.keys(OR).filter(k => k !== 'const').sort((a, b) => orKey(a) - orKey(b) || a.localeCompare(b)).map(k => ({ k, or: OR[k].or, p: OR[k].p, se: OR[k].se }));
    const label = k => (PUMS_TERMS.find(t => t[0] === k) || [k, k])[1];
    const panelRows = ['ldiv|claims_0_12', 'ldiv|claims_0_12|post2022', 'lpriv|claims_0_12', 'lmod|claims_0_12', 'lenf|claims_0_12', 'lpo|claims_0_12', 'lsapcr|claims_0_12', 'ldiv|ur_0_12'].filter(k => pr[k]);
    root.innerHTML = mastHTML({ eyebrow: 'Module 20 · Method and Sources', title: 'Method and Sources', dek: 'What was measured, what was modeled, and where each number came from. Compiled ' + fmtDateL(META.compiled) + '. Nothing in this suite comes from a paid API; every source is public and the pipeline can be rerun.', facts: [['9,348', 'clerk reports pulled from the Court Activity Database'], [N(D.pums.n), 'married Texans in the hazard fit'], ['51,000', 'county months of unemployment'], ['102,108', 'county weeks of unemployment claims']] }) + `
    <div class="grid2"><div class="panel"><h3>Sources</h3><ul class="srcs">
    <li><b>Court filings.</b> Texas Office of Court Administration, Court Activity Reporting and Directory System, district court family section plus the statutory county court family section for the ${Object.keys(ST.ccl_div_2025 || {}).length} counties whose county courts at law take family cases; new cases filed, disposed and pending by case type; monthly ${seriesSpan()} for the ${CTY.filter(c => c.filings.series).length} metropolitan counties and the state, annual for the other ${CTY.filter(c => !c.filings.series).length} counties. <a href="https://card.txcourts.gov/" target="_blank" rel="noopener">card.txcourts.gov</a>. The last two months are provisional. Months with no clerk report in a county that normally files 30 or more cases (${Object.values(ST.imputed || {}).reduce((a, b) => a + b.length, 0)} county months) are filled with the same month of the adjacent year.</li>
    <li><b>Marital status, family structure, income, housing, education, mobility, veterans, commuting.</b> American Community Survey 2020 to 2024 five year estimates, table based summary file, for the state, 254 counties, 26 metros and 1,992 ZIP code tabulation areas. <a href="https://www2.census.gov/programs-surveys/acs/summary_file/2024/table-based-SF/" target="_blank" rel="noopener">census.gov</a>.</li>
    <li><b>Divorce hazard, marriage duration, remarriage, age at marriage, couple employment and earnings.</b> ACS 2020 to 2024 Public Use Microdata Sample for Texas (1,101,835 person records aged 15 and over; 539,863 households). <a href="https://www2.census.gov/programs-surveys/acs/data/pums/2024/5-Year/" target="_blank" rel="noopener">census.gov PUMS</a>. PUMAs are mapped to counties by 2020 tract population and to ZCTAs by land area.</li>
    <li><b>Unemployment.</b> BLS Local Area Unemployment Statistics as published by Texas Workforce Commission LMI, all counties, monthly January 2010 to ${esc(fmtDateL(META.laus_through))}, not seasonally adjusted. <a href="https://texaslmi.com/LMIbyCategory/LAUS" target="_blank" rel="noopener">texaslmi.com</a>. October 2025 is missing for every county (no household survey during the federal shutdown).</li>
    <li><b>Unemployment insurance initial claims.</b> Texas Workforce Commission, weekly initial claims by county, weeks ending January 5, 2019 to ${esc(fmtDateL(META.ui_through))}. <a href="https://texaslmi.com/Home/PopularDownloads" target="_blank" rel="noopener">texaslmi.com popular downloads, UI claims by county</a>.</li>
    <li><b>Layoff notices.</b> Texas Workforce Commission WARN Act notices, 2019 to ${esc(fmtDateL(META.warn_through))}, via the Texas Open Data Portal. <a href="https://data.texas.gov/dataset/Worker-Adjustment-and-Retraining-Notification-WARN/8w53-c4f6" target="_blank" rel="noopener">data.texas.gov 8w53-c4f6</a>. The portal lags the TWC listing by weeks to months.</li>
    <li><b>Payroll jobs and wages.</b> BLS Quarterly Census of Employment and Wages, county totals 2019 Q1 to 2026 Q1 and private sector detail for metro counties, 2026 Q1. <a href="https://www.bls.gov/cew/" target="_blank" rel="noopener">bls.gov/cew</a>.</li>
    <li><b>Child protection.</b> DFPS Data Book on the Texas Open Data Portal: CPS 2.1 removals by county FY2016 to FY2025 and CPI 3.3 abuse and neglect investigation findings with the family violence indicator. <a href="https://data.texas.gov/" target="_blank" rel="noopener">data.texas.gov</a>.</li>
    <li><b>Law offices.</b> Census County Business Patterns and ZIP Business Patterns 2023, NAICS 541110 (offices of lawyers) and 5411. <a href="https://www.census.gov/programs-surveys/cbp.html" target="_blank" rel="noopener">census.gov/cbp</a>.</li>
    <li><b>Population.</b> Census Bureau Vintage 2025 county estimates. Metro definitions: OMB Bulletin 23-01 (July 2023).</li>
    <li><b>Marriage and divorce rates 1990 to 2023.</b> NCHS National Vital Statistics System, state tables (provisional). <a href="https://www.cdc.gov/nchs/nvss/marriage-divorce.htm" target="_blank" rel="noopener">cdc.gov/nchs</a>. Texas DSHS stopped publishing county marriage and divorce tables after the 2016 annual report.</li>
    <li><b>Geography.</b> Census cartographic boundary files, counties 2023 and ZCTAs 2020, simplified and projected in the page. Google Ads geotargets CSV of August 12, 2026 for criteria IDs.</li>
    <li><b>Advertising rules.</b> Supreme Court of Texas Misc. Docket No. 21-9061, Part VII of the Texas Disciplinary Rules of Professional Conduct, effective July 1, 2021. <a href="https://www.txcourts.gov/media/1452266/219061.pdf" target="_blank" rel="noopener">txcourts.gov</a>.</li>
    <li><b>Benchmarks and literature.</b> ${D.lit.map(l => `<a href="${esc(l.url)}" target="_blank" rel="noopener">${esc(l.cite.split('.')[0])}</a>`).join('; ')}.</li></ul></div>
    <div class="panel"><h3>Formulas</h3><div class="prose" style="font-size:13.5px">
    <p><b>County Dissolution Index.</b> Weighted sum of seven percentile ranks across the 254 counties: filing intensity ${Math.round(D.weights.filing * 100)}% (divorce filings per 1,000 married adults, shrunk toward the state rate with weight n/(n+60)), composition hazard ${Math.round(D.weights.haz * 100)}% (the PUMS model applied to the county's married population), separation ${Math.round(D.weights.sep * 100)}% (separated per 1,000 married, shrunk by the ACS coefficient of variation), economic shock ${Math.round(D.weights.econ * 100)}% (mean of six standardized measures: claims vs 2019, claims vs a year ago, unemployment change vs a year ago and vs 2019, WARN workers per 1,000 jobs, payroll change; each shrunk by county size), family structure ${Math.round(D.weights.struct * 100)}% (married with children, cohabiting with children, unmarried births, single parents, grandparents responsible, married 25 to 44), financial strain ${Math.round(D.weights.strain * 100)}% (rent and mortgage burden, SNAP, married with children in poverty, households under $35,000), supply gap ${Math.round(D.weights.supply * 100)}% (log private family filings per law office).</p>
    <p><b>ZIP index.</b> Same idea without the filing component, which does not exist below the county: composition hazard ${Math.round(D.zweights.haz * 100)}%, separation ${Math.round(D.zweights.sep * 100)}%, county economic shock ${Math.round(D.zweights.econ * 100)}%, structure ${Math.round(D.zweights.struct * 100)}%, strain ${Math.round(D.zweights.strain * 100)}%, supply ${Math.round(D.zweights.supply * 100)}% (log expected filings per law office plus one).</p>
    <p><b>ZIP filings.</b> County trailing twelve month filings of each type spread across the county's ZIPs in proportion to married adults times the ZIP's modeled hazard. ZIPs under 200 residents are left blank.</p>
    <p><b>Economic Shock Index.</b> Percentile rank of the economic component above. Expected filings lift applies the panel elasticities at 0, 3 and 12 months to the county's log change in claims against a year earlier.</p>
    <p><b>Service line estimates.</b> Nine lines are court counts. High asset scales divorce filings by the county share of married adults in households over $150,000 times 0.59, the relative hazard of that income band in the first (exploratory) fit; gray divorce by married adults 55 and over weighted by age specific hazards; military by active duty exposure times the 1.46 hazard ratio; premarital agreements assume 6% of new marriages retain counsel.</p>
    <p><b>Confidence grades.</b> A: 500 or more divorce filings, monthly series, married count CV under 5%. B: 100 or more filings and CV under 10%. C: 25 or more and CV under 20%. D: the rest.</p>
    <p><b>Seasonality.</b> Monthly index = mean of the month across 2022 to 2025 divided by the mean of all months, times 100.</p></div></div></div>
    <div class="grid2"><div class="panel"><h3>Hazard model</h3><div class="sub">Weighted logistic regression, outcome = divorced in the past 12 months among Texans married at any point in that year; ${N(D.pums.n)} records, ${N(D.pums.married_w)} weighted; robust standard errors; reference categories age 40 to 44, married 10 to 14 years, first marriage, high school, male, civilian, married at 23 or later. Pseudo R² 0.03, as expected for a rare annual event.</div><div class="tblbox"><div class="tblwrap" style="max-height:420px"><table class="t"><caption class="vh">Hazard model odds ratios</caption><thead><tr><th scope="col">Term</th><th scope="col">Odds ratio</th><th scope="col">SE (log)</th><th scope="col">p</th></tr></thead><tbody>${orRows.map(r => `<tr><td>${esc(label(r.k))}</td><td>${N(r.or, 2)}</td><td>${N(r.se, 3)}</td><td>${r.p < 0.001 ? '&lt;0.001' : N(r.p, 3)}</td></tr>`).join('')}</tbody></table></div></div><p class="small" style="margin-top:6px">Covariates that change with the divorce (household income, employment, tenure, children present, spouse characteristics, commute) were excluded after a first fit showed they absorbed the outcome (a "spouse unknown" dummy alone carried an odds ratio over 400). They are reported as exposures in module 04 instead.</p></div>
    <div class="panel"><h3>Panel model</h3><div class="sub">log(filings + 1) on log(initial claims per 1,000 labor force) at lags 0, 3, 6, 9 and 12 months with county, calendar month and year fixed effects and a 2020 closure dummy; 43 counties over 100,000 residents; OLS with standard errors clustered by county.</div><div class="tblbox"><div class="tblwrap"><table class="t"><caption class="vh">Panel model coefficients</caption><thead><tr><th scope="col">Outcome · sample</th><th scope="col">n</th><th scope="col">lag 0</th><th scope="col">lag 3</th><th scope="col">lag 6</th><th scope="col">lag 9</th><th scope="col">lag 12</th><th scope="col">Cumulative</th></tr></thead><tbody>${panelRows.map(k => { const r = pr[k]; const cs = r.coefs; const ks = Object.keys(cs); const lab = k.replace('ldiv', 'Divorce').replace('lpriv', 'Private family').replace('lmod', 'Modification').replace('lenf', 'Enforcement').replace('lpo', 'Protective orders').replace('lsapcr', 'SAPCR').replace('|claims_0_12', ' · claims').replace('|ur_0_12', ' · unemployment rate (pts)').replace('|post2022', ', 2022 on'); return `<tr><td>${esc(lab)}</td><td>${N(r.n)}</td>${ks.map(x => `<td>${(cs[x].coef >= 0 ? '+' : '') + MINUS(cs[x].coef.toFixed(3))}<br><span class="small">(${cs[x].se.toFixed(3)})</span></td>`).join('')}<td>${(r.cum >= 0 ? '+' : '') + MINUS(r.cum.toFixed(3))} (${r.cum_se.toFixed(3)})</td></tr>`; }).join('')}</tbody></table></div></div><p class="small" style="margin-top:6px">Coefficients are elasticities: a coefficient of 0.058 at lag 12 means a 10% rise in claims is followed by roughly 0.6% more divorce filings a year later. Statewide cross correlation of monthly claims and divorce filings (2020 excluded) peaks at lag 12 at r = ${N(pr.xcorr_state['12'], 2)}.</p></div></div>
    <div class="grid2"><div class="panel"><h3>Judgment calls</h3><div class="prose" style="font-size:13.5px"><ul>
    <li>Metros follow the 2023 OMB delineations, so Dallas Fort Worth is 11 counties (Hood and Somervell moved to the Granbury micropolitan area) and Houston includes San Jacinto.</li>
    <li>McAllen and Brownsville are shown together as the Rio Grande Valley tab with separate maps; they are separate metros in every table.</li>
    <li>The composition hazard uses only pre determined characteristics. That understates the true spread between counties (it ignores the economy) and is why the observed filing rate carries the largest weight.</li>
    <li>Counties without monthly court data use calendar 2025 as the trailing year; their year over year change compares 2025 with 2024.</li>
    <li>Race, ethnicity, religion, national origin and disability are excluded from every score and layer.</li>
    <li>Value per matter defaults ($4,500 to $35,000) are placeholders for a firm's own fee history; change them in modules 07 and 10.</li>
    <li>The Attorney General's Title IV-D reporting changed after 2019 and again in 2025; IV-D counts are floors and are excluded from "private family law" totals.</li></ul></div></div>
    <div class="panel"><h3>Known limits and how to refresh</h3><div class="prose" style="font-size:13.5px"><ul>
    <li>Filings for ${(() => { const m = String(META.oca_through).match(/^(\d{4})-(\d{2})/); if (!m) return 'the last two months'; const t = +m[1] * 12 + +m[2] - 1; return Math.floor((t - 1) / 12) === Math.floor(t / 12) ? MOL[(t - 1) % 12] + ' and ' + MOL[t % 12] + ' ' + m[1] : MOL[(t - 1) % 12] + ' ' + Math.floor((t - 1) / 12) + ' and ' + MOL[t % 12] + ' ' + m[1]; })()} will rise as late clerk reports arrive; rerun after the 90 day window.</li>
    <li>The WARN portal shows notices through ${esc(fmtDateL(META.warn_through))}; the TWC website lists newer ones that the portal has not loaded.</li>
    <li>ZIP filings are allocations, not counts; ZIP law office counts include every kind of law office.</li>
    <li>Small counties share PUMAs, so their composition is regional; their grade reflects it.</li>
    <li>Refresh order: Court Activity Database (monthly), TWC claims file (weekly), Texas LMI unemployment (monthly, third week), WARN portal (irregular), QCEW (quarterly, five month lag), ACS and PUMS (each December), Business Patterns (each spring).</li>
    <li>The statewide and metro modules run entirely from the data inside the page and make no network calls. Network calls happen only where the firm turns them on: the Live Desk sources (the Texas Open Data Portal and FRED), the ad account connectors in Accounts and the website platforms in Publish; credentials stay in this browser.</li></ul></div></div></div>
    <div class="panel"><h3>Metro Atlas (module 13)</h3><div class="prose" style="font-size:13.5px;max-width:none"><ul>
     <li><b>Geography.</b> 12,814 block groups in the six largest metro areas of Texas under the 2023 OMB delineations: Dallas Fort Worth Arlington (11 counties, 4,371 block groups), Houston Pasadena The Woodlands (10 counties, 4,173 block groups), San Antonio New Braunfels (8 counties, 1,473 block groups), Austin Round Rock San Marcos (5 counties, 1,297 block groups), El Paso (2 counties, 602 block groups), and McAllen Edinburg Mission with Brownsville Harlingen, mapped together as the Rio Grande Valley (2 counties, 898 block groups). Shapes come from the Census 2024 cartographic boundary file, projected to the NAD83 Texas State Plane zone that fits each metro (North Central for Dallas Fort Worth, South Central for Houston and San Antonio, Central for Austin and El Paso, South for the Rio Grande Valley) and simplified with shared borders kept intact. City limits and school districts come from the same 2024 series, ZIP outlines from the 2020 ZCTA file, highways and water from TIGER 2024.</li>
     <li><b>Survey data.</b> ACS 2020 to 2024 five year estimates at block group level (B01001, B01002, B01003, B08303, B11001, B11003, B11012, B12001, B15003, B19001, B19013, B21001, B22010, B23025, B25003, B25008, B25035, B25070, B25077, B25091) and at tract level where no block group table exists (B12002 marital status by age).</li>
     <li><b>Local divorce hazard.</b> Married adults by age in each block group are estimated from its own age structure and its tract's married share at each age, then scored with the age specific predicted hazard of its survey area (PUMA) from the statewide model. That figure is multiplied by an education factor and a veteran factor: the block group's mix against its survey area's mix under the model's odds ratios. The survey area carries what it knows about marriage duration and remarriage; the block group adds age, schooling and service.</li>
     <li><b>Allocation.</b> Expected divorce filings in a block group = the county's divorce filings in the twelve months through ${esc(fmtDateL(META.oca_through))} × (married adults × local hazard × household share) ÷ the same sum across the county. Divorces with children use married couples raising children; custody suits use single parents and cohabiting parents; modifications and enforcements use single parent families. Every county total matches the clerk count.</li>
     <li><b>Separated.</b> The survey's separated count is noisy at this size, so each block group rate is pulled toward its tract, and each tract toward its county, by empirical Bayes using the published margins of error. The raw survey figure appears beside it in the detail panel.</li>
     <li><b>Group quarters and small areas.</b> Block groups with a quarter or more of residents in dorms, jails, barracks or care homes (B25008 against B01003), fewer than 150 residents or fewer than 40 married adults are drawn gray and left out of every ranking.</li>
     <li><b>Indices.</b> Pipeline: 35% expected filings per married adult, 25% separated rate, 15% married couples raising children, 25% household strain (mortgage and rent burden, SNAP, unemployment). Case Value: 40% median household income, 30% share of households at $150,000 or more, 30% median home value. Market Fit: the slider weighted blend of Volume (expected filings within one mile), Case Value and competition (expected filings within three miles per law office within three miles, with ZIP Business Patterns 2023 law offices placed at each ZIP's center), weighted 45, 35 and 20 until the sliders move. Every index is a percentile across the scored block groups of its own metro, so a score ranks a block group against its neighbors, not against the state; McAllen and Brownsville are ranked together.</li>
     <li><b>Cities, districts and ZIP codes.</b> Cities and districts are built from block groups weighted by the share of each block group's area inside the boundary, so totals along the edges are approximate. A ZIP code adds up the block groups whose largest part lies in it. Area medians for income are interpolated from pooled income brackets; home values are owner weighted averages of block group medians.</li>
     <li><b>Points.</b> Courthouses are placed from their street addresses; layoff notices at the city each notice lists, over the 24 months through ${esc(fmtDateL(META.warn_through))}.</li></ul></div></div>
    <div class="panel"><h3>Glossary</h3><div class="prose" style="font-size:13.5px"><p><b>SAPCR</b> suit affecting the parent child relationship, the custody case with no divorce attached. <b>Conservatorship</b> the Texas term for custody; <b>possession and access</b> for visitation; <b>JMC</b> joint managing conservatorship, which does not mean equal time. <b>Title IV-D</b> child support cases run by the Attorney General under Title IV-D of the Social Security Act. <b>Protective order</b> the family violence remedy under Family Code chapter 85; a TRO is not one. <b>ESPO</b> the expanded standard possession order, the default within 50 miles since 2021. <b>Hazard</b> divorces per 1,000 married adults per year. <b>Elasticity</b> percent change in one thing per percent change in another. <b>PUMA</b> Public Use Microdata Area, the smallest geography in Census microdata, about 100,000 people. <b>ZCTA</b> ZIP Code Tabulation Area, the Census approximation of a postal ZIP. <b>WARN</b> the Worker Adjustment and Retraining Notification Act, which requires 60 days notice of large layoffs. <b>QCEW</b> the Quarterly Census of Employment and Wages, a count of every job covered by unemployment insurance.</p></div></div>`;
  }
});
