'use strict';
/* Module 23: Accounts. The firm's own ad accounts (Google Ads, Local Services Ads, YouTube, Meta, TikTok, Microsoft Advertising, LinkedIn),
   call tracking and intake exports, normalized by ACCT (src/07_accounts_core.js) into one set of rows; spend, leads, consults and retained
   matters by service line, source, hour, ZIP and county; the month paced against the Campaign Desk plan; and the observed cost per click,
   conversion rate and retained rate handed back to the desk. A port of the Thermal Atlas module 15. Ids carry the ac prefix. */
registerModule({
  key: 'accounts', num: '23', title: 'Accounts', desc: 'Connect the firm\'s ad accounts, import call tracking and intake exports, and let the actuals correct the Campaign Desk',
  mount(root) {
    const self = this;
    const st = { range: (ACCT.settings() || {}).range || 30, geo: 'zip', confirm: {} };
    const ENVN = { chrome: 'the Severance extension', firefox: 'the Severance add on for Firefox', viewer: 'the hosted viewer', file: 'a page opened from disk or the web' };
    const SRCN = { google: 'Google Ads', lsa: 'Local Services', youtube: 'YouTube', meta: 'Meta', facebook: 'Facebook Page', instagram: 'Instagram', gbp: 'Business Profile', tiktok: 'TikTok', microsoft: 'Microsoft', linkedin: 'LinkedIn', linkedinpage: 'LinkedIn Page', callrail: 'CallRail', ctm: 'CallTrackingMetrics', clio: 'Clio Grow', lawmatics: 'Lawmatics', other: 'Other', organic: 'Organic search', referral: 'Referral', direct: 'Direct or website', directory: 'Directories', yelp: 'Yelp', nextdoor: 'Nextdoor', unknown: 'Source not recorded' };
    const badge = s => `<span class="ac-src ac-s-${esc(String(s).replace(/[^a-z0-9]/gi, ''))}">${esc(SRCN[s] || s)}</span>`;
    const money = v => isN(v) ? $$$(v) : 'n/a';
    const money2 = v => isN(v) ? $$$(v, 2) : 'n/a';
    const hh = h => h === 0 ? '12 am' : h < 12 ? h + ' am' : h === 12 ? '12 pm' : (h - 12) + ' pm';
    const when = iso => { if (!iso) return 'n/a'; const d = new Date(iso); return isN(d.getTime()) ? ACCT.stamp(d.getTime()) : esc(iso); };
    const lname = k => ACCT.lineName(k || 'unmapped');
    const live = !!(typeof MODI !== 'undefined' && MODI.live);
    const tbl = (head, body, cls) => `<div class="tblwrap ac-tbl${cls ? ' ' + cls : ''}"><table class="t"><thead><tr>${head.map(h => `<th class="${h[1] || ''}">${esc(h[0])}</th>`).join('')}</tr></thead><tbody>${body}</tbody></table></div>`;

    root.innerHTML = mastHTML({ eyebrow: 'Module 23 · Accounts · Google Ads, Local Services Ads, YouTube, Meta, TikTok, Microsoft Advertising, LinkedIn, call tracking, intake', title: 'Accounts', dek: 'Every other module estimates. This one measures. Connect the firm\'s own ad accounts, or drop in the reports, call logs and intake exports they already produce, and the atlas reads what the campaigns actually did: spend, clicks, leads, calls, consults and retained matters by service line, by source, by hour of the day, by ZIP and county, and against the month\'s plan. Then, with one click, the observed cost per click, conversion rate and retained rate go back to the Campaign Desk in place of its assumptions.', facts: [['7', 'ad platforms connect'], ['11', 'report and export formats import'], ['13', 'service lines read from campaign, ad group and practice area names'], ['0', 'credentials shipped; the firm brings its own']] }) +
      toolbarHTML('Accounts', 'Connectors, actuals, corrections', [{ id: 'acSync', label: '↻ Sync connected', primary: true, title: 'Pull the selected range from every connected account' }, { id: 'acCsv', label: '↓ Actuals CSV' }, { id: 'acJson', label: '↓ Actuals JSON' }, { id: 'acTmpl', label: '↓ Import template' }, { id: 'acDesk', label: 'Campaign Desk ↗' }].concat(live ? [{ id: 'acLive', label: 'Live Desk ↗' }] : [])) +
      `<div id="acEnv"></div>` +
      callout('', 'Read this first', `<p><b>What it does.</b> Holds the firm's own connections to seven ad platforms and pulls their reports by day and by hour; imports the exports those platforms, CallRail, CallTrackingMetrics, Clio Grow and Lawmatics produce, or a plain sheet; turns all of it into one set of rows tagged with a service line, a ZIP and county where the source has one, and the channel an inquiry came from; and shows cost per lead and per retained matter by line and source, the hours that produce leads, where the money landed, and the month against the Campaign Desk plan. Apply hands the observed rates to the desk.</p><p><b>What it does not do.</b> It ships no developer credentials and changes no campaign, bid or budget: every scope it asks for is read only. Nothing leaves this browser except the calls to the provider APIs you configure. Intake and call exports carry prospective clients' names, emails and numbers; the importers read only the date, source, practice area, status, value and geography, and store nothing that identifies a person. Figures here are the firm's own actuals, not benchmarks, and a line with a thin sample keeps the desk's assumption.</p>`) +
      `<div class="tiles" id="acTiles"></div>` +
      panel('Connectors', 'Each card holds the developer credentials the firm creates in its own consoles, the account identifiers and the connection. Connect runs the provider\'s own sign in window; Paste a token takes a token generated elsewhere (a Meta system user token, a TikTok portal token, a Google OAuth Playground token) and works from a page opened from disk where the provider answers browser calls. Local Services Ads and YouTube use the Google sign in and only need their IDs.', `<div class="controls">${ctl('Sync range', segHTML('acRange', [[30, '30 days'], [90, '90 days']], st.range))}</div><div class="cards ac-cards" id="acConn"></div>`) +
      `<div class="grid2 ac-g">` +
      panel('Bring in a report', 'Google Ads (campaign, hour of day or user location report), Meta Ads Manager (with the time of day or region breakdown), TikTok Ads Manager, Microsoft Advertising, Local Services Ads leads, YouTube Studio, CallRail and CallTrackingMetrics call logs, Clio Grow and Lawmatics lead or matter exports, and a generic date, campaign, spend, leads and retained sheet for mailers, directories or anything else. The format is read from the columns; pick it when the columns are thin. Rows already held are skipped, so a report can be imported again safely.', `<div class="dropzone ac-drop" id="acDrop"><span>Drop CSV files here</span><button type="button" class="btn sm" id="acPick">Choose files</button></div><input type="file" id="acFile" accept=".csv,.tsv,.txt,text/csv" multiple hidden aria-label="CSV files to import">
        <div class="formgrid ac-fg"><div class="ctl"><label for="acFmt">Format</label><select id="acFmt"><option value="">Read it from the columns</option>${ACCT.IMPORTERS.map(i => `<option value="${esc(i.id)}">${esc(i.name)}</option>`).join('')}</select></div><div class="ctl"><label for="acLabel">Source label (optional)</label><input type="text" id="acLabel" placeholder="mailer, avvo, nextdoor" autocomplete="off"></div></div>
        <div class="ctl wide"><label for="acPaste">Or paste the CSV text</label><textarea id="acPaste" rows="5" spellcheck="false"></textarea></div>
        <div class="btnrow"><button type="button" class="btn primary" id="acImp">Import</button><button type="button" class="btn" id="acImpTmpl">Template CSV</button><button type="button" class="btn danger" id="acClearA">Clear all actuals</button><button type="button" class="btn danger" id="acClearT">Clear tokens</button></div>
        <div class="logbox" id="acImpLog" aria-live="polite">No imports yet.</div>`) +
      panel('Month to date against the plan', 'Paid spend this calendar month from every source held, the daily rate, where the month lands at that rate, and how that compares with the Campaign Desk budget.', `<div class="formgrid ac-fg"><div class="ctl"><label for="acPlan">Monthly plan $</label><input type="number" id="acPlan" min="0" step="500" placeholder="from the Campaign Desk"><span class="hint" id="acPlanHint"></span></div></div><div id="acPace"></div>`) +
      `</div>` +
      panel('Actuals against the Campaign Desk, by service line', 'What each line cost and returned in the selected range: spend, clicks, leads and calls, intake inquiries, retained matters, cost per lead and per retained matter, next to the cost per click, conversion rate and retained rate the desk assumes. Apply sends the observed rates and the realized fee that clear their thresholds to the desk and says exactly what changed; Revert takes them back to the desk\'s inputs from before the first Apply, however many times Apply ran.', `<div class="btnrow"><button type="button" class="btn primary" id="acApply">Apply actuals to the Campaign Desk</button><button type="button" class="btn" id="acRevert">Revert</button></div><div id="acLines"></div><p class="small" id="acAppliedN"></p><div class="small ac-changes" id="acChanges" role="status"></div>`) +
      panel('Cost per lead and per retained matter, by source', 'Ad platform spend and conversions by platform; tracked calls and intake inquiries by the channel their source names (Google Ads, organic search, referral, directory, website). Cost per lead divides the spend by the largest of the platform\'s conversions, its tracked calls and its intake records, so the same inquiry is not counted twice.', `<div id="acSrcT"></div>`) +
      `<div class="grid2 ac-g">` +
      panel('Hour of the day', 'Share of leads and of spend by hour from the hourly rows held: Google hour segments, Meta time of day, TikTok hourly reports, Microsoft hourly reports, LSA lead timestamps in the account time zone and call log start times. The dashed line is an even spread across the day.', `<label class="chk ac-obs"><input type="checkbox" id="acUseObs"> Let the Live Desk timing use the observed hours</label><div class="chart ac-hour" id="acHour"></div><div class="small" id="acHourN"></div>`) +
      panel('Where the money landed', 'Spend, leads and retained matters by ZIP or county from the Google geographic view, LSA message leads with a postal code, call logs and intake exports with a ZIP, county or city, and any sheet with a ZIP column, with the atlas\'s own read beside each. Meta reports region only; TikTok and Microsoft report nothing below the account.', `<div class="controls">${segHTML('acGeoSeg', [['zip', 'By ZIP'], ['county', 'By county']], st.geo)}</div><div id="acZip"></div>`) +
      `</div><div class="grid2 ac-g">` +
      panel('Lead and intake log', 'Local Services leads, tracked calls and intake records, newest first, with the line each one was matched to, its channel and its outcome. No names or numbers are kept.', `<div id="acLeads"></div>`) +
      panel('Social and profile', 'YouTube views, minutes watched, subscribers and top videos; Facebook Page reach and engagement; Instagram reach and followers; Business Profile calls, website clicks and direction requests; LinkedIn Page followers. Last 30 days against the 30 before.', `<div id="acSocial"></div>`) +
      `</div>` +
      panel('How the module is built', '', `<ol class="steps ac-meth" id="acMeth"></ol>`) +
      `<div class="grid2 ac-g">${panel('Judgment calls', '', '<dl class="ac-judg" id="acJudg"></dl>')}${panel('Source register', '', '<div id="acReg"></div>')}</div>`;

    /* ---------- environment ---------- */
    async function env() {
      const host = $('#acEnv', root); const E = ACCT.ENV; const r = ACCT.redirectUrl();
      if (E === 'viewer') { host.innerHTML = callout('judg', 'Inside the hosted viewer: imports only', 'The viewer blocks every call the page would make to Google, Meta, TikTok, Microsoft or LinkedIn, so Connect, Test and Sync are off here. Report, call log and intake imports work in full. Open Severance from disk to use pasted tokens, or install the extension (the zip that ships with this build) for sign in connections.'); return; }
      if (E === 'file') { host.innerHTML = callout('note', 'Opened from disk or the web: pasted tokens and imports', 'Sign in needs the Severance extension, because a page opened this way has no registered redirect address. Pasted tokens work here where the provider answers browser calls (Meta does, most Google APIs do); Microsoft, LinkedIn and TikTok refuse calls from a page and need the extension. When the browser blocks a call, the card says so. Everything typed below stays in this browser.'); return; }
      const granted = await ACCT.hostsGranted();
      if (!root.isConnected) return;
      host.innerHTML = callout('note', `Running as ${ENVN[E] || E}`, `<p>Sign in connections and API calls run from this page with the credentials below. <b>Redirect URL for every provider console:</b> <code class="ac-code">${esc(r || 'not available')}</code> <button type="button" class="btn sm" id="acCopyR"${r ? '' : ' disabled'}>Copy</button></p>${granted === false ? '<p>The browser has not granted access to the provider sites yet. <button type="button" class="btn sm" id="acHosts">Grant site access</button></p>' : ''}`);
      const cb = $('#acCopyR', root); if (cb) cb.onclick = () => copyText(r);
      const hb = $('#acHosts', root); if (hb) hb.onclick = async () => { const ok = await ACCT.requestHosts(); toast(ok ? 'Site access granted' : 'Site access not granted'); env(); };
    }
    /* ---------- tiles ---------- */
    function tiles() {
      const bl = ACCT.byLine(st.range); const spend = sum(bl.map(o => o.spend)), leads = sum(bl.map(o => o.leads + o.calls)), intake = sum(bl.map(o => o.intake)), retained = sum(bl.map(o => o.retained)); const best = sum(bl.map(o => o.leadsBest));
      const n = ACCT.rowsAll().length; const conn = ACCT.PORDER.filter(p => ACCT.status(p).state === 'connected');
      const fetched = Object.values(ACCT.S.actuals).map(a => a.fetched).filter(Boolean).sort().pop(); const um = bl.find(o => o.line === 'unmapped');
      const dp = ACCT.deskPlan(); const deskCpl = isN(dp.cpc) && isN(dp.cvr) && dp.cvr > 0 ? dp.cpc / (dp.cvr / 100) : null; const cpl = best && spend ? spend / best : null; const ap = ACCT.settings().applied;
      $('#acTiles', root).innerHTML =
        tile('Accounts connected', `${conn.length} of ${ACCT.PORDER.length}`, conn.length ? conn.map(p => esc(ACCT.PROVIDERS[p].name)).join(', ') : 'none yet; imports work without a connection') +
        tile('Rows of actuals', N(n), fetched ? 'last pull or import ' + when(fetched) : 'nothing pulled or imported yet') +
        tile(`Paid spend, ${st.range} days`, money(spend), bl.length ? `${bl.filter(o => o.line !== 'unmapped' && o.spend > 0).length} lines with spend · ${um && um.spend ? money(um.spend) + ' unmapped' : 'every campaign mapped'}` : 'connect an account or import a report') +
        tile(`Leads and calls, ${st.range} days`, N(Math.round(leads)), cpl ? `cost per lead ${money(cpl)}${intake ? ` · ${N(intake)} intake records` : ''}` : intake ? `${N(intake)} intake records` : 'platform conversions, LSA leads and tracked calls') +
        tile('Retained matters', N(retained), retained && spend ? `cost per retained matter ${money(spend / retained)}` : intake ? `${N(intake)} inquiries, none retained in the range` : 'import Clio Grow, Lawmatics or a sheet with a retained column') +
        tile('Against the desk', cpl && deskCpl ? sgn((cpl / deskCpl - 1) * 100, 0) : 'n/a', deskCpl ? `cost per lead against the ${money(deskCpl)} the desk implies (${money2(dp.cpc)} a click at ${N(dp.cvr, 1)}%)` : 'save a Campaign Desk plan to compare') +
        tile('Desk corrections', ap ? 'Applied' : 'Not applied', ap ? 'applied ' + when(ap.at) + (ap.count > 1 ? ', ' + N(ap.count) + ' times' : '') : 'the Campaign Desk runs on its own inputs');
    }
    /* ---------- connectors ---------- */
    const secretK = (k, o) => (o && o.secret) || /secret|token/i.test(k);
    function card(p) {
      const P = ACCT.PROVIDERS[p], C = ACCT.cfg(p); const shared = !!P.tokenOf; const parent = shared ? ACCT.PROVIDERS[P.tokenOf].name : ''; const E = ACCT.ENV; const noSign = E === 'viewer' || E === 'file'; const noNet = E === 'viewer';
      return `<div class="ccard ac-conn" data-p="${p}"><div class="ac-ch"><h4 class="ac-s-${p}">${esc(P.name)}</h4><span class="pill" id="acSt-${p}"></span><span class="small ac-ver" id="acV-${p}">API ${esc(ACCT.ver(p) || '')}</span></div><p class="small">${esc(P.long)}</p>
        <div class="formgrid ac-fg">${P.fields.map(([k, l, o]) => `<div class="ctl"><label for="acF-${p}-${k}">${esc(l)}</label><input type="${secretK(k, o) ? 'password' : 'text'}" id="acF-${p}-${k}" data-k="${k}" value="${esc(C[k] || '')}" autocomplete="off" spellcheck="false"></div>`).join('')}</div>
        <div class="btnrow"><button type="button" class="btn sm" data-a="save">Save</button><button type="button" class="btn sm primary" data-a="connect"${noSign ? ' disabled title="Sign in needs the Severance extension"' : ''}>${shared ? `Sign in on the ${esc(parent)} card` : 'Connect'}</button><button type="button" class="btn sm" data-a="test"${noNet ? ' disabled title="Calls are blocked in the hosted viewer"' : ''}>Test</button><button type="button" class="btn sm" data-a="pull"${noNet ? ' disabled title="Calls are blocked in the hosted viewer"' : ''}>Sync ${st.range} days</button>${shared ? '' : '<button type="button" class="btn sm danger" data-a="disconnect">Disconnect</button>'}</div>
        ${shared ? `<p class="small">Token: the ${esc(parent)} card holds it; disconnect there to drop both.</p>` : `<details class="ac-det"><summary>Paste a token instead</summary><div class="formgrid ac-fg"><div class="ctl wide"><label for="acT-${p}">Access token</label><input type="password" id="acT-${p}" autocomplete="off" spellcheck="false"></div><div class="ctl"><label for="acTH-${p}">Valid for (hours)</label><input type="number" id="acTH-${p}" value="${P.pasteHours || 1}" min="1"></div></div><div class="btnrow"><button type="button" class="btn sm" data-a="paste">Use this token</button></div></details>`}
        <details class="ac-det"><summary>What it covers and how to set it up</summary><p class="small">${esc(P.covers)}</p><ol class="steps">${P.setup.map(s => `<li>${esc(s)}</li>`).join('')}</ol><p class="small">${(P.scopes || []).length ? `Scopes${shared ? ' (granted through the ' + esc(parent) + ' sign in)' : ' requested'}: <code class="ac-code">${esc(P.scopes.join(' '))}</code>` : 'Scopes: set on the app in the provider portal, not in the sign in address.'}</p></details>
        <div class="logbox ac-log" id="acLog-${p}" hidden></div></div>`;
    }
    function conns() { $('#acConn', root).innerHTML = ACCT.PORDER.map(card).join(''); $$('#acConn .ac-conn', root).forEach(c => { const p = c.dataset.p; $$('button[data-a]', c).forEach(b => b.onclick = () => act(p, b.dataset.a, c, b)); }); connStatus(); }
    function connStatus() {
      ACCT.PORDER.forEach(p => {
        const s = ACCT.status(p); const pill = $(`#acSt-${p}`, root); if (pill) { pill.textContent = s.label; pill.className = 'pill ' + ({ connected: 'p-ok', configured: 'p-warn', expired: 'p-block' }[s.state] || ''); }
        const a = ACCT.S.actuals[p]; const c = $(`.ac-conn[data-p="${p}"] .btnrow`, root); if (c) c.title = a ? `Last sync ${when(a.fetched)} · ${a.rows.length} rows` : '';
        const v = $(`#acV-${p}`, root); if (v) v.textContent = 'API ' + (ACCT.ver(p) || '');
      });
    }
    const log = (p, msg, isErr) => { const h = $(`#acLog-${p}`, root); if (!h) return; h.hidden = false; h.classList.toggle('ac-err', !!isErr); h.textContent = `${new Date().toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit', second: '2-digit' })}  ${msg}`; };
    async function act(p, a, c, btn) {
      const P = ACCT.PROVIDERS[p]; const fields = () => { const o = {}; $$('input[data-k]', c).forEach(i => o[i.dataset.k] = i.value.trim()); return o; };
      if (btn) btn.disabled = true;
      try {
        if (a === 'save') { await ACCT.setCfg(p, fields()); log(p, 'Saved in this browser.'); toast(`${P.name} settings saved`); }
        if (a === 'connect') { await ACCT.setCfg(p, fields()); log(p, P.tokenOf ? `Opening the ${ACCT.PROVIDERS[P.tokenOf].name} sign in window` : 'Opening the sign in window'); const t = await ACCT.connect(p); log(p, `Connected${t && t.long ? ' with a 60 day token' : ''}${t && t.note ? ' (' + t.note + ')' : ''}. Test, then Sync.`); toast(`${P.name} connected`); }
        if (a === 'paste') { const t = $(`#acT-${p}`, c).value.trim(); if (!t) throw new Error('Paste a token first'); await ACCT.setCfg(p, fields()); await ACCT.pasteToken(p, t, +$(`#acTH-${p}`, c).value || P.pasteHours || 1); $(`#acT-${p}`, c).value = ''; log(p, 'Token stored. Test, then Sync.'); }
        if (a === 'test') { await ACCT.setCfg(p, fields()); log(p, 'Testing'); const r = await ACCT.test(p); log(p, r); register(); }
        if (a === 'pull') { log(p, `Pulling ${st.range} days`); const r = await ACCT.pull(p, st.range); log(p, `${r.rows.length} rows for ${fmtDate(r.range.since)} to ${fmtDate(r.range.until)}.${(r.notes || []).length ? ' Notes: ' + r.notes.join(' | ') : ''}`); toast(`${P.name}: ${r.rows.length} rows`); }
        if (a === 'disconnect') { await ACCT.disconnect(p); log(p, 'Token removed; settings kept.'); }
      } catch (e) { log(p, (e && e.message) || String(e), true); toast(`${P.name}: ${(e && e.message) || e}`); }
      finally { if (btn && root.isConnected) { const E = ACCT.ENV; btn.disabled = (a === 'connect' && (E === 'viewer' || E === 'file')) || ((a === 'test' || a === 'pull') && E === 'viewer'); } }
      connStatus();
    }
    /* ---------- imports ---------- */
    function impLog() { const im = (ACCT.S.imports || []).slice(-10).reverse(); $('#acImpLog', root).textContent = im.length ? im.map(x => `${when(x.at)}  ${(ACCT.IMPORTERS.find(i => i.id === x.importer) || { name: x.importer }).name}${x.src ? ' (' + x.src + ')' : ''}: ${x.n} rows${x.dup ? ', ' + x.dup + ' already held' : ''}`).join('\n') : 'No imports yet.'; }
    function doImport(text, name) { if (!text || !text.trim()) { toast('Nothing to import'); return; } const r = ACCT.importCSV(text, $('#acFmt', root).value || null, $('#acLabel', root).value.trim() || null); toast((name ? name + ': ' : '') + r.note); if (!r.rows.length) $('#acImpLog', root).textContent = (name ? name + ': ' : '') + r.note + '\n' + $('#acImpLog', root).textContent; }
    const files = async list => { for (const f of Array.from(list || [])) { try { doImport(await readText(f), f.name); } catch (e) { toast('Could not read ' + f.name); } } };
    const drop = $('#acDrop', root);
    $('#acPick', root).onclick = () => $('#acFile', root).click();
    $('#acFile', root).onchange = async e => { await files(e.target.files); e.target.value = ''; };
    drop.ondragover = e => { e.preventDefault(); drop.classList.add('over'); }; drop.ondragleave = () => drop.classList.remove('over');
    drop.ondrop = async e => { e.preventDefault(); drop.classList.remove('over'); await files(e.dataTransfer && e.dataTransfer.files); };
    $('#acImp', root).onclick = () => { doImport($('#acPaste', root).value); $('#acPaste', root).value = ''; };
    $('#acImpTmpl', root).onclick = () => saveFile('severance-import-template.csv', ACCT.templateCSV());
    const twoStep = (id, label, fn) => { const b = $('#' + id, root); b.onclick = async () => { if (st.confirm[id]) { st.confirm[id] = false; b.textContent = label; await fn(); } else { st.confirm[id] = true; b.textContent = 'Click again to confirm'; setTimeout(() => { st.confirm[id] = false; if (b.isConnected) b.textContent = label; }, 4000); } }; };
    twoStep('acClearA', 'Clear all actuals', async () => { await ACCT.clearAll('actuals'); toast('Actuals, imports and desk corrections cleared'); renderData(); });
    twoStep('acClearT', 'Clear tokens', async () => { await ACCT.clearAll('tokens'); toast('Tokens cleared; settings kept'); connStatus(); tiles(); });
    /* ---------- pacing ---------- */
    function pace() {
      const dp = ACCT.deskPlan(); const own = ACCT.settings().plan; const plan = ACCT.planBudget(); const inp = $('#acPlan', root);
      if (document.activeElement !== inp) inp.value = isN(+own) && +own > 0 ? own : '';
      $('#acPlanHint', root).textContent = isN(+own) && +own > 0 ? `typed here${dp.budget ? '; the desk says ' + money(dp.budget) : ''}; clear it to follow the desk` : dp.budget ? `${money(dp.budget)} from ${dp.from}` : 'no Campaign Desk plan saved in this browser yet; type the month\'s budget';
      const p = ACCT.pacing(); const host = $('#acPace', root);
      if (!p.days) { host.innerHTML = `<p class="small">No paid rows for this month yet. ${plan ? `The plan is ${money(plan)} a month; once` : 'Once'} an account is synced or a report imported, this shows spend to date, the daily rate and where the month lands.</p>`; return; }
      const pc = p.onPace; const cls = pc == null ? '' : pc > 1.15 ? 'ac-hi' : pc < 0.85 ? 'ac-lo' : 'ac-ok';
      const lp = p.linePlan || {}; const lineRows = Object.entries(p.byLine).sort((a, b) => b[1] - a[1]);
      host.innerHTML = `<div class="ac-q"><div class="ac-qb"><div class="ac-qt">Spent this month</div><div class="ac-qv">${money(p.spend)}</div><div class="small">through day ${p.day} of ${p.dim} · ${p.days} day${p.days === 1 ? '' : 's'} with rows</div></div><div class="ac-qb"><div class="ac-qt">Daily rate</div><div class="ac-qv">${money(p.rate)}</div><div class="small">${plan ? 'plan ' + money(plan / p.dim) + ' a day' : 'no plan set'}</div></div><div class="ac-qb"><div class="ac-qt">Lands at</div><div class="ac-qv">${money(p.projected)}</div><div class="small">${plan ? 'plan ' + money(plan) + ' · ' + sgn((p.projected / plan - 1) * 100, 0) : 'no plan set'}</div></div><div class="ac-qb"><div class="ac-qt">Pace</div><div class="ac-qv ${cls}">${pc != null ? N(pc * 100, 0) + '%' : 'n/a'}</div><div class="small">${pc == null ? 'set a plan to pace against' : pc > 1.15 ? 'ahead of plan: trim the weakest line or the late hours' : pc < 0.85 ? 'behind plan: budgets are capping or the auction is thin' : 'on plan'}</div></div></div>
        <div class="grid2 ac-g2">${tbl([['Platform', 'l'], ['Spend'], ['Share']], Object.entries(p.bySrc).sort((a, b) => b[1] - a[1]).map(([s, v]) => `<tr><td class="l">${badge(s)}</td><td>${money(v)}</td><td>${P(v / (p.spend || 1), 0)}</td></tr>`).join(''))}${tbl([['Line', 'l'], ['Spend'], ['Desk plan'], ['Pace']], lineRows.map(([k, v]) => { const pl = lp[k]; const pcl = pl ? v / (pl * p.day / p.dim) : null; return `<tr><td class="l">${esc(lname(k))}</td><td>${money(v)}</td><td>${pl ? money(pl) : 'n/a'}</td><td>${pcl != null ? N(pcl * 100, 0) + '%' : 'n/a'}</td></tr>`; }).join(''))}</div>`;
    }
    $('#acPlan', root).onchange = e => { const v = +e.target.value; ACCT.setSettings({ plan: isN(v) && v > 0 ? v : null }); };
    /* ---------- lines ---------- */
    function lines() {
      const bl = ACCT.byLine(st.range); const host = $('#acLines', root); const dp = ACCT.deskPlan();
      if (!bl.length) { host.innerHTML = '<p class="small">No rows in the range. Sync an account or import a report, call log or intake export; the table fills by service line.</p>'; $('#acAppliedN', root).textContent = ''; return; }
      const dev = (a, m, lowGood) => (isN(a) && isN(m) && m) ? ` <span class="ac-dev ${(a > m * 1.15) === !!lowGood ? 'dn' : (a < m * 0.85) === !!lowGood ? 'up' : ''}">${sgn((a / m - 1) * 100, 0)}</span>` : '';
      host.innerHTML = tbl([['Line', 'l'], ['Spend'], ['Clicks'], ['Leads and calls'], ['Intake'], ['Retained'], ['Cost per lead'], ['Cost per retained'], ['CPC'], ['Desk CPC'], ['Conversion'], ['Desk conversion'], ['Retained rate'], ['Desk retained'], ['Value retained'], ['Platforms', 'l']], bl.map(o => `<tr><td class="l"><b>${esc(lname(o.line))}</b></td><td>${money(o.spend)}</td><td>${N(o.clicks)}</td><td>${N(Math.round(o.leads + o.calls))}</td><td>${N(o.intake)}</td><td>${N(o.retained)}</td><td>${money(o.cpl)}</td><td>${money(o.cpr)}</td><td>${money2(o.cpc)}${dev(o.cpc, dp.cpc, false)}</td><td>${money2(dp.cpc)}</td><td>${P1(o.cvr, 1)}${dev(o.cvr, dp.cvr, true)}</td><td>${P1(dp.cvr, 1)}</td><td>${P1(o.retainRate, 1)}${dev(o.retainRate, dp.retain, true)}</td><td>${P1(dp.retain, 1)}</td><td>${o.value ? money(o.value) : 'n/a'}</td><td class="l ac-plats">${Object.entries(o.byPlat).sort((a, b) => b[1].spend - a[1].spend || b[1].intake - a[1].intake).map(([s, v]) => `${badge(s)} <span class="small">${v.spend ? money(v.spend) : ''}${(v.leads + v.calls) ? ' ' + N(Math.round(v.leads + v.calls)) + ' leads' : ''}${v.intake ? ' ' + N(v.intake) + ' intake' : ''}${v.retained ? ' ' + N(v.retained) + ' retained' : ''}</span>`).join(' ')}</td></tr>`).join('')) + '<p class="small">Unmapped rows carry no line token, line name or practice area keyword; rename the campaign in the platform, or import with a practice area column, and the line follows. Desk columns are the Campaign Desk inputs saved in this browser; a deviation in green is better than the desk assumed, in red worse.</p>';
      const ap = ACCT.settings().applied; const M = ACCT.MIN;
      const fv = (k, x) => k === 'cpc' ? 'CPC ' + money2(x) : k === 'cvr' ? 'conversion ' + P1(x, 1) : k === 'retain' ? 'retained ' + P1(x, 1) : 'realized fee ' + money(x);
      $('#acAppliedN', root).innerHTML = ap ? `Applied ${when(ap.at)}${ap.count > 1 ? ` (${N(ap.count)} Applies since ${when(ap.first)}; Revert returns the desk to its inputs from before the first)` : ''}, from ${fmtDate(ap.since)} to ${fmtDate(ap.until)}: ${ACCT.FIELDS.filter(k => ap.patch[k] != null).map(k => `all lines ${fv(k, ap.patch[k])}`).join(', ') || 'no overall rate cleared its threshold'}${Object.keys(ap.patch.lines).length ? '; ' + Object.entries(ap.patch.lines).map(([l, v]) => `${esc(lname(l))}: ${ACCT.FIELDS.filter(k => v[k] != null).map(k => fv(k, v[k])).join(', ')}`).join('; ') : ''}.` : `Apply needs ${M.clicks} Google or Microsoft search clicks on a line for its CPC, ${M.clicks} clicks and ${M.leads} leads for its conversion rate, ${M.intake} intake inquiries with an outcome and ${M.retained} of them retained for its retained rate (open inquiries younger than ${M.youngDays} days wait), and ${M.fees} retained matters with a value for its realized fee. Below that the desk keeps its own figure.`;
    }
    /* ---------- by source ---------- */
    function sources() {
      const rows = ACCT.bySource(st.range); const host = $('#acSrcT', root);
      if (!rows.length) { host.innerHTML = '<p class="small">No rows in the range. Platform pulls and imports fill the spend side; call logs and intake exports fill the inquiry and retained side.</p>'; return; }
      host.innerHTML = tbl([['Source', 'l'], ['Spend'], ['Clicks'], ['Platform leads and calls'], ['Tracked calls'], ['Intake'], ['Consults'], ['Retained'], ['Cost per lead'], ['Cost per retained'], ['Value retained'], ['Value per $1']], rows.map(o => `<tr><td class="l">${badge(o.src)}</td><td>${o.spend ? money(o.spend) : 'n/a'}</td><td>${N(o.clicks)}</td><td>${N(Math.round(o.leads + o.calls))}</td><td>${N(o.tracked)}</td><td>${N(o.intake)}</td><td>${N(o.consults)}</td><td>${N(o.retained)}</td><td>${money(o.cpl)}</td><td>${money(o.cpr)}</td><td>${o.value ? money(o.value) : 'n/a'}</td><td>${o.spend && o.value ? $$$(o.roas, 2) : 'n/a'}</td></tr>`).join(''));
    }
    /* ---------- hours ---------- */
    function hours() {
      const H = ACCT.byHour(st.range); const has = H.some(x => x.n); const host = $('#acHour', root); const cb = $('#acUseObs', root); cb.checked = !!ACCT.settings().useObserved; cb.disabled = !has;
      if (!has) { host.innerHTML = '<p class="small ac-empty">No hourly rows yet. Google Ads and YouTube syncs bring hour segments, Meta brings the time of day breakdown, TikTok and Microsoft bring hourly reports, LSA leads and call logs carry timestamps; a Google Ads hour of day report import works too.</p>'; $('#acHourN', root).textContent = ''; return; }
      const W = 720, Ht = 236, m = { l: 40, r: 8, t: 12, b: 26 }; const iw = W - m.l - m.r, ih = Ht - m.t - m.b; const even = 100 / 24; const mx = Math.max(even * 1.5, ...H.map(x => Math.max(x.leadSh, x.spendSh))) * 1.05; const Y = v => m.t + ih - v / mx * ih; const bw = iw / 24;
      const svg = [`<svg viewBox="0 0 ${W} ${Ht}" role="img" aria-label="Share of leads and spend by hour of the day">`];
      niceTicks(0, mx, 4).forEach(v => svg.push(`<line class="gridl" x1="${m.l}" x2="${W - m.r}" y1="${Y(v).toFixed(1)}" y2="${Y(v).toFixed(1)}"></line><text class="ax" x="${m.l - 6}" y="${(Y(v) + 3).toFixed(1)}" text-anchor="end">${N(v, 0)}%</text>`));
      H.forEach(x => { const x0 = m.l + x.h * bw; svg.push(`<rect class="ac-bl" x="${(x0 + bw * 0.12).toFixed(1)}" y="${Y(x.leadSh).toFixed(1)}" width="${(bw * 0.36).toFixed(1)}" height="${Math.max(0, ih + m.t - Y(x.leadSh)).toFixed(1)}"></rect><rect class="ac-bs" x="${(x0 + bw * 0.5).toFixed(1)}" y="${Y(x.spendSh).toFixed(1)}" width="${(bw * 0.36).toFixed(1)}" height="${Math.max(0, ih + m.t - Y(x.spendSh)).toFixed(1)}"></rect>`); if (x.h % 3 === 0) svg.push(`<text class="ax" x="${(x0 + bw / 2).toFixed(1)}" y="${Ht - 8}" text-anchor="middle">${hh(x.h)}</text>`); });
      svg.push(`<line class="ac-even" x1="${m.l}" x2="${W - m.r}" y1="${Y(even).toFixed(1)}" y2="${Y(even).toFixed(1)}"></line><line class="gridl" x1="${m.l}" x2="${W - m.r}" y1="${m.t + ih}" y2="${m.t + ih}" style="stroke:var(--line-strong)"></line>`);
      H.forEach(x => svg.push(`<rect class="ac-hit" data-h="${x.h}" x="${(m.l + x.h * bw).toFixed(1)}" y="${m.t}" width="${bw.toFixed(1)}" height="${ih}"></rect>`)); svg.push('</svg>');
      host.innerHTML = svg.join('') + `<div class="legendc"><span><i class="ac-li-l"></i>Lead share</span><span><i class="ac-li-s"></i>Spend share</span><span><i class="ac-li-e"></i>Even spread (${N(even, 1)}% an hour)</span></div>`;
      const s = host.querySelector('svg'); s.onmousemove = e => { const r = e.target.closest('rect.ac-hit'); if (!r) { hideTip(); return; } const x = H[+r.dataset.h]; showTip(`<b>${hh(x.h)} to ${hh((x.h + 1) % 24)}</b><div class="row"><span>Lead share</span><span>${P1(x.leadSh, 1)}</span></div><div class="row"><span>Spend share</span><span>${P1(x.spendSh, 1)}</span></div><div class="row"><span>Leads and calls</span><span>${N(Math.round(x.leads + x.calls))}</span></div><div class="row"><span>Cost per lead</span><span>${money(x.cpl)}</span></div>`, e.clientX, e.clientY); }; s.onmouseleave = hideTip;
      const peak = H.slice().sort((a, b) => b.leadSh - a.leadSh).slice(0, 3).filter(x => x.leadSh > 0);
      $('#acHourN', root).textContent = `${N(sum(H.map(x => x.n)))} hourly rows in the range. Lead share peaks at ${peak.map(x => hh(x.h)).join(', ') || 'n/a'}. ${ACCT.settings().useObserved ? 'The Live Desk is offered these hours as its bid grid.' : 'Tick the box and the Live Desk is offered these hours in place of its default timing.'}`;
    }
    /* ---------- geography ---------- */
    function geo() {
      const host = $('#acZip', root);
      if (st.geo === 'county') {
        const rows = ACCT.byCounty(90); if (!rows.length) { host.innerHTML = '<p class="small">No county rows yet. A ZIP, a county name or a Texas city on a row places it in a county.</p>'; return; }
        host.innerHTML = tbl([['County', 'l'], ['Spend'], ['Clicks'], ['Leads'], ['Intake'], ['Retained'], ['Cost per lead'], ['Cost per retained'], ['ZIPs'], ['Atlas read', 'l']], rows.slice(0, 60).map(r => `<tr><td class="l"><b>${esc(r.cname)}</b></td><td>${money(r.spend)}</td><td>${N(r.clicks)}</td><td>${N(Math.round(r.leads))}</td><td>${N(r.intake)}</td><td>${N(r.retained)}</td><td>${money(r.cpl)}</td><td>${money(r.cpr)}</td><td>${N(r.zips)}</td><td class="l small">${r.c ? `Dissolution Index ${N(r.c.di, 0)} · grade ${esc(r.c.grade || 'n/a')} · ${N(((r.c.filings || {}).ttm || {}).div)} divorce filings a year` : 'outside the index'}</td></tr>`).join('')) + (rows.length > 60 ? `<p class="small">${rows.length - 60} more counties in the CSV export.</p>` : ''); return;
      }
      const rows = ACCT.byZip(90); if (!rows.length) { host.innerHTML = '<p class="small">No ZIP rows yet. The Google sync pulls the geographic view (spend by matched postal code), LSA message leads carry the client\'s postal code, and call logs, intake exports and sheets with a ZIP column land here as well.</p>'; return; }
      host.innerHTML = tbl([['ZIP', 'l'], ['City', 'l'], ['County', 'l'], ['Spend'], ['Clicks'], ['Leads'], ['Intake'], ['Retained'], ['Cost per lead'], ['Atlas read', 'l']], rows.slice(0, 60).map(r => `<tr><td class="l"><b>${esc(r.zip)}</b></td><td class="l">${esc(r.z ? r.z.city : '')}</td><td class="l">${esc(r.cname || (r.z ? r.z.county_name : ''))}</td><td>${money(r.spend)}</td><td>${N(r.clicks)}</td><td>${N(Math.round(r.leads))}</td><td>${N(r.intake)}</td><td>${N(r.retained)}</td><td>${money(r.cpl)}</td><td class="l small">${r.z ? `Dissolution Index ${N(r.z.di, 0)}${r.z.paid && isN(r.z.paid.eff_pct) ? ' · paid efficiency ' + N(r.z.paid.eff_pct, 0) : ''}${r.z.alloc && isN(r.z.alloc.div) ? ' · ' + N(r.z.alloc.div, 0) + ' divorces a year' : ''}` : 'outside the metro ZIP index'}</td></tr>`).join('')) + (rows.length > 60 ? `<p class="small">${rows.length - 60} more ZIPs in the CSV export.</p>` : '');
    }
    /* ---------- social ---------- */
    function social() {
      const so = ACCT.social(60); const host = $('#acSocial', root); const keys = Object.keys(so);
      if (!keys.length) { host.innerHTML = '<p class="small">No social or profile rows yet. The YouTube sync brings the channel and its top videos, the Google sync brings the Business Profile when its ID is set, the Meta sync brings Page and Instagram insights, and a YouTube Studio export imports.</p>'; return; }
      const cut = (() => { const d = new Date(); d.setDate(d.getDate() - 30); return d.toISOString().slice(0, 10); })();
      const LBL = { page_impressions_unique: 'Page reach', page_post_engagements: 'Post engagements', page_fans: 'Page likes', reach: 'Reach', follower_count: 'New followers', views: 'Views', estimatedMinutesWatched: 'Minutes watched', subscribersGained: 'Subscribers gained', likes: 'Likes', comments: 'Comments', shares: 'Shares', subscriberCount: 'Subscribers (channel total)', viewCount: 'Views (channel total)', videoCount: 'Videos on the channel', CALL_CLICKS: 'Calls from the profile', WEBSITE_CLICKS: 'Website clicks', BUSINESS_DIRECTION_REQUESTS: 'Direction requests', BUSINESS_IMPRESSIONS_MOBILE_MAPS: 'Maps impressions (mobile)', BUSINESS_IMPRESSIONS_MOBILE_SEARCH: 'Search impressions (mobile)', followers: 'Followers' };
      const rows = []; keys.forEach(src => { const by = {}; so[src].forEach(r => { const k = r.campaign; const o = by[k] = by[k] || { src, k, a: 0, b: 0, video: !!r.adset }; const v = r.imp || r.conv || r.msgs || r.calls || r.clicks || 0; if (r.date >= cut) o.a += v; else o.b += v; }); Object.values(by).forEach(o => rows.push(o)); });
      host.innerHTML = tbl([['Source', 'l'], ['Metric', 'l'], ['Last 30 days'], ['Prior 30'], ['Change']], rows.slice(0, 80).map(o => `<tr><td class="l">${badge(o.src)}</td><td class="l ac-wrap">${o.video ? 'Video views: ' : ''}${esc(LBL[o.k] || o.k)}</td><td>${N(Math.round(o.a))}</td><td>${N(Math.round(o.b))}</td><td>${o.b ? sgn((o.a / o.b - 1) * 100, 0) : 'n/a'}</td></tr>`).join(''), 'ac-short');
    }
    /* ---------- leads ---------- */
    function leads() {
      const k = r => r.date + String(r.hour == null ? 0 : r.hour).padStart(2, '0'); const rows = ACCT.rowsAll(['lead', 'intake']).sort((a, b) => k(b).localeCompare(k(a))).slice(0, 60); const host = $('#acLeads', root);
      if (!rows.length) { host.innerHTML = '<p class="small">No lead or intake rows yet. The Local Services Ads sync pulls the detailed lead report; call logs, LSA lead exports and Clio Grow or Lawmatics exports import from the panel above.</p>'; return; }
      const STG = { retained: 'Retained', consult: 'Consult', lost: 'Not retained', open: 'Open' };
      host.innerHTML = tbl([['When', 'l'], ['Source', 'l'], ['Campaign or source', 'l'], ['Practice area or job type', 'l'], ['Line', 'l'], ['Type', 'l'], ['Outcome', 'l'], ['Place', 'l']], rows.map(r => `<tr><td class="l">${esc(fmtDate(r.date))}${r.hour != null ? ' ' + hh(r.hour) : ''}</td><td class="l">${badge(r.src)}${r.chan && r.chan !== r.src ? ' ' + badge(r.chan) : ''}</td><td class="l ac-wrap">${esc(r.campaign)}</td><td class="l ac-wrap">${esc(r.adset)}</td><td class="l">${esc(lname(r.line))}</td><td class="l">${r.kind === 'intake' ? 'Intake' : r.calls ? 'Call' : r.msgs ? 'Message' : 'Lead'}</td><td class="l small">${r.kind === 'intake' ? STG[r.stage] || 'Open' : r.conv ? (r.trk ? 'Qualified' : 'Charged' + (r.spend ? ' ' + money2(r.spend) : '')) : ''}${r.value && (r.retained || r.trk) ? ' · ' + money(r.value) : ''} ${esc(r.kind === 'intake' ? '' : r.note || '')}</td><td class="l small">${esc(r.geo ? [r.geo.zip, r.geo.cname || r.geo.city].filter(Boolean).join(' · ') : '')}</td></tr>`).join(''), 'ac-short');
    }
    /* ---------- method, judgment, sources ---------- */
    $('#acMeth', root).innerHTML = [
      '<b>Where it runs.</b> The page detects its host: the extension (runtime present), a page opened from disk or the web, or the hosted viewer. Sign in uses the browser identity API and needs the extension; pasted tokens work wherever the provider answers page calls; imports work everywhere. Credentials, tokens and rows live in chrome.storage.local in the extension and in localStorage elsewhere, under sv.accounts.v1.',
      '<b>Connections.</b> Google, Microsoft and LinkedIn use the authorization code flow (PKCE where the provider supports it) against the firm\'s own OAuth client; Google and Microsoft refresh tokens keep the connection alive. Local Services Ads and YouTube reuse the Google token. Meta uses the token flow of Facebook Login for Business (configuration ID, a code redeemed with the app secret when the dialog answers with one) and, with the app secret, exchanges the one hour token for a 60 day token. TikTok opens its portal authorization page and exchanges the auth code with the app secret for a long lived token.',
      '<b>Versions.</b> Google Ads and Meta are probed at Test time: the first version that answers (v25, v24, v23 for Google Ads; v27.0, v26.0, v25.0 for Graph) is remembered until the next Test. TikTok Business API v1.3, Local Services API v1, YouTube Analytics v2 and Data v3, Microsoft v13 and LinkedIn 202509 are fixed.',
      '<b>Pulls.</b> Google Ads API (campaigns by day and by hour, geographic view by postal code); Local Services API (detailed lead reports and account reports under the manager account, with the Google Ads local_services_lead report as the fallback); YouTube Analytics (channel by day, top 25 videos named through the Data API, channel statistics) plus video and Demand Gen campaigns from Google Ads; Business Profile Performance; Meta Marketing API (ad set by day, campaign by hour of the advertiser time zone, region), Page and Instagram insights; TikTok integrated report by day and by hour in 30 day windows; Microsoft Advertising Reporting (hourly campaign performance, zipped CSV unpacked in the page, folded into daily rows); LinkedIn adAnalytics by campaign and Page follower statistics.',
      '<b>Imports.</b> A CSV reader that handles quoted fields, tabs, comment lines and report preambles; column maps for eleven formats; the format is read from the header unless picked. Every imported row carries a hash of its source line, so importing the same file twice adds nothing. Call logs and intake exports are read for date, time, source, campaign, keyword, practice area, status, value and geography only.',
      '<b>Normalization.</b> Every source becomes rows of date, hour, campaign, ad group or practice area, geography (ZIP, county, city, region), impressions, clicks, spend, leads, calls, messages, conversions and retained matters, with a service line, a channel for calls and inquiries, and an intake stage (open, consult, retained, not retained). Daily, hourly, geographic, lead, intake and social rows are separate kinds so nothing counts twice; when the YouTube or LSA card has pulled its own rows, the Google pull\'s copies of those campaigns are dropped.',
      '<b>Service lines.</b> The practice area wins for intake rows; otherwise the ad group, then the campaign: a line key token (SEV_DIV_K_, _MOD_, _PO_), a LINE_META name or short name, then English and Spanish keywords from the most specific line (prenup, adoption, CPS, protective order, military, gray, high asset, enforcement, modification) to the most general (divorce without and with children, child support and paternity, custody). A generic divorce or family law name goes to divorce with children.',
      '<b>Feedback.</b> ACCT.rates(line) returns the observed cost per click and conversion rate from Google and Microsoft search rows and the retained rate from intake, each null below its threshold; Apply stores them as the corrections the Campaign Desk reads, and every change is announced on the bus. The observed hour of day distribution (90 days of hourly rows, six blocks, rounded to 5%) is offered to the Live Desk when the box is ticked.',
    ].map(x => `<li>${x}</li>`).join('');
    $('#acJudg', root).innerHTML = [
      ['Credentials belong to the firm', 'The module carries no developer credentials. Each provider needs an app or client created in the firm\'s own console and, for accounts outside that app\'s business, the provider\'s review. Meta in development mode, Google in testing mode and a TikTok app in the firm\'s own Business Center connect the firm\'s own accounts without review.'],
      ['Secrets in browser storage', 'Google and LinkedIn issue a client secret for web clients, TikTok an app secret, and Meta an optional app secret for the 60 day exchange; they are stored here so the token exchange can run from the page. Anyone with this browser profile can read them. Clear the tokens and the settings when the machine changes hands.'],
      ['Intake records are confidential', 'Clio Grow, Lawmatics and call tracking exports name prospective clients. The importers keep the date, source, practice area, status, value and place, and drop names, emails and phone numbers before anything is stored. The Local Services lead rows keep no consumer name or number either.'],
      ['Local Services Ads for lawyers', 'The listing runs under Google Screened (bar license and background checks) and the API only answers through a manager account that holds it. Lead timestamps are converted to the account\'s time zone. Account spend is itemized by the day and line of each charged lead; the remainder is dated at the end of the range on the account\'s most common lead line.'],
      ['Meta has no ZIP and no legal category', 'Meta reports region at best, so ZIP and county cost per lead come from Google, LSA, call logs and intake. There is no special ad category for legal services, but the personal attributes policy applies: ads that assert or imply the reader is divorcing are disapproved.'],
      ['Generic divorce goes to divorce with children', 'A campaign named only for divorce or family law maps to divorce with children, the line whose Campaign Desk headline is the generic city divorce lawyer ad. LinkedIn reports campaigns as URNs with no names, so its rows go to the high asset line.'],
      ['One inquiry, counted once', 'Platform conversions, tracked calls and intake records often describe the same person. Cost per lead divides by the largest of the three rather than their sum; retained matters come from intake (or a sheet\'s retained column, which should not repeat the same matters).'],
      ['Feedback is deliberately conservative', 'Thresholds (50 clicks, 3 leads, 10 decided inquiries) keep a lucky week from rewriting the plan, and open inquiries younger than 14 days stay out of the retained rate because they have not had time to decide. Below the thresholds the desk keeps its inputs and the table shows the gap.'],
      ['Provider APIs move', 'Google Ads and Graph are probed for the newest working version; the others are pinned. When a provider retires one, Test reports it and the pull notes carry the message. TikTok tokens never expire and have no refresh; they stop when revoked in the portal.'],
    ].map(([t, d]) => `<dt>${esc(t)}</dt><dd>${esc(d)}</dd>`).join('');
    function register() {
      const R = [['Google Ads API', 'GAQL reporting: campaigns by day and hour, geographic view; video and Demand Gen for the YouTube card; local_services_lead as the LSA fallback', 'A', `${ACCT.ver('google')} (probe v25, v24, v23)`, 'https://developers.google.com/google-ads/api/docs/start'], ['Local Services API', 'accountReports:search and detailedLeadReports:search under the manager account', 'A', 'v1', 'https://developers.google.com/local-services-ads/guides/reporting'], ['YouTube Analytics API', 'Channel by day, top videos', 'A', 'v2', 'https://developers.google.com/youtube/analytics/reference/reports/query'], ['YouTube Data API', 'Video titles, channel statistics', 'A', 'v3', 'https://developers.google.com/youtube/v3/docs'], ['Business Profile Performance API', 'Daily metrics time series', 'A', 'v1', 'https://developers.google.com/my-business/reference/performance/rest'], ['Meta Marketing API', 'Insights, breakdowns, Page and Instagram insights, long lived token exchange', 'A', `${ACCT.ver('meta')} (probe v27.0, v26.0, v25.0)`, 'https://developers.facebook.com/docs/marketing-api/insights'], ['TikTok Business API', 'oauth2/access_token, oauth2/advertiser/get, report/integrated/get', 'A', 'v1.3', 'https://business-api.tiktok.com/portal/docs/reporting-reference/v1.3'], ['Microsoft Advertising API', 'Reporting REST, campaign performance; Customer Management user query', 'A', 'v13', 'https://learn.microsoft.com/en-us/advertising/reporting-service/reporting-service-reference'], ['LinkedIn Marketing API', 'adAnalytics, organization follower statistics', 'A', '202509', 'https://learn.microsoft.com/en-us/linkedin/marketing/'], ['CallRail and CallTrackingMetrics', 'Call log CSV exports (start time, source, campaign, keyword, status, value, place)', 'B', 'file', 'https://www.callrail.com/'], ['Clio Grow and Lawmatics', 'Lead and matter CSV exports (created, source, practice area, status or stage, value, place)', 'B', 'file', 'https://www.clio.com/grow/'], ['Service lines', 'LINE_META, module 06', 'A', 'Severance', '#lines'], ['Browser extension identity', 'launchWebAuthFlow and getRedirectURL (Chrome, Edge, Brave, Firefox)', 'A', 'MV3', 'https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/identity']];
      $('#acReg', root).innerHTML = tbl([['Source', 'l'], ['Used for', 'l'], ['Grade'], ['Version', 'l']], R.map(r => `<tr><td class="l">${/^https:/.test(r[4]) ? `<a href="${esc(r[4])}" target="_blank" rel="noopener">${esc(r[0])}</a>` : esc(r[0])}</td><td class="l ac-wrap">${esc(r[1])}</td><td><span class="grade ${r[2]}">${r[2]}</span></td><td class="l ac-wrap ac-narrow">${esc(r[3])}</td></tr>`).join(''));
    }
    /* ---------- wiring ---------- */
    function renderData() { tiles(); connStatus(); impLog(); pace(); lines(); sources(); hours(); geo(); social(); leads(); register(); }
    function renderAll() { env(); conns(); renderData(); }
    wireSeg($('#acRange', root), v => { st.range = +v; ACCT.setSettings({ range: st.range }); $$('#acConn button[data-a="pull"]', root).forEach(b => b.textContent = `Sync ${st.range} days`); });
    wireSeg($('#acGeoSeg', root), v => { st.geo = v; geo(); });
    $('#acUseObs', root).onchange = e => { ACCT.setSettings({ useObserved: e.target.checked }); toast(e.target.checked ? 'The Live Desk is offered the observed hours' : 'The Live Desk keeps its own timing'); };
    /* Apply says exactly what changed, input by input; Revert names the desk inputs it returns to (those from before the first Apply) */
    const showChanges = (head, list) => { const host = $('#acChanges', root); host.innerHTML = list.length ? `<b>${esc(head)}</b><ul>${list.map(t => `<li>${esc(t)}</li>`).join('')}</ul>` : `<b>${esc(head)}</b>`; };
    $('#acApply', root).onclick = () => {
      const patch = ACCT.applyToModels(); const n = Object.keys(patch.lines).length + ACCT.FIELDS.filter(k => patch[k] != null).length; const ch = ACCT.changeText(patch.changes || [], lname);
      if (!n && !ch.length) { showChanges('Not enough volume to correct any desk input yet.', []); toast('Not enough volume to correct any desk input yet'); return; }
      if (!ch.length) { showChanges('Applied again: nothing changed since the last Apply.', []); toast('Applied again: nothing changed since the last Apply'); return; }
      showChanges(`Applied ${N(ch.length)} change${ch.length === 1 ? '' : 's'} to the Campaign Desk:`, ch); toast(`Applied: ${ch.slice(0, 2).join('; ')}${ch.length > 2 ? `; and ${N(ch.length - 2)} more (listed under the table)` : ''}`);
    };
    $('#acRevert', root).onclick = () => {
      const r = ACCT.revertModels(); if (!r) { toast('Nothing applied'); return; } const pv = r.prev || {};
      const own = [isN(pv.cpc) ? 'CPC ' + money2(pv.cpc) : '', isN(pv.cvr) ? 'conversion ' + P1(pv.cvr, 1) : '', isN(pv.retain) ? 'retained ' + P1(pv.retain, 1) : ''].filter(Boolean);
      const msg = `Reverted ${r.count > 1 ? `${N(r.count)} Applies` : 'the Apply'}: the Campaign Desk is back on its own inputs from before ${when(r.first)}${own.length ? ` (${own.join(', ')}${pv.from ? ', from ' + pv.from : ''})` : ''}.`;
      showChanges(msg, []); toast(msg);
    };
    $('#acSync', root).onclick = async () => { const ps = ACCT.PORDER.filter(p => ACCT.status(p).state === 'connected'); if (ACCT.ENV === 'viewer') { toast('Calls are blocked in the hosted viewer'); return; } if (!ps.length) { toast('No connected accounts'); return; } for (const p of ps) await act(p, 'pull', $(`.ac-conn[data-p="${p}"]`, root)); };
    $('#acCsv', root).onclick = () => { const rows = ACCT.rowsAll(); if (!rows.length) { toast('No actuals held'); return; } saveFile(`severance-actuals-${todayISO()}.csv`, toCSV(['source', 'kind', 'date', 'hour', 'campaign', 'ad group or practice area', 'zip', 'county', 'city', 'region', 'channel', 'impressions', 'clicks', 'spend', 'leads', 'calls', 'messages', 'conversions', 'retained', 'stage', 'value', 'line', 'note'], rows.map(r => [r.src, r.kind, r.date, r.hour == null ? '' : r.hour, r.campaign, r.adset, (r.geo && r.geo.zip) || '', (r.geo && r.geo.cname) || '', (r.geo && r.geo.city) || '', (r.geo && r.geo.region) || '', r.chan || '', r.imp, r.clicks, +(+r.spend || 0).toFixed(2), r.leads, r.calls, r.msgs, r.conv, r.retained || 0, r.stage || '', r.value || '', r.line, r.note || '']), 'Normalized actuals from every connected account and import held in this browser. No names or phone numbers are kept.')); };
    $('#acJson', root).onclick = () => saveFile(`severance-actuals-${todayISO()}.json`, JSON.stringify({ exported: new Date().toISOString(), actuals: ACCT.S.actuals, imports: ACCT.S.imports, settings: ACCT.settings() }));
    $('#acTmpl', root).onclick = () => saveFile('severance-import-template.csv', ACCT.templateCSV());
    $('#acDesk', root).onclick = () => goModule('desk'); const lb = $('#acLive', root); if (lb) lb.onclick = () => goModule('live');
    let tmr = null; const later = fn => { clearTimeout(tmr); tmr = setTimeout(() => { if (root.isConnected) fn(); }, 60); };
    self._ac = { root, data: () => later(renderData), status: () => { if (root.isConnected) { connStatus(); tiles(); } }, all: () => later(renderAll) };
    if (!self._acBound) { self._acBound = true; BUS.on('actuals', d => { const a = self._ac; if (!a) return; const w = d && d.what; if (w === 'load') a.all(); else if (w === 'cfg' || w === 'tokens') a.status(); else a.data(); }); BUS.on('plan', () => { const a = self._ac; if (a) a.data(); }); }
    renderAll(); ACCT.ready().then(() => { if (root.isConnected) renderAll(); });
  },
  receive(p) { const a = this._ac; if (!a || !p) return; if (p.provider) { const c = $(`.ac-conn[data-p="${p.provider}"]`, a.root); if (c) c.scrollIntoView({ behavior: 'smooth', block: 'start' }); } if (p.csv) { const r = ACCT.importCSV(p.csv, p.format || null, p.label || null); toast(r.note); } }
});
