#!/usr/bin/env python3
"""One-time generator: appends OmegaWeapon's client-vertical nomes to assets/nomes.json (Horus's ten media
nomes stay untouched). Run from the skill root: python3 scripts/_extend_nomes.py
Idempotent: a nome whose id already exists is replaced, not duplicated."""
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
P = ROOT / "assets" / "nomes.json"
d = json.loads(P.read_text(encoding="utf-8"))

def T(i, label, short, dfn, kw):
    return {"id": i, "label": label, "short": short, "def": dfn, "kw": kw}

OTHER = lambda: T("V00", "Other", "Other", "Items outside the vertical that the frame included; the Other share measures frame noise.", [])

NOMES = []

NOMES.append({
 "id": "local-services", "name": "Local Services and Trades", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Home services, trades, clinics, salons, restaurants and every business that wins or loses in a map pack: the local pack, Google Business Profile, reviews, Local Services Ads, lead marketplaces, private equity roll ups, pricing and the labor squeeze.",
 "clusters": {"Local visibility": ["V01", "V02", "V03"], "Demand": ["V04", "V05", "V06"], "Operations": ["V07", "V08", "V09"], "Reputation and rules": ["V10", "V11"], "Money": ["V12", "V13"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Google Business Profile and the local pack", "GBP and pack", "Ranking, suspensions, edits, categories, justifications, the finder and Maps.", ["google business profile", "gbp", "map pack", "local pack", "3-pack", "suspended listing", "reinstatement", "maps ranking", "local finder", "categories"]),
  T("V02", "Reviews and reputation systems", "Reviews", "Review acquisition, gating, removal, fake review enforcement, review platforms.", ["reviews", "review request", "fake reviews", "review removal", "yelp", "reputation", "5 star", "review gating", "consumer review rule"]),
  T("V03", "Local Services Ads and Google Guaranteed", "LSA", "LSA eligibility, lead quality, disputes, ranking, the badge, pricing changes.", ["local services ads", "lsa", "google guaranteed", "google screened", "lead dispute", "lsa leads", "pay per lead"]),
  T("V04", "Lead marketplaces and aggregators", "Lead marketplaces", "Angi, Thumbtack, HomeAdvisor, Networx, Bark, Zocdoc and pay per lead economics.", ["angi", "thumbtack", "homeadvisor", "networx", "bark", "zocdoc", "lead gen", "shared leads", "pay per lead", "lead quality"]),
  T("V05", "Paid search and Meta for local", "Local paid", "Google Ads, PMax for local, Meta lead ads, call tracking, CPL benchmarks.", ["google ads", "ppc", "cost per lead", "cpl", "meta lead ads", "facebook ads", "pmax", "call tracking", "ad spend"]),
  T("V06", "Seasonality and demand shifts", "Seasonality", "Weather, seasons, economic mood, demand collapses and spikes by trade.", ["slow season", "busy season", "demand down", "phones stopped ringing", "heat wave", "storm season", "recession", "calls dropped"]),
  T("V07", "Software, CRM and AI receptionists", "Software and AI", "Field service software, CRMs, booking tools, AI answering and chat, automation.", ["servicetitan", "housecall pro", "jobber", "crm", "ai receptionist", "answering service", "booking software", "automation", "dispatch software", "ai chat"]),
  T("V08", "Labor, hiring and technician shortage", "Labor", "Hiring, wages, training, retention and the skilled trades gap.", ["hiring", "technicians", "labor shortage", "apprentice", "wages", "turnover", "recruiting", "trade school", "staffing"]),
  T("V09", "Pricing, financing and consumer credit", "Pricing", "Flat rate vs time and materials, financing offers, BNPL for services, price transparency laws.", ["pricing", "flat rate", "financing", "consumer financing", "bnpl", "price transparency", "estimates", "upsell", "membership plans"]),
  T("V10", "Licensing, compliance and enforcement", "Compliance", "License boards, unlicensed work, advertising rules, telemarketing and review law enforcement.", ["license", "unlicensed", "board complaint", "fine", "tcpa", "ftc", "attorney general", "permit", "contractor law", "advertising rule"]),
  T("V11", "Spam, fake listings and lead theft", "Listing spam", "Fake GBP listings, keyword stuffed names, virtual offices, call hijacking, brand bidding by rivals.", ["fake listing", "keyword stuffing", "spam listing", "virtual office", "lead gen sites", "brand bidding", "call hijack", "redressal"]),
  T("V12", "Private equity, consolidation and exits", "Consolidation", "PE roll ups, platform acquisitions, valuations, franchising and what they do to marketing.", ["private equity", "roll up", "acquired", "acquisition", "platform company", "valuation", "exit", "franchise", "consolidation"]),
  T("V13", "Websites, SEO and AI search for local", "Local SEO and AI", "Service and city pages, schema, AI Overviews for local queries, site platforms.", ["local seo", "service pages", "city pages", "schema", "ai overview", "ai mode", "wordpress", "website", "near me"]),
  OTHER()],
 "sun": {"trade_press": ["searchengineland.com (local)", "localu.org", "brightlocal.com/blog", "sterlingsky.ca", "whitespark.ca/blog", "servicetitan.com/blog", "contractingbusiness.com", "pctonline.com", "achrnews.com", "pmmag.com", "dentistryiq.com", "restaurantbusinessonline.com"], "newsletters": ["Local Search Forum digest", "Near Media newsletter", "Whitespark Local Search Insider"], "platform_voices": ["Google Business Profile Help updates", "Google Ads and Commerce blog (LSA)", "Yelp for Business blog", "Angi and Thumbtack pro blogs"], "podcasts": ["Near Memo", "The Local Marketing Institute podcast", "To The Point (home services)"]},
 "moon": {"subreddits": ["r/localseo", "r/smallbusiness", "r/HVAC", "r/Plumbing", "r/electricians", "r/pestcontrol", "r/Dentistry", "r/Entrepreneur", "r/sweatystartup", "r/googleads"], "forums": ["Local Search Forum", "Google Business Profile Help Community", "ContractorTalk", "HVAC-Talk", "The Lawn Forum", "Dentaltown"], "discord_discovery": ["disboard tags: local-seo, home-services, contractors, small-business"], "telegram_discovery": ["TGStat category 'Marketing, PR, advertising' filtered by local seo"], "practitioner_social": ["Local SEO practitioners' public threads on X and LinkedIn (curated only)"]},
 "nilometer": ["Angi Inc. quarterly results (home services demand and lead pricing)", "Yelp Inc. quarterly results (local ad revenue, request a quote volume)", "Alphabet 8-K and Ads blog (LSA and local ad changes)", "BrightLocal Local Consumer Review Survey (annual)", "Whitespark Local Search Ranking Factors (annual)", "Sterling Sky GBP suspension trackers", "BLS employment and wages for construction, HVAC, plumbing, dental and personal care", "ServiceTitan public filings", "FTC Consumer Review Rule enforcement and state license board actions", "Census Bureau County Business Patterns (establishment counts)"],
 "standing_questions": ["What is moving map pack visibility this quarter, and how much of it is within a single business's control?", "Where is lead cost heading on LSA, Google Ads and the marketplaces, and who is capturing the margin?", "What are owners asking for help with that the local search press is not covering?", "Which local tactics are being punished (suspensions, review enforcement) and which grey tactics still pay?", "What is consolidation doing to marketing in the trades?"]})

NOMES.append({
 "id": "legal-services", "name": "Legal Services Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Law firm marketing: intake, LSA, the local pack, mass tort advertising, bar advertising enforcement, legal lead generation, AI in legal research and intake, pricing and the firm labor market.",
 "clusters": {"Acquisition": ["V01", "V02", "V03", "V04"], "Rules": ["V05", "V06"], "Operations": ["V07", "V08", "V09"], "Market": ["V10", "V11", "V12"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Legal LSA and paid search", "Legal paid", "LSA legal categories, Google Screened, CPC inflation, brand bidding between firms.", ["lsa", "google screened", "legal ppc", "cost per click", "personal injury ads", "brand bidding", "google ads lawyers"]),
  T("V02", "Local pack and firm SEO", "Firm SEO", "GBP for firms, practice area pages, city pages, AI Overviews for legal queries.", ["law firm seo", "attorney seo", "practice area page", "gbp", "map pack", "ai overview", "legal keywords"]),
  T("V03", "Legal lead generation and case marketplaces", "Lead gen", "Mass tort lead gen, case marketplaces, referral fees, lead quality, TCPA exposure.", ["lead generation", "mass tort leads", "case leads", "signed cases", "referral fee", "lead vendor", "tcpa"]),
  T("V04", "Mass tort and TV advertising", "Mass tort", "Docket driven advertising, TV and streaming buys, ad disclosure statutes.", ["mass tort", "tv ads", "streaming ads", "camp lejeune", "talc", "roundup", "advertising spend", "docket"]),
  T("V05", "Bar advertising rules and enforcement", "Bar rules", "Rule 7 series, filing states, disclaimers, testimonial rules, discipline for ads.", ["bar rules", "rule 7.1", "attorney advertising", "disclaimer", "state bar", "filing", "testimonials", "specialist", "discipline"]),
  T("V06", "Ethics of AI and technology in practice", "AI ethics", "Generative AI in research and intake, hallucinated citations, confidentiality, court orders.", ["hallucinated", "ai in law", "chatgpt lawyer", "sanctions", "confidentiality", "legal ai", "harvey", "co-counsel", "ai intake"]),
  T("V07", "Intake, call handling and conversion", "Intake", "Answering services, intake software, speed to lead, chat, conversion rates.", ["intake", "answering service", "speed to lead", "chat", "conversion", "missed calls", "intake software", "crm"]),
  T("V08", "Pricing, fees and alternative fee models", "Fees", "Contingency, flat fees, subscription legal, fee transparency.", ["contingency", "flat fee", "subscription", "billable hour", "fee transparency", "pricing"]),
  T("V09", "Hiring, associates and firm labor", "Firm labor", "Associate pay, lateral moves, paralegal shortage, remote work.", ["associate salary", "lateral", "paralegal", "hiring", "remote", "turnover", "law school"]),
  T("V10", "Reviews and reputation for firms", "Reviews", "Client reviews, Avvo, review solicitation rules, negative review responses.", ["reviews", "avvo", "google reviews", "reputation", "negative review", "client testimonial"]),
  T("V11", "Legal directories and referral platforms", "Directories", "Avvo, FindLaw, Justia, Martindale, Nolo, Super Lawyers and pay to play badges.", ["avvo", "findlaw", "justia", "martindale", "super lawyers", "best lawyers", "directory", "badge"]),
  T("V12", "Private equity, ABS and non-lawyer ownership", "Ownership", "Arizona ABS, litigation funding, MSOs, private equity in law firm marketing.", ["alternative business structure", "abs", "arizona", "litigation funding", "private equity", "mso", "non-lawyer ownership"]),
  OTHER()],
 "sun": {"trade_press": ["law.com", "abajournal.com", "lawyerist.com", "attorneyatwork.com", "legalmarketingassociation (strategies)", "above the law", "law360 (legal industry)", "jdsupra (marketing sections)"], "newsletters": ["Lawyerist Insider", "LMA weekly", "Clio Legal Trends briefings"], "platform_voices": ["Google Ads blog (LSA legal)", "Clio blog", "Avvo for Lawyers blog", "Smokeball and MyCase blogs"], "podcasts": ["Lawyerist Podcast", "The Un-Billable Hour", "Legal Marketing 2.0"]},
 "moon": {"subreddits": ["r/Lawyertalk", "r/LawFirm", "r/legaladvice (consumer side, as evidence of demand)", "r/paralegal"], "forums": ["Lawyerist community", "Reddit legal marketing threads", "Legal Marketing Association member forums (public pages only)"], "discord_discovery": ["disboard tags: law, lawyers, legal"], "telegram_discovery": ["TGStat legal marketing channels (rare)"], "practitioner_social": ["Law firm marketers' public posts on LinkedIn (curated only)"]},
 "nilometer": ["Clio Legal Trends Report (annual)", "ABA Profile of the Legal Profession (annual)", "X Ante mass tort TV spend reports", "Thomson Reuters Law Firm Financial Index", "State bar discipline summaries and advertising committee opinions", "Google Ads legal CPC benchmarks (vendor, C3)", "Court dockets for MDL volume (JPML statistics)", "BLS legal occupations employment and wages"],
 "standing_questions": ["Where is legal client acquisition cost heading, and which channels are firms abandoning?", "Which bar advertising rules are actually enforced, and where?", "What are firm marketers asking about that the legal press ignores?", "Is AI in intake and research changing how firms market, or only how they bill?", "What is capital (PE, ABS, funders) doing to competition for cases?"]})

NOMES.append({
 "id": "healthcare-practices", "name": "Healthcare Practice Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Practices, clinics, med spas, telehealth, therapy providers and wellness brands: patient acquisition, reviews, health data and pixel enforcement, FDA and FTC claims enforcement, platform health policies, staffing and consolidation.",
 "clusters": {"Acquisition": ["V01", "V02", "V03"], "Rules": ["V04", "V05", "V06"], "Operations": ["V07", "V08"], "Market": ["V09", "V10", "V11"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Patient acquisition: search, pack and directories", "Acquisition", "Healthcare SEO, GBP for practitioners, Zocdoc, Healthgrades, AI Overviews for symptoms and providers.", ["healthcare seo", "zocdoc", "healthgrades", "gbp", "map pack", "patient acquisition", "ai overview", "provider search"]),
  T("V02", "Paid media under health policies", "Health paid", "Google Healthcare certification, Meta health data restrictions, LegitScript, telehealth ads.", ["google ads healthcare", "legitscript", "meta health", "data source restrictions", "telehealth ads", "certification", "restricted"]),
  T("V03", "Reviews and patient reputation", "Reviews", "Review requests under HIPAA, negative reviews, response rules, review platforms.", ["patient reviews", "hipaa reviews", "google reviews", "negative review", "reputation", "review response"]),
  T("V04", "Health data privacy and tracking enforcement", "Health data", "Pixels on patient pages, MHMDA, HIPAA tracking guidance, litigation, consent.", ["pixel", "meta pixel", "hipaa", "mhmda", "tracking", "class action", "consent", "session replay", "ocr guidance"]),
  T("V05", "Claims enforcement: FDA, FTC, boards", "Claims", "Warning letters, GLP-1 compounding claims, supplements, board certified claims, before and after rules.", ["warning letter", "fda", "ftc", "glp-1", "semaglutide", "compounded", "board certified", "before and after", "claims"]),
  T("V06", "Scope, licensing and corporate practice", "Licensing", "Med spa supervision, corporate practice of medicine, telehealth licensing, DEA flexibilities.", ["medical director", "corporate practice", "med spa", "licensing", "telehealth license", "dea", "scope of practice"]),
  T("V07", "Intake, scheduling and patient experience tech", "Practice tech", "Online scheduling, patient portals, AI scribes and receptionists, EHR marketing integrations.", ["online scheduling", "patient portal", "ai scribe", "ai receptionist", "ehr", "no show", "intake", "automation"]),
  T("V08", "Staffing and clinician labor", "Staffing", "Nurse and clinician shortages, wages, burnout, hiring.", ["staffing", "nurse shortage", "burnout", "hiring", "wages", "turnover", "locum"]),
  T("V09", "Consolidation, PE and payer pressure", "Consolidation", "PE in dental, derm, vet and physio; hospital acquisitions; reimbursement pressure.", ["private equity", "dso", "acquired", "reimbursement", "payer", "consolidation", "roll up", "hospital system"]),
  T("V10", "Telehealth and DTC health brands", "Telehealth DTC", "Hims and Hers model, compounding, subscription health, weight loss brands.", ["telehealth", "dtc", "hims", "ro", "weight loss", "subscription", "compounding pharmacy", "online prescription"]),
  T("V11", "Content, trust and AI answers about health", "Health content", "YMYL content, medical review bylines, AI answers citing providers, misinformation.", ["ymyl", "medical review", "content", "ai answers", "misinformation", "eeat", "author bylines"]),
  OTHER()],
 "sun": {"trade_press": ["fiercehealthcare.com", "medcitynews.com", "healthcareitnews.com", "physicianspractice.com", "dentaleconomics.com", "americanspa.com", "modernhealthcare.com", "mmm-online.com"], "newsletters": ["Fierce Healthcare briefings", "Rock Health Weekly", "Healthcare Marketing Network digest"], "platform_voices": ["Google Ads Healthcare policy updates", "Meta business help (health and wellness)", "Zocdoc for practices blog", "LegitScript blog"], "podcasts": ["Healthcare Rap", "The Dental Marketer", "Rock Health podcast"]},
 "moon": {"subreddits": ["r/medicine (practice management threads)", "r/Dentistry", "r/physicaltherapy", "r/therapists", "r/healthIT", "r/medspa", "r/Nurse (workplace voice)"], "forums": ["Dentaltown", "Student Doctor Network practice forums", "Google Ads Community (healthcare threads)"], "discord_discovery": ["disboard tags: healthcare, medical, dental"], "telegram_discovery": ["TGStat health marketing channels (rare)"], "practitioner_social": ["Practice owners' public posts (curated only)"]},
 "nilometer": ["FDA warning letters database and openFDA enforcement", "FTC health claims actions and Consumer Review Rule letters", "HHS OCR enforcement and tracking guidance status", "CMS and payer rate notices", "Hims and Hers, Teladoc, Zocdoc (private; reported), Henry Schein and Align quarterly results", "BLS healthcare employment and wages", "State attorney general health privacy actions", "Rock Health digital health funding report"],
 "standing_questions": ["What can a practice lawfully track and advertise this quarter, and what just got enforced?", "Where is patient acquisition cost moving by specialty?", "What are practice owners asking for help with that the health marketing press does not cover?", "Which DTC health claims are being punished, and does the claim shape repeat in local practice marketing?", "What is consolidation doing to marketing budgets and brand names?"]})

NOMES.append({
 "id": "ecommerce-retail", "name": "E-commerce and Retail Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Online stores, DTC brands, marketplaces sellers and omnichannel retailers: Shopping and PMax, Meta Advantage+, TikTok Shop, agentic commerce and AI shopping, feeds, marketplaces, tariffs, retention and the platform rules of selling.",
 "clusters": {"Paid": ["V01", "V02", "V03"], "Discovery": ["V04", "V05", "V06"], "Operations": ["V07", "V08", "V09"], "Rules and money": ["V10", "V11", "V12"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Google Shopping, PMax and Merchant Center", "Shopping and PMax", "Feeds, PMax channel reporting, brand exclusions, Merchant Center suspensions, free listings.", ["pmax", "performance max", "merchant center", "shopping ads", "feed", "suspension", "misrepresentation", "brand exclusion", "free listings"]),
  T("V02", "Meta, TikTok and social commerce ads", "Social commerce ads", "Advantage+, Andromeda, creative testing, TikTok Shop ads, Pinterest Performance+.", ["advantage+", "andromeda", "meta ads", "tiktok ads", "tiktok shop", "pinterest", "creative testing", "roas", "cpa"]),
  T("V03", "Retail media and marketplaces advertising", "Retail media", "Amazon Ads, Walmart Connect, Instacart, Target Roundel and marketplace fee changes.", ["amazon ads", "retail media", "walmart connect", "instacart ads", "sponsored products", "marketplace fees", "fba"]),
  T("V04", "AI shopping and agentic commerce", "Agentic commerce", "ChatGPT shopping and checkout, Google AI Mode shopping, product feeds for assistants, agent protocols.", ["agentic commerce", "chatgpt shopping", "instant checkout", "ai mode shopping", "acp", "agent", "ai shopping", "product feed ai"]),
  T("V05", "Organic search and content for stores", "Store SEO", "Category and product page SEO, faceted navigation, AI Overviews on product queries, content.", ["ecommerce seo", "category pages", "faceted", "product page", "ai overview", "collections", "shopify seo", "indexing"]),
  T("V06", "Creators, affiliates and UGC", "Creators", "Creator programs, affiliate networks, disclosure, whitelisting and Partnership ads.", ["creators", "influencers", "affiliate", "ugc", "partnership ads", "whitelisting", "disclosure", "commission"]),
  T("V07", "Platforms, storefronts and checkout", "Platforms", "Shopify, WooCommerce, BigCommerce, headless, checkout and payments changes.", ["shopify", "woocommerce", "bigcommerce", "headless", "checkout", "shop pay", "payments", "app store shopify"]),
  T("V08", "Email, SMS and retention", "Retention", "Klaviyo, SMS consent, loyalty, subscriptions, churn and lifetime value.", ["klaviyo", "email marketing", "sms", "retention", "loyalty", "subscription", "ltv", "churn", "10dlc"]),
  T("V09", "Logistics, returns and customer service", "Operations", "Shipping costs, returns policy, fulfillment, service tech and chatbots.", ["shipping", "returns", "fulfillment", "3pl", "customer service", "chatbot", "delivery", "returns fraud"]),
  T("V10", "Tariffs, costs and pricing", "Costs", "Tariffs, de minimis, input costs, pricing strategy, discounting.", ["tariff", "de minimis", "cogs", "pricing", "discount", "margin", "inflation", "import"]),
  T("V11", "Consumer protection and platform rules", "Rules", "Fake reviews, negative option, junk fees, INFORM Act, marketplace policy enforcement.", ["fake reviews", "ftc", "negative option", "click to cancel", "junk fees", "inform act", "policy", "suspended", "compliance"]),
  T("V12", "Measurement, attribution and privacy signals", "Measurement", "GA4, CAPI, EMQ, incrementality, MMM, consent and signal loss.", ["ga4", "capi", "attribution", "incrementality", "mmm", "consent mode", "signal loss", "emq", "server side"]),
  OTHER()],
 "sun": {"trade_press": ["modernretail.co", "digitalcommerce360.com", "practicalecommerce.com", "retaildive.com", "marketplacepulse.com", "ecommercebytes.com", "adexchanger.com (commerce)", "searchengineland.com (commerce)"], "newsletters": ["2PM", "Modern Retail briefings", "Lean Luxe", "Marketplace Pulse"], "platform_voices": ["Shopify Changelog and Editions", "Google Ads and Commerce blog", "Meta for Business newsroom", "Amazon Ads blog", "TikTok Shop newsroom", "OpenAI commerce announcements"], "podcasts": ["Ecommerce Playbook", "Limited Supply", "The Ecom Show"]},
 "moon": {"subreddits": ["r/ecommerce", "r/shopify", "r/FulfillmentByAmazon", "r/AmazonSeller", "r/PPC (shopping threads)", "r/FacebookAds", "r/dropship", "r/Entrepreneur"], "forums": ["Shopify Community", "Seller Central forums", "eCommerceFuel (public pages)", "Warrior Forum"], "discord_discovery": ["disboard tags: ecommerce, shopify, dropshipping, amazon-fba"], "telegram_discovery": ["TGStat 'Sales' and dropshipping channels"], "practitioner_social": ["DTC operators' public threads (curated only)"]},
 "nilometer": ["Shopify, Amazon, Meta, Alphabet, Pinterest quarterly results", "Digital Commerce 360 and Census e-commerce quarterly estimates", "Adobe Digital Economy Index (holiday and price data)", "Marketplace Pulse seller data", "FTC negative option and review rule actions", "CBP tariff and de minimis notices", "Klaviyo and Attentive public results and benchmarks", "Triple Whale and Northbeam benchmarks (vendor, C3)"],
 "standing_questions": ["Where is discovery for products moving (search, social, marketplaces, AI agents), and who is monetizing the interface?", "What is the real cost of acquisition trend by channel, and what is being hidden by attribution changes?", "What are operators asking for help with that the trade press is not covering?", "Which selling rules are being enforced this quarter (reviews, subscriptions, fees, feeds)?", "How are tariffs and input costs changing promotion and pricing behavior?"]})

NOMES.append({
 "id": "b2b-saas", "name": "B2B and SaaS Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Software and B2B services marketing: pipeline and demand gen, LinkedIn, review sites, AI answers about vendors, content and SEO decline, pricing pages, PLG, events, ABM and the RevOps stack.",
 "clusters": {"Demand": ["V01", "V02", "V03"], "Discovery": ["V04", "V05", "V06"], "Stack and ops": ["V07", "V08", "V09"], "Market": ["V10", "V11"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Demand gen, pipeline and attribution", "Pipeline", "MQL to pipeline debates, self reported attribution, dark funnel, marketing sourced revenue.", ["pipeline", "mql", "demand gen", "attribution", "self reported", "dark funnel", "sourced", "revenue marketing"]),
  T("V02", "LinkedIn and paid social for B2B", "LinkedIn", "Campaign Manager, Thought Leader Ads, CPMs, targeting, LinkedIn organic reach.", ["linkedin ads", "thought leader ads", "campaign manager", "linkedin organic", "cpm", "b2b social", "linkedin algorithm"]),
  T("V03", "Paid search, intent data and ABM", "Search and ABM", "Google and Microsoft Ads for software, intent data vendors, account based programs.", ["google ads b2b", "microsoft ads", "intent data", "abm", "6sense", "demandbase", "account based", "cpc software"]),
  T("V04", "Review sites and the corroboration layer", "Review sites", "G2, Capterra, TrustRadius, Gartner Peer Insights, reviews as AI sources.", ["g2", "capterra", "trustradius", "gartner", "peer insights", "reviews", "review site", "badges"]),
  T("V05", "AI answers about vendors and GEO", "AI answers", "How ChatGPT, Gemini and Perplexity recommend software; citations; llms.txt; visibility tracking.", ["ai visibility", "chatgpt recommends", "geo", "llms.txt", "perplexity", "ai search", "citations", "brand mentions"]),
  T("V06", "Content, SEO and the traffic decline", "Content and SEO", "Blog traffic collapse, programmatic SEO, content strategy, comparison pages, docs SEO.", ["seo", "content marketing", "traffic decline", "programmatic seo", "comparison pages", "blog", "organic", "docs"]),
  T("V07", "Pricing, packaging and PLG", "Pricing and PLG", "Pricing pages, free trials, usage pricing, product led growth, self serve.", ["pricing page", "free trial", "plg", "usage based", "self serve", "freemium", "packaging", "seat"]),
  T("V08", "RevOps, CRM and the martech stack", "Stack", "HubSpot, Salesforce, tooling consolidation, AI agents in the stack, data quality.", ["hubspot", "salesforce", "martech", "revops", "stack", "consolidation", "ai agents", "data quality", "cdp"]),
  T("V09", "Events, community and partnerships", "Events", "Field marketing, conferences, communities, partner and integration marketing.", ["events", "conference", "field marketing", "community", "partnerships", "integration", "webinar", "user group"]),
  T("V10", "Budgets, headcount and the marketing labor market", "Budgets", "CMO tenure, layoffs, agency vs in house, budget cuts, AI replacing roles.", ["budget", "layoffs", "headcount", "cmo", "in house", "agency", "hiring", "ai replacing"]),
  T("V11", "Brand, category creation and positioning", "Brand", "Brand vs demand debates, positioning, category creation, messaging.", ["brand", "positioning", "category", "messaging", "brand marketing", "awareness", "differentiation"]),
  OTHER()],
 "sun": {"trade_press": ["martech.org", "marketingprofs.com", "cmswire.com", "demandgenreport.com", "saastr.com", "openviewpartners.com (blog)", "thecmo.com", "adexchanger.com (b2b)"], "newsletters": ["Exit Five newsletter", "Marketing Brew B2B", "Lenny's Newsletter (growth)", "SaaStr weekly"], "platform_voices": ["LinkedIn Marketing Solutions blog", "HubSpot blog and product updates", "G2 Research and Learn Hub", "Google Ads blog (B2B)"], "podcasts": ["Exit Five", "B2B Growth", "Marketing Against the Grain"]},
 "moon": {"subreddits": ["r/b2bmarketing", "r/SaaS", "r/marketing", "r/ProductMarketing", "r/sales", "r/startups"], "forums": ["Exit Five community (public pages)", "Indie Hackers", "Growth Hackers", "Pavilion (public pages)", "Hacker News (marketing threads)"], "discord_discovery": ["disboard tags: saas, b2b, startup, growth-marketing"], "telegram_discovery": ["TGStat marketing channels filtered by b2b"], "practitioner_social": ["B2B marketers' public LinkedIn posts (curated only)"]},
 "nilometer": ["Gartner CMO Spend Survey", "Forrester B2B forecasts", "LinkedIn and Microsoft quarterly results (Marketing Solutions)", "HubSpot, Salesforce, ZoomInfo quarterly results", "G2 Buyer Behavior Report", "TrustRadius B2B Buying Disconnect", "6sense Buyer Experience Report", "SaaS Capital and OpenView benchmarks", "BLS marketing occupations employment"],
 "standing_questions": ["Where are software buyers discovering and shortlisting vendors now, and how much of it is AI mediated?", "What is happening to organic traffic for software sites, and what replaces it?", "What are B2B marketers asking about that the conference stages are not?", "Which demand gen metrics are being abandoned and which adopted?", "Is the marketing labor market for B2B shrinking, shifting or restructuring?"]})

NOMES.append({
 "id": "marketplace-leadgen", "name": "Marketplaces, Directories and Lead Generation", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Quote marketplaces, directories, comparison and affiliate sites, lead networks and aggregators: lead quality and pricing, TCPA and consent, special ad categories, platform enforcement of lead gen, SEO at scale, payer transparency and the economics of intermediaries.",
 "clusters": {"Economics": ["V01", "V02", "V03"], "Rules": ["V04", "V05", "V06"], "Operations": ["V07", "V08", "V09"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Lead pricing, quality and buyer churn", "Lead economics", "Cost per lead, lead quality disputes, shared vs exclusive leads, buyer churn.", ["cost per lead", "lead quality", "shared leads", "exclusive leads", "lead price", "churn", "refund leads", "bad leads"]),
  T("V02", "Affiliate and comparison economics", "Affiliate", "Commission changes, affiliate program cuts, comparison site rankings, payouts.", ["affiliate", "commission", "payout", "comparison site", "program cut", "cpa network", "publisher"]),
  T("V03", "Programmatic SEO and content at scale", "Scale SEO", "Templated pages, city pages, AI content, site reputation abuse, scaled content policy.", ["programmatic seo", "city pages", "templated", "ai content", "site reputation abuse", "scaled content", "helpful content", "parasite"]),
  T("V04", "TCPA, consent and call generation", "Consent", "Consent language, one to one consent history, lead forms, call transfers, litigation.", ["tcpa", "consent", "one to one", "lead form", "call transfer", "litigation", "ftsa", "dnc"]),
  T("V05", "Platform enforcement of lead gen", "Enforcement", "Google Ads lead gen rules, Meta special ad categories, payer transparency, LSA rules for lead resale.", ["google ads policy", "lead gen ads", "special ad category", "payer name", "advertiser verification", "meta housing", "credit ads", "disapproved"]),
  T("V06", "Sector rules for intermediaries", "Sector rules", "Medicare TPMO, mortgage lead rules, addiction treatment brokering, legal referral rules, insurance lead rules.", ["tpmo", "medicare leads", "mortgage leads", "patient brokering", "referral fee", "insurance leads", "cms", "state rules"]),
  T("V07", "Marketplace platforms and their fee changes", "Platforms", "Angi, Thumbtack, Zillow, Yelp, Indeed, Zocdoc and other intermediaries changing fees or models.", ["angi", "thumbtack", "zillow", "yelp", "indeed", "zocdoc", "fees", "model change", "marketplace"]),
  T("V08", "Data, dedupe and lead tech", "Lead tech", "Lead distribution software, verification, fraud, ping post, CRMs.", ["ping post", "lead distribution", "verification", "fraud", "boberdoo", "leadconduit", "trustedform", "jornaya"]),
  T("V09", "Trust, transparency and disclosure", "Disclosure", "Payer disclosure, 'we are not a...' footers, review provenance, INFORM Act, advertorial labels.", ["disclosure", "we are not", "sponsored", "advertorial", "inform act", "transparency", "who pays", "review provenance"]),
  OTHER()],
 "sun": {"trade_press": ["leadscon (content)", "performancein.com", "adexchanger.com (lead gen)", "insurancejournal.com (lead gen)", "housingwire.com (lead gen)", "searchengineland.com (affiliate)"], "newsletters": ["LeadsCon newsletter", "Affiliate Summit briefings", "PerformanceIN weekly"], "platform_voices": ["Google Ads policy change log", "Meta business help (special ad categories)", "TrustedForm and Jornaya blogs", "FCC and FTC press releases"], "podcasts": ["Lead Generation World", "Affiliate Marketing podcast (Affiliate Summit)"]},
 "moon": {"subreddits": ["r/Affiliatemarketing", "r/PPC (lead gen threads)", "r/juststart", "r/leadgeneration", "r/InsuranceAgent (lead threads)", "r/realtors (lead threads)"], "forums": ["AffiliateFix", "STM Forum (public pages)", "BlackHatWorld (lead gen sections)", "Warrior Forum"], "discord_discovery": ["disboard tags: affiliate-marketing, lead-generation, cpa-marketing"], "telegram_discovery": ["TGStat 'Sales' affiliate and lead channels"], "practitioner_social": ["Lead gen operators' public posts (curated only)"]},
 "nilometer": ["Angi, Zillow, Yelp, LendingTree, EverQuote, MediaAlpha, QuinStreet, SelectQuote quarterly results", "FCC TCPA orders and court rulings", "FTC lead gen and impersonation actions", "CMS TPMO rule status", "Google Ads transparency and payer disclosure rollout notes", "IAB and Performance Marketing Association affiliate surveys", "Litigation trackers for TCPA class actions"],
 "standing_questions": ["Where is lead value migrating between platforms, marketplaces and direct?", "Which consent and disclosure rules are being enforced now, and what did courts change?", "What are lead gen operators asking about that the trade press ignores?", "Which scaled SEO patterns are being punished this quarter?", "How are the big intermediaries changing fees, and what does that do to buyers?"]})

NOMES.append({
 "id": "financial-services", "name": "Financial Services and Fintech Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Lenders, BNPL and lease to own, banks and credit unions, insurance, brokers, crypto and fintech apps: advertising under Reg Z and UDAAP, platform financial verification, app store loan rules, credit special categories, deposit claims, fintech partnerships and the compliance labor market.",
 "clusters": {"Acquisition": ["V01", "V02", "V03"], "Rules": ["V04", "V05", "V06", "V07"], "Market": ["V08", "V09", "V10"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Paid media under financial policies", "Financial paid", "Google financial products certification, Meta credit category and verification, TikTok financial entry rules, crypto ad rules.", ["financial products certification", "meta credit", "special ad category", "verification", "tiktok financial", "crypto ads", "disapproved", "google ads finance"]),
  T("V02", "Search, content and AI answers for money queries", "Finance search", "YMYL content, comparison sites, AI Overviews for rates and products, affiliate money sites.", ["ymyl", "personal finance seo", "nerdwallet", "comparison", "ai overview", "rates", "content", "affiliate"]),
  T("V03", "App acquisition and store rules for finance apps", "Finance apps", "App Store 3.2.2, Play personal loans policy, APR caps in listings, app campaigns.", ["app store", "google play", "personal loans policy", "apr", "36%", "app campaign", "aso", "loan app"]),
  T("V04", "Reg Z, UDAAP and disclosure enforcement", "Disclosures", "Triggering terms, APR disclosure, deceptive fees, CFPB and state actions.", ["reg z", "apr disclosure", "udaap", "cfpb", "junk fees", "triggering terms", "enforcement", "consent order"]),
  T("V05", "BNPL, lease to own and alternative credit", "BNPL and LTO", "Rules for BNPL and lease purchase advertising, credit reporting, state RTO law.", ["bnpl", "buy now pay later", "lease to own", "rent to own", "rto", "alternative credit", "no credit needed", "credit reporting"]),
  T("V06", "Deposits, fintech partnerships and FDIC claims", "Deposits", "Bank partner models, FDIC misrepresentation rule, pass through insurance, fintech failures.", ["fdic", "bank partner", "baas", "pass through", "insured", "synapse", "fintech bank", "deposit insurance"]),
  T("V07", "Privacy, data and open banking", "Data rules", "1033 open banking, data sharing, pixels on applications, GLBA, state privacy.", ["1033", "open banking", "glba", "pixel", "data sharing", "privacy", "application data", "consent"]),
  T("V08", "Rates, demand and the credit cycle", "Credit cycle", "Interest rates, loan demand, delinquencies, tightening and what it does to marketing.", ["interest rates", "fed", "delinquencies", "tightening", "loan demand", "credit cycle", "origination volume"]),
  T("V09", "Crypto, trading and speculative products", "Crypto", "Crypto marketing rules, influencer promotion, trading app ads, gamification.", ["crypto", "trading app", "influencer", "gamification", "sec", "promotion", "token", "exchange ads"]),
  T("V10", "Compliance operations and marketing review", "Compliance ops", "Marketing compliance review, AI in compliance, complaint management, vendor management.", ["compliance review", "marketing compliance", "complaints", "vendor management", "ai compliance", "review process", "approval"]),
  OTHER()],
 "sun": {"trade_press": ["americanbanker.com", "paymentsdive.com", "bankingdive.com", "fintechfutures.com", "thefinancialbrand.com", "housingwire.com", "insurancejournal.com", "pymnts.com"], "newsletters": ["Fintech Business Weekly", "This Week in Fintech", "The Financial Brand newsletter"], "platform_voices": ["Google Ads financial products policy pages", "Meta business help (credit ads)", "Apple App Review updates", "CFPB newsroom", "FDIC and OCC press releases"], "podcasts": ["Fintech Takes", "Breaking Banks", "Bank On It"]},
 "moon": {"subreddits": ["r/fintech", "r/personalfinance (consumer side, demand evidence)", "r/CreditCards (consumer side)", "r/Banking", "r/loanofficers", "r/InsuranceAgent", "r/CryptoMarkets (promotion evidence)"], "forums": ["Bankers Online forums", "Compliance forums (public pages)", "Bogleheads (consumer side)"], "discord_discovery": ["disboard tags: fintech, finance, crypto, trading"], "telegram_discovery": ["TGStat finance and crypto promotion channels (set filter expected)"], "practitioner_social": ["Fintech marketers' public posts (curated only)"]},
 "nilometer": ["CFPB enforcement actions, consent orders and complaint database", "FDIC, OCC and Federal Reserve enforcement", "Federal Reserve rate decisions and Senior Loan Officer Survey", "NY Fed Household Debt and Credit report", "Affirm, Klarna, SoFi, Upstart, LendingTree, Block quarterly results", "State attorney general lending actions", "App store policy change logs", "Google and Meta financial policy change logs"],
 "standing_questions": ["What can a lender or fintech lawfully say and where, this quarter?", "Where is acquisition for credit and deposit products moving between search, apps, partners and affiliates?", "What are financial marketers asking about that the trade press is not covering?", "Which disclosure and fee rules are actually enforced, and against whom?", "How is the credit cycle changing budgets and offers?"]})

NOMES.append({
 "id": "real-estate-housing", "name": "Real Estate, Housing and Mortgage Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Brokerages, agents, teams, property managers, builders and mortgage originators: portals and lead fees, agent marketing, fair housing advertising rules, commission changes, IDX and listing feeds, mortgage lead rules and the housing cycle.",
 "clusters": {"Acquisition": ["V01", "V02", "V03"], "Rules": ["V04", "V05"], "Market": ["V06", "V07", "V08"], "Operations": ["V09"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Portals, Zillow and lead fees", "Portals", "Zillow Premier Agent, Flex, Realtor.com, Homes.com, referral fees and portal policy.", ["zillow", "premier agent", "flex", "realtor.com", "homes.com", "portal", "referral fee", "lead fee"]),
  T("V02", "Agent and team marketing", "Agent marketing", "Personal brand, video, farming, SOI, CRMs, geographic pages, GBP for agents.", ["agent marketing", "personal brand", "video", "farming", "sphere", "crm", "gbp", "neighborhood pages", "open house"]),
  T("V03", "Paid media for housing", "Housing paid", "Google Ads for real estate, Meta housing special category, targeting limits.", ["google ads real estate", "meta housing", "special ad category", "targeting", "lead ads", "cpl real estate", "youtube ads"]),
  T("V04", "Fair housing advertising rules", "Fair housing", "HUD advertising guidance, protected class language, discriminatory targeting enforcement.", ["fair housing", "hud", "protected class", "discriminatory", "targeting", "advertising rule", "complaint"]),
  T("V05", "Mortgage advertising and lead rules", "Mortgage rules", "Reg Z mortgage rules, MAP Rule, NMLS display, trigger leads, RESPA marketing agreements.", ["reg z", "map rule", "nmls", "trigger leads", "respa", "mortgage ads", "loan officer marketing", "co-marketing"]),
  T("V06", "Commissions, settlements and brokerage models", "Commissions", "NAR settlement effects, buyer agreements, flat fee and discount models.", ["commission", "nar settlement", "buyer agreement", "flat fee", "discount brokerage", "compensation", "mls rules"]),
  T("V07", "Housing cycle: rates, inventory and demand", "Housing cycle", "Mortgage rates, inventory, prices, affordability and what they do to marketing.", ["mortgage rates", "inventory", "home prices", "affordability", "housing market", "demand", "listings down"]),
  T("V08", "Proptech, AI and MLS data", "Proptech", "AI in listings and descriptions, IDX changes, MLS data rules, CRMs and automation.", ["proptech", "ai listing", "idx", "mls", "listing descriptions", "automation", "chatbot", "data feed"]),
  T("V09", "Property management and rental marketing", "Rentals", "Rental listing syndication, screening rules, junk fee laws, property manager marketing.", ["property management", "rental listings", "syndication", "screening", "junk fees", "tenant", "apartments.com", "zillow rentals"]),
  OTHER()],
 "sun": {"trade_press": ["inman.com", "housingwire.com", "realestatenews.com", "therealdeal.com", "nationalmortgagenews.com", "multifamilydive.com", "rismedia.com"], "newsletters": ["Inman Headlines", "HousingWire Daily", "Real Estate News briefings"], "platform_voices": ["Zillow Group newsroom and Premier Agent updates", "NAR announcements", "HUD press releases", "Meta business help (housing ads)"], "podcasts": ["Real Estate Rockstars", "HousingWire Daily", "The Tom Ferry Podcast Experience"]},
 "moon": {"subreddits": ["r/realtors", "r/RealEstate (consumer side)", "r/loanofficers", "r/PropertyManagement", "r/CommercialRealEstate"], "forums": ["ActiveRain", "BiggerPockets forums", "Lab Coat Agents (public pages)"], "discord_discovery": ["disboard tags: real-estate, realtor, mortgage"], "telegram_discovery": ["TGStat real estate channels"], "practitioner_social": ["Agents' and loan officers' public posts (curated only)"]},
 "nilometer": ["Zillow, Compass, eXp, Anywhere, Redfin, Rocket, UWM quarterly results", "NAR existing home sales and member profile", "Freddie Mac PMMS mortgage rates", "MBA applications survey", "HUD fair housing enforcement actions", "CFPB mortgage enforcement", "Census housing starts and permits", "Realtor.com and Redfin market reports (B2)"],
 "standing_questions": ["Where are buyers and sellers finding agents and lenders now, and what do portals charge for it?", "Which fair housing and mortgage advertising rules are being enforced?", "What are agents and loan officers asking about that the trade press ignores?", "What did commission changes do to marketing spend and messaging?", "How is the housing cycle changing lead volume and cost?"]})

NOMES.append({
 "id": "automotive-retail", "name": "Automotive Retail and Aftermarket Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Dealers and dealer groups, repair and service shops, parts and accessories retailers: inventory advertising, dealer websites and vendors, pricing disclosure rules, EV transition, service marketing, reviews and consolidation.",
 "clusters": {"Acquisition": ["V01", "V02", "V03"], "Rules": ["V04", "V05"], "Market": ["V06", "V07", "V08"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Inventory advertising: VLA, Meta and marketplaces", "Inventory ads", "Vehicle listing ads, Meta automotive inventory ads, Cars.com, Autotrader, CarGurus fees.", ["vehicle listing ads", "vla", "inventory ads", "cars.com", "autotrader", "cargurus", "marketplace fees", "feed"]),
  T("V02", "Dealer websites, vendors and the digital retailing stack", "Dealer web", "Website vendors, digital retailing tools, chat, trade tools, CDK and DMS outages.", ["dealer website", "dealer.com", "digital retailing", "chat", "trade in tool", "cdk", "dms", "vendor"]),
  T("V03", "Local search, reviews and service marketing", "Local and service", "GBP for dealers and shops, reviews, service department marketing, fixed ops.", ["gbp", "reviews", "service marketing", "fixed ops", "map pack", "shop marketing", "recall marketing"]),
  T("V04", "Pricing disclosure and dealer advertising rules", "Pricing rules", "FTC CARS rule history, state dealer advertising rules, doc fees, add ons, junk fees.", ["cars rule", "ftc", "dealer advertising", "doc fee", "add ons", "junk fees", "attorney general", "advertised price"]),
  T("V05", "Consumer protection: financing, warranties and repair", "Consumer rules", "Reg Z auto, spot delivery, warranty claims, repair shop rules, right to repair.", ["reg z", "auto financing", "spot delivery", "warranty", "repair rules", "right to repair", "consumer complaint"]),
  T("V06", "EV transition and OEM programs", "EV and OEM", "EV demand swings, incentives, OEM co-op and compliance programs, direct sales.", ["ev", "electric vehicle", "incentive", "oem program", "co-op", "direct sales", "tesla", "dealer model"]),
  T("V07", "Consolidation and dealer groups", "Consolidation", "Group acquisitions, valuations, public groups, marketing centralization.", ["acquisition", "dealer group", "buy sell", "valuation", "lithia", "autonation", "consolidation", "centralized marketing"]),
  T("V08", "Parts, accessories and aftermarket e-commerce", "Aftermarket", "Parts e-commerce, fitment data, marketplaces, tariffs on parts.", ["parts", "aftermarket", "fitment", "ebay motors", "amazon parts", "tariff", "accessories", "catalog"]),
  OTHER()],
 "sun": {"trade_press": ["autonews.com", "cbtnews.com", "dealermarketing.com", "autoremarketing.com", "ratchetandwrench.com", "aftermarketnews.com", "wardsauto.com"], "newsletters": ["Automotive News Daily", "CBT News Daily", "Kerrigan Advisors Blue Sky Report"], "platform_voices": ["Google Ads blog (vehicle listing ads)", "Meta automotive inventory ads help", "Cars Commerce newsroom", "NADA announcements"], "podcasts": ["CBT News", "Car Dealership Guy", "Ratchet and Wrench Radio"]},
 "moon": {"subreddits": ["r/askcarsales", "r/CarSalesTraining", "r/MechanicAdvice (consumer side)", "r/AutoDetailing", "r/Autobody", "r/smallbusiness (shop threads)"], "forums": ["DealerRefresh", "iATN (public pages)", "Garage Journal", "Auto Body forums"], "discord_discovery": ["disboard tags: automotive, cars, car-sales, mechanics"], "telegram_discovery": ["TGStat automotive channels"], "practitioner_social": ["Dealer marketers' and shop owners' public posts (curated only)"]},
 "nilometer": ["Lithia, AutoNation, Penske, Group 1, Sonic, Carvana, CarMax quarterly results", "Cars Commerce and CarGurus quarterly results", "NADA Data (annual) and dealership financial profiles", "Cox Automotive forecasts and Kelley Blue Book pricing", "FTC and state attorney general dealer actions", "BLS auto retail and repair employment", "Tariff and EV incentive notices"],
 "standing_questions": ["Where are car buyers and service customers finding dealers and shops now, and what do marketplaces charge?", "Which pricing and financing advertising rules are being enforced?", "What are dealer marketers and shop owners asking about that the trade press ignores?", "What is the EV swing doing to inventory advertising and messaging?", "How is consolidation changing dealer marketing budgets and vendors?"]})

NOMES.append({
 "id": "education", "name": "Education Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Colleges, K12 and private schools, bootcamps, tutoring and course sellers: enrollment marketing, claims and Title IV rules, minors and privacy, AI in education, the enrollment cliff and program viability.",
 "clusters": {"Enrollment": ["V01", "V02", "V03"], "Rules": ["V04", "V05"], "Market": ["V06", "V07", "V08"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Enrollment marketing and lead funnels", "Enrollment", "Inquiry to enrollment funnels, CRMs, agencies and OPMs, cost per enrollment.", ["enrollment marketing", "inquiry", "funnel", "cost per enrollment", "opm", "slate", "crm", "lead"]),
  T("V02", "Paid media for education", "Education paid", "Google Ads education rules, Meta age targeting, YouTube, TikTok for students.", ["google ads education", "meta ads school", "age targeting", "youtube", "tiktok students", "cpl education", "lead ads"]),
  T("V03", "Search, rankings and content for programs", "Program search", "Program pages, rankings sites, AI Overviews for programs, review sites.", ["program pages", "rankings", "us news", "niche", "ai overview", "seo higher ed", "content", "reviews"]),
  T("V04", "Claims, misrepresentation and Title IV rules", "Claims rules", "Misrepresentation rules, job placement claims, borrower defense, FTC bootcamp actions, incentive compensation.", ["misrepresentation", "title iv", "job placement", "borrower defense", "ftc", "bootcamp", "incentive compensation", "gainful employment"]),
  T("V05", "Minors, privacy and student data", "Student privacy", "COPPA, FERPA, state student privacy laws, age gates, ad tags on school sites.", ["coppa", "ferpa", "student privacy", "age gate", "pixel", "minors", "consent", "edtech privacy"]),
  T("V06", "Enrollment cliff, closures and program cuts", "Enrollment cliff", "Demographic decline, closures, program viability, mergers.", ["enrollment cliff", "closure", "program cuts", "merger", "demographic", "decline", "budget"]),
  T("V07", "AI in teaching, admissions and marketing", "AI in education", "AI tutors, AI in admissions, chatbots for students, AI content rules.", ["ai tutor", "chatbot", "admissions ai", "ai policy", "generative ai", "ai content", "student ai"]),
  T("V08", "Online learning, course sellers and creators", "Online learning", "Course platforms, creator courses, bootcamps, certificates, MOOCs.", ["course", "udemy", "coursera", "bootcamp", "certificate", "online learning", "creator course", "cohort"]),
  OTHER()],
 "sun": {"trade_press": ["insidehighered.com", "highereddive.com", "chronicle.com", "edsurge.com", "k12dive.com", "universitybusiness.com", "classcentral.com (report)"], "newsletters": ["Higher Ed Dive Daily", "Inside Higher Ed briefings", "EdSurge Weekly"], "platform_voices": ["Google Ads education policy", "Meta business help (education ads)", "Department of Education press releases", "Coursera and Udemy newsrooms"], "podcasts": ["Higher Ed Marketing Lab", "Enrollify", "The EdUp Experience"]},
 "moon": {"subreddits": ["r/highereducation", "r/Professors (workplace voice)", "r/Teachers", "r/learnprogramming (bootcamp evidence)", "r/ApplyingToCollege (consumer side)"], "forums": ["Enrollify community (public pages)", "Higher ed marketing groups (public pages)", "College Confidential (consumer side)"], "discord_discovery": ["disboard tags: education, students, tutoring, edtech"], "telegram_discovery": ["TGStat education channels"], "practitioner_social": ["Enrollment marketers' public posts (curated only)"]},
 "nilometer": ["National Student Clearinghouse enrollment reports", "IPEDS and Department of Education data", "Department of Education enforcement and borrower defense findings", "FTC bootcamp and for profit actions", "Coursera, Chegg, Stride, Grand Canyon Education quarterly results", "RNL and EAB enrollment surveys", "Common App and application volume reports", "BLS education employment"],
 "standing_questions": ["Where are prospective students discovering programs now, and what does an enrollment cost by channel?", "Which claims and marketing rules are being enforced against schools and bootcamps?", "What are enrollment marketers asking about that the trade press ignores?", "What is the enrollment cliff doing to budgets and program marketing?", "Is AI changing how students choose, or only how schools talk?"]})

NOMES.append({
 "id": "nonprofit-political", "name": "Nonprofit, Advocacy and Political Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Charities, advocacy organizations, campaigns, faith organizations and associations: donor acquisition, Ad Grants, issue and political ad rules, charity disclosure law, platform political ad policy, email and SMS deliverability and donor data.",
 "clusters": {"Acquisition": ["V01", "V02", "V03"], "Rules": ["V04", "V05"], "Market": ["V06", "V07", "V08"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "Donor acquisition and fundraising channels", "Fundraising", "Digital fundraising, Giving Tuesday, recurring giving, peer to peer, donor retention.", ["fundraising", "donor acquisition", "giving tuesday", "recurring", "peer to peer", "donor retention", "year end"]),
  T("V02", "Google Ad Grants and paid media for causes", "Cause paid", "Ad Grants rules, Meta nonprofit tools, YouTube for nonprofits, cost per donation.", ["ad grants", "google grants", "meta nonprofit", "cost per donation", "youtube nonprofit", "paid social", "donation ads"]),
  T("V03", "Email, SMS and deliverability", "Email and SMS", "Deliverability, list health, SMS consent for causes, ActionKit, EveryAction and CRMs.", ["deliverability", "email", "sms", "consent", "list", "everyaction", "actionkit", "crm", "spam"]),
  T("V04", "Political and issue ad rules", "Political ads", "Platform political ad policies, disclaimers, FEC rules, state deepfake laws, EU TTPA.", ["political ads", "issue ads", "disclaimer", "fec", "paid for by", "deepfake", "ttpa", "authorization", "ad policy"]),
  T("V05", "Charity disclosure, registration and solicitation law", "Charity rules", "State registration, disclosure statements, cause marketing rules, FTC charity actions.", ["charity registration", "disclosure statement", "solicitation", "cause marketing", "commercial co-venturer", "ftc charity", "attorney general"]),
  T("V06", "Donor data, privacy and tracking", "Donor data", "Pixels on donation pages, donor privacy, data brokers, platform data changes.", ["pixel", "donor data", "privacy", "tracking", "data broker", "consent", "donation page"]),
  T("V07", "Platforms, algorithms and organic reach for causes", "Organic reach", "Reach changes, Meta political content limits, TikTok and YouTube for causes, communities.", ["organic reach", "political content", "algorithm", "tiktok nonprofit", "youtube", "community", "reach decline"]),
  T("V08", "Funding climate and sector economics", "Funding climate", "Giving trends, grants cuts, membership decline, sector layoffs.", ["giving usa", "grants", "funding cuts", "membership", "layoffs", "donations down", "philanthropy"]),
  OTHER()],
 "sun": {"trade_press": ["chronicle of philanthropy", "nonprofitpro.com", "thenonprofittimes.com", "campaignsandelections.com", "nonprofitquarterly.org", "techsoup blog"], "newsletters": ["Chronicle of Philanthropy briefings", "Nonprofit Tech for Good", "Campaigns and Elections newsletter"], "platform_voices": ["Google for Nonprofits blog", "Meta business help (issue, electoral or political ads)", "FEC press releases", "Candid blog"], "podcasts": ["The Nonprofit Hive", "Nonprofits Are Messy", "Campaign HQ"]},
 "moon": {"subreddits": ["r/nonprofit", "r/fundraising", "r/PoliticalCampaigns", "r/Sysadmin (nonprofit threads, rare)"], "forums": ["TechSoup forums", "Nonprofit Happy Hour (public pages)", "Progressive Exchange (public pages)"], "discord_discovery": ["disboard tags: nonprofit, charity, activism, politics"], "telegram_discovery": ["TGStat politics and activism channels (set filter expected)"], "practitioner_social": ["Nonprofit marketers' public posts (curated only)"]},
 "nilometer": ["Giving USA annual report", "M+R Benchmarks (digital fundraising)", "Blackbaud Institute charitable giving reports", "FEC filings and platform political ad libraries (EU TTPA status)", "State attorney general charity actions", "IRS exempt organization data", "Meta and Google political ad policy change logs", "BLS nonprofit employment"],
 "standing_questions": ["Where are donors and supporters being acquired now, and at what cost?", "Which political and charity advertising rules are being enforced, and by whom?", "What are nonprofit marketers asking about that the sector press ignores?", "What did platform political content limits do to organic reach for causes?", "How is the funding climate changing budgets and channel mix?"]})

NOMES.append({
 "id": "hospitality-travel", "name": "Hospitality, Travel and Events Marketing", "nome": "Client vertical pack (OmegaWeapon)", "flagship": False,
 "scope": "Hotels, restaurants, attractions, tour operators, ticket sellers and event venues: OTAs and direct booking, Google travel surfaces, reviews, junk fee rules, ticketing law, AI trip planning and demand swings.",
 "clusters": {"Acquisition": ["V01", "V02", "V03"], "Rules": ["V04", "V05"], "Market": ["V06", "V07", "V08"], "Other": ["V00"]},
 "taxonomy": [
  T("V01", "OTAs, metasearch and direct booking", "OTAs and direct", "Booking, Expedia, Airbnb fees, Google Hotel Ads, direct booking strategy, parity.", ["ota", "booking.com", "expedia", "airbnb", "hotel ads", "metasearch", "direct booking", "parity", "commission"]),
  T("V02", "Google travel surfaces and local", "Google travel", "Hotel and things to do surfaces, GBP for restaurants and venues, reservations integrations, Maps.", ["google hotels", "things to do", "gbp", "reserve with google", "maps", "local", "restaurant profile", "menu"]),
  T("V03", "Reviews and reputation in travel", "Reviews", "TripAdvisor, Google, Yelp reviews, fake review enforcement, responses.", ["tripadvisor", "reviews", "yelp", "fake reviews", "reputation", "review response", "ratings"]),
  T("V04", "Junk fees, drip pricing and ticketing law", "Fees and tickets", "FTC fee rule for lodging and tickets, BOTS Act, resale rules, resort fees, state ticket laws.", ["junk fees", "drip pricing", "resort fee", "ftc fee rule", "bots act", "ticket resale", "all in pricing", "ticketing law"]),
  T("V05", "Platform and consumer rules for travel", "Travel rules", "Cancellation and refund rules, ADA and EAA for booking sites, alcohol advertising, minors.", ["refund", "cancellation", "ada", "eaa", "accessibility", "alcohol ads", "consumer protection", "dot rules"]),
  T("V06", "AI trip planning and agentic booking", "AI travel", "AI planners, ChatGPT and Gemini trip planning, agents booking, content for AI answers.", ["ai trip planning", "agentic booking", "chatgpt travel", "gemini", "ai itinerary", "ai answers", "agent booking"]),
  T("V07", "Demand swings, events and seasonality", "Demand", "Travel demand, events calendars, weather, economic mood, group business.", ["demand", "occupancy", "seasonality", "events", "conference", "group business", "travel slowdown", "bookings down"]),
  T("V08", "Restaurant marketing and delivery platforms", "Restaurants", "Delivery apps and fees, loyalty, menu and pricing, restaurant paid and social.", ["doordash", "uber eats", "delivery fees", "loyalty", "menu pricing", "restaurant marketing", "reservations", "tiktok restaurant"]),
  OTHER()],
 "sun": {"trade_press": ["skift.com", "phocuswire.com", "hotelnewsnow.com (CoStar)", "restaurantbusinessonline.com", "nrn.com", "pollstar.com", "travelweekly.com", "hospitalitynet.org"], "newsletters": ["Skift Daily", "PhocusWire Daily", "Restaurant Business Daily"], "platform_voices": ["Google travel and Hotel Ads updates", "Booking.com Partner Hub", "Expedia Partner Central", "TripAdvisor for Business", "OpenTable and Toast blogs"], "podcasts": ["Skift Podcast", "No Vacancy", "Restaurant Unstoppable"]},
 "moon": {"subreddits": ["r/hotels (operator threads)", "r/restaurantowners", "r/BarOwners", "r/Airbnb (host side)", "r/travelagents", "r/eventplanning"], "forums": ["Hotel management forums (public pages)", "Airbnb Community Center", "Restaurant owner groups (public pages)"], "discord_discovery": ["disboard tags: travel, hospitality, restaurant, events"], "telegram_discovery": ["TGStat travel channels (set filter expected)"], "practitioner_social": ["Hospitality marketers' public posts (curated only)"]},
 "nilometer": ["STR and CoStar occupancy and ADR data", "Booking Holdings, Expedia, Airbnb, Marriott, Hilton quarterly results", "DoorDash and Uber quarterly results", "National Restaurant Association reports", "FTC fee rule enforcement and BOTS Act actions", "TSA throughput and DOT air travel data", "Live Nation and event industry filings", "BLS leisure and hospitality employment"],
 "standing_questions": ["Where are travelers and diners booking now, and what do intermediaries charge?", "Which fee and ticketing rules are being enforced this quarter?", "What are operators asking about that the travel trade press ignores?", "Is AI trip planning moving bookings, or only talk?", "How is demand shifting by segment, and what does it do to spend?"]})

ids = {n["id"] for n in NOMES}
d["nomes"] = [n for n in d["nomes"] if n["id"] not in ids] + NOMES
d["_omega"] = "Horus's ten media nomes plus OmegaWeapon's twelve client vertical packs. A run picks the nome that matches the target's archetype (assets/archetypes.json); the digital-marketing nome is also the Agency lens's industry read for any target."
P.write_text(json.dumps(d, ensure_ascii=False, indent=1), encoding="utf-8")
print("nomes:", len(d["nomes"]), [n["id"] for n in d["nomes"]])
