/* Split a Severance single file build into the source tree. Node 22, no packages.
     node tools/extract.mjs <Severance.html> [--code]
   Always writes data/suite.js and data/atlas-<key>.js (the embedded JSON, each as window.__SEV_SUITE__ / window.__SEV_ATLAS__[key]
   parsed from a string literal, which V8 parses faster than an object literal) and data/MANIFEST.json (sizes and sha256).
   With --code it also writes the stylesheet (app.css) and the app script split at its module comments into src/ (one time; the
   split files are edited by hand afterwards). */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const [file, ...flags] = process.argv.slice(2);
if (!file) { console.error('usage: node tools/extract.mjs <Severance.html> [--code]'); process.exit(2); }
const html = fs.readFileSync(file, 'utf8');
const out = (rel, text) => { const p = path.join(ROOT, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, text); return text.length; };

/* The suite's counties and ZIPs are arrays of objects that repeat the same nested keys (1,127 ZIPs with 130 leaf paths, 254 counties
   with 551). They are stored columnar: {__packed: 1, cols: ['acs.married', ...], rows: [[...], ...]}, a leaf missing from an object as
   the string "\u0000". src/00_core.js unpacks them (unpackRows) before anything reads them. The round trip is checked here, key order
   included, so the app sees exactly the objects of the original file. Saves about 2.9 MB. */
const MISSING = '\u0000';
const isObj = v => v && typeof v === 'object' && !Array.isArray(v);
const flatten = (o, pre, out) => { for (const k of Object.keys(o)) { const v = o[k]; const p = pre ? pre + '.' + k : k; if (isObj(v) && Object.keys(v).length) flatten(v, p, out); else out.push([p, v]); } return out; };
/* column order: a topological merge of every object's own path order (Kahn, ties by first appearance), so each unpacked object gets its
   keys back in its original order even when objects carry different key sets */
function mergeOrder(seqs) { const first = new Map(), next = new Map(), indeg = new Map(); let n = 0; for (const q of seqs) for (const p of q) if (!first.has(p)) { first.set(p, n++); next.set(p, new Set()); indeg.set(p, 0); } for (const q of seqs) for (let i = 1; i < q.length; i++) { const a = q[i - 1], b = q[i]; if (!next.get(a).has(b)) { next.get(a).add(b); indeg.set(b, indeg.get(b) + 1); } } const ready = [...first.keys()].filter(p => !indeg.get(p)).sort((a, b) => first.get(a) - first.get(b)); const out = []; while (ready.length) { const p = ready.shift(); out.push(p); for (const b of next.get(p)) { indeg.set(b, indeg.get(b) - 1); if (!indeg.get(b)) { let i = 0; while (i < ready.length && first.get(ready[i]) < first.get(b)) i++; ready.splice(i, 0, b); } } } return out.length === first.size ? out : null; }
function packRows(arr) { const flat = arr.map(o => flatten(o, '', [])); const cols = mergeOrder(flat.map(f => f.map(x => x[0]))) || [...new Set(flat.flatMap(f => f.map(x => x[0])))]; const ci = {}; cols.forEach((p, i) => { ci[p] = i; }); const rows = flat.map(f => { const r = new Array(cols.length).fill(MISSING); f.forEach(([p, v]) => { r[ci[p]] = v; }); return r; }); return { __packed: 1, cols, rows }; }
function unpackRows(p) { const paths = p.cols.map(c => c.split('.')); return p.rows.map(r => { const o = {}; for (let i = 0; i < paths.length; i++) { const v = r[i]; if (v === MISSING) continue; const ks = paths[i]; let t = o; for (let j = 0; j < ks.length - 1; j++) t = t[ks[j]] || (t[ks[j]] = {}); t[ks[ks.length - 1]] = v; } return o; }); }
function packSuite(json) {
  const d = JSON.parse(json);
  for (const k of ['zctas', 'counties']) {
    const packed = packRows(d[k]); const back = unpackRows(packed);
    d[k].forEach((o, i) => { if (JSON.stringify(o) !== JSON.stringify(back[i])) { console.error(`${k}[${i}] does not round trip; stored unpacked`); packed.bad = true; } });
    if (!packed.bad) d[k] = packed;
  }
  return JSON.stringify(d);
}
const manifest = {};
for (const m of html.matchAll(/<script type="application\/json" id="([^"]+)">/g)) {
  const a = m.index + m[0].length, b = html.indexOf('</script>', a); let json = html.slice(a, b); const original = json;
  JSON.parse(json);
  const id = m[1]; let rel, js;
  if (id === 'suite-data') json = packSuite(json);
  else json = JSON.stringify(JSON.parse(json));   // compact separators; every value is unchanged
  if (id === 'suite-data') { rel = 'data/suite.js'; js = `/* Severance suite data (counties, ZIPs, metros, state series, models). Generated by tools/extract.mjs; do not edit. */\nwindow.__SEV_SUITE__ = JSON.parse(${JSON.stringify(json)});\n`; }
  else if (id.startsWith('atlas-')) { const k = id.slice(6); rel = `data/atlas-${k}.js`; js = `/* Severance Metro Atlas, ${k}: block group geometry and values. Generated by tools/extract.mjs; do not edit. */\n(window.__SEV_ATLAS__ = window.__SEV_ATLAS__ || {})[${JSON.stringify(k)}] = JSON.parse(${JSON.stringify(json)});\n`; }
  else continue;
  out(rel, js); manifest[id] = { file: rel, json_bytes: Buffer.byteLength(json), source_bytes: Buffer.byteLength(original), source_sha256: crypto.createHash('sha256').update(original).digest('hex') };
  console.log(rel, (js.length / 1e6).toFixed(2) + ' MB');
}
out('data/MANIFEST.json', JSON.stringify({ source: path.basename(file), extracted: new Date().toISOString().slice(0, 10), blobs: manifest }, null, 1) + '\n');
if (flags.includes('--code')) {
  const s0 = html.indexOf('<style>') + 7, s1 = html.indexOf('</style>');
  out('app.css', html.slice(s0, s1).trim() + '\n');
  const j0 = html.lastIndexOf('<script>') + 8, j1 = html.lastIndexOf('</script>');
  const js = html.slice(j0, j1);
  const lines = js.split('\n');
  const cuts = [[/^\/\* SEVERANCE core/, '00_core.js'], [/^\/\* Module 01:/, '20_m01_index.js'], [/^\/\* Module 02:/, '21_m02_ledger.js'], [/^\/\* Module 03:/, '22_m03_market.js'], [/^\/\* Module 04:/, '23_m04_signals.js'], [/^\/\* Module 05:/, '24_m05_econ.js'], [/^\/\* Module 06:/, '25_m06_lines.js'], [/^\/\* Module 07:/, '26_m07_paid.js'], [/^\/\* Module 08:/, '27_m08_supply.js'], [/^\/\* Module 09:/, '28_m09_timing.js'], [/^\/\* Module 10:/, '29_m10_desk.js'], [/^\/\* Module 11:/, '30_m11_compliance.js'], [/^\/\* Metro tabs/, '31_m12_metros.js'], [/^\/\* Module 13:/, '32_m13_atlas.js'], [/^\/\* Module 20:/, '39_m20_method.js'], [/^\/\* boot \*\//, '99_boot.js']];
  let cur = null, buf = [];
  const flush = () => { if (cur) out('src/' + cur, (cur === '00_core.js' ? '' : "'use strict';\n") + buf.join('\n').replace(/\n+$/, '') + '\n'); buf = []; };
  for (const ln of lines) { const c = cuts.find(([re]) => re.test(ln)); if (c) { flush(); cur = c[1]; } if (cur) buf.push(ln); }
  flush();
  const b0 = html.indexOf('<body>') + 6, b1 = html.indexOf('<script type="application/json"');
  out('tools/_body.html', html.slice(b0, b1).trim() + '\n');
  console.log('code split into src/, app.css, tools/_body.html');
}
