/* Split a Severance single file build into the source tree. Node 22, no packages.
     node tools/extract.mjs <Severance.html> [--code]
   Always writes data/suite.js and data/atlas-<key>.js (the embedded JSON, each as window.__SEV_SUITE__ / window.__SEV_ATLAS__[key]
   parsed from a string literal, which V8 parses faster than an object literal) and data/MANIFEST.json (sizes and sha256).
   With --code it also writes the stylesheet (app.css) and the app script split at its module comments into src/ (one time; the
   split files are edited by hand afterwards). */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const [file, ...flags] = process.argv.slice(2);
if (!file) { console.error('usage: node tools/extract.mjs <Severance.html> [--code]'); process.exit(2); }
const html = fs.readFileSync(file, 'utf8');
const out = (rel, text) => { const p = path.join(ROOT, rel); fs.mkdirSync(path.dirname(p), { recursive: true }); fs.writeFileSync(p, text); return text.length; };
const manifest = {};
for (const m of html.matchAll(/<script type="application\/json" id="([^"]+)">/g)) {
  const a = m.index + m[0].length, b = html.indexOf('</script>', a); const json = html.slice(a, b);
  JSON.parse(json);
  const id = m[1]; let rel, js;
  if (id === 'suite-data') { rel = 'data/suite.js'; js = `/* Severance suite data (counties, ZIPs, metros, state series, models). Generated by tools/extract.mjs; do not edit. */\nwindow.__SEV_SUITE__ = JSON.parse(${JSON.stringify(json)});\n`; }
  else if (id.startsWith('atlas-')) { const k = id.slice(6); rel = `data/atlas-${k}.js`; js = `/* Severance Metro Atlas, ${k}: block group geometry and values. Generated by tools/extract.mjs; do not edit. */\n(window.__SEV_ATLAS__ = window.__SEV_ATLAS__ || {})[${JSON.stringify(k)}] = JSON.parse(${JSON.stringify(json)});\n`; }
  else continue;
  out(rel, js); manifest[id] = { file: rel, json_bytes: Buffer.byteLength(json), sha256: crypto.createHash('sha256').update(json).digest('hex') };
  console.log(rel, (js.length / 1e6).toFixed(2) + ' MB');
}
out('data/MANIFEST.json', JSON.stringify({ source: path.basename(file), extracted: new Date().toISOString().slice(0, 10), blobs: manifest }, null, 1) + '\n');
if (flags.includes('--code')) {
  const s0 = html.indexOf('<style>') + 7, s1 = html.indexOf('</style>');
  out('app.css', html.slice(s0, s1).trim() + '\n');
  const j0 = html.lastIndexOf('<script>') + 8, j1 = html.lastIndexOf('</script>');
  const js = html.slice(j0, j1);
  const lines = js.split('\n');
  const cuts = [[/^\/\* SEVERANCE core/, '00_core.js'], [/^\/\* Module 01:/, '20_m01_index.js'], [/^\/\* Module 02:/, '21_m02_ledger.js'], [/^\/\* Module 03:/, '22_m03_market.js'], [/^\/\* Module 04:/, '23_m04_signals.js'], [/^\/\* Module 05:/, '24_m05_econ.js'], [/^\/\* Module 06:/, '25_m06_lines.js'], [/^\/\* Module 07:/, '26_m07_paid.js'], [/^\/\* Module 08:/, '27_m08_supply.js'], [/^\/\* Module 09:/, '28_m09_timing.js'], [/^\/\* Module 10:/, '29_m10_desk.js'], [/^\/\* Module 11:/, '30_m11_compliance.js'], [/^\/\* Metro tabs/, '31_m12_metros.js'], [/^\/\* Module 13:/, '32_m13_atlas.js'], [/^\/\* Module 20:/, '39_m20_method.js'], [/^\/\* boot \*\//, '99_boot.js']];
  let cur = null, buf = [];
  const flush = () => { if (cur) out('src/' + cur, (cur === '00_core.js' ? '' : "'use strict';\n") + buf.join('\n').replace(/\n+$/, '') + '\n'); buf = []; };
  for (const ln of lines) { const c = cuts.find(([re]) => re.test(ln)); if (c) { flush(); cur = c[1]; } if (cur) buf.push(ln); }
  flush();
  const b0 = html.indexOf('<body>') + 6, b1 = html.indexOf('<script type="application/json"');
  out('tools/_body.html', html.slice(b0, b1).trim() + '\n');
  console.log('code split into src/, app.css, tools/_body.html');
}
